### ISSUE TITLE
Addition of back button

### ISSUE THREAD

**Issue by Salman-Inayat** [navidrome/navidrome#1003]
Wouldn't it be great to add a back button on player edit page. There are only two actions right now, save and delete. A user cannot go the previous page directly. User have to go to settings, then select player after which he can view player list. 

Currently, playerEdit page is as below

![image](https://user-images.githubusercontent.com/45660519/114056799-76821c00-98ab-11eb-9345-22b3d2e086fd.png)

Updated page should be 
![image](https://user-images.githubusercontent.com/45660519/114057140-c19c2f00-98ab-11eb-9f82-33899d08c5bf.png)

**Comment by deluan** [comment]
Hey @Salman-Inayat , thanks for the suggestion, but this is the convention for [React Admin](https://marmelab.com/react-admin-demo/#/customers). The user can simply use the browser's back button to go back to the previous page.

This same pattern can be seen in a lot of different web apps.

**Comment by Salman-Inayat** [comment]
@deluan I understand your point. But adding a back button would increase user experience.

**Comment by deluan** [comment]
> But adding a back button would increase user experience.

IMHO this is subjective... But I think if we want to add navigation buttons, we should add back and forth buttons, and in all views, maybe in the top bar, like Spotify:
<img width="839" alt="Screen Shot 2021-04-09 at 10 40 29 AM" src="https://user-images.githubusercontent.com/331353/114198394-45443300-9921-11eb-89ad-1dce5ae867f2.png">

**Comment by superfunk2000** [comment]
### Navigation arrows (like Spotify)

I like to use the "Install as app" feature. But then I miss the browser navigation buttons back and forward.
![image](https://user-images.githubusercontent.com/90634124/168532573-791a6c8b-189a-42d1-bfa1-55747eb5ae7b.png)

It would really be an advantage to introduce navigation buttons across the board, like Spotify is doing.
![Untitled-3](https://user-images.githubusercontent.com/90634124/168532724-afa1ec25-d71b-4453-b0e2-2792a79e7ceb.png)
