### ISSUE TITLE
Replace numerical literal 302 with constant http.StatusFound in server/app/serve_index.go

### ISSUE THREAD

**Issue by AeronCyther** [navidrome/navidrome#1004]
Instead of using a numerical status code, we should use the constant declared in net/http.

### Old
![Screenshot from 2021-04-08 21-17-54](https://user-images.githubusercontent.com/46657504/114057120-ed211880-98af-11eb-8f56-b9565d065d57.png)

### New
![Screenshot from 2021-04-08 21-20-25](https://user-images.githubusercontent.com/46657504/114057555-4721de00-98b0-11eb-96d0-db54cc4d3599.png)

**Comment by AeronCyther** [comment]
It's a quick fix

**Comment by deluan** [comment]
Fixed in #1006
