### ISSUE TITLE
Render SimpleList for xs screens in PlaylistList similar to AlbumListView

### ISSUE THREAD

**Issue by shishir610** [navidrome/navidrome#1008]
### Description

The playlist list is not responsive for xs screens since there is no conditional rendering of SimpleList from `/ui/src/common`

![image](https://user-images.githubusercontent.com/27198773/114085249-bc9ca700-98ce-11eb-9008-f121e4bc905a.png)
![image](https://user-images.githubusercontent.com/27198773/114085272-c7efd280-98ce-11eb-8e04-9ce667519d60.png)

### Expected Behaviour

The playlist list is supposed to be repsonsive like the AlbumListView shown below

![image](https://user-images.githubusercontent.com/27198773/114085410-f7064400-98ce-11eb-8431-fa7e7756f7b3.png)

### Steps to reproduce

1. Use Responsive Device Mode on any broswer
2. Go to Menu > Library > Playlists

### Platform information

 - Navidrome version: master branch
 - Browser and version: all browsers
 - Operating System: all

**Comment by armedev** [comment]
@deluan can i work on this.

**Comment by deluan** [comment]
I think @shishir610 wants to work on it, as he reported it

**Comment by armedev** [comment]
as I was waiting for a reply from @shishir610, I tried to design it for mobile views @deluan take a look at this,
https://www.figma.com/file/4eMY2IbN7rl4WJkJP4Qnkd/playlist_design?node-id=0%3A1

**Comment by shishir610** [comment]
@armedev Like @deluan mentioned, I opened the issue so that I could work on it. Thanks for the inputs, really appreciate it. I will keep in mind while making the changes.

**Comment by armedev** [comment]
ahh, thank you, also kindly modify the designs. any suggestions @deluan.

**Comment by shishir610** [comment]
Thanks, @armedev but the Owner and Date fields didn't seem necessary to me. I've pushed a commit that lists the playlist name, number of songs, and duration. Please do let me know if it's necessary, I can make a custom field and add the same.

**Comment by metalheim** [comment]
@deluan @shishir610 i think this is solved for quite some time now, right?
Playlist Overview and Playlist-List looks fine to me:

![image](https://user-images.githubusercontent.com/44159957/151340502-4cf0648e-ea7e-4ce6-88f9-e568b46e8a63.png)
