### ISSUE TITLE
Fixed Sidemenu for better UX

### ISSUE THREAD

**Issue by pkspyder007** [navidrome/navidrome#1016]
### Is your feature request related to a problem? Please describe.

We have a plan to implement Infinite scrolling to the UI and right now out Menu is scrolled off-screen with the albums see the screenshot attached below
![image](https://user-images.githubusercontent.com/19896788/114350380-c2241680-9b86-11eb-856b-c3781d86ceb8.png)

This is not a good UX on desktops as on mobile we get a toggle button while scrolling up which open the menu

![image](https://user-images.githubusercontent.com/19896788/114350764-46769980-9b87-11eb-996d-18b479cb69a4.png) 
![image](https://user-images.githubusercontent.com/19896788/114350812-55f5e280-9b87-11eb-93f0-6a04e9403c69.png)
 
### Describe the solution you'd like

I want to make the side menu stick to the left while scrolling on large screens.

### Additional context

Infinite scrolling issue #132

**Comment by pkspyder007** [comment]
@deluan I tried it on different resolutions and themes, it worked on them.
I just found a UI issue but that was already mentioned in issue #647.

**Comment by pkspyder007** [comment]
@deluan We discussed elaborately in discord and think that it is ok to have this behavior. 
A PR has been opened on React Admin to have a prop to control hide on scroll behavior. So if you have any suggestions please let me know.

**Comment by deluan** [comment]
Implemented in new React-Admin version 3.18.0. Fixed in 8444c28bed76e6f79408a99a99548931b692e4d1
