### ISSUE TITLE
Add a preference to disable external lookups

### ISSUE THREAD

**Issue by jvoisin** [navidrome/navidrome#102]
With LastFM integration ( #18 ) right around the corner, it would be nice to have a preference to disable external lookups: I'm not at ease with that my music player leaking information to third parties :/

**Comment by deluan** [comment]
I'll keep this in mind when implementing the integration. I added a comment in the Last.FM issue as a remainder about this. I'm closing this now, but feel free to reopen if you feel there's more to it than just Last.FM

**Comment by jvoisin** [comment]
There is `background: 'url(https://source.unsplash.com/random/1600x900?music)',` in  `/src/layout/Login.js:26` :)

**Comment by deluan** [comment]
Do you think this is worth turning off? I mean, it is not exposing any user data (well, only IP and time of access).

**Comment by jvoisin** [comment]
It would be great!

**Comment by deluan** [comment]
Ok, reopening this, will add an option in the configuration: `DisableExternalLookups`

**Comment by Code-Slave** [comment]
you could also add a config for a "splah" dir for custom images

**Comment by deluan** [comment]
Hey @jvoisin, take a look at the PR #154 and check if it is enough to close this issue. I think the login background is the only external lookup for now.

@Code-Slave I like your idea. Unfortunately the above PR does not implement that, it is just a simple configuration to avoid external lookups. 

Feel free to open a new feature request ticket to track the custom image folder idea

**Comment by jvoisin** [comment]
I was more thinking about a `NO_EXTERNAL_LOOKUP=True|False` preference, with the plain-colour background being automatically selected based on the theme, otherwise you'll end up with a ton of preferences for every single integration: `NO_LASTFM`, `NO_MUSICBRAINZ`, `NO_CHROMECAST`, …

**Comment by deluan** [comment]
The idea with the PR was to enable login background customization, as a first step to make it part of the theme.

This global flag you are suggesting could come later, when implementing these other kind of integration. Even then LastFM and MusicBrainz will be server side, and if you don't configure them, they won't work.

**Comment by balki** [comment]
It can be worked around by setting CSP/RP on the web server. However would be best to have direct support in navidrome. Below examples for caddy web server:

Below keeps the server private by not leaking the server URLs when clicking away via referrer header.

    header Referrer-Policy same-origin

Below keeps the client private by not loading external resources other than the domain hosted, 

    header Content-Security-Policy "default-src 'self' 'unsafe-inline' data: ;"

Can allow selected domains by adding to the above list:

    header Content-Security-Policy "default-src 'self' 'unsafe-inline' data: *.unsplash.com;"

doc: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

**Comment by jvoisin** [comment]
This isn't a proper solution, since it might break things.

**Comment by balki** [comment]
On Wednesday, March 17, 2021 8:16:08 AM EDT Julien Voisin wrote:
> This isn't a proper solution, since it might break things.

Yes, not a proper solution but works for now as the only external lookup is 
from unsplash.
