### ISSUE TITLE
Menu icon on the navbar positioning with the sidebar icons

### ISSUE THREAD

**Issue by JayKaku** [navidrome/navidrome#1026]
![image](https://user-images.githubusercontent.com/61429929/114512636-f535db00-9c56-11eb-9a36-2415326cbf34.png)

The Menu icon on the Navigation bar for the sidebar (top left corner) would look great if it were aligned in line with the icons below, let me your thoughts, I'll make the required changes.

**Comment by JayKaku** [comment]
I've created a pull request on the React-Admin Repo @deluan  https://github.com/marmelab/react-admin/pull/6161

**Comment by deluan** [comment]
Awesome! This reminds me that we need to spend some time upgrading to the latest React-Admin....

**Comment by JayKaku** [comment]
The pull request got merged, do update us as to when we plan to update it.
