### ISSUE TITLE
Feature Request: Sharing

### ISSUE THREAD

**Issue by TheFlatworm** [navidrome/navidrome#1029]
It would be wonderful to have sharing as referenced in #390.  An ability to select a song or album and have a link generated to share.  The link would access the music via a limited guest account so a user would not have to be set up to access the share.

**Comment by deluan** [comment]
Yes, this is one of the proposed GSoC projects: https://www.navidrome.org/docs/gsoc/#1-media-sharing

I'm gonna close this issue, as it is a duplcation of #748 , please subscribe to that issue to receive updates on its status
