### ISSUE TITLE
Spotify theme: Buttons in BulkActionsToolbar should have some space between them.

### ISSUE THREAD

**Issue by YashJipkate** [navidrome/navidrome#1031]
### Is your feature request related to a problem? Please describe.

The buttons in the BulkActionsToolbar appear too cramped, and the buttons even appear to overlap with each other.

### Describe the solution you'd like

It would be nice to have the buttons get some space between them. Maybe increasing the margin between the buttons might be a good idea.

### Describe alternative solutions that would also satisfy this problem

We can also look at some alternative forms of buttons, the current ones are too rounded, and therefore take up space of the neighbor. We can have a square button with just the round corners, or we can have something like the side-menu where the selection highlights

### Additional context

This is how the current BulkActionToolbar looks like in Spotify:
![Screenshot from 2021-04-14 15-11-29](https://user-images.githubusercontent.com/34203227/114691969-d35f5580-9d35-11eb-8c22-b699d19d1a48.png)

Whereas the following is from the theme Extra Dark:
![Screenshot from 2021-04-14 15-12-06](https://user-images.githubusercontent.com/34203227/114692101-f0942400-9d35-11eb-8f51-6aaa49f4b958.png)

**Comment by Dnouv** [comment]
@YashJipkate, how about having only the icon, in the toolbar, and as one hovers over the icon, the "Play now" or other button text will appear in the icon, something like the screenshot below
![image](https://user-images.githubusercontent.com/61188295/116364413-cce6d880-a821-11eb-90a2-73470ea6e4f2.png)

**Comment by YashJipkate** [comment]
The idea is nice but then the icons have to be accurately descriptive, like the profile icon or the camera icon in your ss (the previous one). One can guess its motive just by looking at them. But here if you see the 'Add to Playlist' and 'Play later' buttons, they look identical and might not be good UX. Even in players like Spotify or YT, they have full text. So unless there is some icon that expresses them better, I don't think this could work imo.

**Comment by Dnouv** [comment]
Yeah, the icons are not that much descriptive, ok then I will go ahead with adding margin in between icons; thanks for your feedback.
