### ISSUE TITLE
Pin the BulkActionsToolbar to the top.

### ISSUE THREAD

**Issue by YashJipkate** [navidrome/navidrome#1033]
### Is your feature request related to a problem? Please describe.

Say I am in a 50-item per page Song section, I select 2 songs to add to a playlist, but now I have to scroll all the way up to do it. 

### Describe the solution you'd like

I would like a fixed toolbar that appears quickly on the top of my screen so I can perform the actions. I think that will be quite handy.

Thoughts @deluan?

**Comment by deluan** [comment]
Not sure if this is a good enhancement.... Remember that every change we do to the look and feel of React Admin is more code to maintain and harder to upgrade, so small things like this may not be worth the hassle....

**Comment by YashJipkate** [comment]
Say if we add this feature to react-admin itself, would that be a good idea?

**Comment by certuna** [comment]
You can already add songs individually by using the triple-dot menu on the right, which is faster than clicking on two songs and scrolling up

**Comment by YashJipkate** [comment]
Yes, you can do that. But let's say you want to play 5 (or more) songs in a particular order, then it would be too much work (and slower). That's where the BulkActionsToolbar can come real handy, don't you think? Also it would be a good plus for infinite-scroll feature.

**Comment by deluan** [comment]
> Say if we add this feature to react-admin itself, would that be a good idea?

Yes, that would be better, let's see what they say about it

**Comment by YashJipkate** [comment]
@deluan this feature was given green light by the react-admin maintainers. See https://github.com/marmelab/react-admin/issues/6180.

A contributor has volunteered and hopefully he'll be sending a PR.
