### ISSUE TITLE
Change Menu Icon on toggle

### ISSUE THREAD

**Issue by pkspyder007** [navidrome/navidrome#1034]
To change the Menu Icon in app bar as the image below on toggle
![1_KwqSHfeILFT91L3jahO9UQ](https://user-images.githubusercontent.com/19896788/114999527-91621b00-9ebf-11eb-8253-e0f4024d65b1.png)

### Describe the solution you'd like

This [documentation](https://marmelab.com/react-admin/Theming.html#replacing-the-appbar) provides the basic of how to create a custom app bar with no hide on scroll behaviour
### Additional context

At present the menu icon just rotates on its axis which does not provide an idea about the current state of the sidebar.

https://user-images.githubusercontent.com/19896788/114999789-ccfce500-9ebf-11eb-8268-e5006d341be5.mp4

This is a bit on difficult side as we need to recreate the entire app bar including the features React Admin provide and for that this implementation would be really helpful. [React-Admin Appbar implementation](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/layout/AppBar.tsx)

**Comment by pkspyder007** [comment]
I am experimenting with this as there are some UI quirks related to custom app bar implementation.

**Comment by Rishabh-malhotraa** [comment]
I did something similar to [this](https://spotify-design-demo.netlify.app/). You can find the code [here](https://codepen.io/erikterwan/details/EVzeRP)

**Comment by pkspyder007** [comment]
@Rishabh-malhotraa The issue is to achieve this with react-admin Appbar component. 
One way I came up with was to write our own Appbar component from scratch. 
But that's something I want to avoid as it deviated us from react-admin and makes codebase hard to maintain. 

If you have any other suggestions please let is know.

**Comment by Dnouv** [comment]
@pkspyder007, maybe we could open a feature request issue on `react-admin` .

**Comment by pkspyder007** [comment]
@Dnouv I did mentioned few suggestion there. 
https://github.com/marmelab/react-admin/issues/6174

Let's see what they think about it.

**Comment by deluan** [comment]
Hey @pkspyder007, I don't think we need to change the menu icon on toggle. From what I read above, your motivation is:

> At present the menu icon just rotates on its axis which does not provide an idea about the current state of the sidebar.

I think showing a different icon for this is redundant, as the user can see the state by just looking the menu.

Anyway, thanks for opening the issue about making the AppBar always visible in React Admin's repo. I just implemented it now in 6ac2fefaf35443691e005661a25f11d8a5c626e

I'll close this now, but feel free to let me know if you have any other ideas.

**Comment by pkspyder007** [comment]
It's better that React Admin fixed this. 
We don't need to hack around it and add extra code to our system.
