### ISSUE TITLE
Make Albums grid view sortable without switching to list view first

### ISSUE THREAD

**Issue by upward4** [navidrome/navidrome#1035]
### Is your feature request related to a problem? Please describe.

The Albums grid view cannot be sorted, unless you first switch to list view and select the desired sort field.

### Describe the solution you'd like

I would like to be able to sort albums while in grid view, for example using a drop down control.

### Describe alternative solutions that would also satisfy this problem

I don't think there are alternative solutions to this. Maybe using a different type of control, but I think a simple drop down is the most appropriate.

**Comment by deluan** [comment]
We are planning to rewrite the Album Grid, and this may change. Can you please list the fields you want to sort on?

**Comment by oliveconstant** [comment]
I would personally like to sort on release date, but there are other fields that I think most users would like to sort on. For example, Apple Music can sort by:
 
- title
- recently added
- artist

As another example, iTunes can sort by:

- title
- genre
- year
- rating (0-5)

I also think there should be a way to switch between ascending and descending order. I find the way iTunes accomplishes this to be clean and effective:

![image](https://user-images.githubusercontent.com/77325055/115108573-88ca1d00-9f71-11eb-8ce1-45a7e9a267b6.png)

**Comment by oliveconstant** [comment]
As a side note, I think we should consider the possibility of sharing a single sorting control (e.g. dop-down button) between grid and list view.

**Comment by deluan** [comment]
Yeah, agree. The first implementation of Album browsing was based on Subsonic/Airsonic Album List views, and that's what you get in the left-side Albums menu:
- All (Sorted alphabetically)
- Random
- Favourites (marked with "Heart", or "Star" using a Subsonic client, sorted by when it was marked)
- Top Rated (5-star rating, sorted 5-1)
- Recently Added
- Recently Played (by playDate)
- Most Played (by playCount)

But I agree that adding a combo or another control to allow more flexible options is a better approach, and as I said, this will be taken into consideration when implementing a new Album Grid

**Comment by satyaarthchhabra** [comment]
Hi @deluan can i ork on this issue ??

**Comment by GeneralChauhan** [comment]
Hi !
Is the issue still open?

**Comment by GeneralChauhan** [comment]
Is this alotted to someone??

**Comment by GeneralChauhan** [comment]
oh, alright!
