### ISSUE TITLE
AUR package maintainer wanted

### ISSUE THREAD

**Issue by sumnerevans** [navidrome/navidrome#1037]
I no longer use Arch Linux on any of my main machines, thus I'm looking for someone to take over the active maintenance of the AUR package: https://aur.archlinux.org/packages/navidrome-bin/.

@deluan is listed as a maintaner, but AFAIK he doesn't use Arch Linux as his main driver either.

**Comment by BobRawr101** [comment]
I don't have /any/ experience in maintaining arch packages, but w/ some direction, I'd be willing/want to maintain the package.

**Comment by sumnerevans** [comment]
@BobRawr101 do you run Arch Linux as your primary distro?

**Comment by BobRawr101** [comment]
I use Manjaro, but I think it's close enough.

**Comment by sumnerevans** [comment]
That's great! I can give you the info you need to maintain the package. If you are on the Discord, DM me there. Otherwise, contact me via one of the methods listed at my website: https://sumnerevans.com/contact/

**Comment by deluan** [comment]
Maybe we could automate it with: https://github.com/guumaster/aur-publish-docker-action ?
It is being used by this project for example: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kafkactl

I could try to automate it, but I don't have a system to test AUR packages, nor the time to setup one...

**Comment by BobRawr101** [comment]
Username on AUR is lostpolaris

**Comment by sumnerevans** [comment]
Thank you @BobRawr101 for stepping up! I have transferred ownership over to you.
