### ISSUE TITLE
Warning: Missing translation in AlbumsList - favourites

### ISSUE THREAD

**Issue by aldrinjenson** [navidrome/navidrome#1038]
### Description
Opening albums - favourites throws up warnings in the console saying translations are missing

```
Warning: Missing translation for key: "[object Object]" 
QuickFilter@http://localhost:4533/static/js/main.chunk.js:4950:21
div
FilterFormInput@http://localhost:4533/static/js/0.chunk.js:139479:23
form
FilterForm@http://localhost:4533/static/js/0.chunk.js:139317:12
ReactFinalForm@http://localhost:4533/static/js/0.chunk.js:178669:15
EnhancedFilterForm@http://localhost:4533/static/js/0.chunk.js:139390:25
Filter@http://localhost:4533/static/js/0.chunk.js:138947:26
AlbumFilter@http://localhost:4533/static/js/main.chunk.js:1562:85
div
Toolbar@http://localhost:4533/static/js/0.chunk.js:31740:17
WithStyles@http://localhost:4533
```

### Steps to reproduce
Navigate to /album/starred

### Screenshots
![image](https://user-images.githubusercontent.com/53407417/115133155-a9eb4600-a023-11eb-9dd5-9d8d66273ca0.png)

**Comment by deluan** [comment]
This is caused by using an Icon as the filter label. It's a limitation of React-Admin: Even though it works, it shows this message in dev mode. We need to open an issue with React Admin similar to this: https://github.com/marmelab/react-admin/issues/4848
