### ISSUE TITLE
Login error in firefox 

### ISSUE THREAD

**Issue by aldrinjenson** [navidrome/navidrome#1039]
### Description
Trying to Log in for the first time in firefox throws up a securityError error saying that the operation is insecure. 
Works fine in Chrome.
Logging in for the [Navidrome demo site](https://demo.navidrome.org/app/), in new private window also shows the insecure message in the console:
`Uncaught (in promise) DOMException: The operation is insecure.`

### Steps to reproduce

1. Open firefox in incognito (private window)
2. Try to log in

### Platform information

 - Navidrome version: latest master
 - Browser and version: Firefox latest
### Additional information

Any other information that may be relevant or give context to the problem.

 - Screenshots 
  
![image](https://user-images.githubusercontent.com/53407417/115133402-8cb77700-a025-11eb-866c-f0ed869872c1.png)

Has got to do with serviceworker and caching it seems.
This may be of some use: https://stackoverflow.com/questions/58470055/unhandled-rejection-securityerror-the-operation-is-insecure-on-a-fresh-creat

**Comment by deluan** [comment]
Thanks! I pushed a "fix": catch the exception and shows it in console. I think clearing the service worker cache is not required anymore, needs to be validated
