### ISSUE TITLE
Add variables to clearly distinct between Navidrome instances.

### ISSUE THREAD

**Issue by NyaomiDEV** [navidrome/navidrome#1046]
### Is your feature request related to a problem? Please describe.

There is no way to clearly distinct between Navidrome instances.

### Describe the solution you'd like

In the configuration / environment:
- `instanceName` / `ND_INSTANCE_NAME` (`string`, defaults to `Navidrome`): The current instance's name; it will be displayed in the <title> tag and as a header in the login section (under the logo).
- `instanceLink` / `ND_INSTANCE_LINK` (`string`, defaults to empty): In the login section, the instance name can point to another webpage. This variable controls the URL. If empty, the instance name will not point to anything.
- `favicon` / `ND_FAVICON` (`string`, defaults to empty): Path to a custom icon to use as logo (login section) and favicon inside the Navidrome instance.

To credit the project better (optional)
- `Powered by Navidrome` as a subtitle under the sign in button (on the login screen). The `Navidrome` name could then be a link to the project website.

### Describe alternative solutions that would also satisfy this problem

`UIWelcomeMessage` could also satisfy this problem if we were to distinct between instances on login session only, but it would all look the same past authentication.

### Additional context

Having to manage and use multiple Navidrome instances is a nightmare, especially when each friend in a group has its own instance.

**Comment by metalheim** [comment]
Maybe we could also add a configuration option for `defaultTheme`?
It would also allow to visually separate instances from the login screen.

**Comment by deluan** [comment]
> Maybe we could also add a configuration option for `defaultTheme`?

This was introduced last week: https://github.com/navidrome/navidrome/commit/f63a912341c646bcdb97b35aa32ada8bc1db67cd

Docs for 0.42.0: https://deploy-preview-45--navidrome.netlify.app/docs/usage/configuration-options/#notes

It is already available in develop builds, and will be in the next release.

**Comment by deluan** [comment]
@AryToNeX thanks for the suggestion, that seems doable and relatively easy to implement.

> * `favicon` / `ND_FAVICON` (`string`, defaults to empty): Path to a custom icon to use as logo (login section) and favicon inside the Navidrome instance.

This may be challenging, as Favicon is not just one image, it has different resolutions and alpha configurations for different platforms, take a look at the current one: https://github.com/navidrome/navidrome/tree/master/ui/public

We can definitely replace it with one image, but it may not look good in some browsers/platforms.

**Comment by metalheim** [comment]
> > Maybe we could also add a configuration option for `defaultTheme`?
> 
> This was introduced last week: [f63a912](https://github.com/navidrome/navidrome/commit/f63a912341c646bcdb97b35aa32ada8bc1db67cd)
> 
> Docs for 0.42.0: https://deploy-preview-45--navidrome.netlify.app/docs/usage/configuration-options/#notes
> 
> It is already available in develop builds, and will be in the next release.

Awesome, works great!

**Comment by AryToNeX** [comment]
> > * `favicon` / `ND_FAVICON` (`string`, defaults to empty): Path to a custom icon to use as logo (login section) and favicon inside the Navidrome instance.
> 
> This may be challenging, as Favicon is not just one image, it has different resolutions and alpha configurations for different platforms, take a look at the current one: https://github.com/navidrome/navidrome/tree/master/ui/public
> 
> We can definitely replace it with one image, but it may not look good in some browsers/platforms.

Given that your project internally uses `ffmpeg`, and given a reasonably sized (512x, really) square icon with alpha, I don't see why you couldn't use the `cache/` folder to autogenerate all the different favicons to use within multiple platforms.

Sure, the only one problem would then be the `safari-pinned-tab.svg` icon. I do not know about how Safari handles pinned tabs without that icon, but I guess that would not be missed right away in case it doesn't show up (on customized Navidrome instances).

Sure, this would add `icotool` or equivalent library/tool as a runtime dependency.

**Comment by deluan** [comment]
We don't need to use `ffmpeg` for this: Go has good PNG library and there are small, pure Go, ICO encoders out there. I just think it is code that will be included in Navidrome that will be used once, if ever. I think this are static files that could be generated outside Navidrome. For ex: the current favicons were generated using the online site https://realfavicongenerator.net

Maybe we could recommend this site or a tool that generates the icons, and the proposed config option would point to the folder?

**Comment by AryToNeX** [comment]
Handling this internally could be better because this way you do not rely on other services that may be shut down at any moment; plus, it is really trivial and it works well within the intent of pointing the configuration variable to a PNG; but in any other case, laying down some code to do the image processing in a separate project is fine as well.

I'd also doubt that the code would then be used once if ever, since there are people who would set custom logos for their instances (come to think of boxes with multiple hosted services but a common theme around them, eg. japan pop music/anime).

At the end of the day, mine is just a suggestion and sure, having enough documentation will make it viable to manually prepare a folder with all the needed icons (but it will not be as fast and snappy as letting Navidrome do it internally).

**Comment by jvoisin** [comment]
The favicon thingy sounds overkill to me.
Simply having the *name* of the instance somewhere should be enough.

**Comment by C-Fu** [comment]
ND_INSTANCE_NAME would be awesome! I wanna have different servers for different libraries, eg. Western/Hollywood files that prefer lastfm, and local stuff that prefer spotify for instance.
