### ISSUE TITLE
Subsonic API Multi disk view

### ISSUE THREAD

**Issue by SenorSmartyPants** [navidrome/navidrome#1049]
### Is your feature request related to a problem? Please describe.

Option to display a individual disks in a boxset, instead of the current list of all tracks.
I saw this mentioned in #272 but it was crossed out. Was this decided against or just not implemented?

### Describe the solution you'd like

Display sub folders for each disk in a boxset, using disk subtitle for folder name (and year of release). Bonus material sometimes has a different release date than the original CD.

### Additional context

DSub does not have a way to provide separation of disks in the track list (other than just the track number). I would like to be able to select play all on 1 disk in a box set easily.

**Comment by deluan** [comment]
As the UI does not support folders, the best we can do is what is already implemented. With the current implementation you can see the tracks grouped by discs in a boxset, play/shuffle one disc and so on. The image in the mentioned issue #272, is the what you see if the album is properly tagged with disc subtitle tags.

The crossed-out item in that issue is related to your "Additional context": To allow Subsonic clients like DSub to show discs as subfolders in a boxset, _if using browse by folder_ (browse by tag does not support it). I may implement it in the future.

**Comment by SenorSmartyPants** [comment]
Yes, I'm only asking about the subsonic API. No need to change the Navidrome Web UI.

Consider this my +1 for _browse by folder_ to show discs as subfolders.

**Comment by certuna** [comment]
The Subsonic API already supports DiscNumber (it's included in the `Child` ComplexType), it's up to the client to subdivide an album into discs. What could Navidrome do?

**Comment by KingDuckZ** [comment]
It would be nice if the boxset displayed the cover art for the corresponding disc too, for albums that have a different cover for each disc!

Anyways I noticed the spinning disc in the play bar already displays the correct cover, so thank you for that :)

The grouping itself works fine with me in Strawberry (and also the cover art for each song seems to be the correct one).

**Comment by certuna** [comment]
In principle songs can have individual covers in the Subsonic API, but not sure how Navidrome handles this in the DB?

**Comment by deluan** [comment]
> The Subsonic API already supports DiscNumber (it's included in the Child ComplexType), it's up to the client app to subdivide an album into discs. If it doesn't do that, what could Navidrome do?

@certuna,  I agree it is up to the client to do The Right Thing ™️ , but some simply don't. In my use case, DSub correctly displays shows the tracks in order, but does not make a clear separation between discs:
![Screenshot_20210506-102533](https://user-images.githubusercontent.com/331353/117315269-87479280-ae55-11eb-9b04-2c7fc99cb86b.png)

My idea is to leverage the "browse by folder" API, which would allow an album to have "subfolders" (the discs), and each could have its own cover (answering @KingDuckZ question) 

> In principle songs can have individual covers in the Subsonic API, but not sure how Navidrome handles this in the DB?

From Subsonic API `getCoverArt` docs:
> id - The ID of a song, album or artist.

So yes, if the client calls this endpoint passing a song ID, it will return the embedded cover of that song, if available. It falls back to the album cover.

**Comment by SenorSmartyPants** [comment]
Any updates on the possibility of implementing the "Browse by folder" option.

**Comment by deluan** [comment]
I took a look, it is not that simple, but easier to implement than browse-by-folder itself. I'll try to implement it after the next release

**Comment by SenorSmartyPants** [comment]
@deluan any updates on this?

**Comment by SenorSmartyPants** [comment]
This is a feature request, and I still value it as an easy way to play a single disk from a multi disk album in subsonic clients.

**Comment by deluan** [comment]
Update: I'm revisiting the DB schema to support multiple folders, and will try to squeeze this in. No promises on timeline, though.

**Comment by SenorSmartyPants** [comment]
This is a feature request and I would still find it valuable and hopefully others would as well.

**Comment by deluan** [comment]
Hey @SenorSmartyPants are you still using DSub? Symfonium and Tempo both have a clear separation of discs in an album, and soon OpenSubsonic clients will display disc titles as well:

- https://opensubsonic.netlify.app/docs/responses/disctitle/
- https://github.com/navidrome/navidrome/commit/2c9035fdd02566a551b65c83cd288591faaf7b7a

So, can we close this, as the OS discTitle attribute is already supported by Navidrome?

**Comment by SenorSmartyPants** [comment]
I am still using DSub. I've been checking out Ultrasonic but haven't made that my daily driver yet as I have some issues with it/getting used to it.
