### ISSUE TITLE
[Feature request] CLI tool to show metadata(tags) as read by navirdrome

### ISSUE THREAD

**Issue by balki** [navidrome/navidrome#1050]
Before editing the tags, it would be good to see what are the tags needed by navidrome and what their current values are. I created a crude version: https://gitlab.com/balki/naviextract/-/blob/main/naviextract.go
However it does not show the pictures and does not include other ways tags are processed by navidrome.

**Comment by certuna** [comment]
Probably easier to do that in a SQL editor/viewer?

**Comment by balki** [comment]
The idea is to view the tags before adding to navidrome to make sure everything is good.
