### ISSUE TITLE
[Feature Request] Lower Default Volume

### ISSUE THREAD

**Issue by xnaas** [navidrome/navidrome#1052]
### Is your feature request related to a problem? Please describe.

The first time you start audio in the web interface, it can be quite deafening.

### Describe the solution you'd like

Either:
* A lower default volume to begin with
* A configurable default volume through an environment variable

### Describe alternative solutions that would also satisfy this problem

Simply having the first-time volume put into `localStorage` as something lower than 100% would be fantastic, if nothing else.

### Additional context

[Reddit discussion link.](https://www.reddit.com/r/navidrome/comments/mxsmxs/feature_request_default_volume/)

**Comment by jvoisin** [comment]
This seems to be an issue with your operating system volume settings.

**Comment by certuna** [comment]
Yeah I'm a bit puzzled by this - is Navidrome louder than other websites?

**Comment by deluan** [comment]
Hey @xnaas maybe the issue you are experiencing is related to this? https://github.com/lijinke666/react-music-player/issues/379

**Comment by xnaas** [comment]
@deluan: maybe, maybe not? I'm not sure if it's quite the same issue or not. I don't know if that change would resolve full logouts as well as just closing the player.

**Comment by deluan** [comment]
Hey @xnaas, after a big refactor in the Player state management code, I was able to set a default value. Please check if this solves the issue for you. If not, feel free to reopen the issue.

**Comment by xnaas** [comment]
@deluan: Is this a change that's already pushed to a released version, or do I need to build from source to test?

**Comment by deluan** [comment]
It is in the latest dev build: https://github.com/navidrome/navidrome/actions/runs/1002861479 (click on the _binaries_ artifact at the bottom). Also in Docker, by using the tag `deluan/navidrome:develop`. 

But if you prefer to wait for a release, thats fine. Should be end of this month.

**Comment by xnaas** [comment]
> Version: | 0.44.1-SNAPSHOT (b34d77f8)

Still quite loud, but it is technically lower. Would definitely love if this was configurable via an Environment Variable or some such. 😅

**Comment by deluan** [comment]
Yeah, this is due to the way the React-Player implements logarithmic volume: https://github.com/lijinke666/react-music-player/pull/266 Will probably change it to be really 50%

Adding a config option for this is adding more code to maintain and unless there are more users affected by it, it is not worth (IMHO). Hope reducing it to real 50% will make it better

**Comment by xnaas** [comment]
> Yeah, this is due to the way the React-Player implements logarithmic volume: lijinke666/react-music-player#266 Will probably change it to be really 50%

Ah, makes sense. Thanks for the info.

> Adding a config option for this is adding more code to maintain and unless there are more users affected by it, it is not worth (IMHO).

Fair enough; it's your project, not mine. :D

> Hope reducing it to real 50% will make it better

Definitely will. Thanks again. :)
