### ISSUE TITLE
Extract urls from comments and link them to their correspoding sites

### ISSUE THREAD

**Issue by rochakjain361** [navidrome/navidrome#1053]
### Description
Metadata in the comment field of the audio file consists of a URL to the music website when being imported from that site. It would be nice to detect those URLs from the comments and link them to their respective site.
(Songs when downloaded from music sites like Jamendo, etc., would provide URL in comments description.)

### Screenshot

![Screenshot from 2021-04-25 17-34-53](https://user-images.githubusercontent.com/57208018/115994203-a3486a00-a5f3-11eb-9431-69b216123cdb.png)

The expected result is to have a hyperlink to the music website. In this case for example to http://www.jamendo.com.

**Comment by metalheim** [comment]
Generally such links shouldn't go in the comment field, but in the dedicated tag field like WXXX, WOAF or WOAS.

https://hilfe.mp3tag.de/main_tags.html
(page is German, but the table is self explanatory) 

But since it's rather common to have links in comments and navidrome does not read WXXX and alike we should to what you're supposing.

**Comment by certuna** [comment]
Yeah I know, but taggers (and players) are notoriously bad at supporting these URL fields, so everyone just dumps them in the `COMMENTS` field.

**Comment by metalheim** [comment]
Easiest would probably be a URL-detection in javascript clientside with a regex similar to

`(https?:\/\/)?[\w\-~]+(\.[\w\-~]+)+(\/[\w\-~@:%]*)*(#[\w\-]*)?(\?[^\s]*)?`

**Comment by metalheim** [comment]
@dheerajdlalwani there is an open PR from @moulinapradhan of this issue linked.
I don't know if he/she plans to finish this pr, maybe drop a message?

**Comment by vian9** [comment]
Can I get the further details. I would like to work on this issue. So can you pinpoint something in code which I can look at?

**Comment by deluan** [comment]
Sorry @vian9, but this is being worked by @dheerajdlalwani at the moment. Please reach out to me in Discord so I can try to find something for you to work on

**Comment by deluan** [comment]
Hey @MoulinaPradhan, sorry for the delay. I added some comments in your PR

**Comment by vian9** [comment]
Yeah Sure @deluan can I have your discord username to send request so that I can reach out to you?

**Comment by Udit-takkar** [comment]
@deluan  Can I work on this one? this seems to be abandoned

**Comment by deluan** [comment]
This one is being implemented by @dheerajdlalwani (right?)

**Comment by dheerajdlalwani** [comment]
Yes.

**Comment by dheerajdlalwani** [comment]
I am really sorry for keeping this one waiting...
Will be completed within this week.

**Comment by pavithranair** [comment]
@deluan looks like this issue is still open. Could I give it a shot?

**Comment by dheerajdlalwani** [comment]
Hey @pavithranair , do go ahead. Due to some personal issues, I wasn't able to complete it.

**Comment by GeneralChauhan** [comment]
is anyone working on it?

**Comment by deluan** [comment]
Thanks to anyone who collaborated on this.
