### ISSUE TITLE
[PWA] status bar doesn't match theme color

### ISSUE THREAD

**Issue by guim31** [navidrome/navidrome#1063]
I tried the new spotify-ish theme, i find it really great, but when I install Navidrome as a PWA... The status bar on top of my phone is blue... 🤔 

![OfaKePN](https://user-images.githubusercontent.com/331353/117899130-7dc68c00-b294-11eb-9ca2-1c3e6f56cfb3.jpeg)

**Comment by deluan** [comment]
@certuna Can you reproduce this in your environment? Maybe this is caused by the `theme-color` in `manifest.json`: 
https://github.com/navidrome/navidrome/blob/master/ui/public/manifest.json#L9

If that's the case, it is time to make it a template (as we discussed in the beginning of the PWA implementation)

**Comment by certuna** [comment]
I cannot reproduce this on iPhone and iPad (status bar is black as usual), but I don't have an Android phone here.

Templating is nice (also brings the advantage to rename the app to the servername), but I don't know if the manifest.json gets reloaded when you change the theme though - another possibility is choose a neutral colour for it (black/white/grey)?

**Comment by Dnouv** [comment]
@deluan, I was able to reproduce the same; the notification bar was blue.

**Comment by deluan** [comment]
@Dnouv can you please try changing the `theme-color` in the `manifest.json` file and see if it affects the notification bar color?

**Comment by Dnouv** [comment]
I tried varying the color as suggested, but it did not affect the notification bar color. However, I tried something extra, just playing around with `index.html` (ui/public/index.html); by varying the color of `content` in the following line of code, the notification bar color was changed successfully.
`<meta name="theme-color" content="#ffffff">`
If there is anything else I need to do, please feel free to comment. Thank you!

**Comment by metalheim** [comment]
It seems to be different for Android/chrome (possibly all chromium-based renderers) and Apple/Webkit:

- Android takes the `meta` tag `theme-color` with `content ` attribute set to the color as @Dnouv stated
- Apple takes another `meta `tag called `apple-mobile-web-app-status-bar-style` and only allows three values for `content`
   * `default` (black text on white bg)
   * `black` (white text on black bg)
   * `black-translucent` white text on the background-color of the HTML body (?)

https://developers.google.com/web/updates/2015/08/using-manifest-to-set-sitewide-theme-color
https://medium.com/appscope/changing-the-ios-status-bar-of-your-progressive-web-app-9fc8fbe8e6ab
https://codeburst.io/progressive-web-apps-customize-status-bar-23c4b2de590f

**Comment by certuna** [comment]
Hah, I would've thought that's the kind of stuff PWA's would do in the `manifest.json` but it's still in `index.html`. Good for us I guess, that means the manifest doesn't need to be changed when the theme changes.

**Comment by Dnouv** [comment]
So @certuna, will we change the `meta theme-color` for each theme or going for another solution.

**Comment by certuna** [comment]
It appears that's the way to go, yeah. Sadly I'm not good enough with javascript to code that myself.

**Comment by Dnouv** [comment]
Ok, then I will give it a try.
