### ISSUE TITLE
Spotify-ish theme paging not highlighting current page

### ISSUE THREAD

**Issue by blunderberg** [navidrome/navidrome#1066]
### Description

Spotify-ish theme paging not highlighting current page

### Expected Behaviour

Current page to be highlighted (as is on other themes)

### Steps to reproduce

1. Click "Next" or select a specific page at the bottom of Albums/All list

### Platform information

 - Navidrome version: v0.42.0
 - Browser and version: Microsoft Edge Version 90.0.818.46 (Official build) (64-bit) (Navidrome installed as app)
 - Operating System: Windows 10 Pro client connecting to Ubuntu 20.04 server running Docker container

### Additional information

Spotify-is theme page 5
![image](https://user-images.githubusercontent.com/83293651/116356889-6f0cbd80-a82e-11eb-8def-eaa151cb7c0a.png)

Extra Dark theme page 5
![image](https://user-images.githubusercontent.com/83293651/116356535-fa398380-a82d-11eb-98df-f703486c0852.png)

**Comment by samarsault** [comment]
Thank you for pointing this out.  Fixed in https://github.com/navidrome/navidrome/pull/1068
