### ISSUE TITLE
Spotify-ish theme shows Navidrome logo with incorrect display ratio on login screen (not 1:1)

### ISSUE THREAD

**Issue by blunderberg** [navidrome/navidrome#1072]
### Description

The Navidrome logo (blue record) appears with incorrect display ratio (not 1:1) when using the Spotify-ish theme - image width is less than height as compared to other themes

### Steps to reproduce

Change the theme to Spotify-ish, log out, then navigate to /app/#/login

### Platform information

 - Navidrome version: v0.42.0
 - Browser and version: any
 - Operating System: any

### Additional information

Spotify-ish theme:
![image](https://user-images.githubusercontent.com/83293651/116773592-babaa380-aa88-11eb-998d-308a70139797.png)

All other themes:
![image](https://user-images.githubusercontent.com/83293651/116773576-a676a680-aa88-11eb-99a7-f9b25cba84da.png)

**Comment by deluan** [comment]
Thanks for reporting. This was fixed in https://github.com/navidrome/navidrome/commit/0d409e37e2aa9a5b0d15db5bb8db795e2f8f4271 and will be in the next release.
