### ISSUE TITLE
Ignore files from Recycle Bin in Windows

### ISSUE THREAD

**Issue by arg274** [navidrome/navidrome#1074]
### Description

Navidrome seems to pick up files from the Recycle Bin in Windows since the folders are not blacklisted.

### Expected Behaviour

Ignore any file in Recycle Bin so that trashed files don't appear in ND.

### Steps to reproduce

1. Let ND scan for media files via any of the supported means.

### Platform information

 - Operating System: Windows 10 x86_64 binary

### Additional information

The folder for recycle bins are usually named `$RECYCLE.BIN` and are located at the root of a drive. So, if ND is pointed to scan from a root, it will inevitably pick up these folders. Folder name is case-insensitive (i. e. they can be named `$Recycle.Bin` as well).

**Comment by metalheim** [comment]
Would it be feasible to add a file called ".ndignore" in the recycle bin folder?

**Comment by arg274** [comment]
> Would it be feasible to add a file called ".ndignore" in the recycle bin folder?

I don't think that should be the recommended approach. There might be some hacky solution that I'm not aware of but the Recycle Bin isn't really meant to be a place for users to create files in.

**Comment by metalheim** [comment]
Agree, Come to think about it, it's a bad idea, even if it worked, it could get easily deleted..

**Comment by Uatschitchun** [comment]
Why would one add a system's root as source?

**Comment by arg274** [comment]
> Why would one add a system's root as source?

Not sure where you're getting that from. Windows keeps recycle bin per partition/drive. It's not an anomaly for me (or anyone using Windows, as a matter of fact) to dedicate one drive to music and point ND towards the root of that drive, especially since ND doesn't support multi-libraries yet.

**Comment by JayKaku** [comment]
> ### Description
> Navidrome seems to pick up files from the Recycle Bin in Windows since the folders are not blacklisted.
> 
> ### Expected Behaviour
> Ignore any file in Recycle Bin so that trashed files don't appear in ND.
> 
> ### Steps to reproduce
> 1. Let ND scan for media files via any of the supported means.
> 
> ### Platform information
> * Operating System: Windows 10 x86_64 binary
> 
> ### Additional information
> The folder for recycle bins are usually named `$RECYCLE.BIN` and are located at the root of a drive. So, if ND is pointed to scan from a root, it will inevitably pick up these folders. Folder name is case-insensitive (i. e. they can be named `$Recycle.Bin` as well).

Apologies for being out of context but could you tell me how exactly did you setup navidrome for windows

**Comment by deluan** [comment]
@JayKaku , it is better to ask this in our Discord channel. Also check the docs for setting up the environment: https://www.navidrome.org/docs/developers/dev-environment/

**Comment by arg274** [comment]
This is still an issue and I still have to empty my bin before doing a Navidrome scan to avoid unintended files from being added, not sure what extra detail to provide.

**Comment by deluan** [comment]
@arg274 I think I got it. Can you please test it?

**Comment by arg274** [comment]
@deluan Yep, seems to have fixed it.
