### ISSUE TITLE
Is EnableTranscodingConfig not respected?

### ISSUE THREAD

**Issue by KingDuckZ** [navidrome/navidrome#1075]
### Description

This is my current config file:

```
# additional configuration options can be seen
# https://www.navidrome.org/docs/usage/configuration-options/#available-options
MusicFolder = "/data/airsonic/audio"
DataFolder = "/data/navidrome"
BaseURL = "/navidrome"
ScanInterval = "6h"
RecentlyAddedByModTime = true
EnableTranscodingConfig = false
Address = "127.0.0.1"
Port = 4533
TranscodingCacheSize = "2GB"
ImageCacheSize = "300MB"
IgnoredArticles = "The El La Los Las Le Les Il Lo I Gli"
SearchFullString = true
EnableFavourites = true
EnableStarRating = true
```
but in the admin UI I keep getting the security message saying that ND_ENABLETRANSCODINGCONFIG is enabled. I honestly don't know how to verify if the environment variable is really set or not, but to the best of my knowledge it should be unset. I finally fixed this problem by adding `Environment=ND_ENABLETRANSCODINGCONFIG=false` to my systemd unit file. So is navidrome ignoring the setting in the toml file?

### Expected Behaviour

I expect that the security warning in the UI transcoding menu disappears when `EnableTranscodingConfig = false`

### Steps to reproduce

1. Open the config file
2. Set `EnableTranscodingConfig = false`
3. Go to UI transcoding settings
4. See warning

### Platform information

 - Navidrome version: 0.42.0 (f1bd736b)
 - Browser and version: Firefox v78.10
 - Operating System: Archlinux using navidrome-bin package from AUR

### Additional information

Any other information that may be relevant or give context to the problem.

 - Screenshots (if applicable)?
 - Logs? 
 - Client used?

**Comment by deluan** [comment]
This flag is already false by default. If it says it is enabled in the UI, you may have it configured somewhere. If you change loglevel to `debug` you should see what it is using, something like this when starting Navidrome:
```
| |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
\_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
                 Version: 0.42.0-SNAPSHOT (f1bd736b)

Loaded configuration from '/Users/deluan/Development/navidrome/navidrome.toml': &conf.configOptions{
    ConfigFile:                 "/Users/deluan/Development/navidrome/navidrome.toml",
....
    BaseURL:                    "",
    EnableTranscodingConfig:    false,
    EnableDownloads:            true,
....
```

These values can be loaded from the config file or env vars, this is result of merging both. Try removing the change in the systemd unit, changing the loglevel and check this value in the logs

**Comment by KingDuckZ** [comment]
I tried that and... now it says it's set to false and the warning in the web UI is gone :/ I don't know what happened, I'm fairly sure I did change the setting and restart the daemon last time, but maybe I made some mistake somewhere! Anyways I think this can be closed. I'll bump this thread if I see the problem happening again!
