### ISSUE TITLE
Have Search Also Search For Songs in Playlists

### ISSUE THREAD

**Issue by TheFlatworm** [navidrome/navidrome#1077]
I know there may be work in revamping the search bar into a universal search across all categories - ALBUMS, ARTISTS, ALBUM ARTISTS, and SONGS.  If not too much trouble would it be possible to return results of matches in playlists, so that playlist names would be listed if a song in question is in that playlist?

**Comment by deluan** [comment]
Good call! Please add this as a comment in #468, so we can have all ideas and requirements concentrated in one place.
