### ISSUE TITLE
Clicking "play next" on a track while tracks are playing starts the play queue over from track 1.

### ISSUE THREAD

**Issue by SteveDinn** [navidrome/navidrome#1084]
### Description
Clicking "Play Next" on a track from my library while there is music playing will correctly add the track to the next position in the play queue, but it will also reset the play queue to the beginning of track 1. 

Further, if the play queue is paused, "Play Next" will reset to the beginning of Track 1 and start playing! If the play queue was paused, it should remain paused.

"Play Later" performs (I assume) a very similar action, but playback is not affected.

### Expected Behaviour
The track should be added as the next item in the play queue, but the play queue should be otherwise unaffected.

### Steps to reproduce

1. Add multiple tracks to the play queue.
2. Start the play queue playing on a track other than the first one.
3. Click on the vertical three-dot menu on a track and select "Play Next".
4. See that the new track is added in the correct position, but playback is reset to the first track in the play queue.

### Platform information

 - Navidrome version: 0.42.0 (f1bd736b)
 - Browser and version: Chrome Version 90.0.4430.93 (Official Build) (64-bit)
 - Operating System: Windows 10

**Comment by YashJipkate** [comment]
Thanks for reporting this. This is actually a known issue with the Jinke player that Navidrome uses.

You can track #650 for updates on this.

**Comment by SteveDinn** [comment]
Yep, that is exactly my issue. I even searched and didn't find anything matching. I guess I need better keywords. I'll close this one then.
