### ISSUE TITLE
Set scan time for new music

### ISSUE THREAD

**Issue by KingDuckZ** [navidrome/navidrome#1085]
### Is your feature request related to a problem? Please describe.
Is it possible to set a time for when a music scan should be complete? I'd like it to be done in the night, simply because I like finding the music I added the day before when I wake up in the morning. I have set `ScanInterval = "24h"` but I'm not sure at what time of the day the 24h timer will trigger

### Describe the solution you'd like

If there is no way yet, then something as simple as a `TimerBaseTime = <0-23>` in the settings would do. So for example:

```
TimerBaseTime = 4
ScanInterval = 24h
```

means every day at 4am, and with ScanInterval set to 12h it'd mean both at 4am and 4pm. I don't think it's necessary to have higher granularity than hours, but if needed then the parameter could accept a 24h format sttring, like "4:00" for 4am, and "16:23" for 4:23pm.

### Describe alternative solutions that would also satisfy this problem
I don't know, that's why I'm asking! :)

**Comment by deluan** [comment]
Thanks for the suggestion. I think a better approach is to allow a [cron](https://en.wikipedia.org/wiki/Cron)-like configuration. I'll think about it.

**Comment by KingDuckZ** [comment]
Thanks @deluan, looking forward to it! :) In the meantime as a workaround yesterday I tried modifying navidrome.db manually with: `update property set value=1620097200000 where id='LastScan-/data/airsonic/audio';` and I expected the next scan would happen today at that time (so just 24h later), but unfortunately it didn't work. Today I found that timestamp got set to 1620121802099 which is only a few hours after the timestamp I set, so it means the scan ran immediately...?

**Comment by deluan** [comment]
Maybe you changed the DB while Navidrome was up and running? Anyway, with the latest release (0.42.1) you can disable the `ScanInterval` (set it to `0`) and add an entry to your crontab like this:
```
0 5 * * * pkill -USR1 navidrome
```

And it will trigger a scan every morning at 5am. (of course assuming you are using a Linux/Unix system)

**Comment by KingDuckZ** [comment]
Thanks, I'll try that as soon as 0.42.1 hits AUR.
I tried again with the database value hack, I can confirm navidrome was not running when I made my change. The edit was entered correctly (database's sha1 changed), but then navidrome immediately set it to the current timestamp as soon as I started it again. Not that it matters that much if your trick with cron works, but still I don't think the directory should be scanned outside the update intervals.

**Comment by deluan** [comment]
Yeah, the way that the periodic scan works today is: it do a scan at start-up, then it runs scans every ScanInterval past that. So changing the LastScan in the database will not work.

What you can do while waiting for 0.42.1 is to set ScanInterval to some humongous number, like `87600h` (10 years). The cronjob will work and you surely upgrade Navidrome before 10 years :)

**Comment by deluan** [comment]
You can now specify the cron schedule in a new config option , `ScanSchedule`, which superceeds the (now deprecated) `ScanInterval`, examples:
```toml
ScanSchedule = "30m"        # Every 30 minutes, same syntax as ScanInterval
ScanSchedule = "@every 30m" # Same as above
ScanSchedule = "0 5 * * *"  # Once a day at 5 am
ScanSchedule = "@daily"     # Once a day, midnight
```

For more options and syntax, see https://pkg.go.dev/github.com/robfig/cron#hdr-CRON_Expression_Format

This will be in next release (0.43.0)
