### ISSUE TITLE
Recently played and Most played menus don't get updated

### ISSUE THREAD

**Issue by KingDuckZ** [navidrome/navidrome#1088]
### Description

When playing something in an external player such as Ultrasonic or Strawberry, Navidrome seems oblivious to it and both the Recently played and Most played views don't get updated. This makes them pretty irrelevant as the information they show is out of sync with real usage.

### Expected Behaviour

I expect the Recently played and Most played views to get updated when playing music from any client, be it the web UI or strawberry or anything else.

### Steps to reproduce

1. Open Ultrasonic or Strawberry or any other client that is not the web UI
2. Play some song
3. Go to navidrome's web UI
4. See how Recently Played and Most played are unaffected

### Platform information

 - Navidrome version: 0.42.0 (f1bd736b)
 - Browser and version: Firefox 78.10.0
 - Operating System: Gentoo (client) / Arch (server)

### Additional information

Any other information that may be relevant or give context to the problem.

 - Screenshots (if applicable)?
 - Logs? server logs do show correctly songs being transcoded and sent out
 - Client used? Ultrasonic 2.20.0 / Strawberry 0.9.3

**Comment by deluan** [comment]
For Navidrome to register the plays in Subsonic clients, they need to have Scrobble on (even though Last.FM scrobbling is not available yet). Please see https://github.com/navidrome/navidrome/issues/593#issuecomment-715646271

**Comment by deluan** [comment]
Not sure about Strawberry, but Ultrasonic has a setting for this:
<img width="469" alt="Screen Shot 2021-05-05 at 11 33 59 AM" src="https://user-images.githubusercontent.com/331353/117168203-f198fe00-ad95-11eb-993a-a5c42e68689c.png">
