### ISSUE TITLE
Feature Request: Add a configuration option or UI element to sort albums in artist detail page

### ISSUE THREAD

**Issue by TheWrathKing** [navidrome/navidrome#1093]
### Is your feature request related to a problem? Please describe.

When selecting an artist, the albums in the artist detail pages are always displayed oldest first thus having to navigate through, sometimes many, pages before being able to play the latest release of that artist.

### Describe the solution you'd like

Having a configuration option to choose the sort order of albums in artist detail pages (NewestAlbumFirst or something like that)

### Describe alternative solutions that would also satisfy this problem

Having a UI element to toggle the sort order

**Comment by certuna** [comment]
Will probably be part of the Artist page: https://github.com/navidrome/navidrome/issues/961
