### ISSUE TITLE
Incorrect subsonic API implementation (getBookmarks)

### ISSUE THREAD

**Issue by Omnia89** [navidrome/navidrome#1099]
### Description

Hi, I was testing the feature to save and restore bookmarks from an android client (ultrasonic), but the retrieving don't work, so I opened an issue in the ultrasonic repo, but they responded me that the cause seems to be an incorrect implementation of the json API: [ultrasonic-454](https://github.com/ultrasonic/ultrasonic/issues/454#issuecomment-834084884)

In short, the `entry` field doesn't need to contain an array of object, but only a single object.
I couldn't find any resource about the json API (only xml) to find if it's correct their assumption.

### Expected Behaviour

To see the list of bookmarks

### Steps to reproduce

1. Download [ultrasonic](https://play.google.com/store/apps/details?id=org.moire.ultrasonic)
2. Connect to your server
3. Open left menu and click "Bookmarks"

### Platform information

 - Navidrome version: 0.41.0
 - Operating System: Armbian 21.02.3 Buster

### Additional information

See [ultrasonic-454](https://github.com/ultrasonic/ultrasonic/issues/454#issuecomment-834084884)

Think they are related: #499 #245

**Comment by metalheim** [comment]
The xml response seems to be in the exact format that subsonic provides in their [API documentation](http://www.subsonic.org/pages/inc/api/examples/bookmarks_example_1.xml): 

In my understanding, looking at the XML, Ultrasonic is correct. `bookmarks` should contain an array of `bookmark`, but a single `bookmark` only needs to have one entry.

**Comment by deluan** [comment]
Ops, my bad. Didn't have a JSON client when testing this, only XML ones. The fix will be in next release (end of this month)

If you want to give it a try and don't mind living in the edge, you can try the latest development build (should be available in the next 20 minutes)

**Comment by deluan** [comment]
Thanks @metalheim. Will close this now.

@Omnia89 feel free to reopen if you have any other concerns.
