### ISSUE TITLE
openSUSE package request

### ISSUE THREAD

**Issue by NYCJames** [navidrome/navidrome#1100]
>If you can’t find a pre-built binary for your platform, you should open an issue in the project’s GitHub page

I am interested in a package/pre-built binary for openSUSE

**Comment by deluan** [comment]
Hey, thanks for giving Navidrome a try.

For the binaries, have you tried downloading one for you platform, from the [release page](https://github.com/navidrome/navidrome/releases/tag/v0.42.1)? Those binaries should work on any Linux distro, as they are statically linked and self contained.

In terms of packages, we don't provide packaging for any specific OS or platform, although some are [created and maintained by the community](https://www.navidrome.org/docs/installation/packages/). 

I don't know SUSE at all (never used it), but I'm assuming that the basics for setting up Navidrome as a service would be similar to [Ubuntu/Debian](https://www.navidrome.org/docs/installation/ubuntu-linux/) or [CentOS](https://translate.google.com/translate?sl=zh-CN&tl=en&u=https://blog.northtower.top/index.php/archives/12/), no?

**Comment by NYCJames** [comment]
> Hey, thanks for giving Navidrome a try.
> 
> For the binaries, have you tried downloading one for you platform, from the [release page](https://github.com/navidrome/navidrome/releases/tag/v0.42.1)? Those binaries should work on any Linux distro, as they are statically linked and self contained.
> 
> In terms of packages, we don't provide packaging for any specific OS or platform, although some are [created and maintained by the community](https://www.navidrome.org/docs/installation/packages/).
> 
> I don't know SUSE at all (never used it), but I'm assuming that the basics for setting up Navidrome as a service would be similar to [Ubuntu/Debian](https://www.navidrome.org/docs/installation/ubuntu-linux/) or [CentOS](https://translate.google.com/translate?sl=zh-CN&tl=en&u=https://blog.northtower.top/index.php/archives/12/), no?

I have just tried, you are correct. I thought that there was a different package needed because Debian/ubuntu uses .deb
