### ISSUE TITLE
JPEG coverArt which displays fine unresized, fails on server-side resize

### ISSUE THREAD

**Issue by whorfin** [navidrome/navidrome#1102]
### Description
I saw a bunch of "No cover" blue records where I expected to see album art, both in
iSub and the native Navidrome web interface.
Inspecting the logs showed messages such as:
```
WARN[0086] Error extracting image                        error="invalid JPEG format: short Huffman data" path="/tank/whorfin/Audio/Musiq/Erik Wøllo/Infinite Moments (Album)/04 Infinite Moments Pt. 4.flac" requestId=server/B6xcOgmykV-000049 size=300
```
I tried swapping the `CoverArtPriority` to give precedence to local jpg, and also discovered this doesn't seem to resolve at runtime but required a _full_ rescan.  Then I saw:
```
WARN[0025] Error extracting image                        error="invalid JPEG format: short Huffman data" path="/tank/whorfin/Audio/Musiq/Erik Wøllo/Infinite Moments (Album)/cover.jpg" requestId=server/h04pDUthes-000027 size=300
```
As an aside, even without caching, any attempts to trigger this again resulted in no messages until I nuked and regenerated the database.  I was surprised by that.

The issue seems _maybe_ related to https://github.com/golang/go/issues/10447

I've attached an example; as you can see, it displays fine on the web.  And, I would imagine, if covers were not resized server-side, they'd display in the Navidrome web-UI.  But the artwork.go code which resizes covers is failing to decode them, because the golang library is too persnickety.  `sxiv` displays the image fine.  "verbose" mode to `gm` does reveal a premature JPEG end, but plain ol' `identify` does _not_ declare the image corrupted or truncated.
```
$ gm identify 00cover-bug.jpg
00cover-bug.jpg JPEG 1400x1400+0+0 DirectClass 8-bit 353.9Ki 0.000u 0m:0.000010s
gm identify: Premature end of JPEG file (00cover-bug.jpg).
$ identify 00cover-bug.jpg
00cover-bug.jpg JPEG 1400x1400 1400x1400+0+0 8-bit sRGB 362408B 0.000u 0:00.000
$ file 00cover-bug.jpg
00cover-bug.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 300x300, segment length 16, progressive, precision 8, 1400x1400, components 3
```

### Expected Behaviour

I'd like covers to display when resized just as they would display un-resized.
If a basic image viewer or web display can display the image, it would be excellent if Navidrome could decode it as well.
Put another way, I'd expect server-side resizing to behave just like client-side (browser) resizing, if not better.

### Steps to reproduce
Try adding the attached cover such that it will be picked up as coverart.
Observe it displays as a "missing cover" blue Serrato record, and an error is thrown in the logs.

### Platform information

 - Navidrome version: 0.42.1-SNAPSHOT (3e8d3e78)  (same results with 0.41.1)
 - Browser and version:  chrome, firefox, iSub - not the issue
 - Operating System: built from source on illumos

### Additional information

Any other information that may be relevant or give context to the problem.

![00cover-bug](https://user-images.githubusercontent.com/1237590/117519781-f3abba00-af59-11eb-85cd-f84617a42219.jpg)

**Comment by deluan** [comment]
Yeah, Go image library is too finicky... The only current workaround is to open the images in a good editor and save them again. The solution is to try to extract images with `ffmpeg` when Go library fails. It's been in the todo for a while, but we didn't have an issue here in GH. Will keep this to track the work on that.

> I tried swapping the CoverArtPriority to give precedence to local jpg, and also discovered this doesn't seem to resolve at runtime but required a full rescan.

Yes, covers are resolved at scan time.

> As an aside, even without caching, any attempts to trigger this again resulted in no messages until I nuked and regenerated the database. I was surprised by that.

What do you mean by "trigger this again"?

**Comment by deluan** [comment]
> Extracting the images via ffmpeg didn't help; just putting them on disk as cover.jpg, the Go library still didn't like them.

What I mean is to extract the image from `ffmpeg`, using its options to resize the image, and send it directly to the ResponseWriter, without any further image processing in Go. This will be implemented in Navidrome, is not a workaround for the user.

> There was some commentary that this library is more forgiving: https://github.com/pixiv/go-libjpeg

I'll take a look at that

**Comment by deluan** [comment]
Nevermind `go-libjpeg`, it is a biding for a C library, and I think we have enough C dependencies already. I'll work on the `ffmpeg` image extraction whenever I can. In the meantime, you'll have to reencode the images, unfortunatelly.

**Comment by whorfin** [comment]
Agreed on the dependencies
Now I understand - and your `ffmpeg` solution would greatly improve my library, as I have Navidrome configured to prefer embedded covers if they exist.  In this particular case, the cover was embedded -- I only extracted it to a file to understand what was happening, and confirm that the problem happened with files and not just embedded artwork.

So I will await the `ffmpeg` improvement.

A similar solution would be to provide something like the "transcode configuration" for "image resizing".  It would be easily possible to have eg an `imagemagick` command which reads an artwork file, resizes it preserving aspect ratio, converts to a canonical format desired by Navidrome, and squirts that to stdout.  If the Go image library remains pedantically unuseful, this could be a workaround, and would be similar in spirit to the `ffmpeg` extract and resize.

Slightly related to this - it seems there really should be _two_ chances when implementing `CoverArtPriority`.  If a track has a broken embedded image, it would be nice to pick up the next valid "CoverArt object" in the priority list.
Just to explain - if i have track.flac with a broken embedded image, and cover.jpg in the album directory, and a `CoverArtPriority` which has "embedded" before "cover.jpg"
The Navidrome will on scan see the embedded art but not parse it, and decide the right thing to do is use embedded art.  But then on browse-time, when extraction and resizing fails, it seems the album art will just be considered missing, and we won't try the next valid entry in the `CoverArtPriority` list.

**Comment by whorfin** [comment]
I made a very nasty hack to my local "image/jpeg/reader.go" code, which seems to enable perfectly acceptable decoding of all of my cover art in some tests.
I now have various client and user configurations in my navidrome database, but per the above description, my coverart remains broken in the database despite fast or Full rescans
I'd rather not delete the database if it can be avoided --- is there any way "Full Rescan" could be amended (or an option added) to re-process coverart?  It seems it should be enough to only do this when the coverart has been marked as "missing"?
This would also allow eg adding coverart via files-in-directories after the fact.
