### ISSUE TITLE
Warning: React does not recognize the prop in AlbumListActions

### ISSUE THREAD

**Issue by aldrinjenson** [navidrome/navidrome#1118]
### Description
For Extra-Small screens, 2 console warning appears saying that React does not recognize the props 'disableElevation' and 'fullWidth'
```
Warning: React does not recognize the `disableElevation` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `disableelevation` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in button (created by ForwardRef(ButtonBase))
    in ForwardRef(ButtonBase) (created by WithStyles(ForwardRef(ButtonBase)))
    in WithStyles(ForwardRef(ButtonBase)) (created by ForwardRef(IconButton))
    in ForwardRef(IconButton) (created by WithStyles(ForwardRef(IconButton)))
    in WithStyles(ForwardRef(IconButton)) (created by Button)
    in Button (at AlbumListActions.js:45)
    in div (created by ForwardRef(ButtonGroup))
    in ForwardRef(ButtonGroup) (created by WithStyles(ForwardRef(ButtonGroup)))
    in WithStyles(ForwardRef(ButtonGroup)) (at AlbumListActions.js:40)
    in div (created by ForwardRef(Toolbar))
    in ForwardRef(Toolbar) (created by WithStyles(ForwardRef(Toolbar)))
    in WithStyles(ForwardRef(Toolbar)) (created by TopToolbar)
    in TopToolbar (at AlbumListActions.js:31)
    in AlbumListActions (at AlbumList.js:90)
    in div (created by ForwardRef(Toolbar))
    in ForwardRef(Toolbar) (created by WithStyles(ForwardRef(Toolbar)))
```

### Steps to reproduce

1. Open albums
2. Resize the window to XSmall size
3. See warning in the console

### Platform information

 - Navidrome version: latest master
 - Browser and version: Firefox latest

### Additional information
 - Screenshots (if applicable)?
 
![image](https://user-images.githubusercontent.com/53407417/118164670-f8340f00-b440-11eb-9f46-a69fb7a0e60a.png)
![image](https://user-images.githubusercontent.com/53407417/118164949-53fe9800-b441-11eb-8a71-1d13f8ffb3cf.png)

**Comment by sans2801** [comment]
Hello @aldrinjenson, I would like to know whether this issue is open.

**Comment by aldrinjenson** [comment]
> Hello @aldrinjenson, I would like to know whether this issue is open.

Yeah, the warning still shows up in the latest master when you use extra-small screen size for albums

**Comment by sans2801** [comment]
Ohk

> > Hello @aldrinjenson, I would like to know whether this issue is open.
> 
> Yeah, the warning still shows up in the latest master when you use extra-small screen size for albums

Ohk thanks, I'll look into it
