### ISSUE TITLE
Add INDEX to artists and ALL ALBUMS

### ISSUE THREAD

**Issue by ghost** [navidrome/navidrome#1119]
Would something like this be possible to ease browsing of ARTISTS and ALBUMS without using a search.

Add index to artists:

![Artist index](https://user-images.githubusercontent.com/5423879/118377325-7992bb00-b581-11eb-84f8-cb5db5b0701b.jpg)

And for all albums, if the index is added it may make more sense to move the ALL ALBUM page under the library: section

![All Album Index](https://user-images.githubusercontent.com/5423879/118377346-94652f80-b581-11eb-94f3-af256f22d3ac.jpg)

<img width="160" alt="Screen Shot 2021-05-15 at 1 31 59 PM" src="https://user-images.githubusercontent.com/5423879/118377439-16555880-b582-11eb-9d79-2f70a674f3e7.png">

**Comment by SteveDinn** [comment]
Agreed, this would be awesome. The "All Albums" view isn't really useful one you have dozens of pages of albums; you have to search anyway. This index would be super useful.

**Comment by Dnouv** [comment]
@TheFlatworm, thanks for your suggestion; actually, it is planned to re-design the Album UI in the upcoming months as a project under the GSoC by the selected student; if I recall correctly, this alphabetical index feature was discussed to be implemented, so you might see this feature in the future updates. 
If there any more suggestions or feedback, please feel free to comment. Thank you!

**Comment by certuna** [comment]
Plex, Emby etc all have the A-Z index vertically on the right, I think that works well.

Mind you, this isn't totally trivial, as the contents of the index would have to be dependent on the sorting method selected, for example:

- Sort by album title: A-Z bar
- Sort by album artist: A-Z bar
- Sort by album year: 1920-2021 bar
- Sort by album rating: 1-5 ratings bar
- Sort by date added: "Nov 2005" - "May 2021" bar
- Sort by date played: "Nov 2005" - "May 2021" bar
- Sort by playcounts: 0-20 bar
