### ISSUE TITLE
Metadata scanning for certain files 

### ISSUE THREAD

**Issue by infinitejones** [navidrome/navidrome#1137]
This looks similar to this issue: https://github.com/navidrome/navidrome/issues/728
... but the key difference is that the files can be played by Navidrome.

### Description

Errors along these lines for individual tracks when running a full re-scan - regardless of using taglib or ffmpeg

`2021-05-26T05:19:29.235223000Z time="2021-05-26T05:19:29Z" level=warning msg="Error reading metadata from file. Skipping" error="cannot process /music/CHVRCHΞS/EP/01 Gun.m4a" filePath="/music/CHVRCHΞS/EP/01 Gun.m4a"`

Regarding the unusual character in the Artist name: there are other songs in the same folder (ie. with the same Artist and Album name) that Navidrome has scanned with no problem. Those songs also contain the unusual Ξ character in the Artist name and Navidrome doesn't seem to be concerned.

And equally, there are many other hundreds of tracks that Navidrome seems to be having problems scanning that do not contain any unusual characters in their metadata.

### Expected Behaviour

Metadata tags for files should be handled consistently for all files

### Steps to reproduce

Attached tar.gz contains two files from the same album/folder:

01. Gun.m4a
03. Zvvl.m4a

Plus their respective ffprobe outputs.

Running a full scan on the files, Navidrome can successfully read the metadata for 03. Zvvl.m4a but cannot for 01. Gun.m4a

### Platform information

 - Navidrome version: v0.43.0 via docker
 - Browser and version: Chrome 90.0.4430.212
 - Operating System: Debian Buster
 
### Additional information

Any other information that may be relevant or give context to the problem.

![unknown album](https://user-images.githubusercontent.com/5801868/119746163-26026480-bed3-11eb-8f99-496899bdd2f5.png)

Here's the top of the Unknown Album tracklist.

**Comment by deluan** [comment]
Please attach the sample files. TagLib has issues with some tags, which explain the issue when using the default `taglib` Scanner. Extractor.

> Running a full scan on the files, Navidrome can successfully read the metadata for 03. Zvvl.m4a but cannot for 01. Gun.m4a
Is this after changing the extractor to `ffmpeg`?

**Comment by infinitejones** [comment]
Yes, this is after changing to the ffmpeg extractor. I'm running this in Docker via docker-compose so I added       `ND_SCANNER_EXTRACTOR: ffmpeg` under `environment:` and did `docker-compose down; docker-compose up`.

I seem to be having problems attaching a Zip with the two files and their ffprobe outputs. It's a 51.3MB zip file. Is there another way I can get it to you?

**Comment by deluan** [comment]
Send it to me by email? deluan @ navidrome dot org

**Comment by infinitejones** [comment]
Here's a Google Drive link: 

https://drive.google.com/file/d/1krWx-nVOL8JboIOF3bFsUrqtIvhhjuLR/view?usp=sharing

**Comment by deluan** [comment]
Weird, I was able to import the two songs in my environment, with both `ffmpeg` and `taglib` extractors. This is the result of using `taglib`:
<img width="749" alt="Screen Shot 2021-05-27 at 9 52 15 AM" src="https://user-images.githubusercontent.com/331353/119838711-9f00bc80-bed1-11eb-89f4-118eecef985e.png">

Maybe it is something in your setup? Are the files accessed from a network share or are they local?

**Comment by infinitejones** [comment]
Thanks. The files are on a 6TB btrfs volume connected directly via USB to the Raspberry Pi that Navidrome runs on (in a Docker container).

I'm going to try re-ripping the files and re-tagging with MusicBrainz - I'll advise whether that makes a difference.

**Comment by infinitejones** [comment]
I've deleted some of the failing files from the disk and re-added them, and that seems to have done the trick, after a full re-scan in Navidrome.

Thanks for the help, sorry for the false alarm!
