### ISSUE TITLE
Improve the handling for coverArt endpoint missing the id property

### ISSUE THREAD

**Issue by acroyear** [navidrome/navidrome#1139]
### description

Several endpoints do not return coverArt as expected (playlist and artist). SubFire expects it, so it ended up generating the coverArt URL without the id= property.

In Subsonic, if the id= is missing, subsonic returns the generic musical-note icon, the same one it returns if you ask for coverArt and the id= doesn't match anything in the database.

Navidrome (like Ampache) returns the JSON validation error that id= is required, and so it generates the browser's built-in error-image on the screen, looking rather ugly.

### Expected Behaviour

Like subsonic, asking for an image should always return an image, so the request should return the Navidrome blue CD icon.

### Steps to reproduce

View the demo site in https://subfiresuite.com/m2

### Platform information

 - Navidrome version: whatever is on the demo site right now.

**Comment by deluan** [comment]
As we discussed in Discord, there are still situations where `getCoverArt` returns a JSON/XML response:
- User/Password missing or invalid
- `id` is invalid (ex: "abc")

Anyway, Navidrome now returns the placeholder blue record when the id is missing
