### ISSUE TITLE
Playlist update via API does not update the comment field

### ISSUE THREAD

**Issue by acroyear** [navidrome/navidrome#1140]
### Description
SubFire sent an update to

demo.navidrome.org/rest/updatePlaylist.view?playlistId=c21c936f-cbec-4c74-bef7-20e322b4608f&comment=go+away&public=false&name=zz-sbr-local3k&v=1.16.1&f=json&c=SubFireLibDemoIncomplete <&credentials> 

and the comment was not updated. When fetched back, the comment was initially empty, and later the comment was the comment that was updated in the Demo's UI which did work.

### Expected Behaviour

When the updatePlaylist includes a comment parameter, it should be persisted and returned on the next getPlaylist.

### Steps to reproduce

API call.

### Platform information

 - Navidrome version: whatever is on the demo server at this time.

### Additional information

SubFire  uses playlist comments extensively for both the remote control feature (browsing on desktop/tablet and using that to send a play queue to another instance running by the same user, like the TV in a manner similar to Plex and Chromecast), as well as the radio station generators (shuffled on demand playlists). Not being able to update the comment where the metadata is stored means these two features can not work in Navidrome.

**Comment by deluan** [comment]
Ops, not only the `comment`, but also the `public` param is being ignored! Will fix this ASAP
