### ISSUE TITLE
Navidrome connects to google

### ISSUE THREAD

**Issue by c0dev0id** [navidrome/navidrome#1147]
### Description

I noticed that navidrome is asking my browser to connect to `https://storage.googleapis.com/workbox-cdn/releases/6.1.2/workbox-sw.js`. It is the only remote resource that's fetched.

I blocked `storage.googleapis.com` in ublock and found that navidrome is still working as expected. So my question would be:

* Is workbox needed at all or can it be removed?
* If it's needed, would it be possible to include this js lib in navidrome instead of loading it from google?

I'm using navidrome version 0.42.1.

**Comment by deluan** [comment]
This is the default implementation from Create-React-App, and it is used for the PWA functionality. AFAIK, it can potentially be replaced by a npm dependency, @certuna was looking into that a while ago, but PRs are always welcome :)

**Comment by certuna** [comment]
Yeah it's one of the loose ends of the PWA serviceworker implementation, see also https://github.com/navidrome/navidrome/pull/952 . It's been like this ever since we started using the CRA service worker and had PWA support. It definitely would be possible to include the Workbox libraries in Navidrome instead of loading them in remotely, and I'm sure it's super easy for someone with better knowledge than I have of how npm works , feel free to take this up.

**Comment by deluan** [comment]
I was reading the workbox implementation, and it would be pretty straightforward to just host the `workbox-sw.js` in Navidrome itself. The issue with this is that we could end-up with a stale version, and for this reason, I don't think we should do this.

Ideally we would use one of the Workbox's Node modules, but this is a more complex solution, and unfortunately I don't have time to implement that ATM

**Comment by certuna** [comment]
We have the same issue with loading it from the CDN - the URL has a version number in it (`/releases/6.1.2/workbox-sw.js`) so it can become stale anyway.

**Comment by deluan** [comment]
Yeah, you are right, not a great way to handle it, but it is not worse than it is already. I did some tests and embedding workbox in Navidrome will increase the binary in 1.6MB. 

@jvoisin Any comments?

**Comment by jvoisin** [comment]
Do we really need 1.6MB of javascript for PWA support?
Otherwise, just download it when needed. Worse case, this can likely be put behind a knob for people who don't want to have their navidrome instance contacting Google.

**Comment by certuna** [comment]
We're not using all Workbox modules, we can probably eliminate. Only `-core`, `-strategies`, `-routing` and `-preload` are used.
