### ISSUE TITLE
Problem streaming legacy FLAC files with IDv3 tags in Firefox

### ISSUE THREAD

**Issue by whorfin** [navidrome/navidrome#1149]
This is more to document some observed bad interaction between Firefox, legacy FLAC and various web players.  It seems to be not just navidrome, nor even just the webplayer navidrome embeds.  Navidrome could work around this by re-muxing the track (eg `ffmpeg -i busted.flac -vn -acodec copy -f flac -`), but something seems broken here in the firefox/webplayer ecosystem?  Firefox plays the media fine when stream URLs are entered directly.  And it all works just fine in Chrome and Safari.

More details here:
https://github.com/lijinke666/react-music-player/issues/389

**Comment by kescherCode** [comment]
FLAC is not supposed to have IDv3 tags. Therefore, it's correctly strict behaviour by clients to reject such files, and incorrectly permissive by clients to accept such files.

**Comment by whorfin** [comment]
Every web browser plays these files correctly when directly streamed.

Navidrome correctly reads the tags, the issue is on playback.  And as you can see above, the fault ultimately seems not to be navidrome's, but rather some subtle interaction of the javascript player and media typing on Firefox, where the media is incorrectly interpreted as MPEG but only when using non-native player.

Your comment that it is "incorrectly permissive by clients to accept such files" is itself incorrect.
[As you can see here in current master libFLAC stream_decoder.c](https://gitlab.xiph.org/xiph/flac/-/blob/master/src/libFLAC/stream_decoder.c#L1351
), these tags are simply skipped, not flagged as errors.

It is therefore unsurprising that web browsers behave exactly as the reference implementation.

Unsupported tags do not invalidate this file format.

**Comment by deluan** [comment]
IMHO, folks that have these type of files should re-tag to avoid this kind of issue. If they prefer not to do it, the second best option is to "transcode" the files to FLAC (or any other format), removing the tags, as you proposed in the description.

As this is a generalized issue, affecting a lot of different players, I don't think this should be kept open, as there won't be any "solution" for this any time soon.

**Comment by whorfin** [comment]
That's a totally fair point.
I'll close this out, as the issue really is upstream.
