### ISSUE TITLE
Add tzdata to the Docker container in order to configure the timezone

### ISSUE THREAD

**Issue by letompouce** [navidrome/navidrome#1153]
### Description

The container lacks of the `tzdata` package. As a result, the container can not use anything else than UTC.

### Solution

```
RUN apk add --no-cache tzdata
```

### Alternatives

Move to Greenwich.

Or, build a custom image:
```
FROM deluan/navidrome:latest
RUN apk add --no-cache tzdata
```
Build it, then use it in your `docker-compose` file, in which you also mount your host's localtime file:
```
    image: local/navidrome:tzdata
    volumes:
    - /etc/localtime:/etc/localtime:ro
```

### Additional context

https://wiki.alpinelinux.org/wiki/Setting_the_timezone

**Comment by deluan** [comment]
Hey, thanks for reporting this. Based on the link you provided, you don't actually need to install `tzdata`, just need to mount your `localtime` as you specified in the docker-compose example. Can you please confirm this?

**Comment by letompouce** [comment]
Hmm, it turns out you are right, things changed over time in Alpine:
```
$ ls -l /etc/localtime
lrwxrwxrwx 1 root root 32 2021-02-07 19:49 /etc/localtime -> /usr/share/zoneinfo/Europe/Paris
$ LANG=C date
Sun Jun  6 12:53:00 CEST 2021
$ docker run --rm -it  --entrypoint /bin/date deluan/navidrome 
Sun Jun  6 10:53:03 UTC 2021
$ docker run --rm -it  --entrypoint /bin/date -v /etc/localtime:/etc/localtime:ro deluan/navidrome 
Sun Jun  6 12:53:05 CEST 2021
```
I guess I have a few images to shave `tzdata` off!

Sorry for the noise!
