### ISSUE TITLE
Mobile GUI freezes when changing list view

### ISSUE THREAD

**Issue by FabianPiconeDev** [navidrome/navidrome#1154]
Noticed on deluan/navidrome:latest image with Android Chrome and Android Firefox.
Reproducible also on current online demo with Windows Chrome on mobile mode.

![Animation](https://user-images.githubusercontent.com/4472725/120904738-02b38400-c64e-11eb-8aa7-97e1f48b4eb9.gif)

**EDIT**
Exact version of Navidrome was 0.43.0 .

**Comment by deluan** [comment]
Yeah, this is a know bug, and was already fixed, to be released in the next version. You can try the develop build if you want: `deluan/navidrome:develop`

**Comment by FabianPiconeDev** [comment]
I updated Navidrome from 0.43.0 to 0.47.0, I can't reproduce the bug anymore.
