### ISSUE TITLE
Filter by genre

### ISSUE THREAD

**Issue by FabianPiconeDev** [navidrome/navidrome#1155]
When I click on the menu icon, I would like to have a link under Category "Library", named "Genres".
When I would click on the link "Genres", there should be rendered tiles of scanned genres, similar when clicking on "Albums" -> "All".
By clicking on a genre, all files of that genre should be playable, similar as I would click on an album.

![Capture](https://user-images.githubusercontent.com/4472725/120905667-f500fd00-c653-11eb-8a4a-80e74a961d4f.JPG)

**Comment by metalheim** [comment]
I think there is already an Issue for that feature you're describing at #1092

The basis for this feature was just done a few days ago, so it'll take some time to build the API endpoints and UI parts.

**Comment by deluan** [comment]
I'm closing this in favour of #850. Please feel free to follow that issue to get updates on the progress. Also add any relevant comments to that issue.
