### ISSUE TITLE
Installing from Docker

### ISSUE THREAD

**Issue by whi4** [navidrome/navidrome#1157]
Hi,
I am trying to install the docker using this:
"
 docker run -d \
   --name navidrome \
   --restart=unless-stopped \
   --user $(id -u):$(id -g) \
   -v /srv/shares/music:/music \
   -v /srv/shares/navidrone-data:/data \
   -p 4533:4533 \
   -e ND_LOGLEVEL=info \
   deluan/navidrome:latest
"

I get this error message (many times):
"_   _             _     _
| \ | |           (_)   | |
|  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___
| . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
| |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
\_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|

                          Version: 0.43.0 (d9f26826)

time="2021-06-06T14:42:52Z" level=error msg="Error disabling foreign_keys" error="unable to open database file: no such file or directory"

time="2021-06-06T14:42:52Z" level=error msg="Failed to apply new migrations" error="unable to open database file: no such file or directory"

"

What should I do to rectify this problem?

Regards,

Robert

**Comment by metalheim** [comment]
Maybe a typo in mounting your `data` volume?

`-v /srv/shares/navidrone-data:/data` 
sounds like you meant 
-v /srv/shares/navidro**m**e-data:/data

 If that does not exist, navidrome can't create the database.

**Comment by whi4** [comment]
Hi,
Thanks for your very rapid reply.  I did check that the navidrome-data directory was created by docker, so I thought there might be something wrong with the setup file.

I tried retyping the docker compose command, as you suggested, but had no luck.

I found this link: https://www.reddit.com/r/navidrome/comments/ivfknd/dockercompose/ , which identified that the user line caused the problem.

I have removed the use r line and now my portainer page tells me that the navidrome docker container is starting.  The log tells me that is busy building the database.  I expect that will take some time.....  

So it looks like I will have a navidrome media server running pretty soon, which is very exciting.  

I believe there may be some security issues running the docker without the user line but do not know how to rectify the problem.

Please let me know if there is anything I should do to operate more securely.

Regards,

Robert

**Comment by deluan** [comment]
Maybe your issue is related to this?  

https://github.com/navidrome/navidrome/issues/695#issuecomment-855219513

**Comment by JOduMonT** [comment]
@whi4 like @deluan said, you should chown your volumes with the proper user, which could be done with
chown $(id -u):$(id -g) -R -v /srv/shares/music /srv/shares/navidrone-data

@deluan, the container should take care of this such as you could see with [LinuxServer container](https://github.com/search?q=org%3Alinuxserver+%22chown+-R%22&type=code)

**Comment by SteveDinn** [comment]
That might be ok for the data folder, but I have my music accessible in other ways besides Navidrome. I don't think Navidrome should be messing with the owner or permissions of the music files. I have my music mounted as read-only, so this would give me an error each time I started the server.

**Comment by JOduMonT** [comment]
@SteveDinn you need a group in commons with navidrome and the other apps/users which have the right to read at least.
It is a best practice to not run a service as root even inside a container

**Comment by SteveDinn** [comment]
Agreed, and I follow that advice, but I run Navidrome as a group member and not the file owner. I don't want it "taking over".

**Comment by deluan** [comment]
I'll close this as the original issue was resolved. Migrating to a LinuxServer image is tracked here: https://github.com/navidrome/navidrome/issues/531
