### ISSUE TITLE
Nord Theme

### ISSUE THREAD

**Issue by tpbnick** [navidrome/navidrome#1158]
### Is your feature request related to a problem? Please describe.
Creating a Nord theme based on the [Nord color palette](https://www.nordtheme.com/).

### Describe the solution you'd like

Create a new Nord theme.

### Additional context

Also style the music player, beyond the 'dark' and 'light' options.

**Comment by jvoisin** [comment]
Feel free to open a pull-request, creating a theme is [pretty easy]( https://www.navidrome.org/docs/developers/creating-themes/ ).
