### ISSUE TITLE
Top Hits

### ISSUE THREAD

**Issue by ryanmurray** [navidrome/navidrome#1170]
Love navidrome coming from airsonic which was clunky. The only feature i miss is top hits.

**Comment by deluan** [comment]
This is already available in Subsonic API, and you can see it if you use a client that supports it (DSub, Substreamer, probably play:Sub)

But I'm assuming you want the feature in the Web UI, and this will be possible once we get the new Artist Detail page (#961) in place

**Comment by ryanmurray** [comment]
Unfortunately after scanning my entire library In last FM data such as top
songs or biography isn't working on any artists. I am running in a docker
container so maybe I'm missing something

**Comment by deluan** [comment]
Did you configure Last.FM integration? Current version requires manual setup: https://www.navidrome.org/docs/usage/external_integrations/#lastfm

What Subsonic client are you using?

**Comment by ryanmurray** [comment]
dsub. I added the enviroment variables to my docker and all is working. Sorry did not see API key was required.
