### ISSUE TITLE
Transcoding options on download

### ISSUE THREAD

**Issue by kalegood** [navidrome/navidrome#1172]
### Is your feature request related to a problem? Please describe.

A clear and concise description of what the problem is. For e.g. I'm always frustrated when '...'

### Describe the solution you'd like

A clear and concise description of what you would like to happen.

**Comment by kalegood** [comment]
The ability to transcode for downloads would be great.

**Comment by ToadCast** [comment]
Hi, why would that be great? If you have the music on a storage to be accessed by Navidrome, you can change the format of the files then. Do you mind giving a bit of context to picture it?

**Comment by deluan** [comment]
This is already requested in #573. I'm closing this in favour of that one. Please follow that issue for updates.
