### ISSUE TITLE
Ability to disable album image spinning

### ISSUE THREAD

**Issue by zoidy** [navidrome/navidrome#1185]
### Is your feature request related to a problem? Please describe.

I'd like to be able to disable the spinning image of the album cover as it causes unnecessary CPU usage. With rotation the browser process uses about 7-12%. When I edit the DOM to remove the img-rotate class, CPU usage immediately goes to about 2%. When you're running a lot of other browser tabs and applications, it's noticeable as fans will spin up more and battery life will be reduced.

### Describe the solution you'd like

A setting that allows one to disable rotation of the album images.

**Comment by deluan** [comment]
The React Player does not provide an [option](https://github.com/lijinke666/react-music-player#clipboard-api) to do that. The only thing we could do is to not show the cover (by using the `autoHiddenCover ` option)

Another possibility is, once we figure out how to properly [override the player's styles](https://github.com/navidrome/navidrome/pull/1184), is to change the cover style to stop the animation. 

Once that is merged I'll take a look at this

**Comment by zoidy** [comment]
I was able to achieve the desired result by adding 
```
     '& .music-player-panel .panel-content div.img-rotate': {
        'animation-duration': '0s',
      },
```
To the player's styles in [Player.js](https://github.com/navidrome/navidrome/blob/167fe462885f286b84f26e082a663c5d6cde5e0a/ui/src/audioplayer/Player.js#L65). I tried applying the change in a theme without success. Now that the #1184 is merged, perhaps it's possible to do so?

**Comment by deluan** [comment]
I'll try to add this as a config, and not part of a theme. Will try tonight, before the next release
