### ISSUE TITLE
feat(UI): add SSO via auth redirects

### ISSUE THREAD

**Issue by henniaufmrenni** [navidrome/navidrome#1189]
### Is your feature request related to a problem? Please describe.

When enabling http-header authentication, for example in conjunction with Authelia, you need to set Authelia to bypass authentication for that URL otherwise you loose the ability to use the Subsonic API. If you're opening Navidrome in a new Browser and want to use SSO with http-header authentication you would need to first to visit the URL of your SSO solution, sign in and then navigate to Navidrome for it to pass the headers.

### Describe the solution you'd like

Let the user specify a callback URL via enviroment variables which would lead to a button (e.g. "Single-Sign-On") conditionally being rendered which would redirect the user to authenticate in the SSO solution of their choice. 

Using Authelia as an example, it could look something like `ND_PROXYAUTHURL=https://sso.example.org/?rd=https%3A%2F%2Fnavidrome.example.org`, which would lead them to login via Authelia and then redirect them back to Navidrome after having successfully done so.

Furthermore instead of disabling the sign out in the UI like in 
[Don't show "logout" when authenticated by Header](https://github.com/navidrome/navidrome/commit/cf553ce812818908d572835b80fc45e68469bddd) the user could specify a URL for single-sign-out.
Sticking with the Authelia example that could look something like `ND_PROXYSIGNOUTURL=https://sso.example.org/logout`.

Additionally there could be an option to disable normal authentication in the UI when using http-header authentication, which could be a way to lock down the login with an admin account in the UI - if there is no such user in the SSO user database - via enviroment variables.

### Additional context

I've started working on a PR but wanted to post this feature request before continuing after I saw [@deluan 's latest commit](https://github.com/navidrome/navidrome/commit/cf553ce812818908d572835b80fc45e68469bddd)

**Comment by deluan** [comment]
Thanks for the ideas. Let's go over it one by one:

> When enabling http-header authentication, for example in conjunction with Authelia, you need to set Authelia to bypass authentication for that URL otherwise you loose the ability to use the Subsonic API. If you're opening Navidrome in a new Browser and want to use SSO with http-header authentication you would need to first to visit the URL of your SSO solution, sign in and then navigate to Navidrome for it to pass the headers.

I don't use Authelia, but I have a "poor man's" SSO with Caddy and in my case I just put the Subsonic API url in a white-list, so it is not required to be authenticated. All Subsonic API endpoints are under `/rest`. Wouldn't this work for you?

> Furthermore instead of disabling the sign out in the UI like in
Don't show "logout" when authenticated by Header the user could specify a URL for single-sign-out.
Sticking with the Authelia example that could look something like ND_PROXYSIGNOUTURL=https://sso.example.org/logout.

That's a great idea! To keep naming consistent, I'd call it `ReverseProxySignOutURL` (`ND_REVERSEPROXYSIGNOUTURL`)

> Additionally there could be an option to disable normal authentication in the UI when using http-header authentication, which could be a way to lock down the login with an admin account in the UI - if there is no such user in the SSO user database - via enviroment variables.

This would also be a nice implementation. In the case the user does not exists in the DB, where they would land? Should we redirect them to the Sign Out page, or just show an empty page saying "Invalid User"?

**Comment by henniaufmrenni** [comment]
Thank you for your fast respond :^)
> I don't use Authelia, but I have a "poor man's" SSO with Caddy and in my case I just put the Subsonic API url in a white-list, so it is not required to be authenticated. All Subsonic API endpoints are under /rest. Wouldn't this work for you?

Ouh I don't know why I didn't think about that option before, but yeah I agree that this is the better way to implement it, since it's not just one click less, but also protects the UI from bots and crawlers. Should we add documentation for that before the next release? I'm happy to provide a configuration for Authelia.
> That's a great idea! To keep naming consistent, I'd call it ReverseProxySignOutURL (ND_REVERSEPROXYSIGNOUTURL)

Great! 
> This would also be a nice implementation. In the case the user does not exists in the DB, where they would land? Should we redirect them to the Sign Out page, or just show an empty page saying "Invalid User"?

I personally think it would be good if we'd make it obvious to less tech savvy users that they're not authorized, so maybe something like "Invalid User", "There is no account associated to your user." - what is your opinion on that ?

**Comment by deluan** [comment]
> Should we add documentation for that before the next release? I'm happy to provide a configuration for Authelia.

Yes, I'm gonna review the docs before release. A blog post about configuring it with Authelia would be great : 😊 

> I personally think it would be good if we'd make it obvious for less tech savvy users that they're not authorized, so maybe something like "Invalid User", "There is no account associated to your user." or so - what is your opinion on that ?

Yeah, that makes more sense.

If you are going to work on these things and have any issues/questions, let me know.

**Comment by Mikhail5555** [comment]
```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name navidrome.* n.*;
    
    include /config/nginx/ssl.conf;

    client_max_body_size 0;
    include /config/nginx/authelia-server.conf;
	
    location / {
        include /config/nginx/authelia-location.conf;
        include /config/nginx/proxy.conf;

        include /config/nginx/resolver.conf;
        set $upstream_navidrome navidrome;
        proxy_pass http://$upstream_navidrome:4533;
    }
    
    location /rest {
        include /config/nginx/proxy.conf;

        access_log off;

        include /config/nginx/resolver.conf;
        set $upstream_navidrome navidrome;
        proxy_pass http://$upstream_navidrome:4533;
    }

   # This would require the logout url to not be disabled
    location /app/logout/ {
        return 301 https://auth.xxxxxxx/logout;
    }

}
```
@henniaufmrenni incase you are using nginx, this is how i have it setup, this allows /rest to bypass the authelia SSO while all other requests being redirected to your SSO provider.
@deluan This might also be a good reason to keep the logout url enabled (Without the need of adding a new environment variable to configure the redirect ur)l

**Comment by deluan** [comment]
@Mikhail5555, thanks for the sample config. Regarding the logout URL, the `/app/logout/` path you used above is not part of Navidrome. Logout is handled entirely in the frontend, without ever communicating with the server. So I'm not sure if the config above would work....

**Comment by Mikhail5555** [comment]
Oh my bad. It was a way that I handled it in another application which also supported SSO so though it would also work in Navidrome, but ofcourse that wouldnt be the case if the frontend just destroys all tokens. 

(Offtopic) Wouldn't the backend also need to 'destroy' the token at some point (or does the application just wait for it to expire)?
Feels like the frontend should let the backend know that the token was destroyed/expired.

**Comment by deluan** [comment]
The server does not store any session state, it is completely stateless. That's by design, as it helps with the goal of having a very lightweight server.
