### ISSUE TITLE
Auto-skip certain songs

### ISSUE THREAD

**Issue by seanwllms** [navidrome/navidrome#1190]
One feature that I would appreciate is the ability to permanently and automatically skip certain songs when playing an album (or shuffling the whole library). I could obviously delete tracks from my library, but the completest in me wants to keep tracks in my library even if I don't actually listen to them (sketch tracks on hip-hop albums are a good example of this).

I haven't used iTunes in 10+ years, but I seem to remember that you had the ability to "uncheck" songs, which would essentially implement this feature.

I understand if this isn't a priority, but I figured I would add it as an issue to see if someone is interested in implementing it.

**Comment by blunderberg** [comment]
Automatically skipping tracks that are shorter than a certain (configurable) length would be a cool feature.
There are certain albums that have short intros, interludes, outros, etc. that shouldn't be played on their own or as part of a random mix, and should only be played when listening through the entire album (start to finish).
This would be most useful with "shuffle all" functionality that plays random 200 tracks from the entire library.

**Comment by certuna** [comment]
Once we get smart playlists you will probably be able to create a filter on song length that takes out short songs and/or excessively long songs, since you might not want 60+ minute tracks to show up in shuffle.
