### ISSUE TITLE
scrolling with pages is annoying!

### ISSUE THREAD

**Issue by iPwnWolf** [navidrome/navidrome#1196]
![image](https://user-images.githubusercontent.com/31454341/122790188-5c57b780-d2b8-11eb-83c6-5573b64329c8.png)

I think it's really annoying to have pages in all lists.
Is it possible to automatically load new content when scrolling?
Does such a feature exist already or will it be worked on?
I would suggest an option to load all content next to the limit of x per page.

Honestly my biggest issue with this project otherwise really great experience so far. :)

**Comment by deluan** [comment]
As we use React-Admin framework, which does not provide this support, this is not a trivial task as it conflicts with the way the framework handles API calls. And we can't just load all data, as the UI would be really slow and probably would freeze (see #621, #1186).

We are working on making this possible as a GSoC project: https://www.navidrome.org/docs/gsoc/#6-infinite-scroll

I'm closing this issue in favour of the original one: https://github.com/navidrome/navidrome/issues/132, please follow it to receive updates on the subject.
