### ISSUE TITLE
Auto create users when using header auth

### ISSUE THREAD

**Issue by dani** [navidrome/navidrome#1203]
It's really great to see header auth support comming (I'll finally be able to deploy navidrome :-))
But it'd even better to have an option to automatically create users if they are correctly auth by http header. Also, we could define additional headers which could contain any useful information (name/email/groups) and automatically set / update them when the user logs in

**Comment by deluan** [comment]
That would prevent the Subsonic API to work, as it requires the password to be know by the server.

**Comment by dani** [comment]
One way to handle this would be to autocreate the user, and prompt him for an API password on first login on the web interface (or have some kind of notifications inviting him to set a password for the API to be available)
