### ISSUE TITLE
Play queue scroll bar colour doesn't match theme

### ISSUE THREAD

**Issue by SteveDinn** [navidrome/navidrome#1216]
### Description
Just updated to v0.44. I'm just using the default theme and post-upgrade, the player accent colour changed from green to purple, but the play queue scroll bar remained green.

### Expected Behaviour
I would have expected the play queue scroll bar to match the other purple accent colours.

### Steps to reproduce
1. Add enough tracks to the play queue to see the scroll bar.
2. Look at the different colours.

### Platform information

 - Navidrome version: v0.44.0
 - Browser and version:  Chrome 91.0.4472.114 (Official Build) (64-bit)
 - Operating System: Windows 10

### Additional information

![image](https://user-images.githubusercontent.com/3911507/123808227-ef9b7900-d8c6-11eb-99af-b909f3b36e9e.png)

**Comment by deluan** [comment]
Good catch! Will try to fix it ASAP
