### ISSUE TITLE
Can't reopen player on demo

### ISSUE THREAD

**Issue by kerenon** [navidrome/navidrome#1217]
After minimizing the "now playing" overlay/window on android, opening it again is almost impossible. It seems the "hitbox" I'd need to find is waaaaay too small. It takes at least 20-30 taps to eventually hit the mark and thus reopening the player overlay, making this a dealbreaker bug.

First noticed the problem a few months ago, found this reddit thread, but no solution:

https://www.reddit.com/r/navidrome/comments/mrf3mn/music_player_bubble_not_clickable_on_demo_app/

What I've written there, still applies except that I have now 2 separate phones with the same issue. It seems the problem only affects chromium based mobile browsers. Firefox and desktop browsers are unaffected.

To make sure none of my addons/adblocking solutions interfere somehow with navidrome, I've done all my tests using a clean browser on an open network. Same result.

**Comment by certuna** [comment]
I see a related (?) issue with Navidrome in Edge (Chrome probably too, will test):
- make the window smaller to trigger the mobile view
- play a song, minimize it to the bubble
- enlarge the window to switch to desktop view
- now you can't enlarge the bubble to the bottom-bar player anymore
Issue with the upstream player?

**Comment by deluan** [comment]
> Issue with the upstream player?


Most probably yes. I'll do some testing. A solution I may implement is to disable the ability to drag the mini-player, as it bring too little value

**Comment by deluan** [comment]
I made the mini-player position fixed (bottom right of screen), and not draggable anymore. This should help with reopening it. If it does not, please reopen this issue

**Comment by deluan** [comment]
The fix has caused responsiveness issues. Reverting :(

**Comment by FabianPiconeDev** [comment]
I have exactly the same issue. 

Android chrome: Minimized player **can't be opened** on tap, only moved around.
Android firefox: Minimized player can be opened
Windows chrome mobile mode: Minimized player can be opened

Workaround is to hard reload the page which opens the big player, but its not handy to do this every time.

I agree with @deluan that moving the minimized player around is not necessary. Spotify also has a fixed variant (bottom bar) as minimized player.

**Comment by metalheim** [comment]
I've also experienced this on chrome mobile for Android, but on some devices only. Maybe the event (click) target gets too small on some resolution/dpi combinations?

My pixel 2 has the problem while my galaxy S20 ultra doesn't (same chrome mobile engine version)

**Comment by kerenon** [comment]
> My pixel 2 has the problem while my galaxy S20 ultra doesn't (same chrome mobile engine version)

My phone is a Galaxy S20 Ultra, and it has the problem :)
