### ISSUE TITLE
Error: Unauthorized when changing name

### ISSUE THREAD

**Issue by Xx-Ness-xX** [navidrome/navidrome#1222]
### Description

Hi, I am have issues logging into Navidrome after changing the name under personal. I got "Error: Unauthorized" when I tried to login using the unchanged **username** 

### Expected Behaviour

Login without error using the username that I had set up originally

### Steps to reproduce

1. Change "name" under "personal"
2. Log out
3. Log back in using username & password

### Platform information

 - Navidrome version: v0.40.0
 - Browser and version: Firefox v89.0.2
 - Operating System: Windows 10

### Additional information

Any other information that may be relevant or give context to the problem.

 - Screenshots (if applicable)?
 - Logs? 
 - Client used?

**Comment by deluan** [comment]
Hey, thanks for reporting this! The issue is that it was resetting the password to "" when you update your details. I just fixed this and in about 20 minutes a new version will be available for download here: https://github.com/navidrome/navidrome/actions/runs/991380850 or in the `deluan/navidrome:latest` docker tag.

I'll be releasing a bug-fix version tomorrow that will contain this fix.

**Comment by Xx-Ness-xX** [comment]
Thank you for your prompt action!
Does that mean I can still log back in using the password ``"`` ?

**Comment by deluan** [comment]
you can try, but it may be invalid given other checks in the code.

**Comment by Xx-Ness-xX** [comment]
> 
> 
> you can try, but it may be invalid given other checks in the code.

Just tried and couldn't log back in. I tried ``""`` ``''`` no luck
I'll wait for the fix tomorrow since I just started migrating my iTunes library to Musicbrainz Picard to fix my ID3 tags

**Comment by deluan** [comment]
It should be an empty password, without the quotes, but if you just started using Navidrome it would be better to wait till tomorrow, and start from scratch (deleting the current navidrome.db files)

**Comment by Xx-Ness-xX** [comment]
I couldn't enter empty password to sign in, and I tried using "space bar" as password to sign in but no luck.

**Comment by deluan** [comment]
Yeah, it basically screwed your user password.... Sorry about that. The new build or tomorrow's release will not cause this anymore, but any user that had its details updated before the fix had the password broken, and can only have its password reset by another admin in the system

**Comment by Xx-Ness-xX** [comment]
Not a problem, let's just hope I am the only one that changes the name

**Comment by deluan** [comment]
Just released the new fixed version , 0.44.1. Let me know if you have any other issues

**Comment by Xx-Ness-xX** [comment]
> 
> 
> Just released the new fixed version , 0.44.1. Let me know if you have any other issues

Thank you!, I've tested it and it is working fine now
