### ISSUE TITLE
Version incorrect when building from release tarball source

### ISSUE THREAD

**Issue by whorfin** [navidrome/navidrome#1224]
### Description

When building from source from eg:
https://github.com/navidrome/navidrome/archive/refs/tags/v0.44.1.tar.gz

Navidrome reports itself, in banners and "--version" as
```
dev
```

This is because the tarball, reasonably, does not contain a .git directory
Therefore the two Makefile git shell calls for GIT_TAG and GIT_SHA both fail:
```
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

### Expected Behaviour

I would expect to see the actual version; for v0.44.1, something like "0.44.1-SNAPSHOT (fb183e5)"

Doing a manual edit of the Makefile to
```
GIT_SHA=fb183e5
GIT_TAG=v0.44.1
```
works as expected.  Perhaps something such as this should be done as part of release?

Cheers

**Comment by deluan** [comment]
Yeah, I may take a look on how to add a "hardcoded" version in the archive. Maybe a file with the version used in the release and if it is found, the Makefile uses it?
