### ISSUE TITLE
use file's modification timestamp on import

### ISSUE THREAD

**Issue by anarcat** [navidrome/navidrome#1225]
### Is your feature request related to a problem? Please describe.

When switching from another app to navidrome, the first import is impressive: it is fast and works great! One problem, however, is that the "Recently added" time seems rather random. If you've used another program in the past, this is somewhat of a disappointement: your latest additions to your collections are kind of lost in a sea of randomness!

### Describe the solution you'd like

It would be great if the file's (or directory's)  timestamps would be used on import, to order the new albums created. Obviously, this would be a special behavior on *first* import: you don't want *subsequent* imports to consider those timestamps because then *those* might get buried behind *previous* imports...

### Describe alternative solutions that would also satisfy this problem

I considered hacking at the sqlite DB briefly, but that seems like a rather... challenging task.

Thanks!

**Comment by deluan** [comment]
Try setting the config option `RecentlyAddedByModTime = true` and let me know if this is what you are looking for.

Take a look at the complete list of configuration options: https://www.navidrome.org/docs/usage/configuration-options/#available-options

**Comment by anarcat** [comment]
looks like this already exists and works, sorry for the noise and thanks! :)
