### ISSUE TITLE
duplicate albums in different formats show up as duplicate tracks

### ISSUE THREAD

**Issue by anarcat** [navidrome/navidrome#1226]
### Description

Say I'm in a band. I make a recording, and save it in my library as a FLAC. I also have a copy that's transcoded to MP3, as a kind of "master" that I distribute around. Both are in my library.

### Expected Behaviour

Those should show up as different albums. Alternatively, a single album, with the right version streamed, depending on the requested encoding.

The actual behavior is that both albums show up in the *same* album, with duplicate tracks. So you'll have:

 1. Track 1 (MP3)
 2.  Track 1 (FLAC)
 3.  Track 2 (MP3)
 4. Track 2 (FLAC)
 5. etc

### Steps to reproduce

Not sure how to describe this more clearly. Let me know if the above is unclear.

### Platform information

 - Navidrome version: 0.43.0 (d9f26826)
 - Browser and version: dSub 5.5.2
 - Operating System: Android CalyxOS

### Additional information

Any other information that may be relevant or give context to the problem.

Here's a screenshot of an album with FLAC and MP3 tracks duplicated. Bonus points on that one: they *both* show up *twice*, so there are *four* copies of each track. Note that every other track is "downloaded" because I downloaded the FLAC versions, so it seems there's some deduplication *there* at least. Not sure why this is happening, maybe it has something to do with git-annex, which I use to manage my music archives.
![image](https://user-images.githubusercontent.com/796623/124338367-90af5b80-db75-11eb-9c6c-88a4b7d7aafc.png)

**Comment by deluan** [comment]
In Navidrome, songs are grouped by Artist/Album names. The only disambiguation that would work in this case is to add the type in the title ("Verrats [MP3]", "Verrats [FLAC]").

> Alternatively, a single album, with the right version streamed, depending on the requested encoding.

Ideally, you wouldn't need to transcode the files yourself, you should keep only the lossless version (FLAC) as Navidrome transcodes on demand for you (and caches the results). To activate transcoding, just go to the Player's details and select the format/bitrate you want to use. This will be even more useful after #351 is implemented.

Maybe what could help for your use-case is #573, that will allow you to select the transcoding options for downloading.

Regarding the DSub issue, not sure what is happening there.

**Comment by anarcat** [comment]
well i understand that navidrome can transcode: that's not the reason i have those multiple copies. the reason is that those are masters that are actually part of my collection...

from that perspective, changing the tags on the files is unacceptable: the album name is not "Verrats MP3" :)

but i see where you're coming from....

**Comment by deluan** [comment]
So then the only solution for using Navidrome in your use case is when we introduce Multiple Libraries (#192), you could then have one Library with FLACs and other with MP3, and you can give access to only MP3 for your users if you want. Would that work for you?

**Comment by anarcat** [comment]
> Would that work for you?

it would require a major rearchitecturing on my side, unfortunately. it would probably be easier for me to hide the files from navidrome in the first place, because i run navidrome behind docker it's possible for me to hide parts of the filesystem from navidrome. i just didn't want to have to play that whack-a-mole game... :)

**Comment by deluan** [comment]
The only way to skip a folder (and its subdirectories) is to add a `.ndignore` in the folder.

Well, whenever the Multiple Libraries feature is ready, you can write a simple bash to move the MP3s to a different root level, keeping their relative path.

**Comment by anarcat** [comment]
On 2021-07-03 17:55:17, Deluan Quintão wrote:
> The only way to skip a folder (and its subdirectories) is to add a `.ndignore` in the folder.

Oh well that's a great solution for me, actually.

a.
-- 
I believe that if someone choose arts as their subject but do not
criticize the issues of their society, they have have betrayed
themselves, their conscience, and their society.
                        - Atena Farghadani

**Comment by certuna** [comment]
Other option is to tag the FLACs as Disc 2, then you'll see them under the album, but separated.

**Comment by anarcat** [comment]
understood. thanks for all the alternatives! If you're okay with the idea, i think this ticket can be closed. :)

**Comment by laduke** [comment]
Would it be possible to disambiguate on more fields? Or would that break some subsonic api compatibility or something? 

Some albums have multiple remasters that sound different:

- original german pressing (vinyl rip)
- 1986 remaster
- 2016 deluxe edition 
- etc

So It's not only a flac vs mp3/bitrate thing. 

I'd like to be able to listen to all of them through navidrome! 

There are the `year` and `originalyear` fields. `year` seems like it would work for this case, but I don't work with musica metadata all day and am probably being naive.
