### ISSUE TITLE
docker image should start in /data

### ISSUE THREAD

**Issue by anarcat** [navidrome/navidrome#1229]
It's kind of inconvenient to override the config in the docker image. Because the config gets loaded from the current directory, and that is in `/app`, one need to export a config into `/app/navidrome.toml`.

It would be better it the starting directory would be `/data` so that the config could just live there.

**Comment by deluan** [comment]
You don't need to use a config file with docker, just need to map a volume with your data folder, and you can pass all options as environment variables, take a look here: https://www.navidrome.org/docs/installation/docker/#using-docker-compose-

**Comment by anarcat** [comment]
> EDIT: if you really want to use a config file, you can also mount it directly in the `/app` folder, like this:
> 
> ```
> - "/path/to/navidrome.toml:/app/navidrome.toml"
> ```

yeah that's what I actually did... 

> You don't need to use a config file with docker, just need to map a volume with your data folder, and you can pass all options as environment variables, take a look here: https://www.navidrome.org/docs/installation/docker/#using-docker-compose-

ah. doh. totally missed that. :) would have been more visible if it was in the Docker image docs (in https://hub.docker.com/r/deluan/navidrome)

i guess i just missed the docs, sorry again for the noise.
