### ISSUE TITLE
UI play scrub bar hard to click?

### ISSUE THREAD

**Issue by Hukuma1** [navidrome/navidrome#1230]
### Description

![naviui](https://user-images.githubusercontent.com/54511555/124370969-d7628b80-dc31-11eb-9de6-aae2e4d2d3ca.jpg)

Not sure what it is, but it seems the scrubbing section is either super particular where the mouse needs to be, or maybe some overlapping elements issue happening. Just hard to click and skip around the song if the UI doesn't register the click. Clicking the left-mouse button in the position the arrow is in the screenshot did not allow to skip the song ahead.

### Expected Behaviour

Skip ahead in song.

### Steps to reproduce

1. Play song
2. Scrub through at different heights of scrub bar

### Platform information

 - Navidrome version: 0.44.1 (fb183e58)
 - Browser and version: Google Chrome 91.0.4472.124
 - Operating System: Windows 10 64-bit

**Comment by deluan** [comment]
This is the behaviour of the upstream [react-music-player](https://github.com/lijinke666/react-music-player) project. I think it was meant to click on the current position indicator (the small ball) and dragging it to the position you want. This always work for me. 

Please confirm you see the same issue in their demo: https://www.lijinke.cn/react-music-player/

**Comment by Hukuma1** [comment]
Yep. Looks to be happening there too. Will close this out. Thanks!
