### ISSUE TITLE
[FR] Crossfade effect when scrubbing through song

### ISSUE THREAD

**Issue by Hukuma1** [navidrome/navidrome#1231]
### Is your feature request related to a problem? Please describe.
Can we please implement a cross fade effect so when skipping around a song it isn't so jarring?

### Describe the solution you'd like
Add an option to cross fade scrubbing through songs, and maybe even prev/next songs if in playlist (like Spotify).

### Describe alternative solutions that would also satisfy this problem

Continue to scrub through songs like a peasant without this quality of life feature?

### Additional context

Spotify offers this feature, but only in between switching tracks: https://support.spotify.com/us/article/crossfade-feature/

**Comment by deluan** [comment]
As I said in the previous issue, this behaviour is from the upstream project, https://github.com/lijinke666/react-music-player

I suggest you open an issue in that project, as there's currently nothing we can do from Navidrome's side.
