### ISSUE TITLE
How to use local image for wallpaper?

### ISSUE THREAD

**Issue by Darthagnon** [navidrome/navidrome#1234]
I was wondering how I would go about using a local image as a wallpaper for the login screen? There was this pull request that was merged that seemed relevant: https://github.com/navidrome/navidrome/pull/154

I've tried using base64 images in the config file, but that doesn't work (they just don't display for me; am running it on a Raspberry Pi, tried a few JPG images converted to base64) and is a hacky workaround. Is there a certain way a local path has to be formatted for navidrome to display a local image for the login wallpaper, instead of pulling from someone else's website?

**Comment by Darthagnon** [comment]
### Related issues: 
https://github.com/navidrome/navidrome/issues/102

https://www.reddit.com/r/navidrome/comments/kxfa52/option_to_set_static_color_for_login_page_that/

**Comment by deluan** [comment]
Hey @Darthagnon, there's currently no way to set the login background to an image served by Navidrome itself. What you could do is host the image in some place, like your own proxy server, or even in a private image hosting account.

Adding an image to the config file as a base64 should work. Can you please post your config line here?

**Comment by deluan** [comment]
As noted above, this is supported by adding the image as a base64 data url in the config, like:

```
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAIAAAAiOjnJAAAABGdBTUEAALGPC/xhBQAAAiJJREFUeF7t0IEAAAAAw6D5Ux/khVBhwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDDwMDDVlwABBWcSrQAAAABJRU5ErkJggg==
```
