### ISSUE TITLE
FreeBSD Makefile go and node version check

### ISSUE THREAD

**Issue by pacija** [navidrome/navidrome#1235]
### Description

Compiling on FreeBSD needs Makefile modification because current mechanism to check go and node version does not work on FreeBSD

### Expected Behaviour

Compiling on FreeBSD works out of the box

### Steps to reproduce

Described on https://www.x-tra-designs.org/metallum/installing-navidrome-under-freebsd-12.html

### Platform information

 - Navidrome version: navidrome-0.44.1
 - Operating System: FreeBSD 12.2-RELEASE amd64

### Additional information

I have modified Makefile to check go and node versions as follows:

GO_VERSION=$( shell go version | awk '{ print $3 }' | cut -c 3- )
NODE_VERSION=$( shell node --version )

This fixes compilation on FreeBSD, but I don't know if it breaks it for other OSs.

Perhaps someone with better Makefile knowledge can rewrite it to check OS and do the above for FreeBSD.

**Comment by deluan** [comment]
Thanks for opening the issue. I thought this was fixed long time ago. The modifications you did in the `Makefile` are not correct: We need the versions required by Navidrome, not the versions installed in your system.

Can you please post here the output of the following commands (run it in the root of the project):
`grep "^go " go.mod`

and

`echo "go 1.16" | cut -f 2 -d ' '`

**Comment by pacija** [comment]
Here goes:

```
me@somebox:~/navidrome-0.44.1 % grep "^go " go.mod
go 1.16
```
```
me@somebox:~/navidrome-0.44.1 % echo "go 1.16" | cut -f 2 -d ' '
1.16
```

**Comment by deluan** [comment]
So, looks like the original `Makefile` should work. What error message do you get when trying to run `make`?

**Comment by pacija** [comment]
Indeed, it works now out-of-the-box, sorry for the fuss.

Also, nice to see there's FreeBSD port in official tree as of lately:
https://www.freshports.org/multimedia/navidrome/

Best regards,
