### ISSUE TITLE
Special chars running amuck

### ISSUE THREAD

**Issue by kellyksveinson** [navidrome/navidrome#1236]
### Description

songs with special characters seem to be going to to their unknown album 

### Expected Behavior

this should be no different than an album with just letters and numerals

### Steps to reproduce

load albums with as per screen shot that had id3 and filenames from picard

### Platform information

 - Navidrome version: v0.44.1 -->
 - Browser and version: Firefox v8x.xx
 - Operating System: windows 10

### Additional information

Any other information that may be relevant or give context to the problem.

i didn't see a listing for this exact issue but i didn't look all that hard

![image](https://user-images.githubusercontent.com/78395152/124833303-9c1ed000-df43-11eb-94c3-4b4fe136f7bc.png)

**Comment by deluan** [comment]
Sorry, this should be better documented: There's a bug with the `taglib` extractor when running on Windows that it fails to read files with special chars in it.

The current solution for this is to use `ffmpeg`. Add `Scanner.Extractor = "ffmpeg"` to your configuration and forece a rescan (or start from scratch)

**Comment by deluan** [comment]
@kellyksveinson, were you able to test it with the `ffmpeg` Extractor?

**Comment by kellyksveinson** [comment]
Oh buddy, yeah, it totally fixed all my problems, so sorry I forgot to get back.

Sent with a Spark
