### ISSUE TITLE
look for playlists only in a given directory

### ISSUE THREAD

**Issue by anarcat** [navidrome/navidrome#1237]
### Is your feature request related to a problem? Please describe.

I finally managed to get navidrome to parse my precious playlists, yay! Turns out they had to be at the root of my music directory (or, to be more accurate, have the paths in the playlist actually work relative to the playlist, which, to be fair, is reasonable).

But this implies that now, navidrome is parsing *all* of my playlists. And, as you might be aware, some people have this... interesting habit of listing all the tracks in an album in a `.m3u` file. As if we couldn't do a directory listing or something.

Anyways, long story short, I have a *lot* of playlists now. So many that my playlists are basically getting lost in there. I tried to remove some of those silly playlists, but unfortunately a lot of those files are "locked" somehow (being shared with friends, for example).

### Describe the solution you'd like

Other programs (e.g. `mpd`) store their playlists in a predefined directory (specified in the config file). The playlists are considered to be at the root of the music directory, and the program will not parse playlists *there*, which avoids the pesky problem of "omg what are all those playlists".

Alternatively, I could really use a cleanup of my library. But this would involve a lot more hacking around transmission than I would really like to do right now... (In fact, I just made a quick test and "disabling file download" on a given file in the torrent file list still re-downloads the file if it's related to a chunk that *does* need to be downloading, so that doesn't work, surprisingly.)

### Describe alternative solutions that would also satisfy this problem

A way to *ignore* specific playlists might also work, like "please do not import playlists in *this* directory", for example.

### Additional context

Here's a juicy example... 646 pages of playlists, whoohoo!

![image](https://user-images.githubusercontent.com/796623/125009244-280f2580-e032-11eb-9c48-104f0e62054b.png)

Remember kids: for your elite playlist to show up first, prefix it with `00-`! Extra points for that playlist named `-`... 

*From the "anarcat has a garbage music collection" department... with apologies*

**Comment by bjhiltbrand** [comment]
Also requested here: https://github.com/navidrome/navidrome/issues/1181

**Comment by deluan** [comment]
Thanks @anarcat, but as @bjhiltbrand pointed out, we already have an issue tracking this, so I'm closing this as a duplicate. Feel free to follow that one (#1181) for updates.

**Comment by anarcat** [comment]
oh! sorry, i couldn't find #1181, seems perfect for my needs, thanks!
