### ISSUE TITLE
Get Artis Info not working anymore after update

### ISSUE THREAD

**Issue by BobWs** [navidrome/navidrome#1246]
Hi,

After updating Navidrome to version 0.44 LastFM Bio/artist info isn’t working anymore. I keep getting this log errors. Before the update everything was working fine. I’m I missing something? Did something change in the preferences?
```
ERRO[11273] Error calling LastFM/artist.getInfo           artist=a-ha error="json: cannot unmarshal number into Go struct field .artist.stats.listeners of type string" mbid=7364dea6-ca9a-48e3-be01-b44ad0d19897 | stdout
-- | --
```

</div>

**Comment by metalheim** [comment]
Just checked. I'm having the same issue. Can check and provide logs later from home

**Comment by deluan** [comment]
Thanks for reporting. This error was fixed in master already, will be part of next release. In the meanwhile, you could use the develop builds.

**Comment by metalheim** [comment]
"lucky Luke" of coding, @deluan fixing bugs faster than than his shadow ;)

**Comment by antipiot** [comment]
I guess this will fix my problem in client aswell:
https://github.com/navidrome/navidrome/issues/1303
Will close my case.
