### ISSUE TITLE
Web UI prevents KDE from sleeping

### ISSUE THREAD

**Issue by martin-sweeny** [navidrome/navidrome#1256]
### Description

When music is playing in the web UI in Ungoogled Chromium, KDE's screen lock is inhibited

### Expected Behaviour

Music playing should not inhibit screen lock

### Steps to reproduce

1. Prepare a box with KDE and Ungoogled Chromium / Chromium / Chrome
2. Play music in Navidrome
3. Observe the Battery & Brightness panel in your taskbar:

![image](https://user-images.githubusercontent.com/3329959/126223386-fc86bab8-fd32-414c-81dd-1da2e392b127.png)

### Platform information

 - Navidrome version: 0.42.1 (35027bbe)
 - Browser and version: Ungoogled Chromium 87.0.4280.141 
 - Operating System: Artix Linux kernel version 5.12.14-artix1-1

### Additional information

Any other information that may be relevant or give context to the problem.

 - Screenshots (if applicable)?
 - Logs? 
 - Client used?

**Comment by martin-sweeny** [comment]
While writing this I realized that you may need a laptop to repro this

**Comment by lostpolaris** [comment]
Does this not happen w/ a similar context like playing video through VLC? Or playing other sources of media through Chrome like Youtube/Netflix?

**Comment by martin-sweeny** [comment]
> Does this not happen w/ a similar context like playing video through VLC? Or playing other sources of media through Chrome like Youtube/Netflix?

It doesn't happen when playing music in other players (Spotify, youtube, etc) and I think it only prevents sleep for videos when they're fullscreen and playing
