### ISSUE TITLE
32-bit Docker Images

### ISSUE THREAD

**Issue by karmanyaahm** [navidrome/navidrome#1259]
### Is your feature request related to a problem? Please describe.

Cannot install on a 32-bit Intel CPU.

### Describe the solution you'd like

Just like there are ARM images for raspberry pi's it would be nice if there were 32-bit images. I'm not sure about it but I would imagine the process is similar.

### Describe alternative solutions that would also satisfy this problem

Install from source: it takes more work, but this is what I'm doing right now.

### Additional context

Similar to #92

**Comment by deluan** [comment]
Done. When I started supporting Docker images for multiple platforms, I decided to only add new platforms as needed/requested, as each new addition increases the time to build the project. 

I'm curious to know why you need a Docker image for Intel 32-bit. Are you running Docker in a 32-bit host?

**Comment by karmanyaahm** [comment]
Yes, I'm using an old laptop as that's the only server I have access to that has storage available.
