### ISSUE TITLE
Downloads don't work on iOS/iPadOS PWA

### ISSUE THREAD

**Issue by certuna** [navidrome/navidrome#1264]
When running the Navidrome WebUI in Mobile Safari on iOS/iPadOS, downloads work as expected (i.e., they're saved in the default download folder of Safari).

When running Navidrome as PWA on the same platform, downloads do not work: click the download link, nothing happens.

Apparently this is a known issue, discussed here: https://developer.apple.com/forums/thread/119017 and can be solved with this bit of code (the case below refers to downloading an .xml file):

```
function download(content)
{  
     var file = new Blob([content], 
                    { 
                         type: 'text/xml;charset=UTF-8' 
                    });
     var reader = new FileReader(); 
     reader.onload = function() 
                    { 
                         var popup = window.open(); 
                         var link = document.createElement('a');
                         link.setAttribute('href', reader.result);
                         link.setAttribute('download', 'filename.xml');
                         popup.document.body.appendChild(link); 
                         link.click(); 
                    } 
     reader.readAsDataURL(file); 
}
```

Would this workaround be easy to implement?

**Comment by deluan** [comment]
Unfortunately this would load a complete base64 encoded version of the file in memory, before saving the file to disk. For a song it would work ok, but for a large album or an artist's discography, it could use too much memory and completely freeze the PWA (or even the phone).

Some insights on Blob's memory usage (from https://stackoverflow.com/a/43816041): 

**Safari (10.1+ or perhaps earlier):**
No apparent hard limit. It does not use disk space to back larger blobs, so it all goes in memory, potentially with the operating system paging memory to disk. This means that blobs larger than memory may be possible, though likely with bad performance.

**Comment by certuna** [comment]
Hmm...there could be a filesize check with an arbitrary limit (say, 200 MB?), but that might be a bit too much work for just one platform - one that doesn't handle PWA's that well anyway. But if someone with more JS skills than I have wants to tackle this, feel free :)

**Comment by certuna** [comment]
Thinking about this some more, Navidrome could be set up to download individual songs sequentially, instead of a single .zip of songs.

**Comment by deluan** [comment]
Maybe... it could still have issues with very large songs (Close To The Edge, Autobahn, ...) and maybe podcasts/audiobooks.... WHat is the status of Chrome (or Firefox) PWA's on iOS? Maybe this could be an alternative?

**Comment by certuna** [comment]
If I'm not mistaken, PWA's all use the same (Safari) engine. But I saw a couple of methods here: https://stackoverflow.com/questions/2339440/download-multiple-files-with-a-single-action/9425731#9425731 . There's a bit of a divergence what "Download" does on mobile vs desktop - on desktop browsers you can "save as" into a folder of your choice, with mobile browsers (Android/Apple) downloads automatically gets dumped into the Download folder, which you set once in the settings.

**Comment by certuna** [comment]
This has been fixed by Apple in iOS 16, can be closed.
