### ISSUE TITLE
Mobile web interface animates cover art when EnableCoverAnimation is set to false

### ISSUE THREAD

**Issue by mill1000** [navidrome/navidrome#1265]
### Description

When EnableCoverAnimation is set to false the cover art is still animated on the mobile web interface.

### Expected Behaviour

The cover art is not animated.

### Steps to reproduce

1. Set EnableCoverAnimation to false in configuration or via ND_ENABLECOVERANIMATION
2. Confirm that cover art does not animated in desktop web interface.
3. See that cover art does animated in mobile web interface.

### Platform information

 - Navidrome version: 0.44.1
 - Browser and version: Firefox For Android 90.1.3
 - Operating System: Android 9

### Additional information

It's really not a deal breaker. Just an inconsistency.

![image](https://user-images.githubusercontent.com/6924622/127744973-2fd8a9eb-62fd-4ecc-8615-c67e1fb37c22.png)

**Comment by deluan** [comment]
This is not a `bug`, as it is works as intended and is [documented](https://www.navidrome.org/docs/usage/configuration-options/#available-options): 

> EnableCoverAnimation: Controls whether the player in the UI will animate the album cover (rotation) in **desktop mode**

IMHO, if we remove the animation from the mobile player, it will become very dull.

I'll change the issue type to "enhancement", and if anyone else think this is a good idea I can try to implement it (as this has to be "hacked" into the upstream react-player project)

**Comment by mill1000** [comment]
Ah I had missed that bit. Thanks.

Re: dull player. Personally, I don't see the need for a player to be "flashy". Plenty of apps use static cover art and are still polished interfaces. I'd rather see the cover art in it's entirety instead of truncated version that's upside down half the time. If I wanted visualizations, I'd go for visualization. 

But perhaps I'm barking up the wrong tree and I should raise an issue with https://github.com/lijinke666/react-music-player

Thanks for your work. Really enjoying the project overall.
