### ISSUE TITLE
Hiding [Unknown-Album] 

### ISSUE THREAD

**Issue by daviddavo** [navidrome/navidrome#1276]
### Is your feature request related to a problem? Please describe.

When you go to Random Albums, most of them are just [Unknown-Album] with one or two songs

### Describe the solution you'd like

Add the possibility to ignore certaing albums/artists in Random View

### Describe alternative solutions that would also satisfy this problem

Treating it as a whole album: Setting it as a compilation or with the same album artist seems to fix the problem in the meantime

### Additional context

![image](https://user-images.githubusercontent.com/10263941/128010508-063a0762-01a0-472c-ad2d-cefbdf55ef32.png)

**Comment by metalheim** [comment]
I agree that there is audio content that does not fit the vinyl/tape/CD based paradigms of categorization into "albums" that tag systems like id3 and vorbis depict.
An the amount of content like this gets more, as distribution forms evolve. 

But, in your case, it looks like you're just too lazy to tag your audio properly? (not trying to be rude, I certainly have some messy tagging in my library) 

If you don't want those files shown, maybe just move them them from your library folder, or exclude them by putting an `.ndignore` file in their respective folder?

Sorry again if I come across a blunt, but i don't see why you would need a navidrome feature to "fix" your library.

**Comment by deluan** [comment]
Hey @daviddavo, thanks for using Navidrome. What I do in these cases is create a fake album, something like: "Rarities" or "Outtakes" to group all dangling songs from an artist together.

Or if you don't want these songs in your collection, the best solution is to do what @metalheim suggested: remove them from your library or just ignore them.

We have plans to introduce more album filters in the future (ex: release type, label...) and depending on the UX we may add a filter like the one you are proposing, but I'm not 100% convinced this is a good thing.

**Comment by certuna** [comment]
What could be done is auto-hide any `[Unknown Album]` from the Album view, client-side. That way the songs still pop up in the Songs view but not in the Albums view.

**Comment by daviddavo** [comment]
Yeah, I ended up creating a script that is called every time I import an album with beets. The script puts all the "singletons" in a single album with `Various Artists` as albumartist, and compilations set to True. 

My idea was to do something like the "Single Tracks" option from Cantata (mpd client)

![image](https://user-images.githubusercontent.com/10263941/128672913-83df4705-29cc-4a9b-a136-14ef58fe60f7.png)

**Comment by certuna** [comment]
You could also tag singletons with "Singleton" in either the Grouping or Release Type field, and then smart filter, like set the Albums view to exclude Podcasts, Audiobooks and Singletons. I think @deluan had some plans in that direction?

**Comment by flemmingss** [comment]
Old  feature request but I am bumping i as it is still a issue.
In my case I have all my albums and releases tagged correct. But I also have folders with tracks that should not be associated with albums (individual tracks), so they don't have album or album artist tagged to them.

![image](https://user-images.githubusercontent.com/25674067/197184361-44eacd31-0faf-4ba5-848d-35a668916f4b.png)

What @deluan and @daviddavo is describing is not solutions, but workaround.
The software should definitely be supporting non-album tracks in a better way. They should either not be visible under "Albums" or be grouped into one single **[Unknown Album]**
