### ISSUE TITLE
Possible bug with Recently Added

### ISSUE THREAD

**Issue by RandomBloke85** [navidrome/navidrome#1279]
Hello

First let me thank for that fantastic piece of software you've developped. It's small, easy to setup and super fast. So I'm very happy.

The only issue I have is it does not show updated Albums, only new Albums added to the directory (without cover).
Im running version 0.40.0-FREEBSD (8799358) in a TrueNas 12.2 jail behind a nginx proxy installed from pkg install.
Adding `RecentlyAddedByModTime = true` to the config.toml does not make any difference. (also query string in browser is the same)
Connecting to the server directly (with IP) or through the proxy doesn't make any difference.
Recently Played and Most Played show correctly.

LogitechMediaServer, installed in another jail, shows the updated Albums. The music directory in Navidrome shows the updated date after changes were made on an album, so my question is, what date column in the database is Navidrome quering? Maybe it would be possible to offer more choices, so that it can scan the correct column. That's a suggestion from a non-programmer, so excuse me, if that's make no sense...

Thank you

**Comment by deluan** [comment]
Hey, sorry for the long delay. I lost track of some tickets and I'm going through the whole backlog now checking any missing ones. Are you still having this issue with the latest versions?

**Comment by RandomBloke85** [comment]
Hey, thank for getting back to this issue.

I'm still on 0.40.0-FREEBSD (8799358) since pkg upgrade on FreeBSD doesn't give me the latest version. I would install it manually if I knew how to do this.

However, for some reason, if I install a completely new album, it shoes in the "Recently added" section. If I change the directory of an album it also shows in "Recently added". So obviously as long as a change gets a new folder, it shows is an addition. If I only change some tags, it won't show in the "Recently added" section. But I would regard this as a minor issue in an otherwise flawless and really great and very usefull program. Thank you for spending your time in developping such a gem.

Kind regards

**Comment by deluan** [comment]
Yeah, the album is considered "new" if it is a new combination of artist/album names. If this combination is already present in the library, it is not considered a new album. Does that match what you are experiencing?

**Comment by RandomBloke85** [comment]
Yes, that's exactly how I experienced it. It would be "deluxe", if it would be considered as new, when I change, let's say, a title. But it is perfectly fine as it is.

Cheers

**Comment by deluan** [comment]
Great! You may be able to achieve this when we introduce smart playlists, by sorting the albums by "data modified" field. For now , I'm closing this, but feel free to reopen if you have any other concern related to this.
