### ISSUE TITLE
Some songs categorized to [Unknown Album]

### ISSUE THREAD

**Issue by nuts-i77** [navidrome/navidrome#1283]
### Description

Some songs categorized to [Unknown Album]

### Platform information
 - Navidrome version: 0.44.1
 - Browser and version: chrome 92.0.4515.131
 - Operating System: CentOS 7, and using binary

### Additional information
I tried the following, but it didn't work.
* quick scan, full scan from WebUI
* Run "navidrome scan -f" command on server

Here is the screenshot.
![screenshot](https://user-images.githubusercontent.com/88721791/128872363-4e8107e4-aa78-408e-b6b3-c801446c528f.png)

The song can be played correctly.

I thought the id3 tag of the file was invalid, so I checked it with the ffmpeg command and it looks right.
![screenshot2](https://user-images.githubusercontent.com/88721791/128872876-ad64279b-af6b-4baa-91c3-c59d3451f4ec.png)
Other songs in the same folder and over 20000 songs in other folders are correctly categorized.

Is there anything else I should check?

Thank you

**Comment by deluan** [comment]
Thanks for reporting. Can you please attach the output of the `ffmpeg` command above as text? Or attach one of the songs from the problematic album?

**Comment by nuts-i77** [comment]
Thank you for your reply.

Here is output of the ffmpeg command.

```
# ffmpeg -i "/mnt/share/Angela Aki/ANSWER/HiRes/10 - リフレクション.flac"
ffmpeg version 3.4.8 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-39)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' --extra-ldflags='-Wl,-z,relro ' --extra-cflags=' ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libcdio --enable-libdrm --enable-indev=jack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopus --disable-encoder=libopus --enable-libpulse --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzvbi --enable-avfilter --enable-avresample --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-libmfx --enable-runtime-cpudetect
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, flac, from '/mnt/share/Angela Aki/ANSWER/HiRes/10 - リフレクション.flac':
  Metadata:
    COMPOSER        : アンジェラ・アキ
    TITLE           : リフレクション
    ARTIST          : Angela Aki
    ALBUM           : ANSWER
    GENRE           : JPop
    album_artist    : Angela Aki
    disc            : 1
    DATE            : 2015
    track           : 10
  Duration: 00:04:18.83, start: 0.000000, bitrate: 3115 kb/s
    Stream #0:0: Audio: flac, 96000 Hz, stereo, s32 (24 bit)
At least one output file must be specified
```

**Comment by deluan** [comment]
The output works correctly with `ffmpeg` extractor. Maybe `taglib` has issues with it? If you can, please send the file to _issues @ navidrome.org_ so I can take a look. 

In the meantime, you can try using the `ffmpeg` extractor. Just set the `Scanner.Extractor="ffmpeg"` in your configuration. You may need to delete all files in the data folder so Navidrome starts from scratch.

**Comment by deluan** [comment]
Thanks for the file. I don't see any issues when using the latest develop build:

<img width="1551" alt="Screen Shot 2021-08-10 at 8 32 47 PM" src="https://user-images.githubusercontent.com/331353/128952050-5a7d59b0-3beb-40a2-b8f1-2ff89224e8fb.png">

There were some changes in the scanner, so you can try with the latest develop build, or wait for the next release (probably this weekend)

**Comment by nuts-i77** [comment]
Thank you for your swift response.
When I changed Scanner.Extractor to "ffmpeg" in navidrome 0.44.1, the issue did not occur.

I would like to see if this issue will occur in the next release.

**Comment by nuts-i77** [comment]
I tried Navidrome v0.45.0 and it worked perfectly!
This issue will be closed.
