### ISSUE TITLE
Navidrome web player stalls (stops playing) before track is finished

### ISSUE THREAD

**Issue by blunderberg** [navidrome/navidrome#1286]
### Description

This is an intermittent issue I have seen happen more frequently with Navidrome versions 0.44.0 and 0.44.1

Before a track reaches the end, the web player stops playback. It usually happens near the end of a track, but I have seen it happen a few times 2/3 through a track.

### Expected Behaviour

Keep playing.

### Steps to reproduce

Play 200 random tracks by navigating to "Songs" and pressing "Shuffle all".
After a few tracks (can be 3 can be 15 etc.), the web player stops playback before the end of a track is reached.

### Platform information

 - Navidrome version: v0.44.1
 - Browser and version: Firefox v91.0, Chrome 92.0.4515.131, Edge 92.0.902.73, Brave 1.28.105
 - Operating System: Windows 10 Pro client connecting to Ubuntu 20.04 server running Docker container

### Additional information

This happens on Firefox, Chrome, Edge, Brave in a regular browser instance or PWA. Android DSub never stalls.
There seems to be no consistency with which tracks stall and at what point during playback.
When I look at the network tab on the browser developer tools, every "stalled" track shows "CAUTION: request not finished yet!", but when I open the stream in a new browser tab (right click context menu), the new tab plays the track in its entirety.
If there is enough "space" on the track progress bar when it stalls in Navidrome, clicking on the not yet played portion of the track (advancing it) continues playback and finishes the track OK. Skipping the stalled track by clicking on "Next track" continues the playback from the queue.

![web player stalled](https://user-images.githubusercontent.com/83293651/129465711-aa7336e0-ec68-4e47-b269-d9e4137be30f.PNG)

![request is not finished yet](https://user-images.githubusercontent.com/83293651/129465708-26dcd1de-79f7-455a-b122-a27c82c6053f.PNG)

![track in new tab](https://user-images.githubusercontent.com/83293651/129465833-c38d1189-b19a-4d73-84f3-19bf8485380f.PNG)

**Comment by doggogoesbork** [comment]
Can confirm, have the same issue. happens with a 200+ long playlist as well

**Comment by wanieru** [comment]
I have this issue as well, using Firefox. Happens even with short playlists, but especially long tracks (20+ minutes). However, for me the track doesn't resume when clicking on the unplayed part of the track bar.

**Comment by v1sor** [comment]
Can confirm that this is happening while I listen to a 74 track playlist. It's as though Navidrome cuts the track off early and starts the next one. The worst one so far was a good 1'15" from the end of a particularly good song.

Playing that same song directly from the share does not exhibit this behaviour.

**Comment by pavulongit** [comment]
I can confirm having this issue as well. Happens on Firefox with even small playlists (6-10 tracks). Version 0.45.1 in docker.

**Comment by doggogoesbork** [comment]
This issue is seemingly more persistent on the newer docker versions, to the point where I cannot use the webUI for more than 2 songs on any browser.

Firefox seems to be capturing no useful logs with the developer web / browser consoles since the entire tab freezes when this occurs. Edge reports that the tab is no longer responding as well.

let me know what can be done to give you useful logs

**Comment by deluan** [comment]
> This issue is seemingly more persistent on the newer docker versions, to the point where I cannot use the webUI for more than 2 songs on any browser.
> 
> Firefox seems to be capturing no useful logs with the developer web / browser consoles since the entire tab freezes when this occurs. Edge reports that the tab is no longer responding as well.
> 
> let me know what can be done to give you useful logs
> 
> tbf my music library is quite large, I have noticed my data base is 74 mb big (my library is about 600 gb in size)


Hey @doggogoesbork I think your issue is something different, related to #1186. Check if the workaround on that thread (setting `DevActivityPanel=false`) works for you.

Also for others having this issue here, can you please check if the workaround above makes it better?

**Comment by doggogoesbork** [comment]
> 
> 
> > This issue is seemingly more persistent on the newer docker versions, to the point where I cannot use the webUI for more than 2 songs on any browser.
> > Firefox seems to be capturing no useful logs with the developer web / browser consoles since the entire tab freezes when this occurs. Edge reports that the tab is no longer responding as well.
> > let me know what can be done to give you useful logs
> > tbf my music library is quite large, I have noticed my data base is 74 mb big (my library is about 600 gb in size)
> 
> Hey @doggogoesbork I think your issue is something different, related to #1186. Check if the workaround on that thread (setting `DevActivityPanel=false`) works for you.
> 
> Also for others having this issue here, can you please check if the workaround above makes it better?

nice catch, that seems to resolve my main issue.

though to be clear, I did have the separate audio pausing in the middle here as well, though it was separate and less common. I will see if after a few days, if this fixed that issue as well

**Comment by pavulongit** [comment]
> > Hey @doggogoesbork I think your issue is something different, related to #1186. Check if the workaround on that thread (setting `DevActivityPanel=false`) works for you.
> > Also for others having this issue here, can you please check if the workaround above makes it better?

The workaround did not help in my case, but now I tend to think that I'm experiencing a different issue. In my case almost every track skips to the next one after reaching 2/3 or so  duration. I've noticed it only happens when transcoding is enabled. Also, only  Navidrome UI is affected. Mobile clients do not show this behaviour.

**Comment by sdrnk** [comment]
Same issue. Running Navidrome through Cloudflare Tunnel and playback freezing all time. If click to pause playback then track starting from the start. Trying different frontend clients, but no luck. DevActivityPanel=false don't help.

**Comment by AQUOSTICS** [comment]
Same issue, having Navidrome running on my home server. It looks like it only happen when I try to access it using my domain. If I directly access it by typing the ip +port then I did not run into this issue.

I did some investigations and it **seems** like this happened to me because I am streaming flacs files(30mb - 40mb) without using slice on my Nginx reverse proxy server. That means each GET request will try to download the entire flac in one go(from what I understand? sorry I am not an expert in networking stuff :/).

After changing my reverse proxy server, I was able to listen to flacs that's around 4:40 min(usually around 40 mb) for 7 songs straight without a pause. I will let it run for the whole night to see if this still happen. I will come back to this thread once I have more test results.

Can't promise that this is a 100% fix tho :/

**Comment by AQUOSTICS** [comment]
Same issue here. If I access my server using my domain name, then I will run into this issue eventually, also more often if songs are huge(40~50mb). If I access it locally using the server IP with port then I have no issues at all. My assumption is that maybe my reverse proxy server is not configured correctly, but I am not confident.

**Comment by nekr0z** [comment]
Still the same behavior.

**Comment by blunderberg** [comment]
For those that are still struggling with this issue, I can confirm that (in my case) the problem was related to the HTTP/3 QUIC protocol (not a Navidrome issue).
As suggested by a few others in this thread, the issue can be addressed by ensuring that your reverse proxy supports and is configured for HTTP/3 QUIC, or by turning off the QUIC protocol on the client side (browser configuration), or by disabling HTTP/3 (with QUIC) feature on Cloudflare.
Thank you all who provided input and comments.
Navidrome rocks!
