### ISSUE TITLE
Prioritize User's Playlists on top of Playlist List

### ISSUE THREAD

**Issue by ghost** [navidrome/navidrome#1290]
When adding to or accessing the playlists, if there are many shared playlists - it is difficult to find playlists created by me, the current logged in user.

It would be nice if the current user's created playlists were located at the top of any lists - like dropdowns and pageviews, putting the shared playlists after the user's.

**Comment by deluan** [comment]
Playlists will be moved to the sidebar (similar to iTunes), and the user's playlists will be displayed first as you suggest. While we don't have that, I can easily introduce a filter by user. Does that helps?

**Comment by TheFlatworm** [comment]
Yes! That would be so much better. Would playlists be collapsible in the
sidebar?  If so that would be great.

**Comment by deluan** [comment]
> Would playlists be collapsible in the sidebar? If so that would be great.

That's the idea. One "folder" for the user's own playlists and another for shared playlsists.

**Comment by deluan** [comment]
Hey @TheFlatworm , latest develop build has the first implementation of this:
<img width="290" alt="Screen Shot 2021-09-11 at 2 16 52 PM" src="https://user-images.githubusercontent.com/331353/132957485-8cf3896e-7c2d-46cc-9426-3ca382a80218.png">

To try it, set `DevSidebarPlaylists=true` in your config options

**Comment by TheFlatworm** [comment]
Tried this and it is really great. I was thinking at first that the
playlists shouldn’t be displayed in the side bar, but rather the side bar
would have PLAYLISTS/SHARED PLAYLISTS and when clicked it would open the
previous interface for playlists in the main window.  But after using this
for a while this is a good solution as well!

**Comment by TheFlatworm** [comment]
I did notice that the COLLAPSED/EXPANDED state does not persist between logins - it always initiates expanded. Would the state be able to be implemented or a choice to start expanded or collapsed?

**Comment by deluan** [comment]
This is an old TODO: To store the state of any collapsed "folder" in the menu (it is the same for the "Albums"). Will try to fix this for the next release
