### ISSUE TITLE
Error creating data path

### ISSUE THREAD

**Issue by devilliersjohnny** [navidrome/navidrome#1291]
Hi am attempting to run the project in docker... have tried everything under the sun, keep hitting "Error creating data path" I however have created all the other containers in the same directory without issues?! Am using a .env file to make sure that all is the same and so that I can replicate my containers at any time... looking at container details from inside portainer the only thing that seems amiss is the PATH environment variable, it currently reads  `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin` some advice would be much appreciated as this project looks VERY! PROMISING!

**Comment by deluan** [comment]
> this project looks VERY! PROMISING!

Thanks!

Are you using a non-root user? Check permissions on the directory you specified as the data volume. If using docker-compose, please attach the docker-compose.yml file  here and also some logs

**Comment by devilliersjohnny** [comment]
Am the sole user of the system... have created a non root user with sudo permissions and am the owner of all the directories using the chown directive, my testing ( Short compose file ) can be found here... https://pastebin.com/5qA8BBwm 

Logs from portainer... am still pretty new to this all, if there are any other ways of creating/viewing logs please let me know
_   _                 _     _
| \ | |               (_)   | |
|  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___
| . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
| |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
\_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|


                          Version: 0.45.0 (05e27095)

FATAL: Error creating data path: path /media/EPD/docker/server/navidrome mkdir /media/EPD: permission denied

**Comment by devilliersjohnny** [comment]
Hi found the problem.... on your website, your docker-compose file reads

version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "/path/to/data:/data"
      - "/path/to/your/music/folder:/music:ro"

It Should instead Read
Take note of the PUID and PGID

      
version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=TIME/ZONE
      # Optional: put your config options customization here. Examples:
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=info  
      - ND_SESSIONTIMEOUT=24h
      - ND_BASEURL=""
    volumes:
      - "/path/to/data:/data"
      - "/path/to/your/music/folder:/music:ro"     
    ports:
      - "4533:4533"
    restart: unless-stopped

**Comment by devilliersjohnny** [comment]
Hi found the problem.... on your website, your docker-compose file reads

version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "/path/to/data:/data"
      - "/path/to/your/music/folder:/music:ro"

It Should instead Read
Take note of the PUID and PGID

      
version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=TIME/ZONE
    volumes:
      - "/path/to/data:/data"
      - "/path/to/your/music/folder:/music:ro"     
    ports:
      - "4533:4533"
    restart: unless-stopped

**Comment by deluan** [comment]
Are you sure? PUID and PGID are not used anywhere in Navidrome's Dockerfile...

**Comment by devilliersjohnny** [comment]
100% It allows for the rights to use the file structure to reach the target if the ownership is correct... it must be a built in security feature of Linux?! Linux is built on the security first principle... so it made sense to try it that way and it worked!! Feel free to play around with it a bit if you wish, but on a side note am setting up a tutorial on getting an entire webserver up and running would like to feature your product within it but may need help in configuring it optimally... would you be prepared to assist me with a step by step set up of your software so that I can showcase all of its features?

**Comment by deluan** [comment]
Yes, I can help for sure, it is better if you ask questions in Discord, as the discussion may benefit others as well.

Regarding the PGID/PUID, I have to do some testing, but this is news to me. For me this is a custom implementation inf the LinuxServer.io base image. Will sure play around with it.

**Comment by devilliersjohnny** [comment]
hmm... fine and well, if you think that, that is the best route?! But what I was saying is that I am also planning a full youtube channel covering the setup and that I have already figured out a way to serve your player over the software that I am using allowing for the complete spotify effect, but to be at the forefront I am going to be asking for an inside track...

**Comment by deluan** [comment]
Ah, ok. You can ping me directly in Discord.

Regarding the PUID/PGID, I just tested it here and could not set the user using these. Here is the results with PUID/PGID:
```
$ docker-compose run --entrypoint /bin/sh navidrome   
Creating data_navidrome_run ... done
/app # echo $PUID
1000
/app # id
uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
/app #
```

Now with [`user` ](https://docs.docker.com/compose/compose-file/compose-file-v3/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir) configured as in the doc site example, and without PUID set:
```
$ docker-compose run --entrypoint /bin/sh navidrome 
Creating data_navidrome_run ... done
/app $ echo $PUID

/app $ id
uid=1000 gid=1000
/app $ 
```

Anyway, I'm closing this as you got it working (right?)
