### ISSUE TITLE
Limit the size of the journal on disk

### ISSUE THREAD

**Issue by jvoisin** [navidrome/navidrome#1292]
### Description

The journal file of my navidrome database is bigger than the actual database:

```
$ ls -lh *.db*
-rw-r--r--    1 navidrom navidrom   63.2M Aug 19 15:52 navidrome.db
-rw-r--r--    1 navidrom navidrom  160.0K Aug 19 15:52 navidrome.db-shm
-rw-r--r--    1 navidrom navidrom   64.7M Aug 19 15:51 navidrome.db-wal
$
```

### Expected Behaviour

Have a super-small journal file on disk.

### Steps to reproduce

1. Run navidrome
2. Do a couple of re-scans and `vacuums`

### Platform information

 - Navidrome version: 0.45.0
 - Operating System: Linux

### Additional information

[`journal_size_limit`]( https://www.sqlite.org/pragma.html#pragma_journal_size_limit ) should likely be used.

**Comment by hg2s** [comment]
What do you mean by 'vacuums'? Is that a command? 

-Thanks

**Comment by bwat47** [comment]
@hg2s  https://www.sqlite.org/lang_vacuum.html

**Comment by Forceflow** [comment]
Do you often remove media? My journal file is smaller than my db file, but I generally only *add* music
