### ISSUE TITLE
API: failed response with "Internal Error" message when lastfm integration is enabled

### ISSUE THREAD

**Issue by michael-ball** [navidrome/navidrome#1293]
When using latest the latest navidrome (0.45.0) with Last FM integration enabled, I get an error popup in the DSub client when trying to view artist info.

The navidrome log shows the line:
Aug 20 11:55:07 hostname navidrome[4774]: time="2021-08-20T11:55:07+01:00" level=warning msg="API: Failed response" error=0 message="Internal Error" requestId=hostname/9cPSZIk1rv-000014

This happens for every artist I've tested.

**Comment by metalheim** [comment]
@deluan I guess that's the issue I sent you trace log for :)

**Comment by deluan** [comment]
Thanks for reporting! Can one of you attach (or send me) one song from one of the affected artists, please?

**Comment by deluan** [comment]
Found and fix the issue, with @simojenki's help.

**Comment by ryansalerno** [comment]
Ran into this and can confirm the pushed fix works for me now.
