### ISSUE TITLE
Next song always plays at 50% volume (Web UI 0.45.0)

### ISSUE THREAD

**Issue by wanieru** [navidrome/navidrome#1296]
### Description

In the Web UI, after listening to a song at, say, 20% volume, the next song to come up (either from skipping or the previous song ending) will play at 50%. The volume bar will appear to still be at 20%. Slightly nodging the volume slider will significantly reduce the volume back down.

### Expected Behaviour

The volume should play at the same as the previous song, reflecting the value of the volume slider.

### Steps to reproduce

1. Open the web UI
1. Queue multiple song
2. Reduce the volume around 5%
3. Notice the volume level
4. Skip to the next song
5. Notice the volume changing significantly
6. Nodge the volume to around 7-10%
7. Nodge it back down to 5%
8. Notice how the actual volume at 5% is much lower than the volume when the song started

### Platform information

 - Navidrome version: 0.45.0 
 - Browser and version: Firefox 91.0.1 (64-bit) 
 - Operating System: Windows 10

**Comment by deluan** [comment]
Thanks for reporting! Latest development build should fix it, can you please try it?

**Comment by wanieru** [comment]
Yep, it seems to work! Thanks a lot!
