### ISSUE TITLE
Volume & Volume Slider sometimes rises when skipping song (Web UI 0.45.0)

### ISSUE THREAD

**Issue by wanieru** [navidrome/navidrome#1297]
### Description

In the web UI, sometimes, the volume slider will start increasing every time the song is skipped, until maxing out at 100%.

### Expected Behaviour

The volume slider should not change until the user changes it.

### Steps to reproduce

1. Queue multiple songs
2. Change the volume slightly, between 2-10%
3. Skip to the next song
4. Notice if the volume slider rises. If not, repeat step 2.
5. Skip to the next song again.
6. Notice how the volume rises once again. Repeat step 5 until volume maxes out at 100%

### Platform information

 - Navidrome version: 0.45.0 
 - Browser and version: Firefox 91.0.1 (64-bit) 
 - Operating System: Windows 10 

### Additional information
Check out this video, I sent on the Discord, which shows the problem:
https://cdn.discordapp.com/attachments/671335427726114839/878021964978069604/Cy76d8BCWh.mp4

**Comment by deluan** [comment]
Thanks for reporting! Latest development build should fix it, can you please try it?

**Comment by wanieru** [comment]
Yep, it seems to work! Thanks a lot!

**Comment by mradermaxlol** [comment]
@deluan any ETA for the next release containing this fix?

**Comment by deluan** [comment]
Probably today. I'm trying to validate another fix, so it can be included in this bug fix release

**Comment by mill1000** [comment]
Using the latest commit c55e65902b8a6a8f455b9501c0e46f60924e41a6 I've noticed a strange volume slider behavior.

When starting playback the volume starts at 50%. I then increase volume to 100% and click next track. The slider jumps downward. Each new track the slider shifts slight more right until it reaches 100%.

![Animation](https://user-images.githubusercontent.com/6924622/130547272-6da7904c-c3c9-4c15-b2c5-6e0ee4c13cbf.gif)

**Comment by deluan** [comment]
@mill1000 Can you try with 0.43.0? This may be an issue with the upstream react music player...

**Comment by mill1000** [comment]
@deluan I tried downgrading to v0.43.0 but I can't seem to login. I wiped my database and cache but I keep getting "Error: Method Not Allowed" when trying to create a new admin user.

> Sep 03 18:49:27 RockHole navidrome[19800]: time="2021-09-03T18:49:27-06:00" level=warning msg="HTTP: POST http://rockhole:4533/auth/createAdmin" elapsedTime="72.332µs" httpStatus=405 remoteAddr="192.168.1.136:50919" requestId=RockHole/pUC8gHLfDu-000022 responseSize=0 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0"

**Comment by deluan** [comment]
Ops, I forgot to tell you you'll need to use a fresh installation for this test with 0.43.0. The databases from 0.44.0 and 0.43.0 are not compatible.

**Comment by mill1000** [comment]
I thought I blew them away but I'll give it another shot.

**Comment by mill1000** [comment]
No luck. Removed the database files and cache form `/var/lib/navidrome`. Is there something incompatible in the config file between 0.43 and 0.44?

**Comment by mill1000** [comment]
NVM. Got it working. I was building my own release of 0.43 instead of grabbing it from releases.

This volume issues does **not** appear to be present in v0.43.0.

**Comment by deluan** [comment]
Thanks for the feedback. Will take a look.

**Comment by mill1000** [comment]
@deluan You can close this after all. I've been building my own releases and I've just noticed that `make single` does not build the frontend. All along I've been testing with an updated backend and an out of date frontend.

Using the official v0.45.1 release I am not seeing this volume issue.

**Comment by deluan** [comment]
Great it worked! I added a warning message to all make targets that only build the server, thanks for the tip.
