### ISSUE TITLE
Source for v0.45.0 missing .gitinfo file

### ISSUE THREAD

**Issue by whorfin** [navidrome/navidrome#1302]
This is a trivial "oops" complaint, but still seems worth noting:

#1250 provided the foundation to fix #1224 

Unfortunately the `.gitinfo` file is missing from the tarball for v0.45.0
https://github.com/navidrome/navidrome/archive/refs/tags/v0.45.0.tar.gz

Manually plonking this in there fixes it right up:
```
export GIT_SHA=05e2709
export GIT_TAG=v0.45.0
```

**Comment by deluan** [comment]
I think the whole `.gitinfo` implementation is a fiasco. It is not used when GH packs the source code for release. The only way around it is to add `.gitinfo` (or similar file) to the source code and commit it, which I don't think it makes sense

Thinking about this, I'm not sure if it makes sense to embed the version in the source code tar ball at all. Although this is a common practice in applications written in interpreted languages (JS, Python, Ruby) this is usually not done with compiled languages (Go, C++, Rust...) I checked other projects (ex: GoReleaser) and they do the same as Navidrome.

**Comment by whorfin** [comment]
If this isn't done, building from source results in an unknown version, which seems like a bad idea.
I find it immensely useful to see what version is running when consulting the logs.

Most of the CLI tools I build from source handle this, for example `tmux` and `ffmpeg`, for obvious reasons.
`tmux`  passes the version from the makefile as a define, with it baked into the configure script
`ffmpeg` uses a script which looks at git, the name of the source directory being built and other inputs
Given that the navidrome tarball already results in a name such as `navidrome-0.45.1`, you could try the `ffnpeg` method which falls back on parsing the source directory name if there's no git.
See eg
https://github.com/FFmpeg/FFmpeg/blob/n3.0/version.sh

I don't quite understand why whatever pipeline mechanism creates the "named release" directory couldn't also populate .gitinfo and include it, untracked by git just like a binary, as part of the "build" for the tarball.  But in any event if it's easier, perhaps the "just use the build source directory name" would be convenient enough, while still providing useful information.

**Comment by deluan** [comment]
> I don't quite understand why whatever pipeline mechanism creates the "named release" directory couldn't also populate .gitinfo and include it, untracked by git just like a binary, as part of the "build" for the tarball.

That's what I tried to do. The issue is that the source tar ball is created by GitHub itself, and it gets it directly from the git repo, not from the pipeline. Also, if you download the source tar ball from GitHub "download" option, the download will be named `master.zip`:
<img width="935" alt="Screen Shot 2021-09-03 at 8 20 55 PM" src="https://user-images.githubusercontent.com/331353/132076233-dc88aae2-5994-4ea5-beb2-e1ff5a53dd47.png">

If you want to contribute with a script like ffmpeg's, I'd be happy to add it to the project

**Comment by whorfin** [comment]
Right.  I wouldn't expect the `master.zip` download to have the right version.
But OK now that makes sense if the pipeline isn't making the source tarball.
I'll submit a PR for an easier way to do the directory parsing, see what you think.
