### ISSUE TITLE
Option to toggle recently played for all users or current user

### ISSUE THREAD

**Issue by ghost** [navidrome/navidrome#1305]
In the Recently Played section of the album lists - an option to show what all users recently played as well as an option to show what the logged in user recently would be great.

**Comment by deluan** [comment]
Thanks for the suggestion! This will be possible as part of Smart Playlists: You'll be able to create a playlist sorted by `global recent played` (or similar) and select the view to Album (or Song if you prefer).

> as well as an option to show what the logged in user recently would be great.

I didn't get this part.... Can you please elaborate?

**Comment by TheFlatworm** [comment]
Sorry about the non clarity. If I’m logged is as “bill” it would be nice to
be able to to toggle between what every user on the server has recently
played and just what “bill” has recently played. Would that be possible
with smart playlists?

**Comment by deluan** [comment]
Ah, got it! Well, not with one smart playlist, you'd have to have two of them, one with `global recently played` and another with `recently player`. I don't think a toggle would be a good UX in this case, as it would be very "unexpected". I'll keep this open so I can come back to this later, or others can chime in with different ideas.

**Comment by TheFlatworm** [comment]
Great. Thank you.

**Comment by sprnza** [comment]
Hi @deluan ! I can't find this feature in the Smart Playlists issue. Was it implemented so far?

**Comment by deluan** [comment]
Hey, this is not possible yet. I'm looking into how to make this available in the next release.
