### ISSUE TITLE
getAlbumList2 / getAlbumList API for type recent returns no data but web UI shows recent albums

### ISSUE THREAD

**Issue by ghenry22** [navidrome/navidrome#1306]
### Description

Get Recently Played Albums from API returns no results when there are recent plays shown in the web interface.

### Expected Behaviour

Get recently Played Albums from the API will return the same list of albums as shown in the web UI.

### Steps to reproduce

Setup a new navidrome instance
Add some music
Play songs from a couple of albums and see in the web interface recent section they now show up
Grab a subsonic client app (or call the API manually) and see that the recently played returns no results.

### Platform information

 - Navidrome version: 45.0
 - Browser and version: latest chrome / substreamer
 - Operating System: n/a

### Additional information

Any other information that may be relevant or give context to the problem.

This is the API req from the navidrome logs, no errors in the request
HTTP: GET http://192.168.86.31:4533/rest/getAlbumList2.view?u=ghenry&t=[REDACTED]&s=[REDACTED]&v=1.13.0&c=substreamer&f=json&type=recent&size=20"

Screencaps from web ui and debug console when requesting the same from the API
![image](https://user-images.githubusercontent.com/7463213/130930527-64f10fbf-5325-415d-8d99-4931a4360a24.png)
![image](https://user-images.githubusercontent.com/7463213/130930556-c2a08a20-edbc-4812-86f1-6c4d992e73e7.png)

**Comment by deluan** [comment]
Hey @ghenry22, sorry for the long delay. Yes, the UI uses a different API, but the result should be exactly the same. I'll take some time this week to work on pending tickets, and will take a look at this.

**Comment by ghenry22** [comment]
@deluan yeh I figured that the subsonic api probably just transforms and forwards request so likely something going missing in translation versus something fundamentally broken

**Comment by deluan** [comment]
Hey @ghenry22 , sorry but I was not able to reproduce this. You can even check the demo instance and point a subsonic cliente to it, and it is working as intended (I tested with my personal instance, my test instance and the demo). Are you sure you were using the same user in both situations?

**Comment by ghenry22** [comment]
@deluan ok let's make this slightly weirder still...

Logged into demo.navidrome.org (user demo) with chrome
played a song from Maya filipic album in the webUI
recently played in the webUI does NOT update

Logged into demo.navidrome.org (user demo) with substreamer
played a song from VOODOOCUTS album in substreamer
recently played in the webUI AND the subsonic API response does NOT update

So now I am really confused...

drop me a note at ghenry22.apps@gmail.com if you want to take a look at it together.

**Comment by ghenry22** [comment]
@deluan If I call the scrobble API then the recent play is updated on both the webUI and API response.

Fix might be: when the getStream API endpoint is called update recently played based on the streamed track ID.

**Comment by deluan** [comment]
@ghenry22 thoughts?

**Comment by ghenry22** [comment]
If I hit the scrobble API with submission=true does this only submit to the navidrome server or does it also scrobble this to last.fm?

Airsonic-advanced & subsonic will always update the recently played list when the stream end point is called (just tested both).  They will update the "now playing" in the web UI also if the scrobble end point is called.

So in substreamer for example I have a setting where people can choose if they want to scrobble to lastfm (as long as it is enabled on their server).  If they don't want to then I don't call the scrobble end point and plays on the server are tracked by the stream calls.  If they do want to then I call the scrobble API.

It looks like whether submission=true or false in the scrobble API request the server will still try to scrobble to lastfm if it has credentials, is this correct?  This would be my only real issue with not tracking plays on stream (and inconsistency with other *sonic variants).

**Comment by deluan** [comment]
> If I hit the scrobble API with submission=true does this only submit to the navidrome server or does it also scrobble this to last.fm?

Different from Subsonic/Airsonic, Navidrome uses Last.fm APi 2.0, so the user must authorize ND to send scrobbles. This is done in the "Personal" screen. So by default, ND does not send any scrobbles to Last.fm

> Airsonic-advanced & subsonic will always update the recently played list when the stream end point is called (just tested both). They will update the "now playing" in the web UI also if the scrobble end point is called.

Ok, but do you agree that this can cause the play counts and last played info to be inaccurate, as the client can simply call `/stream` to cache/download songs without playing?

> 
> So in substreamer for example I have a setting where people can choose if they want to scrobble to lastfm (as long as it is enabled on their server). If they don't want to then I don't call the scrobble end point and plays on the server are tracked by the stream calls. If they do want to then I call the scrobble API.

When using Navidrome, sending scrobbles is indispensable as discussed before, but the user still has the choice to not send anything to Last.fm. They would need to enable it (as described above), and they can even disable communication with Last.fm altogether, if they want to do so.

> It looks like whether submission=true or false in the scrobble API request the server will still try to scrobble to lastfm if it has credentials, is this correct? This would be my only real issue with not tracking plays on stream (and inconsistency with other *sonic variants).

As I said, only if the user authorizes ND to send the scrobbles to Last.fm. If you want to discuss this more, let's do it over Discord

**Comment by ghenry22** [comment]
Other subsonic forks are the same, you need to add your lastfm API key on the server before you can scrobble to last.fm.

I don't disagree with the approach you have taken, my problem is that it is different to the way any other subsonic forks work.  Any other server records plays from the stream api and uses the scrobble API to scrobble to last.fm.  This means I can have an easy switch in the APP settings to allow users to turn last.fm scrobbling on or off (again provided they have configured their last.fm credentials on their server).

How about this:
IF scrobble is called with submission=true, record the play on navidrome server only
IF scrobble is called with submission=false, scrobble to last.fm

This makes everything work and from reading the subsonic API docs is how this was supposed to work in the first place.

**Comment by ghenry22** [comment]
@deluan I will close this one. After some research and testing I have implemented a similar strategy in substreamer to what you are using in the navidrome webui.  Submit now playing on start and submit scrobble on playback complete.  For anyone who finds this in the future funkwhale was using the scrobble API in a similar way as well and this change on the client side keeps things working for original server forks and these newer implementations.
