### ISSUE TITLE
Sort Albums By Folder

### ISSUE THREAD

**Issue by Horuyuki** [navidrome/navidrome#1309]
### Is your feature request related to a problem? Please describe.

Sometimes my music is not perfectly tagged, being able to just have the album organized by folder would be nice. Or a directory browsing method.

### Describe the solution you'd like

1. Option to or default to sort album by folder

### Describe alternative solutions that would also satisfy this problem

1. Browse music by directory

### Additional context

I think things like foobar does have that function, I hope it ain't too hard!

**Comment by ghenry22** [comment]
Subsonic and the subsonic API support browsing by folder structure out of the box, might be worthwhile supporting in navidrome for compatibility.

In substreamer for example I have an albums section and a folders section and can browse either way or set a preference to only use one or the other.

**Comment by deluan** [comment]
Thanks for the suggestion. 

Unfortunately supporting "browse by folder" would require too much internal changes and it is out of the scope, but may be implemented in the future (but please don't hold your breath). Sorting by folder could be implemented, we are thinking of changing the sorting/filtering options in the web UI and this may be introduced. Again this would be low priority for now.

**Comment by tidux** [comment]
Any media software that runs on Unix and can't directly expose a filesystem it's reading media files from is wrong.  This should be considered a bug, not a feature request.

**Comment by crisclacerda** [comment]
A better alternative IMHO is the creation of crates (or collages or collections) entry in the db.

Much like playlists, crates are a collection of tracks. But unlike playlists, they are not meant for direct playback, but instead used for organizing the music. 
So for crates, it makes sense to be able to browse them much as you do for the whole library, view artists, albums, etc.
So they are a better alternative than plain folders and you can add a track to many crates.

To keep compability with the subsonic api, crates could be used for generating 'fake' paths. 

And for acomodating users who have already curated their library on folders crates could be auto created during the scan based on the folder structure.

**Comment by zrav** [comment]
Navigating by directory tree is absolutely essential. In my experience with a large music collection MusicBrainz recognizes about 80% of my tracks only. The other 20% remain untagged or tagged variable quality, so if the music server absolutely requires tags those tracks aren't discoverable.
