### ISSUE TITLE
Add genre navigation

### ISSUE THREAD

**Issue by tonydub** [navidrome/navidrome#131]
It would be really cool to be able to browse by genres in a Subsonic client (I use [play:sub](https://michaelsapps.dk/playsubapp/)) and in the web interface.

Is this planned soon?

**Comment by deluan** [comment]
Yes, it is. It will probably be available for the clients through the API, and not long after that in the UI. I'm still working on some other improvements and will tackle this next, maybe in a 2-4 weeks timeframe.

**Comment by mariof1** [comment]
@deluan do you think it will support multi tags? I am not sure if this will be possible to tackle multiple variations, for example
Rap/Hip Hop - expected `Rap` `Hip Hop`
Pop; Rock - expected `Pop` `Rock`
Pop; Rap/Hip Hop, Folk/Soul - expected `Pop` `Rap` `Hip Hop` `Folk` `Soul`

**Comment by deluan** [comment]
Yes it will. See #119 

My idea is to allow the separator(s) to be specified as a configuration. So in your examples, if this configuration is set to "`/,;`" it will work as you described.

Just keep in mind that for clients of the Subsonic API, songs and albums will only show the first genre, as the API does not support multi-genres. But you will be able to filter by genre and get songs/albums that lists that genre in their genre field (not all subsonic clients support filtering by genres, though)

**Comment by certuna** [comment]
In principle the id3v2 tag spec has a standard delimiter (the Modified UTF-8 termination code), see [section 4.2](https://id3.org/id3v2.4.0-frames):

`All text information frames supports multiple strings, stored as a null separated list, where null is reperesented by the termination code for the charater encoding.`

Similarly, multiple MP4 `gnre` atoms are also allowed.

Problem is that navidrome doesn't actually read the tags itself, but uses ffmpeg as an intermediary. So the question is more: how does ffmpeg return multi-field genres?

**Comment by deluan** [comment]
> The main problem with custom separators is always false positives - we don't want to accidentally split "AC/DC", "Earth, Wind & Fire", "Rhythm & Blues" or this album title containing ";" 

I'm not planing to apply this configuration to artists or albums, only to genre. As you said:

> If supporting unnormalized forms was easy, everyone would already have done it :)

Things like `featuring` and `vs` and `feat` would make it impossible.

**Comment by deluan** [comment]
@tonydub Browse by genre in Subsonic clients was released in [version 0.15.0](https://github.com/deluan/navidrome/releases/tag/v0.15.0).

I'm keeping this issue open to track work on the WebUI

**Comment by tonydub** [comment]
@deluan I've been successfully testing with my subsonic client. Thank you very much.

You're on the right track.

Will it be possible to edit the metadata later in the web interface?

**Comment by jvoisin** [comment]
I don't think that this fits into the scope of navidrome (a music player).
What about using beet or Picard instead?

**Comment by deluan** [comment]
@tonydub Not really. As @jvoisin said, there are excellent options out there. What I may do is add some kind of integration with these tools (ex: support the `beets` subsonic plugin)

**Comment by Extarys** [comment]
We could use chips to display multiple genres. Could also add `mood` below that eventually (really not a priority though)
https://material-ui.com/components/chips/

![image](https://user-images.githubusercontent.com/11581433/82480959-95649d80-9aa2-11ea-82b1-f7f1e2692096.png)

**Comment by deluan** [comment]
There are no plans to introduce `mood` ATM, but for `genres` I think it would be great!

**Comment by deluan** [comment]
Browsing by genre in the WebUI in now being tracked in #119

**Comment by LennertVA** [comment]
Please reopen this. 

> Browsing by genre in the WebUI in now being tracked in #119

Yes, but #119 was closed as implemented, because it had a different scope which did not include this.

Genre navigation is still not there.

**Comment by Extarys** [comment]
@deluan Check above comment
(Just in case you don't receive notifications when an issue is closed - sorry if you do)

**Comment by LennertVA** [comment]
I mostly access navidrome via a phone app so no huge loss. Still, I browse mostly via genre - I feel like hearing X today, then select albums from there. In the web UI now I have to remember one such album/artist, browse to it, then click on the genre tag. Somewhat cumbersome.

Guess this issue can be reopened then, until the new UI is available :smile:
