### ISSUE TITLE
Allow custom CSS

### ISSUE THREAD

**Issue by renere** [navidrome/navidrome#1311]
I'm not sure if this is possible or not, but the ability to load custom CSS to make small changes to the visuals of the site without having to set up a dev build and create a whole new theme / edit any of the files would be very convenient.

**Comment by Dnouv** [comment]
Hi, @renere; thank you for trying navidrome and opening an enhancement request. If you could elaborate on the changes you want to custom change, it might help to make the required changes.
Please feel free to comment. Thank you!

**Comment by RedKage** [comment]
@Dnouv For me, that'd be to target the header bar `MuiPaper-root MuiAppBar-root MuiAppBar-positionFixed MuiAppBar-colorSecondary mui-fixed MuiPaper-elevation4` so I could change the blue color with a darker one (as I use a dark theme)

Aside from this, being able to change anything in the UI could be cool, like in a album grid view, to be able to change the margin between elements to make it wider, or adding box-shadows... all kinds of stuff!

**Comment by deluan** [comment]
> A CSS override file would be perfect, as long as you're able to use it with the binary build.
> (Like a file you could create in /var/lib/navidrome)

Yes, the idea is that you put it under `${ND_DATAFOLDER}/resources` (DataFolder is where your Navidrome database is)

**Comment by renere** [comment]
Oh lol, sorry about my lack of understanding there. Yes that would be perfect!

**Comment by FrankEBailey** [comment]
Is there a timeline for support of this function yet, please?

**Comment by benoitblancquaert** [comment]
I'm a little late to the party, but still hoping this feature gets added.

**Comment by ak1932** [comment]
+1 this would be really useful

**Comment by Vergil365** [comment]
i also would love to get this feature, as none developer its very difficult to get startet with a own theme.
the things i would like are custom lyrics font size (normal size is way to small), also change the colors of some ui elements would be very nice (the lyrics color this not match the colors of the most themes).
