### ISSUE TITLE
Additional/Custom music format support

### ISSUE THREAD

**Issue by tokyovigilante** [navidrome/navidrome#1312]
Hi, 

Firstly thanks for the great software, have been using Navidrome on my home server for a year or so now and it's been fantastic.

However I have a collection of MOD music in various formats (`.S3M`, `.AMF`), mostly videogame soundtracks and demoscene recordings, which would be great if Navidrome could support. 

Consequently it would be great if custom file formats could be specified (by extension or mime) along with a command line tool to transcode them to opus for streaming, or added as is for players that support them.

For example, for MOD music:

https://en.wikipedia.org/wiki/Module_file
https://lib.openmpt.org/libopenmpt/

```
".MOD,.S3M,.AMF": "openmpt123 -q --stdout --no-float <input> | opusenc --raw --bitrate 256 - output.opus"
```
Alternatively if just MOD music formats were added to Subsonic that would solve my use case, but if others have obscure formats they would like to add that are not supported by ffmpeg then the above could be easily generalised.

I have a custom player with a Subsonic API that can play MOD files so both download and transcode API endpoint support would be preferred.

**Comment by certuna** [comment]
Navidrome does not have codecs onboard, it relies on the formats supported by the browser (or the Subsonic player app). If Chrome/Safari/Edge/Firefox can't play MOD/S3M, neither can Navidrome.

You're probably better off rendering these file to WAV/FLAC/MP3 once, and keep the original MOD/S3M files somewhere else.

**Comment by tokyovigilante** [comment]
Thanks for the response. I understand Navidrome is just doing the indexing, but that is my point, if I have a player that supports additional formats beyond the browser, it would be nice to be able to add that music to Navidrome. 

I can certainly transcode to FLAC etc, but I like to keep my music as close to the source as possible, and for MOD this is obviously the original format. I note that Navidrome at least on my server (git HEAD as of ~2w ago) does actually scan and import ProTracker `.MOD` files, just not other module formats. As you suggest they are not playable in the browser however.

`Aug 31 21:26:18 xserve navidrome[1927]: time="2021-08-31T21:26:18+12:00" level=info msg="Streaming file" artist="[Unknown Artist]" bitRate=0 cached=false format=raw originalBitRate=0 originalFormat=mod title="(C) Terminal Reality" transcoding=false user=ryan`

`

**Comment by deluan** [comment]
Hey @tokyovigilante , thanks for the suggestion. Yes, currently this is not possible, but this use case (supporting additional file formats) will be handled by the upcoming transcoding engine revamp (#351). Please add this use case description to that ticket, so it is all in one place.  Thanks!

**Comment by tokyovigilante** [comment]
Thanks for the comments, closing in favour of #351 as requested.
