### ISSUE TITLE
Option to have API return either true path or tag derived path

### ISSUE THREAD

**Issue by DX21-LLC** [navidrome/navidrome#1319]
### Is your feature request related to a problem? Please describe.

This request is focused for the album list returned for an identified artist, but could be beneficial for the entire physical path.

This is not an issue with the native UI, as switching to table view allows for a good sort.  But in 3rd party apps, alphabetical sorting tends to be the only option, and usually that is either by folder path or id3 tag.   When browsing releases by an artist, where the collection may have upwards of 100 releases for that artist, it can be frustrating to be limited to the ID3 tag sorting.

For instance, my collection is all correct with tag data, and filed on the file system as .\[A-Z]\(Artist Name)\(Release Year) - (Album Title)\(Track) - (Song Title)

if I look at two sample paths:

D/Depeche Mode/1981 - Dreaming Of Me (Single)/
D/Depeche Mode/1989 - 101/

In folder view, they are displayed chronologically,  In tag view, alphabetically.

### Describe the solution you'd like

A server-side settings option that would allow either the true path (as returned by the original Subsonic API) or the tag path (as returned by the Navidrome API)  to maximize compatibility with existing 3rd party apps for presentation of the library.

### Describe alternative solutions that would also satisfy this problem

(none)

### Additional context

Subsonic API response for a getAlbum:

&lt;subsonic-response xmlns=&quot;http://subsonic.org/restapi&quot; status=&quot;ok&quot; version=&quot;1.16.1&quot;&gt;
&lt;album id=&quot;1756&quot; name=&quot;Dreaming Of Me (Single)&quot; artist=&quot;Depeche Mode&quot; artistId=&quot;612&quot; coverArt=&quot;al-1756&quot; songCount=&quot;2&quot; duration=&quot;487&quot; playCount=&quot;0&quot; created=&quot;2010-01-02T15:06:19.703Z&quot; year=&quot;1981&quot; genre=&quot;Synth-Pop&quot;&gt;
&lt;song id=&quot;78389&quot; parent=&quot;78324&quot; isDir=&quot;false&quot; title=&quot;Dreaming Of Me&quot; album=&quot;Dreaming Of Me (Single)&quot; artist=&quot;Depeche Mode&quot; track=&quot;1&quot; year=&quot;1981&quot; genre=&quot;Synth-Pop&quot; coverArt=&quot;78324&quot; size=&quot;9822596&quot; contentType=&quot;audio/mpeg&quot; suffix=&quot;mp3&quot; duration=&quot;243&quot; bitRate=&quot;320&quot; path=&quot;D/Depeche Mode/1981 - Dreaming Of Me (Single)/01 - Dreaming Of Me.mp3&quot; playCount=&quot;0&quot; discNumber=&quot;1&quot; created=&quot;2010-01-02T15:06:19.703Z&quot; albumId=&quot;1756&quot; artistId=&quot;612&quot; type=&quot;music&quot;/&gt;
&lt;song id=&quot;78390&quot; parent=&quot;78324&quot; isDir=&quot;false&quot; title=&quot;Ice Machine&quot; album=&quot;Dreaming Of Me (Single)&quot; artist=&quot;Depeche Mode&quot; track=&quot;2&quot; year=&quot;1981&quot; genre=&quot;Synth-Pop&quot; coverArt=&quot;78324&quot; size=&quot;9841399&quot; contentType=&quot;audio/mpeg&quot; suffix=&quot;mp3&quot; duration=&quot;244&quot; bitRate=&quot;320&quot; path=&quot;D/Depeche Mode/1981 - Dreaming Of Me (Single)/02 - Ice Machine.mp3&quot; playCount=&quot;0&quot; discNumber=&quot;1&quot; created=&quot;2010-01-02T15:06:19.785Z&quot; albumId=&quot;1756&quot; artistId=&quot;612&quot; type=&quot;music&quot;/&gt;
&lt;/album&gt;
&lt;/subsonic-response&gt;

Navidrome API response for the same album:

&lt;subsonic-response xmlns=&quot;http://subsonic.org/restapi&quot; status=&quot;ok&quot; version=&quot;1.16.1&quot; type=&quot;navidrome&quot; serverVersion=&quot;0.45.1 (c55e6590)&quot;&gt;
&lt;album id=&quot;ca78bec6a62f3cb0ff31b2682ba05410&quot; name=&quot;Dreaming Of Me (Single)&quot; artist=&quot;Depeche Mode&quot; artistId=&quot;10ddf0306cdaf9f0f0ca7e539dabeb73&quot; coverArt=&quot;f3c7001f5542aa8644a1b31bab918c00&quot; songCount=&quot;2&quot; duration=&quot;488&quot; created=&quot;2021-08-25T16:31:28.6317958Z&quot; year=&quot;1981&quot; genre=&quot;Synth-Pop&quot;&gt;
&lt;song id=&quot;f3c7001f5542aa8644a1b31bab918c00&quot; parent=&quot;ca78bec6a62f3cb0ff31b2682ba05410&quot; isDir=&quot;false&quot; title=&quot;Dreaming Of Me&quot; album=&quot;Dreaming Of Me (Single)&quot; artist=&quot;Depeche Mode&quot; track=&quot;1&quot; year=&quot;1981&quot; genre=&quot;Synth-Pop&quot; coverArt=&quot;f3c7001f5542aa8644a1b31bab918c00&quot; size=&quot;9822596&quot; contentType=&quot;audio/mpeg&quot; suffix=&quot;mp3&quot; duration=&quot;243&quot; bitRate=&quot;320&quot; path=&quot;Depeche Mode/Dreaming Of Me (Single)/Dreaming Of Me.mp3&quot; discNumber=&quot;1&quot; created=&quot;2021-08-25T16:31:28.6317958Z&quot; albumId=&quot;ca78bec6a62f3cb0ff31b2682ba05410&quot; artistId=&quot;10ddf0306cdaf9f0f0ca7e539dabeb73&quot; type=&quot;music&quot; isVideo=&quot;false&quot;/&gt;
&lt;song id=&quot;e3f6159b71dad741ab10096df80fbcdf&quot; parent=&quot;ca78bec6a62f3cb0ff31b2682ba05410&quot; isDir=&quot;false&quot; title=&quot;Ice Machine&quot; album=&quot;Dreaming Of Me (Single)&quot; artist=&quot;Depeche Mode&quot; track=&quot;2&quot; year=&quot;1981&quot; genre=&quot;Synth-Pop&quot; coverArt=&quot;e3f6159b71dad741ab10096df80fbcdf&quot; size=&quot;9841399&quot; contentType=&quot;audio/mpeg&quot; suffix=&quot;mp3&quot; duration=&quot;244&quot; bitRate=&quot;320&quot; path=&quot;Depeche Mode/Dreaming Of Me (Single)/Ice Machine.mp3&quot; discNumber=&quot;1&quot; created=&quot;2021-08-25T16:31:28.6317958Z&quot; albumId=&quot;ca78bec6a62f3cb0ff31b2682ba05410&quot; artistId=&quot;10ddf0306cdaf9f0f0ca7e539dabeb73&quot; type=&quot;music&quot; isVideo=&quot;false&quot;/&gt;
&lt;/album&gt;
&lt;/subsonic-response&gt;

**Comment by deluan** [comment]
Thanks for using Navidrome!

is this what you are looking for (in the Edit Player screen):
<img width="829" alt="Screen Shot 2021-09-03 at 3 49 02 PM" src="https://user-images.githubusercontent.com/331353/132058829-51bd04fa-e609-4db0-b017-0ef568a5923f.png">

**Comment by DX21-LLC** [comment]
Perfect - & thanks for the quick response.  Keep up the great work!
