### ISSUE TITLE
Recently Added includes Albums with only Tag Updates

### ISSUE THREAD

**Issue by DX21-LLC** [navidrome/navidrome#1321]
### Description

Under Recently Added, both new Albums and Albums where any file therein has the Album Artist tag updated are shows in chronological descending order.

I would fully expect this if I completely changed the Artist name (e.g., "Depeche Mode" to "Recoil"), but case correction changes (e.g., "Depeche mode" to "Depeche Mode") are being considered new entries.

### Expected Behaviour

Case corrections to artist names would not be considered different entities; artists names would be evaluated case insensitive.

### Steps to reproduce

Edit the Artists metadata, changing only the case of any letter.
Allow Navidrome to rescan.
Album appears under Recently Added in the "most recent" position.

### Platform information

 - Navidrome version: 0.45.1 (c55e6590)
 - Browser and version: n/a
 - Operating System: Windows Server 2019

### Additional information

I'm really happy you've taken this project up.

**Comment by deluan** [comment]
Thanks for reporting. This should not happen as artistIDs and albumIDs are derived from lowercased artist/album names. I'll take a look this weekend.

**Comment by DX21-LLC** [comment]
Thanks!

**Comment by DX21-LLC** [comment]
Just to expand out, I recently did an update to correctly mark compilations I'd missed, and that also bumps them to the Recently Added list..
