### ISSUE TITLE
Can't update library after changing the contents of /var/lib/navidrome/navidrome.toml

### ISSUE THREAD

**Issue by Horuyuki** [navidrome/navidrome#1322]
### Description

Updated a new location of where music is stored in the file:
```
/var/lib/navidrome/navidrome.toml
```
Restarted the service, but there were no new files being added. Plex is using that directory just fine.

### Expected Behaviour

Albums should pop up and stuff.

### Steps to reproduce

should be already described.

### Platform information

 - Navidrome version: 0.45.1
 - Browser and version: firefox
 - Operating System: ubuntu 20.04 from source

### Additional information

Any other information that may be relevant or give context to the problem.

 - Screenshots (if applicable)?
 - Logs? 
 - Client used?

**Comment by deluan** [comment]
Hey @Horuyuki, sorry for the long delay. Are you still experiencing this? Can you please share a debug log?

**Comment by Horuyuki** [comment]
> Hey @Horuyuki, sorry for the long delay. Are you still experiencing this? Can you please share a debug log?

I am staring to think it is problem with my cloud drive. I will update here as soon as I have an update.
