### ISSUE TITLE
Albums get merged

### ISSUE THREAD

**Issue by NyTimez** [navidrome/navidrome#1324]
### Expected Behaviour

What you would have expected to happen instead.

### Steps to reproduce

1. Open the '...'
2. Click on '...'
3. Scroll down to '...'

### Platform information

 - Navidrome version: 
 - Browser and version: 
 - Operating System: 

### Additional information

Any other information that may be relevant or give context to the problem.

 - Screenshots (if applicable)?
 - Logs? 
 - Client used?

**Comment by NyTimez** [comment]
I have a Music folder.  In It I have subfolders:  Mike and Dave.  Both folders have an albums with the same name.  In Mikes folder the album has 2 discs.  Dave's album has 4 discs.  When Navidrome scans these folders it combines the first 2 discs.  This is not correct. They are 2 separate distinct albums.

**Comment by deluan** [comment]
Thanks for using Navidrome. ND uses tags exclusively to identify and group songs, it ignores folders. So if the two albums have the same artist/album name, they will be considered one. If you want to import multiple albums with same name for the same artist, you can change the names in the tags, like:

The Doors - Morrison Hotel
The Doors - Morrison Hotel (40th Anniversary Edition)

Currently that's the only way to disambiguate the albums. We plan to add the option to use MBIDs (MusicBrainz IDs) for this disambiguation
