### ISSUE TITLE
rescan updates Album Artist in mediafile table but not album table

### ISSUE THREAD

**Issue by certuna** [navidrome/navidrome#1328]
v0.45.1 on latest macOS 11
mp3 with id3v2.4 tags

I had a couple of compilations with Album Artist = "Various" (so not "Various Artists") and Compilation=True
- edited the tags and set Album Artist to blank
- rescan
- Album Artist is updated correctly in the `mediafile` table and the `song` endpoint returns "Various Artists" as albumArtist
- Album Artist is not updated in the `album` table and the `album` endpoint returns "Various" as albumArtist

Moving the album out of the music folder, rescan to remove album from DB, moving the album back, rescan - will pick it up correctly, but that's clearly not the workaround we want.

Can you reproduce?

**Comment by deluan** [comment]
Are you really using version 0.40.1?

Anyway, in previous versions (0.44.1 and earlier), the full rescan was broken, and would not reimport tags if the files didn't change. This was fixed in 0.45.0. Let me know if it is still occurring in newer versions

**Comment by certuna** [comment]
0.45.1, sorry :)

**Comment by deluan** [comment]
Hey @certuna, I was not able to reproduce this. If I have an album already scanned with album_artist = 'Various', and I change it to blank, after running a quick scan I can see both `song` and `album` endpoints returning album_artist = 'Various Artists'. 

Maybe there's some key info missing from your report? an you change the log level to `trace` and try again? Then send me in private the logs.

**Comment by certuna** [comment]
I have some problems reproducing it as well. It has happened twice now but I can't find out why.
