### ISSUE TITLE
Keyboard shortcut; currently playing track in an album

### ISSUE THREAD

**Issue by bbsixzz** [navidrome/navidrome#1336]
Hello!

I would like to suggest a command that takes you to the currently playing track in an album.

Just like clicking the currently playing track.

Cheers

**Comment by satyaarthchhabra** [comment]
hi @deluan  can you assign this issue to me

**Comment by satyaarthchhabra** [comment]
@deluan  and @bbsixzz   so you want it  to display current album right as when we click on the name of the song i takes to the album .for eg https://vimeo.com/600080682

**Comment by deluan** [comment]
Yes. The idea is that a shortcut would have the same effect as clicking in the song name in the player

**Comment by bbsixzz** [comment]
In iTunes <kbd>⌘</kbd> + <kbd>L</kbd>  invokes **Go to Current Song**

L is already used for love (add to favorites) in Navidrome so I guess you need another key, maybe C?

On a tangent, may I suggest using capital letters in the Navidrome Hotkeys popup for clarity?

<img width="292" alt="Screenshot 2021-09-08 at 16 32 15" src="https://user-images.githubusercontent.com/47334163/132529326-c6d55ee3-5cba-48f0-9b21-ea333749be86.png">

It's unclear if Add this track to favourites is L or capital i.

Here's a version with `<kbd>` for improved clarity.

Show This Help <kbd>SHIFT</kbd> + <kbd>?</kbd>
Toggle Menu Side Bar <kbd>M</kbd>
Play / Pause <kbd>SPACE</kbd>
Previous Song <kbd>←</kbd>
Next Song <kbd>→</kbd>
Volume Up <kbd>=</kbd>
Volume Down <kbd>-</kbd>
Add this track to favourites <kbd>L</kbd>

**Comment by nitin094-hub** [comment]
Is this issue still open?

**Comment by deluan** [comment]
@nitin094-hub Yes it is. I haven't heard from @NayamAmarshe about this.

**Comment by nitin094-hub** [comment]
Could you assign this issue to me?

**Comment by deluan** [comment]
No need to assign, go ahead and let me know if you have any questions (preferable in Discord)

**Comment by pavithranair** [comment]
Hello @deluan ! I would love to work on this. Any suggestions on what the keyboard shortcut should be? For trial purposes, I've used 'c' in order to display the current song.
![image](https://user-images.githubusercontent.com/66196840/149071394-774b20fb-8301-4923-9625-c79fb5c4e263.png)

**Comment by vian9** [comment]
Is this issue has been resolved?
