### ISSUE TITLE
Allow multiple transcodings to be registered with the same target-format

### ISSUE THREAD

**Issue by simojenki** [navidrome/navidrome#1337]
Currently it would appear that only 1 transcoding per target format can be registered.  Trying to create a second one for mp3 for example results in a constraint violation;

time="2021-09-09T05:06:40Z" level=error msg="SQL: `INSERT INTO transcoding (command,default_bit_rate,id,name,target_format) VALUES (?,?,?,?,?)`" args="['ffmpeg -i %s -map 0:0 -b:a %bk -v 0 -f mp3 -',320,'e7de14f1-2dd9-4304-9c7e-79168deb8fa3','mp3v2','mp3']" elapsedTime="111.675µs" error="UNIQUE constraint failed: transcoding.target_format" requestId=fe39cf2a148a/huZzZM0CAT-000184 rowsAffected=0

2021/09/09 05:06:40 Saving transcoding: UNIQUE constraint failed: transcoding.target_format

Which in turn leads to a 500 error in the ND UI.

### Describe the solution you'd like

It would be an improvement to remove the constraint and allow multiple configurations per target format, so that for example I can have a different transcoding command for sonos/bonob to the regular transcoding.  Transcodings are selected per player by name already, so this shouldnt change the user experience much.

### Describe alternative solutions that would also satisfy this problem

I'm not sure of any alternatives.

**Comment by deluan** [comment]
Thanks for reporting. I'll take a look this week on this

**Comment by girlmaya** [comment]
Anything on this?

**Comment by girlmaya** [comment]
I don't recall if this issue is still applicable but I don't want it to be forgotten if it is. Isn't the bot maybe a bit too quick to close issues btw?

**Comment by deluan** [comment]
This is a test comment to see if I can retrieve actual comments on this issue.
