### ISSUE TITLE
Rescan crashes when scanning certain files

### ISSUE THREAD

**Issue by wanieru** [navidrome/navidrome#1343]
### Description

When rescanning the attached .mp3, navidrome crashes.

### Expected Behaviour

The scanning should complete without problems.

### Steps to reproduce

1. Start navidrome using the attached docker-compose.yml
2. Add the songs to the music volume
3. Do a full rescan
4. Navidrome should crash while scanning the files.

### Platform information

 - Navidrome version: 0.45.1-SNAPSHOT (79363d6c) (also happens using the Docker tag :latest, as of 2021/09/13)
 - Operating System (Docker Host): Raspberry Pi 4 running raspbian
 - Browser and version (UI): Firefox 92.0 (64-bit)
 - Operating System (UI): Windows 10 Pro, 10.0.19042 Build 19042

### Additional information

[docker-compose.yml](https://github.com/navidrome/navidrome/files/7157398/docker-compose.yml.txt)
[Song 1](https://cdn.discordapp.com/attachments/886714670793244743/886730178301149184/d9565b10-5105-4022-8370-4907aba26058.mp3)
[Song 2](https://cdn.discordapp.com/attachments/886714670793244743/887079032951279647/6b097668-b541-498d-9bfd-e32187ec43f4.mp3)
[crashlog.txt](https://github.com/navidrome/navidrome/files/7157383/crashlog.txt)

**Comment by deluan** [comment]
Thanks for opening this. I was not able to reproduce on my dev environment (macOS), but will try in a docker container.

Worse case, I'll put in place a panic recover, so it does not crash Navidrome

**Comment by deluan** [comment]
I put in place the panic recover. Now when this happens, the file will not have any tags read, it will appear as `[Unknown Artist]/[Unknown Album]`, and you'll see the message `TagLib: recovered from panic when reading tags` in the logs. If you get this issue, please attach the problematic file to this issue and reopen it so I can try to reproduce it in my environment

**Comment by possessedbysatan** [comment]
Hey @deluan! I finally got some time off and here are the files that previously caused Navidrome to crash. They are already tagged and play fine with vlc, clementine, etc.

https://www.mediafire.com/file/8mc90tnwx4l2g4v/Endstille.zip/file
