### ISSUE TITLE
Cached album art for player isn't updated

### ISSUE THREAD

**Issue by PillTime** [navidrome/navidrome#1347]
### Description

If changing the cover art of an album, the image is updated everywhere except for in the player.

### Expected Behaviour
For the art to be updated in the player as well.

### Steps to reproduce

1. Have cover art in an album.
2. Change it.
3. Refresh Navidrome.

### Platform information

 - Navidrome version: v0.45.1
 - Browser and version: Firefox v93.0b4
 - Operating System: NixOS 21.05 (using docker)

### Additional information

I use [beets](https://beets.io/) to get the metadata for some of the songs I have.
One of the songs got the wrong album art, so I changed it.
It changed everywhere as expected, but it didn't change in the player, when the song is actually playing.

I have beets setup so that the name of the image file it fetches is `albumart.*`, and Navidrome has the option **CoverArtPriority** set to `cover*, albumart*, embedded`. This way, if I need to change the album art, I can add a new image called `cover.*` without having to remove what beets gave me.
I've also tried removing the original `albumart.*` file and restarting the container, but nothing worked.

Screenshot:
![image](https://user-images.githubusercontent.com/2399664/133684305-f12a4828-431c-46fd-9746-a1ded3ea7f99.png)

**Comment by deluan** [comment]
Is that the case that you changed the cover _after_ the song was added to the play queue? What happens if you click on the song again after the cover changes in Navidrome?

**Comment by PillTime** [comment]
> Is that the case that you changed the cover _after_ the song was added to the play queue?

If I remember correctly, yes, I had already added the song to the play queue when I changed the cover.

> What happens if you click on the song again after the cover changes in Navidrome?

Nothing changes.
I tried changing the cover with another image.
The cover art only changes after doing a quick scan and refreshing the webpage with F5.
The image in the player is still the old one. It doesn't change no matter what.

**Comment by deluan** [comment]
> The cover art only changes after doing a quick scan and refreshing the webpage with F5.

This is expected

> The image in the player is still the old one. It doesn't change no matter what.

The play queue (part of the player) keeps the old cover. To make it "forget" it, you'd need to remove the song from the play queue and add it again. Please confirm this is the case. If that's it, it is unfortunately something that cannot be fixed for now, while we depend on the react-jinke-player. We have plans to replace it in the future, but we are not there yet.

**Comment by PillTime** [comment]
Unfortunate timing as I just updated my previous comment.

> To make it "forget" it, you'd need to remove the song from the play queue and add it again.

This doesn't work. The old cover is still being used after removing and adding the song to the play queue.

**Comment by deluan** [comment]
Humm.. I have to check, but IIRC, the `CoverArtPriority` is only for albums, and  I think for a song the embedded art always take precedence over any album artwork.... You can disable song artwork by setting `DevFastAccessCoverArt=true`. 

Anyway, will take a look at this before closing this. Please let me know if `DevFastAccessCoverArt` works for you

**Comment by PillTime** [comment]
Yep, `DevFastAccessCoverArt=true` fixed it.
So I guess the player simply uses the embedded cover if the song has it.

Thank you so much for your help.

**Comment by deluan** [comment]
Closing this as there is a workaround, and not sure if it is worthy to "fix" it, as it allows songs to have individual covers (ex: [8-bit lagerfeuer by pornophonique](https://demo.navidrome.org/app/#/album/ad0f112b6dcf83de5e9cae85d07f0d35/show)
