### ISSUE TITLE
allow using file creation date for "date added"

### ISSUE THREAD

**Issue by certuna** [navidrome/navidrome#1350]
Opening this issue to track progress/discussion, as per discussion with @deluan back in March.

**Issue**
There are currently two timestamps to select how Navidrome sorts the "recently added" screen, and sorts songs by date added in the Song list or playlist.
- _created_at_, the date that the Navidrome scanner first added the mediafile or album to the Navidrome database. This gets reset when the user deletes the database and starts fresh, but also when you change the Album Artist or Album Title tags: https://github.com/navidrome/navidrome/issues/1321
- _updated_at_  the filesystem modification timestamp `mtime`, rolled up to the album level. This gets updated to Now when the user updates any tag.

Neither of these are very intuitive - ideally you'd want to be able to sort songs & albums by:
- "birth time", the `btime` filesystem timestamp when the user downloaded, ripped or created the song onto his hard drive. This won't change with tag edits, and also survives a complete rebuild of the database

This is trivial to implement on Windows, macOS and OpenBSD, but not on Linux:
a) the ext2 and ext3 filesystems don't store a file creation date
b) for filesystems like ext4 and btrfs that do store file creation date, the legacy Linux _system_ call `stat` does not return file creation dates

Since the addition of `statx` to kernel 4.11 in 2019 the door is open for Navidrome to support this.

**Proposed implementation**
- There's a nice Go abstraction to get `btime`: https://github.com/djherbis/times
- Rolling up mediafile timestamps to album timestamp using the lowest (oldest) file, this allows for subsequent addition/replacement of individual songs without changing the album date
- graciously fall back when `btime` is not available

Three ways to implement `btime` support:
1. populate `created_at` with `btime` instead of the DB record creation time _(probably best? IMO most intuitive/logical)_
2. populate `updated_at` with `btime` instead of `mtime` _(but this may interfere with some code that does things based on modification times? Besides, it makes it impossible to see/sort by "recently updated")_
3. add a third column `filesystem_created_at` and allow the user to choose between the three _(unnecessarily complicated?)_

**Comment by metalheim** [comment]
Sounds like a good addition.

Regarding the rollup: file times will be different for every file in an album (as copying/ripping/downloading/extracting takes time) 

Usually these are only a few minutes apart, but it could also happen that songs in 1 album have vastly different creation dates. 
What's a good priority to roll up to album, the earliest date?

**Comment by certuna** [comment]
probably the earliest date (which will catch the occasional "you find out that one track is corrupt, so you re-download it" scenario).

**Comment by certuna** [comment]
It is still relevant, and it's on my To Do list.

**Comment by certuna** [comment]
Once [this PR](https://github.com/djherbis/times/pull/13) has been merged, we can use https://github.com/djherbis/times

**Comment by gildesmarais** [comment]
The linked PR to [times](https://github.com/djherbis/times) has been merged (not released yet). With this, using `btime` should be feasible. :)

What is everybody's favourite implementation approach (see the three suggested ones in the opening post)?

**Comment by metalheim** [comment]
1. Sounds cleanest as long as it doesnt interfere with anything else that uses created_at

**Comment by certuna** [comment]
I prefer 1.

From the tests and code analysis I've done so far, the current created_at isn't used for anything else than sorting by Recently Added, so should be safe to use.

I'll see if I have some time for this the coming weeks.
