### ISSUE TITLE
Individual Favourite Songs are not showing on favourite page, Album marked as Favourite is coming

### ISSUE THREAD

**Issue by srrathi** [navidrome/navidrome#1351]
### Description
I don't know exactly whether its a bug or the the feature I'm looking is not present in.  As I mark a song favourite from any album that song is not listing on Favourites page instead it's showing No Records Found but if I mark an Album as Favourite its showing on favourites page.

### Expected Behaviour
If a user mark a song as Favourite that song too should be listed on Favourite Page, So that user can access its favourite songs from different albums at one place.

### Steps to reproduce

1. Open the any Album.
2. Mark any song as Favourite.
3. Now check on the Favourites Page whether that song is listed or not. Ideally it should be listed there.

### Platform information

 - Navidrome version: v0.45.1
 - Browser and version: Chrome Version 93.0.4577.82
 - Operating System: Ubuntu 20.04 and using built from source  

### Additional information

Any other information that may be relevant or give context to the problem.

1. Video 1 showing a song marked as Favourite but not listing in Favourites Page.
https://user-images.githubusercontent.com/57089237/134033370-1c518ee2-7ef0-4657-94da-c2c1cab4f92e.mp4

2. Video 2 showing an album marked as Favourite and listing in Favourites Page.
https://user-images.githubusercontent.com/57089237/134033437-a23f5037-bed3-4bef-a569-3a481b6f877f.mp4

If it's a BUG I want to discuss more about it and will be more than happy to resolve it.

**Comment by metalheim** [comment]
This is more or less working how it is designed to be.
The "favourite" page is sitting under the "albums" menu, indicating it is only for favorite albums.
It's really just the "All albums" grid with a filter "favourite=true" applied.

That said I totally agree there should be a page for favourite songs!
I already opened #1067 for this reason :)

**Comment by metalheim** [comment]
Also related is #1076 as an attempt to implement this, but as I understood @deluan it wasn't the best approach and should be implemented in a proper way

**Comment by deluan** [comment]
Yes, @metalheim is right: The implementation from 1076 has some problems, and I'm not sure that's the best way to approach the issue.

I'm closing this in favour of #1067, feel free to follow that issue for updates
