### ISSUE TITLE
Display Free Storage Space in Activity

### ISSUE THREAD

**Issue by bbsixzz** [navidrome/navidrome#1361]
I would like to request that the activity popup shows the free storage space.

<img width="264" alt="Screenshot 2021-09-22 at 22 25 24" src="https://user-images.githubusercontent.com/47334163/134416667-25547e5b-6957-4b65-97d3-99ef40d78d5e.png">

This would be useful for many reasons, especially on systems with small SD-cards.

**Comment by deluan** [comment]
That's a good idea. I have plans to add more info to the Activity Panel, but I'm trying to first figure out the issue that it freezes the browser #1186

Will keep this open, but let's wait for that bug to be fixed first.

**Comment by bbsixzz** [comment]
Bumping this if you think you can add it without much effort.

**Comment by deluan** [comment]
I'll take this in consideration for the new UI, but won't change it for the current Activity Panel.
