### ISSUE TITLE
Last.fm Scrobbling Authorization Not Working

### ISSUE THREAD

**Issue by aosterholt** [navidrome/navidrome#1362]
### Description

When attempting to enable scrobbling in the client, I got to last.fm and attempt to authorize by clicking the button in Last.fm and it returns with the following:  

```
An error occurred while authorizing with Last.fm. 

Request ID: navidrome/h5qxazRWuS-005653
```

### Expected Behaviour

Scrobbling gets authorized

### Steps to reproduce

Open the web page, click profile/personal and toggle Scrobble to Last.fm. authorization screen appears and click Yes, Allow Access in last.fm. Returns and error

### Platform information

 - Navidrome version: 0.45.1
 - Browser and version:  Chrome 93.0.4577.82
 - Operating System:  Docker

### Additional information

Any other information that may be relevant or give context to the problem.

This environment is behind a reverse proxy attached to the /music subfolder providing SSL access.

 - Screenshots (if applicable)?
 - Logs? 
 - Client used?

**Comment by deluan** [comment]
Can you please post (or send to deluan @ navidrome.org) all log messages that contain the string `navidrome/h5qxazRWuS-005653` ? Thanks

**Comment by aosterholt** [comment]
I just emailed them

**Comment by aosterholt** [comment]
It seems that my custom API key was not working as expected. I removed this from my configuration and scrobbling works without issue. Thank you @deluan

**Comment by KingDuckZ** [comment]
Thanks I fixed the issue. I had to switch scrobbling off and then back on as you had suggested. Button wasn't there because scrobbling got somehow disabled in the config file, after the last update I suspect.
