### ISSUE TITLE
Set all playlists as public

### ISSUE THREAD

**Issue by Porco-Rosso** [navidrome/navidrome#1365]
Hello, firstly thanks for making this project, it's really great. I was using Koel before but this is a much more elegant solution.

### Is your feature request related to a problem? Please describe.

I would like to share guest accounts with my friends and family, and to make my library useful, playlists are a must. The "public playlists" function seems to work great for this. The problem is that I have a few hundred playlists, and there seems to be no way to set these all public at once. Furthermore newly created playlists will by default not be public.

### Describe the solution you'd like

I think my problem could be solved by having a navidrome.toml setting that defaults all newly imported playlists to "public"

### Describe alternative solutions that would also satisfy this problem

Another solution would be to be able to select all playlists and mark them as "public" at once. This was mentioned in the following issue by another user: https://github.com/navidrome/navidrome/issues/479
This would not be as great for me as I would need to go through and mark them all public every once in awhile through the UI. I suppose some sort of script to edit the db could work, but feels like a hacky solution.

### Additional context

I tend to organize all my music through playlists. Thankfully all the .m3u playlists imported without a problem after I rescanned the library. As I understand automatic playlist imports will reflect any updates/changes to the underlying .m3u files. I haven't had a chance to test this yet, but from reading other issues, I believe this is the case. (one-way sync)

**Comment by deluan** [comment]
> I think my problem could be solved by having a navidrome.toml setting that defaults all newly imported playlists to "public"

That's a great idea. Something like: `DefaultPlaylistPublicVisibility=true|false`? And this would be used whenever a playlists is created, through importing a .m3u or in Navidrome itself. What do you think?

> Another solution would be to be able to select all playlists and mark them as "public" at once. This was mentioned in the following issue by another user: #479

This can also be implemented. I'll take a look.

> As I understand automatic playlist imports will reflect any updates/changes to the underlying .m3u files. I haven't had a chance to test this yet, but from reading other issues, I believe this is the case. (one-way sync)

Yes, that's the current behaviour. It also means that any changes you do to the playlist through Navidrome UI or a Subsonic client will be lost when there are any changes in the synced .m3u file. This behaviour can be disabled in the playlist edit view.

**Comment by Porco-Rosso** [comment]
Yes, exactly the first is what I had in mind. The second solution is just a nice addition to the UI for ease of life.

The default syncing functionality is perfect for my use as is. I Just have a library and would like to serve it through Navidrome. I have noticed that only a full sync pics up m3u changes, but that might be due to something else on my end.

**Comment by deluan** [comment]
>  I have noticed that only a full sync pics up m3u changes, but that might be due to something else on my end.
Navidrome only picks up changes in quick sync if files have their timestamps updated. If the app you use to edit your .m3u files does not update the timestamp, ND won't be able to detect the changes

**Comment by crazygolem** [comment]
I find this feature request still relevant and valuable.

I am using navidrome to share music with my family and friends, and this includes playlists.
I'm managing my collection from my PC, and sync it with a server where navidrome runs.

For music in general, the workflow is seamless, I don't have to think much about navidrome, it does its thing on its own and it just works =)
For playlists however I have to remember to make them manually public in navidrome when I create new ones on my PC, and delete them manually from navidrome if I delete them on my PC.
Admittedly it's not a big effort (except for the first setup), but still it would be neat if navidrome could do it automatically.

**Comment by john8329** [comment]
I also agree this is valuable. Otherwise the point of having multiple users becomes useless if we want to give them all access to all playlists by default. Setting them as public manually is a hassle and it's for specific use cases.

**Comment by Porco-Rosso** [comment]
I'm in exactly the same situation and opinion as @crazygolem and @john8329. I think the request is still valid.
Been using Navidrome with Submariner, and the experience has been great. If only I could more easily share it with my family.

**Comment by krokenn** [comment]
+1

**Comment by john8329** [comment]
Hey, see https://github.com/navidrome/navidrome/issues/2065 for something similar, I have the project open, I could implement this if I get a consensus on how it should work (especially from the owner).
