### ISSUE TITLE
admin users can not modify not owned (public) playlists via subsonic api

### ISSUE THREAD

**Issue by symzn** [navidrome/navidrome#1366]
### Is your feature request related to a problem? Please describe.

Admin users are able to modify other users playlists from the navidrome web client.
But this is not possible from a subsonic client.
As all playlists are imported with the user admin, my family users are not able to manage their playlists from their android phones (DSub app). And moreover if I set them as admin users it will allow us to share playlists management.

### Describe the solution you'd like

Admin users should be able to modify playlists from subsonic client like web client.
In server/subsonic/playlists.go is it possible to remove the following checks?
In update function for example
```go
owner := getUser(ctx)
if owner != pls.Owner {
  return model.ErrNotAuthorized
}
```

### Describe alternative solutions that would also satisfy this problem

If it is not possible may be we can use a configuration option to enable this behavior?

### Additional context

Thanks for this amazing work, it's really impressive!

**Comment by deluan** [comment]
This is working as intended. The [Subsonic API](http://www.subsonic.org/pages/api.jsp#updatePlaylist) states that:
> Only the owner of a playlist is allowed to update it.

I could disable this behaviour, but maybe introducing a config option as you said is the best approach.

> Thanks for this amazing work, it's really impressive!
Thanks, glad you liked it :)

**Comment by symzn** [comment]
> This is working as intended. The Subsonic API states that:

Ok thanks, now I understand the reason of the owner check.

> I could disable this behaviour, but maybe introducing a config option as you said is the best approach.

Great! I am not a go programmer but may-be I could create a PR for this issue (it shouldn't be too difficult I think)? If you are ok of course.

**Comment by deluan** [comment]
> Great! I am not a go programmer but may-be I could create a PR for this issue (it shouldn't be too difficult I think)? If you are ok of course.

Sure, go ahead!

**Comment by symzn** [comment]
Hi @deluan, :+1: 
I've just try to setup the dev environment today and play with go and the config options in navidrome.
You are totally right! Adding this option would add unnecessary complexity (Even the name of the option I try to code is complex) 
Moreover:
- Playlists mgt policies will be aligned between navidrome web client & subsonic clients.
- Subsonic clients (DSub, Substreamer at least) playlists mgt will be also more coherent : public playlists are proposed when admin user choose to add a song to a playlist.

Many thanks for taking into account this request.
