### ISSUE TITLE
Playback quiet when loading a new album

### ISSUE THREAD

**Issue by sparkhom** [navidrome/navidrome#1367]
### Description

Sometimes, the playback is quiet after pausing/unpausing a new album, and the following error is printed in the JS console:

```Uncaught DOMException: Failed to set the 'volume' property on 'HTMLMediaElement': The volume provided (10000) is outside the range [0, 1].```

After adjusting the volume slider, it works again.

### Expected Behaviour

Pausing/unpausing a newly loaded album always plays music.

### Steps to reproduce

1. Open Navidrome.
2. Remove any currently loaded music using the "destroy" button on the player.
3. Reload Navidrome.
4. Click play on an album.
5. Pause the music (error is printed in the console).
6. Play the music again (errors continue printing in the console).

### Platform information

 - Navidrome version: master branch, commit 210dc6b (latest as of this report)
 - Browser and version: Chrome 93.0.4577.82 (Official Build) (64-bit) (cohort: Stable)
 - Operating System: Windows 10 12H1, Navidrome running using "make dev" from Ubuntu 20.04.03 in WSL2

### Additional information

DOM errors screenshot:
![DOM Errors](https://user-images.githubusercontent.com/97196/134778703-312b377c-a9d1-42a3-ba3f-5b6550d75764.png)

**Comment by sparkhom** [comment]
I'm actually not sure whether this is an upstream React Music Player issue, or if this should be solved in Navidrome. I've [taken a crack at the upstream code](https://github.com/sparkhom/react-music-player/commit/9af4b37708a260af3b13dc1b198b02406aec1492), which fixes this in my dev instance. LMK what you think.

**Comment by deluan** [comment]
Yeah, I saw this behaviour before but couldn't reproduce it. Seems that it is an issue with the upstream player, as you pointed out. Open a PR in their repo and see what the author says.
