### ISSUE TITLE
Makefile broken for FreeBSD (again)

### ISSUE THREAD

**Issue by pacija** [navidrome/navidrome#1369]
### Description

`make setup` throws errors and exits

### Expected Behaviour

`make setup` does its thing without errors - downloading go and node dependencies

### Steps to reproduce

Download source v0.45.1.tar.gz, extract, cd to dir, issue `make setup`.

### Platform information

 - Navidrome version: 0.45.1
 - Operating System: FreeBSD 12.2-RELEASE-p4 amd64

### Additional information

```
me@mybox:~/navidrome-0.45.1 % make setup
make: "/usr/home/me/navidrome-0.45.1/Makefile" line 4: Missing dependency operator
make: "/usr/home/me/navidrome-0.45.1/Makefile" line 7: Missing dependency operator
make: "/usr/home/me/navidrome-0.45.1/Makefile" line 8: Could not find .gitinfo
make: "/usr/home/me/navidrome-0.45.1/Makefile" line 9: Need an operator
make: Fatal errors encountered -- cannot continue
```

**Comment by deluan** [comment]
Can you please try with latest from master? https://github.com/navidrome/navidrome/archive/refs/heads/master.zip

The `.gitinfo` is not being used anymore and was removed already

**Comment by pacija** [comment]
Hi,

after re-building node with BUNDLED_SSL=on, setup and buildall finished without problems, albeit with `gmake`, not with `make`. Compiled binary works without problems on FreeBSD 13.0-RELEASE.

I am not [www/navidrome](https://www.freshports.org/multimedia/navidrome) FreeBSD port maintainer, but it is almost certain it will be hard to maintain if it depends on another port with non-standard options, namely node with BUNDLED_SSL.

It appears (not thoroughly tested) that Navidrome works fine with FreeBSD 13.0's base openssl, which is 1.1.1k, without node's BUNDLED_SSL. Perhaps Navidrome's check could be modified so that it doesn't error out in 1.1.1k?

Regards,

**Comment by deluan** [comment]
Glad you were able to make it work.

> but this one fails with different error:
> 
> ```
> me@mybox:~/navidrome-master % gmake setup
> ld-elf.so.1: /lib/libcrypto.so.111: version OPENSSL_1_1_1e required by /usr/local/bin/node not found
> \nERROR: Please check your Node version. Should be at least v16\n
> gmake: *** [Makefile:132: check_node_env] Error 1
> ```

This error has nothing to do with Navidrome. This simply says that, when `make` tried to run `node --version` [[Makefile:132](https://github.com/navidrome/navidrome/blob/9f00aad216793f9e52bdbd4ff04cdafe3a9560f1/Makefile#L132)], `node` failed with the error `ld-elf.so.1: /lib/libcrypto.so.111: version OPENSSL_1_1_1e required by /usr/local/bin/node not found`. From what I see, `node` was not working previously on your machine, so there would be no way to build Navidrome with it.

There's no requirement from Navidrome for any special version or specific build of `node`, actually it works with any `node` >= v16 out-of-the-box, without any change, in all supported environments

**Comment by jan666** [comment]
I ran into the same error trying to build it on FreeBSD. Here are my findings, maybe someone can benefit from it:

I installed the packages: (I think thats all thats needed. But maybe I forgot something)

```
taglib-1.12
go-1.17.5,1
npm-6.14.8_1
node-17.0.1
ffmpeg-4.4.1_3,1
indexinfo-0.3.1 
pkgconf-1.8.0,1
```

- I did **not** build node with `BUNDLED_SSL=on` - the first build I did was with a prebuilt version of node (`pkg install node`) and it worked, too
- I built ffmpeg with just `LAME, LIBXML2, OPUS, OPTIMIZED_CFLAGS, RTCPU, THEORA, VDPAU, VMAF, VORBIS` =on to keep it minimal (maybe only `LAME=on` and `OPUS=on` are required - I did not test removing more options)

To build it on FreeBSD you have to use `gmake` because the BSD-make does not support `ifneq ("$(wildcard .git/HEAD)","")` (line 4 in the Makefile)

```
$ git clone https://github.com/navidrome/navidrome
$ cd navidrome
$ gmake setup        # Install build dependencies
$ gmake buildall     # Build UI and server, generates a single executable
```

Builds without problems in my FreeBSD 13.0 jail.

**Comment by make-nz** [comment]
Thanks jan666

Having seen your post, I went ahead and gave it a go on TrueNas, using 12.3-RELEASE in a Base-Jail
`FreeBSD navidrome 12.2-RELEASE-p9 FreeBSD 12.2-RELEASE-p9 2ee62d665f0(HEAD) TRUENAS  amd64`

I needed those too:
`pkg install gmake go taglib node npm ffmpeg indexinfo pkgconf`

```
gmake setup
gmake buildall
```

> root@navidrome:~/navidrome # gmake buildall
> 
> > navidrome-ui@0.1.0 build /root/navidrome/ui
> > react-scripts build
> 
> Creating an optimized production build...
> **Compiled successfully.**
> 
> File sizes after gzip:
> 
>   419.73 KB  build/static/js/2.1ed9fe8f.chunk.js
>   49.71 KB   build/static/js/main.477f84ae.chunk.js
>   7.36 KB    build/static/css/2.90fae412.chunk.css
>   776 B      build/static/js/runtime-main.75a71a76.js
>   278 B      build/static/css/main.6dea0f05.chunk.css
> 
> The project was built assuming it is hosted at ./.
> You can control this with the homepage field in your package.json.

In /`usr/local/bin` I renamed the navidrome 0.40.0 version from my previous ports install and copied the compiled over

**All good:**
```
Navidrome Music Server
Version:	0.47.0-SNAPSHOT (8c707b4e)
```

Cheers
