### ISSUE TITLE
Support a directive file for Navidrome to use when adding music files to its database.

### ISSUE THREAD

**Issue by HubKing** [navidrome/navidrome#1384]
### Is your feature request related to a problem?

Music files from various sources could have different aspects, like different character set in the tags, or different volume levels. I mean, not all music files have tags encoded in Unicode or in the same character set as the default character set of the operating system on which Navidrome runs. And some music files are louder than others.

### Describe the solution you'd like

How about having user-supplied directive files where the music files are. It could be `[music file name].navi` for a single specific music file, or `directory.navi` for all music files in the same directory.

The directive file could have fields like:

    Text encoding: Shift-JIS
    Volume gain: 3

When Navidrome scans the directory and finds the directive file, it uses Shift-JIS to decode the text in the tags, not the system's default English character set. And it registers that the the volume level of the songs should be boosted by 30%. Navidrome could boost the volume by that level when transcoding (it seems that ffmpeg already has the `volume` parameter, so this should be easy), or it could simply just pass that gain information to the player client, so that the player client can do something to boost the volume (I mean, most players have equalisers) on its own.

**Comment by metalheim** [comment]
Regarding Volume: There is also a very universal solution out there, called ReplayGain.

It's written to the tags and understood not only by navidrome but most music players! 
The tag is already read by navidrome so if your client supports ReplayGain (most do), your problem is pretty much solved.

**Comment by deluan** [comment]
Navidrome uses UTF-8 encoding. Are you having issues with encoding? Can you elaborate?

Regarding "volume normalization", I think ReplayGain is a better approach, as @metalheim suggested, and we have a GH issue opened for that: #233. Individual volume gain adjust may be a thing in a distant future, and I'm not sure if having a sidecar file is the best approach. Ideally we would use the UI to do that

**Comment by HubKing** [comment]
> Can you elaborate?

This is not a problem limited to Navidrome, but a general text problem. MP3's ID3 v1 do not specify encoding. So, by default most software just used the system's default encoding, like Shift-JIS, if the system's language is Japanese. And it has no field indicating what kind of encoding was used, so on the decoding side, the software just uses the system's default encoding, and the two can be different, resulting in broken text.

If you see the Wikipedia entry for ID3v2, it says

> "The internationalization problem was solved by allowing the encoding of strings not only in ISO-8859-1, but also in Unicode. "

implying that it had the "internationalisation problem" that I mentioned above, in the previous version.

Anyway, this problem can be solved by specifying the correct character set when decoding the tag. It probably can be possible to automatically detect some popular characters sets, but that would take a lot of work. The easiest way is probably just let the user decide (if the user knows that the song is Japanese, then it probably is Shift-JIS, or if the song is Korean, then it probaly is EUC-KR.

Here is a demonstration of that effect

![image](https://user-images.githubusercontent.com/10900489/136119711-ef19ffde-3f00-4ad2-a1b6-7ba66c1b2f11.png)

https://dotnetfiddle.net/E6jUoU

**Comment by deluan** [comment]
Hummm, I see. I think the effort for the user to create such configuration for each file/album is so great that it would be basically the same as fixing the tags to a more modern version of ID3 (v1 sucks big time!)

So, I'm not sure if this is worth the added complexity (and the dev effort) required to handle this.

**Comment by HubKing** [comment]
I see
