### ISSUE TITLE
Extension/plugin like search handler.

### ISSUE THREAD

**Issue by HubKing** [navidrome/navidrome#1385]
### Is your feature request related to a problem? Please describe.

Things get complicated when music files are in multiple foreign languages, especially for Eastern Asian languages. For example, the same Japanese can be written in numerous different ways. The followings are all the same meaning and the same reading (sokoni):

* そこに
* ソコに
* 其処に

Also to type Japanese, when one is usually typing in English, one has to switch to the Japanese IME and then switch to the appropriate input mode (by default, it is in the Alphabet mode, so one has to switch to the Kana mode). It will be a lot more convenient if one could just type "soko" and all music files that contain any of the above appear in the result.

Also, I have not tested these yet, but what about French or German? If the music title is "Ça va", does typing "ca" retrieve the music? And German Umlaut can be substituted with an additional "e" if typing Umlaut is impossible. If the music title is "schönen", does typing "schoenen" get that song?

I know that kind of handling is for rare use cases, so I am not asking that such search feature should be implemented. What I am asking is the ability to create an extension/plugin for that.

### Describe the solution you'd like

Support plugin or extension. The plugin/extension should have access to the Navidrome's music database. For certain events like searching, the plugin can register itself as a search provider. When the user searches, the search string is passed to the plugin. The plugin returns something like the song ID's in the database, Navidrome returns those songs along with its own search result to the user.

For example, when there are the following three songs in the database:

Song1. Title: "I hate long songs". Singer: Short Life. Duration: 02:40
Song2. Title: "Filibuster". Singer: Running for Congress. Duration: 15:10
Song3. Title: "Yesterday". Singer: The Battles. Duration: 03:40

If the user types "long song" in the search box, then Navidrome passes that input to the search provider plugin. Navidrome's own search result is Song1, and the plugin returns Song2. Navidrome returns the following search results to the user.

* "I hate long songs" by Short Life
* "Filibuster" by Running for Congress

**Comment by deluan** [comment]
Thanks for the suggestion! The idea is great, but it requires a plugin system to be in place before anything else. I have plans to introduce it, but we are not there yet, so I'll keep this issue open to track this "search plugin" idea.

By the way, for western languages, accents are ignored: `legião` can be found by searching for `legiao`. For German, `schönen` can be found by typing `schonen`, but unfortunately not `schoenen`
