### ISSUE TITLE
Searchable/Filterable star ratings

### ISSUE THREAD

**Issue by RedKage** [navidrome/navidrome#1390]
### Is your feature request related to a problem? Please describe.

As a user, I need to be able to search tracks by their star rating.
I do this so that I can search for tracks I have yet to listen (they have no ratings) or because sometimes I want to listen to only the good stuff (all of those which have 5 stars).

### Describe the solution you'd like

I see multiple ways to solve this.
The ultimate feature would be what Plex has: they call it "smart playlists".
Using the search/filter UI, you filter your music using several criteria.
The result of the search can be "saved" into a playlist which you can give a custom name.

For my use case, say I would select all musics which have 4 stars for instance, and "save" that into a "★★★★☆" named playlist.
As soon as I rate a new music 4 star, they will get "added" to that playlist.

The quotes are important, because I suspect technically Plex saves the search parameters and shows the results as a "playlist".
Nothing is saved or added in there, it's all computed.

### Describe alternative solutions that would also satisfy this problem

An easier solution would be to simply being able to filter musics using the ratings.
In the Songs view, I can sort by rating, but I cannot filter the ratings by star count. 
The 'Filter' option only has 'Genre' and '♥'

The addition of a new 'Rating  in the filter list would solve my issue.
Just like for the 'Genre' filter, you'd have a dropdown list once the Rating filter is selected, containing 0 to 5 stars options. 
Yeah, I want to be able to filter all the musics which do not have any ratings yet as well.

### Additional context

Whichever solution, at the end of the day I want the tracks filtered to be inside a queue, so I can shuffle them.

Which means that when the rating filter is active and I have a list of tracks displayed, I must be able to "select" all of them, even those not shown in the UI. The selection has to match the entire results beyond what the UI shows me.
This very thing may be a separate feature, like being able to select "beyond" the 15 or 50 search results entries (kinda like what the "Shuffle All" does, which acts on the entire result set... almost, it's capped at 200)

**Comment by deluan** [comment]
Thanks for the suggestion! Yeah, Smart playlists are coming, we just don't have a GH issue to track it.

As for adding filters, yeah, this can come before smart playlists, I'll take a look

**Comment by RedKage** [comment]
Related #1067, for the "select entries beyond the search result UI"

**Comment by RedKage** [comment]
Since version 0.47, phase 1 of this #1417 is solving my issue!

Works well with a manual .nsp, for example I named it `★★★★★.nsp` 
``` 
{
  "all": [
    { "any": [
      {"is": {"rating": "5"}}
    ]}
  ],
  "sort": "playcount",
  "order": "desc"
}
``` 

And this is making a playlist named `★★★★★` with only my best rated musics.
Perfect!

NOTE: Do not forget to activate the playlist auto-import in the config file, if not the .nsp file won't be imported!

I'm not closing this issue right now though, has it also contains some UI description when phase 3 of #1417 will be done!
As of right now though, the minimal implementation is sufficient for my use case.
