### ISSUE TITLE
Navidrome won't play AIF and WAV files without transcoding (but MP3 and FLAC yes)

### ISSUE THREAD

**Issue by CypZ** [navidrome/navidrome#1404]
### Description

AIF(F) and WAV files don't start playing (just hangs in the player track at 00:00) when no transcoding option is set in the player. 

FLAC and MP3 aren't affected.

Transcoding on the fly adds some annoying delay (small pi, big files).

Tried with or without reverse proxy.

Also, the embedded album art of those files doesn't seem to work either (90% of my collection is AIF properly tagged).

### Expected Behaviour

Being able to play those files straight out without transcoding.

### Steps to reproduce

1. Disable the transcoding option in the player (or delete the player, transcoding being disabled by default)
2. Try to play any AIF/WAV track
3. Enable transcoding to mp3/128
4. Try to play same track
![2021-10-14 19_11_48-](https://user-images.githubusercontent.com/18141587/137365650-3b06833f-ad62-49ba-9acb-abdc06551b89.png)

### Platform information

 - Navidrome version: v0.46.0
 - Browser and version: Player [Edge/Windows] (tried with chrome too)
 - Operating System: docker armv7l
 - Client : NavidromeUI

**Comment by deluan** [comment]
Thanks for trying Navidrome. You see, ND uses the browser implementation of HTML Audio tag, and I don't think AIFF files are supported in any browser. WAV should be supported, though.

Regarding the cover art, I'm not sure if [the library](https://github.com/dhowden/tag) we use to extract album art works with these extensions.... Can you send me one of each (with artwork) so I can do some testing here?

Thanks!

**Comment by CypZ** [comment]
Alright I just sent you an example per email. However the cover art is not that important, it's anyway not always decoded properly (depending on the player) but at least the files play...

In any case, thanks for the support and for the great piece of software !

**Comment by deluan** [comment]
I just got your AIFF sample, and as expected the coverart cannot be extracted by https://github.com/dhowden/tag. As for playback, do you know any **web** player that can play AIFF without transcoding? AFAIK, this is a limitation of the HTML Audio Tag, and you'll only be able to play AIFF files in any browser if you transcode them.

You didn't send me your WAV sample, but I was able to play some samples here in the browser _without_ transcoding, no problem at all. Are you still having issues with WAV files as well?

**Comment by CypZ** [comment]
In the meantime I went ahead and batch converted (with fre:ac) my whole collection to FLAC in a parallel folder structure which is now the only source scanned by Navidrome. Not ideal but works around both my issues.

Bonus : In there I also ran a PowerShell script (which creates a playlist file foreach folder containing music) to compensate for the lack of folder view (#739)

Cheers
