### ISSUE TITLE
Big Feature Request: Support for audio books (e.g. m4b)

### ISSUE THREAD

**Issue by sandreas** [navidrome/navidrome#1419]
### Describe the solution you'd like

This might be a (too) big feature request... I would love to see support for audio books, since this kind of feature is pretty rare on mature streaming server solutions. The one I'm currently using is https://github.com/advplyr/audiobookshelf, but it would be awesome to have an all in one solution and I really prefer navidrome.

Best case scenario:
- Support switching the media-type (music, audiobooks, etc.) via dropdown, tab or similar on the main page
- Support for `m4b` files (including tags)
- Save the listening progress of audio books per user
- Supporting playlists
- Offline sync option in the app to save bandwidth / listen, if no internet connection is available
- Adjust player interface to support: 15s rewind/fast-forward, prev/next chapter, bookmarks, playback-speed, etc. (see https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/e3/af/3a/e3af3a91-99ff-87a2-5e3a-1086b7a22617/pr_source.jpg/750x750bb.jpeg)

Maybe this request should be divided into multiple ones, but I just would like to ask, if this is beyond the scope of navidrome?

Best,
sandreas

**Comment by deluan** [comment]
Yes most of it is supported already if you use a client with audiobook support (ex: DSub). The only thing I didn't understand is:
> Supporting playlists

Navidrome already support playlists. What do you have in mind?

Re: filtering on audiobooks, this will also be possible when we introduce multiple libraries, so you could have a library only for audiobooks, apart from your music library.

**Comment by sandreas** [comment]
Ok, I made some experiments. First let me say that navidrome is awesome (really, the docker image worked nearly out of the box behind an nginx-proxy). Since I know audio book stuff pretty well (see https://github.com/sandreas/m4b-tool), here are my thoughts, where I see room for improvement:

- Currently, there is no way to globally "filter" the mediatype (music, audio book, podcast, video, etc.) in the web interface
  - In my case I have music and audiobooks
  - I don't think its useful to have them all in the same view - playing a song followed by and audiobook or vice versa makes no sense to me
  - Having a dropdown in the main menu to set a global filter the media type would be awesome
- Manually setting the mediatype would also be nice to have support for `mp3` based audiobooks
- Chapters support would be nice for players (`m4b` native chapters and `mp3` files with chapters - see https://id3.org/id3v2-chapters-1.0)

So this feature request comes all down to supporting the "media type" with `mp4` format files (e.g. `m4b`):
- `ITUNESMEDIATYPE` or `stik`
- Possible values
  ```
  0 = Movie (old)
  1 = Normal (Music)
  2= Audiobook
  6= Music Video
  9 = Movie
  10 = TV Show
  11 = Booklet
  14 = Ringtone
  23 = iTunes U
  ```
as well as setting the media type manually for other file types and beeing able to globally filter these and lastly to support embedded chapters.

I used the app substreamer with my iPhone and while playback of audio books worked well, the same media type filtering problem applies to the app as well. Chapters did not work either.

What do you think?

**Comment by sandreas** [comment]
> I think the idea is that selecting/filtering by media type in the Web UI would come as part of the bigger Release Type feature

Looks good to me. One problem I can think of is, that Release Type is a bit unclear / unspecific. Although there is a release type "audio book", I'm not sure if ONE data field "release type" is enough to represent two pieces of information:

- The form, how it is released (LP, CD, MP3 Download, etc.)
- The descriptive information, what content is contained (music, podcast, audiobook, video, etc.)

However, you should definitely consider to set a global filter for "release type" property then to prevent mixing up different types of media in the user interface.

> especially in combination with Smart Playlists you'd then be able to make a sub-section of your library with just Audiobooks.

Yes, smart playlists would be awesome. In my opinion smart playlists would be nothing more than "stored filters" and could be used ANYWHERE (including search inputs and music suggestions), which would make them very powerful. One implementation I was very impressed by is the JsonApi.NET one: https://www.jsonapi.net/usage/reading/filtering.html 
Maybe you can get some further inspiration here, I especially liked the URL representations of complex filters without having to use JSON.

> chapter support in the Web UI player would be cool but is difficult to add since the web player component isn't developed by Navidrome

I understand. You're right, chapter support should go to the upstream project. Although as far as I can tell, chapter support would not be that complex, if you just provide a list of timestamps+titles and "seek" to the according chapter markers timestamp. It is also possible to `renderCustomUI` or at least use `addExtendsContent`: 
https://github.com/lijinke666/react-music-player/blob/8ec6ff6bcaf374c6790d20002a4ff863e7158849/example/example.js#L762
https://github.com/lijinke666/react-music-player/blob/8ec6ff6bcaf374c6790d20002a4ff863e7158849/example/example.js#L479
just to display a list of these markers

> chapters are not part of the Subsonic API specs but 3rd party players could in principle add support for that themselves already, by parsing tags clientside. For example, DSub supports ReplayGain tags in a similar way.

I see. Well, maybe there would be a way to workaround this using virtual [bookmarks](http://www.subsonic.org/pages/api.jsp#getBookmarks)? Bookmarks are normaly user specific, but specified with a "comment", whereas the comment could contain the chapter title prefixed with a special marker to signal the player, that this is not a user defined or editable bookmark, but an auto generated one that represents a chapter...  Well, maybe this is not ideal, since:

> If a bookmark already exists for this file it will be overwritten. 

which would mean, that chapter markers prevent users to generate a bookmark matching a chapter timestamp... I don't know, just an idea :-)


I hope you get me right... I'm not trying to tell you how to do your job, I just did some research what it would take to implement this myself, because I really like the project. Unfortunately I doubt that I find the time to contribute code... :-/

Keep up the good work and thank you for the polite and meaningful clarifications. Maybe you could also get some inspiration out of my comments, at least I would hope so.

Keep up the good work.

**Comment by sandreas** [comment]
@deluan 
I'm really sorry, but I have to tell you that already for a while now I'm no longer in the position to open PRs this big (personal reasons). My time is VERY limited at the moment and unfortunately it is not enough to further develop this feature.

So if this can't be delegated or you don't would like to develop it yourself, this issue can be closed (although I would love to see it in the future).

**Comment by smolenskij** [comment]
@sandreas If you have any work up until this point, is it in a branch at all?  This is a feature I'm also very interested in, and may be able to take a look at things in the next few months

**Comment by sandreas** [comment]
For audio books I'm now using [audiobookshelf](https://www.audiobookshelf.org/) + Audiobookshelf App, while for music I still use Navidrome and Substreamer App. Thanks for making this.
