### ISSUE TITLE
Multi-word genres shown as multiple genres

### ISSUE THREAD

**Issue by pacija** [navidrome/navidrome#1420]
### Description

Since implementation of #1251, genres which contain multiple words delimited by space are shown as multiple genres.

### Expected Behaviour

Multi-word genres whose words are delimited by space should be displayed as single genre, unless perhaps admin chooses to set space as delimiter.

### Steps to reproduce

- Make sure `Scanner.GenreSeparator` is not defined in `config.toml` so that default delimiters `;/,` apply.
- Navigate to the album which has multi-word genre, such as "Drum & Bass", "Gothic Rock", "Heavy Metal", "Neue Deutsche Welle", "New Wave" etc., and see how tags are displayed.
- Alternatively, add "Genre" filter and observe that all the results offered are single words.

### Platform information

 - Navidrome version: v0.46.0
 - Browser and version: Chrome 95.0.4638.54
 - Operating System: FreeBSD:x86:64 13.0-RELEASE-p4

### Additional information

Here are some screenshots:
<img width="420" alt="drum_n_bass" src="https://user-images.githubusercontent.com/14246467/138300268-ed83a07d-3fe6-499f-a006-80cfdbc5ad08.PNG">
<img width="416" alt="gothic_rock" src="https://user-images.githubusercontent.com/14246467/138301331-98d23695-9fe6-494a-9d21-0d7875eb1e1a.PNG">
<img width="455" alt="heavy_metal" src="https://user-images.githubusercontent.com/14246467/138301358-4367a0f0-0dab-4c7f-ac0e-dbfaebebdfa6.PNG">
<img width="410" alt="neue_deutsche_welle" src="https://user-images.githubusercontent.com/14246467/138301368-94458732-ccf8-4da3-b597-9a398d2129c5.PNG">
<img width="629" alt="new_wave" src="https://user-images.githubusercontent.com/14246467/138301389-802d80bc-e605-4544-bd3b-cffe1d047b37.PNG">

**Comment by deluan** [comment]
> Or the wildcard pattern which guards the shell git calls in the Makefile could be expanded to look for more than just .git but rather perhaps .git/objects

I think this could be better

> I can look further into this if it would be helpful.

That would be awesome, thanks! 

Will close this as the original issue is resolved
