### ISSUE TITLE
Mobile player uses 1/4 of available volume level

### ISSUE THREAD

**Issue by mradermaxlol** [navidrome/navidrome#1429]
### Description

Mobile web player uses the default 25% volume setting, which results in audio playback being far more quiet than it should be. User can't change the 25% value without opening the desktop version.

### Expected Behaviour

Mobile web player uses 100% volume setting, as the actual volume is controlled by the OS (media stream). A good alternative is having a volume slider in the mobile version (it's a good question though whether it should control the system media stream or the internal player stream).

### Steps to reproduce

1. Open the mobile web player
2. Set system media volume to max, play any track
3. Reload the page as a desktop version, set the volume slider to 100%
4. Play the same track/return to mobile version and play the same track, notice the difference in volume levels before/after

### Platform information

 - Navidrome version: v0.46.0
 - Browser and version: Fennec F-Droid (aka Firefox) 93.1.0; reproducible on other devices with playstore browsers
 - Operating System: Android 11 (Omni); reproducible on other devices with stock e.g. MIUI (various versions)

**Comment by mradermaxlol** [comment]
@deluan any possibility of having this fixed in e.g. 0.47.1?

**Comment by deluan** [comment]
@mradermaxlol Sorry, I completely forgot about this. I just fixed it, you can try the latest development build. Regarding 0.47.1, I usually only release bug fixes like this if it is a very critical bug, as it creates extra burden on the package maintainers

**Comment by mradermaxlol** [comment]
It's alright :) IMO this one is somewhere near the critical level as it cuts listenable volume in half, but worse things happen in life, ha.
Maybe it would make sense to accumulate some fixes and get the .1 version going.

I don't really want to try the development build on my machine, but I guess I could edit the PKGBUILD and cherry-pick the commit.
Thanks a lot!
