### ISSUE TITLE
Playback stutters while switching windows/programs

### ISSUE THREAD

**Issue by Pingumania** [navidrome/navidrome#1431]
### Description

Playback in browser starts to stutter when I minimize and maximize some windows/programs. I tested this with Firefox and Edge.
I made a video because its hard to describe otherwise: 
https://xbackbone.nethog.xyz/SAJO6/gAyOyuPu96.mp4

### Expected Behaviour

Playback without stuttering.

### Steps to reproduce

1. Start playback
2. Click on the playback slider
3. Switch windows or minimize and maximize a window

### Platform information

 - Navidrome version: Docker 0.46.0-SNAPSHOT (47549ecf)
 - Browser and version: Firefox v93.0 & Edge 95.0.1020.30
 - Operating System: Windows 10 21H1

**Comment by maxdelia** [comment]
Hi, I find this issue really, really annoying.
I can see that react-music-player is not maintained anymore, but I'm a full stack developer, so maybe I can help with that? Would You be opened to merge a PR implementing a different player? I don't like the idea to fork and fix react-music-player, but I would also like to know your point of view!

**Comment by deluan** [comment]
Hey @maxdelia , thanks for volunteering. We already [forked the player](https://github.com/navidrome/react-music-player) to fix a long standing bug, but that's not something I want to keep doing (PR's for the fork).

I also don't feel like the effort to just replace the player is worthy, as I couldn't find any open source that meets the requirements for Navidrome. My plan is to actually write a new player, as described here: https://github.com/navidrome/navidrome/issues/1651#issuecomment-1384551296

Let me know if this is something you'd like to contribute to.

**Comment by maxdelia** [comment]
> Hey @maxdelia , thanks for volunteering. We have already [forked the player](https://github.com/navidrome/react-music-player) to fix a long standing bug, but that's not something I want to keep doing (PRs for the fork).
> 
> I also don't feel like the effort to just replace the player with another OS player is worthy, as I couldn't find any open source player out there that meets the requirements for Navidrome. My plan is to actually write a new player, as described here: [#1651 (comment)](https://github.com/navidrome/navidrome/issues/1651#issuecomment-1384551296)
> 
> Let me know if this is something you'd like to contribute to.

Hi @deluan ! I have no prior experience working with HTML 5 audio, but this won't stop my willing to help!
I will join the discussion on Discord during the weekend and figure out how to contribute, thanks!
