### ISSUE TITLE
Disabling genre separators not possible

### ISSUE THREAD

**Issue by haeringer** [navidrome/navidrome#1444]
### Description

The default for `ND_SCANNER_GENRESEPARATOR` is `;/,`, but when changed to e.g. only `;` or `''`(empty), values like `Alternative/Indie` or `Alternative, Indie` are still shown as separate Genres `Alternative` and `Indie`

### Expected Behaviour

Genres should only be separated by the actual value of `ND_SCANNER_GENRESEPARATOR`.

### Steps to reproduce

1. Configure environment variable `ND_SCANNER_GENRESEPARATOR=;` (only separate by semicolon)
2. Have music data with a slash in its genre, e.g. `Alternative/Indie`
3. Perform full scan
4. See in Navidrome that the music has multiple genres `Alternative` and `Indie`

### Platform information

 - Navidrome version: v0.46.0
 - Browser and version: Chrome, Android DSub
 - Operating System: Ubuntu 20.04, Docker

**Comment by deluan** [comment]
Thanks for reporting! You found a bug.... in the docs! The option should be `ND_SCANNER_GENRESEPARATORS` (plural), and if you change log level to "debug" you can see if it was picked up in the logs when ND starts:
```
 _   _             _     _
| \ | |           (_)   | |
|  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___
| . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
| |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
\_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
                                        Version: dev

Loaded configuration from '/Users/deluan/Development/navidrome/navidrome.toml': &conf.configOptions{
...
    ReverseProxyWhitelist:      "",
    Scanner:                    conf.scannerOptions{Extractor:"taglib", GenreSeparators:";"},
    Agents:                     "lastfm,spotify",
...
}
```

I'm fixing the docs right now, thanks!

By the way, you cannot make it empty (`''`) as an environment var, as it means it is not defined and the default will be used.

**Comment by haeringer** [comment]
Cool, I can confirm that it works with `ND_SCANNER_GENRESEPARATORS`. Thank you for the quick reply and for the hint with the empty env var.
