### ISSUE TITLE
Error retrieving cover art

### ISSUE THREAD

**Issue by sker65** [navidrome/navidrome#1445]
### Description

I'm running a self hosted navidrome 0.46 in a docker container. For some albums it fails to load cover arts. logfile is not really helpful. Looking at the client (browser) I see that in the request the id parameter is wrong "&id=not_found"
Full url is: https://server/rest/getCoverArt?u=admin&t=4725ee5c4d82ace2602097af33a44cb1&s=5a5882&f=json&v=1.8.0&c=NavidromeUI&id=not_found

on the server this simply results in

### Expected Behaviour

After scanning music directory I expect cover art read from tag or external source. It's not clear what causes this behavior, because most of the time it works as expected. Only for a few audiobook folders it fails.

### Steps to reproduce

1. Open the '...'
2. Click on '...'
3. Scroll down to '...'

### Platform information

 - Navidrome version: 0.46
 - Browser and version: chrome 95
 - Operating System: ubuntu 20.04 / docker

### Additional information

Any other information that may be relevant or give context to the problem.

 time="2021-11-04T09:23:47Z" level=debug msg="API: New request /rest/getCoverArt" client=NavidromeUI requestId=362246790b18/Ifo1lLYVfx-000045 username=admin version=1.8.0
time="2021-11-04T09:23:47Z" level=trace msg="SQL: `SELECT * FROM user WHERE user_name LIKE ?`" args="['admin']" elapsedTime="433.042µs" requestId=362246790b18/Ifo1lLYVfx-000045 rowsAffected=1
time="2021-11-04T09:23:47Z" level=trace msg="Looking for media file art" id=not_found requestId=362246790b18/Ifo1lLYVfx-000045
time="2021-11-04T09:23:47Z" level=trace msg="SQL: `SELECT starred, starred_at, play_count, play_date, rating, media_file.*, position as bookmark_position FROM media_file LEFT JOIN annotation on (annotation.item_id = media_file.id AND annotation.item_type = 'media_file' AND annotation.user_id = 'a9a99fac-acb1-4884-844e-5746d9a8011e') LEFT JOIN bookmark on (bookmark.item_id = media_file.id AND bookmark.item_type = 'media_file' AND bookmark.user_id = 'a9a99fac-acb1-4884-844e-5746d9a8011e') LEFT JOIN media_file_genres ag on media_file.id = ag.media_file_id LEFT JOIN genre on ag.genre_id = genre.id WHERE media_file.id = ? GROUP BY media_file.id`" args="['not_found']" elapsedTime="267.207µs" requestId=362246790b18/Ifo1lLYVfx-000045 rowsAffected=0
time="2021-11-04T09:23:47Z" level=trace msg="Looking for album art" id=al-not_found requestId=362246790b18/Ifo1lLYVfx-000045
time="2021-11-04T09:23:47Z" level=trace msg="SQL: `SELECT starred, starred_at, play_count, play_date, rating, album.* FROM album LEFT JOIN annotation on (annotation.item_id = album.id AND annotation.item_type = 'album' AND annotation.user_id = 'a9a99fac-acb1-4884-844e-5746d9a8011e') LEFT JOIN album_genres ag on album.id = ag.album_id LEFT JOIN genre on ag.genre_id = genre.id WHERE album.id = ? GROUP BY album.id`" args="['not_found']" elapsedTime="154.795µs" requestId=362246790b18/Ifo1lLYVfx-000045 rowsAffected=0
time="2021-11-04T09:23:47Z" level=trace msg="Cache HIT" cache=Image key=".0.0001-01-01T00:00:00Z.75" requestId=362246790b18/Ifo1lLYVfx-000045 size=304565
time="2021-11-04T09:23:47Z" level=debug msg="HTTP: GET http://server/rest/getCoverArt?u=admin&t=[REDACTED]&s=[REDACTED]&f=json&v=1.8.0&c=NavidromeUI&id=not_found" elapsedTime=3.6ms httpStatus=200 remoteAddr=x.x.x.x requestId=362246790b18/Ifo1lLYVfx-000045 responseSize=304565 userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"

**Comment by sker65** [comment]
So what I read from the trace output, the error is more in the scanner? Looking at the json the server provides for that album (see below), coverArtId and coverArtPath are empty??

----
{
  "playCount": 0,
  "playDate": "0001-01-01T00:00:00Z",
  "rating": 0,
  "starred": false,
  "starredAt": "0001-01-01T00:00:00Z",
  "id": "02992b63200c97f0ec9d32470829d01e",
  "name": "Der Patient",
  "coverArtPath": "",
  "coverArtId": "",
  "artistId": "84343cbbaead590d6b4919a26fef4a9d",
  "artist": "John Katzenbach",
  "albumArtistId": "84343cbbaead590d6b4919a26fef4a9d",
  "albumArtist": "John Katzenbach",
  "allArtistIds": "84343cbbaead590d6b4919a26fef4a9d",
  "maxYear": 0,
  "minYear": 0,
  "compilation": false,
  "comment": "gelesen von Simon Jäger",
  "songCount": 153,
  "duration": 61804.68,
  "size": 989058811,
  "genre": "Speech",
  "genres": [
    { "id": "bfa6cdb2-991e-4bfc-80b3-4e91fafc9f49", "name": "Speech" }
  ],
  "fullText": " der john katzenbach patient",
  "orderAlbumName": "Der Patient",
  "orderAlbumArtistName": "John Katzenbach",
  "createdAt": "2021-11-04T09:01:11.487042377Z",
  "updatedAt": "2021-11-03T20:16:53Z"
}

**Comment by deluan** [comment]
Yes, based on your info, the cover was not detected by the scanner.... Can you touch one of the files, trigger a quick scan and post the resulting logs here?

**Comment by sker65** [comment]
I tracked it down even more and also found some workaround.
It is an audio book with 6 discs, each in a separate sub directory, but all files are tagged as same album continuous track numbering, but the cover.jpg was only present in top level directory and in "CD01" (first disc).
This way the scanner detected it in the CD01 dir, but overrides it later when processing the subsequent directories.
Workaround was: put the cover.jpg in each subdirectory!

**Comment by deluan** [comment]
Ah, I see... Not sure if there's a simple way to fix this in the code.... Will keep this open as a reminder to take a look. Thanks for the troubleshooting!

**Comment by RainbowPants** [comment]
is it possible to use wildcards with directories in the config? 
thinking if a workaround would be like looking like this
`../Disc\ 0*/cover.*`

**Comment by SenorSmartyPants** [comment]
Keep this open.

**Comment by deluan** [comment]
Is it still an issue in 0.49.3?

**Comment by SenorSmartyPants** [comment]
Just retested with develop tagged docker image. Just a cover.jpg in CD 01 works fine now.

**Comment by deluan** [comment]
@sker65 this was fixed in 0.49.3. I'll close this, but feel free to chime in or reopen if you still have any related issues.
