### ISSUE TITLE
Remove the artistId property from songs with no valid corresponding artist data

### ISSUE THREAD

**Issue by jeffvli** [navidrome/navidrome#1446]
### Is your feature request related to a problem? Please describe.

There's currently no way to do a pre-check to see if a song has a valid corresponding artist page or not via the `artistId` property when fetching songs from the API. This causes issues when navigating to the artist page via either a client or the web UI. The user will be forced to wait for the response failure and then have to navigate back.

### Describe the solution you'd like

Remove the `artistId` property from all songs returned by the API that do not have data that is valid to be returned by `/getArtist`

### Describe alternative solutions that would also satisfy this problem

N/a

### Additional context

Example of Airsonic (vanilla) omitting the artistId property on a song without valid artist data.
![image](https://user-images.githubusercontent.com/42182408/140323212-65bcb289-3121-4026-8fbb-fdcf2cfebcd5.png)

**Comment by deluan** [comment]
Thanks for the report. This was fixed in 1c82bf517961f432109a13d8b2c45dcaa12aa23a.
