### ISSUE TITLE
Apple Silicon

### ISSUE THREAD

**Issue by kaambiz** [navidrome/navidrome#1447]
Are there any plans to support Apple Silicon natively?

**Comment by deluan** [comment]
Yes, but it is not a priority for now, as the intel version works well. If you really need it, you can follow the instructions on how to build Navidrome from source, and you'd get a natively compiled version: https://www.navidrome.org/docs/installation/build-from-source

**Comment by kaambiz** [comment]
That is great to hear. Also I had built from source and it works perfectly.
