### ISSUE TITLE
Sort and resave playlist

### ISSUE THREAD

**Issue by dessalines** [navidrome/navidrome#1448]
### Is your feature request related to a problem? Please describe.

I accidentally shuffled a playlist, and now I can't "unshuffle" it. I'd like to have it sorted by artist, so I can see all the songs by them, check for dupes, etc. 

### Describe the solution you'd like

Have the ability through the web ui to sort and then save the playlist.

**Comment by deluan** [comment]
Thanks for using Navidrome! What do you mean by "shuffled a playlist"? Did you change the original order of the playlist and want it sort it back as it was originally created? If that's the case, just click on the "Track #" column as in the screenshot:
<img width="781" alt="Screen Shot 2021-11-14 at 5 34 14 PM" src="https://user-images.githubusercontent.com/331353/141701299-8fa75a54-5fa1-43ce-9d36-226795cadd8e.png">

You can also click on the "Artist" column and it sorts by artist. Is it what you are looking for?

**Comment by dessalines** [comment]
When I do that, the web-ui freezes, on both firefox and chromium. Maybe due to the fact that its a multiple page playlist.

![image](https://user-images.githubusercontent.com/930215/141797214-0b6b1cea-71b4-4cc5-8662-6b6a99b72328.png)

**Comment by deluan** [comment]
@dessalines: yeah, you are being affected by the issue with the ActivityPanel (#1186). Try setting `DevActivityPanel=false`

**Comment by dessalines** [comment]
Okay that env_var did fix the freezes. I must have used the `Shuffle` function on my `Dsub` android client, which permanently changes the order. 

Either way it would be nice to have either a:

- Re-save playlist in current order.
- if anyone knows a tool to do so, be able to save and re-import it. 

Feel free to close this if its out of scope.
