### ISSUE TITLE
Internet streams

### ISSUE THREAD

**Issue by lapara1** [navidrome/navidrome#1450]
Allow us to be able to add our internet streams INTERNET RADIO tab on the left hand side menu. Thanks

**Comment by certuna** [comment]
Not currently planned: https://github.com/navidrome/navidrome/issues/316#issuecomment-912782166

**Comment by deluan** [comment]
Yes, sorry. As @certuna said, it is not current planned.

**Comment by gildesmarais** [comment]
Browsing through the issues and just recently https://github.com/navidrome/navidrome/pull/2063 has been merged. Looks like it adds exactly this! <3

**Comment by deluan** [comment]
Thanks for finding this! I was looking for this to link the PR but couldn't find it!
