### ISSUE TITLE
Scrobbles report twice if you pause and then resume in web player

### ISSUE THREAD

**Issue by SenorSmartyPants** [navidrome/navidrome#1451]
### Description

Play a song about half way-ish, pause. Resume playing after a few minutes. Album play count will be higher than it should. I noticed after I had paused a CD twice. Play count was N+2.

### Expected Behaviour

Playcount should not increase based on pausing and resuming.

### Steps to reproduce

See description

### Platform information

 - Navidrome version: 0.46.0
 - Browser and version: Chrome Version 94.0.4606.81 (Official Build) (64-bit)
 - Operating System: docker official image

**Comment by metalheim** [comment]
I think this has recently been fixed in #1432

You can try in one of the development releases or wait for the next release version

**Comment by deluan** [comment]
Hey @SenorSmartyPants, as @metalheim said, this was fixed in #1432. Can you confirm it is fixed so we can close this?

**Comment by SenorSmartyPants** [comment]
Just tested with several pauses in a shorter song. Only one play recorded. Looks good to me.
