### ISSUE TITLE
New Artist Detail View: Sort albums by full date, not just year

### ISSUE THREAD

**Issue by SenorSmartyPants** [navidrome/navidrome#1452]
### Description

Only year is being used to sort, Not year-month-day. For artists with multiple releases in a year this can cause the albums to be in the wrong order. Example: The Beatles. Please Please Me should be first, not With the Beatles. (see screenshot below). Sgt. Pepper and Magical Mystery Tour are out of order as well. All albums are tagged with full dates.

### Expected Behaviour

Albums should sort by YYYYMMDD when sorting by date or "year".

### Platform information

 - Navidrome version: 0.46.0
 - Browser and version: Chrome Version 94.0.4606.81 (Official Build) (64-bit)
 - Operating System: docker official image

### Additional information

![image](https://user-images.githubusercontent.com/991618/140666903-36409cf1-4d04-4cd5-85c8-34d45cc8b2ff.png)

**Comment by metalheim** [comment]
I fully agree that this would be nice.

Navidrome currently only reads the "year" field, which technically is only supposed to be filled with a year, not a datestring (for id3 tags f.e)

So it is working as intended currently. 

Maybe also reading the "releasedate" would help, but technically these can be different things and every tagger has different interpretations what to put in there. 

Some taggers put the first ever release date of that album, some put the release of the physical medium (which can be completely different)

**Comment by SenorSmartyPants** [comment]
I wouldn't want to check releasedate, as you state they could be different.

Beets allows putting in the full date as does Picard it seems. So if the data is there, why not take advantage of it?

For reference here is the ffprobe output of one of the files in question.
```
Input #0, mp3, from 'The Beatles - With The Beatles - 01 - It Won’t Be Long.mp3':
  Metadata:
    title           : It Won’t Be Long
    artist          : The Beatles
    track           : 1/14
    album           : With The Beatles
    disc            : 1/1
    date            : 1963-11-22
    genre           : Rock And Roll, Rock, Pop
    TBPM            : 0
    compilation     : 0
    TDOR            : 1963-11-22
    originalyear    : 1963
```

**Comment by certuna** [comment]
Navidrome currently only extracts the year, even if the actual date field has months/days (or even time) in it. I think this was largely driven by the needs for the Subsonic API, which only supports years.

I've been thinking about better release date implementations, supporting full dates can probably best be done as part of https://github.com/navidrome/navidrome/issues/278

**Comment by deluan** [comment]
Yeah, importing the full date if available makes sense. It is not a simple change, but I'll try to work on this soon. Thanks for the report.

**Comment by rombat** [comment]
What would be great too would be to have distinct albums displayed based on this full date.
For instance, I have an album with "year" tag being `1986-09-25`, and another album (exact same name, different folder) with "year" tag being `2014-07-16`, because it's kind of a reissue.
In navidrome, both of them are considered as one single album with duplicate tracks and 2 possible years, 1986 and 2014. I've tried adding a subtitle to them but it doesn't make any difference

**Comment by SenorSmartyPants** [comment]
> Yeah, importing the full date if available makes sense. It is not a simple change, but I'll try to work on this soon. Thanks for the report.

Any updates on this?

**Comment by koehntopp** [comment]
I would like to add to this bug:

YEAR will usually have the date of the version in question, ORIGINALRELEASEDATE should get you the order of release of themaster version.

I understand the way people tag files makes a massive difference here, and finding a solution that works for everyone might not be possible.

I'd like to advocate for a configuration file option like

album_sort_tag = 'ORIGINALRELEASEDATE'

**Comment by certuna** [comment]
Problem is that it is not clear cut what the ORIGINALRELEASEDATE should hold:
- the id3 standard says that the Original Date of a track is the release date of the original song, in case of a cover version, live version, interpretation of a classical piece, remix, etc. So for, say, _Jeff Buckley - Hallelujah_ it's "1984", when the original Leonard Cohen song was released
- MusicBrainz Picard uses this field as the date-of-first-edition of the album it is on, so in the case of "Hallelujah" the Original Date is either 1994 (if the song is on the album "Grace"), 2007 (if it's on the single "Hallelujah") or 2019 (if the song is on the "Hallelujah: The Songs of Leonard Cohen" tribute album)

**Comment by SenorSmartyPants** [comment]
The comments thread is getting off topic from my original issue. 

> Yeah, importing the full date if available makes sense. It is not a simple change, but I'll try to work on this soon. Thanks for the report.

**Comment by deluan** [comment]
This now can be done, since #2162 was merged. Will take a look.
