### ISSUE TITLE
How can I disable the download function?

### ISSUE THREAD

**Issue by akimolll** [navidrome/navidrome#1453]
I ran it in Synology Docker. It's perfect. But I had doubts.

I want to turn on the function of online listening to songs for more ordinary accounts, but I don't want them to download these songs. How can I turn off the download function for ordinary accounts?

**Comment by mradermaxlol** [comment]
https://www.navidrome.org/docs/usage/configuration-options/#available-options
`EnableDownloads` config option or `ND_ENABLEDOWNLOADS` envvar is probably what you're looking for.

**Comment by akimolll** [comment]
> https://www.navidrome.org/docs/usage/configuration-options/#available-options `EnableDownloads` config option or `ND_ENABLEDOWNLOADS` envvar is probably what you're looking for.

Thank you very much. I succeeded. Its function has become more practical through customization.

**Comment by metalheim** [comment]
> Here I put forward the problems I encountered. I used the docker version. It doesn't seem to be able to set information for users. For example, I changed "language", "theme" and "default view". When I clear the browser data and log in to my account again, everything will change to the default setting.

Yes, that is actually expected, because these "personal" settings are clientside (in the browser).
The only of those things you can currently set permanently (for all users) is the Default Theme with the `ND_DEFAULTTHEME` option
https://www.navidrome.org/docs/usage/configuration-options/#available-options

If you want to set a default language or view, then please open another issues(s), with a precise title :)
This issue here is been solved i would say.

**Comment by akimolll** [comment]
> > Here I put forward the problems I encountered. I used the docker version. It doesn't seem to be able to set information for users. For example, I changed "language", "theme" and "default view". When I clear the browser data and log in to my account again, everything will change to the default setting.
> 
> Yes, that is actually expected, because these "personal" settings are stored clientside (in the browser). The only of those things you can currently set permanently (for all users) is the Default Theme with the `ND_DEFAULTTHEME` option https://www.navidrome.org/docs/usage/configuration-options/#available-options
> 
> If you want to set a default language or view, then please open another issues(s), with a precise title :) This issue here is been solved i would say.

Thank you for reminding me that I have submitted this new question.

**Comment by mradermaxlol** [comment]
@akimolll please close the issue if the original problem has been solved.
