### ISSUE TITLE
External cover.jpg not discovered in CD 01 subdirectory

### ISSUE THREAD

**Issue by SenorSmartyPants** [navidrome/navidrome#1454]
### Description

MP3s with no embedded cover art, but there is a cover.jpg in CD 01 subdirectory. No cover art displayed in ND. This is where beets places cover art file when using CD subdirs.

### Expected Behaviour

Cover art file should be detected if present in the same directory as CD 01 - Track 01. For compatibility with beets fetchart plugin.

### Steps to reproduce

2 CD album with no cover art embedded
place cover.jpg at Album/CD 01/cover.jpg alongside Album/CD 01/01 - song.mp3

### Platform information

 - Navidrome version: 0.46.0
 - Browser and version: Chrome Version 94.0.4606.81 (Official Build) (64-bit)
 - Operating System: docker official image

**Comment by SenorSmartyPants** [comment]
cover.jpg is detected in a single subdir (this was part of a DVD collection, first 2 discs are DVD, only 1 CD in the set)
album/CD 03 - disctitle/cover.jpg

but not when there is more than 1 CD directory.
album/CD 01/cover.jpg
album/CD 02

**Comment by certuna** [comment]
Seems to be a duplicate of this? https://github.com/navidrome/navidrome/issues/1445

**Comment by SenorSmartyPants** [comment]
Yes. Seems like a duplicate.
