### ISSUE TITLE
The information of personal settings does not seem to be saved correctly.

### ISSUE THREAD

**Issue by i-iooi-i** [navidrome/navidrome#1461]
Here I put forward the problems I encountered. I used the docker version. It doesn't seem to be able to set information for users. For example, I changed "language", "theme" and "default view". When I clear the browser data and log in to my account again, everything will change to the default setting.

**Comment by certuna** [comment]
That's the designed behaviour, language/theme/default view are client-side settings, stored in the browser cache.

**Comment by TheWrathKing** [comment]
A server-side settings for users would be more interesting as you have to do it all again each time you change browser or go on another computer or device.
The is a 'user_props" table in the database which is currently hopelessly empty that would do the work to store user settings.

**Comment by deluan** [comment]
Yes, the table `user_props` was created for any user specific info. Currently it only stores tokens for Last.fm and ListenBrainz, but it can be expanded to save more preferences.

I think saving language server-side is a no brainer, but not 100% sure if the selected theme should also be saved. A user may potentially want different themes for using Navidrome in a desktop browser and in a mobile device. Same for the default view
