### ISSUE TITLE
Customize left column ?

### ISSUE THREAD

**Issue by ThomasDebnt** [navidrome/navidrome#1462]
Hello,
I would like to know if there is a way to add filters/categories on the left column.
I would like to be able to add under Artists "year" and "genre".

Thanks!

**Comment by metalheim** [comment]
I guess you mean something like this:

![image](https://user-images.githubusercontent.com/44159957/141453721-f47bc7d7-4733-45ff-b7ff-108b6dc9d03c.png)

Genre and Years are not currently implemented, these would need to be developed.
That said, for Genre there already is some discussion in #850
