### ISSUE TITLE
Multiple `append` can be combined into a single call

### ISSUE THREAD

**Issue by Biki-das** [navidrome/navidrome#1463]
Appending calls in a single call of append allocates memory just once to accommodate all the elements to be appended. Whereas multiple calls to append introduce many overheads, most notably being the possibility of more calls for memory allocation because the total number of elements to be appended over multiple calls of append is unknown beforehand, resulting in inaccurate preallocation.

filelink-https://github.com/Biki-das/navidrome/blob/master/model/criteria/operators.go#L164-L164

```
current code looks like this 👇

if s.Kind() != reflect.Slice || s.Len() != 2 {
162			return "", nil, fmt.Errorf("invalid range for 'in' operator: %s", v)
163		}
164		and = append(and, squirrel.GtOrEq{f: s.Index(0).Interface()})
165		and = append(and, squirrel.LtOrEq{f: s.Index(1).Interface()})
166	}
167	return and.ToSql()
168}```

we can do something like this👇


	if s.Kind() != reflect.Slice || s.Len() != 2 {
162			return "", nil, fmt.Errorf("invalid range for 'in' operator: %s", v)
163		}
164		and = append(and, squirrel.GtOrEq{f: s.Index(0).Interface()}, squirrel.LtOrEq{f: s.Index(1).Interface()})

165	}
166	return and.ToSql()
167}

**Comment by deluan** [comment]
Hey, thanks for taking a look at this. But please don't go crazy fixing any opportunity for such micro-optimizations you can find (hint: there's a lot!), as this is actually not an issue for Navidrome: You see, the main performance bottlenecks in the server are the DB access and the network communication with the clients. Saving a few cycles and bytes here and there won't make any real difference. For example, the same code you are fixing also uses the `reflect` library, a big no-no if you are concerned with performance, but even removing that won't make any difference. 

If you want to really improve performance, you should spend time looking into optimizing the SQL queries, specially the most complex ones.

Anyway, thanks for the contribution!

**Comment by Biki-das** [comment]
Thanks for the feedback, and where should i exactly route to get to see whatever you just said

**Comment by mradermaxlol** [comment]
Optimisations tend to have a snowball effect, so every little bit adds up and makes a difference in the end :)

**Comment by deluan** [comment]
> Optimisations tend to have a snowball effect, so every little bit adds up and makes a difference in the end :)

Sure, but I rather prioritize writing readable code first, and optimizing things as needed. Of course without doing anything stupid like introducing memory leaks and 1+N problems.

> where should i exactly route to get to see whatever you just said

Some examples:
- https://github.com/navidrome/navidrome/issues/1448#issuecomment-968955270
- Search is slow because it is based on SQLite's LIKE clause. It would make more sense to introduce Full Text Search (#255)
- Find ways to make the scanner even faster (bottleneck is IO to disk, so we need to be smart on how/when to read and how/when to update the DB)
