### ISSUE TITLE
Songs shown multiple times

### ISSUE THREAD

**Issue by milesmcclane** [navidrome/navidrome#1467]
Hello,

I cant get my head around an issue that’s occurring. There are often 5 or 6 instances of the same songs. Albums containing 80 songs instead of 15. I just cannot work out the issue. 

I am trying to migrate from DS Audio on my Synology system, and have Navidrome installed on Docker.

The issue doesn’t exist on DS Audio, and there is only one instance of each song on the drive where they’re stored. I have tried deleting Navidrome container and all of its associated folders (to the best of my knowledge), but to no avail. I use Play:sub on my phone with it, and all of the same issues occur here too.

Can anyone please help me?

**Comment by metalheim** [comment]
That's really weird. Do you have access to the logs?
Maybe it shows a hint or an error in there. 

With docker you can access them with 'docker logs navidrome'
(assuming your container is named "Navidrome")

**Comment by deluan** [comment]
Really weird. Can you check in the UI's _Get Info_ option (in the song's context menu) if the songs have the same path on the server?

**Comment by milesmcclane** [comment]
> Really weird. Can you check in the UI's _Get Info_ option (in the song's context menu) if the songs have the same path on the server?

Ha, good call. They’re all different paths, and they belong to the hidden recycle bin on my server. It’s likely due to a big rearrange/musicbrainz/cull I had of my collection some months ago, prior to installing Navidrome. I was copying to various folders to aid in that and to prevent accidental loss. The DS Audio application just pics up on a per folder basis so I didn’t think of it at all.

I don’t seem to see an option for folders within Navidrome - can it not see them and rather just find every music file on the partition regardless? 

No worries anyway… at least the problem is solved so I can try to mitigate it. Thank you so much!!!

**Comment by deluan** [comment]
Great you found out the issue. I thought I fixed the recycle bin issue a long time ago, but looks like I missed it: https://github.com/navidrome/navidrome/issues/1074

Anyway, I'll close this issue now, but feel free to comment on #1074 if you have any other concern.
