### ISSUE TITLE
"Play Next" causes first song in queue to play

### ISSUE THREAD

**Issue by sigmakey** [navidrome/navidrome#1472]
### Description

While having an active queue in the web UI, regardless of whether playing or paused, and assuming the current song is not the first one in the queue, adding any song to the queue using "Play Next" will cause the first song in the queue to start playing immediately. The desired song _does_ correctly get added to the queue after the song which was originally playing/paused, though.

The issue is unique to the web UI, it doesn't happen in any other clients. It also doesn't seem to depend on the web browser used (tested with Firefox and Edge).

Besides my own server, I can also reproduce this on the live demo site.

### Expected Behaviour

"Play Next" should have no effect on playback of the existing queue besides adding the desired song after the current one.

### Steps to reproduce

For example:
1. Open the web UI.
2. Click on an album with more than one song.
3. Click on a song other than the first one to start playback of the album from that song.
4. Add any song to the queue using the "Play Next" context menu item (can be a song from the same album, doesn't matter).
5. Notice that immediately the first song in the queue/album starts playing.

### Platform information

 - Navidrome version: v0.47.0 (occurs in previous versions too, not sure how far back since I only started using Navidrome since v0.45)
 - Browser and version: Firefox v94.0.1, Edge v95.0.1020.53
 - Operating System: Raspberry Pi OS (Debian 10 Buster based with Linux kernel 5.10.63)

**Comment by deluan** [comment]
Thanks for using Navidrome!

This is a [bug](https://github.com/lijinke666/react-music-player/issues/349#issuecomment-840522656) in the upstream react player, and it has to be fixed in that project. I tried to fix it without success. A possible solution is reverting to a previous version of the player, before the bug was introduced. We may lose one or two nice features but I think "Play Next" may be more important. 

In the mean time, it would help if you report the issue in the upstream project.

**Comment by sigmakey** [comment]
Ah, thank you for explaining the situation. I'm not sure what other features would be lost by downgrading, but it may indeed be worth it to get a queue that works as expected, I think. I'll go and leave a comment on that issue you linked.

**Comment by binamov** [comment]
The upstream bug was closed in July @deluan , my hunch is our +1s are invisible, we probably need a new issue to upvote.

**Comment by deluan** [comment]
I created a fork and put a "naive" fix in place: reverted the commit that introduced this bug. Not sure if it will be enough, as I don't really understand the code. Hopefully this will be enough until we have our own player.

If folks here that have this issue can try the latest build from dev and give feedback, it would be very much appreciated. Thanks for the patience.

**Comment by tomerrr** [comment]
> I created a fork and put a "naive" fix in place: reverted the commit that introduced this bug. Not sure if it will be enough, as I don't really understand the code. Hopefully this will be enough until we have our own player.
> 
> If folks here that have this issue can try the latest build from dev and give feedback, it would be very much appreciated. Thanks for the patience.

i'd like to test this build but not sure how to compile the source code on arm64. any chance you could compile this build for arm64?

**Comment by deluan** [comment]
> i'd like to test this build but not sure how to compile the source code on arm64. any chance you could compile this build for arm64?

You can always find the latest dev builds by going to the project's [GitHub page](https://github.com/navidrome/navidrome) and clicking here:

<img width="1189" alt="Screen Shot 2022-12-03 at 11 02 31 AM" src="https://user-images.githubusercontent.com/331353/205450199-6bfa67b7-7bef-4cc0-922e-85072e46bd58.png">

You'll find a `binaries.zip` that contains the compiled binaries for all platforms.

**Comment by tomerrr** [comment]
thanks , got 0.48.0-SNAPSHOT (51b67d18) arm64 working.
the issue still happens, but not on the first i choose "Play Next" -
so i start playing an album , the first time i choose another song to Play Next, it works perfectly and adds the song to the playlist (right after the currently playing song) . if I choose another song to Play Next, it would restart playing from the beginning of the playlist.
 interesting thing i noticed - if  i let it play to the next song in the playlist, the next time i use Play Next, it would  work correctly again

**Comment by deluan** [comment]
> the issue still happens, but not on the first i choose "Play Next" -

Thanks for taking a look at this. You are right. It is better now, but not entirely solved. But seems that now it is an issue in Navidrome code, not in the player. I'll take a closer look this week.
