### ISSUE TITLE
Have a permalink to the latest release

### ISSUE THREAD

**Issue by Hyask** [navidrome/navidrome#1474]
### There is no permalink to the latest release

For those who want to install with the binary, there is no quick way to get a permalink to the latest release, to automate the process of updating Navidrome, or to help linking directly to it.

I currently use the following script as a workaround, but that requires having `jq`, and it makes multiple requests, which isn't very efficient:
```bash
#!/bin/bash

set -e
set +x

BASEDIR="$(dirname "$(realpath "$0")")"
DATE="$(date '+%Y-%m-%d')"

pushd "$BASEDIR"
mkdir -p "$BASEDIR/log"

{

    # Get latest release name
    tag_name="$(wget -O - "https://api.github.com/repos/navidrome/navidrome/releases/latest" | jq -r .tag_name)"
    echo "latest release: $tag_name"
    archive_name="navidrome_${tag_name:1}_Linux_x86_64.tar.gz"

    # Download and check latest release
    wget "https://github.com/navidrome/navidrome/releases/download/$tag_name/$archive_name"
    wget -O - "https://github.com/navidrome/navidrome/releases/latest/download/navidrome_checksums.txt" | grep Linux_x86_64 > navidrome_checksum.txt
    if ! sha256sum -c navidrome_checksum.txt; then
        echo "Bad checksum"
        rm "$archive_name"
        rm navidrome_checksum.txt
        exit 1
    fi

    # Extract archive
    tar xvf "$archive_name"
    rm "$archive_name"
    rm navidrome_checksum.txt

    # Restart service
    systemctl restart navidrome

    # Clean up old logs
    find "$BASEDIR/log" -name "update.*.log" -ctime +7 -delete
} 2>&1 | tee "$BASEDIR/log/update.$DATE.log"

popd
```

Of course, now that I have the script, I don't really care anymore, but it would have been far more straight-forward if either:
* there was a direct permalink to any archive for any architecture
* or the tag name was not in the archive name, in which case Github already meets the requirement with the following link (for the checksums): https://github.com/navidrome/navidrome/releases/latest/download/navidrome_checksums.txt

What do you think is possible to help solve this problem?

Thanks for creating and maintaining Navidrome, great work! :-)

**Comment by deluan** [comment]
Thanks for the script. This could be a good thing, but it would break versioning custom builds (#1327). I'll see what can be done. Maybe something like we use for the develop builds (https://nightly.link/).

Let me know if you can think of something that could work for both use cases.

**Comment by Hyask** [comment]
The intent is not to break existing things indeed. I was not aware of the https://nightly.link service, but if it can provide easily discoverable permalinks, then I think it's fine.

**Comment by Hyask** [comment]
This is still relevant imho, but:
* I've provided a workaround script.
* Many people just use `docker` that provides the `latest` tag, which also works around the problem.

Thus, I'll close the issue, as I won't push for it, but feel free to re-open if need be.
