### ISSUE TITLE
Browse by folders 

### ISSUE THREAD

**Issue by lapara1** [navidrome/navidrome#1476]
Could you please on a future release add Folders on the left navigation column, you have Albums, Artist and playlists. A quick example of what is seen under my servers terminal for music 

**root@Airsonic:/home/luieq/Airsonic/music# ls
Adoracion-   Bassline-  House-  'Mambo 90s - 2000-'   'Reggae Jamaica-'  Salsa-   'Toda la crema-'  Bachata-   Dance-     Ingles-   Merengue-    'Reggaeton - 90s'  'Slow Music-'  'UK Garage'  Baladas-     Dembow-    'Mambo - Actuales-'  'Punk Rock-'          Reggaeton-   Tipico-**

I used this as the example of what I have right now,something like this on Airsonic but on a more organized way:

<img width="1438" alt="Screen Shot 2021-11-20 at 12 21 39 PM" src="https://user-images.githubusercontent.com/93839987/142735605-55e55700-6bf9-4829-9bc4-83aa3162f047.png">

For example as you see on my music folders list right now there are different (Folders/named by Genre) once I open one of those directories I will see folders by artists names then all songs for each artists, one of the reasons I still am using Airsonic which works with the browse by folder and want to move away since its outdated. 

Please think about something like the old simple iTunes which allowed you to do this without any complexity. 

If something like this is created under Navidrome It would make it big, im still on the Navidrome testing phase and I do like what you have created here but for me as maybe for some it might get little complex by artist or albums if you dont know all the albums or artists you or someone else might have uploaded.  

There are many more features I have on mind if you would like to hear them out, but cant help on the programming since my knowledge only goes as far as some bash scripting.

Hope this helps and could be implemented on a future releases. Thanks.

**Comment by adjenks** [comment]
@lapara1 I too want folder navigation. I don't care about song and artist indexing because my music is very well organised already. I'm going to use this instead:
https://github.com/izderadicka/audioserve
