### ISSUE TITLE
Bulk set ratings/likes

### ISSUE THREAD

**Issue by certuna** [navidrome/navidrome#1479]
Context is the following workflow, when migrating from another player/server (iTunes/Music, Plex, Emby, Airsonic, Foobar, MusicBee, etc):
1. in the other player app, create a playlist containing all songs with 3 stars
2. save as `3stars.m3u`
3. import `3stars.m3u` in Navidrome
4. select all songs in playlist, set rating to 3 stars _<--this is not possible yet_

Currently when all songs in a playlist are selected, the only bulk option available is Delete, see below.
Proposal: add buttons in this bar to set Star and Rating

![Screen Shot 2021-11-22 at 15 56 27](https://user-images.githubusercontent.com/62144283/142883374-fca1c404-82cd-4911-8fd6-3bf9a6036207.png)

**Comment by WolfgangDpunkt** [comment]
For reference:
The desktop Subsonic-player [sonixd](https://github.com/jeffvli/sonixd), which is highly compatible with Navidrome, has just integrated this feature.
For me a very usable solution, in this way I could very quickly rate several hundred songs at once. This went very fast and as far as I can see error free.

In this respect, this would be a viable workaround for the moment.
But a native implementation in Navidrome would certainly  have advantages.

**Comment by allesauseinerhand** [comment]
Also see this solution from https://github.com/rombat/musicbee-navidrome-sync, which should the job even easier. I didn't tried it yet, but I definitely will use it.

**Comment by certuna** [comment]
A solution I'm currently working on:

ND parses the filename of the imported playlist for `[rating=x]` and `[like=yes]`, so ratings and likes for tracks are set on import.

For example: `Top Songs [rating=5].m3u` or `My Favourite Songs [like=yes].m3u`.

Nothing fancy, but it avoids complex changes in the Web UI/API and the need for 3rd party applications.
