### ISSUE TITLE
Return the userRating property for albums/artists from the API

### ISSUE THREAD

**Issue by jeffvli** [navidrome/navidrome#1486]
### Is your feature request related to a problem? Please describe.

The `userRating` property is not being returned for albums and artists from the Subsonic API. Setting the rating for an album or artist using the `/setRating` endpoint works successfully, but there is currently no way to retrieve that set value. 

### Describe the solution you'd like

Add the `userRating` property to all Subsonic API endpoints that return artists or albums.

Endpoints:
- `/getAlbum`
- `/getAlbumList2`
- `/getArtist`
- `/getArtists`
- etc.

**Comment by deluan** [comment]
Wow! Good catch, will fix this ASAP

**Comment by deluan** [comment]
As we discussed, it was actually implemented per the specification. I changed the responses to include the `userRating` now, but keep in mind that this is non-standard, so don't expect other Subsonic compatible servers to return this.
