### ISSUE TITLE
Smart playlists merged with last.fm topSongs and similarSongs information, ie. Super Smart Playlists.

### ISSUE THREAD

**Issue by simojenki** [navidrome/navidrome#1487]
### Is your feature request related to a problem? Please describe.

Ability to define a smart playlist that allows discovery of music based on another smart playlist query.

### Describe the solution you'd like

Lets say I have a smart playlist like top 80s songs from the reddit thread;
```json
{
  "all": [
    { "any": [
      {"is": {"loved": true}},
      {"gt": {"rating": "3"}}
    ]},
    {"inTheRange": {"year": [1981, 1990]}}
  ],
  "sort": "year",
  "order": "desc",
  "limit": 25
}
```
This is in effect what my favourite 80s tracks are.

However more interestingly last.fm contains other related information for these artists/tracks that may allow discovery of 80s tracks that I have overlooked.

So some ability to merge the results from the query with the information from last.fm to create playlists like;

- my favourite 80s songs + songs other people rate from the same artists.

### Describe alternative solutions that would also satisfy this problem

Manually creating the playlists?  
Write a script to do this outside of ND and push the info back in as an m3u?

### Additional context

It might be good if the additional sourced songs were also passed through the same filter above so that for example the 80s playlist example above didnt contain songs from the 2000s that just happend to be by an artist that has songs from multiple decades.  Does that mean it is a 2 stage pipeline?

It might also be good to be able to tweak the weighting of tracks made up from the 'my favourite 80s songs' and the tracks returned from looking at the last.fm data.  This would allow the person defining the playlist to decide how much 'new' music they want to listen to vs. how many of their favourites.
ie: 
1:2 -> 1 song from the 'my favourite 80s songs' and 2 songs from the last.fm data

[edit] Maybe https://jsonlogic.com/ could be used here for filtering if cannot be done within the db/sql query?

**Comment by deluan** [comment]
That's a great idea! I'm already thinking of having a way to have a rule in smart playlists that reference another playlist, something like "is in X playlist" or "is not in Y playlist". We could then somehow integrate external playlists (Last.fm Top Songs, any specific Spotify playlists, ....), and use them with these rules.

> my favourite 80s songs + songs other people rate from the same artists.

This would be then possible by doing something like:
```json
{
    "any": [
        { 
          "all": [
                { "any": [
                    {"is": {"loved": true}},
                    {"gt": {"rating": "3"}}
                ]},
                {"inTheRange": {"year": [1981, 1990]}}
            ]          
        },
        { 
            "all": [
                { "is": { "playlist": "last.fm top songs"}}
            ]
        }
    ]
}
  ```

> This would allow the person defining the playlist to decide how much 'new' music they want to listen to vs. how many of their favourites.
>ie: 1:2 -> 1 song from the 'my favourite 80s songs' and 2 songs from the last.fm data

This is trickier.... I'll have to give it more thought...

> [edit] Maybe https://jsonlogic.com/ could be used here for filtering if cannot be done within the db/sql query?

Did't know this library, interesting... But I think I have mostly figured it out. I just need to create an editor with https://github.com/react-querybuilder/react-querybuilder

**Comment by arsaboo** [comment]
This is a great idea. Popularity information is the most important part of discovery. Users can provide their own ratings, but we can also obtain this information from other sources. 

In fact, Spotify already provides the rating track popularity information in its [Track](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-track) or [Tracks](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-several-tracks) API. Including this information in Navidrome would definitely supercharge discovery. 

I, personally, would love to have Spotify popularity information.

**Comment by simojenki** [comment]
I guess I originally thought that it would work as follows;

my favourite 80s songs might be:
```
Prince - Purple Rain
Michael Jackson - Beat It
```

According to last.fm similar tracks to Prince - Purple Rain [are](https://www.last.fm/music/Prince/Purple+Rain/Purple+Rain)
```
Prince - Lets Go Crazy
Cyndi Lauper - Time After Time
Tina Turner - Whats Love Got To Do With It
Michael Jackson - Billie Jean
....
```

According to last.fm similar songs to Michael Jackson - Beat It [are](https://www.last.fm/music/Michael+Jackson/Thriller/Beat+It)
```
Michael Jackson - Billie Jean
A-Ha - Take On Me
....
```
(Note that Billie Jean is common to both)


So the discovery playlist might contain the union of both;
```
Prince - Purple Rain
Michael Jackson - Beat It
Prince - Lets Go Crazy
Cyndi Lauper - Time After Time
Tina Turner - Whats Love Got To Do With It
Michael Jackson - Billie Jean # This one appears in both above, so the duplicate is removed.
A-Ha - Take On Me
```

In terms of how you could weight 'my favourite 80s' songs vs songs that are added as part of discovery, perhaps you could introduce something that allowed 'picking' only some of the results;  That would allow the person to defining the playlist to 'drop' the odd new song in, or to have a playlist made up of mostly new songs.
ie
```
{
  "all": [
    { "any": [
      {"is": {"loved": true}},
      {"gt": {"rating": "3"}}
    ]},
    {"inTheRange": {"year": [1981, 1990]}}
  ],
  "sort": "year",
  "order": "desc",
  "limit": 25,
  "pick": "0.33"
}
```

In the case above roughly 1/3 of tracks from this playlist would be 'picked' (or selected).

Not sure how you pipe the outcome of this query into the last.fm similar songs data.

**Comment by arsaboo** [comment]
I think there are two different aspects being conflated here. 

1. First, is identifying popular tracks. This is where we can use explicit user ratings or obtain popularity information from other sources (LastFM or Spotify being the more reliable ones). 
2. Next, is how do we combine tracks into a playlist. I think giving users some control like defining the parameters would help. We should also include something like the degree of separation feature in Plexamp that configures how far to look from the initial configuration to enable discovery. 

Music discovery is indeed the bigger problem and this would be a great first step to address that issue. I cannot wait for this to be available.

**Comment by simojenki** [comment]
Yes, it can be treated as 2 different aspects.  

For part 1 I think it is important to be able to refine the list of 'popular tracks', in my mind this is the input to the discovery algorithm.  I think that the nsp files already provide this functionality on the ND music collection.

The reason I think this refinement is important is that In my case I like all sorts of different types music, so I may for example feel like listening and discovering more 'New Wave' music.   This could be done using a simple nsp query on 'genre:New Wave'.
However I also happen to listen to Hip-Hop, Metal, Electronic, etc.  when I am in the mood for 'New Wave' I don't really want to listen to those other types of music, as the resultant 'playlist' would be a total mess of music types and quite jarring to listen to.

How it is implemented I don't really have a strong opinion on, more that 'discovery playlists' can be refined to discover particular types of music based on some user input somewhere.

**Comment by dbuttric** [comment]
I use @simojenki's bonob Sonos interface. Here's how I solve this problem:
The Youtube 'My Supermix' playlist contains 100 songs. So I have made a number of playlists with 100 songs, and some with 50 songs. I add the My Supermix to the queue for the speakers I'm listening to, and then I add one of my navidrome playlists, and I shuffle.
It delights me everyday!
I do wish there was an easier way to do that, but for now, a little manual labor doesn't suck while I'm waiting for coffee!
For me, here's the ultimate solution; and this requires some kind of change in Sonos:
I want to make a playlist in Sonos that stores a reference to both of these playlists - The youtube My Supermix, and one of my other navidrome playlists. When I actually add this to the queue, all the songs get expanded at that moment, so the queue is full of songs, and all I have to do is go shuffle them.

I absolutely love the idea of getting queues from my last.fm playlists. I've been looking for a way to play those in the sonos, and so far no luck.
Thanks for all the effort on this great product!
Navidrome is lightweight, easy to use and seems to be growing in the right way.
Just so I've said it, I am going to be making a semi-regular donation to you to keep the development going.

**Comment by arsaboo** [comment]
Would still like to see this
