### ISSUE TITLE
LastFM integration activation is not fully working

### ISSUE THREAD

**Issue by ToadCast** [navidrome/navidrome#1488]
I did have a look a the other issues first but didn't find something related.

### Description

After an upgrade of Navidrome and disabling LastFM integration, I could still see on an artist's page the icon 'Open in Last.fm' next to the one of 'Open in MusicBrainz' even though I added the env var to disable the integration of LastFM.

I opened the page with another Firefox profile to be sure it's not a matter of some cache or add-on, but I still can see the icon.

### Expected Behaviour

I would like that the icon completely disappear since I clearly do not want to use LastFM in any way.

### Steps to reproduce

Do the upgrade from 0.46 to 0.47 (in docker-compose) and add to the configuration this two env vars:
```
      ND_LASTFM_ENABLED: "false"
      ND_LISTENBRAINZ_ENABLED: "false"
```

Then do a `docker-compose up --force-recreate --build` to apply the upgrade of the image and vars.

### Platform information

 - Navidrome version: v0.47.0
 - Browser and version: Firefox v94.0.2
 - Operating System: 5.14.18-1-MANJARO Linux, **with docker**

### Additional information

I got confirmation from the starting logs that it should be disabled (in `loglevel: info`):
```
[...]
time="2021-11-25T16:11:43Z" level=info msg="Last.FM integration is DISABLED"
[...]
```

With the `loglevel: trace` I also have confirmation:
```
Loaded configuration from '': &conf.configOptions{
[...]
    LastFM:                     conf.lastfmOptions{Enabled:false, ApiKey:"[REDACTED]", Secret:"[REDACTED]", Language:"en"},
    Spotify:                    conf.spotifyOptions{},
    ListenBrainz:               conf.listenBrainzOptions{},
[...]
```

Also, further in the log I can see this which I'm not sure to understand:
```
time="2021-11-25T16:33:07Z" level=error msg="Agent not available. Check configuration" name=lastfm
```

**Comment by deluan** [comment]
Sorry for the confusion: The Last.fm "integration" refers to Navidrome making calls to Last.fm to retrieve/publish any kind of information. When it is disabled, Navidrome never tries to contact Last.fm.

The links to Last.fm from the artist/album pages are not related to this Last.fm integration: It is simply a link to the album/artist page, and does not send any information to Last.fm _if_ the user does not click on the link. The URLs for those links are created using a simple pattern. Ex. for artist: https://www.last.fm/music/{ArtistName}

I never considered these links a type of "integration" as I described in the first paragraph above, as clicking on the link is a user's choice.

> time="2021-11-25T16:33:07Z" level=error msg="Agent not available. Check configuration" name=lastfm

This is a harmless, confusing log message that I'm fixing now.

Let me know if this answers your question.

**Comment by ToadCast** [comment]
It answers perfectly my questioning. Thank you for clarifying it 🙂 I guess I can simply close this issue with the comment.

**Comment by blunderberg** [comment]
Disabling any links, buttons, etc. pointing to external services would be a nice option. 9/10 secret squirrels recommend it.
LastFM is just one example, but this should be configurable for all (current and future) external services.
Reasons:
Some people don't care about LastFM content.
Not all links created using the above stated pattern actually exist on LastFM.
The LastFM link/button takes up space if not used.
