### ISSUE TITLE
Intempestive interruption of playback

### ISSUE THREAD

**Issue by azukaar** [navidrome/navidrome#1491]
### Description

Whenever I try to play lossless Flac on the Web UI, the music just stop constantly, sometime after a minute or 2, and stay stuck quite from 4-5 secs to a long time. Sometime I just end up skipping the song.

 - I dont have the issue on Mobile with an app
 - The same server streams 4k video so its not a server/network issue
 - The Flac are usually only up to 40-50 mb anyway

### Platform information

 - Navidrome version: 0.46.0 (8bbb878b)
 - Browser and version: Firefox latest
 - Operating System: Ubuntu Server, Windows client

**Comment by deluan** [comment]
Thanks for reporting this. I never saw this issue because I transcode the files when listening in the Web UI. I tried it without transcoding and I now see the issue. Can you try something? Try using another Web client, like [Subplayer](https://subplayer.netlify.app/) or [Airsonic refix](https://airsonic.netlify.app/), and check if they have the same issue.

I'll try to figure out what is going on, but in the meantime, as a workaround, you can enable transcoding for the WebUI, if that's ok for you. Opus 128 should be good enough, if you have average ears like me :P

**Comment by azukaar** [comment]
OK so
 - I tried with AirSonic and I get the same issue
 - I realise the phone is transcoding hence why I didnt get the issue on the phone
 - I dont get an issue if I stream it from HTTP\

So I'm guessing it should be coming from the backend, seems like the backend doesn't allow resuming the playback after a buffering phase maybe? But I doubt it is the only issue because from a performance perspective I dont seem to need any buffering at all when using HTTP

**Comment by vs49688** [comment]
I'm streaming FLACs from the Web UI from multiple machines without issue. Because you're seeming the same behaviour with AirSonic, I'd be inclined to say this isn't an issue with Navidrome.

Are you running behind a reverse proxy? That could certainly cause buffering issues if it's misconfigured.

**Comment by mradermaxlol** [comment]
Haven't observed such issues before. Server is running Arch + Wireguard + Nginx + Navidrome (AUR) combo. Clients (Linux, Windows, Android) connect (via both Subsonic clients and Web UI) and play files without issue. The instance serves FLAC, sometimes with quality levels as funny as 32/192 IIRC.

My guess here is that a misconfigured reverse proxy/web server is causing problems, as mentioned above.

**Comment by SteveDinn** [comment]
I am running Navidrome 0.47 from the deluan/navidrome docker image on Ubuntu 20.04 (x64) and behind a reverse proxy (Caddy). I can play FLAC files on the web just fine with Chrome on Windows 10.

Navidrome runs purely as HTTP, and the reverse proxy handles HTTPS.

For what it's worth...

**Comment by Vitriia** [comment]
Same issue here with Navidrome 0.47.
No issue with my files because they was handled by another subsonic-like

**Comment by vosscodes** [comment]
I've had some issues with the UI being unresponsive, but no issues at all playing flac files specifically.

**Comment by deluan** [comment]
Hey @azukaar, are you still having this issue? As others said above, this seems to be caused by your reverse proxy configuration.

**Comment by azukaar** [comment]
> Hey @azukaar, are you still having this issue? As others said above, this seems to be caused by your reverse proxy configuration.

Hello! I am back!
 - I stilll experience the issue
 - I have changed my reverse proxy from Caddy to Traefik and still get the issue
 
I took a screenshot of the console after an interupted playback *i cannot garantee this error is related* because I opened the console after without checking. From now on I will play music console opened to try to gather more inteligence about the enemy

**Comment by azukaar** [comment]
> Hey @azukaar, are you still having this issue? As others said above, this seems to be caused by your reverse proxy configuration.

Hello! I am back!
 - I stilll experience the issue
 - I have changed my reverse proxy from Caddy to Traefik and still get the issue
 
I took a screenshot of the console after an interupted playback *i cannot garantee this error is related* because I opened the console after without checking. From now on I will play music console opened to try to gather more inteligence about the enemy

![image](https://user-images.githubusercontent.com/7872597/152059508-bbb9c3c2-9a35-4230-8f44-70f520b41a2e.png)

**Comment by MRIO** [comment]
Hi all,
I just came to describe my own version of the same problem. IOS app streaming (Play:sub) works fine, but MacOS stops and loops to beginning of the track. I have one observations to add, which maybe helps point in the right direction:
- The length of the song estimated by the player at the bottom is different than the actual song duration (see screenshots)

<img width="1784" alt="image" src="https://user-images.githubusercontent.com/8012564/155316826-0ea506a1-02ad-4246-b57d-65047901efaf.png">

<img width="1781" alt="image" src="https://user-images.githubusercontent.com/8012564/155316844-03d8deab-fdb9-4d53-b4f9-fd248312cc23.png">

Seems like it could be some issue with the estimated duration of the song in the web player.

**Comment by azukaar** [comment]
I have disabled the CloudFlare proxy, seems to fix the issue with interrupted playback. 
Will close for now, and will re-open if that was a false positive
