### ISSUE TITLE
Show star ratings directly in the player (or alternatively add some kind of "Now Playing" view)

### ISSUE THREAD

**Issue by WolfgangDpunkt** [navidrome/navidrome#1494]
The handling of ratings makes wonderful progress and together with the smart playlists features, this really makes Navidrome stand out (many thanks for that!). But I now notice that the access to the ratings of the current song is currently kind of cumbersome. This is because you can only see or change the ratings in the library list or the album view, which must first be accessed manually.

- I know that the player is an external component. The best solution to display the star rating directly in the player is therefore probably difficult. 
- One other possibility would be an additional, optionally displayable, menu bar, above the player, with more info about the current song. 
- Or an "Now Playing" view that could be accessible via the menu on the left. 
- Or a "Now Playing" box that can be opened as a small pop-up like the "Queue" box.
- Or, perhaps the quickest way to implement it, would be an option that the album view automatically changes corresponding to the currently played song (instead of having to click on each currently playing song individually in the player to get to its album view).

I am looking forward to seeing how this can be solved well. Many thanks in advance!

**Comment by metalheim** [comment]
Although I don't use star rating, I like the idea of a "now playing" view that could be customized by navidrome (ie not the playqueue pop-up from the player)

I just fear that would require changing out the player?

**Comment by srichter** [comment]
We could show the rating in the player pretty easily (as we do for a track's "loved" status).

I played around with a "Now Playing" view last year, but didn't go any further with it intending to work on a "mini player" instead. The idea was to have something similar to what Google Play Music previously offered. I still desire something nicer to look at while music is actively playing than just whatever page I had open last.

![image](https://user-images.githubusercontent.com/933620/144697467-24ae1672-357e-427f-a3d5-67d71ea88bb4.png)

![image](https://user-images.githubusercontent.com/933620/144697493-6b11f4da-614b-42aa-962c-a7e6f15111bd.png)

**Comment by AndersMoberg** [comment]
Some possiblity of setting rating / loved status in the media player UX element is really important to me.
This is a really ugly quick edit via web tools, but I'd suggest having this displayed alongside other metadata of the track whilst still being clickable. It'd likely lend itself to the mobile view aswell
![image](https://user-images.githubusercontent.com/4711748/144767768-e5fe3904-c4aa-469c-a668-ffd09673efcd.png)

**Comment by WolfgangDpunkt** [comment]
Thanks for the contributions and ideas!

Priority would also have the rating function for me. If necessary, optionally switchable, since some of the users do not use the star rating function.

@AndersMoberg Your sketch is exactly what I had in mind.

Apart from this, would a now-playing view also be wonderful for the other reasons already mentioned.
I think all the elements for it (artist info, links to more info like Last.fm etc.) are already there and would than need to be combined in a new view.

I am very excited about the new opportunities!
