### ISSUE TITLE
music folders feature

### ISSUE THREAD

**Issue by trombonax** [navidrome/navidrome#1502]
Could you please add music folders as a playlist source like a synology audio station.
![audiostation](https://user-images.githubusercontent.com/88163506/144481420-1cb36289-3237-419c-8d7f-5cbad611d765.png)

You have albums, artist and playlists, but does not have folders. 
A lot of people have a collections grouped via simple `cp` or `mv`, and they are not have too much time to cretate playlists, so if this feature to be added, this will be killer feature of your music collection server

**Comment by simpz** [comment]
Is this the same as:
[
Support exact filesystem structure in subsonic api indexes/musicdirectory (as option) #1380](https://github.com/navidrome/navidrome/issues/1380)

[Sort Albums By Folder #1309](https://github.com/navidrome/navidrome/issues/1309)

I think quite a few of us would like this, as we have spent time curating
our music collections into a sensible directory tree.

**Comment by deluan** [comment]
Sorry, but full browse-by-folder might not be supported any time soon. The issues linked by @simpz above have a better chance to be added at some point in the future. Please follow those issues to get updates on this.
