### ISSUE TITLE
Songs with exclamation mark in ID3 (title) aren't recognized

### ISSUE THREAD

**Issue by morbificagent** [navidrome/navidrome#1505]
Hi together,

i was wondering about some missing songs yesterday and it looks like songs with exclamation mark in ID3 (title) aren't recognized.

Have changed these tags and after that they are listed properly.

**Comment by TheWrathKing** [comment]
This is strange because I checked my library (and in the navidrome database) and i can see nearly 200 songs with exclamation mark in their title.

**Comment by morbificagent** [comment]
Im very sorry.... Looks like i had another problem.

I have tested the exclamation mark in all fields now (filename, id3 title, ...) and everything looks fine.

Not sure why these files had problems here but it wasnt the exclamation mark.
