### ISSUE TITLE
Handling of duplicate songs

### ISSUE THREAD

**Issue by morbificagent** [navidrome/navidrome#1506]
Hi together,

i have folders with hundreds of mp3's which are representing different playlists.
and
i have folders with whole albums.

I was hoping that navidrome would notice that and would do some "grouping the versions of the same song". Plex for example is doing this to prevent these duplicates shown up.

![grafik](https://user-images.githubusercontent.com/50199132/144814476-f1031b2a-215b-4c93-a616-0523cb92f080.png)

It would be great if navidrome could handle this too.

Of course i could kill all my playlist-folders and rebuild them with the songs from the album-folders but... im old and grey until i finish this ;-)

**Comment by metalheim** [comment]
It's not the end-all solution for duplicate songs, but in your case, you could put a ".ndignore" file in the playlist folder.
That way, navidrome would ignore those folders on scanning.

**Comment by morbificagent** [comment]
But then i would lose all my playlists ;-)

**Comment by metalheim** [comment]
You're right, I really haven't thought this through

**Comment by CypherpunkSamurai** [comment]
Hi, I have an idea. What if we use media metadata to check if two music files have similar titles and then add a new integer `duplicate_index` to keep a track of the file.

Also a duplicate cleaner that simply replaces duplicate indexes to user chosen file and removes all other duplicates from the scanned database.

**Comment by morbificagent** [comment]
I would love to see that feature implemented, but im only the guy who reported this ;-)

**Comment by CypherpunkSamurai** [comment]
Ah I got ya @morbificagent. I'll wait confirmation ;)

**Comment by certuna** [comment]
Duplicate detection is more difficult than it looks. Are we talking about similar song titles only? Or disambiguate by artist and abum name too? And what about songs with different length?

**Comment by CypherpunkSamurai** [comment]
> Duplicate detection is more difficult than it looks. Are we talking about similar song titles only? Exact same string? Disambiguate by artist and abum name too? And what about songs with different length, are those duplicates?

Fair point, differentiating song titles from similar ones and checking song length is tough. We wont have a perfect implementation, but we can try.

Here's how I plan on implementing it:
* Group similar song titles that match by 95%. Ask user if the two are duplicates.
* Check length of duplicates. Suggest longer version.
* Compare album art using image hashing and image similarity library.

**Comment by blunderberg** [comment]
How many false positive "duplicates" would a feature like this find?
This either needs to be an optional feature that is turned off by default (I like my duplicates) or not implemented at all. I think that Navidrome is the best personal music streaming server on this planet, and it should remain just that; a personal streaming service. There are countless options out there for "media library management software" that can be used for de-duplication. 

Not counting various other cover versions, the potential for false positives is significant.
One - John Farnham
One - Metallica
One - U2
One - Johnny Cash
One - Brothers of Metal
One - Lewis Capaldi
One - Ed Sheeran

**Comment by morbificagent** [comment]
I think if this feature is optional it would be ok for everyone.

For me it would help a lot and I think finding duplicates while using the ID3 tags should work well for the first try...

They have to be OK of course.

**Comment by deluan** [comment]
I think a way to show duplicates like iTunes/Music's `Library->Show Duplicate Items`, that when select just filter all songs with same title/artist could be useful. But it is not what is asked here.

I'm not sure if keeping duplicates of the same files just for the sake of creating "playlists" is a use case we want to support in Navidrome. As creating real playlists (.m3u files) based on the folder with duplicates would be a one-time only thing, a script could be used to match the files from these "playlist" folders with the songs in the albums and generate a proper .m3u file with the matching songs.

**Comment by Szeraax** [comment]
When I have duplicates, its either due to format shifting (FLAC vs mp3) or partial duplication of folders (each dup has same contents/hash).

In both cases, hiding duplicates based on Artist, Album, and Song tag would be great for me.

**Comment by Szeraax** [comment]
> just filter all songs with same title/artist could be useful. But it is not what is asked here.

@deluan Based on the number of thumbs ups to my comment about items with the same Artist/Album/Song tag, I'm inclined to state that my suggestion of hiding (or possibly simpler: skipping them during import and logging the skip) is worth pursuing. Would you like to see my feature request in a new issue instead of un-staling this one?

**Comment by deluan** [comment]
@Szeraax the current solution for this is to create an empty `.ndignore` file in the folder you don't want to import. I'm closing this now, as a solution exists. If you think this does not solve the issue for your use case, please let me know.
