### ISSUE TITLE
Custom Indexes

### ISSUE THREAD

**Issue by CTParkinson** [navidrome/navidrome#1510]
### Is your feature request related to a problem? Please describe.

I'm using a custom front-end, themed a little like a vinyl jukebox, it arranges Artists by the indexes returned from the `getIndexes` endpoint which groups all Artists by '#', 'A', 'B', ... , 'V', 'W', 'X-Z'

X,Y, and Z are grouped and spoils the letter selection I have, which scrolls to that section of Artists.

### Describe the solution you'd like

An ability to specify the set used for the Indexes, so that I can separate X, Y and Z.

No urgency for this, it is a front-end I've built, it's just for myself, I had been using on top of AirSonic before moving to Navidrome some time ago, it's been this way since and isn't _really_ an issue, just a nice to have to clean up my UI.

### Additional context

![image](https://user-images.githubusercontent.com/46909431/145118983-b8235307-860f-42a5-803d-06d8c13b1dc1.png)
results in this, which is designed to be 27 buttons.
![image](https://user-images.githubusercontent.com/46909431/145119170-a2bd1af5-c020-41b2-b547-4b74834943ee.png)

**Comment by srichter** [comment]
You can use the config key `IndexGroups` ([default value](https://github.com/navidrome/navidrome/blob/afe1e4cfcd56e7bc1d5442b53f9e32b9e7322d9e/conf/configuration.go#L224)) to modify it. I'm not sure what side effects this would have (but it doesn't look like it'd cause any outside of modifying that endpoint response)

**Comment by CTParkinson** [comment]
Ah! I Didn't realise that was a part of the configuration options.
Works as expected.

Thank you!
