### ISSUE TITLE
Cannot open index.html on riscv64

### ISSUE THREAD

**Issue by bkeys** [navidrome/navidrome#1512]
I am trying to run only the server on my riscv64 computer, I have the exact version of go specified in the directions.

```ERRO[0026] Could not find `index.html` template          error="open index.html: file does not exist" requestId=nas/kYowdzyXzW-000002```

Can you tell me why this error is occuring?

**Comment by deluan** [comment]
Seems that the frontend was not built. You need to run `make buildjs` before running the server. If you are just trying to create a build to riscv64, please follow these instructions: https://www.navidrome.org/docs/installation/build-from-source/

**Comment by bkeys** [comment]
I am following those instructions, do I really need to buildjs if I want only a server? I don't have your specified version of nodejs available and building on riscv64 would be a large undertaking.

**Comment by deluan** [comment]
Hey @bkeys, were you able to build the riscv64 version? Can I close this?

**Comment by hboetes** [comment]
I can reproduce the same problem on aarch64, raspberry-pi, whilst using the following recipe

Funny thing is: it used to work before, and I didn't change the recipe.

```bash
build()
{
    install -m 644 -D $name.service $PKG/etc/systemd/system/navidrome.service
    install -m 644 -D $name.toml    $PKG/var/lib/navidrome/navidrome.toml
    install -m 644 -D nginx_$name.conf $PKG/usr/local/share/doc/navidrome/nginx_$name.conf
    cd navidrome # -$version
    export PATH=$PATH:/usr/local/go/bin
    make setup
    make buildjs # Problem occurs with and without this line
    make buildall
    install -m 755 -D $name $PKG/usr/local/bin/navidrome
}
```
