### ISSUE TITLE
Granular configuration of external services (e.g. LastFM)

### ISSUE THREAD

**Issue by blunderberg** [navidrome/navidrome#1513]
This was inspired by #1488

Disabling any links, buttons, placeholders etc. pointing to external services would be a nice option. 9/10 secret squirrels recommend it.
LastFM is just one example, but this should be configurable for all (current and future) external services.

Reasons:
Some people don't care about LastFM content.
Not all links created using the pattern described in #1488  actually exist on LastFM (https://www.last.fm/music/{ArtistName}).
The LastFM link/button takes up space if not used.
Other "placeholders" not used (if integration is disabled) should either be removed as part of disabling the integration or using the specific feature flags (e.g. artist biography on artist detail page).

### Describe the solution you'd like

Granular configuration using feature flags (enable/disable) to allow for all external services links, buttons, placeholders to be disabled (finetuned).

![image](https://user-images.githubusercontent.com/83293651/145656326-4fcff8d4-7779-4d5a-b144-dcdc8e65d380.png)

**Comment by Dnouv** [comment]
Thank you for reporting this issue, @blunderberg. A similar issue was discussed in the past for disabling external lookups #102; there is an option `EnableExternalServices `  available in the config file, which can be set to `false` to disable the external links.
I hope you were referring to some solution like this. If I got something wrong, please feel free to comment. 
Thank you!

**Comment by blunderberg** [comment]
@Dnouv
that option does not remove LastFM link/icon - that was already discussed in #1488 and it was pointed out that disabling LastFM does not fully remove everything. Same is true for the "artist biography" as shown in the screenshot. I have the two options set and still see remnants of various external services.
ND_ENABLE_EXTERNAL_SERVICES: "false"
ND_LASTFM_ENABLED: "false"

**Comment by Dnouv** [comment]
@blunderbergm, thanks for correcting me. As far as I understood your issue, you can set `DevShowArtistPage` as false in the configuration file, which would set the artist page to the old style(no bio+no LastFM link).
I hope this may be of some help. Please feel free to comment. Thank you!

**Comment by blunderberg** [comment]
@Dnouv 
Thank you for the dev option - that removed the whole artist header (image, star rating, heart/loved, bio, LastFM link).
This is a good result, however, the LastFM button/link is still present on the individual album header.

![image](https://user-images.githubusercontent.com/83293651/146918732-82a088ff-ca7a-42d1-b7a6-4da278c163fb.png)

It would be great if the existing LastFM.Enabled option controlled all aspects of the LastFM service, or if there were additional (granular) options that would allow for finetuning of external services - this is the primary reason for my suggestion to allow granular control of all external services. The more I think about it, the more I'm leaning toward the straight forward and logical approach; when LastFM.Enable (or any other external service option) is set to "false" any and all LastFM features, functionality, links, buttons, etc. are disabled across the entire system.

This is just a suggestion. Navidrome is still the best personal music streaming server on this planet.

**Comment by Dnouv** [comment]
Thank you so much for your good words; your suggestion means a lot. Your idea is excellent; let's keep this issue open. I'm currently working on some other features of the Artist page; as soon as they are completed, I'll try to work on this issue; meanwhile, if someone would like to work on these contributions, they are welcome.
Thank you!

**Comment by celynw** [comment]
I found this issue when I too was confused to find LastFM link when I had set `lastFMEnabled` to `false`.
As far as I can tell, after the config option `lastFMEnabled` is set to `false`, the only things remaining are:

1. LastFM link in the album page
2. LastFM link in the artist page
3. Biography and artist images in the artist page

For 1 and 2, it's quite simple to remove the LastFM links based on the value of the config option.

For 3, if the biography and artist images are never populated, it makes the artist page a bit pointless. Setting `devShowArtistPage` to true like @Dnouv [mentioned](https://github.com/navidrome/navidrome/issues/1513#issuecomment-998189953) seems like a good idea, although it does remove the ability to set the artist as favourite (heart) or set a 5-star rating here.

You can still do this from the artist list. Is that enough? Maybe a thin artist page (i.e. without the placeholders) might still be nice to have?

Regarding granularity of config options maybe:

- `lastFMEnabled` should hide the LastFM artist and album links, but not the placeholders for artist images or biographies. This would allow other providers (could be implemented in the future?) to still function
- There should be a global toggle for `ExternalMetadata` which would disable showing the artist images (or placeholders if there's no provider). This would allow the LastFM links to still be shown if you wanted, even if the metadata retrieval was disabled.

What do you think? I could submit a pull request to hide the LastFM buttons if LastFM is disabled in the config, and try tackling the other part in a separate one?

(And I wonder if navidrome would participate in hacktoberfest 👀)

**Comment by deluan** [comment]
Hey @celynw, sorry for the delay, missed the hacktoberfest... :(

Anyway, thanks for the PR, it is merged. Regarding the Biography and Images in the page Artist, this will change soon once we introduce local artist images, so I don't think it should be the scope of this issue.

@blunderberg AFAICT, the original request is fulfilled by @celynw's PR, so I'm closing this. Feel free to chime in if you have any other concerns.
