### ISSUE TITLE
How many simultaneous connections can navidrome handle?

### ISSUE THREAD

**Issue by izyspania** [navidrome/navidrome#1514]
How many simultaneous connections can navidrome handle? What specs should server have for about 500 burst users? Im building a server with audiobooks for the blind people in my city (city association) so it could have from 100 to 2000-3000 members and i am not sure what server hardware should i have for this many users (im just assuming that sometimes they could be a max of 500 simultaneous connections but in general will be 10 -30 with burst of max 50-100) or if navidrome is suited for this amount of users. Most of them they will use an android app so the most traffic/usage will be from there (i can set the app to preload 3 5 chapters in advance). Thanks

There will be like 100k audiobook files (chapters), 5-20 files per Album/book. 96kbps to 192kbps, most of them 128 kbps (so i can disable transcoding for performance). The folder structure is Artist - Book Name - Audiobooks chapters with names ( 1 - chapter one , 2 - chapter two   etc.) (1Gbs server connection)

Is it possible to add an script for googlebooks? (Booksonic app already has it but would be nice if i could add it to navidrome so i can get book descriptions)

Edit: Can it use more than 1 core?

**Comment by Dnouv** [comment]
@izyspania, thank you for trying navidrome. Well, I'm not sure about the possibility of adding a google books script; however, for your other question related to file size handling, Navidrome could smoothly handle 600GB+ libraries. 
Please feel free to comment. Thank you!

**Comment by deluan** [comment]
Hey @izyspania, if you don't use transcoding, Navidrome should handle easily this traffic with average hardware. I don't have numbers, you'd have to try. Using apps that preloads files (ex: DSub) would help as well

> Is it possible to add an script for googlebooks? (Booksonic app already has it but would be nice if i could add it to navidrome so i can get book descriptions)

Navidrome does not officially support Audiobooks, just the basic Subsonic API endpoints. We may introduce more audiobooks features in the future, but it has low priority for now.

I'm closing this as there's nothing much more info we can provide for this, but feel free to experiment with it and reach out if you have any issues.

**Comment by izyspania** [comment]
Thanks.
