### ISSUE TITLE
Feature Request: Collaborative Playlists

### ISSUE THREAD

**Issue by nep2ner** [navidrome/navidrome#1523]
### Is your feature request related to a problem? Please describe.

There is no way to enable multiple users adding songs to a playlist.

### Describe the solution you'd like

Allow the owner of a playlist to give another user permission to add/remove songs.

### Additional Context 

Or maybe I am just missing where to find this feature in the UI?

**Comment by metalheim** [comment]
It's not implemented afaik and would be a nice touch really.

The basic implementation of this is probably not that difficult, would need a new table thats defines user<->playlist Permissions.

Really nice would be "this song has been added by UserA on date", but that makes things more complex i guess. Also not compliant with Subsonic API spec, so Navidrome-UI only.
