### ISSUE TITLE
Lexicographic sort order in search results and playlists for albums 

### ISSUE THREAD

**Issue by bbsixzz** [navidrome/navidrome#1534]
On a tangent to https://github.com/navidrome/navidrome/issues/273 search results and playlists do not sort numerically.

<img width="1065" alt="lexigraphic" src="https://user-images.githubusercontent.com/47334163/147016136-f5f8ee64-911d-4d8d-85b1-3db3f0c221c0.png">
<img width="789" alt="Screenshot 2021-12-20 at 21 14 50" src="https://user-images.githubusercontent.com/47334163/147016141-d364c15c-d57e-405e-93a0-d3027821f565.png">

Is this working as intended?

**Comment by Dnouv** [comment]
Thank you for trying out Navidrome @bbsixzz .
 > * Tracks out of order: When sorting by `track #`, the actual sort used is `disc#/track#`, you may have a wrong `disc #`. See [Sorting order for the track number is lexigraphic instead of being numeric #273](https://github.com/navidrome/navidrome/issues/273) and please confirm this is your case
> * Yes, right now Navidrome only indexes album artists. Please see [Import all artists found in tracks, and make them browseable/searchable/filterable #211](https://github.com/navidrome/navidrome/issues/211)

Please have a look at the above comments by deluan. I hope this might answer your question. Please feel free to comment if I misunderstood your question or missed something.
Thank you!

**Comment by bbsixzz** [comment]
My screenshots indicate albums in search results and playlist (when set to sort by album) are not sorted numerically.

In the search results I would like it to be like this (numerical):

Total 2
Total 3
Total 4
Total 5
Total 2
Total 10
Total 11
Total 12
Total 14
etc.

Instead it's lexicographic like this:

Total 10
Total 11
Total 12
Total 14
Total 2
Total 3
Total 4
Total 5
Total 2

The same problem can be seen in the playlist when sorted by album.

This is related to https://github.com/navidrome/navidrome/issues/273 but is not the same issue.

I do not see what https://github.com/navidrome/navidrome/issues/211 has to do with anything.

My question is if this is working as intended, does the developer want lexicographic sorting as default?

If so, could we please have an option to set numerical sorting?

Cheers

**Comment by witten** [comment]
On my system (Navidrome 0.47.5), search results appear to be *randomly* ordered. E.g., each time I type a character, I get different ordering among the results. This is even if I backspace and re-type the same character at the end of a search term.

Let me know if I should file a separate ticket for this.
