### ISSUE TITLE
See the artist photo

### ISSUE THREAD

**Issue by Vctrsnts** [navidrome/navidrome#1536]
Hi, 

Sorry for my question, but how you make to see the photo of artist? Because on the "demo" if I select any artits ( for example Back On Earth ) I see the photo.

Thanks a lot

**Comment by metalheim** [comment]
The auxiliary artist info comes from external services that you'll You need to configure.
Have a look on the documentation page of navidrome:
https://www.navidrome.org/docs/usage/external-integrations/

**Comment by Vctrsnts** [comment]
Thanks a lot

👍🏻
