### ISSUE TITLE
UX Improvement: don't duplicate play, play next, play later in bulk action buttons

### ISSUE THREAD

**Issue by Sohalt** [navidrome/navidrome#1537]
When selecting songs with the checkboxes you need to use the bulk action buttons on the right. However, there are already buttons to do the same actions at the top, the only difference being, that they act on all songs in the album/list. I think this is confusing and propose 
to remove the bulk action buttons and make the buttons on the top aware of the selection instead.

![navidrome](https://user-images.githubusercontent.com/2157287/147355229-b7bb182f-eb04-46cb-919a-c5e6d454fe26.png)

It would also be good to reduce the height of the popup showing "3 items selected", so it does not overlap with the big round play button.

Maybe one could give the "play next", "play later", "add to playlist", and "download" buttons above a very thing green outline or otherwise green highlight in the same color as the popup, when songs are selected, to convey that they now work on the selection instead of the whole album.

**Comment by Ayush01729** [comment]
Hi @Sohalt , I am working on this issue.

**Comment by Ayush01729** [comment]
@Sohalt , why am I not getting the whole list of songs like the example displayed above?? 
Also, I am getting a bit different UI ( green replaced with blue),  could you please point out the reason ?
![Navi](https://user-images.githubusercontent.com/76625106/147491579-41ff0790-e0df-41e7-adcd-01a229790ec7.PNG)

**Comment by Sohalt** [comment]
@Ayush01729 to get the green theme you need to click on the "user" icon in the top right corner and then on settings and choose the "spotify-ish" theme.
To get songs displayed you need to have the album in the music folder that is indexed by Navidrome (and it takes some time for Navidrome to index the music on the first run).

**Comment by Ayush01729** [comment]
Thanks, @Sohalt, that's very great of you.

**Comment by Ayush01729** [comment]
Thanks, @Sohalt, that's very great of you.
