### ISSUE TITLE
same songs in different cd of an album are unorganized

### ISSUE THREAD

**Issue by grbharati** [navidrome/navidrome#1538]
Hello team:

I have an example album: The darkside of the moon by Pink Floyd, which has 6 CDs and it has different version of the same songs in different CDs. I created the metadata using musicbrainz picard and it created the filename accordingly:

![image](https://user-images.githubusercontent.com/69709740/147381108-9b8441bf-a2a0-4930-baee-902b384ce115.png)

Now if I look in the Navidrome, I see all the songs in the single CD as below:
![image](https://user-images.githubusercontent.com/69709740/147381155-5b5a0e67-07d7-488b-9ffb-2146f995826d.png)
I am not sure what I am doing wrong. Sorry didn't know where to put so started with a bug report.

I am using:
![image](https://user-images.githubusercontent.com/69709740/147381194-52bad533-f21a-45a9-8200-a9fa2385be9f.png)

Thank you

**Comment by metalheim** [comment]
For navidrome to know that these are separate discs you have to tag the files with the `DISCNUMBER`.
I don't use Picard, but you can surely tell it to include that somewhere in it's options.

**Comment by grbharati** [comment]
> 

Thank you, somehow in the picard, there were 2 ids for disc, in which one of them was 1 for all the CDs. Now after I changed them things are working fine.

thank you
![image](https://user-images.githubusercontent.com/69709740/147421737-986a3055-8ae7-4c97-9242-5454f6edfa07.png)
