### ISSUE TITLE
/metrics target

### ISSUE THREAD

**Issue by jelmer** [navidrome/navidrome#1548]
### Is your feature request related to a problem? Please describe.

It would be great if navidrome supported a /metrics target for easy monitoring with e.g. Prometheus.

(See https://openmetrics.io/ for details about openmetrics)

### Describe the solution you'd like

It would be great if there was a /metrics target provided by navidrome, either on the standard port or a separate port with key metrics. In particular, I'm interested in things like:

 * size of database
 * number of connected users
 * number of files that failed to be scanned

### Describe alternative solutions that would also satisfy this problem

Another option would be to have a separate exporter that could run alongside navidrome and introspect its state some other way. However, this would require more setup work for users and would need to be actively maintained as interfaces in navidrome change.

See e.g. https://prometheus.io/docs/instrumenting/exporters/

### Additional context

This would be helpful when e.g. running navidrome in kubernetes, along with e.g. a /health target for regular health checking.

**Comment by Dnouv** [comment]
Thanks for your suggestion @jelmer, how about incorporating all these details in the `Activity` button on the top bar? 
Here,
<img width="262" alt="image" src="https://user-images.githubusercontent.com/61188295/147897053-39c51842-a7e0-4306-b3fb-2fb2296bcdaf.png">
Although this is a major change, we also need deluan's or jvoisin's opinion on this feature.
Please feel free to comment.
Thank you!

**Comment by jelmer** [comment]
This is just something that would be exposed over HTTP, not something visible in the UI - it's something that would be scraped by e.g. Prometheus, rather than be consumed directly by humans.

**Comment by quinqu** [comment]
I'd be interested in taking on this feature if you all decided to go forward with it. There is a [Go client library](https://prometheus.io/docs/guides/go-application/) for prometheus and I don't believe it would be a major change if we are just adding support for tracking 3 metrics.

**Comment by jelmer** [comment]
Those three metrics were just what was first on my mind - I suspect there are others that may be useful to track.

I agree this doesn't need to be an intrusive change.

**Comment by deluan** [comment]
@jelmer This is straightforward to implement as a HTTP endpoint. Without digging too much into the links above, the main complication I see is how to *not* expose it publicly, as these metrics can be considered sensitive information for most of Navidrome users. Maybe a simple solution could be turn this off by default, and if the user wants to turns it on, it is their responsibility to protect it (ex: via a rule in their reverse proxy)

@quinqu You are more than welcome to implement this, but I'm not sure if the Prometheus library is the way to go. As you said it is adding a new dependency (and possibly some runtime instrumentation) that is not required if all we want to expose is some custom information.

@Dnouv We may add some of this info in the Activity Panel, once it is stable enough to be always on. Currently it causes some freezes for some users: #1186 #1511

**Comment by jelmer** [comment]
@deluan Some other tools that support openmetrics have an option for a separate port that they expose metrics on (and e.g. a /health target, for Kubernetes health checking). That makes it really easy to avoid exposing these through a reverse proxy.

**Comment by deluan** [comment]
Yeah, putting it under a separated port could be easier (for the user, not much for us :P ) 

Regarding the metrics themselves, some considerations:
- **size of database**: This is straightforward if you are talking about number of artists, albums, songs, total length/size. To get the actual DB file size, you'd probably have to resort to the `os` package ad get the size of the `DataFolder` directory recursively
- **number of connected users**: this is hard, as Navidrome is a stateless server and there's no tracking of who is logged in. Even the `NowPlaying` endpoint is "guessing" it by recording the start of a song and considering it is active for up to one hour. Which can be completely wrong...
- **number of files that failed to be scanned**: We don't currently have this information, and this will require some digging in the scanner code, to expose this information

**Comment by jelmer** [comment]
For posterity, I think this should be "fixed" rather than "not planned" since there is now a basic /metrics I think?

**Comment by AlekseyLobanov** [comment]
> For posterity, I think this should be "fixed" rather than "not planned" since there is now a basic /metrics I think?

Agree.
