### ISSUE TITLE
Add repeat functionality and toggle button

### ISSUE THREAD

**Issue by Tyfuzzle** [navidrome/navidrome#1553]
### Is your feature request related to a problem? Please describe.

On the web UI, I would like to be able to listen to queued up tracks, be it an album(s), playlist(s) etc., on repeat so I don't have to manually play the queue from the start once it's finished playing the last track.

### Describe the solution you'd like

I would like a toggle on the bottom "now playing" bar (maybe to the right of the "next track" button) to enable or disable repeating. 
A similar toggle for shuffle would also be nice.

**Comment by srichter** [comment]
You can change the play mode here

![Screen Shot 2022-01-04 at 17 45 59](https://user-images.githubusercontent.com/933620/148134277-57b52e5c-60d6-41b2-9b51-de9da1e5a6de.png)
