### ISSUE TITLE
Add the ability to randomise the artists list

### ISSUE THREAD

**Issue by Tyfuzzle** [navidrome/navidrome#1554]
### Is your feature request related to a problem? Please describe.

In the web UI, I would like to be able to view the list of artists in a randomised order, like you can with albums.

### Describe the solution you'd like

The albums section has a sub-menu with a few options, including "all", "random", "favourites" etc. A similar sub-list for the artists would likely be the best way to add this, for consistencies sake, perhaps with all the same options as the album section in the future.

### Alternative solutions

This could also be achieved with a "randomise" button in the artists screen, perhaps to the left of the "add filter" button.

**Comment by Dnouv** [comment]
@Tyfuzzle, thank you for your suggestion; I guess the "randomize" button would be a better option than a new sub-section; however, maybe not many users would use this feature. Let's keep the issue open, and based on votes for this feature, we'll add it to Navidrome.
If you have any new suggestions, please feel free to comment.
Thank you!

**Comment by deluan** [comment]
@Hansi7 Is this what you are looking for?

https://user-images.githubusercontent.com/331353/200855275-e99643ed-9fca-476c-b97a-e9cf4220c802.mov

**Comment by Hansi7** [comment]
> @Hansi7 Is this what you are looking for?
> 
>  Screen.Recording.2022-11-09.at.9.22.56.AM.mov

thank you! that's what i'm looking for! 
I was looking for  some text like "add all to playlist".  ^-^, silly me.
