### ISSUE TITLE
Group albums not only by album tag

### ISSUE THREAD

**Issue by jan666** [navidrome/navidrome#1555]
Sometimes there is more than one release with the same name. For example the artist "Pershing Boys" has a demo tape calles "Pershing Boys" and an album called "Pershing Boys" (see https://musicbrainz.org/artist/0c8e3043-7b42-4a97-9917-a57e9116cf6f)

Or there are 2 different releases of the album with different tracks or versions of the tracks (see for example https://musicbrainz.org/release-group/1f6f0de1-cba7-351a-9e22-d65e4ab759a9).

In the two cases navidrome lists all titles under one "album". This is not really correct as there are different releases.

I dont really want to change the tags because I use MusicBrainz for tagging. 

Maybe its possible to group only if album AND year tag is the same?

**Comment by metalheim** [comment]
Unfortunately it's not that simple, as some albums span across different years. (Compilation albums or Albums with 2discs)
And these shouldn't be split up.

I think musicbrainz provides (and tags if you specify it in Picard) a unique "Release ID" that is much more precise and should be used to deal with this issue.

**Comment by jan666** [comment]
IMO a compilation album is released in one year.

But yea - the musicbrainz release id tag would be even better.

**Comment by jan666** [comment]
I just noticed this is a duplicate of #489
