### ISSUE TITLE
Set default language in config file

### ISSUE THREAD

**Issue by vitormfgoncalves** [navidrome/navidrome#1561]
### Is your feature request related to a problem? 

- No

### Please describe. 

- Its frustrating when your native language is not english and you jump from device to device and have to set preferences again and again.

### Describe the solution you'd like

- An option to set the default language in the config file

**Comment by metalheim** [comment]
Agree! 
Imho it's a bit of an oversight that this hasn't been done before?
And it should be an easy enough change.

**Comment by methatronc** [comment]
I'd love to see that as well :)

**Comment by deluan** [comment]
> Agree! Imho it's a bit of an oversight that this hasn't been done before? And it should be an easy enough change.

It was not an oversight. I tried it before a couple of times, but because the way React-Admin apps are structured, I'd have to add all languages in the final bundle, which would make the initial load larger and slower. 

I tried it again and I think I found a good solution. The new config option is `DefaultLanguage`, and it has to be the 2 letter ISO code for the language (see the list here: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)

Please test it and let me know.

**Comment by metalheim** [comment]
@deluan tested with latest develop branch ba28e9a109fb3bb57233f2b4c6ad8ad95f4c3f86.
Works well and as expected.

One thing to add: The new `DefaultLanguage` setting is case sensitive, only lowercase entries work.
f.e. this works:
`DefaultLanguage="pt" `
but this doesnt:
`DefaultLanguage="PT"` 

Which is fine, just something to be aware of.

**Comment by deluan** [comment]
> One thing to add: The new `DefaultLanguage` setting is case sensitive, only lowercase entries work.

Fixed. Thanks for testing.

**Comment by methatronc** [comment]
Just tested with latest docker hub release 0.48.0, it works fine with this in the docker compose :
ND_DEFAULTLANGUAGE: "fr"
Thank you for this :beer:

**Comment by SoSolife** [comment]
> > One thing to add: The new `DefaultLanguage` setting is case sensitive, only lowercase entries work.
> 
> Fixed. Thanks for testing.

But for "zh-Hans" it occurs error that `translation(id:zh-hans) not found`.

**Comment by zheyiyuezhuo** [comment]
> > > One thing to add: The new `DefaultLanguage` setting is case sensitive, only lowercase entries work.
> > 
> > 
> > Fixed. Thanks for testing.
> 
> Thanks for adding the option. However for "zh-Hans" it occurs error that `translation(id:zh-hans) not found`.

![图片](https://user-images.githubusercontent.com/46232425/198854426-0d55be2b-8bb8-4d74-b7c1-9a7cc7c11fcf.png)

You has to be 2 letter ISO code for language . The China`s 2 letter is 'zh' .

**Comment by SoSolife** [comment]
> > > > One thing to add: The new `DefaultLanguage` setting is case sensitive, only lowercase entries work.
> > > 
> > > 
> > > Fixed. Thanks for testing.
> > 
> > 
> > Thanks for adding the option. However for "zh-Hans" it occurs error that `translation(id:zh-hans) not found`.
> 
> ![图片](https://user-images.githubusercontent.com/46232425/198854426-0d55be2b-8bb8-4d74-b7c1-9a7cc7c11fcf.png)
> 
> You has to be 2 letter ISO code for language . The China`s 2 letter is 'zh' ?

Unfortuately, it don't define in the resources [i18n](https://github.com/navidrome/navidrome/tree/master/resources/i18n). 
And the author has [restore DefaultLanguage case-sensitiveness](https://github.com/navidrome/navidrome/commit/aab4925dfcfd67fe77981659286acd50eb2a88de).

**Comment by YEDEDD** [comment]
I tried `ND_DEFAULTLANGUAGE = zh`, but the default language was not changed to Chinese, and the others were not successfully changed, and the browser was in seamless mode.

**Comment by deluan** [comment]
The `DefaultLanguage` option has to match one of the file names in the [`resources/i18n`](https://github.com/navidrome/navidrome/tree/master/resources/i18n) folder as @SoSolife mentioned. So for Chinese simplified it has to be `zh-Hans`, and it is case sensitive.

It is only used for new sessions. So, if you already logged from a browser, it won't use the default anymore.
