### ISSUE TITLE
Songs of different artists in the same album will be recognized as different albums.

### ISSUE THREAD

**Issue by shanyan-wcx** [navidrome/navidrome#1562]
### Expected Behaviour

What you would have expected to happen instead.

### Steps to reproduce

1. Open the '...'
2. Click on '...'
3. Scroll down to '...'

### Platform information

 - Navidrome version: 
 - Browser and version: 
 - Operating System: 

### Additional information

Any other information that may be relevant or give context to the problem.

 - Screenshots (if applicable)?
 - Logs? 
 - Client used?

**Comment by metalheim** [comment]
That's actually not a bug, but Intented behavior.
If you want them grouped together, you should tag the "Album artist". 

If the album doesn't have one definite "album artist", you can tag every song in that album as a "compilation" and it will also be grouped together.

**Comment by deluan** [comment]
Yes, what @metalheim said. Please also take a look here: https://www.navidrome.org/docs/faq/#i-have-an-album-with-tracks-by-different-artists-why-is-it-broken-up-into-lots-of-separate-albums-each-with-their-own-artist
