### ISSUE TITLE
Why does the album display such information?

### ISSUE THREAD

**Issue by shanyan-wcx** [navidrome/navidrome#1563]
![屏幕截图 2022-01-06 162005](https://user-images.githubusercontent.com/58252651/148351966-e189f971-7d70-4dca-b5a4-6c8706c3ae65.png)

**Comment by metalheim** [comment]
Most probable because it's in (on of the) files "comment" tag

**Comment by shanyan-wcx** [comment]
I don't know how to remove it

**Comment by metalheim** [comment]
Any tagging software should be able to set, modify and remove comments.

I like to recommend "mp3tag" as it works with most formats (contrary to its name) and is available on multiple platforms.
If you're on Linux "kid3" also does a good job
