### ISSUE TITLE
Unique constraint errors (genre) on scan

### ISSUE THREAD

**Issue by fabpico** [navidrome/navidrome#1564]
### Description
I am getting unique constraint errors in the scan log when scanning. I scan 2’855 Files in 239 Folders. Most of the scan log entries are infos.

### Expected Behaviour
No contraint errors should happen / be logged.

### Steps to reproduce
1. Add files to `music` folder
2. Open the terminal
3. Run `scan`

### Platform information
 - Navidrome version: `0.47.0 (8c7d95c1)`
 - Operating System: `Ubuntu 20.04.3 LTS`
 - Docker image: `deluan/navidrome:0.47.0`

### Additional information
 - Logs
`ERRO[0025] Error updating folder in the DB               dir="/music/[path]" error="UNIQUE constraint failed: media_file.id"`
`ERRO[0026] Error updating folder in the DB               dir="/music/[path]" error="UNIQUE constraint failed: media_file_genres.media_file_id, media_file_genres.genre_id"`
`ERRO[0096] Error writing albums to the DB                error="UNIQUE constraint failed: album_genres.album_id, album_genres.genre_id"`
`ERRO[0099] Error updating folder in the DB               dir="/music/[path]" error="UNIQUE constraint failed: media_file_genres.media_file_id, media_file_genres.genre_id"`

```
ERRO[0008] SQL: `INSERT INTO genre (id,name) VALUES (?,?)`  args="['3d8dd8ae-cb27-47e0-a55e-62dc1d500826','Minimal']" elapsedTime="767.806µs" error="UNIQUE constraint failed: genre.name" rowsAffected=0
ERRO[0008] SQL: `INSERT INTO genre (id,name) VALUES (?,?)`  args="['eb61e4dc-111d-4a93-9112-3b630a31e018','Minimal']" elapsedTime="364.883µs" error="UNIQUE constraint failed: genre.name" rowsAffected=0
ERRO[0008] SQL: `INSERT INTO genre (id,name) VALUES (?,?)`  args="['9b3bb53e-2b2b-4d75-af80-1792eb62605e','Minimal']" elapsedTime="405.682µs" error="UNIQUE constraint failed: genre.name" rowsAffected=0
ERRO[0008] SQL: `INSERT INTO genre (id,name) VALUES (?,?)`  args="['7846779b-f947-4428-ab45-b3af273fdb55','Minimal']" elapsedTime="376.545µs" error="UNIQUE constraint failed: genre.name" rowsAffected=0
ERRO[0008] SQL: `INSERT INTO genre (id,name) VALUES (?,?)`  args="['66a502e7-4b25-4551-ada9-8445722bf9df','Minimal']" elapsedTime="384.746µs" error="UNIQUE constraint failed: genre.name" rowsAffected=0
ERRO[0008] SQL: `INSERT INTO genre (id,name) VALUES (?,?)`  args="['653298d0-f844-4fd0-9023-2599ff0acc80','Minimal']" elapsedTime="925.026µs" error="UNIQUE constraint failed: genre.name" rowsAffected=0
ERRO[0008] SQL: `INSERT INTO genre (id,name) VALUES (?,?)`  args="['249ecd8d-dd03-4cea-ae3c-7e923da27df2','Minimal']" elapsedTime="382.917µs" error="UNIQUE constraint failed: genre.name" rowsAffected=0
ERRO[0008] SQL: `INSERT INTO genre (id,name) VALUES (?,?)`  args="['b8f04650-df05-4b5f-a205-44a0b6825a4e','Minimal']" elapsedTime="392.301µs" error="UNIQUE constraint failed: genre.name" rowsAffected=0
ERRO[0008] SQL: `INSERT INTO genre (id,name) VALUES (?,?)`  args="['405db359-2c39-497d-8772-c9ccac6e9d97','Minimal']" elapsedTime="418.633µs" error="UNIQUE constraint failed: genre.name" rowsAffected=0
```

**Comment by vs49688** [comment]
Confirmed, I've just hit the same issue. Interestingly, it only happens when run in a Docker container. The exact same binary works when run outside it.

**Comment by vs49688** [comment]
Hacky workaround for now:
```
DELETE FROM genre;
DELETE FROM album_genres;
DELETE FROM artist_genres;
DELETE FROM media_file_genres;
```
and a full rescan.

**Comment by vs49688** [comment]
Root cause: https://github.com/navidrome/navidrome/issues/1918
