### ISSUE TITLE
Interface improvement suggestions

### ISSUE THREAD

**Issue by vitormfgoncalves** [navidrome/navidrome#1568]
#### No.

Interface usability problems:
1 - No "clear way" to play only the liked songs, no way to filter only rated songs....
2 - When in window mode (aka, Chrome APP) there is no clear way to go back to previous page.
3 - Sometimes, the progress bar's clicable area is invisible above the white line. It's dificult to aim at an invisible object.

### Describe the solution you'd like

Interface usability suggestions:
1 - Songs and Artists sub-menus with Random, Favourite, Top Rated, etc. (like Albuns)
2 - A button to go back  (maybe on top, like spotify)
3 - Align white line and click area.

**Comment by vitormfgoncalves** [comment]
In the 3# problem i found a possible solution:
Adding CSS "z-index:78" to the clickable element (.rc-slider) puts it above the previous div (.progress-load-bar) wich have z-index set to 77.
This solves the problem without messing with funcionality.
I guess this can be done in the themes, right?

**Comment by certuna** [comment]
The progress bar problem is probably in the upstream player component: https://github.com/lijinke666/react-music-player

I think you can submit your fix there.

**Comment by vitormfgoncalves** [comment]
> The progress bar problem is probably in the upstream player component: https://github.com/lijinke666/react-music-player
> 
> I think you can submit your fix there.

Yes, probably.
I added my fix (and other things) to the theme's css and it fixed the problem.

**Comment by yllekz** [comment]
Definitely think a global back button is in order. I have been using this as a web app in Linux Mint and keep attempting to implicitly reach for a back button that doesn't exist.
