### ISSUE TITLE
Authentication Cookies dont respect ND_BASEURL setting

### ISSUE THREAD

**Issue by ndecker** [navidrome/navidrome#1580]
### Description

The authentication cookies are set with a path of "/" even if ND_BASEURL is set to some path.

When multiple instances of navidrome are running on the same host behind a reverse proxy, loging into one instance overwrites the cookies of the other instance.

### Expected Behaviour

Setting the authentication cookies should be restricted to the ND_BASEURL path.
Ist should be possible to stay logged in into multiple navidrome instances. (For example /navidrome1 and /navidrome2)

### Steps to reproduce

Observe the cookies set by the login process using the browser developer tools.

### Additional information
Lines where the cookie path is set:
* https://github.com/navidrome/navidrome/blob/master/server/middlewares.go#L116
* https://github.com/navidrome/navidrome/blob/master/server/subsonic/middlewares.go#L164

**Comment by deluan** [comment]
Thanks for reporting this. Will fix for next release, but would gladly accept a PR fixing this ;)
