### ISSUE TITLE
Can't play .wma

### ISSUE THREAD

**Issue by fabpico** [navidrome/navidrome#1592]
Already checked for other issues concerning .wma. https://github.com/navidrome/navidrome/issues?q=is%3Aissue+wma , no specific issue for that exists.

### Description

I added .wma tracks which can't be played. The same album contains .mp3 files that can be played.

### Expected Behaviour

.wma tracks should be playable like .mp3 tracks.

### Steps to reproduce

1. Open the start page
2. Click on an album with .wma tracks
3. Click on a .wma track
4. See Play/Pause icon keeps loading and the track does not start playing

### Platform information

 - Navidrome version: `0.47.0 (8c7d95c1)`
 - Browser and version: Windows's Chrome `97.0.4692.99 (Official Build) (64-bit)`, Android's Firefox `96.2.0`.
 - Operating System: Docker image `deluan/navidrome:0.47.0`

### Additional information

When I download such a .wma file on Windows over the Navidrome GUI, I can play that downloaded .wma file on Windows.

**Comment by metalheim** [comment]
The problem here is, that no big browser supports wma encoded audio (chromium/webkit/gecko).
A workaround would be to enable Transcoding for the Navidrome web player (Settings->Players->NavidromeUI).

Maybe transcoding of wma could be enabled by default? But this requires #351

**Comment by FabianPiconeDev** [comment]
Setting the transcoding to mp3 indeed let the .wma tracks work on Window's Chrome and Android's Firefox. Can this be applied as default behavior for .wma files?

**Comment by shivan** [comment]
Mhmm... currently I do not understand yet how to configure that (only) WMA files will be transcoded to MP3.... or is it only possible to configure transcoding per player and not per file type?
Also I did not find a suitable commandline for that....

**Comment by dweymouth** [comment]
See also https://github.com/navidrome/navidrome/issues/351 which discusses general improvements to the transcoding engine

**Comment by deluan** [comment]
> But strangely, it works only for some of them and not for many others

Many other files or browsers? Can you share the debug logs, so we can figure out what is going on?
