### ISSUE TITLE
Group for Playlists

### ISSUE THREAD

**Issue by ghost** [navidrome/navidrome#1593]
### Is your feature request related to a problem? Please describe.

I manage my music collection according to different criteria (added date, ratings, events, etc.) in various playlists, as well in smart playlists. Everything works really well, but the overview gets a bit lost because the list is getting longer and longer... 

So would it be possible to create group folders to be able to summarize the playlists?

### Describe the solution you'd like

I thought on something that is similar to spotify or in a way like the shared playlists.

As a small workaround I use exactly that. I created a second account and assigned the most important playlists to them.

**Comment by nagarrido** [comment]
I would also love this feature

**Comment by deluan** [comment]
Thanks for the suggestion, this will be implemented in a future release. I'm closing it as it is a duplicate of #1858. Please subscribe to that issue to receive updates.
