### ISSUE TITLE
caching of artist images

### ISSUE THREAD

**Issue by kzshantonu** [navidrome/navidrome#1601]
Hi, really love the project. Is there any way to pull all the artist images at once? I use bonob and would really like to see images for all artists on my sonos app

**Comment by vvyushmanov** [comment]
support this suggestion.
Also, can there be an option to re-fetch or re-cache the images?
I ran into a problem where I haven't set up the Spotify API initially, and some artists got the "grey star" from last.fm that won't go away even after Spotify is set up properly and new artist get the pictures correctly.

**Comment by crosbyh** [comment]
I'm experiencing this as well - I've set up the Spotify API (since the Last.fm API has disabled Artist Images now), but none of my artist images populate.
