### ISSUE TITLE
Song never completes loading

### ISSUE THREAD

**Issue by dln949** [navidrome/navidrome#1607]
Navidrome 0.46.0 running on Ubuntu 20.04.  Trying to access it using Brave browser 1.35.101 Chromium 98.0.4758.87 running on Ubuntu 18.04.  

Up until recently this worked great.  

Now, when I try to play a song via Navidrome using the Brave browser on the 18.04 machine, I am able to browse and select the song (mp3 file), but when I click on play, it is forever stuck in the "loading" mode, but the song never completes loading.  This is true for all mp3 files I try, even those that are quite small.

**Comment by tuxthepenguin84** [comment]
Seeing a similar issue with the latest Docker image at the time of this writing. I turned on debug logging but nothing is standing out. On Chrome 100

**Comment by WhaleJ84** [comment]
I had the same issue in 0.47.5. After reading [#813](https://github.com/navidrome/navidrome/issues/813) above, I could verify the songs that were not playing were ALAC encoded.
Thanks to the post, I was able to resolve the issue by going to Settings>Players>**your player**>Transcoding in the web GUI for Navidrome and setting it to mp3.

Hopefully this works for you
