### ISSUE TITLE
Full rescan does not update removed "disc number" and added "compilation" tags

### ISSUE THREAD

**Issue by pacija** [navidrome/navidrome#1623]
Hi,

I have been tidying up some tags in my library, namely removing all "disc number" tags, and adding extended "compilation" tag to compilations. I noticed that full re-scan apparently does not take these into account, and leaves them at values from first scan.

**Comment by metalheim** [comment]
Navidrome scans for updated timestamps reported by the filesystem. Can you check if the "Changed Date" of your files were updated when you changed the tags? Some Tag editors dont update the timestamp.

If not, you can just "touch" the files (linux command "touch <file>")

**Comment by pacija** [comment]
Hi,

In this case I was not updating my timestamps on purpose - I like to preserve date of original addition of a release to my library (see #717). Most of other problems with updating tags were solved by full library re-scan, for example when I had multi-word genre tags shown as separate tags (see #1420), without the need to update timestamps.

Perhaps some tag properties are updated but others aren't?

**Comment by metalheim** [comment]
Okay maybe you're right and it is buggy behavior :)
