### ISSUE TITLE
Artists on Compilations Displayed Separate in Album View

### ISSUE THREAD

**Issue by zajnemzaj** [navidrome/navidrome#1624]
In album view, compilations displayed as by separate artists unless Album Artist tag is filled to the same on all songs from the same album.

For those who doesn't have Album Artist tag filled, it's hard to start playing a compilation album.

Maybe it could be better to arrange things in album view by Album tags.

Thanks for reading.

[https://pasteboard.co/vwsGp4ZEjKL2.png](https://pasteboard.co/vwsGp4ZEjKL2.png)

**Comment by zajnemzaj** [comment]
Forcing users to re-tag more ten thousands of mp3s is not the best idea I guess.

Still see no reason why mp3-s tagged with same album name shouldn't be displayed in one place (they have the same album name... they belong together) or at least there should be an option in album view to switch between display modes (just below grid - list modes)

**Comment by zajnemzaj** [comment]
> That is not a bug and working how it is supposed to be. To avoid those albums splitting up, you can either:
> 
> * Set an album artist
> * Set the "compilation" tag for all songs in that album
> 
> Please see the documentation: https://www.navidrome.org/docs/faq/#i-have-an-album-with-tracks-by-different-artists-why-is-it-broken-up-into-lots-of-separate-albums-each-with-their-own-artist

Forcing users to re-tag more ten thousands of mp3s is not the best idea I guess.

Still see no reason why mp3-s tagged with same album name shouldn't be displayed in one place (they have the same album name... they belong together) or at least there should be an option in album view to switch between display modes (just below grid - list modes)

**Comment by metalheim** [comment]
The reason is simple: there are lots of albums with the same name (by completely different artists) that shouldn't be grouped together.
So it's a loss either way you implement it: "grouping too much" VS. "grouping too less".
Navidrome has decided to go with the latter with the benefit that you can at least control it if you tag your files thoroughly.

Maybe beets or Musicbrainz can help you batch-tag your library :)

**Comment by deluan** [comment]
As @metalheim said:

> <img alt="Screen Shot 2021-01-31 at 10 53 36 PM" width="1526" src="https://user-images.githubusercontent.com/331353/106413095-3ddf4580-6417-11eb-9dc8-16e40f0d94aa.png"> or <img alt="Screen Shot 2021-01-31 at 11 00 20 PM" width="1512" src="https://user-images.githubusercontent.com/331353/106413479-25bbf600-6418-11eb-84c4-c12bd01c66f2.png"> or <img alt="Screen Shot 2021-01-31 at 11 02 56 PM" width="516" src="https://user-images.githubusercontent.com/331353/106413600-7cc1cb00-6418-11eb-80d9-8a6067195ac9.png">
> 
> Implementing what you are suggesting would require implementing 'workarounds" to handle situations like these above. This implementation would be messy at best, and I don't think it makes sense to implement it when we have a perfect solution, a standard and widely accepted way to handle this: the "Part of Compilation" tag.
> 
> May I ask why it is not an option for you to edit your tags?

This is from another discussion we had on the topic, https://github.com/navidrome/navidrome/issues/622

**Comment by zajnemzaj** [comment]
I can see the advantages here but still it's an extra and big trouble for newcomers who doesn't have this tag managed so far ( beets or Musicbrainz cannot really help because having so much rare stuff, that's the reason not using spotify either...).

In my opinion the best would be to be able to switch between the two viewing/grouping modes where you can choose from grid/list view.

Just a question.
If I use the "Part of Compilation" tag. How it is known that which album is it belongs to? By folder? Than it could be grouped simply by folder if album name is the same otherwise album tags.

**Comment by certuna** [comment]
By Album Name - Navidrome only looks at tags. If ND would do it by foldername, it would be impossible to store an album across multiple folders.
