### ISSUE TITLE
Make artist in song list view clickable

### ISSUE THREAD

**Issue by krateng** [navidrome/navidrome#1627]
### Is your feature request related to a problem? Please describe.

When viewing an album that has songs not by the album artist, the song list shows the individual tracks' artists in the respective column, but I cannot click on them to get to their artist page.

### Describe the solution you'd like

In the album view, make the artist column linked to the artist just like in any other song list view.

Thank you!

**Comment by awsms** [comment]
I'd add that the current behaviour is extremely unintuitive since artists names are highlighted, but clicking on them plays the tied track instead

**Comment by awsms** [comment]
Bump as this is not a small issue

**Comment by deluan** [comment]
> Bump as this is not a small issue for a tags-oriented player

Sorry, but lots of issues with Navidrome are not small issues for a tags-oriented player. I do what I can to keep making it better, as time and life permits.

Anyway, what do you mean by this:
> current behaviour is extremely unintuitive since artists names are highlighted

Artists are NOT highlighted if they are not links. In SongList view, only artists that are also AlbumArtists are links:

<img width="930" alt="Screenshot 2023-03-09 at 5 57 57 PM" src="https://user-images.githubusercontent.com/331353/224179227-584ac307-b736-40a9-b731-3d56e8eb6f9a.png">

In this example, "Them" is not a AlbumArtist, all others are and if you click you are redirected to their respective page.

On Album Songs view, this is different. Currently no artists are highlighted/have links there:
<img width="1030" alt="Screenshot 2023-03-09 at 6 09 47 PM" src="https://user-images.githubusercontent.com/331353/224181270-7482eb1f-4129-4552-a803-be9fa4eccef0.png">

I'm changing that and add the same behaviour as in the SongList view:
<img width="1071" alt="Screenshot 2023-03-09 at 6 08 12 PM" src="https://user-images.githubusercontent.com/331353/224181013-a0dabf41-e7f8-479c-95c0-6f3843436811.png">

"Barão Vermelho" now is highlighted and linked to their Artist page.
