### ISSUE TITLE
Caching/"downloading for offline playback" in PWA

### ISSUE THREAD

**Issue by Knyffen** [navidrome/navidrome#1629]
Hello :)

As my music collection grew, I installed Navidrome in order to avoid having a local copy on each device. And it performs way beyond my expectations!

There is however an issue in that I have yet to find a truly good android app. And by that, I mean an app that supports reasonable browsing features, offline downloads, and where the GUI doesn't get stuck every 5 seconds (requiring me to restart the app, stopping the music)...

The exception, however, is the Navidrome PWA that somehow works way better than any of the native apps. But the PWA doesn't support downloading songs for offline use, which is quite rough on my data plan, when I am pendling to work every day. I know that I can download albums as zip-folders, and play them locally that way, but that requires quite a lot of work, whenever I switch what albums or artists I listen to locally.

So what solution would I suggest? I find it quite unreasonable to request true offline support, since that would require very large additions to the code, so instead I will suggest a solution that gets 90% of the way with only 10% of the effort: How about we add a "cache" button next to the existing "download" button, that downloads a song/album and adds it to the browsers local storage (IndexDB specifically, not LocalStorage). From that point on, whenever we are about to stream a song, we start by checking if it is located in the database, and just stream it from there.

Theoretically, it should be relatively simple to implement, but I don't have any experience with Go or React, so I got completely lost when I tried to figure out where in the code the songs were streamed, so I don't know if it is actually easy to implement.

Finally, I have to admit that there a quite a few problems with storing the songs locally at all, why it will probably need to be an optional features with a warning/disclaimer before enabling it... and even then you might get additional Github issues from people that didn't read it... but here are the problems I've found:
- Each website has a limit on the size of the local storage, that varies drastically from browser to browser. I've created and attached a simple webpage ([test_local_storage.zip](https://github.com/navidrome/navidrome/files/8140776/test_local_storage.zip)) that downloads a song (5.36MB) stores it and tells you how many songs you can store before you reach the limit. From my research it seems that Firefox (on my desktop) has a 10GB limit (Mozilla's documentation said 2GB, though), and Chrome (on desktop and mobile) seems to have a limit 60% of the system storage. Unless you download all your music, it should be enough for most people. I've heard rumors that Safari has a very strict limit, but I am not sure.
- The browser reserves the right to delete locally stored data if the device is running out of space. This means that the cached music could potentially be wiped randomly, without us being able to do anything. This is why it is especially important to have a disclaimer before enabling the feature.
- It isn't fully offline, so the page will (might?) not work at all if you truly don't have any internet connection. But It will reduce the data consumption to a minimum, so it can save your data plan.

So, yeah, it has a lot of problems - especially deleting your cached songs - why I only find it a reasonable request if it is very quick to implement. As an alternative, Chrome has supported access to folders in the local file system for some time, but only on desktop, and only chrome... so I don't find that to be all that useful.

I feel like I forgot to mention something, so I might add some details later, but this is the overall gist of it.

And I understand if you respond with "nope, not happening" since there doesn't seem to exist a truly good solution to the problems, why you might prefer working on some actually solvable problems. :-)

Thank you for working on Navidrome!

**Comment by Knyffen** [comment]
Sorry for the slow response.

Regarding the library changing on the server, how about we let each client hold a list of all song UUIDs and then it is up to the client to delete any song not in the list?
Initially, we need to perform a full sync (16 bytes * library size). Since the server recognizes each client as an individual player object, we could potentially have the server update a diff for each player whenever it performs a scan, and reset it when the player synchronizes. But honestly, it is probably not worth it to create a diff since even the UUIDs of a 10,000 song library would only be 0.16 MB, and instead just a "library changed" flag combined with full syncs should suffice.

What do you mean by partially downloaded songs? If you are thinking of when you loose connection mid-download, then I don't know anything about downloads so I would have to research how it works.

While I can't comment on how to implement the simplified offline mode, I would like to suggest possibly adding a separate navigation tab for the offline mode containing all downloaded content grouped by how it was downloaded. So if you downloaded a playlist, it would show up as usual, but if you downloaded an album it would also show up - possible as a pseudo-playlist (since playlists doesn't have album covers etc., and playlists would be the lowest common denominator).
Of course it would be more intuitive to have the album tab just only show downloaded albums, but the amount of code to rewrite would probably increase a lot.

**Comment by Knyffen** [comment]
After looking at some other issues, I realized that we also need to consider external files (artwork, lyrics, etc.) (or make a decision not to support it).

**Comment by certuna** [comment]
Yeah this is why I'm never a big fan of all these sidecar files, everything embedded makes things a lot easier.
