### ISSUE TITLE
Song added to the library with band's name's first letter dropped

### ISSUE THREAD

**Issue by sergio-ns** [navidrome/navidrome#1631]
### Description

Added song "Multilateral Nuclear Disarmament" by Beastie Boys to the library.
The track gets scanned and added to the database but the band's name is recorded as "eastie Boys" despite the file tag is correct

### Expected Behaviour
The band's name should be detected as "Beastie Boys"

### Steps to reproduce

1. Drop the file into one the folders scanned by Navidrome
2. Click on '...'
3. Scroll down to '...'

### Platform information

 - Navidrome version: v0.47.5
 - Browser and version: Firefox v97.0.1
 - Operating System: Windows 11

### Additional information

See attached images
[Navidrome1](https://i.imgur.com/nrXdwcC.png)
[Navidrome2](https://i.imgur.com/VfzRSoQ.png)
[File tags](https://i.imgur.com/7mUYu9l.png)

**Comment by metalheim** [comment]
Can you post the full tags?
For example by running "ffprobe <filename>" 
Or by using mp3tags "show all tags" 

My suspicion is that there's some tag in the file that windows explorer doesn't display, but confuses navidrome

**Comment by sergio-ns** [comment]
> Can you post the full tags? For example by running "ffprobe " Or by using mp3tags "show all tags"
> 
> My suspicion is that there's some tag in the file that windows explorer doesn't display, but confuses navidrome

Indeed, the issue is with an "ALBUM ARTIST" tag that has the truncated band's name:

```
 Metadata:
    title           : Multilateral Nuclear Disarmament
    artist          : Beastie Boys
    track           : 13/18
    album           : Hot Sauce Committee Part Two
    disc            : 1/1
    date            : 2011-04-27
    genre           : Hip-Hop
    TDOR            : 2011
    album_artist    : Beastie Boys
    TSO2            : Beastie Boys
    artist-sort     : Beastie Boys
    TSRC            : USCA21100556
    SCRIPT          : Latn
    TMED            : Digital Media
    TRACKTOTAL      : 7
    publisher       : Capitol Records
    originalyear    : 2011
    ARTISTS         : Beastie Boys
    ALBUM ARTIST    : eastie Boys <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    MusicBrainz Album Type: album
    MusicBrainz Album Status: official
    MusicBrainz Album Release Country: US
    Acoustid Id     : c4d86e22-8e17-4880-a13d-a92ec0ed8c28
    MusicBrainz Album Id: 989c58b6-6a89-4cdc-9909-413c00e416bb
    MusicBrainz Artist Id: 9beb62b2-88db-4cea-801e-162cd344ee53
    MusicBrainz Album Artist Id: 9beb62b2-88db-4cea-801e-162cd344ee53
    MusicBrainz Release Group Id: 1f660e76-b300-4084-aeb5-04b5a8dee845
    MusicBrainz Release Track Id: adb12bd9-9beb-38ee-a555-4b3a21c21607
    comment         : Hot Sauce Committee Part Two is the eighth studio album by the Beastie Boys, released in 2011. The album was originally planned for release on September 15, 2009 under the title Hot Sauce Committee, Pt. 1, as the first installment of a two part set. The a
  Duration: 00:02:54.21, start: 0.025056, bitrate: 323 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 320 kb/s
    Metadata:
      encoder         : LAME3.98r
    Stream #0:1: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 300x300 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      title           : Front cover
      comment         : Cover (front)
```
