### ISSUE TITLE
Always logging me out

### ISSUE THREAD

**Issue by rightsaidfred99** [navidrome/navidrome#1632]
Hi, 

I used Nativefy (an app for Mac) that basically uses an electron wrapper for the web based site so that I can create my own app. 

Short story is it works perfectly. 

However Navidrome constantly logs me out every couple of days and it becomes tiresome when wanting to play music having to enter in credentials all the time. 

I would propose a little checkbox to keep people signed in indefinitely for the web portal to fix this issue. Thanks

**Comment by rightsaidfred99** [comment]
The docker container will crash if set to

ND_SESSIONTIMEOUT = 999 

:(

**Comment by metalheim** [comment]
It's expecting a time value, not a unitless integer. 
Please try "999h" or similar.

**Comment by rightsaidfred99** [comment]
Yes, this will crash docker too "999h".

I can send in a log if it helps.

**Comment by SteveDinn** [comment]
I have my config set up in a separate YAML file and "999h" is working. Are you trying to configure it right in docker?

**Comment by rightsaidfred99** [comment]
Yes, for mine if set as an environment variable (using the appropriate setting) it will simply crash :(

**Comment by rightsaidfred99** [comment]
Can close this now. Idk why, but I can get this to work now in Docker (the environment variable). 
Still think it might be useful for non tech users to have a "keep me signed in" checkbox perhaps.
