### ISSUE TITLE
Navidrome fails to start if `.sql` files are located in $PWD

### ISSUE THREAD

**Issue by brianredbeard** [navidrome/navidrome#1637]
### Description

Navidrome fails to start if files ending in `sql` exist in the present working directory throwing the following error:

```bash
[/tmp/tmp.Hv4hTm2RYG]$ ~/Downloads/navidrome -l error
 _   _             _     _
| \ | |           (_)   | |
|  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___
| . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
| |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
\_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
                          Version: 0.47.5 (86fe1e3b)

ERRO[0000] Failed to apply new migrations                error="no separator found"
```

### Expected Behavior

Proper execution & startup of the navidrome binary.

### Steps to reproduce

1. Make a temporary directory

```bash
cd $(mktemp -d)
```

2. Create a file ending in `.sql` (Note: it does not seem to matter if the contents contain syntactically correct SQL.  Using a single empty comment for this example):

```bash
echo "---" > stuff.sql
```

3. Attempt to execute binary

```bash
~/Downloads/navidrome -l error
```

### Platform information

 - Navidrome version: 0.47.5 (86fe1e3b)
 - Browser and version: N/A
 - Operating System: Linux, glibc 2.32, kernel 5.14.18

### Additional information

Additionally I'm not sure if this is an issue with `goose` or another component, but there seems to be a code path which is enumerating all files in `${PWD}`.  This was discovered by noticing approx. 600 `SIGURG`  responses to the `rt_sigreturn()` syscall.

Discussed on [Discord](https://discord.com/channels/671335427726114836/671335427726114839/948355502197334077)

Likely related to https://github.com/pressly/goose/issues/78

**Comment by brianredbeard** [comment]
One suggestion, potentially include the problematic filename being parsed in the error.  This would make the error a bit easier to understand for future users.

**Comment by deluan** [comment]
Still reproducible. Low priority though. Thanks for reporting, hopefully I'll find time to revamp the migrations implementation and use newest goose.

**Comment by brianredbeard** [comment]
Not stale.

**Comment by deluan** [comment]
Goose was updated in https://github.com/navidrome/navidrome/commit/87ecd118bb9796e98510080e36f92640485ef35d and I was not able to reproduce this issue anymore. Please confirm.

**Comment by brianredbeard** [comment]
Works for me.
