### ISSUE TITLE
Can't delete transcodings

### ISSUE THREAD

**Issue by ras07** [navidrome/navidrome#1639]
### Description

I entered some test transcodings, and now I can't delete them. When I try the entry goes away temporarily, but in a second or two I get a red box that says either "Server communication error" (Brave, Chrome, and Edge) or "Forbidden" (Firefox), and the entry comes back. Same thing happens if I click on the entry and hit Delete. I am able to make edits to the transcode entries and they persist; I just can't delete them.

### Expected Behaviour

Deleted transcode entries go away never to be seen again, rather than rising from the dead.

### Steps to reproduce
1. Start Navidrome with the **ND_ENABLETRANSCODINGCONFIG=true** environment variable
2. Click on the user icon, then Transcodings
3. Click Create; create a new transcoding with any settings; save it
4. Select the checkbox next to the entry and click Delete
4a. Alternately, click on the transcode entry to edit it, then click delete
5. The entry goes away and a box comes up that says "Entry deleted (undo)", but then the entry comes back and an error message saying either "Server communication error" or "Forbidden", depending on the browser
5. See error

### Platform information

 - Navidrome version: [0.47.5] (Docker)
 - Browser and version: Brave 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit); Firefox 97.0.1 (64-bit); Chrome Version 98.0.4758.102 (Official Build) (64-bit); Edge Version 98.0.1108.62 (Official build) (64-bit)
 - Operating System: 

### Additional information
![image](https://user-images.githubusercontent.com/17038818/156320894-8cee7d89-7dd0-4b11-8b50-477b7c294c53.png)

Now it's gone ...
![image](https://user-images.githubusercontent.com/17038818/156321044-2ba6c43c-9217-41bc-b791-d1af56636e17.png)

... and whoops, now it's back
![image](https://user-images.githubusercontent.com/17038818/156322825-ed001f2a-50a5-4cf3-853f-e203fbc9881f.png)

**Comment by kushalShukla-web** [comment]
Can I work on it

**Comment by mradermaxlol** [comment]
This is strange, messing with transcodings works fine on my end (though I build Navidrome from source via AUR). Could it be a fs-level (or even docker-level) permission error? Anything useful in your logs?

**Comment by ras07** [comment]
I don't see anything that looks very helpful in the logs. I don't think it's a file permission problem; I changed everything in the data dir to 777 and it didn't help. I am creating a navidrome user in the Dockerfile and running as that user, but even when I run the docker image as root I have the problem. Could it be something going on with the database table permissions?

**Comment by ras07** [comment]
Hmm ... I was using the USER command in the Dockerfile to switch users, but when I run the deluan/navidrome:latest container as is and set the user from the command line, it works. So either there's some difference between setting the user in the Dockerfile and setting it with the **docker run** command, or else I'm doing something else in the Dockerfile that's interfering with this. 

I will do some more testing to try to isolate exactly what's causing the problem, but it's going to be a week+ before I can get to it. I'll report back.

**Comment by ras07** [comment]
Well, this had nothing to do with Navidrome or Docker; it ended up being a misconfigured reverse proxy. My nginx config had
`limit_except GET HEAD POST PUT { deny all; }`
and deleting transcodes (or anything else) needs, surprise, the DELETE method. Dumb mistake on my part.
