### ISSUE TITLE
Using play next causes the play queue to reset

### ISSUE THREAD

**Issue by Vista2003** [navidrome/navidrome#1649]
### Description

When selecting play next on a song, it causes the music queue to reset and jump back to start

### Expected Behaviour

For the selected track to play after the current song

### Steps to reproduce

1. Play an album
2. Go to another album and click on play next
3. The song playing should jump back to the start of the queue

### Platform information

 - Navidrome version: [0.47.5](https://github.com/navidrome/navidrome/releases/tag/v0.47.5) (86fe1e3b)
 - Browser and version: Brave 1.36.112 on Windows 10 and Brave 1.35.103 on Android 12
 - Operating System: unRAID 6.9.2 (Docker)

**Comment by tomerrr** [comment]
i experience the exact same issue. 
navidrome 0.47.5 (86fe1e3b) 
browser Firefox on Windows 10 / Linux
OS Debian 10

**Comment by juliadin** [comment]
Plus 1, experiencing the same on 
navidrome 0.47.5 (86fe1e3b) (Debian 11)
Browser: Chrome (102.0.5005.61) on OS X (12.4)

It seems to only happen though when the song currently playing is not the first one in the queue. I wasn't able to reproduce it while playing the first one in the queue ... but skipping to the next and then adding a song from any screen I tried using 'Play next' started playing the first song in the queue again. 

--


[0.47.5](https://github.com/navidrome/navidrome/releases/tag/v0.47.5) (86fe1e3b)

**Comment by tomerrr** [comment]
issue still exists on 0.48.0 (af5c2b5a)

**Comment by deluan** [comment]
This is a duplicate of #1472. Please follow that issue.
