### ISSUE TITLE
Possibility to display full path of a song

### ISSUE THREAD

**Issue by eskiiom** [navidrome/navidrome#1653]
Hello,

I would like to have the full path of where a file is stored, because I would like to identify some files where either the quality is bad, or tags are not explicit enough (I listened a very good one from no_artist, called track 01 on album no_album :))
I couldn't find this information on the webpage or PR list.
Sorry of that's already been asked/adressed, but my search didn't give me the answer

Thank you for providing such a great tool !

(actually using the latest docker version)

**Comment by mradermaxlol** [comment]
Press the "Get Info" button next to a disc or a specific track.
![image](https://user-images.githubusercontent.com/11138966/158236783-96f12546-7e56-431c-8c4d-98bd739a71d4.png)

**Comment by metalheim** [comment]
> Hello and thank you for the quick reply I don't have the same display. what did i miss ? is it because I'm using the docker version ? ![image](https://user-images.githubusercontent.com/26815164/158247379-cbd0dd8b-d28a-48f5-a572-d791050c078b.png)

There's a toggle in the "players" submenu for each player. I think it's called "Report real path"

**Comment by mradermaxlol** [comment]
> > Hello and thank you for the quick reply I don't have the same display. what did i miss ? is it because I'm using the docker version ? ![image](https://user-images.githubusercontent.com/26815164/158247379-cbd0dd8b-d28a-48f5-a572-d791050c078b.png)
> 
> There's a toggle in the "players" submenu for each player. I think it's called "Report real path"

I don't think it's related. You should be able to get the correct file information without messing with the toggle (just checked it again). Can't say for sure what's up with the Docker version, though.

@eskiiom is that the song info? Looks a bit smaller than it should, that's for sure.

**Comment by eskiiom** [comment]
Hi All,
mea culpa, this was indeed the album info, not the song info. I didn't notice I was on the albums page.
So, for songs it works as expected I have the full path displayed. So I believe for the album display you are working at the metadata level, and not at the folder level, which is why there is no "album path" so to speak. is that correct ?

Thanks again and sorry for the bother ...

**Comment by mradermaxlol** [comment]
I believe there are no techincal limitations for extending the album-level (and even artist-level) info to better match individual song information (e.g. file path). @deluan?

**Comment by metalheim** [comment]
Rolling up paths to album or artist level isn't easy, since songs could be scattered around multiple folders.

IMHO, having the info on songpath is fine, everything beyond gets complicated, incorrect or both.

**Comment by mradermaxlol** [comment]
I'm not the one who calls the shots out here :)
You're probably looking for @deluan

**Comment by deluan** [comment]
Sorry for being late to the discussion, but yes, paths are only available for songs, mainly because of the complications explained by @metalheim .

Will close this now.
