### ISSUE TITLE
Additional filter fields in ``songs`` screen

### ISSUE THREAD

**Issue by rm-dr** [navidrome/navidrome#1655]
### Describe the solution you'd like

It would be nice to have more filters than "genre" and "favorites" in the ``songs`` screen. Why not allow filtering by Artist, Genre, etc, just as in the ``all`` screen?

**Comment by deluan** [comment]
There was a technical reason limiting this, but I'll take another look and let you know. Thanks for the feedback

**Comment by eskiiom** [comment]
Hello
that would also be great if we could filter out on the quality
For example "I'd like to listen to my highest quality songs", or "i'd like to remove or re-rip all the lowest quality songs"
Can be for example based on the audio codec, a first filter would be to be able to show only wma/aac/mp3/flac/ogg
Then a second one would be related to bitrate
