### ISSUE TITLE
"Add to playlist" popup is not shown in artist page.

### ISSUE THREAD

**Issue by rm-dr** [navidrome/navidrome#1656]
### Description

No popup is shown when trying to add an album to a playlist from the artist screen.

### Expected Behaviour

The "select a playlist" popup is shown.

### Steps to reproduce

1. Select any artist
2. Click on the ... on any album, and click "add to playlist"
3. Nothing happens.
4. Now, click on any album.
5. Once the album page loads, the "select a playlist" popup is shown.

### Platform information

 - Navidrome version: v0.47.5
 - Browser and version: v98.0b9
 - Operating System: Arch, Navidrome running in docker

**Comment by Dnouv** [comment]
Hey @rm-dr 
Thank you for noticing the bug and reporting it. I have raised a PR with the fix, the bug would be fixed once it's merged.
