### ISSUE TITLE
ListenBrainz Scrobble Agent uses incorrect MBID parameter

### ISSUE THREAD

**Issue by tlaporte** [navidrome/navidrome#1657]
**Disclaimer:** I am new to music library management and MusicBrainz/ListenBrainz, so it is possible that I have naively missed something in my assessment in this issue. I have just documented what I think is going on after observing some weird behaviour in the ListenBrainz UI when Navidrome "playing now" events are present, and digging into the code and related documentation to see what could be causing it.

### Description

When Listenbrainz scrobbling is enabled, it scrobbles using the [MusicBrainz Recording ID](https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html#id21), but it passes it as the `track_mbid` ([related code for ListenBrainz agent](https://github.com/navidrome/navidrome/blob/2ddd3acba6cde5fae11e6684a8aa01a070fda23d/core/agents/listenbrainz/client.go#L78), [related code for tag mapping](https://github.com/navidrome/navidrome/blob/2ddd3acba6cde5fae11e6684a8aa01a070fda23d/scanner/metadata/metadata.go#L95)). Based on the [ListenBrainz API documentation](https://listenbrainz.readthedocs.io/en/latest/users/json/#json-doc), the parameter that should be used when passing the [MusicBrainz Recording ID](https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html#id21) is `recording_mbid`.

The result is that when Navidrome submits a call to the ListenBrainz submit-listens endpoint, it produces a listen that has a bad link, and when you view that listen in the ListenBrainz UI (https://listenbrainz.org/user/<YOUR_USER>/), ~~you get an error toast in the bottom right corner of the screen~~ (ListenBrainz UI stopped showing the error toast since this ticket was created). Additionally, the hyperlink on the track title in the listen history for the track is not there.

### Expected Behaviour

When Navidrome uses the ListenBrainz `submit-listens` endpoint, it should pass `recording_mbid` instead of `track_mbid`, because the metadata that populates the Navidrome model's MediaFile.MbzTrackID is associated with the [MusicBrainz Recording ID](https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html#id21) ([related code](https://github.com/navidrome/navidrome/blob/2ddd3acba6cde5fae11e6684a8aa01a070fda23d/scanner/metadata/metadata.go#L95)). This mismatch is likely due to the fact that the tag for the [MusicBrainz Recording ID](https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html#id21) is `MUSICBRAINZ_TRACKID`, which is a bit confusing.

### Steps to reproduce

1. Enable scrobbling to ListenBrainz in Navidrome
2. Play any track in Navidrome that has MediaBrainz MBID metadata populated (you can also emulate these first two steps using the first request I included in the bottom of this issue)
3. Go to the ListenBrainz home page for your user (https://listenbrainz.org/user/<YOUR_USER>/)
4. Observe the "Could not fetch Recording MBID" error in the bottom right, and note that the "playing now" track's title is not a hyperlink.

### Platform information

 - Navidrome version: 0.47.5
 - Browser and version: Brave V1.36.112
 - Operating System: Windows 10

### Additional information

Any other information that may be relevant or give context to the problem.

- Screenshots (if applicable): Missing hyperlink on track title: 
  <img width="311" alt="image" src="https://user-images.githubusercontent.com/2347599/159179279-1a166bc6-5ec3-46ff-ad92-673a52da1986.png">
- Client used: Navidrome UI, DSub, any client that triggers scrobbles

Below is an HTTP Request (with ListenBrainz token stubbed) that emulates how Navidrome is calling the ListenBrainz API, based on inspection of the related code. `track_mbid` is populated with the MBID in the MUSICBRAINZ_TRACKID tag, which according to the MusicBrainz documentation, is actually the  [MusicBrainz Recording ID](https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html#id21). **This request produces the same behaviour as playing a track through the Navidrome UI.**
```
POST https://api.listenbrainz.org/1/submit-listens
Authorization: Token <LISTENBRAINZ_TOKEN>

{
  "listen_type": "playing_now",
  "payload": [
        {
        "track_metadata": {
            "additional_info": {
            "release_mbid": "acb6fd35-074f-4ab9-bc83-66f8a3eb6f0f",
            "artist_mbids": [
                "7004bc31-23ee-4216-8d74-0d230e88079f"
            ],
            "track_mbid": "99b455ec-7f1e-49b2-bcbc-b8ee3302dbb1",
            },
            "artist_name": "Yōko Takahashi",
            "track_name": "The Cruel Angel's Thesis",
            "release_name": "Evangelion Finally"
        }
        }
  ]
}
```

Here is the same request, but `recording_mbid` is used instead of `track_mbid`, with the same value that is associated with tag MUSICBRAINZ_TRACKID. **This request does not produce an error in the ListenBrainz UI and does produce a hyperlink on the track title for the listen.**
```
POST https://api.listenbrainz.org/1/submit-listens
Authorization: Token <LISTENBRAINZ_TOKEN>

{
  "listen_type": "playing_now",
  "payload": [
        {
        "track_metadata": {
            "additional_info": {
            "release_mbid": "acb6fd35-074f-4ab9-bc83-66f8a3eb6f0f",
            "artist_mbids": [
                "7004bc31-23ee-4216-8d74-0d230e88079f"
            ],
            "recording_mbid": "99b455ec-7f1e-49b2-bcbc-b8ee3302dbb1",
            },
            "artist_name": "Yōko Takahashi",
            "track_name": "The Cruel Angel's Thesis",
            "release_name": "Evangelion Finally"
        }
        }
  ]
}
```

**Comment by deluan** [comment]
Hey, thanks for the report. I'm not sure this is an issue with Navidrome as it seems to work well:
<img width="736" alt="Screen Shot 2022-03-19 at 1 04 08 PM" src="https://user-images.githubusercontent.com/331353/159130988-19dd548a-6601-492a-9139-d6609be85b17.png">

All hyperlinks to tracks work for me.  I use `beets`, not sure if the tagger you use may be messing things up.... Anyway, I'd like to hear from @srichter, as he contributed the ListenBrainz agent.

**Comment by tlaporte** [comment]
Right, I am using MusicBrainz Picard to tag my music. I think it is tagging the media "correctly" based on MusicBrainz's documentation, though I do find the metadata naming they use, and the corresponding tag names, are a bit confusing. I could be wrong on that, or be doing something wrong though. I will try out beets on my library and do some comparisons and report back.

**Comment by tlaporte** [comment]
Oh, small, additional comment, for what its worth, https://github.com/navidrome/navidrome/issues/1036 indicates that "MusicBrainz Release Track ID", which I believe in the MusicBrainz documentation corresponds to the ["MusicBrainz Track ID" (tagged as MUSICBRAINZ_RELEASETRACKID)](https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html#id24), is not currently mapped by Navidrome, but it does indicate that "MediaBrainz Recording ID", which corresponds to ["MusicBrainz Recording ID" (tagged as MUSICBRAINZ_TRACKID)](https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html#id21), is mapped.

This matches my observation, and I believe it is the former, "MusicBrainz Track ID", that the ListenBrainz API is expecting in the track_mbid field. 

Makes me wonder how beets is populating these fields, so I will check that out.

**Comment by tlaporte** [comment]
I imported "No Time To Die" from iTunes, using both MusicBrainz Picard and beets.

Both populated MUSICBRAINZ_RELEASETRACKID (tag for MusicBrainz Track ID) as [5606ca56-cdea-40c7-9c6d-22d49a38da26](https://musicbrainz.org/release/b50caad5-fe40-4c98-8947-f2a77ccc8a6c/disc/1#5606ca56-cdea-40c7-9c6d-22d49a38da26), and populated MUSICBRAINZ_TRACKID (tag for MusicBrainz Recording ID) [14848e6d-61fa-49f2-9e22-883e285a3a76](https://musicbrainz.org/recording/14848e6d-61fa-49f2-9e22-883e285a3a76?tport=8000).

I added the file from beets to Navidrome and their was no hyperlink for the title on the listen entry. Interestingly, the error toast on ListenBrainz stopped happening, and I tested for the other tracks I noticed this issue on, and the error toast was gone for those as well, so maybe a ListenBrainz update changed that.

**Comment by srichter** [comment]
I recall seeing some odd behavior with the links in ListenBrainz. If you think we're sending the wrong ID to the API I can change it. I'll try to find some time to play around with this

**Comment by vs49688** [comment]
> Oh, small, additional comment, for what its worth, #1036 indicates that "MusicBrainz Release Track ID", which I believe in the MusicBrainz documentation corresponds to the ["MusicBrainz Track ID" (tagged as MUSICBRAINZ_RELEASETRACKID)](https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html#id24), is not currently mapped by Navidrome, but it does indicate that "MediaBrainz Recording ID", which corresponds to ["MusicBrainz Recording ID" (tagged as MUSICBRAINZ_TRACKID)](https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html#id21), is mapped.
> 
> This matches my observation, and I believe it is the former, "MusicBrainz Track ID", that the ListenBrainz API is expecting in the track_mbid field.
> 
> Makes me wonder how beets is populating these tags, so I will check that out.

I add support for capturing the "track id", or "MUSICBRAINZ_RELEASETRACKID" in https://github.com/navidrome/navidrome/pull/1827.

**Comment by phw** [comment]
It might be a good idea to rename `MbzTrackID` in https://github.com/navidrome/navidrome/blob/master/model/mediafile.go#L47 to `MbzRecordingID`, if that's possible without causing too much breakage. Because as mentioned above the tag `musicbrainz_trackid`  in the files for historical reasons actually contains what is called recording ID.

In the ListenBrainz submission this is supposed to be set into the `recording_mbid` field.

**Comment by AlexKurisu** [comment]
Still an issue, Navidrome still doesn't submit recording_mbid to ListenBrainz

**Comment by AlexKurisu** [comment]
```{
  "track_metadata": {
    "artist_name": "Renard Queenston",
    "release_name": "Rainbow Dash Likes Girls",
    "additional_info": {
      "track_mbid": "ad1c4356-5ae5-459c-9087-bc80f820509d",
      "tracknumber": 4,
      "artist_mbids": [
        "04022043-8507-4471-80af-efa140162727"
      ],
      "release_mbid": "e9abdc37-ce2e-4383-b436-1950bab098f4",
      "recording_msid": "de2e0e36-520c-405e-803b-551a9e0f9eaa",
      "submission_client": "navidrome",
      "submission_client_version": "0.49.1 (0.49.1-r2)"
    },
    "track_name": "Sean Paul Opens a MFing Carnival"
  },
  "listened_at": <RUBOUT>,
  "recording_msid": "de2e0e36-520c-405e-803b-551a9e0f9eaa",
  "user_name": <RUBOUT>,
  "inserted_at": 1676252563
}```

Data gathered from ListenBrainz itself using it's "Inspect Listen" button

**Comment by phw** [comment]
```json
"additional_info": {
      "track_mbid": "ad1c4356-5ae5-459c-9087-bc80f820509d",
```

So `ad1c4356-5ae5-459c-9087-bc80f820509d`  is indeed a recording ID, see https://musicbrainz.org/recording/ad1c4356-5ae5-459c-9087-bc80f820509d . That means Navidrome reads the proper ID, but uses the wrong field name for LB submission. According to the LB API docs it must be `recording_mbid`, see https://listenbrainz.readthedocs.io/en/latest/users/json.html
