### ISSUE TITLE
All songs removed after scan completes

### ISSUE THREAD

**Issue by wowregistering** [navidrome/navidrome#1668]
### Description

All files are removed after scan completes but function normally during the scan.

### Expected Behaviour

The scan to finish and the files to continue being playable

### Steps to reproduce

1. scan
2. let scan finish

### Platform information

 - Navidrome version: 0.47.5
 - Browser and version: Microsoft Edge Version 99.0.1150.52 (Official build) (64-bit)
 - Operating System: windows 10

### Additional information

Microsoft Edge
Version 99.0.1150.52 (Official build) (64-bit)

time="2022-03-26T10:15:32-07:00" level=debug msg="Playlist auto-import is disabled"
time="2022-03-26T10:15:32-07:00" level=debug msg="Finished reading directories from filesystem" elapsed=5m9s
time="2022-03-26T10:15:34-07:00" level=debug msg="Deleted dangling tracks" totalDeleted=19828
time="2022-03-26T10:15:34-07:00" level=debug msg="Removing non-album artist_id"
time="2022-03-26T10:15:34-07:00" level=debug msg="Purged empty albums" totalDeleted=2473
time="2022-03-26T10:15:34-07:00" level=debug msg="Purged empty artists" totalDeleted=1250
time="2022-03-26T10:15:34-07:00" level=debug msg="Clean-up annotations" table=media_file totalDeleted=1
time="2022-03-26T10:15:34-07:00" level=debug msg="Clean-up annotations" table=album totalDeleted=1
time="2022-03-26T10:15:34-07:00" level=debug msg="Clean-up annotations" table=artist totalDeleted=1
time="2022-03-26T10:15:34-07:00" level=debug msg="Purged unused genres" totalDeleted=186
time="2022-03-26T10:15:34-07:00" level=info msg="Finished processing Music Folder" added=19828 deleted=0 elapsed=5m11s folder="Z:" playlistsImported=0 updated=0
time="2022-03-26T10:15:34-07:00" level=debug msg="Detected changes in the music folder. Sending refresh event" changeCount=19828 folder="Z:"

**Comment by deluan** [comment]
Did you changed the MusicFolder config between the scans?

**Comment by wowregistering** [comment]
No, the folder is set to the same directory every time.  

If I rescan after it removes all of the files it will find them again, they will work during the scan again, and then be removed again after the scan finishes.

**Comment by deluan** [comment]
Try setting the MusicFolder to "Z:\", just to make sure it is not causing any issues.

**Comment by wowregistering** [comment]
That does seem to have resolved the problem I was having. Thank you for the assistance and sorry for not realizing my mistake.

**Comment by deluan** [comment]
Glad it worked! It was a honest mistake. I may change it to handle this situation.
