### ISSUE TITLE
Playlist switching doesn't reset pagination state

### ISSUE THREAD

**Issue by TheBlueMatt** [navidrome/navidrome#1676]
On `0.47.5-SNAPSHOT (86fe1e3b)` (actually just 0.47.5 self-built), on the web interface,if I open a large playlist and click onto the next page, then click another smaller playlist, it shows up as simply "nothing here" - the request that flies to the server shows up as paginated with the start pos 100 (presumably or whatever the start pos was on the first playlist), so of course its getting back an empty result.

**Comment by deluan** [comment]
Thanks for the report. Will take a look.
