### ISSUE TITLE
Setting for default volume level

### ISSUE THREAD

**Issue by koehntopp** [navidrome/navidrome#1679]
### Is your feature request related to a problem? Please describe.

I understand the reasoning behind the issue that created the change to 50% as the default, but ultimately this is only going to please a group of users, just as the 100% initially did. 
On my Mac, *all* audio is always set to 100% (Youtube, Netflix, ...) , which allows me to control a desired volume with the master volume keys / menu.
With Navidrome at 50%, I keep increasing the master volume, only to have my speakers jump off the shelf the next time i start a Youtube video ;)

### Describe the solution you'd like

Please provide an environment variable for the default volume (0-100) that, if set, sets the default volume to that level.
That should be a rather small change, unfortunately my coding skills are limited to Python so I can't do it myself.

**Comment by dpraul** [comment]
This would be a wonderful change. As an alternative/supplement, it would be great to save the volume preference to the device and just reuse that on reload, rather than any global setting.

**Comment by deluan** [comment]
Yeah, I agree this is not optimal.... I'll introduce this flag in the next version.

> it would be great to save the volume preference to the device and just reuse that on reload, rather than any global setting.

@dpraul This is how it works today. It sets the volume to 50% _only_ if it is the first time in that browser. If you change the volume it saves it in the local storage, and read the value from there when you open Navidroem again in that browser.

**Comment by deluan** [comment]
> Is this recent? My instance resets to 50% volume each time I log in.

Ah, yes. If you log out, this is lost. I'll take a look at that as well. I don't have this issue because I set my `SessionTimeout` to 120h (5 days), so I rarely get logged out.
