### ISSUE TITLE
In artist page, when Last.fm is disabled, the MusicBrainz link points to nowhere

### ISSUE THREAD

**Issue by sjohannes** [navidrome/navidrome#1684]
### Description

In [ArtistExternalLink.js](https://github.com/navidrome/navidrome/blob/40b14e6d81505d4af799abff0a9184463929b101/ui/src/artist/ArtistExternalLink.js), the `links` array can contain 0, 1, or 2 elements depending on whether a Last.fm link and/or a MusicBrainz link is available.

However, when actually creating the link buttons, the code always uses `links[0]` for Last.fm and `links[1]` for MusicBrainz. This means that, when Last.fm is disabled, there is an empty MusicBrainz link (because `links[1]` is undefined).

### Expected Behaviour

Last.fm link, if available, links to Last.fm.  
MusicBrainz link, if available, links to MusicBrainz.

### Steps to reproduce

1. Disable Last.fm (`LastFM.Enabled = false`) but keep external services enabled (`EnableExternalServices = true`).
2. Browse to an artist page on Navidrome.
3. Underneath the artist name, there is a MusicBrainz icon that links nowhere.

### Platform information

 - Navidrome version: v0.49.3
 - Browser and version: tested with Chromium and Firefox

**Comment by Dnouv** [comment]
Hey @sjohannes 
Thank you for noticing this bug. My apologies for the long delay in fixing this, but please rest assured, that I have raised a PR with the fix.

**Comment by sjohannes** [comment]
After <https://github.com/navidrome/navidrome/pull/1935> the issue is still present, just with a slightly different symptom. I have updated the report accordingly.

The idea from @Dnouv's proposed fix <https://github.com/navidrome/navidrome/pull/1757> can still be used, but the patch itself conflicts with current master branch.
