### ISSUE TITLE
Volume level jumps to 100% when browser is resized to be narrow

### ISSUE THREAD

**Issue by sjohannes** [navidrome/navidrome#1685]
### Description

Due to 3e282df6391c9f271ca719bd505604b728b84e76 , when "mobile" mode is triggered by narrowing the browser window, the audio player volume is set to 100%.

### Expected Behaviour

Resizing the browser does not cause volume to change.

### Steps to reproduce

1. For your safety, make sure your OS/hardware volume level is not set too high.
2. Open Navidrome in a browser.
3. Resize the window such that it's not in mobile mode.
4. Play a song.
5. Set the volume to lower than 100%.
6. Resize the window by narrowing it until it triggers mobile mode (there is a full-screen player interface overlaying the track list).
7. The audio level jumps up to 100%, which you can confirm by widening the window again and checking the volume bar.

### Platform information

 - Navidrome version: v0.47.5
 - Browser and version: tested with Chromium and Firefox

**Comment by sjohannes** [comment]
The issue is still present in Navidrome 0.49.3.

**Comment by deluan** [comment]
Thanks for reporting. Unfortunately, with the current player, that does not allow changing volume in mobile view, there is no easy fix for this. This will be taken into consideration when working on the new player (see #1651).

I'll close this for now, but feel free to chime in if you have any other concerns.
