### ISSUE TITLE
Maloja scrobble support

### ISSUE THREAD

**Issue by rightsaidfred99** [navidrome/navidrome#1688]
Currently there is no way to support custom Last.fm alternative, like self hosted Malaga. 

https://github.com/krateng/maloja/

Would be awesome to have support so we can use open source software to audioscrobble

**Comment by kgarner7** [comment]
Now that the linked issue is resolved, you should be able to set `ListenBrainz.BaseURL` (toml) or `ND_LISTENBRAINZ_BASEURL` (environment) to point to your Maloja instance.
