### ISSUE TITLE
improve TopSongs findMatchingTrack by de-prioritizing compilations

### ISSUE THREAD

**Issue by metalheim** [navidrome/navidrome#1701]
### Is your feature request related to a problem? Please describe.

For me, GetTopSongs frequently returns Songs that are not from the original album (they were first released on), but rather i get results that are from a compilation.

Reason for that is that I often several have copies of songs.
One copy from the "correct" album and then duplicates in a few "Charts/Best Of" and "Label Sampler" Albums.

Navidrome already does quite a good job, sorting by year, starred and rating (so later re-releases get de-prioritized in matching)

### Example
F.e. i collect the "Bravo Hits" compilation series, a german "best-of sampler" that releases 3 compilations on CD every year with the most popular songs from that period.
For a lot of popular artists, the songs from this compilation will end up in the `getTopSongs` API response. (bceause they matched via `findMatchingTrack`).
This happens because both the songs from the original album and the song on the compulation are the same year/rating/unstarred.

### Describe the solution you'd like
I would like that the GetTopSongs method returns the "most correct" song. 
With "correct", i mean the instance from the Album that the artist released it on and not a compilation.

This could be achieved by de-prioritizing compilations when doing the matching. 
Adding `, compilation asc` to the squirrel "sort" statement in the findMatchingTrack method would do the trick:
https://github.com/navidrome/navidrome/blob/master/core/external_metadata.go#L417

It shouldn't harm the matching, having it as the "weakest" sorting factor. (Unless i didn't think of a weird edgecase)

### Describe alternative solutions that would also satisfy this problem

1. I could tag my entire library with the correct albumartist-mbzid, but im not sure that is honored in navidrome?
2. If navidrome would read full "releasedate" instead of just "year", it would also help, as the "correct" album is likely to be released (a month or two) before the compilation.

**Comment by metalheim** [comment]
Unstale!
Would improve matching quality and seems straightforward to implement.

**Comment by deluan** [comment]
Closed by #2532
