### ISSUE TITLE
Add Public Domain music in the development docker image

### ISSUE THREAD

**Issue by jfenske89** [navidrome/navidrome#1703]
### Is your feature request related to a problem? Please describe.

When working with the developer docker image, there is no music to test with.

### Describe the solution you'd like

It would be a nice to have for there to be some public domain music downloaded during the docker image build process, and for the development environment to point to this data.

### Describe alternative solutions that would also satisfy this problem

Sample public domain or free music data available in the development environment, for testing purposes.

**Comment by deluan** [comment]
I just added a target in the Makefile to download some music from the [demo instance](https://demo.navidrome.org):

```bash
$ make get-music
```

This command will create a subdirectory `./music` under the project's folder and populate it with a few albums. You just need to change your `MusicFolder` config option to `./music`
