### ISSUE TITLE
Playback of long audio tracks seem to stop randomly

### ISSUE THREAD

**Issue by Vista2003** [navidrome/navidrome#1706]
### Description
When playing a long audio track (i.e. an album mix) the playback of the track would randomly and I would be unable to resume it, instead I would need to opt to play a different track.

### Expected Behaviour

For the player to play the whole audio track from start to finish without issue.

### Steps to reproduce

1. Play a long audio track (> 1 hour)
2. Leave it playing until it stops

### Platform information

 - Navidrome version: [0.47.5](https://github.com/navidrome/navidrome/releases/tag/v0.47.5) (86fe1e3b)
 - Browser and version: Brave Version 1.37.116 Chromium: 100.0.4896.127 (Official Build) (Windows 10 64-bit) and Brave 1.37.116 on Android 12
 - Operating System: unRAID 6.9.2 and 6.10.0-rc4 with Navidrome on a Docker  
 - Using the default web client

**Comment by zeezhao** [comment]
I have also seen this on Windows 10 version 0.47.5 running directly without Docker, playing a track in a Firefox on Android 11. Track is only about 10min though. I can't tell what is causing it.
