### ISSUE TITLE
Navidrome unresponsive after listing a specific artist

### ISSUE THREAD

**Issue by morbificagent** [navidrome/navidrome#1709]
Hi together,

i am using navidrome for e few month now and everything works great.
But today i am trying to list a specific Artist and navidrome (webUI) gets unresponsive vor minutes... After ~2min the webui comes back to live. When i try to relist the artist the same happens.
Listing other artists is working. Im not sure if die Artistname could be a Problem because its "Die Drei ???" or eventually because there are >200 Albums from it?

Die Gui shows unfinished results when it gets unresponsive:

![image](https://user-images.githubusercontent.com/50199132/165527494-8e43d539-a497-41a6-80e2-8f097af9c83a.png)

And te debug-Log only shows a lot of api-requests but without any errormessage...

vel=debug msg="HTTP: GET http://ssh.bit-link.de:4533/rest/getCoverArt?u=Alex&t=[REDACT>
vel=debug msg="API: New request /rest/getCoverArt" client=NavidromeUI requestId=Bit-Li>
vel=debug msg="HTTP: GET http://ssh.bit-link.de:4533/rest/getCoverArt?u=Alex&t=[REDACT>
vel=debug msg="HTTP: GET http://ssh.bit-link.de:4533/rest/getCoverArt?u=Alex&t=[REDACT>
vel=debug msg="HTTP: GET http://ssh.bit-link.de:4533/rest/getCoverArt?u=Alex&t=[REDACT>
vel=debug msg="HTTP: GET http://ssh.bit-link.de:4533/rest/getCoverArt?u=Alex&t=[REDACT>
vel=debug msg="API: New request /rest/getCoverArt" client=NavidromeUI requestId=Bit-Li>
vel=debug msg="API: New request /rest/getCoverArt" client=NavidromeUI requestId=Bit-Li>
vel=debug msg="API: New request /rest/getCoverArt" client=NavidromeUI requestId=Bit-Li>
vel=debug msg="API: New request /rest/getCoverArt" client=NavidromeUI requestId=Bit-Li>
vel=debug msg="HTTP: GET http://ssh.bit-link.de:4533/rest/getCoverArt?u=Alex&t=[REDACT>
vel=debug msg="HTTP: GET http://ssh.bit-link.de:4533/rest/getCoverArt?u=Alex&t=[REDACT>
vel=debug msg="API: New request /rest/getCoverArt" client=NavidromeUI requestId=Bit-Li>
vel=debug msg="API: New request /rest/getCoverArt" client=NavidromeUI requestId=Bit-Li>
vel=debug msg="HTTP: GET http://ssh.bit-link.de:4533/rest/getCoverArt?u=Alex&t=[REDACT>
vel=debug msg="HTTP: GET http://ssh.bit-link.de:4533/rest/getCoverArt?u=Alex&t=[REDACT>
vel=debug msg="HTTP: GET http://ssh.bit-link.de:4533/rest/getCoverArt?u=Alex&t=[REDACT>
vel=debug msg="HTTP: GET http://ssh.bit-link.de:4533/rest/getCoverArt?u=Alex&t=[REDACT>
vel=debug msg="HTTP: GET http://ssh.bit-link.de:4533/rest/getCoverArt?u=Alex&t=[REDACT>
vel=debug msg="API: New request /rest/getCoverArt" client=NavidromeUI requestId=Bit-Li>
vel=debug msg="API: New request /rest/getCoverArt" client=NavidromeUI requestId=Bit-Li>
vel=debug msg="API: New request /rest/getCoverArt" client=NavidromeUI requestId=Bit-Li>
vel=debug msg="API: New request /rest/getCoverArt" client=NavidromeUI requestId=Bit-Li

**Comment by certuna** [comment]
Is this Firefox specific? I've noticed a lot of slowdowns on Firefix, while Safari/Edge/Chrome stay responsive.
