### ISSUE TITLE
Support for compilations albums

### ISSUE THREAD

**Issue by superfunk2000** [navidrome/navidrome#1711]
I have several titles that belong to a compilation. When I sort by album, each track appears separately in this compilation:
![image](https://user-images.githubusercontent.com/90634124/165700037-60376a54-44d4-4c44-8213-2c815f64e29b.png)

Can't these titles be summed up like a normal album?

My music files (32k) are all in one folder and have the naming convention "Artist - Title.mp3". In the metadata (ID3v1/v2), the Album field is filled accordingly.

**Comment by metalheim** [comment]
Compilation albums are supported. If you tag them with the "Compilation" Tag, they will get grouped together.

https://www.navidrome.org/docs/faq/#i-have-an-album-with-tracks-by-different-artists-why-is-it-broken-up-into-lots-of-separate-albums-each-with-their-own-artist

**Comment by superfunk2000** [comment]
Oh sorry - I should have read the FAQ's better.

Ouch - How do I set this tag now?
Now I have to make myself smart first... Or are there tips?
I have a tool (Mp3tag v2.49b) It's just loading the files, it always takes forever...

**Comment by metalheim** [comment]
mp3tag is a great tool, but as you said its not optimal if you have all files in one folder.

If you like to rely on automatically setting the information try "Musicbrainz Picard" (http://www.thedreaming.org/2020/11/22/musicbrainz-picard/) It gets the metadata/tags from the musicbrainz.org project.

Another option would be "beets" (the recommended option by navidromes author), but it definitely has an entry barrier and a  learning curve to it.

**Comment by dlehammer** [comment]
Hi @superfunk2000,

I too encountered this compilation issue initially, and the remedy I used was populating the "album artist" tag to get consistent compilation grouping with ex. [Various Artists](https://www.discogs.com/search/?q=various+artists&type=all).
The tagging of your library can most-likely be automated with the aid of ex. [beets](https://beets.io/) etc. as suggested above, and after re-scanning your library the new tags should be reflected as desired :)
