### ISSUE TITLE
Downloading Artist images from Spotify doesn't work on Windows server

### ISSUE THREAD

**Issue by rmccullagh99** [navidrome/navidrome#1712]
### Description
Downloading/caching of artist images from Spotify doesn't work on Navidrome windows.

I've used SPOTIFY_ID and SPOTIFY_SECRET as per [this documentation link](https://www.navidrome.org/docs/usage/external-integrations/#spotify).

### Platform information

 - Tested on Navidrome version [0.47.5](https://github.com/navidrome/navidrome/releases/tag/v0.47.5). I have also tested on a docker setup with the same version and don't experience this issue. I'm able to get the artist images fine.
 - Browser: Brave V1.38.109
 - Operating System: Windows 10 Home

### Screenshot

![image](https://user-images.githubusercontent.com/42370113/165735468-3aef76aa-924c-48e9-adbc-e374808f06b6.png)

**Comment by nkappe** [comment]
looks like last.fm isn't allowing artist-image-fetching through the api anymore, legal reasons..
[--> support thread from last.fm](https://support.last.fm/t/display-artwork-of-track-artist/53785/4)
