### ISSUE TITLE
Show filepath in the columns of Songs view

### ISSUE THREAD

**Issue by ribtoks** [navidrome/navidrome#1719]
### Is your feature request related to a problem? Please describe.

Yes, the problem is that I organize my music by folders and it's hard for me to use Navidrome in a way that is compatible with my music organization. What I will be able to achive if this feature request will be implemented is that I can create playlists based on folders via the UI if I will see file path.

### Describe the solution you'd like

"Columns to display" also includes a Filepath column.

### Describe alternative solutions that would also satisfy this problem

Having a folder view among others.

### Additional context

-

**Comment by zeezhao** [comment]
For large collections, I agree that having a folder view or alternative is essential. Thanks

**Comment by cxw620** [comment]
> For large collections, I agree that having a folder view or alternative is essential. Thanks

I do agree with you!

My songs are classified according to the source of the songs. For example, when I see a good BGM while watching a movie, I will download it and put it in the same folder, and name the folder the name of the movie. But these songs are often different albums and different singers.

**Comment by certuna** [comment]
For larger libraries I'd assume organisation by folder becomes less practical since you end up with big tree structures to navigate?

I think @deluan planned to support the Grouping tag, so you can slice and dice your library more easily, that would give more flexibility than oldfashioned folder-based navigation.

**Comment by ribtoks** [comment]
@certuna Yep, however this issue is about just showing a Filepath column. This will already help.

**Comment by ribtoks** [comment]
Not stale
