### ISSUE TITLE
Case-insensitive Playlists not importing on Windows 10

### ISSUE THREAD

**Issue by zeezhao** [navidrome/navidrome#1720]
### Description
A .m3u playlist file is not importing on Windows 10. Even though paths to music files are correct, navidrome server gives errors, for instance:

`time="2022-05-03T15:59:59+01:00" level=warning msg="Path in playlist not found" error="data not found" path="c:\\zmusic\\mp3\\artist1\\track1.mp3" playlist=test`

Event though the file exists at:

`c:\zmusic\mp3\artist1\Track1.mp3
`
### Expected Behaviour

The playlist file should be imported correctly.

### Steps to reproduce the 

Import a .m3u file via the Navidrome Web GUI

Playlist name gets created. But entries are not loaded.

### Platform information

 - Navidrome version:  v0.47.5
 - Browser and version:  Firefox v99.0.1
 - Operating System:  Windows 10

**Comment by zeezhao** [comment]
I played around with the .m3u file, and it seems if music filepath and name are in lowercase, it can't find the track if actual name on filesystem is uppercase. Since windows is case insensitive, code probably needs to ignore case for windows... Thanks.

**Comment by deluan** [comment]
Thanks for reporting. To make things more complicated, seems that Windows NTFS is not _always_ case-insensitive: https://stackoverflow.com/questions/33998669/windows-ntfs-and-case-sensitivity. Or even worse: https://superuser.com/a/1648706

Anyway, I'll take a look and see what I an can come up with

**Comment by zeezhao** [comment]
Please can you confirm if now fixed?

**Comment by deluan** [comment]
Now it should be , just fixed it :)

Can you try the latest develop build?
