### ISSUE TITLE
Extend Reverse Proxy Auth

### ISSUE THREAD

**Issue by helmut72** [navidrome/navidrome#1723]
Thank you for Reverse Proxy Auth.

But wouldn't it be better if the user will be created automatically and get a screen on the first login, where the user must set the local password for accessing Navidrome with apps?

Right now the user must be created in advance. This is ok for a few users, but for 50+ users it's a time consuming task and central management moves a bit away to be central.

Also an option for a logout call like `/logout` should be there, that can be catched from the reverse proxy.

Last but not least it would be fantastic if it also handles other headers like Remote-Email, Remote-Name to fill user informations automatically. If Remote-Group contains "xxx", the user should get admin rights.

Thank you.

**Comment by janderedev** [comment]
I agree, having the option to automatically create new users would be great. Maybe I can find the time to draft a pull request in a couple days.

**Comment by helmut72** [comment]
Any response from the developer?

**Comment by deluan** [comment]
This was already implemented in #2087 and already released, just forgot to close this. Let me know if you have any trouble using it.
