### ISSUE TITLE
Logs report scrobbling for user who has scrobbling disabled

### ISSUE THREAD

**Issue by planetClaire** [navidrome/navidrome#1730]
### Description

Following the docker logs and I can see log entries such as:
`level=info msg=Scrobbled artist="Billy Idol" timestamp="2022-05-12 22:38:13.447319886 +0000 UTC m=+54332.421794756" title="Don’t Need a Gun" user=<username>
`
even though this user doesn't have a last.fm account and hasn't enabled scrobbling. 
The only other user on the system is me, I have a last.fm account and it doesn't appear to be scrobbling to my account so that's good.

### Expected Behaviour

Perhaps this isn't a bug but if the user hasn't enabled scrobbling I wouldn't expect to see these log entries.

### Steps to reproduce

User in question runs substreamer on Android, following docker logs

### Platform information

 - Navidrome version: [0.47.5]
 - Operating System: Debian GNU/Linux 11 (bullseye)
 - Docker deluan/navidrome:latest

### Additional information

 - Logs (turned up to trace here's the latest example)

`{"log":"time=\"2022-05-12T23:03:02Z\" level=info msg=Scrobbled artist=\"David Bowie\" timestamp=\"2022-05-12 23:03:02.755838418 +0000 UTC m=+784.536246166\" title=\"Boys Keep Swinging\" user=<username>\n","stream":"stderr","time":"2022-05-12T23:03:02.779335427Z"}
`
 - Client used? Android substreamer

**Comment by deluan** [comment]
Scrobbling here refers to the act of registering the play, to increment play counts, etc... If the user also have Last.fm or ListenBrainz configured, _then_ (and only then) Navidrome will also send the scrobble to those services. In this case, you should see logs like this:
```
time="2023-01-14T23:59:44Z" level=debug msg="Sending scrobble" artist="The Black Crowes" scrobbler=lastfm track="Hotel Illness"
time="2023-01-14T23:59:44Z" level=debug msg="Sending scrobble" artist="The Black Crowes" scrobbler=listenbrainz track="Hotel Illness"
```

Hope this clarifies it.
