### ISSUE TITLE
Navigation arrows (like Spotify)

### ISSUE THREAD

**Issue by superfunk2000** [navidrome/navidrome#1731]
I like to use the "Install as app" feature. But then I miss the browser navigation buttons back and forward.
![image](https://user-images.githubusercontent.com/90634124/168532573-791a6c8b-189a-42d1-bfa1-55747eb5ae7b.png)

It would really be an advantage to introduce navigation buttons across the board, like Spotify is doing.
![Untitled-3](https://user-images.githubusercontent.com/90634124/168532724-afa1ec25-d71b-4453-b0e2-2792a79e7ceb.png)

There was already a similar request: [#1003](https://github.com/navidrome/navidrome/issues/1003)

**Comment by Octoputty** [comment]
I also install as app on my mobile device. When I click an album I won't be able to go back to the previous window, only return to the primary albums page.
This can be frustrating when browsing a large collection.
