### ISSUE TITLE
Add spoiler to (long) playlist descriptions

### ISSUE THREAD

**Issue by metalheim** [navidrome/navidrome#1737]
### Is your feature request related to a problem? Please describe.

I have some playlists with a lenghty description. When in the playlist-view, the description takes up most of the screen (especially apparent on mobile)

### Describe the solution you'd like

Wrap the playlist description in a spoiler element. Only show ~3 rows by default. Expand the description when clicked on. 
The same way that the Artist Bio and Album comments are handled.

**Comment by deluan** [comment]
That makes sense, will take a look at that. Thanks for the suggestion

**Comment by slashformotion** [comment]
ping myself
