### ISSUE TITLE
Free 'Tagging' for Tracks and Albums would be great

### ISSUE THREAD

**Issue by schittli** [navidrome/navidrome#1738]
Hello
**Thank you very much** for sharing your great work!

### Is your feature request related to a problem? Please describe.
Playlists are nice, but today they feel like decades ago.
### It would be great to be able to freely add tags to Audio Tracks and Albums.
The use cases are simple:

#### Use case 1) Tagging the Music Collection
While listening to music, you freely assign tags to individual tracks, e.g
- piano, cinema, romantic
But also:
- Maya Filipič, Back On Earth
- French, German
- ... whatever

#### Use case 2) Using the power of the tagged music collection 😄 
Tags can be used in many ways, e.g. for searching (_"What was the French name of that rock song by Andrea Bocelli again?"_)
But of course, you can also create playlists dynamically:
- Play all music tracks with 4+ rating in the Spanish language
- Play all movies with Hans Zimmer
- ...

### Describe the solution you'd like
I guess you already used Tags, they can even be found here on GitHub.
Those features would be great:
- Tags can have spaces (e.g. `Maya Filipič`
- Tags can be added to Albums and Tracks
- Creating new Tags is easy: Just add them
- Each Track and Album can have multiple Tags
- A minimal Tag-Manager would be great:
  - Delete a Tag
  - Rename a Tag
  - If `Tag2` is renamed to `Tag1` and it already exists, then all Albums/Tracks with `Tag2` gets the new Tag `Tag1` and afterward, `Tag2` ist deleted (this way, `Tag2` is merged into `Tag1`)

### Describe alternative solutions that would also satisfy this problem
I don't know a more simple, useful, and powerful solution.

Thanks a lot, kind regards,
Thomas

**Comment by juliadin** [comment]
I don't think the OP talks about tagging as in 'metadata' but about tagging as in 'assigning sticky notes to songs/albums within the application'. They could for example be stored in the database and be used to sort, search and arrange music according to a taxonomy that the user is thinking of. There are complexities though that are not that simple to resolve and in my opinion depend highly on the use case:

 - See if and how to merge album / song tags. For example: Should a song that is part of an album be treaded as if it was tagged with the tags of the album or not? 
 - Should each user have their own tags or should they be shared?
 - How should tags be treated regarding the Subsonic API? Virtual playlists? Virtual Albums/Artitst? Not at all? AFAIK Subsonic doesn't support this and I guess it would be nice to at leas think about it.

**Comment by upsuper** [comment]
If tagging is added, it would be great if [smart playlist](https://github.com/navidrome/navidrome/issues/1417) can also support tags.
