### ISSUE TITLE
Auto-select transcoding configuration/format if unselected

### ISSUE THREAD

**Issue by superwave1999** [navidrome/navidrome#1739]
### Is your feature request related to a problem? Please describe.

So I started using Navidrome this week and I noticed that the transcoding setting is not selected (and by consequence, not used) on subsonic clients even if these request a max bitrate.
It's assumed by the user that once the max bitrate is set in a client, it should be working, but I had to enter the web UI and select a transcoding format between the default two available to make it work.

### Describe the solution you'd like

My idea is implement a check [here](https://github.com/navidrome/navidrome/blob/ce0db8344b1d12ae7b5680fa95bdbdb88612fa9e/server/subsonic/stream.go#L35) to see if the current player has a transcoding format selected (+1 database query). If unselected we could either pick the closest configuration below the requested bitrate, or pick opus as default (+1 database query). Suggestions open.

### Describe alternative solutions that would also satisfy this problem

We could extend the subsonic API with a transcoding format selection option, but it's unlikely clients will follow suit.

### Additional context

1. I spun up the latest docker image on a Linux machine
2. Created my admin account
3. Logged in via mobile through the Subtracks subsonic client.
4. Used audio quality as a test. Set max bitrate to 24kbps.
5. Before manually setting the transcoding options in the browser, no difference was heard.
6. After selecting a transcoding configuration, the audio quality was clearly diminished.

By default, the player has a bitrate set, but doesn't have a transcoding configuration set, so it is not applied.

**Comment by superwave1999** [comment]
This seems somewhat related to #351

**Comment by deluan** [comment]
This should now work after #1575 was merged. It will be part of the next release (due end of this month). Let me know if you have any concerns.
