### ISSUE TITLE
Playlist names in sidebar do not update after renaming playlist

### ISSUE THREAD

**Issue by whjms** [navidrome/navidrome#1746]
### Description

When a playlist is renamed, it is still listed in the sidebar with its original name. The name updates after refreshing the page.

### Expected Behaviour

Renamed playlists' labels in the sidebar should update immediately after they are renamed.

### Steps to reproduce

1. Click on the gear icon on the sidebar next to the 'Playlists' category
2. Click 'edit' button on a playlist, change its name, and click save
3. Observe the playlist name in the sidebar does not change

### Platform information

 - Navidrome version: 0.47.5 (86fe1e3b)
 - Browser and version: Firefox 100.0.2
 - Operating System: Debian 11, using pre-built binary

**Comment by deluan** [comment]
Yes, this is a know behaviour, but won't be fixed in the current UI version, unless someone sends a PR. I'm planning a rewrite of the UI and this will be taken into consideration. Thanks for reporting, but will close for now.
