### ISSUE TITLE
Ability to download m3u playlist files using external API

### ISSUE THREAD

**Issue by metalune1** [navidrome/navidrome#1747]
### Is your feature request related to a problem? Please describe.

I want to write a script that automatically downloads playlists from my personal navidrome server and then puts them into m3u files, but the current problem is when fetching them using the Subsonic API it doesn't return the actual file path on the filesystem but rather in a `Artist/Album/Title.mp3` format which is completely useless to me

### Describe the solution you'd like

An easily-accessible link I could call like `https://navidrome.instance.org/playlist/playlist_name/download_m3u` and then include the authentification data in the request header so it would return me a m3u file.

### Describe alternative solutions that would also satisfy this problem

A demonstration of a way how I could artifically call the "Export" button in the web interface from a python or JS script

**Comment by deluan** [comment]
Sorry for the loooong delay. I'm going through old issues and trying to answer as time permits.

Yes, the Subsonic API does not have provisions for what you want, but you can use the native API for that, with these steps:
1. Authenticate and get a auth token by POSTing `{"username": "<username>", "password: "<password>"}` to `/auth/login`. Keep in mind that the token expires after the configured `SessionTimeout` (default 24h)
2. GET `/api/playlist/<playlist_id>/tracks` with the following headers:
   - `x-nd-authorization: Bearer <token from previous step>`
   - `accept: audio/x-mpegurl`
 
This will give you the playlist in M3U format. This is how the UI exports playlists to .M3U files.

Let me know if this answers your question or if you have any further issues.

**Comment by deluan** [comment]
Sorry, I missed one thing: You can make the Subsonic API return real paths, by editting to the Player created for your script and changing the "Report Real Path" flag: 

<img width="524" alt="Screen Shot 2023-01-15 at 3 48 18 PM" src="https://user-images.githubusercontent.com/331353/212566540-31d54ac7-6a6b-4c76-a55d-beaf8eee4834.png">

Now you have two solutions :) 

Closing this for now, but feel free to report back any issues.

**Comment by metalune1** [comment]
Hey thank you for the reply but sadly I'm not using navidrome anymore. Not any Music server as a matter of fact, but thank you anyways, I hope this will be useful to someone stumbling over this.
