### ISSUE TITLE
Folder Name in Song Title

### ISSUE THREAD

**Issue by dl-lim** [navidrome/navidrome#1754]
For context, Navidrome reads this folder: `/music`

And under `/music/` I have several folders, some artist names, some album names etc. But I have one special folder `/music/Songs/` where I store all uncategorised songs. There is a long list of songs here, thousands.

Most songs parse through to Navidrome ok with no issues, title and all, but some songs show title as "Songs/Song Title"

There appears to be no pattern for when this sort of thing occurs. I've checked if having two-word file names do it, or if they come from a specific album/artist etc. No commonalities nor patterns on when a song will have its title changed to "Songs/Song Title" or if its just "Song title"

Hope this picture clarifies a little

![image](https://user-images.githubusercontent.com/69715968/171485232-b47aa169-1116-4941-b935-f533f3b7fa64.png)

Why is this and what can I do to remove the "Songs/" part of the title?

**Comment by metalheim** [comment]
Navidrome displays the path/filename if the file doesnt have a Tag for "Title".
Download mp3tag, filter for missing "title" and add it (You can also add it from filename)

**Comment by deluan** [comment]
What @metalheim said :)

Did you try to fix the file tags? Can this be closed?
