### ISSUE TITLE
ver 0.47.5,Set volume to 100% when web player is in mobile mode .The problem still exists

### ISSUE THREAD

**Issue by ekin1106** [navidrome/navidrome#1756]
i saw releases v0.47.5 
Highlights
[UI] Set volume to 100% when web player is in mobile mode. Fix https://github.com/navidrome/navidrome/issues/1429
my Docker ver is 0.47.5
but this problem  is still exists。
how can i fix it？
thanks everyone

**Comment by deluan** [comment]
Maybe there's some confusion here, the fix is to force the volume to 100%, not the reduce the volume. Is that what you expect?
