### ISSUE TITLE
Possible to remove authentication? 

### ISSUE THREAD

**Issue by mindfuucker** [navidrome/navidrome#176]
Hi,

I'm running [Vouch ](https://github.com/vouch/vouch-proxy) to access Navidrome behind a reverse proxy. This means I need to go through 2 login screens to reach Navidrome. 

Could I disable the authentication of Navidrome and set a default user?

**Comment by deluan** [comment]
Usually this kind of authentication system is used for single user softwares (Sonarr, Radarr, etc...) that only has a login as a gate. 

Navidrome is a multi-user app, so it needs to know which user is accessing it so it can load the personal information for that user, like playlists, stars, ratings (this info is not exposed in the UI yet, but will be soon). If you force it to have one single user you loose this capability.

Having said that, I can see this being useful for installations where there's only one user. I'll leave this open and may introduce a configuration in future versions to handle this. 

In the meantime, you can increase the [session timeout](https://www.navidrom.org/docs/usage/configuration-options) to something like "72h", so you only have to login once and as long as you use Navidrome at least once every 72h you won't need to login again.

**Comment by mindfuucker** [comment]
Vouch has the option to return a username in the header to the application. This could be username or email-address but this depends on the authentication provider. 

I think the audience for this problem is quite niche so I'm okay with setting the session timeout  to 72 hours.

**Comment by mindfuucker** [comment]
I like how [File Browser implements authentication](https://filebrowser.org/configuration/authentication-method). 

They have three options:
1. default login
2. Proxy header
3. No login with default username

This would be very flexible for users. From a developer standpoint it look do-able.

**Comment by deluan** [comment]
Yes, that's the way I want to implement this. But with a configurable session timeout, this is less of a priority ATM, as you can change the Session Timeout to 1 year (525600m) and effectively only login once.

**Comment by NOBLES5E** [comment]
How about support oauth?

**Comment by deluan** [comment]
We don't have plans to support OAuth2 natively, maybe after other priorities are implemented. 

Having said that, the new Reverse Proxy Auth (#1152) will allow you to use a OAuth2 enabled reverse proxy, like Authelia or Vouch, that can handle the authentication flow.

**Comment by mindfuucker** [comment]
I got it working in vouch with the following docker-compose: 
![image](https://user-images.githubusercontent.com/5075692/123240911-04e86000-d4e1-11eb-8644-47e309ff2187.png)

And the following Vouch Nginx proxy-pass block:
![image](https://user-images.githubusercontent.com/5075692/123241182-37925880-d4e1-11eb-9314-f936a938e3ed.png)

A question that's on my mind: 
Is the request username matched with the Navidrome Username, User or Email?

**Comment by helmut72** [comment]
> Reverse Proxy Auth (#1152)

Thank you for this feature. But wouldn't it be better if the user will be created automatically and get a screen on the first login, where the user must set the local password for accessing Navidrome with apps?

Right now the user must be created in advance. This is ok for a few users, but for 50+ users it's a time consuming task and central management moves a bit away to be central.

Also an option for a logout call should be there, that can be catched from the reverse proxy.

Thank you.
