### ISSUE TITLE
Downloaded files with slash in tag fields (/) gets converted into new folder

### ISSUE THREAD

**Issue by andylundqvist** [navidrome/navidrome#1763]
### Description

When downloading files from Navidrome 0.47.5 (from an album or playlist), if a tag field contains a "/" character, the download creates a folder at the place of this character in the file name, thus breaking the general, expected file structure.

Example (correct) : A track "Song A" by artist "John" is correctly named "John - Song A.mp3" when downloaded and is placed in the root directory when unzipped.

**Example (incorrect): The track "My Track" by artist "Lisa / Michael" when downloaded and unzipped instead gets the filename: "Michael - My track.mp3" inside a folder called "Lisa".**

### Expected Behaviour

A common solution for such cases is to convert fields with slash ("/") to an underscore ("_") and I believe this would be an easy fix for the problem.

### Platform information

 - Navidrome version: 0.47.5
 - Browser and version: Safari 15.5
 - Operating System: macOS 12.4

**Comment by andylundqvist** [comment]
I was unable to comment before the issue was marked stale and closed but I can confirm that this bug still exists in the current 0.49.3 version.

**Comment by deluan** [comment]
Thanks for the call-out. I reopened the issue.

**Comment by subhajit20** [comment]
@deluan  hey! I would like to fix this issue also, could you help me like in which file I have to replace the slash with the underscore sign?

**Comment by deluan** [comment]
This will require a complete dev environment, with `make` and all. Were you able to install the whole dev environment in your local?

**Comment by subhajit20** [comment]
> This will require a complete dev environment, with `make` and all. Were you able to install the whole dev environment in your local?

@deluan  hey! Yes I have install entire environment setup in my local machine.

**Comment by subhajit20** [comment]
> This will require a complete dev environment, with `make` and all. Were you able to install the whole dev environment in your local?

@deluan Hey thanks for guiding me and it was my first open-source contribution.

**Comment by subhajit20** [comment]
@deluan  and I have made the local setup done can you guide me that which fil do I have to change in this issue ?

**Comment by deluan** [comment]
Hey @subhajit20 , sorry for the delay.

For this we will need to create a function to clean-up filenames. There maybe something ready on the internets, but we don't want to add a new Go dependency just for that ;)

Then this function will be used in the two places used to add files to a zip:

https://github.com/navidrome/navidrome/blob/c12510d6e2387e9cef942c5dad902baa82fe50ce/core/archiver.go#L89

and 

https://github.com/navidrome/navidrome/blob/c12510d6e2387e9cef942c5dad902baa82fe50ce/core/archiver.go#L133

Don't forget to write tests. Let me know if you have any other questions.

**Comment by subhajit20** [comment]
@deluan  so I have to just paste these two functions you have mentioned above in two separate files or anything else?

**Comment by deluan** [comment]
You will have to create a function like:
```
func cleanFilename(name string) string
```

Then you will use this function in the places I mentioned above. No new files, put this new function in the `navidrome/core/archiver.go` file.

**Comment by andylundqvist** [comment]
I haven’t had the time to try it yet but thank you!
