### ISSUE TITLE
Not able to enable Listenbrainz Scrobble

### ISSUE THREAD

**Issue by bhankas** [navidrome/navidrome#1766]
### Description

When trying to enable 'Scrobble to Listenbrainz', after adding token, a popup appears with an error:

```
ListenBrainz could not be linked: Get "https://api.listenbrainz.org/1/validate-token": dial tcp: lookup api.listenbrainz.org on [::1]:53: read udp [::1]:47765->[::1]:53: read: connection refused
```

### Expected Behaviour

What you would have expected to happen instead.

### Steps to reproduce

1. Open Personal Settings
2. Click on 'Scrobble to ListenBrainz'
3. Paste token
4. Click save

### Platform information

 - Navidrome version: 0.47.5
 - Browser and version: Firefox 101.0.1 (Windows)
 - Operating System: NixOS Unstable channel, built from source.

### Additional information

Any other information that may be relevant or give context to the problem.

 - Screenshots
![image](https://user-images.githubusercontent.com/24254289/173220173-0bc066c0-85d2-4089-a5be-f602640a3ece.png)

 - Logs?
 ```
  253   │ Jun 12 11:59:14 hermes navidrome[3438]: time="2022-06-12T06:29:14Z" level=error msg="Could not validate ListenBrainz token" error="Get \"https://api.listenbrainz.org/1
       │ /validate-token\": dial tcp: lookup api.listenbrainz.org on [::1]:53: read udp [::1]:37295->[::1]:53: read: connection refused" requestId=hostname/yqCzHTijMu-000233 user
       │ Id=f2f8a0e3-373e-4506-a93c-d0af2a092e01
 254   │ Jun 12 11:59:14 hermes navidrome[3438]: time="2022-06-12T06:29:14Z" level=error msg="HTTP: PUT http://127.0.0.1:4533/api/listenbrainz/link" elapsedTime=1.1ms httpStatu
       │ s=500 remoteAddr="127.0.0.1:37626" requestId=hermes/yqCzHTijMu-000233 responseSize=179
```
 
 - Client used? : browser

- Systemd unit:

```
~ 2m 37.3s ❱ systemctl cat navidrome.service | cat
# /etc/systemd/system/navidrome.service
[Unit]
After=network.target
Description=Navidrome Media Server

[Service]
Environment="LOCALE_ARCHIVE=/nix/store/crmz9nic5njddjscq8wc9kfdzsvxici5-glibc-locales-2.34-210/lib/locale/locale-archive"
Environment="PATH=/nix/store/y72i4llqf5zxvdp6b3j7ysixpdrid7qr-coreutils-9.1/bin:/nix/store/lxd4xas5jkkf4q2gnb9v8iss3lpgh4jh-findutils-4.9.0/bin:/nix/store/z3q9q9549ci7kbdgyq99r6crnvrky6v3-gnugrep-3.7/bin:/nix/store/j8hcaam4dpv1ys2bnxijwxqiy0si0pzk-gnused-4.8/bin:/nix/store/4c022pyxsr5lwaghbj9s3w0lbqnqzi1l-systemd-250.4/bin:/nix/store/y72i4llqf5zxvdp6b3j7ysixpdrid7qr-coreutils-9.1/sbin:/nix/store/lxd4xas5jkkf4q2gnb9v8iss3lpgh4jh-findutils-4.9.0/sbin:/nix/store/z3q9q9549ci7kbdgyq99r6crnvrky6v3-gnugrep-3.7/sbin:/nix/store/j8hcaam4dpv1ys2bnxijwxqiy0si0pzk-gnused-4.8/sbin:/nix/store/4c022pyxsr5lwaghbj9s3w0lbqnqzi1l-systemd-250.4/sbin"
Environment="TZDIR=/nix/store/2gwcg7qi7p4pg83pyibmhg76dc65zlyp-tzdata-2022a/share/zoneinfo"



BindReadOnlyPaths=/nix/store
BindReadOnlyPaths=/home/user/Music/
CapabilityBoundingSet=
DynamicUser=true
ExecStart=/nix/store/g432s8by5kvvp49xql4v3syag2j2rmny-navidrome-0.47.5/bin/navidrome --configfile /nix/store/6ndqr2r7nfxv2f8vlr0gscjj003qmkf4-navidrome.json

LockPersonality=true
MemoryDenyWriteExecute=true
PrivateDevices=true
PrivateUsers=true
ProtectClock=true
ProtectControlGroups=true
ProtectHome=tmpfs
ProtectHostname=true
ProtectKernelLogs=true
ProtectKernelModules=true
ProtectKernelTunables=true
ReadWritePaths=
RestrictAddressFamilies=AF_UNIX
RestrictAddressFamilies=AF_INET
RestrictAddressFamilies=AF_INET6
RestrictNamespaces=true
RestrictRealtime=true
RootDirectory=/run/navidrome
RuntimeDirectory=navidrome
StateDirectory=navidrome
SystemCallArchitectures=native
SystemCallFilter=@system-service
SystemCallFilter=~@privileged
SystemCallFilter=~@resources
UMask=0066
User=user
WorkingDirectory=/var/lib/navidrome
```

I am new to music streaming, so it is possible I am missing something obvious, but I'm not understanding why is it looking for open UDP port on local. Any help or insight appreciated.

**Comment by bhankas** [comment]
So far, I've had to fix MusicFolder and DataFolder by forcing systemd unit to make them accessible to the service. It makes me think this bug is also possibly related to the unit config only. However, I'm not well versed in systemd  unit configs, and cannot trial-error around every unit config out there, so will need some help. For starters, I tried removing 1RestrictAddressFamilies` completely and that didn't make any difference.

**Comment by karmanyaahm** [comment]
> I'm not understanding why is it looking for open UDP port on local

To talk to listenbrainz, it's trying to connect to the local DNS server, so it can find the address of listenbrainz. (port 53 is DNS).

I don't have much experience with NixOS specifically, but could you post the contents of your `/etc/resolv.conf` file? Also, maybe try adding `BindReadOnlyPaths=/etc/resolv.conf` (whether that will make a difference depends on the contents of the file)
