### ISSUE TITLE
Won't import smart playlists

### ISSUE THREAD

**Issue by cinbunnaps** [navidrome/navidrome#1769]
### Description

I'm fairly certain this is user error so I didn't want to mark it down as a bug.

### Expected Behaviour

For the life of me I can't get Navidrome to recognize/import my smart playlist. I have my library mounted in /music and my playlists in /music/playlists

### Steps to reproduce

Tried restarting container, recreating the container, I always show 0 imported. Also tried doing a manual search.

### Platform information

 - Navidrome version: [0.47.5] (86fe1e3b)
 - Browser and version: Firefox 101.0 (64-bit)
 - Operating System: Ubuntu 22.04 LTS (installed from bootable USB, not sure what kind of install that's considered)

### Additional information

Any other information that may be relevant or give context to the problem.

**Comment by TheWrathKing** [comment]
Did you put the following lines in your configuration file ?
 PlaylistsPath = "playlists" 
 AutoImportPlaylists = "true"
In your case the PlaylistPath variable must be "playlists" as it is relative to the music path.

**Comment by cinbunnaps** [comment]
> Can you tr set the loglevel to "debug" and search for "playlist" in the logs? If Its a malformed nsp file, navidrome will tell you whats wrong with it.
> 
> If theres nothing in the logs, chances are that its a permission issue and navidrome doesn't See the playlist, because Its Not allowed to.

I've chown/chgrp on the playlist folder which didn't seem to help, I also switched to debug and filtered the logs for 'playlist' and 'nsp' just to see what I could find and this is all it's said:
    AutoImportPlaylists:        true,
    PlaylistsPath:              "playlists",
    DevSidebarPlaylists:        true,

**Comment by cinbunnaps** [comment]
> Did you put the following lines in your configuration file ? PlaylistsPath = "playlists" AutoImportPlaylists = "true" In your case the PlaylistPath variable must be "playlists" as it is relative to the music path.


This is my compose file:

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      - ND_LOGLEVEL=debug
      - ND_SESSIONTIMEOUT=24h
      - ND_AUTOIMPORTPLAYLISTS=true
      - ND_PLAYLISTSPATH=playlists
      - ND_UIWELCOMEMESSAGE=Good morning cruel world, you may be cruel but I'm still kickin' it
    volumes:
      - "./navidrome:/data"
      - "${MUSIC}:/music:ro"

**Comment by TheWrathKing** [comment]
Did you try to log in as 'admin' ? I think the playlists are imported for this account and then you have the possibility to share them (make them public) or edit them and change their owner.

**Comment by ammgws** [comment]
@cinbunnaps Did you get anywhere with this? I somehow got one smart playlist imported when I first setup Navidrome, but now that I'm trying to add more I'm in the same situation as you.

**Comment by l0l67** [comment]
I also have this issue with Docker, however it was working fine on the same version without Docker on a native install.

**Comment by l0l67** [comment]
I got my smart playlists to show up after i added a new one and ran a quick scan...
All i did:
1. Create a new .nsp file in the playlists directory: `nano /Musik/smartPlaylists/test.nsp` with the following content:
```
{
  "all": [
    {"is": {"loved": true}}
  ],
  "sort": "dateLoved",
  "order": "desc",
  "limit": 500
}
```
2. save the file
3. press quick scan in the webinterface
4. delete the `test.nsp` file

**Comment by Merkwurdichliebe** [comment]
I am having this issue since updating to 0.49. In my music folder, I have a `__Playlists__` folder which contains some `m3u8` files. navidrome used to import them without problems, I wonder what could have caused it to stop working.

**Comment by l0l67** [comment]
> I am having this issue since updating to 0.49. In my music folder, I have a `__Playlists__` folder which contains some `m3u8` files. navidrome used to import them without problems, I wonder what could have caused it to stop working.


Try to create a new playlist file (`.nsp`) and do a quick scan (you can delete it afterwards)

**Comment by Merkwurdichliebe** [comment]
I tried both creating a new empty playlist from the web UI and doing `touch test.nsp` in the same `__Playlists__` folder, doing a quick scan after each step, but navidrome still ignores the two new `m3u8` which are in the same folder (it otherwise perfectly detects new albums and tracks btw).

**Comment by l0l67** [comment]
Is there anything in the log?

**Comment by Merkwurdichliebe** [comment]
From click Quick Scan to the end of the process only this:
```
time="2023-02-07T14:54:05+01:00" level=info msg="Triggering manual scan" fullScan=false requestId=me.local/Kq6clkhi83-014263 user=me username=me
time="2023-02-07T14:54:09+01:00" level=info msg="Finished processing Music Folder" added=0 deleted=0 elapsed=4.3s folder="/Volumes/Music/iTunes Media/Music" playlistsImported=0 updated=0
time="2023-02-07T14:54:09+01:00" level=info msg="Manual scan complete" elapsed=4.4s requestId=me.local/Kq6clkhi83-014263 user=me username=me
```

**Comment by deluan** [comment]
@Merkwurdichliebe to be able to figure this out, I need you to follow these steps:
1. Stop Navidrome
2. Backup your data folder
3. Remove all files from the data folder (`navidrome.db`, etc...)
4. Change your log level to `debug`
5. Start navidrome.

Then send me the complete log. If you think it has any sensitive data, you can send it by email: deluan @ navidrome.org

**Comment by deluan** [comment]
@cinbunnaps Did you ever figure this out? If not, please do the same steps as I mentioned above.

**Comment by Merkwurdichliebe** [comment]
Sorry if it's a silly question, but if I remove all files from the data folder how can I change the log level? It's set in the `.toml` file which is in there too, together with the log and cache.

**Comment by deluan** [comment]
Ah, in this case just keep the `.toml` file there, removing all the rest.

**Comment by Merkwurdichliebe** [comment]
Well, this is going to be a very large file. It's scanning a 360gb music folder and there are tons of "TagLib: ID3v2.4 no longer supports the frame type TDAT.  It will be discarded from the tag." Wouldn't it be simpler to change the music folder, have a couple of sample albums there and try again, with my offending playlists?

**Comment by deluan** [comment]
```
  PlaylistsPath:                    "../../../SSD/Users/me/Files/Docs/Playlists",
```

Is this correct? It has to be relative to the MusicFolder. Anyway, playlists are imported at the end of the scan, so logs for them should appear immediately before the "Finished processing Music Folder". You should have seen lines like:

```
DEBU[0006] Found playlist                                lastUpdated="2020-10-13 19:11:11.615515288 -0400 EDT" name="Best Of Saara Saara" numTracks=6 path="/Users/deluan/Music/Music/Media/Music/Best Of Saara Saara.m3u"
INFO[0006] Adding synced playlist                        owner=admin path="/Users/deluan/Music/Music/Media/Music/Best Of Saara Saara.m3u" playlist="Best Of Saara Saara"
DEBU[0006] Imported playlist                             lastUpdated="2020-10-13 19:11:11.615515288 -0400 EDT" name="Best Of Saara Saara" numTracks=0 path="/Users/deluan/Music/Music/Media/Music/Best Of Saara Saara.m3u"
```
for M3U playlists, and:
```
DEBU[0006] Found playlist                                lastUpdated="2022-07-27 20:56:41.029916502 -0400 EDT" name=Favourites numTracks=0 path=/Users/deluan/Music/Music/Media/__/Favourites.nsp
INFO[0006] Adding synced playlist                        owner=admin path=/Users/deluan/Music/Music/Media/__/Favourites.nsp playlist=Favourites
DEBU[0006] Refreshing smart playlist                     id=93a8eb50-c22e-4f8d-82a1-f1d043ca2fb5 playlist=Favourites
DEBU[0006] Refreshed playlist                            elapsed=1.4ms id=93a8eb50-c22e-4f8d-82a1-f1d043ca2fb5 numTracks=0 playlist=Favourites
DEBU[0006] Imported smart playlist                       lastUpdated="2022-07-27 20:56:41.029916502 -0400 EDT" name=Favourites numTracks=0 path=/Users/deluan/Music/Music/Media/__/Favourites.nsp
```

for NSP (smart) playlists.

**Comment by Merkwurdichliebe** [comment]
As you can see in the log, I don't have any of these. The `PlaylistPath` is valid, and has worked in 0.48. To confirm, I just went into my music folder:
`cd /Volumes/Music/iTunes\ Media/Music`
From there, I entered:
`ls ../../../SSD/Users/me/Files/Docs/Playlists`
This lists 7 `m3u8` files and one `m3u` file.

**Comment by deluan** [comment]
> As you can see in the log,

Well, I don't see the lines immediately above the `Finished processing Music Folder` line, so I can't really tell. 

> ls ../../../SSD/Users/me/Files/Docs/Playlists

Reading the code now, and I'm pretty sure this wouldn't work, as the scanner does not follow paths outside the MusicFolder. You would need to create a symlink inside the MusicFolder, pointing to that path.

Also, I forgot to mention, but playlists are only imported if you have an admin user created in your system.

**Comment by Merkwurdichliebe** [comment]
> Well, I don't see the lines immediately above the `Finished processing Music Folder` line, so I can't really tell.

Sorry about that, here they are:

```
time="2023-02-07T20:38:47+01:00" level=debug msg="Processing changed folder" dir="/Volumes/Music/iTunes Media/Music"
time="2023-02-07T20:38:47+01:00" level=debug msg="Finished deleted folders check" elapsed=859ns total=0
time="2023-02-07T20:38:47+01:00" level=debug msg="Finished reading directories from filesystem" elapsed=53m55s
time="2023-02-07T20:38:47+01:00" level=warning msg="Playlists will not be imported, as there are no admin users yet, Please create an admin user first, and then update the playlists for them to be imported" dir="/Volumes/Music/iTunes Media/Music/__Playlists__"
time="2023-02-07T20:38:47+01:00" level=debug msg="Removing non-album artist_id"
```

> Reading the code now, and I'm pretty sure this wouldn't work, as the scanner does not follow paths outside the MusicFolder. You would need to create a symlink inside the MusicFolder, pointing to that path.

As I wrote in my post above, I've tried removing the `PlaylistPath` but playlists inside the music folder weren't imported either.

> Also, I forgot to mention, but playlists are only imported if you have an admin user created in your system.

There is only one user in my setup, the one I created when installing navidrome. I've opened the db (my backup one, not the test db which doesn't even have a user), and indeed there is only one user there, the one I've always been using, with `is_admin` set to `1`.

**Comment by deluan** [comment]
> time="2023-02-07T20:38:47+01:00" level=warning msg="Playlists will not be imported, as there are no admin users yet, Please create an admin user first, and then update the playlists for them to be imported" dir="/Volumes/Music/iTunes Media/Music/__Playlists__"

Well, you didn't have the user when running the scanner. I know it is inconvenient and I'll fix soon, but this is what is happening here.

Remember that any playlists that were skipped for any reason (no admin user, changing the `PlaylistPath` config), they won't be detected in next scan. You need to touch/edit them before the scan.

**Comment by Merkwurdichliebe** [comment]
> Well, you didn't have the user when running the scanner. 

Indeed, but that was just the non-existing user for the test scan. In my real db I have an admin user as explained in my post above.

> You need to touch/edit them before the scan.

Ah, well, that wasn't obvious :) If I do `touch *.*` in my `__Playlists__` folder and remove the `PlaylistPath` variable from the config, then the playlists are imported correctly. **Although** strangely enough they are **not** imported on a quick-scan — the server needs to be stopped and restarted for this to work.

**Comment by JOJ0** [comment]
Hi! I had a similar problem with importing my m3u/m3u8  playlists located within a subfolder of /music. Changing timestamp/touching those playlists and rebooting my navidrome docker container fixed it. Thanks for reporting and explaining in detail to all of you!

@deluan, would it make sense to add this behaviour (user has to be created prior to make importing happen) to the docs for the AutoImportPlaylists configuration option here: https://www.navidrome.org/docs/usage/configuration-options/ (or to PlaylistsPath or both or link to somewhere in the docs where this is explainend from those places)

I'm a little busy currently but with some pointers I might even submit a PR. What do you think?

**Comment by deluan** [comment]
> @deluan, would it make sense to add this behaviour (user has to be created prior to make importing happen) to the docs for the AutoImportPlaylists configuration option here: https://www.navidrome.org/docs/usage/configuration-options/ (or to PlaylistsPath or both or linking to somewhere in the docs where this is explainend)
> 
> I'm a little busy currently but with some pointers I might even submit a PR. What do you think?

It is already mentioned here: https://www.navidrome.org/docs/getting-started/
But if you want to make it more visible or change the wording, feel free to submit a PR.

**Comment by JOJ0** [comment]
Oh wow that is actually pretty detailed and obvious. Shame on me for not reading the getting started guide. I think that's well documented already. Thanks and sorry bothering!

**Comment by hidetheweed** [comment]
So I just discovered smart playlists, but I am also having trouble importing it to navidrome. I have created .nsp files in vim and moved them to /music/playlists.
My user is admin, PlaylistPath is /music/playlists (I have also tried with the whole pathway /home/users/docker...../music/playlists). ND_AUTOIMPORTPLAYLISTS=true. Nothing happens when I scan or restart docker. 
Just one error message (yesterday) when I search for "nsp", even though I have restarted docker and scanned navidrome many times since. The message: ERRO[2355000] Error parsing playlist                        error="invalid character 'ï' looking for beginning of value" path="/music/recently added.nsp"
Since then I have changed the path to /music/playlists, made sure that there are no 'ï'  characters (it werent in the first place) and changed file nape to recently_added.nsp. But like I said, except for this one error message, I havent got any more when I search for nsp in the docker log.

Any ideas what I should try next?  Is there something obvious I have missed?

**Comment by metalheim** [comment]
> So I just discovered smart playlists, but I am also having trouble importing it to navidrome. I have created .nsp files in vim and moved them to /music/playlists. My user is admin, PlaylistPath is /music/playlists (I have also tried with the whole pathway /home/users/docker...../music/playlists). ND_AUTOIMPORTPLAYLISTS=true. Nothing happens when I scan or restart docker. Just one error message (yesterday) when I search for "nsp", even though I have restarted docker and scanned navidrome many times since. The message: ERRO[2355000] Error parsing playlist error="invalid character 'ï' looking for beginning of value" path="/music/recently added.nsp" Since then I have changed the path to /music/playlists, made sure that there are no 'ï' characters (it werent in the first place) and changed file nape to recently_added.nsp. But like I said, except for this one error message, I havent got any more when I search for nsp in the docker log.
> 
> Any ideas what I should try next? Is there something obvious I have missed?

Playlistpath is relative to /music/ already (see documentation). From what I read, your Playlistpath should be just "playlists"

**Comment by hidetheweed** [comment]
> 

Thanks for replying. Tried with just /playlists but nothing happened. So if my playlists would be in the music folder, the path should only be "/" I see that for ND_MUSICFOLDER the path is "/music"

**Comment by deluan** [comment]
PlaylistPaths need to be _relative_. Paths that start with `/` are _absolute_ (from root). So in your case it should be:
```
ND_MUSICFOLDER=/music
ND_PLAYLISTSPATH=playlist. # <- no "/" at the beginning
```

If you want to match playlists anywhere under the MusicFolder, you can leave `ND_PLAYLISTSPATH` blank as this is the default. Or, you can set it to "." meaning only in the MusicFolder itself (i.e. `/music/123.m3u matches, but `/music/other/123.m3u` does not`)

**Comment by hidetheweed** [comment]
> PlaylistPaths need to be _relative_. Paths that start with `/` are _absolute_ (from root). So in your case it should be:
> 
> ```shell
> ND_MUSICFOLDER=/music
> ND_PLAYLISTSPATH=playlist. # <- no "/" at the beginning
> ```
> 
> If you want to match playlists anywhere under the MusicFolder, you can leave `ND_PLAYLISTSPATH` blank as this is the default. Or, you can set it to "." meaning only in the MusicFolder itself (i.e. `/music/123.m3u matches, but `/music/other/123.m3u` does not`)

Omg TIL the difference between absolute and relative path (noob, yes). THANK YOU GUYS! It of course works perfectly now!! :D
