### ISSUE TITLE
Cookies use depreated value "None" for SameSite

### ISSUE THREAD

**Issue by ElectronicWar** [navidrome/navidrome#1776]
### Description

* None is deprecated and will fallback to Lax in the future, it currently throws a warning on Firefox. [Details on MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite)
* Using Strict is future proof and provides additional CSR protection
* Using Strict caused no regressions in my tests

### Expected Behaviour

No warnings in developer console about cookie settings.

### Steps to reproduce

1. Open Navidrome instance over HTTPS
2. Start playing any song
3. Check developer console output

### Platform information

 - Navidrome version: v0.47.5
 - Browser and version: Firefox Developer Edition 102.0b9
 - Operating System: Windows 11 (Client, Browser), Debian 12 (Server, official Navidrome amd64 binary from Github)

### Additional information

Any other information that may be relevant or give context to the problem.

Screenshots of browser console output
![image](https://user-images.githubusercontent.com/1890874/174351332-d9e44e31-7a0e-4fa0-bcc3-e3962713ee7f.png)

**Comment by deluan** [comment]
Fixed by #1777
