### ISSUE TITLE
[Request] Approve Language in POEditor (gl)

### ISSUE THREAD

**Issue by xmgz** [navidrome/navidrome#1784]
I'd like to contribute translating Navidrome to my language (gl, gl_ES)

Some weeks (months?) ago I requested joining the project, but it's been not approved yet

Please would any translations manager activate this language in POEditor web? thank you.

I have experience translating other free/libre software: https://xmgz.eu/traducindo/

**Comment by deluan** [comment]
Hey @xmgz , sorry I completely missed your request. Let me know if you are still interested in helping with the translation. It would be very much appreciated.

**Comment by xmgz** [comment]
yes, I'm actively using Navidrome in my server, so I will translate it. Thank you.

(I see it's already available in poeditor)

**Comment by deluan** [comment]
Thanks! Please join our Discord (channel #translators) if you have questions.

**Comment by deluan** [comment]
Hey @xmgz , the term `languageName` should be the name of the language written in itself, not the translation of "English". In Galician, it should be "Galego", right? 

Are you in our Discord server? It is easier to talk about these things in our #translations channel.

**Comment by xmgz** [comment]
yes, "Galego". 


no, I'm not.

Thank you.
