### ISSUE TITLE
HTTP 510 vs 501 - not implemented mix-up 

### ISSUE THREAD

**Issue by memen45** [navidrome/navidrome#1785]
https://github.com/navidrome/navidrome/blob/af00503b77f3bca6259aac607fbaded1ffb42295/server/subsonic/api.go#L208

In the comments and function name I would expect a 501 - Not Implemented response, however, in the referenced line, a 510 is created instead. I assume this is a typo?

**Comment by deluan** [comment]
Good catch!! Thanks for reporting this, I'm fixing it right now!
