### ISSUE TITLE
Development stalled?

### ISSUE THREAD

**Issue by helmut72** [navidrome/navidrome#1787]
Development stalled?

**Comment by edimusxero** [comment]
I hope not, I really like this

**Comment by lostpolaris** [comment]
I spoke with the creator not too long ago, AFAIK, he's in a pretty busy time in his work right now, but he has still has full plans to continue to actively develop the application.

**Comment by helmut72** [comment]
Ok, I just asked because of the last commit and even no few words in the issues after 31th march. Also know some other projects shutting down.
