### ISSUE TITLE
Support for Automatic Playlists (saved searches)

### ISSUE THREAD

**Issue by djjudas21** [navidrome/navidrome#1794]
### Is your feature request related to a problem? Please describe.

I have migrated to Navidrome from Rhythmbox. I'm mostly happy with the experience but Rhythmbox has one killer feature which they call _Automatic Playlists_. I guess you can think of them like saved searches.

https://help.ubuntu.com/community/Rhythmbox#Playlists

I have several automatic playlists set up but the one I use most is to display tracks that have never been played (i.e. `Play Count == 0`), so I can listen only to new music.

I've got several other automatic playlists for helping me maintain my library:
* tracks that have never been rated (so I can rate them)
* tracks that have a low rating (so I can consider removing them my library)
* tracks with no Composer (so I can contribute the data to MusicBrainz and re-tag with Picard)
* tracks with no Genre (so I can contribute the data to MusicBrainz and re-tag with Picard)

And obviously some more obvious use cases like:
* tracks with a 5-star rating

### Describe the solution you'd like

It would be amazing if Navidrome could support automatic playlists. Rhythmbox has a little query builder GUI but I guess a first pass attempt at this could use some basic kind of query language to prove the concept.

![image](https://user-images.githubusercontent.com/604595/176725665-8e0a0446-81d6-4548-98c8-c5539a015345.png)

Automatic Playlists appear in Rhythmbox alongside regular Static Playlists. Static Playlists have a page icon and Automatic Playlists have a magnifying glass icon.

![Screenshot from 2022-06-30 17-17-06](https://user-images.githubusercontent.com/604595/176727820-469883c0-0a79-46ff-b752-a8305da6b944.png)

### Additional context

I appreciate this is quite a complex feature and not likely to a priority, but I just wanted to log it here so it can be discussed etc. Thanks for all your work on Navidrome.

**Comment by metalheim** [comment]
You will love #1417

There is no GUI to enter queries for automatic playlists... Yet. 
But for now you can enter the queries as a json object into a file with ". nsp" suffix and navidrome will create a dynamic/query based playlist and keep it updated.

**Comment by djjudas21** [comment]
This is amazing news! I've spent the rest of my evening opening issues against projects that seem to be dead so it's nice to hear about a feature I need :grinning: I'll give this a try

**Comment by djjudas21** [comment]
I've managed to implement some playlists in nsp format, so I'll close this issue as #1417 seems to have everything covered
