### ISSUE TITLE
Option to turn off downloads

### ISSUE THREAD

**Issue by ebiscaia** [navidrome/navidrome#1801]
Is it possible to implement a button to disable the download option?

Thanks,

Eduardo

**Comment by neingeist** [comment]
You can disable downloads by configuration (`EnableDownloads`/`ND_ENABLEDOWNLOADS`, see [the documentation](https://www.navidrome.org/docs/usage/configuration-options/)).

**Comment by ebiscaia** [comment]
Hi,

As I am using the Docker version of Navidrome I added the parameter as a environment parameter and it worked. Unfortunately, my streamer app started popping messages so I had to disable this option until a fix from there is made.

Thanks,

Eduardo

**Comment by Vista2003** [comment]
Would be nice to have this as a per user thing

**Comment by deluan** [comment]
> Would be nice to have this as a per user thing

This will be implemented as part of [Multiple Folders](https://github.com/navidrome/navidrome/issues/192#issuecomment-703625578)

> Unfortunately, my streamer app started popping messages so I had to disable this option until a fix from there is made.

Closing this then, as it seems to be an issue with your client.
