### ISSUE TITLE
I'm using a QNAP device, I installed Navidromome via qnapclub, how should I set the music storage location.

### ISSUE THREAD

**Issue by zwandlp** [navidrome/navidrome#1803]
I'm using a QNAP device, I installed Navidromome via qnapclub, how should I set the music storage location.

**Comment by suicablue** [comment]
You can change the location in navidrome,sh in your navidrome working directory using SSH. It's "/share/CACHEDEV1_DATA/.qpkg/NaviDrome" in my NAS. Find the line "export ND_MUSICFOLDER=" and type in the scanning location you desire, then save and restart.

You might need to edit navidrome.sh using "admin" account cause the default owner of navidrome is "admin". Other users including the administer you created has no access to execute navidrome by default.

**Comment by zwandlp** [comment]
Thanks！谢谢您
