### ISSUE TITLE
how to init my project

### ISSUE THREAD

**Issue by Linindoo** [navidrome/navidrome#1808]
### Description

i can`t create user .

### Expected Behaviour

create user success.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/26195410/178500557-d6973363-917f-4ae5-b4e4-0e58637c4df5.png)

### Platform information

 - Navidrome version: 0.47.0
 - Browser and version: Chrome  103.0.5060.114 
 - Operating System: Linux raspberrypi 5.10.103-v7    armv7l GNU/Linux

**Comment by zeezhao** [comment]
Try username: admin
I cant recall but maybe it is expecting that as the admin person.

**Comment by scottmuc** [comment]
@Linindoo, something to check is whether or not navidrome's data location is writeable. Can you display the permissions of the `DataFolder` configuration?

**Comment by Linindoo** [comment]
> Try username: admin I cant recall but maybe it is expecting that as the admin person.
> 
> Also, current version is 0.47.5 see: https://github.com/navidrome/navidrome/releases

thanks,it is work for me to check the permission of user,i forget to authorize user the folder

**Comment by Linindoo** [comment]
> > Try username: admin I cant recall but maybe it is expecting that as the admin person.
> > Also, current version is 0.47.5 see: https://github.com/navidrome/navidrome/releases
> 
> thanks,it is work for me to check the permission of user,i forget to authorize user the folder

but it is strange to throw a error  of  401
