### ISSUE TITLE
segfault when scanning

### ISSUE THREAD

**Issue by FF899F** [navidrome/navidrome#1826]
### Description

While scanning library Navidrome segfaults at the same file and reboots itself creating a failure loop

### Expected Behaviour

To scan my music library.

### Platform information

 - Navidrome version: v0.47.5
 - Operating System: Linux / raspberrypi zero / 5.15.32+ / armv6l

### Additional information

Log snippet (trace):
https://pastebin.com/raw/Q6ETuxCj

**Comment by deluan** [comment]
Can you please attach here the file that is causing the issue? If you can't share it publicly, please send it to my email at deluan @ navidrome.org. Thanks

**Comment by FF899F** [comment]
@deluan I switched to ffmpeg instead of taglib and it seems to have stopped segfaults, gonna take a while to fully index but yeah. 

here is the mp3 that was crashing taglib:
https://filebin.net/1l9ewymxgvj6jf9m

**Comment by deluan** [comment]
> I switched to ffmpeg instead of taglib and it seems to have stopped segfaults,

Yeah, that's is usually the solution for these cases. ffmpeg is more resilient to malformed tags.

Thanks for the file, I'll take a look and see if this is something we can handle. I'm closing this for now, but feel free to report back any further related issues
