### ISSUE TITLE
Please add the possibility to add more than one folder f.e. a folder audiobooks. Thanks so much for your great work.

### ISSUE THREAD

**Issue by thomy2065** [navidrome/navidrome#1829]
### Is your feature request related to a problem? Please describe.

A clear and concise description of what the problem is. For e.g. I'm always frustrated when '...'

### Describe the solution you'd like

A clear and concise description of what you would like to happen.

**Comment by deluan** [comment]
Thanks for using Navidrome. This is a duplicate of #192
