### ISSUE TITLE
Is the lyrics function working properly?

### ISSUE THREAD

**Issue by WatcherSaria** [navidrome/navidrome#1840]
I've tried different ways to make the lyrics function working, put the .lrc file which has same filename with the audio file in the same folder, copy the content in .lrc file then use them as the value of ID3 tag named \<LYRICS\> of the audio file, but all failed. It still displays "No lyrics". I mean is the lyrics function working properly? or I did wrong way to add lyrics. Or it just won't read it from local file only gather lyrics from Internet? I viewed documentation for times but didn't find any useful information about this problem
Version 0.47.0 in Docker

**Comment by metalheim** [comment]
".lrc" files are not (yet) supported, see #1421 

The only thing that is supported currently, is reading unsynced lyrics (no timestamps) from tags. 
Lyrics in ID3 tags shouldn't go in a frame called "<LYRICS>". The correct tag to use would be "USLT".
See: https://docs.mp3tag.de/mapping/#unsyncedlyrics

As far as i can see, the PR that implemented #1379 can also cope with synced lyrics (timestamps), it will just ignore the timestamps and store them as they were unsynced lyrics.

Can you please try to tag a file with lyrics in the USLT tag and see if that works?

**Comment by hboetes** [comment]
> The only thing that is supported currently, is reading unsynced lyrics (no timestamps) from tags. Lyrics in ID3 tags shouldn't go in a frame called "". The correct tag to use would be "USLT". See: https://docs.mp3tag.de/mapping/#unsyncedlyrics

Would this also apply to FLAC files? Currently I've set all lyrics in the custom LYRICS tag in my FLAC files, since I couldn't find any documentation about it.

**Comment by WatcherSaria** [comment]
> ".lrc" files are not (yet) supported, see #1421
> 
> The only thing that is supported currently, is reading unsynced lyrics (no timestamps) from tags. Lyrics in ID3 tags shouldn't go in a frame called "". The correct tag to use would be "USLT". See: https://docs.mp3tag.de/mapping/#unsyncedlyrics
> 
> As far as i can see, the PR that implemented #1379 can also cope with synced lyrics (timestamps), it will just ignore the timestamps and store them as they were unsynced lyrics.
> 
> Can you please try to tag a file with lyrics in the USLT tag and see if that works?

I just tried but "No Lyrics" still there. :-(

**Comment by ZhangTianrong** [comment]
I find the behaviors across files are pretty inconsistent. For example both files shown below are in FLAC format and has LYRICS in their metadata, but only the lyrics of the one on the left are correctly displayed in the Web UI and it says "No Lyrics" when it comes to the other one.
![image](https://user-images.githubusercontent.com/20651728/197371777-79db43f4-553d-48dd-8a74-51c06122f70e.png)

**Comment by LeoSum8** [comment]
Interesting! Thank you for sharing. 
Looks like the one on the left has some additional "declarations" before the first time-tag with actual lyrics appears.
Is there a general format specification for the lyrics tag, that is not fulfilled by the right example?

For me, I have only unsynced lyrics and I have not yet had a file for which navidrome displays the lyrics.

**Comment by stalemartyr** [comment]
For those who still wonder how lyrics in browser works, this is what I did.

- I managed to make this works by using LYRICS metadata. Tried USLT and SYLT but never works.
- The format of timestamp should always be [MM:SS.MS] i.e. [01:25.30] 
- Note that the ms should always be 2 decimal places. the format [01:25.30]  will work, [01:25.3] or [01:25.3032673] will not work
-  "No Lyrics" is showing because it is waiting for the timestamp... If you can, just add "[00:00.00] ♪" or any message so that you know lyrics will work at the beginning

**Comment by jixunmoe** [comment]
> I find the behaviors across files are pretty inconsistent. For example both files shown below are in FLAC format and has LYRICS in their metadata, but only the lyrics of the one on the left are correctly displayed in the Web UI and it says "No Lyrics" when it comes to the other one. ![image](https://user-images.githubusercontent.com/20651728/197371777-79db43f4-553d-48dd-8a74-51c06122f70e.png)

Timestamp needs to be in `[MM:SS.MS]` as what @stalemartyr said.

Here's the sed command to batch replace it:

```sh
sed -i.bak 's/\[([0-9]{2}:[0-9]{2}\.[0-9]{2})[0-9]+\]/[\1]/' *.lrc
```

**Comment by ERROR-404-NULL-NOT-FOUND** [comment]
Can someone make a script to mass-copy the USLT field data to LYRICS?

**Comment by mybuntu-git2** [comment]
Ok so I got this working. Sharing some info and how to do it.
USLT is a tag ID not a tag name. The name of the tag is lyrics.
The tool to understand what is going on best for me is eyeD3, which shows neatly all lyrics values.
Lyrics all have a language. If language =XXX, lyrics are saved as lyrics_XXX (this is what you will see with eyeD3).
You have to save in a language that Navi will understand.
I use beets in Linux to get my library in order, including lyrics. I download with spotdl.
My feeling is neither of those two works very well with lyrics.

EyeD3 is great but (afaik) it requires us to export lyrics to file, then import them again. That is …some I/O for a large library.

mass change using beets:
—beware if you use tekstowo and not use the last unstable version of beets, it will add “tekst piosenki” all across the place.

in the config you use for import, either add the full translation bing setup (not tested by me) or add just this:
lyrics:
    auto: yes
    fallback: ''
    force: yes
    bing_lang_to: 'eng'

Then when you import it will save the lyrics as lyrics_eng (without translating them)
I suggest to create a dedicated beets config file to fetch all tags only from file, force add only lyrics (section above), and write back to file the tags.

you can also use
beet -c ‘full/path/to/config.yaml’ lyrics ‘the/file/to/alter.mp3’
which will change the beets database tags.
To make the changes into the file you have to use afterwards command
beet write ‘the/file/to/alter.mp3’
You have to check the info with eyeD3 though, is much clearer than beet info .

**Comment by mybuntu-git2** [comment]
This is a sample config.yaml file that I use for beets import and library automatic reorganisation. All parts where you see REDACTED have to be adjusted appropriately.
you can follow the beets manual here: [http://docs.beets.io/en/v1.6.0/plugins/index.html](url)
Please note that just installing and running this, will move all _your files_ around according to how _I_ keep organized _my_ library!
I cannot support you in case something awful happens, so if you are new to beets, expect some time to set it up.

important: in the file I have set lyrics.force: no, set it to yes if you need to overwrite existing lyrics.

[lyrics_config.yaml.txt](https://github.com/navidrome/navidrome/files/13846876/lyrics_config.yaml.txt)

**Comment by mybuntu-git2** [comment]
I opened an issue on spotdl to have a default language there:
https://github.com/spotDL/spotify-downloader/issues/1996#issue-2068116335
An alternative I can think of is to enable the equivalent of opensubsonic’s https://opensubsonic.netlify.app/docs/responses/structuredlyrics/
with a default set by navidrome, then pass the result to the standard getlyrics subsonic call.

**Comment by mybuntu-git2** [comment]
**Full beets lyrics remove and refetch shell flow to fix whole library**

using beets 1.6.0 stable. Tested on Linux.
works around “tekst piosenki” issue with beets scraper on tekstowo, by removing tekstowo as a source.
I recognize, this will mostly be useful to those that already have a basic understanding of beets.
Please read all first and assess if you are comfortable doing this. If you have doubts, please copy a few songs and test the flow in a dedicated directory.
Information on how to install beets and set up plugins is not provided here, please check beets docs.


create a config_zero.yaml for beets to clear the whole lyrics tags of your library. You can copy the normal beets config.yaml under $BEETSDIR

in the config_zero.yaml this part has to be set to this to work with lyrics only:

```
zero:
   auto: yes
   fields: lyrics
   update_database: true
```
 
then run the zero command to clean the lyrics.

`beet -c /PATH/TO/YOUR/config_zero.yaml zero /PATH/TO/ROOT/FOLDER/OF/YOUR/MUSIC`

now adjust config to allow beets fetching.
Copy config.yaml to config_import.yaml
If misssing, add lyrics plugin (follow instructions on beets docs v. 1.6.0 if you don’t know how to).

the lyrics plugin will exclude tekstowo but I added a Google API key to increase hits.

His is how the lyrics section is set:

```
lyrics:
    auto: yes
    fallback: ''
    force: yes
    bing_lang_to: ‘eng’
    sources: google musixmatch genius
    google_API_key: REDACTED
```

`REDACTED`: you have to set up a Google search api key.
`‘eng’`: this is the default language you will record the lyrics to. Note that this is just a coding and has nothing to do with the actual language of the song.

then create a script beetlyrics_fillmissing.sh 

```
BEETSDIR=/YOUR/PATH/WHERE/CONFIG_IMPORT/IS
mynolyrics=$(beet list -p lyrics:'')
for i in "${mynolyrics[@]}";
do
beet -c "$BEETSDIR/config_import.yaml" lyrics -f "$i"
beet -c "$BEETSDIR/config_import.yaml" write"$i"
done
```
Make this executable
`chmod +x beetlyrics_fillmissing.sh` 
Then run it:
`sh beetlyrics_fillmissing.sh` 
This will iterate over files missing lyrics and write them to file and beets db.
Also, if you run normal beets import for new incoming songs, it will now write lyrics coding the language as ’eng’ if no other language is found.
**Note**:
consider that the free Google api has a daily limit of 100 calls so you may want to schedule this to run daily to retry misses. If all your songs will have lyrics, it will do nothing.

**Comment by mybuntu-git2** [comment]
The script above is not parallelised, meaning it uses up one thread for all operations, except `beet lyrics` which could spawn new threads (not sure if it does).
However due to “skips” subsequent iterations will be more and more fast.
What I really dislike is I did not find a proper way to replace the weird eyeD3 requirement for a lyrics file with an in-memory variable, so there is a lot of I/O that I would have preferred to avoid.

**Comment by mybuntu-git2** [comment]
@deluan just for my own clarity, do we have generic language encodings that Navidrome supports? (E.g. ‘zxx’, ‘mul’, …) What if we have lyrics stored separately in the same id3 tag for multiple languages, is there an order, or the order comes from the tag?

**Comment by Intrinsically-Sublime** [comment]
@mybuntu-git2 Have you submitted your formatting to beets for direct integration?

**Comment by mybuntu-git2** [comment]
> @mybuntu-git2 Have you submitted your formatting to beets for direct integration?

Well, it is debatable that they need to fix something, in the end beets saves the lyrics to the fallback xxx “language” as other similar tools do. The issue at hand (in my opinion) is that Navidrome returns empty lyrics in some cases and there is no way to trick that with env vars

**Comment by mybuntu-git2** [comment]
> The script above is not parallelised, meaning it uses up one thread for all operations, except `beet lyrics` which could spawn new threads (not sure if it does). However due to “skips” subsequent iterations will be more and more fast. What I really dislike is I did not find a proper way to replace the weird eyeD3 requirement for a lyrics file with an in-memory variable, so there is a lot of I/O that I would have preferred to avoid.

I worked around the I/O issue with a ramdisk
