### ISSUE TITLE
Random "database disk image is malformed"

### ISSUE THREAD

**Issue by deepsweet** [navidrome/navidrome#1843]
### Description

Hi.

I use Navidrome on "aarch64 ASUSWRT-Merlin" router architecture with Entware and see a lot of _random_ errors like this from time to time:

```
ERRO[0153] SQL: `UPDATE media_file SET album = ?, album_artist = ?, album_artist_id = ?, album_id = ?, artist = ?, artist_id = ?, bit_rate = ?, bpm = ?, catalog_num = ?, channels = ?, comment = ?, compilation = ?, disc_number = ?, disc_subtitle = ?, duration = ?, full_text = ?, genre = ?, has_cover_art = ?, id = ?, lyrics = ?, mbz_album_artist_id = ?, mbz_album_comment = ?, mbz_album_id = ?, mbz_album_type = ?, mbz_artist_id = ?, mbz_track_id = ?, order_album_artist_name = ?, order_album_name = ?, order_artist_name = ?, order_title = ?, path = ?, size = ?, sort_album_artist_name = ?, sort_album_name = ?, sort_artist_name = ?, sort_title = ?, suffix = ?, title = ?, track_number = ?, updated_at = ?, year = ? WHERE id = ?`  args="['Inner Landscapes','Robert Rich','b827ee3001c033770581897c59ebc292','4cd11045d5233192d3f7f4b0e1d92927','Robert Rich','b827ee3001c033770581897c59ebc292',292,0,'',2,'https://www.discogs.com/Robert-Rich-Inner-Landscapes/master/29022',false,0,'',522.89,' 8 inner landscapes part rich robert','',false,'94dbdb851e5f0677019011d94cdbfb93','','','','','','','','Robert Rich','Inner Landscapes','Robert Rich','Inner Landscapes Part 8','/mnt/sda2/music/Robert Rich - 1988 - Inner Landscapes [1999]/08 - Inner Landscapes Part 8.m4a',19106130,'','','','','m4a','Inner Landscapes Part 8',8,'2022-08-16T20:46:08+02:00',1988,'94dbdb851e5f0677019011d94cdbfb93']" elapsedTime="529.843µs" error="database disk image is malformed" rowsAffected=0
ERRO[0153] Error updating folder in the DB               dir="/mnt/sda2/music/Robert Rich - 1988 - Inner Landscapes [1999]" error="database disk image is malformed"
```

* Sometimes scan goes fine, sometimes it doesn't for many albums in a row, it's very unpredictable. But It _never_ happens if I just stop everything, wipe "DataFolder" and start over again with the same albums.
* `/mnt/sda2/` is USB hard drive connected to the router. The disk itself is healthy and doesn't have any read/write errors for sure.
* Happens with either `taglib` or `ffmpeg` extractors.
* All files are `.m4a` AAC@256 VBR.

Other than that it's working absolutely fine, just a bit annoying to wipe everything every time I need to update the library.

Would appreciate any thoughts and ideas.

### Expected Behaviour

No errors or at least less cryptic log.

### Steps to reproduce

Quick / Full scan from the web UI or just `navidrome scan ...` – doesn't really matter.

### Platform information

 - Navidrome version: v0.47.5
 - Browser and version: any
 - Operating System: Linux 4.1.27 / aarch64 ASUSWRT-Merlin router + Entware.

**Comment by deluan** [comment]
Hey @deepsweet , there was a lot of dependencies updates in the last release (0.48.0). Can you confirm this is still happening?

**Comment by deepsweet** [comment]
Sorry, I don't use Navidrome anymore and can't check if the issue is still there.

**Comment by limitlessbritt** [comment]
Hello @deluan, I'm currently experiencing this issue.

This happens every time I've tried to scan my music either quick or full. I've tried starting from scratch (deleting the datafolder) many times but it just seems to error out at random times. My music collection is very large. 
The database is stored on my NAS.

Because of this bug I can't use Navidrome at all. 

```
Thugs‐n‐Harmony - The Art of War - 16 - Hatin Nation.mp3',0,0,0,0,12865064,'Bone Thugs‐n‐Harmony','','','','mp3','Hatin Nation',16,'2021-10-04T01:47:34.498502732Z',1997]" elapsedTime=4.1ms error="database disk image is malformed" requestId=7b368691ac1a/bvl40XShmx-000031 rowsAffected=0 username=limitlessbritt
time="2023-02-12T02:47:22Z" level=error msg="Error updating folder in the DB" dir="/music/Bone Thugs‐n‐Harmony/The Art of War" error="database disk image is malformed"
```

Platform infomation:

- Navidrome 0.49.1 - Docker
- Operating System: Ubuntu Server

**Comment by limitlessbritt** [comment]
A little update, ended up trying to store the database on the servers drive itself and it worked! Downside is now I have to make a script so it backups to the NAS because that's where I wanted to store it originally. 

I think this bug has something to do with the database being stored on the NAS but my NAS is reporting no problems with the hard drives so I'm not sure the what issue could be. 

For now I'll just use the workaround.
