### ISSUE TITLE
Navidrome PWA causes Chrome lockups

### ISSUE THREAD

**Issue by djjudas21** [navidrome/navidrome#1847]
### Description

I've observed that all tabs in my Chrome browser intermittently freeze while Navidrome is also open (just open, not even playing) as a Chrome progressive web app which I've "installed" on my desktop. All tabs become frozen (you can't switch tabs or scroll or click on anything) for maybe 5 seconds, every minute or so. No errors are reported.

The freezes do not seem to occur if Navidrome is running in a regular Chrome tab, only if it's running as a PWA.

Navidrome is running in Kubernetes on a 3-node cluster, which is on the same LAN as my PC. Kubernetes nodes are i5 CPU and 16GB RAM and are not stressed.

PC System health is good, it's an 8-core Ryzen with 64GB RAM and the system is not stressed. CPU usage does not spike during the freezes.

### Expected Behaviour

I expect Navidrome running at idle not to interrupt other Chrome tabs.

### Steps to reproduce

1. Open Navidrome as a Progressive Web App
2. Start playing some music
3. Pause the music
4. Use Chrome normally, observe random freezes

### Platform information

 - Navidrome version: v0.47.5
 - Browser and version: Chrome v104.0.5112.79 (has been observed on older versions too)
 - Client Operating System: Fedora 36
 - Server Operating System: MicroK8s on Ubuntu 20.04

### Additional information

Any other information that may be relevant or give context to the problem.

 - Screenshots - I can provide screenshots of the PWA and even a video of the freezes if it would help
 - Logs
```
time="2022-08-25T10:51:46Z" level=info msg="Streaming file" artist="CHVRCHΞS" bitRate=0 cached=false format=raw originalBitRate=172 originalFormat=mp3 title=Graffiti transcoding=false user=jonathan
time="2022-08-25T10:51:46Z" level=info msg="Now Playing" artist="CHVRCHΞS" player="NavidromeUI [Chrome/Linux]" title=Graffiti user=jonathan
# I paused it here, and over the next few minutes I saw several freezes, but no log messages from the Navidrome server
```
I have no idea how PWAs work, I don't know if there is some debugger that might get some useful log messages? I'm happy to do whatever it takes to diagnose this, but I also have no idea about front end development.

My Navidrome instance is publicly exposed so I can make you an account if you need to use it etc.

**Comment by djjudas21** [comment]
It took me about 30 minutes to run into a freeze, but yes it does

**Comment by certuna** [comment]
That is odd. Does Chrome on Mac/Windows have this issue too? (can't test it right now, but I haven't noticed it with Edge)

**Comment by SteveDinn** [comment]
I've had the PWA open for literally weeks on Chrome on Windows and noticed nothing of this sort.

**Comment by SrIzan10** [comment]
Maybe chrome install being strange.

Can you try using a clean Chrom(ium) installation via this link? http://download-chromium.appspot.com/

**Comment by djjudas21** [comment]
Sorry for the delay getting back to you. Two more data points:

- I can recreate the same issue in Chrome on a different, unrelated Linux system within a few minutes of starting the PWA
- I can **not** recreate the issue in Chrome on Windows although this hasn't had much testing. I played music in the PWA and browsed Google/Wikipedia which is all I normally need to do to notice the lockups

**Comment by deluan** [comment]
Hey @djjudas21, did you try using other PWA apps? Is Navidrome freezing when opened as a normal tab in the browser?

> I can recreate the same issue in Chrome on a different, unrelated Linux system within a few minutes of starting the PWA
> I can not recreate the issue in Chrome on Windows

This seems to be related to Chrome on Linux. I use it on macOS without any issues as well....

**Comment by djjudas21** [comment]
* Navidrome does not freeze when opened as a normal tab (and this is my workaround)
* Other PWA apps do not freeze on Chrome on Linux (e.g. I also use PhotoPrism)
* It only occurs in Chrome on Linux. It is fine on Windows, and I don't have access to macOS
