### ISSUE TITLE
Read Sound Files over Webdav or Nextcloud

### ISSUE THREAD

**Issue by YourSandwich** [navidrome/navidrome#1849]
### Is your feature request related to a problem? Please describe.

1. You cannot choose other Music locations then local filesystem
2. Nextcloud encryption makes the Music unreadable on filesystem level, this would mean i need to copy my Terabytes of audio just to have in unencrypted.

### Describe the solution you'd like
Implement a way to read Music from cloud providors for exaple over Webdav.
Since its localy it gould go over websocket so it should be able to use full disk speed over LAN

A clear and concise description of what you would like to happen.
Implement webdav or native nextcloud capabilities to be able to load the Audiofiles from there 

### Describe alternative solutions that would also satisfy this problem
Maybe it would be possible to decrypt the files that are located on the local stoage, Nextcloud is working with a master-key, but i think this would makes think realy complicated for that edge case scenario

**Comment by tralph3** [comment]
I would love to have WebDAV support! It would be a very elegant solution. That way I can use Nextcloud to sync my music across devices, and at the same time have a nice music player to listen to it.

I guess I could achieve this same thing by adding a WebDAV mount point on the Navidrome container, but that's going to get removed when I recreate it, so I would need to make my own image. It's just cumbersome. Dedicated env vars on the official Docker image, or even better, adding it as part of the settings UI would be awesome.

**Comment by palijn** [comment]
Can't you just use [https://github.com/efrecon/docker-webdav-client ](https://github.com/efrecon/docker-webdav-client )to make the webdav contents available to the navidrome container transparently in a regular mountpoint ?

**Comment by YourSandwich** [comment]
I used davfs2, it is able to mount WebDav locally, but unfortunately it seemed very slow.

I found a workaround now, I am able to just leave my Music unencrypted and bind the folder to an NFS Share.

**Comment by chrisdong** [comment]
+1 for webdav support.

**Comment by mitexleo** [comment]
+1

**Comment by thomasdba** [comment]
This should be a cool feature ,nice to have .
