### ISSUE TITLE
Expose replaygain tags

### ISSUE THREAD

**Issue by CorePoint** [navidrome/navidrome#1850]
Hey,

I know that replaygain support in general is an already requested feature.
But it would be great if replaygain tags could be exposed to just start somewhere.

The dev of Symfonium seems to be [open about supporting](https://support.symfonium.app/t/replaygain-support/265/3) it if the tags are exposed (as far as I know the local part of the app already supports it anyway).

That would at least give us one setup constellation consisting of two popular projects, it maybe also could kick-start the whole thing.

Thanks for your work!

**Comment by deluan** [comment]
Hey @CorePoint , I've been discussing with @tolriq (and others) about extending the Subsonic API, and then this will be possible. For now, the only way for Subsonic clients to get RG info is by extracting the tags from the files themselves.

I'm closing this as it is not something we can change right now. Feel free to raise any other concerns.

**Comment by CorePoint** [comment]
@deluan
Thanks for letting me know, expanding the Subsonic API this sounds like a great effort!

Also thanks for being so proactive, with contacting the Symfonium dev!
When I created the issue, the only thing i could find was [this](http://support.symfonium.app/t/replaygain-support/265/4) but without the edit.
I later saw the edit but thought the issue was still relevant so I left it open.
Should have let everybody know here that it's possible though, so thanks for doing that.
