### ISSUE TITLE
OBS overlay

### ISSUE THREAD

**Issue by SrIzan10** [navidrome/navidrome#1852]
### Is your feature request related to a problem? Please describe.

I'm playing music on my streams, and I want to show what song is playing.

### Describe the solution you'd like

Have some URL that can be used as a browser Overlay on obs

### Additional context

Im moving from spotify

**Comment by juddisjudd** [comment]
This is more of something that would be more of a plugin/utility for OBS rather than building in Navidrome.

Look into Snip or something of the sort for OBS
