### ISSUE TITLE
Group different release types together in artist profile page

### ISSUE THREAD

**Issue by raudraido** [navidrome/navidrome#1853]
Right now all different release types in artist page are mixed together like that

![image](https://user-images.githubusercontent.com/31039697/187194246-8e6685f5-4f92-4c9f-a92d-c6ccc4e778cd.png)

Should be in groups as albums, compilations, singles etc.

**Comment by certuna** [comment]
Duplicate of https://github.com/navidrome/navidrome/issues/369
