### ISSUE TITLE
Make "Shuffle All" be able to create and play list of more than 200 tracks

### ISSUE THREAD

**Issue by bhankas** [navidrome/navidrome#1856]
My music library has 2000+ tracks, and I like pretty much all of them. My usual strategy with ecery music player so far has been to simply "Shuffle All" over entire library. This works well, I get a decent coverage over entire library without getting much repetitiveness.

I was glad to see Navidrome allows "Shuffle All" in the Songs menu and have been using this feature ever since. However, despite any number of tracks available in the library, the resulting playlist generated after clicking "Shuffle All" always ends up with 200 tracks.

If, depending on mood, I end up skipping multiple songs, eventually the list ends up being repetitive.

### Describe the solution you'd like

After clicking "Shuffle All" the resulting shuffled playlist should have entire library instead of just 200 tracks.

### Describe alternative solutions that would also satisfy this problem

Cannot think of alternative, but open to suggestion.

### Additional context

![image](https://user-images.githubusercontent.com/24254289/187438783-9988b28d-4c6d-422d-a95b-553a4943e365.png)

**Comment by dtypo** [comment]
+1 !
