### ISSUE TITLE
Nested or grouped playlists

### ISSUE THREAD

**Issue by guiltlab** [navidrome/navidrome#1858]
I'm just trying out Navidrome and it's pretty great so far!

It would be useful if we could create collapsible groups of playlists, for example I have a dozen jazz playlists I'd like to put under Jazz group, stoner/hard/pop rock under Rock group, etc...
![Foo_plorg 1](https://user-images.githubusercontent.com/45518224/187930112-c84c8e91-a7ae-4319-9b44-87fb5779b980.png)

Basically, a feature similar to what this component for foobar2000 achieves: https://wiki.hydrogenaud.io/index.php?title=Foobar2000:Components/Playlist_Organizer_%28foo_plorg%29

Thanks for considering it!

**Comment by DanielNautre** [comment]
I would also like to see playlist folders added. This is espacially useful for those of us who have large playlist collections as the current UI is not well suited for that. Here is a example how that looks like in Musicbee:
![image](https://user-images.githubusercontent.com/2039600/210135138-ee0d0029-6e42-4180-8d37-62d692597c56.png)

One possible way of handling this would be to use the folder structure under the playlist folder, this seems like the most natural way of dealing with it, it's human readable and avoids reinventing the wheel.
Currently, that's how Musicbee handles it. I can't speak for other softwares

**Comment by nagarrido** [comment]
I would also love this feature. It's a mess to keep my playlists in order without folders

**Comment by nagarrido** [comment]
Any news on this feature?

**Comment by laker-93** [comment]
I would also love to see this feature added. Happy to help implement it if you could give me some pointers of where to start! I've checked out the code and built it locally.
I see the UI logic for creating a playlist is mainly here: `navidrome/ui/src/dialogs/AddToPlaylistDialog.js`.

Perhaps for an initial basic implementation, can create a pair of functions `createAndAddToPlaylistGroup` and `addToPlaylistGroup` analogous to`createAndAddToPlaylist` and `addToPlaylist`. First it creates a Playlist Group and then gives the user the option to create and add to a playlist that will then be added to the host group.

Design for being able to dynamically re arrange playlists in to groups will need a bit more thought...

**Comment by certuna** [comment]
I think this will probably have to wait (like many web UI features) until the migration to ReactAdmin v4.

**Comment by rizzlebap** [comment]
Just adding to this, would really love this feature. 

Is there any indication to when the migration to ReactAdmin v4 will happen?
