### ISSUE TITLE
Add option to choose if the lyrics should be stripped of sync annotations, if present

### ISSUE THREAD

**Issue by gandbg** [navidrome/navidrome#1867]
### Is your feature request related to a problem? Please describe.

When a client requests the song lyrics thru the Subsonic API, Navidrome removes any kind of sync annotation

### Describe the solution you'd like

It'll be cool to have a configuration option to choose this behavior (if to remove the sync annotation or not)

### Additional context

I've coded a potential implementation of this feature: [5b907a8](https://github.com/gandbg/navidrome/commit/5b907a8414ebc4392d98fe489210a4916eb0e26f). If this is a desired feature i can open a pull request from the fork.

I should also note that i actually don't know how to code in Go: I've looked at the syntax and figured things out, so please excuse me if it's coded poorly 😄

**Comment by deluan** [comment]
Thanks for the suggestion and sorry for the long delay.

I think a better implementation would be to have a config for each player,
as the majority of subsonic clients do not support synchronized lyrics. A
config similar to "Report Real Path" in the Players page.

What do you think?

**Comment by gandbg** [comment]
Yeah, that makes much more sense. Considering the general lack of support for synchronized lyrics this might be an option disabled by default.
