### ISSUE TITLE
Incorrect release dates for some albums

### ISSUE THREAD

**Issue by jonleopard** [navidrome/navidrome#1868]
### Description

Navidrome is pulling incorrect release dates for some albums. I'm not sure where its getting the date values? I've confirmed that the dates are correct over at musicbrainz. Happy to provide more details if needed. 

### Platform information

Navidrome in Docker (latest tag) on Ubuntu 20.04.5 LTS

Here are  some screenshots:

<img width="1223" alt="Screen Shot 2022-09-09 at 12 45 41" src="https://user-images.githubusercontent.com/2111234/189431711-439fb815-0b2b-4993-95fb-ca3c2651c615.png">

You  can see here that there are multiple albums released in '97, 2013 and 2015. These are all incorrect. 
<img width="1144" alt="Screen Shot 2022-09-10 at 09 37 36" src="https://user-images.githubusercontent.com/2111234/189493043-5075e5d8-9dea-4fa2-b57a-78d707f50cc6.png">

Here's the directory located on my NAS:
<img width="1209" alt="Screen Shot 2022-09-09 at 12 45 57" src="https://user-images.githubusercontent.com/2111234/189431778-bd9b08f2-660f-412d-920a-0996e900f6ba.png">

<img width="1081" alt="Screen Shot 2022-09-09 at 12 47 53" src="https://user-images.githubusercontent.com/2111234/189431859-02d88561-efa8-4975-9a95-90fe20956376.png">

**Comment by certuna** [comment]
what do the tags say?

**Comment by jonleopard** [comment]
Hmm, the tag is wrong but I am not sure where it is picking up that value from? This album was released in 1985.

<img width="939" alt="Screen Shot 2022-10-12 at 17 07 47" src="https://user-images.githubusercontent.com/2111234/195469886-8bcae550-f983-42bd-b808-f958e95e424a.png">

**Comment by jonleopard** [comment]
@certuna Where can I find this information?

**Comment by jonleopard** [comment]
Oddly enough, Plexamp is picking up the correct release date info. So perhaps this is an issue with musicbrainz?

**Comment by deluan** [comment]
This will most probably be fixed by #2162, right @certuna ?

**Comment by certuna** [comment]
Probably, but I don't think we've seen what the tags in @jonleopard 's file contained?
