### ISSUE TITLE
Allow removing tracks from a playlist / inconsistent add to playlist for tracks

### ISSUE THREAD

**Issue by tarneaux** [navidrome/navidrome#1871]
### Is your feature request related to a problem? Please describe.

I just found myself in a situation where I had the same track multiple times in a playlist. I wanted to remove one of the two but didn't find how to do that.
it's also strange that you can't just add a song to a playlist using a button instead of the current check boxes.

### Describe the solution you'd like

Just a cross in the playlist interface on the track description, like in the queue interface.

For adding a song to a playlist, just provide a button for each playlist instead of a menu that opens (it's really dumb to have that type of menu on a PC monitor:
![example](https://user-images.githubusercontent.com/62650051/189983534-2743a6f2-c15e-4a27-8a3b-04867e5ce9bc.png)
Here, it is just a bit dumb: you have to check the playlist name, then either click on the green button you can slightly see behind the dialog or first close the menu before clicking it.
I'd want something like this:
![bad](https://user-images.githubusercontent.com/62650051/189984894-0ceab8af-1811-4635-b273-a42bccc7f090.png)
(There should be some way to let the user know the song has been added, like closing the dialog or showing a little check mark right beside the text)

### Describe alternative solutions that would also satisfy this problem

- in the "add to playlist" dialog for a track, just save the track as"in the playlist" or "not in the playlist" instead of "add it" or "don't add it" (similar to youtube). However that wouldn't be perfect without the cross because it would still be hard to remove a track quickly;
- when checking tracks in a playlist, add "remove from playlist" to the possible actions.

**Comment by deluan** [comment]
For removing tracks, it is already possible to select multiple tracks to be removed:

https://user-images.githubusercontent.com/331353/224734705-5814e36c-9b11-4927-b27c-e154e8e022e0.mov

Re: adding, your suggestion would work for a limited number of playlists. Some users have hundreds of playlists, and having a way to find/filter it by name is important. Besides, the number of clicks would be the same as the current solution, and "showing a little check mark right beside the text" is basically what we have now with the checkboxes. Unless I'm misinterpreting your suggestions, I don't see how it would be better than the current solution.

**Comment by tarneaux** [comment]
@deluan Apparently navidrome has come a long way since I last used it. Seems like all the missing features now exist.
Closing.
