### ISSUE TITLE
Cannot play some mp3 files no error in logs

### ISSUE THREAD

**Issue by greatbody** [navidrome/navidrome#1872]
### Description

Cannot play mp3 file.

### Expected Behaviour

Can play mp3 file.

### Steps to reproduce

1. Copy mp3 file to music folder
2. Can find it in list
3. click it
4. Not playing

### Platform information

 - Navidrome version: 0.47.5 (86fe1e3b)
 - Browser and version: Chrome (Version 105.0.5195.102 (Official Build) (x86_64))
 - Operating System: Ubuntu

### Not all mp3 failed, so I attach this sample which cannot be played

[music.mp3.zip](https://github.com/navidrome/navidrome/files/9572590/music.mp3.zip)

**Comment by metalheim** [comment]
ffmpeg (which is used in the background of navidrome) chokes on this file.

Could you please create an issue at ffmpeg itself? Maybe its a broken file, maybe its a bug in ffmpeg. They would know.

**Comment by deluan** [comment]
The file is actually a `mp2` file:

```
Input #0, mp3, from 'music.mp3':
  Metadata:
    artist          : 贝多芬
    album           : 贝多芬经典交响乐
  Duration: 00:07:12.41, start: 0.000000, bitrate: 160 kb/s
  Stream #0:0: Audio: mp2, 44100 Hz, stereo, fltp, 160 kb/s.  <-------------
  ```

and is not playable in the browser (try opening it in Chrome). 

`ffmpeg` is used in Navidrome only when transcoding, and it can actually read this file, so my suggestion is convert the files manually, or configure Navidrome to transcode it for you on demand. You could transcode it to Opus 128, which should be good enough to keep the audio quality of the original.

Besides this there's nothing much Navidrome can do, so I'm closing this now but feel free to reopen if you have any other concerns.

**Comment by greatbody** [comment]
Thanks for the feedback, just noticed that this file is actuailly mp2 file.
