### ISSUE TITLE
Navigation bug with Lyrics overlay

### ISSUE THREAD

**Issue by koehntopp** [navidrome/navidrome#1875]
### Description

Ui items in the vertical equivalent of the lyrics 'window' are not reachable

### Expected Behaviour

Make sure the lyrics canvas does not cover important navigation items such as tracks or pages.

### Steps to reproduce

Steps to reproduce:
- search albums for something with a multiple page result
- play one of the albums in the search result
- activate lyrics
- try to navigate to the next page of search results

Alternatively:
- play an album with many tracks
- activate lyrics
- try to play the track in the same line as the lyrics

### Platform information

 - Navidrome version: Current
 - Browser and version: Chrome
 - Operating System: MacOS

### Additional information

Any other information that may be relevant or give context to the problem.

 - Screenshots (if applicable)?
 - Logs? 
 - Client used?

**Comment by LeoSum8** [comment]
Interesting to see that lyrics display is working at all for you (not the case for all of us, #1840).

Could you give some details on your setup and the tags you are using? I'd gladly supply input to this issue here then :)

**Comment by koehntopp** [comment]
> Interesting to see that lyrics display is working at all for you (not the case for all of us, #1840).
> 
> Could you give some details on your setup and the tags you are using? I'd gladly supply input to this issue here then :)

Nothing special - using Yate on MacOS to tag files.

FLAC tag is called "Lyrics"

**Comment by deluan** [comment]
Hey @koehntopp , sorry for the delay. Can you show a screenshot of the issue (I don't have lyrics in my library :P ) 

If this is a quick fix that can be applied to Navidrome's own codebase, I can try to fix it. If this is something in the player, then we will have to wait for when we replace it with our own implementation

**Comment by koehntopp** [comment]
No worries, it's not *that* much of a problem. You don't even need lyrics.

Unfortunately I can't screenshot the issue - it's not actual graphics overlaying, it's probably the window.

![image](https://github.com/navidrome/navidrome/assets/7113567/a0a00916-e77d-48a4-a1aa-a47d3ddf465c)

To reproduce, go to a page with navigation and click the lyrics button. 
If you now try to click the navigation the cursor is a "move window" one (4 arrows) and doesn't click.
I just saw that you can even use that to move the lyrics overlay, the the buttons are accessible again.
So it's mostly about the defualt position of the lyrics layer, which should end above the navigation.

**Comment by deluan** [comment]
Ah I see. Well, as I said, I think the best course of action here is to wait for our own implementation as this is not a _blocking_ issue.
