### ISSUE TITLE
Allow automatic creation of an initial user/admin

### ISSUE THREAD

**Issue by max-tet** [navidrome/navidrome#1885]
Right now, when accessing the Navidrome UI for the first time, there is a registration screen, even if using reverse proxy authentication.
In some deployment settings, this is awkward. In particular, this prevents a comfortable fully automated one-click install like on [Portal](https://docs.getportal.org/).

It would be great, if we could provide the username of the initial admin as an environment variable. E.g.

* LD_SUPERUSER_NAME
* LD_SUPERUSER_PASSWORD

The second variable could be optional. If omitted, no password would be set and the user can only be authenticated with proxy authentication.

**Comment by deluan** [comment]
Hey @max-tet , before I tell you how to do it, keep in mind that the password in this case will be visible in the config file, which may not be a great thing to do security-wise. 

There's an undocumented flag, `DevAutoCreateAdminPassword = "password"` that you can put in the config file or as an env var `ND_DEVAUTOCREATEADMINPASSWORD`. When ND is starting and there are no users created, if it finds this flag in the config it creates an `"admin"` user, with the specified password. 

Is this what you are looking for?

**Comment by max-tet** [comment]
Great, thank you!
I believe option 1 should be good. It doesn't matter if the password is known in my case, since authentication is done by a reverse proxy anyway. Getting rid of any login/registration is the only goal here.
I'll try it later today and tell you how it went.

**Comment by max-tet** [comment]
Alright, just tested it and it works wonderfully. Thanks for your help!

**Comment by bencinium** [comment]
Im having the same issue, i never got the create account screen. I tried the above step listed by deluan, but my credentials i set dont work.
