### ISSUE TITLE
新版啥时候发布？

### ISSUE THREAD

**Issue by jiaoting** [navidrome/navidrome#1887]
就是想问问，新版啥时候发布？半年没有新版了

**Comment by Vista2003** [comment]
Please use English for these GitHub Issues as most people here don't understand Chinese.

**Comment by Vista2003** [comment]
Please use English for these GitHub Issues as most people here don't understand Chinese.

由于這裏的大多數人不明白中文，所以請用英文來表述這些GitHub問題。

OP is asking when the new version will be released.

**Comment by deluan** [comment]
I'm reviewing some PRs and plan to release a new version in the next few days.

**Comment by jiaoting** [comment]
> Please use English for these GitHub Issues as most people here don't understand Chinese.
> 
> 由于這裏的大多數人不明白中文，所以請用英文來表述這些GitHub問題。
> 
> OP is asking when the new version will be released.

在一堆英文里，突然有个中文，不是很明显嘛哈哈哈，其实就是为了催更哈哈哈哈
