### ISSUE TITLE
Can't scroll play queue on mobile web

### ISSUE THREAD

**Issue by SteveDinn** [navidrome/navidrome#1893]
### Description

The play queue allows the user to reorder the songs.  This is great in the desktop web, where a scroll can be accomplished with a mouse wheel or touch pad gesture or grabbing the scroll bar, but in the mobile web, each swipe picks up a track and moves it rather than scrolling the play queue's view. On Chrome the scroll bar seems impossible to grab, and on Firefox the scroll bar is not visible.

### Expected Behaviour

Allow up/down swipes to scroll the play queue's view. Tap & hold would enable reordering the held-on track.

### Steps to reproduce

1. Open the web client on a mobile device.
2. Add sufficient tracks to the play queue such that the play queue's view should be scrollable.
3. Attempt to scroll the play queue's view.
4. See that the track that was touched is moved instead of the view being scrolled.

### Platform information

 - Navidrome version: 0.47.5 (86fe1e3b)
 - Browser and version: Chrome 105.0.5195.136, Firefox 97.1.0
 - Operating System: Android 12 (LG Velvet)

**Comment by deluan** [comment]
Yeah, another reason to replace the player with something else, as the author stopped maintaining it....
