### ISSUE TITLE
Send plain http keepalive messages at a regular interval from client to server

### ISSUE THREAD

**Issue by max-tet** [navidrome/navidrome#1908]
### Is your feature request related to a problem? Please describe.

On Portal, an app shuts down after a period of inactivity, i.e. when no requests are received.

### Describe the solution you'd like

Send plain http keepalive messages at a regular interval to keep the app running as long as a client is connected.

### Describe alternative solutions that would also satisfy this problem

Perhaps the Traefik proxy can somehow detect the messages from the Server Event connection. But I have not found a way.

### Additional context

This feature is mainly for improving integration in [Portal](https://getportal.org/). Priority is not high, the app is still very usable without it.

**Comment by deluan** [comment]
With the Activity Panel enabled (default), there is always a persistent (Server-Side Events) connection between the server and any web clients. Isn't this enough?

**Comment by max-tet** [comment]
I've been using Navidrome on Portal for a while now and it works great. Seems to be enough.

I haven't analyzed it but I suspect that the SSE are *not* picked up by Traefik, thus Navidrome is shut down regularly but then immediately started again by the client which makes some retry request upon connection loss. Thanks to quick startup times, the client-side buffer is able hide this and playback is not interrupted.
Again, pure conjecture.

In any way, no further action seems to be needed.
