### ISSUE TITLE
Clicking 'Get Info' from an Album listed by an Artist under Artists hangs

### ISSUE THREAD

**Issue by K4r0qtuYNE5G4qgZ** [navidrome/navidrome#1909]
### Description

Clicking 'Get Info' from an Album listed by an Artist under Artists hangs and the Info Page is only displayed on entering the Album or entering other pages. The Info Page that then comes also has empty fields and looks a bit different as the other opened from Album List

### Expected Behaviour

The Info Page for that Album displayed correctly like when you call it up from the Album List.

### Steps to reproduce

1. Open the Artists Page
2. Open some Artist with some Albums listed
3. Click ⋮ on one of the Albums
4. Click 'Get Info'
5. See error

### Platform information

 - Navidrome version: 0.47.5 (86fe1e3b)
 - Browser and version: Chrome 105.0.5195.127 (Official Build) (64-bit)
 - Operating System: Ubuntu 20.04
 
### Additional information

Get Info opened from an Album listed by an Artist under Artists(only shows when entering other pages):
![image](https://user-images.githubusercontent.com/5566460/193750038-6aac6bec-fd70-4d32-906c-933cc0899533.png)

Get Info opened from the album list:
![image](https://user-images.githubusercontent.com/5566460/193750434-8b532934-6601-4891-be1c-5a34402677ab.png)

**Comment by deluan** [comment]
Thanks for catching this. Will be fixed in the (soon to be released) next version.
