### ISSUE TITLE
MPC Musepack files are recognized and listed correctly but they aren't played and are loading forever

### ISSUE THREAD

**Issue by K4r0qtuYNE5G4qgZ** [navidrome/navidrome#1910]
### Description

MPC Musepack files are recognized and listed correctly but they aren't played and are loading forever.

### Expected Behaviour

MPC Musepack files loaded and played correcly

### Steps to reproduce

1. Upload an album of the MPC files
2. Open album in the Navidrome web interface
3. Try to play a song

### Platform information

 - Navidrome version: 0.47.5 (86fe1e3b)
 - Browser and version: Chrome 105.0.5195.127 (Official Build) (64-bit)
 - Operating System: Ubuntu 20.04
 
### Additional information

MPC Musepack files are recognized and displayed as such:
![image](https://user-images.githubusercontent.com/5566460/193753269-476cd955-7d76-4aab-b209-b302f560387d.png)

But trying to play them results in this endlessly:
![image](https://user-images.githubusercontent.com/5566460/193753851-6cd62444-524e-4574-a825-cc2e65d39fc2.png)

MediaInfo from one of those files:
![image](https://user-images.githubusercontent.com/5566460/193754695-235098f2-2cda-4f48-b989-955525ba424b.png)

**Comment by metalheim** [comment]
I guess that is because your browser (probably any browser) doesn't support musepack playback.

This is a case where navidrome would need to transcode to a compatible format on-the-fly. Which Navidrome can do, but you can enable it only per-player. This enables transcoding for all files or none.
Theres a ticket about improving it: #351

**Comment by deluan** [comment]
Closing as this is not a Navidrome issue, as explained by @metalheim. Transcoding is the only way to play these non-popular audio formats in the browser.
