### ISSUE TITLE
Embedded Cover not loaded from APEv2 Tagged Files

### ISSUE THREAD

**Issue by K4r0qtuYNE5G4qgZ** [navidrome/navidrome#1911]
### Description

Embedded Cover is not loaded from APEv2 Tagged Files

### Expected Behaviour

The Embedded Cover being loaded from APEv2 Tagged Files

### Steps to reproduce

1. Upload an album with some APEv2 Tagged Files containing a cover
2. Open album in the Navidrome web interface
3. See error

### Platform information

 - Navidrome version: 0.47.5 (86fe1e3b)
 - Browser and version: Chrome 105.0.5195.127 (Official Build) (64-bit)
 - Operating System: Ubuntu 20.04
 
### Additional information

MP3Tag showing embedded Cover:
![image](https://user-images.githubusercontent.com/5566460/193757542-edf33728-1edd-4892-91f7-5297e7b99c16.png)

Navidrome didn't load Cover from APEv2 Tag:
![image](https://user-images.githubusercontent.com/5566460/193757117-ba73d257-6315-4b2b-b4db-60b0f565299c.png)

**Comment by deluan** [comment]
Thanks for opening this. Can you send me one sample file for analysis? I'm pretty sure the [lib](https://github.com/dhowden/tag) we use to extract coverart does not support this.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
APEv2 Specs:
https://mutagen-specs.readthedocs.io/en/latest/apev2/apev2.html
https://wiki.hydrogenaud.io/index.php?title=APEv2_specification
https://wiki.hydrogenaud.io/index.php?title=APEv2
https://mutagen.readthedocs.io/en/latest/api/ape.html

APEv2 Sample File with embedded Cover
(Zipped PW=navidrome1234)
https://file.io/4Z2aICwbskxK (Expires on DL)
https://filebin.net/8d4lfajpap1hbgm4 (Expires in 6 days)
https://we.tl/t-bvXbGAWntp (Expires in 7 days)

**Comment by K4r0qtuYNE5G4qgZ** [comment]
As you can see in #1930 this also happens with .ape files and isn't ,mpc files specific.

**Comment by deluan** [comment]
Sorry, but I failed to download the samples in time, can you please reupload? But before that, Navidrome now uses `ffmpeg` as a fallback to extract covers, maybe it is working now for you? Can you please try with latest version 0.49.3?

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Uhh that was last year and way too late now. And because I now per default convert all APE's to FLAC to avoid such issues I don't have any APE files anymore to upload any samples. But I then gonna test v0.49.3 (still on v0.48.0 currently) as soon I finished re-tagging, which should be the case in about 2-3 weeks.

But what I perhaps still gonna encounter is .MP3 Files with APEv2 Tags on them, which is a bug btw. and not supported anyway.
The same also for FLAC with MP3 tags, this isn't allowed and I wonder which tagger produced them.
If I encounter a such one I can send you a sample lol
