### ISSUE TITLE
Improve fake filename generation

### ISSUE THREAD

**Issue by Tolriq** [navidrome/navidrome#1912]
Navidrome by default does not return real filenames in it's API but fake generated ones Artist/Album/Song

Unfortunately the song part does not take in account the track number, leading to duplicate values when an album have multiple tracks with the same name. (More common than I expected seing the support I get from that).

Users can enable the report real filename option, but it's hard to find and duplicate filenames side effects are not obvious to figure out for them.

Would be nice if at least track number could be added to the song name as prefix to solve this even in default mode.

**Comment by deluan** [comment]
I'll take a look at that, thanks for reporting.

**Comment by Tolriq** [comment]
@deluan small bump as I see you are active :)
