### ISSUE TITLE
希望新增功能

### ISSUE THREAD

**Issue by renshinizhenhao** [navidrome/navidrome#1913]
现在一首歌曲添加到自己创建的播放列表，可以一首歌曲重复的添加。望改进！同一首希望只能在列表里面出现一个。

还有能不能禁止其他用户下载歌曲

能不能添加游客自己注册用户，管理员审核通过可以登陆

望回复  476599224@qq.com

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Google Translate of it for Convenience:
> Hope for new features #1913
> 
> Now add a song to the playlist created by yourself, you can add a song repeatedly. Hope to improve! The same song can only appear in one list.
> 
> Is it possible to block other users from downloading songs?
> 
> Can you add a registered user by yourself, the administrator can log in after the approval
> 
> Hope to reply 476599224@qq.com

**Comment by deluan** [comment]
Sorry for the delay in answering this.

> Now add a song to the playlist created by yourself, you can add a song repeatedly. Hope to improve! The same song can only appear in one list.

When adding a repeated song to a playlist, Navidrome now asks if it is ok to add the song again, and you have the option to cancel it. Playlists CAN have the same song more than once.
> 
> Is it possible to block other users from downloading songs?

You can disable downloads completely by setting `ND_ENABLEDOWNLOADS` (or EnableDownloads) to `false`

> 
> Can you add a registered user by yourself, the administrator can log in after the approval

That's not possible. Navidrome is a personal server, it was not meant to be a public service.

Let me know if you have more questions.
