### ISSUE TITLE
Navidrome export playlist to m3u from command line option

### ISSUE THREAD

**Issue by swimminsparrow** [navidrome/navidrome#1914]
Hi, is there any way to export a playlist to a m3u file from the terminal? Something like that
navidrome -c CONFIG_FILE --export-playlist PLAYLISTNAME.

I'm doing a bash script to sync spotify playlist and navidrome ones. 
Thanks.

**Comment by deluan** [comment]
That's a great idea! Thanks for the suggestion!

**Comment by Crazy-Ginger** [comment]
Having this feature somewhere in the UI would also be really useful for people running their servers in docker containers

**Comment by deluan** [comment]
> Having this feature somewhere in the UI would also be really useful for people running their servers in docker containers

Like this? :)
<img width="968" alt="Screen Shot 2022-12-21 at 12 52 19 PM" src="https://user-images.githubusercontent.com/331353/208971829-60464b84-0dd3-48bb-9c5f-d4179adbdb91.png">

**Comment by deluan** [comment]
Done:

```
$ navidrome pls --help
Export Navidrome playlists to M3U files

Usage:
  navidrome pls [flags]

Flags:
  -h, --help              help for pls
  -o, --output string     output file (default stdout)
  -p, --playlist string   playlist name or ID

Global Flags:
  -c, --configfile string    config file (default "./navidrome.toml")
      --datafolder string    folder to store application data (DB, cache...), needs write access (default ".")
  -l, --loglevel string      log level, possible values: error, info, debug, trace (default "info")
      --musicfolder string   folder where your music is stored (default "music")
  -n, --nobanner             don't show banner
```

Note that the `-p` argument can be both the name (case-sensitive) or the ID (as seen in the URLs in the UI). To make sure you don't get any extra info (logs, banner, etc...) in the `stderr`, call it like this:

```
navidrome pls -n -l error -p "cb692017-6883-4e77-b10a-410b1d8c065d" -o out.m3u
```

**Comment by swimminsparrow** [comment]
> Done:
> 
> ```
> $ navidrome pls --help
> Export Navidrome playlists to M3U files
> 
> Usage:
>   navidrome pls [flags]
> 
> Flags:
>   -h, --help              help for pls
>   -o, --output string     output file (default stdout)
>   -p, --playlist string   playlist name or ID
> 
> Global Flags:
>   -c, --configfile string    config file (default "./navidrome.toml")
>       --datafolder string    folder to store application data (DB, cache...), needs write access (default ".")
>   -l, --loglevel string      log level, possible values: error, info, debug, trace (default "info")
>       --musicfolder string   folder where your music is stored (default "music")
>   -n, --nobanner             don't show banner
> ```
> 
> Note that the `-p` argument can be both the name (case-sensitive) or the ID (as seen in the URLs in the UI). To make sure you don't get any extra info (logs, banner, etc...) in the `stderr`, call it like this:
> 
> ```
> $ navidrome pls -n -l error -p "cb692017-6883-4e77-b10a-410b1d8c065d" -o out.m3u
> ```


(GREAT JOB)²!
