### ISSUE TITLE
Purge all non-existent entries within the web UI (administrator)

### ISSUE THREAD

**Issue by HubKing** [navidrome/navidrome#1922]
### Is your feature request related to a problem? Please describe.

It seems that non-existing entries (files that previously existed but now has been deleted) still show up in the web player UI. I mean, the files are not listed but the albums show up in the Albums, and the singers in the Artists. There seems no menu like "Delete". Clicking "Refresh" or "full/partial scan" (even as the administrator) does not remove them either.

### Describe the solution you'd like

There should be some sort of "Remove all non-existent entries" menu. Or, at least, manually deleting selected non-existent entries. 

### Describe alternative solutions that would also satisfy this problem

Deleting the DB files of course removes all of them, but it also deletes all other settings like user accounts, and it is not convenient.

### Additional context

Version: 0.47.5 (86fe1e3b)

**Comment by deluan** [comment]
This seems to be related to this issue: https://github.com/navidrome/navidrome/issues/937#issuecomment-1257089106

Can you please confirm?

**Comment by HubKing** [comment]
Yeah, I think I had put some music files to the music directory for testing without creating a sub directory. If it is "a known bug", then this problem (lingering albums, etc after the files are gone) does not exist if put in subdirectories? Then, I think this request is not needed.
