### ISSUE TITLE
Swallows up to a second at the end of each track. Displayed length in Navidrome does not match the file either.

### ISSUE THREAD

**Issue by K4r0qtuYNE5G4qgZ** [navidrome/navidrome#1926]
### Description

Swallows up to a second at the end of each track (audible) before switching to another.
The displayed length in Navidrome also does not match the file lenghts.

### Expected Behaviour

The files/tracks should be played completely before switching to the next file/track.
The displayed length in Navidrome should be rouned correctly.

### Steps to reproduce

1. Open an album with many Tracks
2. Compare the lenghts in Navidrome with the lenghts o the Files
or
1. Open an album with many Tracks (best are such ones that fade out at the end)
2. Play Tracks and skip to 5-10 sec before end and listen the switch to next Track

### Platform information

 - Navidrome version: 0.47.5 (86fe1e3b)
 - Browser and version: Chrome 105.0.5195.127 (Official Build) (64-bit)
 - Operating System: Ubuntu 20.04

### Additional information

Comparation Pics of Lenghts in Navidrome and the real one in File:
![image](https://user-images.githubusercontent.com/5566460/194915852-ca940b93-9373-4b89-b60f-963279b06794.png)
![image](https://user-images.githubusercontent.com/5566460/194916155-6112fb60-32a5-4094-9f24-1f896881dd26.png)
![image](https://user-images.githubusercontent.com/5566460/194916190-7ead4ab4-962b-4186-a322-94b85789209c.png)
![image](https://user-images.githubusercontent.com/5566460/194916258-de01e7e6-008c-4190-aeb9-6c36fd0e4b43.png)
![image](https://user-images.githubusercontent.com/5566460/194916288-3f495bd7-b460-4c1a-a0a1-4c661632acc3.png)
![image](https://user-images.githubusercontent.com/5566460/194916377-726d6c97-08ae-496b-bcfd-1b86e7f27c21.png)
![image](https://user-images.githubusercontent.com/5566460/194916428-69a8bd9b-6fa5-4cdb-a3b3-1d766aa53481.png)
![image](https://user-images.githubusercontent.com/5566460/194916460-f2f25bfa-f3a3-4ae1-b416-f39b61e6ac97.png)

![image](https://user-images.githubusercontent.com/5566460/194916923-194fb067-3ada-42a6-b8f9-748764089f9c.png)
![image](https://user-images.githubusercontent.com/5566460/194916994-10a6de81-b853-4d6a-b3cd-b652b7ad0006.png)
![image](https://user-images.githubusercontent.com/5566460/194917037-410f5996-a2f1-4731-ab2d-4198e7aef5a0.png)
![image](https://user-images.githubusercontent.com/5566460/194917084-7e1502ec-0608-49d7-a3e6-a0958dada3c6.png)
![image](https://user-images.githubusercontent.com/5566460/194917116-ca18ed70-c31d-45b2-9a10-4cf6e3bf483b.png)

As you can see some doesn't match and if I test them in AIMP the play correctly and the lenght is also correct.

My guess is that this is a rounding error in Navidrome because see:

```
Lenght (Navidrome) - Lenght (AIMP)
04:14                04:15 (04:14.981)
03:23                03:24 (03:23.990)
03:12                03:13 (03.12.533)
03:10                03:11 (03:10.707)
```

If rouded normally it should be rounded up if over .500 and down if under .500
But I guess it should only be rounded that way for display and not for playback to avoid any audible things.

**Comment by deluan** [comment]
Two issues here:
1) Displayed duration: Yes, it was truncating down. I just changed it in af5c2b5a42ed8b1038f8434ff64bab78378360a4 and now it is rounded like AIMP.
2) _"Swallows up to a second at the end of each track"_: If you are referring to the silent "gap" between songs, this is because the player we use in Navidrome does not provide gapless playback (#745), and unfortunately there's nothing much we can do at the moment. But you can use a gapless player with Navidrome if you want. Sonixd (a desktop player) is a good example.  Let me know if this is what are you referring to.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
No, I didn't mean the silent "gap" between songs for (2.) and the "two" issues seem closely related, because I meant it as described it "swallows" the last second eg. the last second is not played at all and it skips to the next. Like I had Tracks that have a fade out in last second that wasn't played at all, clearly audible.

But it's possible that this is because of (1.) eg. Navidrome skips to next exactly at duration end and because it was truncated instead rounded, it swallowed that second on some. So if that truncating was also used in play functions it's quite possible that it was fixed too now.

I gonna re-test that then once the version with the recent fixes is available.
