### ISSUE TITLE
Incorrect case in username in Subsonic API causes failure creating new player

### ISSUE THREAD

**Issue by srichter** [navidrome/navidrome#1928]
If the username sent via the Subsonic API does not match the case of the username in the database, the user will successfully authenticate, but a new player will fail to be created.

The username in the context is set directly from the query string. This context value is what is used when creating a new player, however the player table has a foreign key constraint to the users table on username. If the case does not match, this constraint will fail.

The easy fix is to have the player registration method pull the username from the user stored in the context. A better fix might be to update the username stored in the context directly from the user model that is fetched from the database, but I am unsure if this will have any unintentional side effects when other methods will now see a "different" user based on case

**Comment by deluan** [comment]
I think the best option is avoid using the username as a foreign key. I'll try to fix this mess soon. Thanks for the report!
