### ISSUE TITLE
Does not play APE Monkey Audio Lossless and doesn't load Cover from APEv2 Tags

### ISSUE THREAD

**Issue by K4r0qtuYNE5G4qgZ** [navidrome/navidrome#1930]
### Description

APE Monkey Audio Lossless not loaded / played
Embedded Cover not loaded from APEv2 Tagged Files

### Expected Behaviour

APE Monkey Audio Lossless played correctly
Embedded Covers from APEv2 Tagged Files being displayed correctly

### Steps to reproduce

1. Upload an album with some APE Files containing a cover
2. Open album in the Navidrome web interface
3. Try to play a Track

### Platform information

 - Navidrome version: 0.47.5 (86fe1e3b)
 - Browser and version: Chrome 105.0.5195.127 (Official Build) (64-bit)
 - Operating System: Ubuntu 20.04
 
### Additional information

MediaInfo Output:
```
Format                                   : Monkey's Audio
File size                                : 38,2 MiB
Duration                                 : 6 min 57s
Overall bit rate                         : 768 kb/s

Audio
Format                                   : Monkey's Audio
Duration                                 : 6 min 57s
Bit rate                                 : 768 kb/s
Channel(s)                               : 2 Kanäle
Sampling rate                            : 44,1 kHz
Bit depth                                : 16 bits
Compression mode                         : Lossless
Compression ratio                        : 1.837
Stream size                              : 38,2 MiB (100%)
Encoding settings                        : Extra-high
```

Mp3Tag Screenshot:
![image](https://user-images.githubusercontent.com/5566460/195980897-bcf79eeb-61a9-4a79-80fe-f19f1d859dcc.png)

Navidrome Screenshot
![image](https://user-images.githubusercontent.com/5566460/195981180-96a4501d-7767-4e51-aa4b-d97a1cc03935.png)
![image](https://user-images.githubusercontent.com/5566460/195981215-41fcb188-b41f-4f03-b535-8ba78f54c68e.png)

**Comment by vs49688** [comment]
I've seem similar behaviour when trying playing formats the browser doesn't support natively. Could you try enabling transcoding to a known-to-work format (e.g. mp3) and try playing then?

**Comment by K4r0qtuYNE5G4qgZ** [comment]
I could, but it's too tedious for me to create transcoding for every format that isn't supported. And transcoding would be much more useful if it could be defined per format, precisely because so many are not natively supported.

I'm currently re-tagging my multi terrabyte library for Navidrome which is enough work. So if I encounter such issues I now simply convert them into FLAC which seems the only lossless format that works fine.

But all those unsupported formats now put the following statements into perspective considerably...:
- Streams virtually **any** audio format available
- Reads and uses **all** your beautifully curated metadata

If it only supports what browsers supports natively it's massively reduced to [PCM, FLAC, AAC, MP3, Vorbis, Opus] only.

**Comment by dweymouth** [comment]
> And transcoding would be much more useful if it could be defined per format

See #351 tracking this and other possible improvements to the transcoding engine.

**Comment by deluan** [comment]
@K4r0qtuYNE5G4qgZ 

> But all those unsupported formats now put the following statements into perspective considerably...:
> 
> * Streams virtually **any** audio format available
> * Reads and uses **all** your beautifully curated metadata
> 
> If it only supports what browsers supports natively it's massively reduced to [PCM, FLAC, AAC, MP3, Vorbis, Opus] only.

Well, using transcoding, it can play **any** file that `ffmpeg` can read, so basically almost all formats out there (except maybe `.mod`, and other peculiar formats) :) Yes, it needs transcoding, but that does not invalidate the phrasing ;)

As for the tags, it may be a stretch for now, but we are working on this: #1036 

Regarding your issue, I need a sample file to understand why the tags were not read. Sorry but I failed to download in time the samples you provided in #1911. Can you please provide them again?

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Like I said already in the other comment, I now per default convert all to FLAC if in unsupported Formats.
But I gonna keep an eye open if there are still some of them somewhere in the mess i currently re-tag and if so gonna send you a sample then.

And btw. Does v0.49.3 now support per format transcoding or is it still all or none?

**Comment by deluan** [comment]
> And btw. Does v0.49.3 now support per format transcoding or is it still all or none?

Still all or nothing, but now downsampling works: the client can specify a maxbitrate, and it will only transcode if the file has a bitrate higher than what is requested. Unfortunately it does help in your use-case, AFAIU.
