### ISSUE TITLE
11 vulnerabilities according to npm

### ISSUE THREAD

**Issue by hboetes** [navidrome/navidrome#1931]
Hi there!

Being somewhat paranoid the message below is somewhat disconcerting:

```
11 vulnerabilities (5 moderate, 6 high)

To address all issues possible (including breaking changes), run:
  npm audit fix --force
```

So I added `sed -i 's@npm ci@npm ci \&\& npm audit fix ||:@' Makefile` to my build recipe. Which results in the same output. Using the additional `--force` option breaks the build (or at least it did 2 weeks ago)

What can you say about this message? Is it harmless? Would bumping a few version strings help? Can I help with testing?

Thanks,
Han

**Comment by deluan** [comment]
Hey @hboetes , the issues found by `npm` are all related to `react-scripts` (create-react-app), and the dependencies they affect are all used only when working with the project locally (dev-dependencies). All security issues that affected the app at runtime were fixed before the 0.48.0 release. 

Of course we will have more in the future, but as they are reported I evaluate them and if it has a serious implication, I usually release a security fix.
