### ISSUE TITLE
[0.48.0 - Windows] Unable to find ffmpeg

### ISSUE THREAD

**Issue by shiioo** [navidrome/navidrome#1932]
### Description

Upon upgrade from 0.47.5 to 0.48.0, FFmpeg isn't found anymore in Navidrome folder.

> level=warning msg="Unable to find ffmpeg. Transcoding will fail if used" error="exec: \"ffmpeg\": cannot run executable found relative to current directory"

### Expected Behaviour

FFmpeg is found, transcoding is happening and player plays music.

### Steps to reproduce

1. Launch navidrome
2. See error
3. Music isn't transcoded and player can't stream music

### Platform information

 - Navidrome version: 0.48.0
 - Browser and version: unrelated, server issue
 - Operating System: Windows 11 x64

### Additional information

Any other information that may be relevant or give context to the problem.

- Obvious, but it was working fine with 0.47.5 (only the main exe was replaced).
- Scanner.Extractor = 'ffmpeg' (same as 0.47.5)

**Comment by shiioo** [comment]
I've added the navidrome folder in PATH and it does indeed solve the issue :)

Can [this](https://github.com/caddyserver/xcaddy/pull/117#issue-1368933510) provide an alternative?

**Comment by deluan** [comment]
Not really, but I may put in place a workaround for Windows installations. I'll keep this issue open to track it.

**Comment by deluan** [comment]
Hey @shiioo, can you please test this with the latest build from develop? You can download the latest from here:

<img width="1036" alt="Screenshot 2023-02-02 at 12 12 07 PM" src="https://user-images.githubusercontent.com/331353/217346903-7ff42273-1b70-43ab-8ba6-12224e08f0d2.png">

Let me know if this solves the issue. If not, please reopen this. Thanks!
