### ISSUE TITLE
Support edit music info

### ISSUE THREAD

**Issue by wcb33** [navidrome/navidrome#1943]
### Support edit music information.

Support some way to edit the music information such as in detail info page. 

I'm fund some other issue about file upload/ file edit. The answer is read-only due to security issues. But I think the security issue is not very importance for some people.(maybe many people). Maybe it would be better to be controlled by users themselves. like the environment value 'ND_ENABLETRANSCODINGCONFIG' ...

**Comment by marksdestiny** [comment]
I also would find a way to change the meta data of music files very helpful, maybe just for one (admin) user.

**Comment by xkevinx** [comment]
I would love to have that kind of feature as well!

**Comment by kkkkxl** [comment]
great! I want have this function.

**Comment by deluan** [comment]
Sorry, but this requires a lot of effort, it is not just a matter of adding a config option. I rather use my (scarce) time in other features that IMO are more important, like Sharing, Multiple Folders, Multi-valued tags, Jukebox, etc...

**Comment by dro-ex** [comment]
If on a mac - I recommend YATE - a deceptively simple looking tagger with scripting, workflow, automated tagging features - I got it down I can tag 100 albums in one go with minimal intervention.  My $0.02.
