### ISSUE TITLE
Error when linking custom ListenBrainz

### ISSUE THREAD

**Issue by crosbyh** [navidrome/navidrome#1944]
### Description

When I attempt to link my Navidrome instance to a selfhosted instance of Maloja, I receive an error: `ListenBrainz could not be linked: Invalid token`at the "Enter your ListenBrainz user token" stage 

### Expected Behaviour

I would expect the instances to properly link when provided correct URL and credentials.

### Steps to reproduce

1. Open the 'Personal' settings menu
2. Click on 'Scrobble to ListenBrainz'
3. Enter Maloja API Key in Navidrome
4. See error `ListenBrainz could not be linked: Invalid token`

### Platform information

 - Navidrome version: v0.48.0
 - Browser and version: Firefox v105.0.3
 - Operating System: Docker on Ubuntu
 
### Additional information

Navidrome and Maloja are both behind a Traefik reverse proxy. 

I notice in my logs when I attempt to link, that the PUT request to link accounts is going to the plain http version of my Navidrome URL (music.mydomain.com), rather than the HTTPS URL, where I think the request should be directed:

- Logs Excerpt:
```
time="2022-10-19T04:44:18Z" level=warning msg="HTTP: PUT http://music.mydomain.com/api/listenbrainz/link" elapsedTime=2.2ms httpStatus=400 remoteAddr=10.0.1.1 requestId=ac7ascd7d3ed/ugkTkkCCIoG-000125 responseSize=25
```

Is there a way to ensure the PUT is sent to the HTTPS domain?

I am willing to provide a Maloja key to test with my instance, if that would be helpful.

Thank you for this wonderful software!

**Comment by redeel-media** [comment]
I had the same problem and was able to link to **maloja** by adding "/1/" to the end of the ListenBrainz.BaseURL setting:

`ListenBrainz.BaseURL = 'https://XXXXXXXX/apis/listenbrainz/1/'`

But now it doesn't scrobble.

Navidrome log:
```
DEBU[145740] Sending scrobble                              artist="xxxxx" scrobbler=listenbrainz track="xxxxx"
ERRO[145740] Error sending scrobble to service. Discarding  artist="xxxxx" error=unrecoverable scrobbler=listenbrainz track="xxxxx" userId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

```
Maloja log:
```
[apis] Listenbrainz API request: ['submit-listens']
[apis] Error with Listenbrainz API: <class 'maloja.apis._exceptions.MalformedJSONException'> (Request: [])
```

**Comment by crosbyh** [comment]
Thanks @redeel-media , I added the `/1/` to my Maloja URL and it properly authenticated. I am now seeing a similar error as you in my logs, and tracks do not scrobble.

Navidrome Log:
```
time="2022-10-20T04:19:48Z" level=warning msg="ListenBrainz UpdateNowPlaying returned error" error="ListenBrainz error(400): Invalid JSON document submitted." requestId=743b62c066c4/dmcuTQpr8g-000074 track="xxxxxx"
time="2022-10-20T04:19:48Z" level=error msg="Error sending NowPlayingInfo" artist="xxxxxx" error=unrecoverable requestId=743b62c066c4/dmcuTQpr8g-000074 scrobbler=listenbrainz track="xxxxxx"
```

In Maloja Log:
```
[apis] Listenbrainz API request: ['submit-listens']
[apis] Error with Listenbrainz API: <class 'maloja.apis._exceptions.MalformedJSONException'> (Request: [])
```

**Comment by deluan** [comment]
I personally do not use Maloja, and this option to configure the URL was contributed by @andyklimczak. Not sure if he tested it with Maloja or any other self-hosted solution.

If @andyklimczak  or anyone else can figure this out, it would be very much appreciated.

**Comment by TheWrathKing** [comment]
I have developed a simple php rest script which writes in a database the timestamp and the track being played by navidrome and it works perfectly fine.
My configuration is : ListenBrainz.BaseURL = "https://xxx.xxx.com" 
Navidrome posts the json to this url : https://xxx.xxx.com/submit-listens and it's working like a charm.
The json payload looks like this :
{
 "listen_type":"single" or "playing_now",
 "payload":[{
  "listened_at":1666077830, => only when "listen_type" = "single"
  "track_metadata":{
   "artist_name":"Aphrodite's Child",
   "track_name":"The Battle Of The Locusts",
   "release_name":"666",
   "additional_info":{
    "tracknumber":12,
    "artist_mbids":[""]
   }
  }
 }]
}
@andyklimczak  : Thanks for this great addition.
@deluan : Thanks  a lot for this wonderful peace of software. Only thing missing for me now is the possibility to put a jpeg file along playlists (same name as m3u or nsp)

**Comment by jan666** [comment]
I used the maloja patch @redeel-media did (https://github.com/krateng/maloja/pull/170) and now scrobbling works fine.

`ListenBrainz.BaseURL    = 'https://<domain>/apis/listenbrainz/1/'`

**Comment by deluan** [comment]
Thanks @redeel-media for looking into this, and @jan666 for confirming it. So it seems to be an issue with Maloja's "compatibility mode" with ListenBrainz, as this same payload works with LB. I'll wait for the https://github.com/krateng/maloja/pull/170 closing before closing this one.

**Comment by krateng** [comment]
I might be wrong here, but from testing this isn't navidrome missing the header `Content-Type: application/json`?

**Comment by rhamzeh** [comment]
> I might be wrong here, but from testing this isn't navidrome missing the header Content-Type: application/json?

💯 

@krateng https://github.com/krateng/maloja/pull/170 shouldn't be merged as is because it breaks compatibility with Listenbrainz clients that do send the `Content-Type` header

**Comment by crosbyh** [comment]
Can confirm this works great for me in the latest develop branch, thanks everyone!
