### ISSUE TITLE
`DefaultLanguage` config doesn't work when set to Chinese

### ISSUE THREAD

**Issue by cnRuanYF** [navidrome/navidrome#1946]
### Description

`DefaultLanguage` config doesn't work when set to Chinese.

### Expected Behaviour

Default language can be change to Chinese.

### Steps to reproduce

1. According to [configuration-options doc](https://www.navidrome.org/docs/usage/configuration-options)
> Sets the default language used by the UI when logging in from a new browser. This value must match the [2 letter ISO code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) for the language
set `DefaultLanguage` to `zh` in `navidrome.toml`
2. Restart server
3. Clear browser cache, LocalStorage and Cookie
4. Open WebUI, language is still English
(Also doesn't work when set to `zh-Hans` or `zh-Hant`)

### Platform information

 - Navidrome version: v0.48.0
 - Browser and version: MsEdge v106.0.1370.42
 - Operating System: Windows 11 22H2

### Additional information

I think the legal configuration value should be the same as `i18n/xx.json`,
Chinese needs to be set to `zh-Hans` or `zh-Hant`,
but due to the processing in this commit https://github.com/navidrome/navidrome/commit/bfeb8ef6b3e5756d72b230abdbb96f8a31b2e2fa
`zh-Hans` / `zh-Hant` will be converted to `zh-hans` / `zh-hant`, causing the language file cannot be loaded

I have tried to fix this bug and will create a PR later

(Sorry for my bad English)

**Comment by deluan** [comment]
Thanks for looking into this, but I think the best to do here is to revert https://github.com/navidrome/navidrome/commit/bfeb8ef6b3e5756d72b230abdbb96f8a31b2e2fa, as the language code is clearly case-sensitive. I'll revert it for next release.
