### ISSUE TITLE
Transcoding: ffmpeg non-zero exit codes are silently swallowed, cache is poisoned

### ISSUE THREAD

**Issue by isker** [navidrome/navidrome#1950]
### Description

Navidrome does not properly use `exec.Command` to detect non-zero exit codes from `ffmpeg` (or whatever other configured command, but I'll stick with `ffmpeg` in this issue) when transcoding.

When `ffmpeg` fails, the typical result is that nothing is output to stdout, and so navidrome happily caches an empty file as the result of transcoding, serving clients this empty file.

The problem is that navidrome only handles errors in the course of reading from stdout; it does not handle the error returned by `exec.Wait`, which is what actually signals a non-zero exit status: https://pkg.go.dev/os/exec#Cmd.Wait.

The issue is here: https://github.com/navidrome/navidrome/blob/86c0b422f64173d9fae9ba59c4d1f7483c53bf5b/core/transcoder/transcoder.go#L37

I'm not sure how to fix this while retaining the streaming behavior.  Cache entries must not be produced when the command fails.

Navidrome doesn't even log anything when `ffmpeg` exits non-zero.  Logging would be a good start, but the real problem remains that the cache is poisoned in this case.

### Expected Behaviour

Streaming transcoded files does not silently fail when the transcoding command fails.

Navidrome logs something when the transcoding command fails.

### Steps to reproduce

1. Either put a bogus, always-failing `ffmpeg` on navidrome's PATH, or configure a transcoding that invalidly invokes `ffmpeg` such that it exits non-zero.
2. Configure the web player to use this transcoding.
3. Play a song.  Observe that the `/rest/stream` request either fails with HTTP 416, or succeeds with a `Content-Length: 0` response.  I don't actually understand when one failure mode happens over the other, but both are symptoms of the transcoding cache being poisoned with empty files.

### Platform information

Navidrome 48.0.  Other platform information is not relevant.

### Additional information

We discovered this problem in https://github.com/NixOS/nixpkgs/pull/196304.

The lack of logging on transcoding failure has also been pointed out in #1872.

**Comment by deluan** [comment]
Hummm... thanks for the investigation. I'll take a look and try to find a good way to handle this.

**Comment by FoxBuru** [comment]
I've recently hit this problem while trying to use aac transcoding on the fly, using a custom-built ffmpeg binary including fdk_aac. I've used:

´´´
/opt/ffmpeg/bin/ffmpeg -i %s -c:a libfdk_aac -vbr:a 4 -movflags faststart -f adts -write_id3v2 1 -
´´´

As the transcoding command. 

If I pipe the output (through, let's say, VLC) it plays properly. Also, if I explore the `cache/transcoding` folder after the HTTP error happens, no file is stored (I'm not sure if the last bit is helpful, though)

**Comment by FoxBuru** [comment]
> ```shell
> /opt/ffmpeg/bin/ffmpeg -i %s -c:a libfdk_aac -vbr:a 4 -movflags faststart -f adts -write_id3v2 1 -
> ```

My bad about this command. In reality, to make a functional AAC streaming from ffmpeg, I needed to use something like:

```shell
/opt/ffmpeg/bin/ffmpeg -nostdin -v 0 -i %s -c:a libfdk_aac -vbr:a 4 -f adts -
```

Nevertheless, I think I took some time these last days to take a hunch on this, and I'll be opening a PR to try to address this very problem.

**Comment by isker** [comment]
Thanks for fixing!
