### ISSUE TITLE
Strange display of track duration

### ISSUE THREAD

**Issue by LeoSum8** [navidrome/navidrome#1956]
I just noticed a strange track duration here, maybe a rounding error? Shouldn't this read 4:00? :)

![grafik](https://user-images.githubusercontent.com/23354139/198013319-ca45392e-8d53-4e3b-a662-c32e6634fcfe.png)

**Comment by deluan** [comment]
Ops, I messed things up in af5c2b5a42ed8b1038f8434ff64bab78378360a4. Fixed now. Thanks!
