### ISSUE TITLE
Firefox don´t play track

### ISSUE THREAD

**Issue by DJoLoAo** [navidrome/navidrome#1957]
### Description

Firefox starts playing a track in navidrome media player but stops immediately. Can´t get it started again.
No issues in Ubuntu 22.04 Firefox Firefox 106.0.1 (64 bit). Same issues were there before also in 0.47.5 Firefox/Windows
Problem occurs also with Firefox/Windows 11. No problems in Brave/Windows.

### Platform information

 - Navidrome version: v0.40.0 
 - Browser and version: Firefox v106.0.1 (64-bit)
 - Operating System: Windows 10 Pro 21H2
 
### Additional information

 - Client used? navidrome UI under Firefox/Windows

Thanks for your help and massive thx for this great fast media server.

**Comment by Trufax** [comment]
Did you test v106.0.2 ? i tested the same setup on Windows and FF and it works without issues. Maybe some addons blocking it ?
