### ISSUE TITLE
New songs dont receive an element in time and covers are very pixeled

### ISSUE THREAD

**Issue by g4njawizard** [navidrome/navidrome#1960]
Hello,

I just updated the container and added some new songs. I noticed that only 1 full album has been added to recently added.
Single songs in a mixed directory are partially available to search under "songs" but when you click on either artist or album, there appears an error: Element could not be found.
It takes much longer for these elements to be listed. Now almost 30 minutes passed and now the 13 songs I added are appearing in recently added, but the cover is still loading and refreshing the page causes a "bad gateway".
I also notice that the downloaded covers are very low quality. The more high res covers are from pre-update.
![Bildschirmfoto_2022-10-28_10-43-30](https://user-images.githubusercontent.com/21695748/198569480-3823e5cd-1163-441e-a684-3458bf8e33e8.png)

**Comment by deluan** [comment]
These errors are likely to happen when the scanner is running (specially the "Element could not be found" error). Please try when there's no importing happening anymore and let me know.
