### ISSUE TITLE
Navidrome fails to start using contrib/navidrome.service and go 1.19

### ISSUE THREAD

**Issue by JeffHenson** [navidrome/navidrome#1961]
The service file in contrib doesn't work when Navidrome is built with go 1.19 due to it trying to use the `setrlimit` syscall that is being disallowed by the `@resources` in line 40.

https://github.com/navidrome/navidrome/blob/5f38d9dca2c93f9527eb1d1014e13d4631f17eff/contrib/navidrome.service#L40

There's two ways this could be fixed:
1. Remove `@resources` from line 40 and just allow all of those syscalls.
2. Add a line specifically allowing the `setrlimit` syscall after line 40:
```
SystemCallFilter=setrlimit
```

I'm happy to submit a PR for either fix.

**Comment by deluan** [comment]
Hey, sorry for not seeing this before. It would be better to go with option 2, enabling only the `setrlimit`. Let me know if you can create the PR. Thanks!

**Comment by deluan** [comment]
Awesome! Thanks!
