### ISSUE TITLE
Log if ffprobe cannot see ID3 tags

### ISSUE THREAD

**Issue by asmartin** [navidrome/navidrome#1962]
Hello! I seem to be experiencing an issue similar to #359 where I have a folder full of files (all with the same ownership and permissions), however only a subset of the files appear in Navidrome (0.48.0). Looking at it more closely, it seems that ffprobe doesn't show any id3 tags on the missing files (except for `lyrics-eng`), yet if I use `id3tool` to examine the files, I can see all the ID3 tags just fine. Is there a way I can examine the "bad" files to determine what is wrong with the ID3 tags on the files that ffprobe can't parse? Moreover, is it possible to log files that fail in this way (ffprobe can't read their metadata) rather than silently excluding them? As seen in the log, all 16 files in this folder are successfully scanned and added to the library, but only a subset of those 16 are actually accessible in Navidrome:
```
navidrome navidrome[7631]: time="2022-10-28T15:00:07Z" level=info msg="Finished processing changed folder" deleted=0 dir="/path/to/folder" elapsed=477.9ms updated=16
```

Thanks!

**Comment by deluan** [comment]
When `ffprobe` (actually `ffmpeg`) can not extract any tags from a file, it uses the following defautls:
- Title: File path
- Artist: `[Unknown Artist]`
- Album: `[Unknown Album]`  

So you should still find your files in Navidrome after the scan. Please confirm that this is not the case.

**Comment by asmartin** [comment]
You're correct, I was able to find the missing files under `[Unknown Artist]` - `[Unknown Album]`. Thank you!

I examined the situation more closely and found that these files only had ID3v1 tags and not ID3v2 tags which is why they weren't being picked up by `ffmpeg`. I was able to easily convert them using [id3v2](https://id3v2.sourceforge.net/) (`apt-get install id3v2` on Debian-based distros) as follows:
```bash
#!/bin/bash
# Example usage: convert_id3.sh /path/to/files
while read file; do
  id3v2 -l "$file" | grep -q "No ID3v2 tag"
  if [ $? -eq 0 ]; then
    # this file needs to be converted
    id3v2 -C "$file"
    if [ $? -ne 0 ]; then
      echo "ERROR: cannot convert $file"
    fi
  fi
done < <(find $1 -type f -print)
```

After doing the above conversion, the files now show up under the correct artist/album in Navidrome!

Maybe it would be useful to list under [the FAQ page](https://www.navidrome.org/docs/faq/) that ID3v2 tags are required and ID3v1 tags must be converted. Thanks for the help!
