### ISSUE TITLE
[0.48] Navidrome fails to run on Pi Zero /armv6

### ISSUE THREAD

**Issue by kgarner7** [navidrome/navidrome#1968]
### Description
When attempting to run the armv6 binary on an armv6l device, navidrome throws an "Illegal instruction" error. 

### Expected Behaviour

Navidrome should run.

### Steps to reproduce

1. Get a binary from [Github armv6](https://github.com/navidrome/navidrome/releases/download/v0.48.0/navidrome_0.48.0_Linux_armv6.tar.gz) or manually build using [ci-gorelease](https://github.com/navidrome/ci-goreleaser)
2. Extract and attempt to run.
3. Crash.

### Platform information

 - Navidrome version: v0.48
 - Browser and version: n/a; does
 - Operating System: Pi zero (`Linux raspberrypi 4.4.34+ #3 Thu Dec 1 14:44:23 IST 2016 armv6l GNU/Linux`)

### Additional information

I tested this in a VM. I was actually able to build from source, but attempting to build using `https://github.com/navidrome/ci-goreleaser` manually gave the same error. Probably an error in building taglib for arm?

Additional users (with real devices):
- https://discord.com/channels/671335427726114836/704303730660737113/1036831066515836999
- https://discord.com/channels/671335427726114836/671335427726114839/1032884826283454504 (follow the message chain)

**Comment by kgarner7** [comment]
This appears to specifically be a problem with `arm-linux-gnueabihf-gcc`. It has flags including `--with-arch=armv7-a`, denoting a lack of support for armv6. For that, you would need something like https://github.com/Pro/raspi-toolchain

**Comment by deluan** [comment]
Hey, thanks for the report. Because of deprecated tools, I had to change the build to start using armhf instead of armel. This causes old platforms to be incompatible. I may revisit the [build toolchain](https://github.com/navidrome/ci-goreleaser) in a future release, but for now the only workaround is to build it yourself.

**Comment by kgarner7** [comment]
Tentative solution https://github.com/navidrome/ci-goreleaser/pull/5 !
