### ISSUE TITLE
Multiple Folders or select folders for music library

### ISSUE THREAD

**Issue by alwynpinto** [navidrome/navidrome#1973]
I user UNRAID and the version of NAVIDROME is 0.48.0

I would like to add multiple folders or select folders into my library in UNRAID.
Another question: I would like all the music formats to be played WITHOUT transcoding. Are all set that way ?

**Comment by deluan** [comment]
Sorry, I missed this when you originally posted. This is a duplicate of #192.

Regarding transcoding, the default configuration is to play everything _without_ transcoding.
