### ISSUE TITLE
Add the "created_at" field to the "Columns to Display"

### ISSUE THREAD

**Issue by sterling-tenn** [navidrome/navidrome#1974]
### Is your feature request related to a problem? Please describe.

Yes, I would like to be able to sort my music library by the date I added it to Navidrome

### Describe the solution you'd like

"Columns to Display" also includes the "created_at" field labelled as "Date Added"

### Additional context

![image](https://user-images.githubusercontent.com/56081843/199869989-426acf4b-533b-4410-93e3-7960c79fc909.png)

**Comment by Cor4zon** [comment]
Hi @deluan @sterling-tenn ! I would take that issue. Please assign it to me

**Comment by deluan** [comment]
@Cor4zon No need for assignment, just send the PR :)

**Comment by KartikBudania** [comment]
@deluan I am interested in solving this issue, will you please help me in finding the codebase for this issue??
