### ISSUE TITLE
lot of MP3 not playing in Navidrome Player

### ISSUE THREAD

**Issue by Moacc95** [navidrome/navidrome#1981]
### Description

Hello, several of my MP3 files do not play in Navidrome (it works in VLC)

 - Navidrome version: 
 - Browser and version: 
 - Operating System: 

### Additional information
 
here are the logs :

 level=debug msg="Streaming RAW file" id=8c0a513da763345e131404057aa1666e originalBitrate=0 originalFormat=mp3 path=/music/test.mp3 requestBitrate=0 requestFormat= requestId=073667d28924/ozFX4eklfh-000033 selectedBitrate=0 selectedFormat=raw

 level=info msg="Streaming file" artist="[Unknown Artist]" bitRate=0 cached=false format=raw originalBitRate=0 originalFormat=mp3 title=test transcoding=false user=Morgan

warning msg="API: Failed response" error=0 message="Internal Error" requestId=073667d28924/ozFX4eklfh-000033

My stack in Docker :

version: "3"
services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    user: 1002:100 # should be owner of volumes
    networks:
    - reverse-proxy-net
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: trace  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      ND_DEFAULTLANGUAGE: fr
      ND_ENABLETRANSCODINGCONFIG: true
      ND_AUTOIMPORTPLAYLIST: true
      ND_PLAYLISTSPATH: "/playlists:playlists/**"
      ND_ENABLECOVERANIMATION: false
      ND_REVERSEPROXYUSERHEADER: ""
      #ND_REVERSEPROXYWHITELIS: "0.0.0.0/0"
      PasswordEncryptionKey: mypassword
    volumes:
      - "/srv/dev-disk-by-uuid-c8472a0a-61b5-4f1d-8189-1623ef476463/appdata/navidrome:/data"
      - "/srv/dev-disk-by-uuid-b861ba3c-16f8-4827-9c7c-4d87a8386067/Musiques:/music:ro"
      - "/srv/dev-disk-by-uuid-b861ba3c-16f8-4827-9c7c-4d87a8386067/Musiques/Playlists:/playlists"
      
networks:
  reverse-proxy-net:
    external: true

**Comment by deluan** [comment]
Does any MP3 plays in Navidrome? Maybe it is a misconfiguration in the reverse proxy? Can you send me (deluan AT navidrome.org) one file that does not play?

**Comment by Moacc95** [comment]
Hello, 
I solved my problem. It was a directory access problem.

Thank you.
