### ISSUE TITLE
Track with artist and album showing as [Unknown Album] and [Unknown Artist]

### ISSUE THREAD

**Issue by flemmingss** [navidrome/navidrome#1983]
### Description
I have this whole 4CD-album I have ripped and tagget with MusicBrainz Picard. They have the same album and album artist tags, but one of the tracks is showing as  [Unknown Album] and [Unknown Artist] and is not recognized by navidrome as part of the same album.

### Expected Behaviour

All will be in the same album with same album artist (Various Artists)

### Steps to reproduce

Don't know, just normal import form musicfolder.
I can't publish the exact file because of copyright reasons, but I am willing to send on request.

### Platform information

 - Navidrome version: [0.48.0](https://github.com/navidrome/navidrome/releases/tag/v0.48.0) (af5c2b5a)
 - Browser and version: Google Chrome
 - Operating System: Windows 11

### Additional information

Any other information that may be relevant or give context to the problem.

 - Screenshots (if applicable)
 - 
![scr1](https://user-images.githubusercontent.com/25674067/201065689-b5dd9651-90f6-4cf4-ace0-1fb52002f47e.png)
![scr2](https://user-images.githubusercontent.com/25674067/201065694-9ec09afb-8050-49e4-8c35-4e3eb4ef6435.png)
![scr3a](https://user-images.githubusercontent.com/25674067/201065697-a8b188ce-d2cd-4259-a5f6-cd297db3a390.png)
![scr3b](https://user-images.githubusercontent.com/25674067/201065698-f85216a8-aa7b-4912-b0fa-b9b8819b5503.png)
![metadata](https://user-images.githubusercontent.com/25674067/201065683-6a71075a-77e1-491b-80fc-85e188ba5267.png)

 - Logs? idk where
 - Client used? Web

**Comment by deluan** [comment]
Can you please send me the file so I can take a look? deluan AT navidrome.org

> Logs? idk where

https://www.navidrome.org/docs/faq/#where-are-the-logs

**Comment by flemmingss** [comment]
Hi @deluan, i got the log here:
`time="2022-11-07T20:23:19Z" level=info msg="Finished processing changed folder" deleted=0 dir="/music/releases_ripped/Various Artists/2018 - Dominator, the Hardcore Festival_ Wrath of Warlords (album)" elapsed=2.73s updated=38
time="2022-11-07T20:23:19Z" level=info msg="Finished processing Music Folder" added=38 deleted=0 elapsed=4.2s folder=/music playlistsImported=0 updated=0
time="2022-11-07T20:24:17Z" level=info msg="Finished processing changed folder" deleted=0 dir="/music/releases_ripped/Various Artists/2018 - Dominator, the Hardcore Festival_ Wrath of Warlords (album)" elapsed=129.2ms updated=9
time="2022-11-07T20:24:17Z" level=info msg="Finished processing Music Folder" added=9 deleted=0 elapsed=2.2s folder=/music playlistsImported=0 updated=0
time="2022-11-07T20:42:18Z" level=warning msg="Error reading metadata from file. Skipping" error="cannot process /music/releases_ripped/Various Artists/2016 - Defqon.1 2016_ Dragonblood (album)/4-16 - Outsiders - Rebel Baby.flac" filePath="/music/releases_ripped/Various Artists/2016 - Defqon.1 2016_ Dragonblood (album)/4-16 - Outsiders - Rebel Baby.flac"
time="2022-11-07T20:42:24Z" level=info msg="Finished processing changed folder" deleted=0 dir="/music/releases_ripped/Various Artists/2016 - Defqon.1 2016_ Dragonblood (album)" elapsed=8.3s updated=83
time="2022-11-07T20:42:25Z" level=info msg="Finished processing Music Folder" added=83 deleted=0 elapsed=10.33s folder=/music playlistsImported=0 updated=0
time="2022-11-07T20:43:19Z" level=info msg="Finished processing changed folder" deleted=0 dir="/music/releases_ripped/Various Artists/2016 - Defqon.1 2016_ Dragonblood (album)" elapsed=2.73s updated=14
time="2022-11-07T20:43:19Z" level=info msg="Finished processing Music Folder" added=14 deleted=0 elapsed=4.24s folder=/music playlistsImported=0 updated=0
time="2022-11-08T22:46:27Z" level=info msg="Finished processing changed folder" deleted=0 dir="/music/releases_ripped/Various Artists/2019 - Defqon.1 2019_ One Tribe (album)" elapsed=10.59s updated=17
time="2022-11-08T22:46:27Z" level=info msg="Finished processing Music Folder" added=17 deleted=0 elapsed=12.6s folder=/music playlistsImported=0 updated=0
time="2022-11-08T22:47:22Z" level=info msg="Finished processing changed folder" deleted=0 dir="/music/releases_ripped/Various Artists/2019 - Defqon.1 2019_ One Tribe (album)" elapsed=6.2s updated=24
time="2022-11-08T22:47:22Z" level=info msg="Finished processing Music Folder" added=24 deleted=0 elapsed=7.88s folder=/music playlistsImported=0 updated=0
time="2022-11-08T22:48:19Z" level=info msg="Finished processing changed folder" deleted=0 dir="/music/releases_ripped/Various Artists/2019 - Defqon.1 2019_ One Tribe (album)" elapsed=2.97s updated=47
time="2022-11-08T22:48:19Z" level=info msg="Finished processing Music Folder" added=47 deleted=0 elapsed=4.72s folder=/music playlistsImported=0 updated=0`

Sending you the file now within 5 minutes :)

**Comment by K4r0qtuYNE5G4qgZ** [comment]
On FLAC Files also check that there are only FLAC Tags and not any ID3 tags.
I had a bunch of weird FLAC Files where there was an ID3 Tag over an FLAC Tag or ID3 Tags instead FLAC Tags and both leads to issues. Best is to check in Mp3Tag if it reports issues with those Files or if it shows ID3 Tags and if so use the Remove Tag Function and then Re-Tag them cleanly.

What I also had, not related to FLAC but to Mp3 is an IDv2.3 Tag over an IDv2.4 Tag that lead to massive errors like crashes on read in Windows etc. Really dunno which Tools create such crap, but I also was able to fix it with Mp3Tag (Copy Tag, Remove Tag, Paste Tag fixed it).

**Comment by deluan** [comment]
Hey @flemmingss , I was able to import your file in my local instance:
<img width="1046" alt="Screen Shot 2022-11-11 at 4 38 50 PM" src="https://user-images.githubusercontent.com/331353/201434596-279ac26b-28aa-499f-807c-bfe68625ff75.png">

So, seems the file is ok. I tried with both `ffmpeg` and `taglib` extractors. Looking closely at your log above, seems that there was an error while reading this specific file:
```
time="2022-11-07T20:42:18Z" level=warning msg="Error reading metadata from file. Skipping" error="cannot process /music/releases_ripped/Various Artists/2016 - Defqon.1 2016_ Dragonblood (album)/4-16 - Outsiders - Rebel Baby.flac" filePath="/music/releases_ripped/Various Artists/2016 - Defqon.1 2016_ Dragonblood (album)/4-16 - Outsiders - Rebel Baby.flac"
```

Maybe it is a permissions issue? You can try moving it out of your music library, rescanning so it disappears from ND,  moving it back and rescanning again. Before doing that, I suggest changing ND's LogLevel to `debug`.

**Comment by flemmingss** [comment]
I can confirm removing and re-adding it was working, it is now in the right album with correct metadata.

`time="2022-11-12T09:57:43Z" level=info msg="Finished processing changed folder" deleted=1 dir="/music/releases_ripped/Various Artists/2016 - Defqon.1 2016_ Dragonblood (album)" elapsed=852.4ms updated=0
time="2022-11-12T09:57:43Z" level=info msg="Finished processing Music Folder" added=0 deleted=1 elapsed=2.95s folder=/music playlistsImported=0 updated=0
time="2022-11-12T09:58:43Z" level=info msg="Finished processing changed folder" deleted=0 dir="/music/releases_ripped/Various Artists/2016 - Defqon.1 2016_ Dragonblood (album)" elapsed=74.1ms updated=0
time="2022-11-12T09:58:43Z" level=info msg="Finished processing Music Folder" added=0 deleted=0 elapsed=2.41s folder=/music playlistsImported=0 updated=0
time="2022-11-12T10:00:43Z" level=info msg="Finished processing changed folder" deleted=0 dir="/music/releases_ripped/Various Artists/2016 - Defqon.1 2016_ Dragonblood (album)" elapsed=242.9ms updated=1
time="2022-11-12T10:00:43Z" level=info msg="Finished processing Music Folder" added=1 deleted=0 elapsed=2.51s folder=/music playlistsImported=0 updated=0
time="2022-11-12T10:01:43Z" level=info msg="Streaming file" artist=Outsiders bitRate=0 cached=false format=raw originalBitRate=1096 originalFormat=flac title="Rebel Baby" transcoding=false user=fleska
time="2022-11-12T10:01:44Z" level=warning msg="Request was interrupted" error="context canceled" path=stream
time="2022-11-12T10:01:44Z" level=info msg="Now Playing" artist=Outsiders player="NavidromeUI [Chrome/Windows]" title="Rebel Baby" user=fleska
time="2022-11-12T10:01:44Z" level=info msg="Streaming file" artist=Outsiders bitRate=0 cached=false format=raw originalBitRate=1096 originalFormat=flac title="Rebel Baby" transcoding=false user=fleska
`

Maybe Navidrome should re-check skipped files every X hours or something?
Anyway, it is working now with this workaround.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
> Maybe Navidrome should re-check skipped files every X hours or something?

It does if not disabled:


Option in config file | Env var | Description | Default Value
-- | -- | -- | --
ScanSchedule | ND_SCANSCHEDULE | Configure periodic scans using “cron” syntax. To disable it altogether, set it to "0" | "@every 1m"


I dunno if those are Quick or Full Scans, but I guess only Quick Scans and then you need to remove/re-add to fix such issues.
And another issue may be if files then are intermittently unreadable for some reason.

**Comment by deluan** [comment]
Yes, a Full Scan should have fixed this as well, but I never remember that, as they are too slow for me and I rarely use them.

Well, glad it worked.
