### ISSUE TITLE
Feature: Enhancing Artists view on web-ui

### ISSUE THREAD

**Issue by JSubelj** [navidrome/navidrome#1984]
### Is your feature request related to a problem? Please describe.
My main search for music on my server is via artist not albums. On web-ui albums have subcategories like All, Random, Favorite etc. I would love it if Artists would get the same treatment. Also to have grid view on artists and to update artist icons (I think already done here: #1921)

### Describe the solution you'd like
Add grid view to Artists, then add subcategories to Artists: All, Random, Favorite

### Describe alternative solutions that would also satisfy this problem
Starting with just grid view for Artists would be great.

**Comment by OlvrWllms** [comment]
I'd especially welcome the random and favorite songs displayed on the artist page.

**Comment by DanielNautre** [comment]
Grid view for Artist would be a big plus. IMHO It's visually more appealing than a long list and makes better use of the real estate
Possible images to show in the grid:
- Artist image from last.fm
- User supplied image
- Placeholder image
- Tiled covers (as in #1992)
- Piled covers (similar to Musicbee for example)
