### ISSUE TITLE
Can I get confirmation that everything works correctly on Apple Chipset? (M1 Mac)

### ISSUE THREAD

**Issue by bensrokosz** [navidrome/navidrome#1986]
Hello, I have followed all of the steps in the MacOS installation instructions......and I am not able to find any way to tell Navidrome to look in a different folder for music than the default /music

It seems like the instructions are aimed more at experienced common line programmers (which I completely understand), but I have done lots of this over the years, custom setups for Audio Devices, control surfaces, setting up raspberry PI, etc etc and I just find the instructions to be very vague.

That said I can get Navidrome to work when I place music in my home/music folder. Everything works great.

It says 'a configuration file is created'. So I made one in textedit with extension .toml
Pasted in the code suggested. Copied the path from finder to my music folder, added to the proper line in the .toml file.....nothing.

So I would just like someone who has successfully got this working on an M1 Mac to confirm (please) just so I'm not wasting my time. Thanks. Don't get me wrong.....I love this and it is my new streaming solution. I just have too much music to keep it on my internal Mac drive.

**Comment by deluan** [comment]
Yes, Navidrome works on M1 Macs, (although still using Rosetta).  I personally never used the [`navidrome.plist` file from the docs](https://www.navidrome.org/docs/installation/macos/), but you can confirm Navidrome runs on your local by calling it directly:
```
$ ./navidrome --loglevel debug  --musicfolder "/Users/yourusername/Path/To/Music"
```
More options can be found in the [config documentation](https://www.navidrome.org/docs/usage/configuration-options/)

**Comment by bensrokosz** [comment]
As much as I'd love to keep trying this......I think I'll just wait for an installer. Tried making my own .toml and .plist files exactly as specified in the guide and they seem do nothing. 

So either I'll hold off for some clearer instructions or till this thing becomes an app with a proper installer. For now at least I have it working with the defaults.

**Comment by kaambiz** [comment]
I've been building from source for a few months now with no issue, so more Rosseta for me. Also my music is not located in /home/music, in fact they're on another drive. I run Navidrome by one single command and it works flawlessly:

`./navidrome --musicfolder "/Volumes/Music" --scaninterval "0"`

(scaninterval 0 so I just scan it manually).
