### ISSUE TITLE
Non-admin user can't change password 

### ISSUE THREAD

**Issue by yarg-kane** [navidrome/navidrome#199]
While trying to setup a few accounts for friends, I noticed that the admin users can change everybody's password (normal), but the normal users can't manage their own at all.

**Comment by deluan** [comment]
Ops, totally forgot about this. Will try to implement this in the next couple of weeks. Thanks for the report

**Comment by ElleshaHackett** [comment]
This should probably be implemented along with a "password forget" functionality and https://github.com/deluan/navidrome/issues/202.

**Comment by williamkray** [comment]
"password forgotten" reset functionality would require some sort of account validation, presumably email verification which would require an SMTP connection. i've created https://github.com/deluan/navidrome/issues/454 to reflect that.

**Comment by williamkray** [comment]
any chance this can get added to the list of things for next release?

**Comment by deluan** [comment]
Not for the next (0.37.0), but I'll plan to add it for the following release (0.38.0)

**Comment by andrewzah** [comment]
Any progress on this?

**Comment by deluan** [comment]
I hope to have it working for next release.

**Comment by anarcat** [comment]
i actually can't figure out how to change my password, as admin or regular user. what am i missing?

**Comment by deluan** [comment]
@anarcat Here's the way, let me know if you are having any other issues:

https://user-images.githubusercontent.com/331353/124339087-c5251680-db79-11eb-84d8-9a146c724783.mov

**Comment by anarcat** [comment]
right okay, so i guess that's my problem: the "users" dropdown gives me a "Forbidden" error and doesn't load.

**Comment by anarcat** [comment]
after flushing the data directory (for #1225), this issue has gone away and i can see the user listing.
