### ISSUE TITLE
Tiled cover image for playlists (as on original subsonic server)

### ISSUE THREAD

**Issue by ghenry22** [navidrome/navidrome#1992]
### Is your feature request related to a problem? Please describe.

The original subsonic server (and direct forks like airsonic) generate a tiled coverart image for playlists using a random selection of album coverart based on the tracks included in the playlist.  The image is a 2x2 grid of covers.  If there are only tracks from less than 4 different albums in the playlist then the use a single album cover as the platlist coverart (random select).

This generates really nice looking artwork for playlists.

Navidrome currently uses the default blue vinyl image for playlists which makes them look like they are missing coverart.

### Describe the solution you'd like

Implement the same behaviour as the original subsonic server.

For a playlist, get coverArt property for each file sequentially until you have at least 4 unique ID's.  Generate a a coverArt image where the cover is a grid of the 4 covers.

If less than 4 unique coverArt ID's are found, use the first coverArt ID as the coverArt for the playlist.

### Describe alternative solutions that would also satisfy this problem

N/A

### Additional context

N/A

**Comment by TheWrathKing** [comment]
I think this would be a great addition but only if no image file is found alongside the playlist file (m3u or nsp) during the scan.
I would prefer having my own images for playlists (same name as playlist file with jpg or png extension)

**Comment by ghenry22** [comment]
assuming that navidrome is working similar to subsonic then playlists created through the webui or a client app will be stored in the database and not as files on the file system so they would never have sidecar image files.

**Comment by TheWrathKing** [comment]
I totally agree with an art priority in case of "physical" playlists (m3u or nsp) as it's already the case for CoverArtPriority.
It could be an option in the config file (PlaylistArtPriority) with default values "generated, cover.*, folder.*, front.*"

**Comment by deluan** [comment]
This was already suggested in the issue tracking [Playlist cover art](https://github.com/navidrome/navidrome/issues/406#issuecomment-1059928798). Please subscribe to that issue (#406), as I'm closing this as a duplicate.
