### ISSUE TITLE
Kee incompatibility

### ISSUE THREAD

**Issue by j4ncp** [navidrome/navidrome#1998]
### Description

**Background**: I am using the ["Kee" browser extension](https://addons.mozilla.org/en-US/firefox/addon/keefox/) which connects to a KeePass instance running on my desktop to auto-fill login formfields in the browser. Kee identifies the right formfields on the page by using include and exclude lists with terms to match the "id" and "name" fields of HTML input elements. The include lists contain terms such as "username", "name", etc., while the exclude list contains terms such as "search" and "query". Those lists contain a few terms by default (like the examples above), but can be edited by the user. Of course this matching is not perfect, but it generally works pretty well.

With Kee active, the login fields for my navidrome instance's login page are nicely auto-filled. However: once I get to main page, the search field in the upper left part of the page is auto-filled with my username. That, however, triggers the result list to update and display nothing, because nothing matches with my username. I can delete my username from the search field, but then the page updates again to show the new search results, which triggers Kee to auto-fill that form-field again, and again the page reloads to show no search results. Meaning: the search is not usable with Kee active.

A little bit of investigation yields that the reason for this behavior is that the search field in the HTML has the id and name properties both set to "name", which Kee matches with the username. So I think this behavior can be easily avoided by changing that name and id to "search" or "query" or something similarly appropriate. It is not a real bug and probably does not affect many people, but since it can be easily solved, I wanted to report it anyway.

### Steps to reproduce

1. Install Keepass and Kee on the computer you use to open the navidrome web UI
2. Store the credentials you use to log in to navidrome in Keepass, and add the navidrome URL there
3. Open navidrome URL in browser
4. -> log in should auto-fill, click log in
5. See the search filed being auto-filled with the username -> undesirable.

### Platform information

 - Navidrome version: 0.48.0, dockerized
 - Browser and version: Firefox 102.4.0esr
 - Operating System: Gentoo Linux 5.15.75

**Comment by deluan** [comment]
Thanks for reporting. I changed the `id` attribute but AFAICT, due to limitations in React-Admin's `SearchInput`, I can't easily change the `name` property. Let me know if this helps.

**Comment by j4ncp** [comment]
Will do, thanks!
