### ISSUE TITLE
level=warning msg="Request was interrupted" error="context canceled" path=stream 

### ISSUE THREAD

**Issue by tomerrr** [navidrome/navidrome#2000]
### Description

my log file shows this error and i have no idea why
level=warning msg="Request was interrupted" error="context canceled" path=stream

### Steps to reproduce
nothing special. Navidrome works normally, but i see this error all the time,
whether log=warn or log=debug or log=trace

### Platform information
`
 - Navidrome version: 0.48.0 (af5c2b5a)
 - Browser and version: 
 - Operating System: Debian 11 arm64 
### Additional information

Any other information that may be relevant or give context to the problem.

 - Screenshots (if applicable)?
 - Logs? 
`
navidrome[139403]: time="2022-11-18T11:18:57+02:00" level=warning msg="Request was interrupted" error="context canceled" path=stream`
 - Client used? Google Chrome 107.0.5304.110 64bit

**Comment by deluan** [comment]
Thanks for reporting. These are harmless debug information. In the next version they won't appear in Info level: 8f02daf337dce8a6bf899a78d2c1fc3a3a7a5bb9
