### ISSUE TITLE
Subsonic Apps Using Navidrome Not Scrobbling To Last.fm

### ISSUE THREAD

**Issue by JaxzKyd** [navidrome/navidrome#2005]
### Description

Some subsonic applications I'm using for Navidrome (Subtracks, Symfonium, Sonixd) aren't scrobbling to last.fm properly. Even though the albums I'm listening to are showing up in the "Recently Played" section in the web ui. 
Strangely, songs played from the webui and not one of the apps _is_ scrobbling to last.fm.

### Expected Behaviour

I expected the songs I listened to on my apps to properly scrobble to last.fm

### Steps to reproduce

1. Connect last.fm account to Navidrome and enable scrobbling
2. Connect to your Navidrome server via a subsonic-enabled app (I personally tried Subtracks, Symfonium, and Sonixd(Desktop))
3. Try and listen to a song from one of those apps and see if it scrobbles to last.fm

### Platform information

 - Navidrome version: v0.48.0
 - Symfonium version: 2.1.0
 - Subtracks version: 1.3.0
 - Sonixd version: v0.15.3

**Comment by K4r0qtuYNE5G4qgZ** [comment]
I don't know for sure, but could it be because the app that is playing it is also the one that has to do it?
If so you need to set-up scrobbling in Subtracks, Symfonium, and Sonixd because they are playing it not Navidrome.

**Comment by JaxzKyd** [comment]
[_navidrome-navidrome-1_logs.txt](https://github.com/navidrome/navidrome/files/10060285/_navidrome-navidrome-1_logs.txt)
These were my logs after restarting and playing a song from Sonixd

**Comment by deluan** [comment]
Looking at these logs:
```
time="2022-11-21T20:21:34Z" level=debug msg="HTTP: GET http://[REDACTED]/rest/getAlbumList2.view?type=recent&size=20&offset=0&order=desc&u=jaxz&s=[REDACTED]&t=[REDACTED]&v=1.13.0&c=sonixd&f=json" elapsedTime=37.6ms httpStatus=200 remoteAddr=154.16.57.150 requestId=d0a7f8ae08ec/o98D1pENr0-000029 responseSize=8400 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Sonixd/0.15.3 Chrome/91.0.4472.164 Electron/13.6.3 Safari/537.36"
time="2022-11-21T20:21:39Z" level=debug msg="API: New request /audio/rest/scrobble.view" client=sonixd requestId=d0a7f8ae08ec/o98D1pENr0-000030 username=jaxz version=1.13.0
time="2022-11-21T20:21:39Z" level=info msg="Registering new player" client=sonixd id=2f8209bb-b02e-4874-907c-97efd581a30e type=Sonixd/Windows username=jaxz
time="2022-11-21T20:21:39Z" level=error msg="SQL: `INSERT INTO player (client,id,ip_address,last_seen,max_bit_rate,name,report_real_path,scrobble_enabled,transcoding_id,user_agent,user_name) VALUES (?,?,?,?,?,?,?,?,?,?,?)`" args="['sonixd','2f8209bb-b02e-4874-907c-97efd581a30e','','2022-11-21T20:21:39.9693136Z',0,'sonixd [Sonixd/Windows]',false,true,'','Sonixd/Windows','jaxz']" elapsedTime=2.5ms error="FOREIGN KEY constraint failed" requestId=d0a7f8ae08ec/o98D1pENr0-000030 rowsAffected=0
time="2022-11-21T20:21:39Z" level=error msg="Could not register player" client=sonixd error="FOREIGN KEY constraint failed" username=jaxz
time="2022-11-21T20:21:39Z" level=debug msg="Scrobbling tracks" ids="[58d2e1d387f58056cded3921d7ca9025]" requestId=d0a7f8ae08ec/o98D1pENr0-000030 times="[]"
time="2022-11-21T20:21:39Z" level=debug msg="External scrobbling disabled for this player" ip= player= requestId=d0a7f8ae08ec/o98D1pENr0-000030 user=jaxz
```

ND is failing to register the player, which causes the player to not send scrobbles to external services (default behaviour).  Maybe this is related to this bug: https://github.com/navidrome/navidrome/issues/1928. Can you confirm your username (`jaxz`) matches the case in the DB (check the Users page)

**Comment by JaxzKyd** [comment]
> Maybe this is related to this bug: #1928 
> **Incorrect case in username in Subsonic API causes failure creating new player**
No... don't tell me....
*checks DB, uppercase J*
*checks every client I used, every time I logged in I used a lowercase j*
*fixes the case in the clients*
***every single client works***
I feel like an idiot. 😅 Good to know the case of the username matters!
