### ISSUE TITLE
Support pre-transcoding library

### ISSUE THREAD

**Issue by schpet** [navidrome/navidrome#2021]
### Problem

I'm always frustrated when I go to play a song and I see a lengthy loading indicator waiting for ffmpeg to transcode the file to an appropriate codec for my client. In my case I convert flac files to mp3 files for my phone, but stream flac without issue to my computer.

### Describe the solution you'd like

I would like the ability to transcode my library into the cache ahead of time. e.g. after running the sync task that discovers new files. If TranscodingCacheSize is smaller than the library, then maybe prioritize tracks or albums that are newly added, or by play count.

### Describe alternative solutions that would also satisfy this problem

- I can download a cached copy of my entire library with many clients (e.g. amperfy, subsonic) but this is not desirable when the library is larger than the size of the cache available to those clients
- I can wait for transcoding to finish, but it seems like the clients I use struggle and freeze waiting for this

### Additional context

- [Plex supports this type of behavior](https://support.plex.tv/articles/214079318-media-optimizer-overview/)
- reddit thread: ["can i transcode my entire library ahead of time?"](https://www.reddit.com/r/navidrome/comments/z73umv/can_i_transcode_my_entire_library_ahead_of_time/)

**Comment by dweymouth** [comment]
An issue I see with this is that clients can request a transcode of the file at any bitrate so it's possible that the pre-transcode may be unusable if you pre-transcode to MP3 320, for example, and your client requests 192. I think this would be best handled on the clients, by requesting the file slightly ahead of time of when playback would begin. (Obv. this only works when there are already tracks in the play queue) What clients do you use? Could you bring this request up to the client devs?

**Comment by schpet** [comment]
thanks for your thoughts on this @dweymouth, and supersonic is working well for me so thanks for that too!

closing out this issue given it seems like something that can be solved by clients.
