### ISSUE TITLE
Feature request: option to disable Last.fm and Musicbrainz link icons

### ISSUE THREAD

**Issue by emes81** [navidrome/navidrome#2022]
I'd prefer to have no links to external services in my collection.
This could also avoid potential confusion about the ND_LASTFM_ENABLED and ND_LISTENBRAINZ_ENABLED options - users could assume that these options are not working, as icons relating to both are still visible.

**Comment by blunderberg** [comment]
This and similar items have been brough up previously in various feature enhancement suggestions.
E.g. https://github.com/navidrome/navidrome/issues/1513 https://github.com/navidrome/navidrome/issues/1488
There are some (partial) workarounds and it sounds the external services will get looked at as part of future enhancements.

Below is just an example showing that the LastFM icon/link/button is shown even though both the external services and the LastFM integration are disabled.

![image](https://user-images.githubusercontent.com/83293651/213861889-b70dbd01-7c4b-489c-ad0a-3a248f4d25d6.png)

![image](https://user-images.githubusercontent.com/83293651/213861870-b31455dd-52f8-4437-9d9e-daa2a6fc9119.png)

...still, Navidrome is the best personal music streaming server on this planet.

**Comment by deluan** [comment]
Fixed this for next release. Now if you set the `EnableExternalServices` config option to `false` it will also disable all links in the UI.

@blunderberg to use it as an env var, the correct name is `ND_ENABLEEXTERNALSERVICES`, but it was not disabling the links before.

**Comment by blunderberg** [comment]
Amazing!
@deluan 
Thank you for fixing this and for pointing out the correct env var name - not sure why I used so many underscores.
I appreciate it.

**Comment by bbsixzz** [comment]
What about disabling the links but still allow scrobble? :)

**Comment by deluan** [comment]
> What about disabling the links but still allow scrobble? :)

Sorry, but this won't be supported. Disabling `EnableExternalServices` means disabling **all** communication with any external service.
