### ISSUE TITLE
Option to remove the placeholder artist image and the text "Biography not available" when external services disabled

### ISSUE THREAD

**Issue by emes81** [navidrome/navidrome#2023]
### Is your feature request related to a problem? Please describe.

I and other users do not connect to external services to get artist info. Hence our collections would never have artist bios.

### Describe the solution you'd like

Where external services are disabled, the text "Biography not available" is not shown, and no placeholder artist image is shown.

**Comment by deluan** [comment]
This was already addressed in the current version: 
- Biographies now are empty if there's no external services configured
- Artist images were not removed in this case, but you can provide your own as external files (see https://www.navidrome.org/docs/usage/artwork/#artists)
