### ISSUE TITLE
UI inconsistencies with 5 stars ratings

### ISSUE THREAD

**Issue by RedKage** [navidrome/navidrome#2028]
### Description

I am using `config.enableStarRating = true`.

My use case is:
- I have a smart playlist listing all the songs without a rating
- I often load that playlist and listen to these songs
- I rate the song
- The song is now rated, and disappears from the smart playlist
- My goal is to have listened to all the unrated songs
- I do this from my desktop mostly, but wish to be able to do this also from a mobile device using the native navidrome UI.

My issue: the 5-stars rating visiblity is not consistent, it's sometimes shown, sometimes not.

-----------------

On desktop, the 5-star ratings is visible almost everywhere.
But it's not visible on the player panel, even with a very wide width.

![0](https://user-images.githubusercontent.com/11867168/205495093-65592166-4ae6-406a-830c-523e88a125bd.png)

-----------------

On mobile, the-5 star ratings is almost never shown except in the songs list.

It's not visible in the `AlbumSongs`

![1](https://user-images.githubusercontent.com/11867168/205495144-8839fc91-0ecf-4730-8e5e-a8a5093fbf76.png)

-----------------

It's not visible in the Player overlay

![1a](https://user-images.githubusercontent.com/11867168/205495158-1e65a6b9-5ea1-4b29-a767-5896ff038bd4.png)

-----------------

It's not visible even visible in "desktop" with a width lower than about 960px:

![2](https://user-images.githubusercontent.com/11867168/205495227-09c10b6f-2c0c-4c71-abad-11aa12039224.png)

-----------------

Forcing  `config.enableStarRating = true` and  `config.config.enable Favourites= false` doesn't change anything.
The love button is gone, I have a blank space, but still not 5-star ratings.

### Expected Behaviour

I am expecting to see the 5-star ratings everywhere where it's supposed to be, regardless of the `isDesktop` value.
It's mostly a UI challenge as there is little space, and a mobile screen is also physically small making taping the stars a bit difficult with big fingers.

### Platform information

 - Navidrome version: 0.48.0 (af5c2b5a)

**Comment by deluan** [comment]
The current UI is not going to get any updates. I'm working on a new API/UI, and will make sure this inconsistence is addressed.
