### ISSUE TITLE
[Feature Request] Folder View

### ISSUE THREAD

**Issue by khromov** [navidrome/navidrome#2031]
I understand this has been discussed many times like in #739 and #1917 but all of the issues have been closed as "completed" when this is not the case.

### Is your feature request related to a problem? Please describe.

Not being able to see files in a tree view.

### Describe the solution you'd like

The solution has been described as difficult/impossible, but I would ask to consider that we don't need to rebuild the database layout to enable this solution. The `path` to each individual file is accessible in the database, so you could loop through all the paths and basically split by the path separator to generate path segments, eg: `/Rock/Artist/Album-1/song-1.mp3` => Split into `Rock > Artist > Album 1`. It might not be super fast but it can easily be cached or run as a background job during the scheduled scan. Finding songs inside the folder can be done with something like `SELECT * FROM songs WHERE path LIKE "/Rock/Artist/Album-1/%";` An index can be added to speed up performance.

### Describe alternative solutions that would also satisfy this problem

Tagging a big music library by hand, which is very time-intensive.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
If you already have that structure cleanly for every album and file you also could retag all in one go with Mp3Tag.

Filename-Tag `\%genre%\%albumartist%\%album%\%title%-%track%`

Which isn't so time-intensive and runs from alone over all files together.

But with that structure you gonna miss the individual artists of tracks for compilations, to also get those you gonna need a structure like:

Filename-Tag `\%genre%\%albumartist%\%album%\%track%-%artist%-%title%`

And you also gonna miss the multi- and sub-genres and the year, adding year to structure is easy...

Filename-Tag `\%genre%\%albumartist%\%year%\%album%\%track%-%artist%-%title%`

...but I guess adding multi- and sub-genres still gonna need some manual editing then.

**Comment by soup-eater** [comment]
this is what i [found ](https://flemmingss.com/use-folders-as-playlists-in-navidrome/)on the navidrome community tab

**Comment by Snippet24816** [comment]
Looking forward too for tree view like folder browsing as well

**Comment by deluan** [comment]
Sorry, but not planned: https://www.navidrome.org/docs/faq/#-can-you-add-a-browsing-by-folder-optionmode-to-navidrome

**Comment by darkpixel** [comment]
> "We have decided to focus on features that align with our vision of a music server"

Well that's unfortunate.

> If browsing by folder is an essential feature for you, there are [alternative music servers](https://github.com/basings/selfhosted-music-overview) that offer this functionality. We encourage you to explore these options if folder browsing is a priority.

That's nice of you to include a list of alternatives.

**Comment by tomasts248** [comment]
> Sorry, but not planned

Oh okey, thanks for confirming.

> That's nice of you to include a list of alternatives.

Agreed :)
