### ISSUE TITLE
Keep the relative order of an album after it gets updated

### ISSUE THREAD

**Issue by KingDuckZ** [navidrome/navidrome#2036]
### Is your feature request related to a problem? Please describe.

A common scenario I have is when I have to update the metadata of an album I already added to Navidrome in the past, for example because the info in MusicBrainz have changed, or because I'm re-encoding something, adding a missing replay gain or touching some audio files in general. When I do so, the updated album ends up at the top of the "recently added" list, as if it was really new, which bumps down all the recently added (for real) albums.

### Describe the solution you'd like

Once you add an album (say, with a given MusicBrainz ID, or a given title+albumartist+trackcount combo) Navidrome remembers it and doesn't shuffle it around even if it gets modified later in the future. For example:

1. In January I add album A, Navidrome finds it and saves it somewhere that it's been seen in January
2. In February I add album B, same as above happens
3. Later I modify the replay gain of album A, its cover art and some catalog numbers
4. In Navidrome, I expect to still see album B as having been added after album A
5. If I remove album A entirely, and say it's gone for a hardcoded or configurable amount of time, Navidrome forgets about it for good so that adding A again will cause Navidrome to act as if it's the first time it's been ever added

### Describe alternative solutions that would also satisfy this problem

I don't know, use the MusicBrainz ID if present, or a combination of metadata that shouldn't reasonably change. Disable the feature if none of this is possible (eg: no metadata). Store that info alongside the necessary timestamps in a db and reuse that timestamp when adding a new album that has a match in said database.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
I stumbled over the same issue, but this only applies for Recently Added anyway, because else Date/Time doesn't matter.
My Solution is to Preserve File Modification Times when altering files I already added.
This works fine, but then some changes need a Full Scan to be detected.

**Comment by KingDuckZ** [comment]
My syncthing touched every single file just this morning so that completely destroyed my "recently added" :( idk if I could have prevented that, but I had just swapped the syncthing directory and didn't expect it to touch at remote files since there was no change to their content.

**Comment by metalheim** [comment]
If the tags stay the same, a simple file touch shouldn't cause the albums to be re-added.
Only if the files competely disappear, or the Tags change significantly

**Comment by KingDuckZ** [comment]
It could be because I've got `RecentlyAddedByModTime = true` in my settings. I can change it to false but it won't fix the main problem.
