### ISSUE TITLE
Hotspot barely responds to tapping (Android)

### ISSUE THREAD

**Issue by fabpico** [navidrome/navidrome#2043]
### Description

Given I have the player opened and I minimize it by clicking on the close button, the player becomes a hotspot that I can drag it around.

![Capture](https://user-images.githubusercontent.com/4472725/207850625-9c81f80c-64b0-43dd-a081-05eb0aca841a.PNG)

When I try to reopen the player, meaning I tap on the hotspot, after releasing the thumb, the hotspot gets only moved by some pixels. As if a drag was intended.
I have to fast-repeat tapping about 10 times so that the player is being opened.

### Expected Behaviour

I would expect opening on first tap. To not conflict with the drag event, the drag event could just fire after touching for some milliseconds.

### Steps to reproduce

1. Open the player by playing a track
2. Minimize the player with the close icon
3. Tap on the player hotspot

### Platform information

 - Navidrome version: 0.48.0
 - Browser and version: Android Edge 107
 - Operating System: Ubuntu 20.04

### Additional information

Current workaround is to hard reload the page, so that the player gets opened on initialization, but this has been annoying for a while.

**Comment by fabpico** [comment]
I noticed that the player is not from Navidrome, it's an integration of https://github.com/lijinke666/react-music-player. And there is already an issue related to that https://github.com/lijinke666/react-music-player/issues/480. But the entire project seem to stall, the last commit was almost 2 years ago.

**Comment by deluan** [comment]
Yeah, we are currently using [a fork](https://github.com/navidrome/react-music-player), but we don't plan to do any further development on it.

I'll close this as we have plans to replace completely this player. For more info, follow #1651
