### ISSUE TITLE
webclient - Cover art is not updated until logout and login

### ISSUE THREAD

**Issue by glaubersm** [navidrome/navidrome#2044]
### Description

When I add or replace a cover art, the webclient does not show the new cover art until logout and login.

### Expected Behaviour

the webclient should update the cover art without logout and login.

### Steps to reproduce

1. login to the webclient
2. add or replace a covert art in your music collection
3. look for the correspondent album in the webclient and observe that its cover art was not updated. Even click on 'Refresh' button in the upper right corner does not update the cover art. The only solution is logout and login.

### Platform information

 - Navidrome version: navidrome-bin 0.48.0-1
 - Browser and version: Vivaldi 5.6.2867.46
 - Operating System: Arch Linux

### Additional information

Any other information that may be relevant or give context to the problem.

 - Screenshots (if applicable)?
 - Logs? 
 - Client used?

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Refresh only Refreshes the Page, you need to do a Quick Rescan or Full Rescan for Navidrome to see changes on files.

**Comment by glaubersm** [comment]
> Refresh only Refreshes the Page, you need to do a Quick Rescan or Full Rescan for Navidrome to see changes on files.

Doing a quick scan and then refreshing after editing an already indexed cover art does not work. The cover art is only updated in the webclient after logout and login.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
> > Refresh only Refreshes the Page, you need to do a Quick Rescan or Full Rescan for Navidrome to see changes on files.
> 
> Doing a quick scan and then refreshing after editing an already indexed cover art does not work. The cover art is only updated in the webclient after logout and login.

I don't have that issue, if I do a Quick Scan it updates the covers instantly in the WebUI even without manually refreshing.

The only case where a Quick Scan doesn't work for me, is if the File Modification Time has been preserved on changing Tags, Covers etc. Then a Full Scan is required to update them.

**Comment by metalheim** [comment]
I also don't have that issue, it works like @K4r0qtuYNE5G4qgZ describes for me.
@glaubersm One issue i could think of is: Do you maybe have reverse proxy inbetween, that does cache the images?

**Comment by glaubersm** [comment]
I do not use a proxy. After more tests, I noticed that the problem is intermittent.
The weblclient updates as expected a few seconds after I copy/move a folder containing audio files and the cover art file to my music collection. But the cover art is not always updated if I add a cover art to an already indexed folder that contains no cover art yet, replace or edit a covert art located in an already indexed folder. Sometimes the webclient updates the cover art after quick scan and refresh and rarely without any manual intervention, but I need to log out and log in often. I have no idea what is going on. My music collection is located in a ntfs partition mounted with ntfs3 driver, if it matters.
