### ISSUE TITLE
Rapid graphic shaking/resizing while viewing certain artists.

### ISSUE THREAD

**Issue by coreyaboy** [navidrome/navidrome#2049]
### Description

Web Player view of artist discography shakes violently when certain combinations of screen size, artist bio length, and number of albums are present. This is being caused by the artist bio text being expanded, causing the album art to move down the screen just enough to make the browser think it needs to produce a scroll bar.  Upon rendering the scroll bar, the scroll bar subtracts from the screen space available to the app, the artist bio and album art are repositioned accordingly, and upon reaching their new positions the browser determins that a scroll bar is not necessary, and de-renders it. All on-screen elements reflow to make use of the space that the scroll bar no longer occupies, and the combination of states that triggered the scroll bar rendering become satisfied again, and a rapid cycle of bouncing graphics/text around the screen while drawing/erasing the scroll bar begins.

### Expected Behaviour

Not that.

### Steps to reproduce

1. Start out in a Chrome browser windows of 1920x2160 pixels, on a windows 10 computer with the UI scale set to 150%
2. Viewing an artist page with a biographical blurb of 469 characters containing 9 albums. (Actual number of characters and albums needed to trigger may be different. This is just the size of the bio text and number of albums I had on screen when I produced this result)
3. Notice that the artist description blurb is truncated and can be expanded. Click on the text block to expand it.
4. Don't have epilepsy while seeing the error condition.

### Platform information

 - Navidrome version: 0.48.0 (af5c2b5a)
 - Browser and version: 108.0.5359.125 (Official Build) (64-bit)
 - Operating System: Ubuntu 22.04.1 LTS - using official docker image

### Additional information

Don't know if it's relevant, but I recently added my last.fm and spotify API keys to the config.

 - Screenshots: See attached video file?
 - Client used? The standard web client.

https://user-images.githubusercontent.com/39365396/208319320-1ac950e9-f0e3-4074-a5ae-c431531ef36b.mp4

**Comment by deluan** [comment]
Thanks for the report! This is caused by the current implementation of the Album Grid. This may also happen in other situations. 

I started working on rewriting parts of the UI with React-Admin 4, and will rewrite this grid from scratch, not using the current scaling solution, which causes the flickering.

**Comment by coolguy001tv** [comment]
It's still happening in 0.49.3.
Using win11 with chrome 119.
Workaround can be changing browser width/height, or in my situation, changing "Items per page" from default 36 to 18.
Here's  picture taken by my mobile phone.
![flicker](https://github.com/navidrome/navidrome/assets/936825/84ba0827-d9b0-41e1-bbf4-8b4ef1c11945)
