### ISSUE TITLE
"Remember password" option in login screen

### ISSUE THREAD

**Issue by flemmingss** [navidrome/navidrome#2052]
Today there is no option to select "remember password" or "Keep me logged in".
This should be implemented so re-typing credentials is avoided.

**Comment by deluan** [comment]
That's the actual current behaviour, to keep you logged in. The session timeout is only 24 hours by default, but you can increase by setting the [config option](https://www.navidrome.org/docs/usage/configuration-options/) `SessionTimeout` to a higher number. Mine is set to `"120h"`
