### ISSUE TITLE
How to change the size of the album picture? and why?

### ISSUE THREAD

**Issue by JadeVane** [navidrome/navidrome#2056]
### Description

I'm making a theme to my liking, based on the syntax of other theme files. After making a js file as a new theme, I did change some styles, but I found that some styles don't seem to apply in a common and easy way.

The general approach is to add css styles here:

```js
export default {
}
```

It works for most style whose name start with a capital letter and are joined by `-`, for example, `MuiPopover-paper`, It is easy to understand and easy to use.

> In this regard, I have a question that may deviate from the meaning of the topic, why do we must to set the css style through js? What was the reason for having to go through such a roundabout way?

Of course, if things were really going so well, this little complaint wouldn't make me post this issue here, unfortunately, I found that the names of some styles seem to be different, such as `jss21`.

It's confusing, these names formed by random numbers cannot find the source for modification in a easy way, and by combining multiple theme files and searching keywords at the same time, I finally found that this part of the style needs to be modified in another structure

```js
const musicListActions = {
  '@global': {
    button: {
      ...
    }
  }
}
```

Such a rule increases the difficulty. Sometimes I just need to modify the style of some of the buttons, but I have to change the style of all the buttons together, and then exclude some exceptions by other methods, which adds extra workload.

This was more of a hassle, it eventually worked out, but I've now run into another problem and after spending a whole day still unable to solve it, I'm posting this issue.

![图片](https://user-images.githubusercontent.com/34258753/209496742-a22d1ed3-371f-4a1e-93da-1c71f74f2079.png)

The settings files for these styles are located in `ui/src/album/AlbumDetails.js`, yes, not inside the theme folder, and the structure is also not common to other themes:

```js
const useStyles = makeStyles(
  (theme) => ({
    coverParent: {
      [theme.breakpoints.down('xs')]: {
        height: '8em',
        width: '8em',
        minWidth: '8em',
      },
      [theme.breakpoints.up('sm')]: {
        height: '10em',
        width: '10em',
        minWidth: '10em',
      },
      [theme.breakpoints.up('lg')]: {
        height: '15em',
        width: '15em',
        minWidth: '15em',
      },
    },
  }),
  {
    name: 'NDAlbumDetails',
  }
)
```

I tried to add this part of the content to the js theme file under the theme folder, but an error was reported:

```
[eslint] 
src/themes/allure.js
  Line 651:19:  'makeStyles' is not defined  no-undef
```

So how do i change the size of the album art?

Sorry to spend so much time complaining, but I still don't understand why do you making theme rules so complicated. The playback action bar at the bottom is a third-party plug-in, so it needs to be imported in a way similar to `theme-name.css.js` which is acceptable, but why do other parts need to do this?

### Expected Behaviour

1. Change the size of the album art via theme files.
2. Provide a documentation that clearly describes how to make a theme, rather than “See the existing themes for examples.”

### Platform information

 - Navidrome version: `v0.48.0`
 - Browser and version: `Firefox v104.0.1`
 - Operating System: `Ubuntu 22.04`

**Comment by kgarner7** [comment]
`makeStyles` is a Material UI thing, which you would need to import. This is a bit weird to import in a theme, which really just defines some CSS (via JavaScript). 

These `makeStyles` calls are for custom CSS on certain components. For some of these calls, they are given a name.

```JavaScript
// The same snippet for AlbumDetails
const useStyles = makeStyles(
  (theme) => ({
    // text beforehand
    coverParent: {
      [theme.breakpoints.down('xs')]: {
        height: '8em',
        width: '8em',
        minWidth: '8em',
      },
      [theme.breakpoints.up('sm')]: {
        height: '10em',
        width: '10em',
        minWidth: '10em',
      },
      [theme.breakpoints.up('lg')]: {
        height: '15em',
        width: '15em',
        minWidth: '15em',
      },
    },
    // text after...
  }),
  {
    name: 'NDAlbumDetails', // pay attention to this name
  }
)
```
Named styles can actually be overridden. Take a look at `nord.js`
```JavaScript
export default {
  themeName: 'Nord',
  // ... some text
  overrides: {
    // some more properties
    NDALbumDetails: {
      root: {
        background: '#434C5E',
        borderRadius: 0,
        boxShadow: '0 8px 8px rgb(0 0 0 / 20%)',
      },
      // additional properties for album details
    },
    // additional overrides
  }
```
Here, certain parts of album details are being overridden. You should be able to do a similar thing by just adding a `coverParent` property in this section.

**Comment by JadeVane** [comment]
Yes, other parts are changed in this way, but this method does not seem to apply to additional style definitions such as `[theme.breakpoints.up('lg')]`:

```
  Line 482:10:  'theme' is not defined  no-undef
```

Or is there a syntax error in what I've added?

```js
overrides: {
  ...
  NDAlbumDetails: {
    coverParent: {
      [theme.breakpoints.up('lg')]: {
        height: '13em',
        width: '13em',
        minWidth: '13em',
      },
    },
  },
  ...
},
```

**Comment by kgarner7** [comment]
Yeah, `theme` doesn't exist. Without some reworking, I doubt that will change.
It's not pretty, but you can do a work-around and explicitly write out the media queries (e.g. `theme.breakpoints.down('xs')` -> `@media (max-width:599.95px)`)

**Comment by JadeVane** [comment]
I don't understand this part of the grammar enough. It seems impossible to directly replace the content. Is there a simple example?

```
overrides: {
  ...
  NDAlbumDetails: {
    coverParent: {
      [@media (min-width: 1280px)]: {
        height: '13em',
        width: '13em',
        minWidth: '13em',
      },
    },
  },
  ...
},
```

it show some error below:

```
SyntaxError: ... : Support for the experimental syntax 'decorators' isn't currently enabled (482:10):
  480 |       },
  481 |       coverParent: {
> 482 |         [@media (min-width: 1280px)]: {
      |          ^
  483 |           height: '13em',
  484 |           width: '13em',
  485 |           minWidth: '13em',
```

**Comment by kgarner7** [comment]
`@media (max-width:599.95px)` is the string value returned from the `xs` breakpoint. To override it, you would need to pass that in also as a string (`["@media (min-width: 1280px)"]:`). It's complaining because the `@` operation is for decotators, not a string.

**Comment by JadeVane** [comment]
It works. Thanks for the reply.

Although the problem is finally solved, I still hope that the team can consider providing a more unified way for others to develop new themes and make navidrome better.

But anyway, there is no doubt that navidrome is a great project, thank you for developing this project.
