### ISSUE TITLE
Navidrome won't start at boot

### ISSUE THREAD

**Issue by dln949** [navidrome/navidrome#2057]
I am running Navidrome 0.48.0 on ubuntu desktop 22.04 (wayland).  

When I issue the command sudo systemctl enable navidrome.service, at system boot starting the navidrome service fails with the error, "bind: cannot assign requested address".  Strangely, when I disable the navidrome.service, and in /etc/systemd/system I create (and enable) a simple "timed delay" systemd service for navidrome that actually triggers the navidrome service after a one minute delay, all works great.  But I'd rather not have to have such a workaround.  

Why won't the navidrome service start at boot on my machine?

**Comment by andrewgdunn** [comment]
Likely one of two things:
 - your networking isn't coming up before systemd is attempting to start the service
 - something else is binding to that port before navidrome (use `ss -tupln` to figure that out)
 
 Post your configuration that your starting navidrome with.

**Comment by dln949** [comment]
I'm not exactly sure what you're asking to see, tell me if I'm interpreting you correctly.  

The contents of /etc/systemd/system/navidrome.service:  

`
[Unit]
Description=Navidrome Music Server and Streamer compatible with Subsonic/Airsonic
After=remote-fs.target network.target
AssertPathExists=/var/lib/navidrome

[Install]
WantedBy=multi-user.target

[Service]
User=main19
Group=main19
Type=simple
ExecStart=/opt/navidrome/navidrome --configfile "/var/lib/navidrome/navidrome.toml"
WorkingDirectory=/var/lib/navidrome
TimeoutStopSec=20
KillMode=process
Restart=on-failure

# See https://www.freedesktop.org/software/systemd/man/systemd.exec.html
DevicePolicy=closed
NoNewPrivileges=yes
PrivateTmp=yes
PrivateUsers=yes
ProtectControlGroups=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
RestrictNamespaces=yes
RestrictRealtime=yes
SystemCallFilter=~@clock @debug @module @mount @obsolete @reboot @setuid @swap
ReadWritePaths=/var/lib/navidrome

# You can uncomment the following line if you're not using the jukebox This
# will prevent navidrome from accessing any real (physical) devices
#PrivateDevices=yes

# You can change the following line to `strict` instead of `full` if you don't
# want navidrome to be able to write anything on your filesystem outside of
# /var/lib/navidrome.
ProtectSystem=full

# You can uncomment the following line if you don't have any media in /home/*.
# This will prevent navidrome from ever reading/writing anything there.
ProtectHome=true
`

The contents of /etc/systemd/system/navidrome.timer:  

`# navidrome.timer
[Unit] 
Description=Runs the navidrome.service 1 minute after boot up

[Timer] 
OnBootSec=1 m 
Unit=navidrome.service 

[Install] 
WantedBy=basic.target
`

**Comment by andrewgdunn** [comment]
> something else is binding to that port before navidrome (use ss -tupln to figure that out)

**Comment by dln949** [comment]
Output of that command you suggested:  

`main19@system19:~$ ss -tupln
Netid State  Recv-Q Send-Q                   Local Address:Port    Peer Address:Port                                                                            Process                                                                         
udp   UNCONN 0      0                            127.0.0.1:53696        0.0.0.0:*                                                                                users:(("rygel",pid=2037,fd=14))                                               
udp   UNCONN 0      0                              0.0.0.0:5353         0.0.0.0:*                                                                                                                                                               
udp   UNCONN 0      0                              0.0.0.0:46394        0.0.0.0:*                                                                                                                                                               
udp   UNCONN 0      0                              0.0.0.0:39138        0.0.0.0:*                                                                                                                                                               
udp   UNCONN 0      0                              0.0.0.0:7359         0.0.0.0:*                                                                                                                                                               
udp   UNCONN 0      0                            127.0.0.1:56608        0.0.0.0:*                                                                                                                                                               
udp   UNCONN 0      0                         192.168.1.19:56932        0.0.0.0:*                                                                                users:(("rygel",pid=2037,fd=17))                                               
udp   UNCONN 0      0                        127.0.0.53%lo:53           0.0.0.0:*                                                                                                                                                               
udp   UNCONN 0      0                              0.0.0.0:111          0.0.0.0:*                                                                                                                                                               
udp   UNCONN 0      0                        192.168.1.255:137          0.0.0.0:*                                                                                                                                                               
udp   UNCONN 0      0                         192.168.1.19:137          0.0.0.0:*                                                                                                                                                               
udp   UNCONN 0      0                              0.0.0.0:137          0.0.0.0:*                                                                                                                                                               
udp   UNCONN 0      0                        192.168.1.255:138          0.0.0.0:*                                                                                                                                                               
udp   UNCONN 0      0                         192.168.1.19:138          0.0.0.0:*                                                                                                                                                               
udp   UNCONN 0      0                              0.0.0.0:138          0.0.0.0:*                                                                                                                                                               
udp   UNCONN 0      0                              0.0.0.0:57630        0.0.0.0:*                                                                                                                                                               
udp   UNCONN 0      0                              0.0.0.0:49582        0.0.0.0:*                                                                                                                                                               
udp   UNCONN 0      0                              0.0.0.0:631          0.0.0.0:*                                                                                                                                                               
udp   UNCONN 0      0                            127.0.0.1:964          0.0.0.0:*                                                                                                                                                               
udp   UNCONN 0      0                              0.0.0.0:33839        0.0.0.0:*                                                                                                                                                               
udp   UNCONN 0      0                         192.168.1.19:50837        0.0.0.0:*                                                                                                                                                               
udp   UNCONN 0      0                              0.0.0.0:50873        0.0.0.0:*                                                                                                                                                               
udp   UNCONN 0      0                              0.0.0.0:1900         0.0.0.0:*                                                                                users:(("java",pid=3991,fd=25))                                                
udp   UNCONN 0      0                              0.0.0.0:1900         0.0.0.0:*                                                                                                                                                               
udp   UNCONN 0      0                      239.255.255.250:1900         0.0.0.0:*                                                                                users:(("rygel",pid=2037,fd=16))                                               
udp   UNCONN 0      0                         192.168.1.19:1900         0.0.0.0:*                                                                                users:(("rygel",pid=2037,fd=15))                                               
udp   UNCONN 0      0                      239.255.255.250:1900         0.0.0.0:*                                                                                users:(("rygel",pid=2037,fd=13))                                               
udp   UNCONN 0      0                            127.0.0.1:1900         0.0.0.0:*                                                                                users:(("rygel",pid=2037,fd=12))                                               
udp   UNCONN 0      0                         192.168.1.19:59354        0.0.0.0:*                                                                                users:(("java",pid=3991,fd=45))                                                
udp   UNCONN 0      0                              0.0.0.0:44325        0.0.0.0:*                                                                                                                                                               
udp   UNCONN 0      0                                [::1]:36812           [::]:*                                                                                users:(("rygel",pid=2037,fd=20))                                               
udp   UNCONN 0      0                                 [::]:53991           [::]:*                                                                                                                                                               
udp   UNCONN 0      0                                 [::]:5353            [::]:*                                                                                                                                                               
udp   UNCONN 0      0                                 [::]:47876           [::]:*                                                                                                                                                               
udp   UNCONN 0      0       [fe80::bff:9785:7887:76e]%eno1:49109           [::]:*                                                                                users:(("rygel",pid=2037,fd=23))                                               
udp   UNCONN 0      0                                 [::]:111             [::]:*                                                                                                                                                               
udp   UNCONN 0      0                                 [::]:33181           [::]:*                                                                                                                                                               
udp   UNCONN 0      0                                 [::]:33474           [::]:*                                                                                                                                                               
udp   UNCONN 0      0                [::ffff:192.168.1.19]:49904              *:*                                                                                users:(("java",pid=1530,fd=20))                                                
udp   UNCONN 0      0                                 [::]:50103           [::]:*                                                                                                                                                               
udp   UNCONN 0      0                                    *:1900               *:*                                                                                users:(("java",pid=1530,fd=18))                                                
udp   UNCONN 0      0                                [::1]:1900            [::]:*                                                                                users:(("rygel",pid=2037,fd=18))                                               
udp   UNCONN 0      0                            [ff05::c]:1900            [::]:*                                                                                users:(("rygel",pid=2037,fd=19))                                               
udp   UNCONN 0      0       [fe80::bff:9785:7887:76e]%eno1:1900            [::]:*                                                                                users:(("rygel",pid=2037,fd=21))                                               
udp   UNCONN 0      0                       [ff02::c]%eno1:1900            [::]:*                                                                                users:(("rygel",pid=2037,fd=22))                                               
udp   UNCONN 0      0                                 [::]:43579           [::]:*                                                                                                                                                               
tcp   LISTEN 0      64                             0.0.0.0:43391        0.0.0.0:*                                                                                                                                                               
tcp   LISTEN 0      5                              0.0.0.0:8000         0.0.0.0:*                                                                                users:(("mpd",pid=3125,fd=24))                                                 
tcp   LISTEN 0      512                            0.0.0.0:8096         0.0.0.0:*                                                                                                                                                               
tcp   LISTEN 0      10                        192.168.1.19:41217        0.0.0.0:*                                                                                users:(("rygel",pid=2037,fd=25))                                               
tcp   LISTEN 0      64                             0.0.0.0:2049         0.0.0.0:*                                                                                                                                                               
tcp   LISTEN 0      4096                           0.0.0.0:37541        0.0.0.0:*                                                                                                                                                               
tcp   LISTEN 0      50                        192.168.1.19:5001         0.0.0.0:*                                                                                users:(("java",pid=3991,fd=46))                                                
tcp   LISTEN 0      50                             0.0.0.0:9001         0.0.0.0:*                                                                                users:(("java",pid=3991,fd=16))                                                
tcp   LISTEN 0      50                             0.0.0.0:9002         0.0.0.0:*                                                                                users:(("java",pid=3991,fd=22))                                                
tcp   LISTEN 0      5                         192.168.1.19:6602         0.0.0.0:*                                                                                users:(("mpd",pid=3125,fd=9))                                                  
tcp   LISTEN 0      50                             0.0.0.0:139          0.0.0.0:*                                                                                                                                                               
tcp   LISTEN 0      4096                           0.0.0.0:43919        0.0.0.0:*                                                                                                                                                               
tcp   LISTEN 0      4096                           0.0.0.0:111          0.0.0.0:*                                                                                                                                                               
tcp   LISTEN 0      4096                      192.168.1.19:4533         0.0.0.0:*                                                                                                                                                               
tcp   LISTEN 0      4096                           0.0.0.0:52149        0.0.0.0:*                                                                                                                                                               
tcp   LISTEN 0      4096                     127.0.0.53%lo:53           0.0.0.0:*                                                                                                                                                               
tcp   LISTEN 0      128                          127.0.0.1:631          0.0.0.0:*                                                                                                                                                               
tcp   LISTEN 0      10                           127.0.0.1:46073        0.0.0.0:*                                                                                users:(("rygel",pid=2037,fd=11))                                               
tcp   LISTEN 0      50                             0.0.0.0:445          0.0.0.0:*                                                                                                                                                               
tcp   LISTEN 0      4096                           0.0.0.0:44061        0.0.0.0:*                                                                                                                                                               
tcp   LISTEN 0      10                               [::1]:35743           [::]:*                                                                                users:(("rygel",pid=2037,fd=26))                                               
tcp   LISTEN 0      64                                [::]:2049            [::]:*                                                                                                                                                               
tcp   LISTEN 0      10      [fe80::bff:9785:7887:76e]%eno1:45477           [::]:*                                                                                users:(("rygel",pid=2037,fd=27))                                               
tcp   LISTEN 0      4096                              [::]:37703           [::]:*                                                                                                                                                               
tcp   LISTEN 0      50               [::ffff:192.168.1.19]:4041               *:*                                                                                users:(("java",pid=1530,fd=19))                                                
tcp   LISTEN 0      64                                [::]:40841           [::]:*                                                                                                                                                               
tcp   LISTEN 0      4096                              [::]:56523           [::]:*                                                                                                                                                               
tcp   LISTEN 0      50                                [::]:139             [::]:*                                                                                                                                                               
tcp   LISTEN 0      10                                   *:5900               *:*                                                                                users:(("gnome-remote-de",pid=1203,fd=16))                                     
tcp   LISTEN 0      4096                              [::]:46415           [::]:*                                                                                                                                                               
tcp   LISTEN 0      4096                              [::]:111             [::]:*                                                                                                                                                               
tcp   LISTEN 0      100                                  *:8080               *:*                                                                                users:(("java",pid=1530,fd=33))                                                
tcp   LISTEN 0      4096                              [::]:55571           [::]:*                                                                                                                                                               
tcp   LISTEN 0      128                              [::1]:631             [::]:*                                                                                                                                                               
tcp   LISTEN 0      511                                  *:3000               *:*                                                                                users:(("mstream",pid=1502,fd=71))                                             
tcp   LISTEN 0      511                                  *:44923              *:*                                                                                users:(("apache2",pid=2092,fd=4),("apache2",pid=2091,fd=4),("apache2",pid=2090,fd=4))
tcp   LISTEN 0      10                                   *:3389               *:*                                                                                users:(("gnome-remote-de",pid=1203,fd=14))                                     
tcp   LISTEN 0      50                                [::]:445             [::]:*                                                                                                                                                               
main19@system19:~$ `

**Comment by tdm4** [comment]
Hi,

  I get this problem too, on OpenBSD. I think that the network isn't quite ready when Navidrome starts so it just quits. When my OpenBSD machine boots up it has to associate with a WiFi AP and then get a DHCP address and this doesn't happen very fast.

   This happens on 0.49.3.

**Comment by tdm4** [comment]
An update.. I've upgraded to 0.50.1 and the problem has gone away now.
Has the code changed between 0.49.x and 0.50.1 with regards to sockets/listening addresses?
