### ISSUE TITLE
How does lyrics in web-ui even work?

### ISSUE THREAD

**Issue by YSPESHNUY** [navidrome/navidrome#2059]
I'm struggling to get the thing working. I don't get what I'm missing. Synced lyrics are working in android's Symfonium, but not in the web-ui.

**Comment by YSPESHNUY** [comment]
Found the solution

**Comment by deluan** [comment]
Hey, sorry for not replying earlier. Can you please describe the solution, so others having the same issue can benefit from it? Thanks!

**Comment by YSPESHNUY** [comment]
> Hey, sorry for not replying earlier. Can you please describe the solution, so others having the same issue can benefit from it? Thanks!

Sure. I found the solution completely by accident. The timestamp should be formatted like this
![timestamp](https://user-images.githubusercontent.com/79416318/210174538-39dd3a0c-082d-490e-9811-bf86b11019d3.jpg)

I couldn't find any info about lyrics requirements in navidrome resources. If it's not there, I think you should mention it.

**Comment by kpcenti** [comment]
Where do you place the synced lyrics?

**Comment by YSPESHNUY** [comment]
> Where do you place the synced lyrics?

You need to place text to track tag named "Lyrics". And for that, brother, you need any tag editor. Musicbrainz picard, for example.

**Comment by kpcenti** [comment]
Thanks. I wasn't sure since there wasn't documentation on it from Navidrome (that I could find) and Lyrics isn't really the suggested Vorbis Comments.
