### ISSUE TITLE
Make imported playlists public by default

### ISSUE THREAD

**Issue by john8329** [navidrome/navidrome#2065]
Just a quick note on a counterintuitive behavior of Navidrome (the rest is excellent, good job), when playlists are imported from .m3u, they're visible only to the admin user, and not others. I found out it's due to them being "private".

I think it makes a lot more sense to have them public by default, unless they're created by the user, since music already is, and both are imported from the same source. At least a configuration parameter to control that would be useful.

Another possible configuration parameter is to delete unmatched synced playlists, so if they're removed from the origin they don't clutter the program and don't require manual removing. This would enhance a lot the experience of importing playlists IMO, since the program would just be a reader.

**Comment by RealStickman** [comment]
bump, this feature request is still relevant

**Comment by john8329** [comment]
I might give a try at implementing this since I'm familiar with the language, but it'd be at least nice to know if the feature would be actually accepted as a pull request.

**Comment by deluan** [comment]
Hey @john8329, sorry for the delay, this slipped through the cracks :)

I think both suggestions are good. If you are still interested, let me know if you want to tackle this.

**Comment by john8329** [comment]
Oh hey, why not, I'll try to tackle this in the next days if I get the environment working in the IDE.

**Comment by john8329** [comment]
*eons have passed* okay I got the environment working, and I've implemented the first fix. I can't think of a use case where somebody doesn't want playlists as public but I've implemented the flag anyway, setting it as true by default.

Should I fork the project and make a PR or just send a patch?

**Comment by deluan** [comment]
Hey @john8329, if you want to work on this, go ahead and please implement a `DefaultPlaylistPublicVisibility=true|false` config option. I'm ok with the default being `true`.

The best way to work on this is to create a PR from your fork.

**Comment by john8329** [comment]
All right, just one question, I don't see a production Dockerfile, and there's no documentation about how to generate docker images. I'd like to test these features on my instance before creating a PR. Any hint?
Thanks

**Comment by crazygolem** [comment]
> All right, just one question, I don't see a production Dockerfile, and there's no documentation about how to generate docker images. I'd like to test these features on my instance before creating a PR. Any hint? Thanks

You can make a fork of the repository and open a PR against it. The same workflow as upstream will trigger and build an image and push it to a registry.

You need to set the repository secrets `DOCKER_IMAGE`, `DOCKER_USERNAME` and `DOCKER_PASSWORD` to a Docker Hub account, and then your image will get pushed to Docker Hub and `ghcr.io/username/repository`. You will then be able to pull the image from `ghcr.io/crazygolem/navidrome:pr-X`.

In principle the `DOCKER_*` secrets should not be needed to push to ghcr, but the way the workflow is written the image won't even be built if `DOCKER_IMAGE` is missing (check the [docker job in pipeline.yml](https://github.com/navidrome/navidrome/blob/master/.github/workflows/pipeline.yml#L142)).

If you're only interested in how the image is built to do it manually, check the Dockerfile [pipeline.dockerfile](https://github.com/navidrome/navidrome/blob/master/.github/workflows/pipeline.dockerfile).

And thanks for working on it, I'm looking forward to this feature =)

**Comment by deluan** [comment]
@john8329 any news? To make it easier to build a docker image, I just added a make target to build the image locally: https://github.com/navidrome/navidrome/commit/7f551a79328e0781b78d537aa88abcb1d4e9442a

Let me know if this helps

**Comment by john8329** [comment]
@deluan hey sorry for being unresponsive, taking a long trip right now, I'll be back in a few weeks. Thanks

**Comment by krasen1234** [comment]
any update on this?

**Comment by john8329** [comment]
My bad, I lost the event in the calendar. Here's the PR, sorry for the wait. https://github.com/navidrome/navidrome/pull/3143

**Comment by deluan** [comment]
Closing this as resolved, with the introduction of the `DefaultPlaylistPublicVisibility` config option in #3143.
