### ISSUE TITLE
UI/Subsonic API: Some diacritic marks aren't ignored in search text matching

### ISSUE THREAD

**Issue by dweymouth** [navidrome/navidrome#2070]
### Is your feature request related to a problem? Please describe.

It can be hard to search for artists, albums, etc. that have diacritics in their names, like ~~"Sigur Rós" or~~ "Dvořák". 

### Describe the solution you'd like

I have no idea how feasible this is, but it would be nice if searching for ~~"Sigur Ros"~~ or "Dvorak" would match. Obviously this only would apply to artist/track/etc names using the Latin alphabet.

**Comment by deluan** [comment]
This is the current behaviour:

<img width="805" alt="Screen Shot 2023-01-11 at 11 28 14 PM" src="https://user-images.githubusercontent.com/331353/211976322-ca919878-5314-4352-9cd2-4303f73cc6fa.png">

Maybe you have a different issue? Can you check the logs to see if anything unusual shows up?

**Comment by dweymouth** [comment]
Actually I confirmed that Sigur Ros searches just fine. I think it's specifically the ř in Dvořák that isn't matched by the "r" character. I don't know the name of that diacritic mark but maybe it could be added to the set of ignored diacritics (or however it's implemented). I'm also still running a 6-month or so old build of navidrome, so maybe it's fixed now and I don't even know it :)

**Comment by deluan** [comment]
I was using the https://github.com/kennygrant/sanitize package, but it is not actively developed anymore, so I forked it and added the `ř` diacritic mark. If you find any other chars that should be converted, let me know. The current list is here: https://github.com/deluan/sanitize/blob/master/sanitize.go#L218

**Comment by dweymouth** [comment]
I have another request here: it seems that the "ä" character maps to "ae" in the sanitize library, and "ö" to "oe" which means when searching for an artist like "Björk" or "Arvo Pärt", it's matched by "Bjoerk" and "Arvo Paert". This seems unintuitive to me and I think "ä" and "ö" should map to "a" and "o" instead of (or maybe in addition to?) "ae"/"oe"

**Comment by dweymouth** [comment]
I opened a PR here: https://github.com/deluan/sanitize/pull/1

**Comment by deluan** [comment]
Thanks!
