### ISSUE TITLE
Artists‘ photo cannot be display

### ISSUE THREAD

**Issue by MercuryLoveShapa** [navidrome/navidrome#2071]
![image](https://user-images.githubusercontent.com/52125806/211203625-3bb0271e-4dde-46db-8e38-fa3476d2ec63.png)
![image](https://user-images.githubusercontent.com/52125806/211204421-1dc10897-bce0-4e1c-9266-6c30f592ceb8.png)

**Comment by kgarner7** [comment]
That's the default image Last.FM returns when there is no artist image. Not sure why it happens here, but I can confirm that's what the API gives when I search Imagine Dragons.

**Comment by sphars** [comment]
From what I can see, in the HTML, the `title` attribute should be the artist name (in this case it should be "Imagine Dragons"), looks like it's not picking it up as expected for you. Possibly a metadata issue? 

It's working fine for me:   

![image](https://user-images.githubusercontent.com/18315081/211667527-79e26d10-4298-4e2a-8c8b-36132aff745c.png)

**Comment by kgarner7** [comment]
Yeah, that's my bad. This does require spotify API. Try checking the logs for something like `Artist not found in Spotify` or `Error calling Spotify` and see what name it shows.

**Comment by NiNiyas** [comment]
I  am having the same issue, `level=warning msg="Artist not found in Spotify" artist="Novo Amor"`. I have set spotify api currectly according to the docs but none of my artists have images. 

Navidrome: [0.48.0](https://github.com/navidrome/navidrome/releases/tag/v0.48.0) (af5c2b5a)
Browser: Librewolf 105.0.3-1
Operating System: 22.04.1 LTS (GNU/Linux 5.15.0-1021-raspi aarch64), Docker 20.10.22, build 3a2c30b

Debug logs:
```
time="2023-01-14T14:32:46Z" level=warning msg="Artist not found in Spotify" artist="Novo Amor" requestId=e07ba196149e/76SeZmyyl5-000018
time="2023-01-14T14:32:46Z" level=debug msg="Got Images" agent=placeholder artist="Novo Amor" elapsed=4.5ms images="[{https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png 300} {https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png 174} {https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png 64}]" requestId=e07ba196149e/76SeZmyyl5-000018
```

**Comment by deluan** [comment]
@MercuryLoveShapa, as @kgarner7 explained you need to configure the Spotify API to retrieve artist's images: https://www.navidrome.org/docs/usage/external-integrations/#spotify

@NiNiyas: Could be an invisible chars in the name. Can you send me one file of this artist? If yes, send it to `deluan @ navidrome.org`. Thanks

**Comment by NiNiyas** [comment]
> @NiNiyas, just re-read your message. You don't get any images?  Do you get the same log message for all artists (Artist not found in Spotify)?

Yes, I don't get any artists images and yes, same log message.

**Comment by deluan** [comment]
The only thing I can think of is something wrong with your tags.... Can you send me one music file so I can debug it locally? If yes, send it to deluan @ navidrome.org. Thanks

**Comment by deluan** [comment]
The files are ok:
```
DEBU[0015] Got Images     agent=spotify artist="Novo Amor" elapsed=108.4ms images="[{https://i.scdn.co/image/ab6761610000e5eb6f9004573a721336b343bbd3 640} {https://i.scdn.co/image/ab676161000051746f9004573a721336b343bbd3 320} {https://i.scdn.co/image/ab6761610000f1786f9004573a721336b343bbd3 160}]" requestId=MacDeluan16.local/gVMfR5kMii-000010
```
<img width="444" alt="Screen Shot 2023-01-16 at 3 25 53 PM" src="https://user-images.githubusercontent.com/331353/212760638-f52e70c5-a754-4f56-9f6a-86dd9b0254b9.png">

Maybe your Spotify ID or Secret are misconfigured?

**Comment by NiNiyas** [comment]
I am an idiot, my Adguard Home was blocking all the connections to api.spotify.com. Unblocking it worked. I am truly sorry for wasting you time @deluan.
