### ISSUE TITLE
Playlists view in sidebar only lists ~100 playlists

### ISSUE THREAD

**Issue by yllekz** [navidrome/navidrome#2077]
### Description

I imported my M3U playlist files and noticed only the first 100 are displaying in the sidebar. I have more than this.

### Expected Behaviour

All playlists need to load in the sidebar

### Steps to reproduce

1. Add lots of M3U playlists to your library
2. Full Scan library
3. Count the playlists in the sidebar

### Platform information

 - Navidrome version: [0.48.0](https://github.com/navidrome/navidrome/releases/tag/v0.48.0) (af5c2b5a)
 - Browser and version: Firefox v108.0.2 64-bit
 - Operating System: Server is macOS Ventura running Docker Desktop. Client is Linux Mint 21.1.

### Additional information

Any other information that may be relevant or give context to the problem.

 - Screenshots (if applicable)?
 - Logs? 
 - Client used? Web browser

**Comment by deluan** [comment]
This is not a bug, this is done to limit the resource utilization on the browser, as rendering a lot of elements could cause the browser to crash. A solution would be to load the list on demand, and maybe implement a filter. In the meantime, I may add a config option to increase this number, so users can try what works best for them.

**Comment by SaiRev0** [comment]
@deluan Since you cleared the problem are there any issues left in this, if so I would like to work on it.

**Comment by deluan** [comment]
@SaiRev0 I haven't worked on this yet, so I think a good first approach is to have a config option (`MaxSidebarPlaylists`?) to set the limit. 

For the loading on demand, it may be tricky with the current React-Admin version. Once I upgrade to v4, this could be simplified using the new `useInfiniteGetList` hook. Anyway, feel free to try another approach.

**Comment by Porco-Rosso** [comment]
Just casting my vote on this issue as well, it is also a concern for me. @SaiRev0 would appreciate if you manage to implement it.

**Comment by yllekz** [comment]
I also noticed that all playlists display in a third party app such as Soundwaves on iOS so it only seems to be a web UI thing.

**Comment by deluan** [comment]
I implemented a `MaxSidebarPlaylists` config option (default 100), that can be increased at the user's own risk :) 

> I also noticed that all playlists display in a third party app such as Soundwaves on iOS so it only seems to be a web UI thing.


@yllekz You can also access all playlists in the web UI:
<img width="446" alt="Screenshot 2023-02-01 at 10 26 19 AM" src="https://user-images.githubusercontent.com/331353/216086666-e032c031-e3a5-41dc-a9aa-d5b35fb40230.png">

I agree the icon is not that great, but the option is there.
