### ISSUE TITLE
Smarter transcoding settings for Wi-Fi vs cellular streaming

### ISSUE THREAD

**Issue by alangrafu** [navidrome/navidrome#2081]
### Is your feature request related to a problem? 

It would be great to allow transcoding options no only base on client but also other parameter such as if the user is on Wi-Fi, cellular network, in that way you can use the same client without transcoding FLAC files while in your internal network, but you don’t use a lot of bandwidth while on cellular mode.

### Describe the solution you'd like

maybe a simple way to detect these changes would be based on IP. Eg i can define that clients in `192.168.0.0/24` do **not** need to transcode while everyone else does.

### Describe alternative solutions that would also satisfy this problem

not sure if you can pass other parameter or but alternatively maybe you can use different domains `www.lan-music.domain.com` vs `www.external-music.domain.com` to define transcoding or no transcoding.

### Additional context

Just wanted to say navidrome is awesome, thanks for all the effort 🙏

**Comment by DanielNautre** [comment]
It seems to be me that this should be handled by the client.

**Comment by deluan** [comment]
Yes, as @DanielNautre mentioned, this is usually handled by the client. DSub does that for example. Anyway, we have an issue opened to track improvements to the transcoding engine, #351. Feel free to add your idea as a comment there.
