### ISSUE TITLE
Option Skip silence at beginning and end of tracks

### ISSUE THREAD

**Issue by DanielNautre** [navidrome/navidrome#2082]
### Is your feature request related to a problem? Please describe.

Some tracks may have silences at the start and end that span over several seconds.

### Describe the solution you'd like

As an option, Navidrome should be able to skip the silent parts at teh start and end of a track. 

### Describe alternative solutions that would also satisfy this problem

I don't have any clear idea on an alternative, but I welcome suggestions

### Additional context

This might cause issues if the silences are intentional, thus this needs to be an option.

I do realise htis is quite the big ask and might not be feasible currently, but I wanted to document it nonetheless

**Comment by deluan** [comment]
If you are referring to the Gap between tracks, this is already covered by #745. If you mean silence _in_ the track, this is out of scope for Navidrome. It plays the tracks as it is given to it. If you need to remove the silence from the beginning or end of the track, I'm sure there are audio edit tools out there that can help.

Either way, I'm closing this but feel free to chime in if you have any other concerns.

**Comment by DanielNautre** [comment]
I do mean silence that are in the tracks and not between tracks. But if it's out of scope, fair enough.

Editing to trim has drawbacks, it's destructive and usually requires re-encoding. 
Automating triming allows to deal with a lot of files but might cause some files to be cut to short. Doing it manually isn't a option for more than a couple files.

**Comment by deluan** [comment]
> Automating triming allows to deal with a lot of files but might cause some files to be cut to short.

This could also happen if the triming is done in the player as you suggested. 

I don't know of any player that handles this automatically. I've only seen it in iTunes where you can specify _manually_ the beginning and end of each song, individually:

<img width="508" alt="Screen Shot 2023-01-12 at 8 07 38 AM" src="https://user-images.githubusercontent.com/331353/212074465-589e3973-217d-45d4-af45-80e30f38925d.png">

**Comment by DanielNautre** [comment]
> This could also happen if the triming is done in the player as you suggested.

Oh yeah, for sure. But since it's non-desctructive, it's more of an inconvenience.

> I don't know of any player that handles this automatically. I've only seen it in iTunes where you can specify manually the beginning and end of each song, individually:

Musicbeee does it too. Either by setting it manually as in your screenshot, or automatically with some detection algorithm.
I agree that this should be handled by the client, in this case the web-ui client.
