### ISSUE TITLE
having an extremely large album breaks the webui/player

### ISSUE THREAD

**Issue by nekopsykose** [navidrome/navidrome#2083]
### Description
having a massive folder (>500? >800? ~914 in my case) that all gets shown under a single album in the webui (so every track is displayed as an entry on the single album page) breaks the website entirely (can't click on anything, etc). sometimes a few entries load, sometimes not. sometimes lets you navigate to another page for a bit, but overall it's just kinda really broken

this is quite a rare case (not sure if any actual albums of so many entries exist), but i ran into this by downloading a "compilation" of something that all grouped it under the same name so it got indexed as a single album, then opened it.

### Expected Behaviour

normal operation

### Steps to reproduce

have a huge music folder all with the same album name so they are grouped into one album (i guess?)

### Platform information

 - Navidrome version: 0.48.0
 - Browser and version: Firefox 108.2, Chromium 109.0.5414.74 
 - Operating System: built from source

**Comment by DanielNautre** [comment]
Seems similar to #1186

Tried it with my biggest album 432 songs on 38 discs and though it struggled, it got there fairly quickly. Not smooth, but not unbearable

Navidrome: 0.48 via docker on a NUC
Browser: Firefox 108.2 (64bits
OS: Windows 10 on a 12 year old potato PC

**Comment by nekopsykose** [comment]
ah, yeah it's the same as that. somehow didn't find it..
