### ISSUE TITLE
WebUI Player Won't Autostart New Tracks on Chromium

### ISSUE THREAD

**Issue by nosbig** [navidrome/navidrome#2100]
### Description

While playing music in the Web UI on multiple versions (at least 0.45 onwards through and including 0.48.0), playback in a Chromium browser session won't advance to next track in playlist.

### Expected Behaviour

When any playlist item finishes, playback should continue with the next item as defined by the repeat/shuffle setting.

### Steps to reproduce

1. Add any album, song, or playlist to an empty or existing playback queue.
2. Allow the first track to finish.
3. When playback stops, the track advances but remains in a stopped state.
4. Click play allows playback to continue for the duration of the playing song, at which point, it will stop.

### Platform information

 - Navidrome version: v0.48.0 (as well as earlier versions going back to at least v0.45.0)
 - Browser and version: Failing - Chromium v108.0.5359.124 (and many older builds); Successes - Firefox ESR (102.6.0esr-1), Epiphany (43.0), Vivaldi (5.6.2867.58-1)
 - Operating System: Debian Testing (from at least pre-Buster through today)

**Comment by pulberg** [comment]
Are you running Navidrome on the same Debian host?  I am running Navidrome on an M1 Mac Studio, I tested this in a VM with Chromium Version 109.0.5414.74 (Official Build) snap (64-bit) on Ubuntu 23.04 and there are no playback issues as you described.

**Comment by nosbig** [comment]
I have run Navidrome on a Raspberry Pi Zero W using Raspbian, on my local desktop running Debian Testing, and on my home file server which runs Debian Stable.  All three have exhibited this issue with the web UI.

**Comment by nosbig** [comment]
This issue does appear to be resolved.  I'm still running 0.49.3, but I have upgraded to 114.0.5735.198 as a part of the Debian Testing stack.
