### ISSUE TITLE
Inconsistent delete icons in queue

### ISSUE THREAD

**Issue by DanielNautre** [navidrome/navidrome#2102]
### Description

The remove/delete icons in the queue are inconsistent. Showing a trashcan to delete the whole queue but crosses for individual songs.
Another cross is used to close the queue window, creating some confusion

![image](https://user-images.githubusercontent.com/2039600/213665501-9391dc43-e819-480d-87c7-2e54462e865a.png)

### Expected Behaviour

Icons should always produce the same expected result across a software and especially on the same view.

If thrashcan delete the queue, it should delete the individual songs too.
If the cross deletes, it should close the queue window

### Steps to reproduce

- Start playing an album
- Open the queue, clicking the approriate icon

### Platform information

 - Navidrome version: v0.48

### Additional information

Client used: Navidrome UI on Chrome 108.0.5359.125

**Comment by deluan** [comment]
I agree this is not very consistent, but the player is an [external component](https://github.com/lijinke666/react-music-player), and it is unfortunately not maintained anymore.  I have plans to replace it with a new one in the (near) future.

I'll close this now, but let me know if you have any other concerns.
