### ISSUE TITLE
Strange bug after login

### ISSUE THREAD

**Issue by Igorgro** [navidrome/navidrome#2107]
### Description

When logging in to navidrome after a long period of time not using it, it shows infinite loading icon near the profile and the 401 error in console

### Expected Behaviour

No errors are hapening

### Steps to reproduce

1. Install navidrome, fill library but do not use it for a period of time (probably 3-4 days)
2. Login via browser, open devtools and see error

### Platform information

 - Navidrome version: 0.48.0
 - Browser and version: Google chrome 109.0.5414.74
 - Operating System:
     - Server: Debian 11
     - Client: Arch linux

### Additional information

Any other information that may be relevant or give context to the problem.

 - Screenshots:
    ![image](https://user-images.githubusercontent.com/22894169/213998698-f21299f2-7994-4886-9acc-6f4ba3a49955.png)
    ![image](https://user-images.githubusercontent.com/22894169/213998748-188b339c-9896-4fd3-93c2-1ab7f5c265a3.png)

**Comment by Igorgro** [comment]
Still happens in 0.49.0

**Comment by deluan** [comment]
Hey, sorry for not replying before. 

The 401 errors are normal, it just mean your session expired and you should be redirected to the login page (right?)

The spinning, ever-loading icon is an issue with React-Admin I was never able to fix. I have other projects using it that suffer from the same issue. 

The good news is that I've been playing with React-Admin 4 and seems the issue went away. So when I upgrade Navidrome to use RA4, this issue will most probably go away. It needs some big refactoring to upgrade to RA4 so, unless someone figures it out and sends a PR, I won't fix it in the current version of the UI. 

I'll close this now but let me know if. you have any other concerns.
