### ISSUE TITLE
Some subsonic clients (DSub) ignore coverArt ID for playlist

### ISSUE THREAD

**Issue by SenorSmartyPants** [navidrome/navidrome#2112]
### Description

Some subsonic API clients (notably DSub) ignore the coverArt attribute for a playlist and request coverArt based on pl-[PlaylistID]

### Expected Behaviour

I know this is not a Navidrome issue, but it would be nice to support these additional style of request and return coverArt.

### Steps to reproduce

See these DSub issues for more details. 
https://github.com/daneren2005/Subsonic/issues/1099
https://github.com/daneren2005/Subsonic/issues/531

### Platform information

 - Navidrome version: deluan/navidrome:develop
 - Browser and version: 
 - Operating System: 

### Additional information

Any other information that may be relevant or give context to the problem.
 - Client used : DSub v5.5.3

**Comment by deluan** [comment]
This should be working on the `develop` builds. Did you try to clean up DSub's cache?

![Screenshot_20230123-162454](https://user-images.githubusercontent.com/331353/214153329-8b97e105-5056-49e6-b17d-71de91d16d9a.png)

**Comment by SenorSmartyPants** [comment]
I've cleared DSub cache many times with no effect. Just did it again.

Haven't cleared storage since I didn't want to set up my account on the phone again.

**Comment by deluan** [comment]
Yeah, think DSub is not smart enough to re-request a playlist cover when its `changed` attribute is updated. You may have to clear DSub's storage...

With the `develop` builds, you can add the following lines to your toml config file and see how calls to coverArt are resolved:
```
[DevLogLevels]
"server/subsonic" = "trace"
"core/artwork" = "trace"
"utils/cache/" = "trace"
```

**Comment by deluan** [comment]
Hey @SenorSmartyPants were you able to figure this out?

**Comment by SenorSmartyPants** [comment]
I'm planning on turning the logs on and checking it out, but haven't done it yet.

**Comment by SenorSmartyPants** [comment]
I use docker, so would set ND_LOGLEVEL = trace be the same thing? Or are those devLogLevels more detailed? How would I set those in a docker set up?

**Comment by SenorSmartyPants** [comment]
I think I figured it out. This is the output in docker logs. I refreshed the playlist a couple times and then clicked on a playlist and refreshed it. Let me know if that's not the logs you're looking for.


```
navidrome           | time="2023-02-04T18:14:58Z" level=debug msg="API: New request /rest/getPlaylists.view" client=DSub requestId=dabbdcd9bf23/ENyAMtsISx-000010 username=Danzo version=1.2.0
navidrome           | time="2023-02-04T18:14:58Z" level=debug msg="API: Successful response" endpoint=/rest/getPlaylists.view requestId=dabbdcd9bf23/ENyAMtsISx-000010 status=OK username=Danzo
navidrome           | time="2023-02-04T18:15:11Z" level=debug msg="API: New request /rest/getPlaylists.view" client=DSub requestId=dabbdcd9bf23/ENyAMtsISx-000012 username=Danzo version=1.2.0
navidrome           | time="2023-02-04T18:15:11Z" level=debug msg="API: Successful response" endpoint=/rest/getPlaylists.view requestId=dabbdcd9bf23/ENyAMtsISx-000012 status=OK username=Danzo
navidrome           | time="2023-02-04T18:15:17Z" level=debug msg="API: New request /rest/getPlaylist.view" client=DSub requestId=dabbdcd9bf23/ENyAMtsISx-000013 username=Danzo version=1.2.0
navidrome           | time="2023-02-04T18:15:17Z" level=debug msg="API: Successful response" endpoint=/rest/getPlaylist.view requestId=dabbdcd9bf23/ENyAMtsISx-000013 status=OK username=Danzo
navidrome           | time="2023-02-04T18:15:23Z" level=debug msg="API: New request /rest/getPlaylists.view" client=DSub requestId=dabbdcd9bf23/ENyAMtsISx-000014 username=Danzo version=1.2.0
navidrome           | time="2023-02-04T18:15:23Z" level=debug msg="API: Successful response" endpoint=/rest/getPlaylists.view requestId=dabbdcd9bf23/ENyAMtsISx-000014 status=OK username=Danzo
```

**Comment by SenorSmartyPants** [comment]
I ended up clearing DSub storage, re-set up the server in DSub and then playlist images are pulled. So that works. But oddly now my user image does not display in DSub.
