### ISSUE TITLE
Playing new music uses lyrics from previously played one in Web Browser

### ISSUE THREAD

**Issue by stalemartyr** [navidrome/navidrome#2117]
### Description

When searching a song in "Songs" menu, the currently playing music uses the lyrics from previously played one. Both are embedded with lyrics tag. I need to refresh the page to fix this issue. 

### Expected Behaviour

Should use the correct lyrics and not the lyrics from the previously played music.

### Steps to reproduce

1. Open Navidrome. Click "Songs" menu
2. Search a music with lyrics in the Search textbox. Click to play
3. Click the "Toggle lyrics"...lyrics is working
4. Search a different music with lyrics. Click to play("Toggle lyrics" is still on).
6. Lyrics is from previous song.

### Platform information

 - Navidrome version: 0.48.0
 - Browser and version: Firefox 109.0, Chrome 108.0.5359.124
 - Operating System: Mac OS Ventura 13.0.1 (client), Rocky Linux 8 (server)
 - Music are embedded with LYRICS tag(synced lyrics)

### Additional information

Current Song is Skyway Avenue by We the Kings but the lyrics is from Welcome to the Family by ADTR (previous song)
<img width="795" alt="image" src="https://user-images.githubusercontent.com/5483695/215016942-388ca1aa-d4b0-4198-9f65-38d920e3afd0.png">

**Comment by joaomqc** [comment]
I just smacked into this issue today after putting off adding lyrics to songs for so long.
From what I can tell, the problem seems to be coming from the navidrome-react-player, not from this project.
