### ISSUE TITLE
Some songs cannot be played on Windows Chrome.

### ISSUE THREAD

**Issue by Lin-Producer** [navidrome/navidrome#2122]
### Description

There is an issue that some songs cannot be played on Windows Chrome.

There are some songs that play fine, in all my songs.
There are some pictures:
![image](https://user-images.githubusercontent.com/69388144/215319121-fda34781-6e81-4535-bea7-c33ec71803eb.png)
And I used ’chrome://media-internals/‘ to view audio information:
![image](https://user-images.githubusercontent.com/69388144/215319194-40b74c03-6ca7-41c7-ad0f-98db36acac6a.png)

But, there are still some songs that cannot be played normally, it looks like:
![image](https://user-images.githubusercontent.com/69388144/215319332-036bd1aa-5f11-4d67-b7ac-b0d2559c988b.png)
And ’chrome://media-internals/‘ is:
![image](https://user-images.githubusercontent.com/69388144/215319378-fa8ec562-f8e8-4dd7-ae6c-c259e11035b7.png)

I don't know how to fix :<html>
<body>

error | "FFmpegDemuxer: open context failed"
-- | --

</body>
</html>

### Expected Behaviour

i hope it works.

### Steps to reproduce

I don't think this bug can be reproduced. Because my iPhone opens this page and everything works fine.
This bug only occurs on this device.

### Platform information

 - Navidrome version: 0.47.5(86fe1e3b)
 - Browser and version: Chrome 109.0.5414.120
 - Operating System: Windows 11 22H2

### Additional information

Any other information that may be relevant or give context to the problem.

 - Screenshots (if applicable)?
 - Logs? 
 - Client used? 
[0.47.5](https://github.com/navidrome/navidrome/releases/tag/v0.47.5) (86fe1e3b)

**Comment by deluan** [comment]
Do you have transcoding enabled for this device? What is the media file format? Can you play the file directly in the browser?

**Comment by Lin-Producer** [comment]
thank you for your reply. Now the problem is solved. The error was caused by wrong encoder metadata for unplayable songs. Encoders with Lavf xx.xx cannot be played. And I changed the song to reference libFLAC xx.xx and it can be played. I solved this problem by using FL Studio to re-encode the wrong song. I will close this issue.我还在我自己的博客上写了一篇中文解决该问题的文章：https://www.linp.moe/index.php/2023/02/13/%e6%9b%b4%e6%96%b0%e6%9c%8d%e5%8a%a1%e5%99%a8%ef%bc%81%e9%9f%b3%e4%b9%90%e7%ab%99%e6%8e%92%e9%9a%9cget%ef%bc%81%e5%b9%b6%e6%96%b0%e5%a2%9e%e4%b8%93%e8%be%91%ef%bc%81/
