### ISSUE TITLE
Volume control missing in share player

### ISSUE THREAD

**Issue by dani** [navidrome/navidrome#2124]
### Is your feature request related to a problem? Please describe.

When sharing an album to someone, he can access the link and listen to the album, but the web player has no volume control

### Describe the solution you'd like

Add the volume control on the sharing web player

**Comment by deluan** [comment]
Currently the player used in share is the same mobile player we use in normal operation, and it does not provide a volume control in mobile view. Th only solution is to use he computer's volume controls. I may replace the player in the future, but for now it is out-of-scope. 

Closing this but let me know if you have any other concerns.
