### ISSUE TITLE
downloadable shares

### ISSUE THREAD

**Issue by anarcat** [navidrome/navidrome#2125]
### Is your feature request related to a problem? Please describe.

I am really happy to see navidrome support the "share" feature. It's something I've been wanting to use to share my music with friends basically forever: airsonic was supposed to support it, but it never really worked, for example...

Now, I can share my music, but my friends need to stream it and can't download it locally. That's okay for many people, but for some others (who live very far away), it's actually a challenge, 

### Describe the solution you'd like

I am not sure what the subsonic API says about this, but it would sure be nice to have a "download" button in the web interface. Nothing fancy, just stream a zip file on-the-fly with the files.

### Describe alternative solutions that would also satisfy this problem

I guess another solution would be to expose a folder with a "auto-index" style thing where the user could download the files one by one, but meh.

### Additional context

Thanks again for the share feature: as soon as I saw this land in a release, I used it the same day. :)

**Comment by andrewgdunn** [comment]
Right now I see there is a download at the album or track level:

![Screenshot 2023-02-03 at 10-47-52 Levitate - Hildegunn Øiseth - Navidrome](https://user-images.githubusercontent.com/323695/216646571-015d0f74-e729-45d9-be4e-bcbbaea274d6.png)

Are you looking for more than that, for example are you asking:
 - to be able to have downloads in the new share feature? #2106
 - to be able to create downloads of multiple albums?

**Comment by anarcat** [comment]
> to be able to have downloads in the new share feature?

i am explicitly asking for downloadable shares, yes, it's the title of this issue...

**Comment by andrewgdunn** [comment]
> yes, it's the title of this issue...

Another solution would be to give the users accounts to the server.

**Comment by Sevinfolds** [comment]
In the config of the SharePlayer file.js I noticed the line **showDownload**:

    audioLists: list,
    mode: 'full',
    toggleMode: false,
    mobileMediaQuery: '',
    showDownload: false,
    showReload: false,
    showMediaSession: true,
    theme: 'auto',
    showThemeSwitch: false,
    restartCurrentOnPrev: true,
    remove: false,
    spaceBar: true,
    
There are other interesting parameters that are currently disabled. Most likely they have not yet been implemented for the SharePlayer file file.js
I tried to include some parameters, nothing has changed.

**Comment by deluan** [comment]
@Sevinfolds `showDownload` is a feature of the player that would only enable the download of the current playing song, not the whole share. And even for that, it still needs some code to work.

The solution will be to implement a button that hooks into the current download function.

**Comment by fkrivsky** [comment]
Hi @deluan, I'm using the :latest docker image and I don't see the feature there. Any idea when this will be available please?

**Comment by deluan** [comment]
> Hi @deluan, I'm using the :latest docker image and I don't see the feature there. Any idea when this will be available please?

Don't you see this option when sharing?

<img width="622" alt="Screenshot 2023-04-12 at 12 25 08 PM" src="https://user-images.githubusercontent.com/331353/231521454-995b073c-4ca3-43fe-8e9f-04cbccee1c66.png">

You need `EnableDownloads` config option to be true, or else it won't allow you to download anything from the server.

**Comment by fkrivsky** [comment]
> > Hi @deluan, I'm using the :latest docker image and I don't see the feature there. Any idea when this will be available please?
> 
> Don't you see this option when sharing?
> 
> <img alt="Screenshot 2023-04-12 at 12 25 08 PM" width="622" src="https://user-images.githubusercontent.com/331353/231521454-995b073c-4ca3-43fe-8e9f-04cbccee1c66.png">
> 
> You need `EnableDownloads` config option to be true, or else it won't allow you to download anything from the server.

Oh, sorry for not being clear, I meant the whole Share option. The version is 0.49.1.
![image](https://user-images.githubusercontent.com/68921465/231525898-0c18df88-ef32-4c77-bbf9-f85027cf41ac.png)

**Comment by anarcat** [comment]
> To enable Sharing, you need to explicitly enable it, as it is still considered [incomplete]9#2106). Add `EnableSharing=true` in your config options.

i'm curious here, actually... how is it incomplete? that link above seems broken...

**Comment by deluan** [comment]
Fixed :) Basically it is missing permissions (who can share)
