### ISSUE TITLE
Certain checkboxes are same color as panel - Gruvbox Dark theme

### ISSUE THREAD

**Issue by IdeallyGrey** [navidrome/navidrome#2129]
### Description

Using the new Gruvbox Dark theme, the checked version of the check boxes in the "Columns to display" panel are the same color as the background of the panel, causing them to appear invisible. The unchecked version is colored white, so it is visible. See screenshot bellow.

### Steps to reproduce

1. Open the 'Artists', 'Songs', 'Radios', or 'Playlists' page
2. Click on the 3-dot menu in the top-right.
3. The "checked" symbol for the selected options will not be visible. 

### Platform information

 - Navidrome version: v0.49.0
 - Browser and version: Firefox v109.0
 - Operating System: Ubuntu 22.04, Docker container

### Additional information

<img width="257" alt="Bildschirmfoto 2023-01-30 um 17 36 37" src="https://user-images.githubusercontent.com/77685111/215612250-dfda617d-7680-4f4a-94b5-2ec12d9d816d.png">

**Comment by deluan** [comment]
Thanks for reporting this. Hey @vlfldr, can you please take a look? Thanks!

**Comment by vlfldr** [comment]
Thanks for testing the theme. I will look into and fix this within the next two days.
