### ISSUE TITLE
ImageCacheSize setting no longer respected 

### ISSUE THREAD

**Issue by michael-ball** [navidrome/navidrome#2142]
### Description

After upgrading to v0.49.0, I noticed that my `/run` directory ran out of space after doing a full scan with navidrome. When I inspected `/run/navidrome/cache` I saw that all the space was taken up by images, even though I've set `ImageCacheSize = "0"` in my `navidrome.toml` settings.

### Expected Behaviour

I would expect images to not get cached.

### Steps to reproduce

1. Set `ImageCacheSize = "0"` in `navidrome.toml`
2. Restart navidrome for the setting to take effect
3. Trigger a full scan
4. Watch the image cache grow

### Platform information

 - Navidrome version: v.0.49.0
 - Browser: Firefox 109.0.1
 - OS: Raspberry Pi OS (based on Debian 11.6)

**Comment by deluan** [comment]
Hey thanks for reporting, but I'm confident that setting `ImageCacheSize = "0" ` turns the cache off.
With `LogLevel="debug"`, you should see the following lines in the beginning of the logs: 
```
WARN[0000] Image cache disabled                         
INFO[0000] Finished initializing cache                   cache=Image elapsedTime="164.013µs" maxSize=0
DEBU[0000] Cache DISABLED                                cache=Image size=0
```

If the cache is in fact enabled you should see this:
```
INFO[0000] Creating Image cache                          maxSize="100 MB" path=data/local/cache/images
INFO[0000] Finished initializing cache                   cache=Image elapsedTime="942.797µs" maxSize=100MB
```

Can you confirm this?

**Comment by michael-ball** [comment]
> Hey thanks for reporting, but I'm confident that setting `ImageCacheSize = "0" ` turns the cache off. With `LogLevel="debug"`, you should see the following lines in the beginning of the logs:
> 
> ```
> WARN[0000] Image cache disabled                         
> INFO[0000] Finished initializing cache                   cache=Image elapsedTime="164.013µs" maxSize=0
> DEBU[0000] Cache DISABLED                                cache=Image size=0
> ```
> 
> If the cache is in fact enabled you should see this:
> 
> ```
> INFO[0000] Creating Image cache                          maxSize="100 MB" path=data/local/cache/images
> INFO[0000] Finished initializing cache                   cache=Image elapsedTime="942.797µs" maxSize=100MB
> ```
> 
> Can you confirm this?

I can confirm this is the case, yes.

I've just run another full scan in order to collect more data, but now I can't recreate the problem.

It must have been a misconfiguration on my end. I'm happy to close this.

**Comment by michael-ball** [comment]
I'm afraid I need to reopen this because the issue happened again: This morning my `/run` partition filled up again with cached images after the daily full scan.

Here is my `navidrome.toml`:

```
MusicFolder = "redacted"
ScanSchedule = "0 2 * * *"
EnableTranscodingConfig = false
LastFM.ApiKey = "redacted"
LastFM.Secret = "redacted"
Address = "localhost"
AutoImportPlaylists = false
TranscodingCacheSize = "0"
ImageCacheSize = "200M"
LastFM.Enabled = true
IgnoredArticles = "The El La Los Las Le Les Os As O A Der Die Das"
```

After this morning's full scan the `/run/navidrome/cache/images` dir totalled 786MB, which is well above the expected "200M" I have configured.

**Comment by michael-ball** [comment]
This sounds highly likely, yes. I suspect the clean-up isn't happening in my case, though,  as the total cache size was well above the configured cache size for hours.

Being able to disable the cache warmer would resolve this for me. Thank you.

**Comment by michael-ball** [comment]
Where can I download the latest dev build? Or do I need to build myself?

**Comment by deluan** [comment]
You can always download the latest from this link:

<img width="1036" alt="Screenshot 2023-02-02 at 12 12 07 PM" src="https://user-images.githubusercontent.com/331353/217330000-4f05a4e8-e419-4804-9499-5f65fc29b43a.png">

If you use Docker, you can use the tag `deluan/navidrome:develop`

**Comment by michael-ball** [comment]
The cache cleanup didn't clean my image cache.

At 02:00 UTC a full scan is done, and it grows my navidrome cache dir to the maximum size of the partition it's on (764MB).

Here are the trace logs after that time:

```
Feb 08 01:57:56 hostname_redacted navidrome[17940]: time="2023-02-08T01:57:56Z" level=trace msg="Running cache cleanup" cache=Image maxSize="200 MB"
Feb 08 01:57:56 hostname_redacted navidrome[17940]: time="2023-02-08T01:57:56Z" level=trace msg="Current cache stats" cache=Image numItems=0 size="0 B"
Feb 08 02:07:56 hostname_redacted navidrome[17940]: time="2023-02-08T02:07:56Z" level=trace msg="Running cache cleanup" cache=Image maxSize="200 MB"
Feb 08 02:07:56 hostname_redacted navidrome[17940]: time="2023-02-08T02:07:56Z" level=trace msg="Current cache stats" cache=Image numItems=0 size="0 B"
Feb 08 02:17:56 hostname_redacted navidrome[17940]: time="2023-02-08T02:17:56Z" level=trace msg="Running cache cleanup" cache=Image maxSize="200 MB"
Feb 08 02:17:57 hostname_redacted navidrome[17940]: time="2023-02-08T02:17:56Z" level=trace msg="Current cache stats" cache=Image numItems=0 size="0 B"
Feb 08 02:27:59 hostname_redacted navidrome[17940]: time="2023-02-08T02:27:59Z" level=trace msg="Running cache cleanup" cache=Image maxSize="200 MB"
Feb 08 02:27:59 hostname_redacted navidrome[17940]: time="2023-02-08T02:27:59Z" level=trace msg="Current cache stats" cache=Image numItems=0 size="0 B"
Feb 08 02:37:59 hostname_redacted navidrome[17940]: time="2023-02-08T02:37:59Z" level=trace msg="Running cache cleanup" cache=Image maxSize="200 MB"
Feb 08 02:37:59 hostname_redacted navidrome[17940]: time="2023-02-08T02:37:59Z" level=trace msg="Current cache stats" cache=Image numItems=0 size="0 B"
Feb 08 02:47:59 hostname_redacted navidrome[17940]: time="2023-02-08T02:47:59Z" level=trace msg="Running cache cleanup" cache=Image maxSize="200 MB"
Feb 08 02:47:59 hostname_redacted navidrome[17940]: time="2023-02-08T02:47:59Z" level=trace msg="Current cache stats" cache=Image numItems=0 size="0 B"
Feb 08 02:57:59 hostname_redacted navidrome[17940]: time="2023-02-08T02:57:59Z" level=trace msg="Running cache cleanup" cache=Image maxSize="200 MB"
Feb 08 02:57:59 hostname_redacted navidrome[17940]: time="2023-02-08T02:57:59Z" level=trace msg="Current cache stats" cache=Image numItems=0 size="0 B"
Feb 08 03:07:59 hostname_redacted navidrome[17940]: time="2023-02-08T03:07:59Z" level=trace msg="Running cache cleanup" cache=Image maxSize="200 MB"
Feb 08 03:07:59 hostname_redacted navidrome[17940]: time="2023-02-08T03:07:59Z" level=trace msg="Current cache stats" cache=Image numItems=0 size="0 B"
Feb 08 03:17:59 hostname_redacted navidrome[17940]: time="2023-02-08T03:17:59Z" level=trace msg="Running cache cleanup" cache=Image maxSize="200 MB"
Feb 08 03:17:59 hostname_redacted navidrome[17940]: time="2023-02-08T03:17:59Z" level=trace msg="Current cache stats" cache=Image numItems=0 size="0 B"
Feb 08 03:27:59 hostname_redacted navidrome[17940]: time="2023-02-08T03:27:59Z" level=trace msg="Running cache cleanup" cache=Image maxSize="200 MB"
Feb 08 03:27:59 hostname_redacted navidrome[17940]: time="2023-02-08T03:27:59Z" level=trace msg="Current cache stats" cache=Image numItems=0 size="0 B"
Feb 08 03:37:59 hostname_redacted navidrome[17940]: time="2023-02-08T03:37:59Z" level=trace msg="Running cache cleanup" cache=Image maxSize="200 MB"
Feb 08 03:37:59 hostname_redacted navidrome[17940]: time="2023-02-08T03:37:59Z" level=trace msg="Current cache stats" cache=Image numItems=0 size="0 B"
Feb 08 03:47:59 hostname_redacted navidrome[17940]: time="2023-02-08T03:47:59Z" level=trace msg="Running cache cleanup" cache=Image maxSize="200 MB"
Feb 08 03:47:59 hostname_redacted navidrome[17940]: time="2023-02-08T03:47:59Z" level=trace msg="Current cache stats" cache=Image numItems=0 size="0 B"
Feb 08 03:57:59 hostname_redacted navidrome[17940]: time="2023-02-08T03:57:59Z" level=trace msg="Running cache cleanup" cache=Image maxSize="200 MB"
Feb 08 03:57:59 hostname_redacted navidrome[17940]: time="2023-02-08T03:57:59Z" level=trace msg="Current cache stats" cache=Image numItems=0 size="0 B"
Feb 08 04:07:59 hostname_redacted navidrome[17940]: time="2023-02-08T04:07:59Z" level=trace msg="Running cache cleanup" cache=Image maxSize="200 MB"
Feb 08 04:07:59 hostname_redacted navidrome[17940]: time="2023-02-08T04:07:59Z" level=trace msg="Current cache stats" cache=Image numItems=0 size="0 B"
```

**Comment by deluan** [comment]
Interesting how it says:
```
msg="Current cache stats" cache=Image numItems=0 size="0 B"
```

It means that it is not finding any cached files.... I'm not able to reproduce this but will try to figure out. Maybe I'll send a binary with more logs to you, to help debug this, if that's ok. Just let me know the platform (arm version).

**Comment by michael-ball** [comment]
Sure, I'm happy to help try and pin down the issue further. I'm using armv7 binaries.

**Comment by deluan** [comment]
Question: The log above is with `ImageCacheSize = "200MB"`, right? Just to be sure, it has to be "200MB", not "200M"..

What happens if you disable the cache with `ImageCacheSize="0"`? Is it still caching images on an initial scan?

**Comment by michael-ball** [comment]
Oh I didn't realise the typo I had in my config. But setting `ImageCacheSize = "0"` still results in my image cache growing after a scheduled full scan.

**Comment by michael-ball** [comment]
I have some more data: the image cache doesn't get generated/warmed when manually triggering a full scan via the web interface. It only happens on scheduled scans (either using navidrome's sceduler or via `cron`).
