### ISSUE TITLE
一些功能上的小建议

### ISSUE THREAD

**Issue by ADa1st** [navidrome/navidrome#2143]
首先非常抱歉我的英语不太好，可能您看起来比较麻烦。
目前我搭建navidrome实在局域网使用，使用的时候有一些操作可以优化一下，感觉会有更好的体验
1. 添加一个可以免登录使用的功能，免去登录步骤的繁琐操作。
2. 给每首歌曲一个单独的url地址（目前是一个专辑、一个列表是单独id，全部音乐页面切歌曲url不变），方便快速加载到想要听取的歌
3. 在2的基础上，url中添加一个变量来控制输入url之后歌曲是否自动播放（比如a=0,不播放音乐，a=1自动播放音乐）

（machine translation）
First of all, I'm very sorry that my English is not very good, maybe you seem to be troublesome.
At present, I build Navidrome to use in a real LAN, and there are some operations that can be optimized when using it, and I feel that there will be a better experience
1. Add a feature that can be used without logging in, eliminating the tedious operation of login steps.
2. Give each song a separate URL address (currently an album, a list is a separate ID, all music pages cut the song URL unchanged), convenient to quickly load to the song you want to listen
3. On the basis of 2, add a variable to the URL to control whether the song will play automatically after entering the URL (e.g. a=0, do not play music, a=1 automatically play music)

**Comment by deluan** [comment]
> * Add a feature that can be used without logging in, eliminating the tedious operation of login steps.

Navidrome was not created for that use case. Navidrome is a personal server, and has a lot of personalizations per user (stars, playlists, ratings, play counts...). If you remove the login all users will have to share this data.

Having said that, if you really, really, really, REALLY want to allow users have access to your music without login and all share the same username, you can use an _undocumented_ config option: `DevAutoLoginUsername`. Set it to the username it will autologin.

> * Give each song a separate URL address (currently an album, a list is a separate ID, all music pages cut the song URL unchanged), convenient to quickly load to the song you want to listen

> * On the basis of 2, add a variable to the URL to control whether the song will play automatically after entering the URL (e.g. a=0, do not play music, a=1 automatically play music)

That is planned but not with this version of the UI.

As a side note, based on your questions, you may want to try the new Sharing feature? It allows you to create shareable links directly to  songs, albums, playlists and artists. When you open the link in a browser, you will see a player that can only play the shared music in that link.

Anyway, thanks for the suggestions

**Comment by ADa1st** [comment]
> > * 增加无需登录即可使用的功能，省去繁琐的登录步骤操作。
> 
> Navidrome 不是为该用例创建的。Navidrome是一个个人服务器，每个用户都有很多个性化设置（星级，播放列表，评级，播放次数......如果删除登录名，所有用户都必须共享此数据。
> 
> 您可以增加 ，登录频率将降低。我的设置为 5 天：。这样，用户将不得不在不使用 Navidrome 的情况下进行 5 天，然后才能再次要求登录。`SessionTimeout``SessionTimeout="120h"`
> 
> 话虽如此，如果您真的，真的，真的，真的想允许用户无需登录即可访问您的音乐并且所有人都共享相同的用户名，您可以使用_未记录_的配置选项：。将其设置为您想要的用户名，导航馆将绕过登录屏幕。`DevAutoLoginUsername`
> 
> > * 给每首歌曲一个单独的URL地址（目前是专辑，列表是单独的ID，所有音乐页面删掉的歌曲URL不变），方便快速加载到你想听的歌曲
> 
> > * 在 2 的基础上，在 URL 中添加一个变量来控制输入 URL 后歌曲是否会自动播放（例如 a=0，不播放音乐，a=1 自动播放音乐）
> 
> 这是计划好的，但不是这个版本的 UI。
> 
> 作为旁注，根据您的问题，您可能想尝试新的共享功能？它允许您创建直接指向歌曲，专辑，播放列表和艺术家的可共享链接。当您在浏览器中打开链接时，您将看到一个播放器，该播放器只能播放该链接中的共享音乐。
> 
> 无论如何，感谢您的建议

Thank you for your answer

**Comment by ADa1st** [comment]
I'm sorry, but when I tried to create and type DevAutoLoginUsernam = 'admin'  in navidrome.toml to save, it didn't change when it was restarted, I was using docker desktop and installing navidrome with power shell. Since I'm not familiar with Docker, I'd like to ask what went wrong. There were so few tutorials for Navidrome that I couldn't find the answers I was looking for online.

**Comment by ADa1st** [comment]
#

> > > * 增加无需登录即可使用的功能，省去繁琐的登录步骤操作。
> > 
> > 
> > Navidrome 不是为该用例创建的。Navidrome是一个个人服务器，每个用户都有很多个性化设置（星级，播放列表，评级，播放次数......如果删除登录名，所有用户都必须共享此数据。
> > 您可以增加 ，登录频率将降低。我的设置为 5 天：。这样，用户将不得不在不使用 Navidrome 的情况下进行 5 天，然后才能再次要求登录。`` SessionTimeout``SessionTimeout="120h" ``
> > 话虽如此，如果您真的，真的，真的，真的想允许用户无需登录即可访问您的音乐并且所有人都共享相同的用户名，您可以使用_未记录_的配置选项：。将其设置为您想要的用户名，导航馆将绕过登录屏幕。`DevAutoLoginUsername`
> > > * 给每首歌曲一个单独的URL地址（目前是专辑，列表是单独的ID，所有音乐页面删掉的歌曲URL），方便快速加载到你想听不变的歌曲
> > 
> > 
> > > * 在 2 的基础上，在 URL 中添加一个变量来控制输入 URL 后歌曲是否会自动播放（例如 a=0，不播放音乐，a=1 自动播放音乐）
> > 
> > 
> > 这是计划好的，但不是这个版本的 UI。
> > 作为旁注，根据您的问题，您可能想尝试新的共享功能？它允许您创建直接指向歌曲，专辑，播放列表和艺术家的可共享链接。当您在浏览器中打开链接时，您将看到一个播放器，该播放器只能播放该链接中的共享音乐。
> > 无论如何，感谢您的建议
> 
I'm sorry, but when I tried to create and type DevAutoLoginUsernam = 'admin' in navidrome.toml to save, it didn't change when it was restarted, I was using docker desktop and installing navidrome with power shell. Since I'm not familiar with Docker, I'd like to ask what went wrong. There were so few tutorials for Navidrome that I couldn't find the answers I was looking for online.

**Comment by deluan** [comment]
When using docker, try to set it as an env var: `ND_DEVAUTOLOGINUSERNAME: admin`

By the way, having a server with auto login as admin is a bad decision.....

**Comment by ADa1st** [comment]
Thank you for solving my problem, and at the same time thank you for your concern, because I am a personal family LAN, so permissions are not very important to me, and finally I wish you a happy life
