### ISSUE TITLE
Access to WebUI without an Password (Guest Listening)

### ISSUE THREAD

**Issue by kobayashi90** [navidrome/navidrome#2147]
Checked was nothing to be found.

### Is your feature request related to a problem? Please describe.

No, its not.

### Describe the solution you'd like

And option to show the WebUI without any login, just like spotify, soundclound etc.

**Comment by deluan** [comment]
Thanks for trying Navidrome, but it is not meant to be a public service as Spotify, Soundcloud, Apple Music, etc.... There's no plan to allow access without a login. 

See also: https://github.com/navidrome/navidrome/issues/2143#issuecomment-1416439804
