### ISSUE TITLE
Create more GUI filters

### ISSUE THREAD

**Issue by JaneX8** [navidrome/navidrome#215]
It would be great to be able to add filter in the Songs Grid in the GUI. Such as bitrate, filetype (FLAC/MP3), genre, size, plays. All data that is currently available already.

**Comment by deluan** [comment]
FIle type and other string based values are simple, will work on them.

The issue is with the numeric fields, not sure what is the best approach to introduce a filter for those, as IMO only makes sense if the filter is a range (min and max values). Should I introduce two filters for each field? I think it will be too much... 

Thoughts?

**Comment by ElleshaHackett** [comment]
I'm looking at the "custom filters" in the GUI of Plex now.

![image](https://user-images.githubusercontent.com/5116641/80323719-65bccf80-882d-11ea-8b06-c4c3b23ebf33.png)

![image](https://user-images.githubusercontent.com/5116641/80323739-779e7280-882d-11ea-9dd8-98550d876690.png)

![image](https://user-images.githubusercontent.com/5116641/80323744-7f5e1700-882d-11ea-9e3d-9c11dcfd00b1.png)

It's quite advanced but what if we use a similar but simpler approach? A simple "contains" for string based values and a choice of ==, !=, >, < choice for int/float based values.

**Comment by deluan** [comment]
I'm planing to implement exactly this as part of Smart Playlists... Not sure how to handle this overlap between filters in Song view and Smart Playlists, though...

**Comment by ElleshaHackett** [comment]
@certuna can you share some screenshots of the specific elements you refer to?

**Comment by JaneX8** [comment]
This should be reopened.

**Comment by deluan** [comment]
I will take this into consideration when rewriting the UI in ReactAdmin 4
