### ISSUE TITLE
Implement ArtistArtPriority

### ISSUE THREAD

**Issue by altosys** [navidrome/navidrome#2151]
## Issue

When fetching artist artwork there are several conventions for filenames if a music library is shared with other software by Navidrome, for instance Jellyfin or Plex.

A common structure of a library as an example:

```
/library/artist/artist.jpg
/library/artist/poster.jpg
/library/artist/album/track.flac
```

The current state is that Navidrome looks only for the file `artist.jpg` while in the case of Jellyfin it doesn't coincide with [their expected filenames](https://jellyfin.org/docs/general/server/media/music/#primary) for artist artwork.

## Proposed solution

A configuration parameter similar to `CoverArtPriority` but for artist artwork, i.e. `ArtistArtPriority` as discussed previously in https://github.com/navidrome/navidrome/issues/394, which allows the user to define which filenames Navidrome expects when looking for artist art in the library.

### Additional context

I'm opening this issue to move discussion regarding this feature request here instead of continuing discussion in the closed thread of issue https://github.com/navidrome/navidrome/issues/394.

**Comment by rwdnnz** [comment]
I see that this has been merged but I'm struggling to get this working with the docker-compose env options. I have all my artist images in the folders called `folder.jpg` and `folder.png`. Does the docker env of  `ND_ARTISTARTPRIORITY` exist? And if so, should adding "folder.*"` be enough to pickup the artist images?

**Comment by deluan** [comment]
This is not released yet: https://github.com/navidrome/navidrome/discussions/2334#discussioncomment-5754783

If you are using the `develop` image and it is still not working, please create a new discussion in the [Q&A section](https://github.com/navidrome/navidrome/discussions/categories/q-a). In the future, please avoid asking for support in closed PRs ;)
