### ISSUE TITLE
Internet Radio, Multiple Stream URLs

### ISSUE THREAD

**Issue by andrewgdunn** [navidrome/navidrome#2152]
With the recent addition of #2063 I'd added a stream from [somafm](https://somafm.com/) which by provides their streams in [playlist (e.g. `pls`)](https://en.wikipedia.org/wiki/PLS_(file_format)) form, which specifies multiple stream endpoints. For example [somafm groove salad](https://somafm.com/groovesalad/) provides a `256k mp3` `.pls` file that has the contents:

```
[playlist]
numberofentries=5
File1=https://ice6.somafm.com/groovesalad-256-mp3
Title1=SomaFM: Groove Salad (#1): A nicely chilled plate of ambient/downtempo beats and grooves.
Length1=-1
File2=https://ice4.somafm.com/groovesalad-256-mp3
Title2=SomaFM: Groove Salad (#2): A nicely chilled plate of ambient/downtempo beats and grooves.
Length2=-1
File3=https://ice1.somafm.com/groovesalad-256-mp3
Title3=SomaFM: Groove Salad (#3): A nicely chilled plate of ambient/downtempo beats and grooves.
Length3=-1
File4=https://ice2.somafm.com/groovesalad-256-mp3
Title4=SomaFM: Groove Salad (#4): A nicely chilled plate of ambient/downtempo beats and grooves.
Length4=-1
File5=https://ice5.somafm.com/groovesalad-256-mp3
Title5=SomaFM: Groove Salad (#5): A nicely chilled plate of ambient/downtempo beats and grooves.
Length5=-1
Version=2
```

A user can easily add a stream and specify the specific endpoint enumerated in one of those `fileN=` invocations. However if an internet radio station is doing maintenance and takes one of those endpoints offline it will appear that the stream is "down".

I'd wanted to enumerate a feature request to see:
 - is this a common way to specify streams (e.g. is this something only somafm does?), and therefor impacts users of other streams?
 - would it be plausible to extend the stream to:
     + allow users to specify more than one stream URL that the player can rotate between (if a stream endpoint is unresponsive)
     + allow users to specify a playlist as a stream URL

Thanks for #2063 and the work of @kgarner7 & @deluan, also this might be entirely blocked by what happens with #1651.

**Comment by kgarner7** [comment]
SonaFM Is not the only one that does this (if you want to get a fuller list, you can browse https://www.radio-browser.info/). So yes, this would definitely impact other streams (when writing the feature, I wasn't actually aware of pls). 
Whether or not that will be integrated currently is ultimately up to Deluan (it would require more kludge with the old player code...)
