### ISSUE TITLE
[BUG] Samplers with no Albumartist are scattered

### ISSUE THREAD

**Issue by Apewert** [navidrome/navidrome#2153]
### Description

I have a Sampler with various artists. I usually delete the Tag "ALBUMARTIST" from my mp3 files and rely on the "ALBUM" Tag. When importing them to navidrome, they are scattered to an album for each artist. When I forgot to delete "ALBUMARTIST" and every album artist is the same, it works like it should.

Example for a working one: 
![grafik](https://user-images.githubusercontent.com/96546854/217464151-d38fc8f7-9f51-4b86-92b4-42738a112a16.png)

Example for a not working one:
![grafik](https://user-images.githubusercontent.com/96546854/217464279-36f24322-803f-43e2-8b14-034438d16b24.png)

Here is how it look like in navidrome:
![grafik](https://user-images.githubusercontent.com/96546854/217464559-3ad45a21-3445-45cb-b4e4-b52758053acb.png)

Maybe it could also be a problem of ALBUMSORT

### Expected Behaviour

All mp3 files with the same "ALBUM" ID3-Tag should be in one album.

### Steps to reproduce

Add a Sampler with multiple Artists with no ALBUMARTIST/ALBUMSORT-Tag set to the music database.

### Platform information

 - Navidrome version: 0.49.1
 - Browser and version: Firefox 109.01
 - Operating System: Windows Server 2019

**Comment by deluan** [comment]
To handle these types of albums you need to set the `Par of Compilation` tag, please see https://www.navidrome.org/docs/faq/#i-have-an-album-with-tracks-by-different-artists-why-is-it-broken-up-into-lots-of-separate-albums-each-with-their-own-artist
