### ISSUE TITLE
Shared music player should have a maximum width limit

### ISSUE THREAD

**Issue by Khazbs** [navidrome/navidrome#2155]
### Description

The player of shared music takes up 100% of available width, which looks good on narrow screens (e.g. phones), but not on wide screens (e.g. desktops). Please see screenshot in "Additional information".

### Expected Behaviour

The player's width should be limited to a certain absolute maximum width (e.g. a commonly used width breakpoint — 768 pixels). A limited maximum width makes the player more compact, offering wide screen users better focus on its controls.

### Steps to reproduce

1. Create and copy a link for sharing one song/track in Navidrome;
2. Paste the link in the address bar of a desktop web browser and open the page;
3. See that the player takes the whole width of the window — not ideal UX.

### Platform information

 - Navidrome version: v0.49.1
 - Browser and version: Firefox v109.0.1
 - Operating System: macOS Ventura v13.2

### Additional information

![Screenshot of Navidrome's shared music player taking up all available width (in Firefox on macOS)](https://user-images.githubusercontent.com/15271295/217531645-980eeb50-04a2-4d7d-a614-f8b217b04228.png)

**Comment by Igorgro** [comment]
@kgarner7 There are now white gaps on the sides when using dark theme 
![image](https://user-images.githubusercontent.com/22894169/218302807-215cc504-adeb-47c3-8cf9-067ee17bc3a3.png)
