### ISSUE TITLE
Read ratings from mp3 tracks

### ISSUE THREAD

**Issue by Merkwurdichliebe** [navidrome/navidrome#2158]
### Is your feature request related to a problem? Please describe.

Navidrome doesn't seem to read ratings embedded in the extended tags of a file.

### Describe the solution you'd like

The embedded rating should be displayed in navidrome.

### Additional context

![Screenshot 2023-02-08 at 21 40 57](https://user-images.githubusercontent.com/11777208/217646592-afc53535-efaa-41e9-8603-4f37d5879547.jpg)

Any way to read this into the navidrome interface?

**Comment by deluan** [comment]
Yep, it does not. There has been a lot of discussions about this, you can find them in other issues, but the gist can be found in https://github.com/navidrome/navidrome/issues/1036:

>  POPM and PCNT Rating/popularity and Playcount note: since Navidrome does not write ratings to tags (that would require write access) but keeps them in the database, there needs to be some careful thought how to handle ratings-in-tags: do we read them once, when the file is first scanned? Or keep track of ratings-in-tags independently, and update them whenever the tag gets updated outside of Navidrome?

Another issue is that Navidrome is multi-user, so the ratings found in the files would apply to which user?

You may find some scripts and tools that help importing these tags, but it is not planned as a feature in Navidrome.

**Comment by Merkwurdichliebe** [comment]
Why not just read the ratings tag, display it for all users (maybe with a specific color to signify it's an embedded tag), then when a user changes the rating, add it to the database for that user and display the rating in a different color, meaning it's a user tag only valid in navidrome? The option to import tags, whether by default or not, could be an option in the `.toml` file.
