### ISSUE TITLE
Attempts to edit playlist fail and generate error (.49.1)

### ISSUE THREAD

**Issue by krista611** [navidrome/navidrome#2160]
Upgraded docker container to .49.1; completed successfully without notice or error.  Music streams fine.

Later, tried to reorder songs within a playlist and a window "something went wrong" flashed up. This happens with brand new playlists, created for the test, and old: songs can be added but not reordered or removed. Different users, including admin, see the same result.

I've deleted and rebuilt the image (saved the app data). Did not fix the error.

Next, I set the logs to debug and triggered the error.

### Expected Behaviour

Song order to change within the frame as songs were dragged.

### Platform information

 - Navidrome version: 
 - Browser and version: 
 - Operating System: 

### Additional information

Any other information that may be relevant or give context to the problem.

 - Screenshot attached
 - Logs? 
 - Client used? 
![2-9-2023 5-01-40 PM](https://user-images.githubusercontent.com/11448132/218103881-45c36264-8759-453a-a217-a6dd509fe552.png)
![2-10-2023 8-30-25 AM](https://user-images.githubusercontent.com/11448132/218104178-2a2620a9-840b-48b7-a0a9-93618293ac26.png)

**Comment by deluan** [comment]
Thanks for reporting. This is fixed and will be part of 0.49.2: https://github.com/navidrome/navidrome/commit/9b2dd1bb06abc8c43b17ec20933614f7b901edc0
