### ISSUE TITLE
"Failed to apply new migrations" when updating to 0.49.2 from 0.47.5

### ISSUE THREAD

**Issue by ribtoks** [navidrome/navidrome#2168]
### Description

I downloaded Navidrome 0.49.2 and replaced 0.47.5, but it does not start.

The error from the logs is: 
```
Feb 12 13:48:09 salo navidrome[1151]: time="2023-02-12T13:48:09+02:00" level=fatal msg="Failed to apply new migrations" error="ERROR 20230209181414_change_image_files_list_separator.go: failed to run Go migration function func(*sql.Tx) error: sql: Scan error on column index 1, name \"image_files\": converting NULL to string is unsupported"
```

### Platform information

 - Navidrome version: v0.49.2
 - Operating System: Raspbian

### Additional information

Version 0.48.0 works.

**Comment by propserer** [comment]
Same problem here but my Navidrome on docker container

```
 _   _             _     _

| \ | |           (_)   | |

|  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___

| . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \

| |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/

\_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|

                          Version: 0.49.2 (3cd934ab)

time="2023-02-12T12:34:37Z" level=fatal msg="Failed to apply new migrations" error="ERROR 20230209181414_change_image_files_list_separator.go: failed to run Go migration function func(*sql.Tx) error: sql: Scan error on column index 1, name \"image_files\": converting NULL to string is unsupported"
```

**Comment by RainbowPants** [comment]
upgrading from 0.49.1 to 0.49.2 fails as well for me with same error. downgrading to 0.49.1 works fine.
guessing this [this](https://github.com/navidrome/navidrome/blob/3cd934abd7f7e680f0ea3595b6d750e80963f308/db/migration/20230209181414_change_image_files_list_separator.go) file is the culprit

**Comment by csaleman** [comment]
Same issue here going from 0.48.0 to 0.49.2. I was able to make it work by downgrading to 0.49.1 first and then performing a full scan. The migration to 0.49.2 worked after that.

**Comment by deluan** [comment]
I'll try to release a 0.49.3 later today, to address this. Thanks for reporting!

**Comment by dolugen** [comment]
> Same issue here going from 0.48.0 to 0.49.2. I was able to make it work by downgrading to 0.49.1 first and then performing a full scan. The migration to 0.49.2 worked after that.

Same story here. Re-deploying an older version and upgrading again worked for me.

As a side effect, albums that didn't have cover art now have them?? I didn't know pulling cover art was a feature (or how to trigger it).

**Comment by deluan** [comment]
> As a side effect, albums that didn't have cover art now have them?? I didn't know pulling cover art was a feature (or how to trigger it).

Starting with 0.49.0, Navidrome now also tries to extract images using `ffmpeg`, and as a last resort it tries to pull cover art from Last.fm. This is configurable. See https://www.navidrome.org/docs/usage/artwork/#albums
