### ISSUE TITLE
Database disk image is malformed

### ISSUE THREAD

**Issue by 4volodin** [navidrome/navidrome#2175]
Hello.
My navidrome container is restarting and in logs I am getting error
_level=fatal msg="Failed to apply new migrations" error="ERROR 20221219112733_add_album_image_paths.go: failed to run Go migration function func(*sql.Tx) error: database disk image is malformed"_
How to fix it? 
Thanks.

**Comment by 4volodin** [comment]
It's so pitty
I was forced to re-create DB file to start the docker container
I consider it happened after an update(I dont't remember version because I've been trying many ones for last months)
(arm64 Raspbian)

**Comment by deluan** [comment]
Sorry for late reply. This is a duplicate and was fixed yesterday: #2168. I'll release a new version with the fix tonight.
