### ISSUE TITLE
The selected track from the "share" list does not start on the touch screen

### ISSUE THREAD

**Issue by Sevinfolds** [navidrome/navidrome#2184]
The selected track from the "share" list does not start on the touch screen of the smartphone. You cannot select to start a specific track. The second question is, in the "share" list, you can move tracks, swap them, is it possible to turn it off somehow?

**Comment by deluan** [comment]
Hey @Sevinfolds, sorry for the delay. 

These are limitations of the current player. As I said in other issues related to the player, I'm not spending too much time fixing issues in it as we plan to move to a different player implementation. Unfortunately I can't give you any timelines.

I'll close this for now, but feel free to chime in if you have any other concerns.
