### ISSUE TITLE
Add the artist's name to the "share" playlist

### ISSUE THREAD

**Issue by Sevinfolds** [navidrome/navidrome#2185]
Would love to see "artist name - track name" in the open playlist "share". It would be convenient if there are several artists in the list, and it was clear which track belongs to whom

**Comment by deluan** [comment]
Like this?
<img width="368" alt="Screenshot 2023-02-17 at 9 53 11 AM" src="https://user-images.githubusercontent.com/331353/219687994-bd6db5b6-81eb-407d-b9f7-d1087edc55d6.png">

**Comment by Sevinfolds** [comment]
Yes, that would be great!

**Comment by deluan** [comment]
Well, that's a screenshot of the current implementation, that what you should be seeing. Can you share a screenshot of what you see?

**Comment by Sevinfolds** [comment]
Strange, I just looked, really everything is there. Can the previous question be corrected? https://github.com/navidrome/navidrome/issues/2184
