### ISSUE TITLE
Safari - consecutive play album clicks not starting playback

### ISSUE THREAD

**Issue by bbsixzz** [navidrome/navidrome#2191]
Version 16.3 (16614.4.6.11.6, 16614)

Individual tracks work but not albums, I have to destroy the player to be able to start playing an album again.

https://user-images.githubusercontent.com/47334163/218942557-f2d01763-37db-4f3e-a051-f0f0636027b9.mov

**Comment by deluan** [comment]
Can't reproduce... 

https://user-images.githubusercontent.com/331353/219065033-d12bf3d0-3038-4142-8646-f2fef8d9173a.mov


Do you see anything in the logs when you click the second album?

**Comment by bbsixzz** [comment]
Thanks I found the culprit, `Auto-Play` was set to`Never Auto-Play` in settings.

![Screen Shot 2023-02-15 at 20 38 53](https://user-images.githubusercontent.com/47334163/219135778-f854c47f-409c-4d29-8532-c6d5558ce051.png)

The favicon is wrong but that's another Safari specific issue, sigh…

It ignores different ports on the same domain so it uses one icon for everything: https://github.com/MichaIng/DietPi/issues/3267
