### ISSUE TITLE
user registration via api

### ISSUE THREAD

**Issue by susl16c** [navidrome/navidrome#2192]
Tell me how can I create a user using the api if the user has registered on the forum? In other words, simultaneous registration of users both on the forum and in your script.

**Comment by metalheim** [comment]
Navidrome uses (part of) the Subsonic API which also has a createUser endpoint:
http://www.subsonic.org/pages/api.jsp#createUser

But i don't think navidrome has implemented the createUser endpoint
https://www.navidrome.org/docs/developers/subsonic-api/

**Comment by deluan** [comment]
This is not implemented in the Subsonic API and won't be. You can potentially do that use the Native API, but requires some coding. You could see how it works by using the inspect window in Chrome.

**Comment by tdzz1102** [comment]
You can create user using the navidrome api.

```py
def create_user(username, password):
    # log in to get token
    login_url = "https://your.navidrome.server/auth/login"
    login_data = {
        "username": 'admin_user',
        "password": 'admin_pass'
    }
    login_response = requests.post(login_url, json=login_data, verify=False)
    login_response_json = login_response.json()
    token = login_response_json.get("token")

    if token:
        # create user
        create_user_url = "https://your.navidrome.server/api/user"
        headers = {
            "x-nd-authorization": f"Bearer {token}"
        }
        user_data = {
            "isAdmin": False,
            "userName": username,
            "name": username,  
            "password": password
        }
        create_user_response = requests.post(create_user_url, headers=headers, json=user_data, verify=False)
        create_user_response_json = create_user_response.json()
        return create_user_response_json
```

If successful, you'll get a response like `{"id": "f79bf8a0-722d-4bc9-8159-d79e703721e1"}`.

**Comment by deluan** [comment]
Thanks for the code sample @tdzz1102.
