### ISSUE TITLE
Allow "artist" in CoverArtPriority 

### ISSUE THREAD

**Issue by c0utta** [navidrome/navidrome#2195]
Further to my comment https://github.com/navidrome/navidrome/pull/1921#issuecomment-1382900146

I realise that Navidrome pulls cover art on the fly (ie doesn't store paths in the db like subsonic), so I have been embedding images into audio files as suggested by deluan.  Quite a laborious process.

I know this is niche feature request, but would it be possible to add "artist" to CoverArtPriority so that the artist images (logic specified in https://www.navidrome.org/docs/usage/artwork/#artists) can be used?

For me: CoverArtPriority = cover.*, artist, folder.*, front.*, embedded, external

Compilations would then require that cover.* be renamed to folder.* or front.* but I can live with that.  My original comment stands - compilation cover art is usually boring!

**Comment by deluan** [comment]
This would't allow individual tracks to display different artist images, as the `CoverArtPriority` is used for albums, not tracks.

As you can read [here](https://www.navidrome.org/docs/usage/artwork/#mediafiles), Navidrome tries to read the embedded image for a track, if it cannot find it, then it falls back to the album art (using the album ID), which then uses the `CoverArtPriority` config option for that album. So in this case, if your tracks do not have any embedded images, they would all show the same cover.

**Comment by c0utta** [comment]
Understood.  Under the misconception that cover art was by track.

I'll close this request.  Thanks for your work on Navidrome - it is most appreciated by the community.
