### ISSUE TITLE
Concurrent probe and scan?

### ISSUE THREAD

**Issue by mayli** [navidrome/navidrome#2196]
### Is your feature request related to a problem? Please describe.
Full scanning a large collection is slow, it could be faster if navidrome could process changed folder concurrently.

### Describe the solution you'd like
Scan folders concurrently

### Describe alternative solutions that would also satisfy this problem
Probe files concurrent if possible.

**Comment by deluan** [comment]
Yes, that's something I'm working on. By the way, how large is your collection(# folders and # files), are you using a local or networked drive, and how long does it take to run a full scan and a quick scan? These info can help me with improving it.

**Comment by mayli** [comment]
It's a NAS (HDD) over NFS, I had a draft patch that enables concurrent scan, but it could be much better if navidrome can support it in the upstream.
```
	var wg sync.WaitGroup
	jobChan := make(chan string, 1)

	for i := 1; i <= 8; i++ {
		wg.Add(1)
		go func(jobChan <-chan string, i int) {
			defer wg.Done()
			for path := range jobChan {
				log.Info("Processing changed folder", "i", i, "dir", path)
				err := s.processChangedDir(ctx, refresher, fullScan, path)
				if err != nil {
					log.Error("Error updating folder in the DB", "dir", path, err)
				}
			}
		}(jobChan, i)
	}

	for {
		folderStats, more := <-foldersFound
		if !more {
			break
		}
		progress <- folderStats.AudioFilesCount
		allFSDirs[folderStats.Path] = folderStats

		if s.folderHasChanged(folderStats, allDBDirs, lastModifiedSince) {
			changedDirs = append(changedDirs, folderStats.Path)
			jobChan <- folderStats.Path
		}
	}
	close(jobChan)
	wg.Wait()
```
the refresher also need a mutex to prevent inserting the same artist and breaks the UNIQUE constraint in sqlite
```
func (r *refresher) flushMap(ctx context.Context, m map[string]struct{}, entity string, refresh refreshCallbackFunc) error {
	if len(m) == 0 {
		return nil
	}
	r.mu.Lock()
	defer r.mu.Unlock()
```

**Comment by deluan** [comment]
I'm going with a different approach, and I'm rewriting the scanner to follow the Go pipelines pattern. But if you get it done in the current implementation and want to contribute it back, I'd be happy to review and merge it :)

**Comment by deluan** [comment]
You just have to be careful to avoid multiple simultaneous writes to the DB, or SQLite3 can slow down everything. Maybe you can try to use [`BEGIN CONCURRENT`](https://www.sqlite.org/cgi/src/doc/begin-concurrent/doc/begin_concurrent.md#:~:text=Usually%2C%20SQLite%20allows%20at%20most,system%20still%20serializes%20COMMIT%20commands.) if this becomes an issue.

**Comment by mayli** [comment]
I could work a bit and provide a cleaner version of the draft patch copied from gobyexample.com.
The mutex at flushMap seems to be good enough to prevent the race condition of 
 - look up artist
 - insert artist
It also prevents concurrent writes as well, but that's not a major concern for me.

**Comment by deluan** [comment]
The mutex in the refresher will only prevent writing multiple album/artists at the same time, but won't prevent [writing](https://github.com/navidrome/navidrome/blob/d303ad26764c9af0423a981dd20af211a68e37f7/scanner/tag_scanner.go#L384-L385 ) or [deleting](https://github.dev/navidrome/navidrome/blob/d303ad26764c9af0423a981dd20af211a68e37f7/scanner/tag_scanner.go#L349)  multiple MediaFiles in the DB.

**Comment by mayli** [comment]
Ahh, then I guess I will wait for the upstream version.

**Comment by 112RG** [comment]
Wouldn't doing this concurrently slow it down just as much? I would imagine the slow down here is disk IO

**Comment by mayli** [comment]
Imagine each disk up costs 100ms, and there is a queue/raid on the nas. So by making requests concurrently, the disks can reach a better utilization.

**Comment by 112RG** [comment]
I would very much be interested in comparing performance with this vs sync. I have toyed with it on my music server Deaftone and it gave no benefit at least from my little time trying it. Since we also have to do queries checking if ids exists etc which slowed it down slower than sync. I wonder how long it would take for a full scan of your library with my rust scanner.
