### ISSUE TITLE
Cancel scanning on exit or Received termination signal

### ISSUE THREAD

**Issue by mayli** [navidrome/navidrome#2197]
### Description

navidrome still continue the scanning after receiving ctrl-c

### Expected Behaviour

It would be nice if navidrom cancel the scan on exit.

### Steps to reproduce

Prepare a large music set on nas, or add a delay in `s.folderHasChanged`, start navidrome and press C-c.

```
^CINFO[0073] Received termination signal                   signal=interrupt
INFO[0073] Stopping HTTP server
```
But the scanning will still continue and navidrome will stuck at foreground.

### Platform information

 - Navidrome version: latest
 - Browser and version: doesn't matter
 - Operating System: linux

**Comment by deluan** [comment]
Yeah, I'lll fix this 👍🏼

**Comment by mayli** [comment]
my fix is `pkill -9 navidrome`, probably not ideal to include it in the upstream :(
