### ISSUE TITLE
Pagination in /app/#/artist for large collection

### ISSUE THREAD

**Issue by mayli** [navidrome/navidrome#2199]
### Is your feature request related to a problem? Please describe.
My collection as too many albums in `VA` (various artists), and the web will stuck on loading it.

### Describe the solution you'd like
Pagination on the artist page could help resolve this issue.

**Comment by deluan** [comment]
The "Various Artists" (exactly this name) page IS paginated. Unless yours has a different name/spelling.
<img width="1548" alt="Screenshot 2023-02-17 at 9 38 18 AM" src="https://user-images.githubusercontent.com/331353/219684643-00491c31-419a-4ace-851f-0ba5a9eacf5f.png">

**Comment by mayli** [comment]
![image](https://user-images.githubusercontent.com/822628/219757402-361bb8a8-8311-4dc5-9427-0e58acb214dc.png)
I guess I have too many other names for `Various Artists`. Is there a way to allow it handle those as well?

**Comment by deluan** [comment]
The solution for that is to add infinite scroll to the artist view, with I don't have current plans to add to the current UI. The workaround is to disable the artist view, and go back to a paginated list of albums for any artist. This can be achieved by setting `DevShowArtistPage=false`. You are going to lose artist images and bio, though.

Ideally, you should tag all "Various Artists" with the same name, to avoid this issue.

**Comment by deluan** [comment]
Hey @mayli , can I close this? Were you able to change the `DevShowArtistPage` config option?
