### ISSUE TITLE
Feature Request: Self-hosted Rotating Background Images

### ISSUE THREAD

**Issue by tggjifdhn** [navidrome/navidrome#2202]
Please add support for multiple image URLs and randomly pick among them.

Alternatively add support for an image folder on the host machine.

**Comment by dodedodo** [comment]
I'm assuming you are referring to the login screen background. 

Iirc navidrome already supports setting a custom background using an env variable. It would be trivial to set that url to a page that serves random images. [Loremflickr](https://loremflickr.com/1920/1080/abstract) comes to mind. Or you could write it yourself in a couple lines of php, nodejs, perl or probably nginx even. 

I don't think this needs to be part of navidrome.

**Comment by ghenry22** [comment]
The ability to just set a simple css gradient would be great as well. I don’t need any images really on a login screen.

**Comment by deluan** [comment]
@tggjifdhn Thanks for the suggestion, but I don't have plans to add this to Navidrome, at least not with the current UI. Please refer to the alternative suggested by @dodedodo .

@ghenry22 Not a gradient, but you can replace the background image with an inline `data:` url. See #154.
