### ISSUE TITLE
0.49.3 - ffmpeg not found

### ISSUE THREAD

**Issue by pulberg** [navidrome/navidrome#2203]
### Description

After upgrading from 0.49.0 to 0.49.3 ffmpeg is no longer found.

### Expected Behaviour

Absolute path to ffmpeg set in transcodings command should be honored and used. (this worked in 0.49.0)

In 0.49.0 I set the options for transcodings like - 

`/opt/homebrew/bin/ffmpeg -i %s -map 0:0 -b:a %bk -v 0 -c:a libopus -f opus -` this worked great.

After upgrading to 0.49.3 none of my FLAC files would play, after checking the log i found these - 

`time="2023-02-15T17:37:01-06:00" level=warning msg="API: Failed response" endpoint=/rest/stream.view error=0 message="Internal Server Error: invalid argument" requestId=myhost/Hizz6RIwPF-188001 username=pulberg`

`time="2023-02-15T17:37:01-06:00" level=error msg="Error starting transcoder" error="exec: \"ffmpeg\": executable file not found in $PATH" id=058899595b82093a026af33ba9edeae6 requestId=myhost/Hizz6RIwPF-188002 username=pulberg`

`time="2023-02-15T17:37:01-06:00" level=error msg="Error accessing transcoding cache" error="invalid argument" id=058899595b82093a026af33ba9edeae6 requestId=myhost/Hizz6RIwPF-188002 username=pulberg`

One of the errors said ffmpeg could not be found in my $PATH, i checked and the path is correct - 

`➜ echo $PATH
/Users/pulberg/.jenv/bin:/opt/homebrew/opt/openjdk/bin:/Users/pulberg/.krew/bin:/Users/pulberg/.guard/bin:/opt/homebrew/sbin:/opt/homebrew/bin:`

I read the notes for 0.49.2 and saw that a new param has been added for an ffmpeg path, so I edited my `.toml` file, added the param and value, restarted Navidrome and files now play correctly.

There are a few issues - 
1. The "not found in $PATH" log message is misleading and confusing, and apparently not working, for me at least.
2. If absolute paths in transcodings previously worked, then they should continue to work or be called out as a breaking change.

### Platform information

 - Navidrome version: 0.49.3
 - Browser and version: Chrome 110.0.5481.100 (Official Build) (arm64)
 - Operating System: macOS Ventura 13.2.1, M1 Mac Studio

**Comment by deluan** [comment]
You are right, and I'll take a look at that as soon as I can. In the meantime, the workaround is to set `FFmpegPath` config option to the full `ffmpeg` path (in your case `FFmpegPath=/opt/homebrew/bin/ffmpeg`) and leave the transcoding command without a path (it will use the one configured): `ffmpeg -i %s -map 0:0 -b:a %bk -v 0 -c:a libopus -f opus -`

I'll see if I can make it more "inteligent" and honor the path specified in the transcoding command.
