### ISSUE TITLE
Hope  hope hope   Everyone can set up their own music folder

### ISSUE THREAD

**Issue by idmanage** [navidrome/navidrome#2207]
### Is your feature request related to a problem? Please describe.

Everyone can set up their own music folder

### Describe the solution you'd like

Each user can configure their own music folder path in the Settings

**Comment by SickProdigy** [comment]
well from the backend you could. setup ftp users with their own folder from within the main folder navidrome watches. It will add anything anyone adds to those folders.

**Comment by idmanage** [comment]
> well from the backend you could. setup ftp users with their own folder from within the main folder navidrome watches. It will add anything anyone adds to those folders.

But in the music interface, everyone can see other people's music, I hope that I can only see my own uploaded music, other users are the same

**Comment by dweymouth** [comment]
What you're asking for is multiple libraries. Navidrome doesn't currently support multiple root music folders, and support for this would have to come before support for multiple libraries, I imagine. But it may eventually come.

**Comment by dweymouth** [comment]
See also this ticket https://github.com/navidrome/navidrome/issues/192 which is asking for this feature

**Comment by ghenry22** [comment]
> What you're asking for is multiple libraries. Navidrome doesn't currently support multiple root music folders, and support for this would have to come before support for multiple libraries, I imagine. But it may eventually come.

Music folders are a core concept from the original subsonic and granting rights to different music folders is supported out of the box.

So while implementation may take effort on the navidrome side there is at least an example of how it might be done and support in the subsonic api which is neat.

the default behaviour if a music folder is not specified is to show all content from all which is basically as it is now with navidrome.

music folders are also handy for segregation of different types of content but support in subsonic clients is hit and miss.

**Comment by deluan** [comment]
@idmanage Thanks for the suggestion. Multiple music folders will be implemented in #192, which will also allow permissions per folder, similar to the original Subsonic implementation. Managing multiple folders will be restricted to admins only.

There won't be a way for each user set up their own folder, the admin would have to create a folder for each new user added to the system, and set the permission for that folder accordingly. 

Anyway, I'm closing this as the use case is already covered in #192.
