### ISSUE TITLE
Navidrome sometimes crashes when I download albums in the Substreamer iOS app

### ISSUE THREAD

**Issue by lrebscher** [navidrome/navidrome#2211]
### Description

When downloading albums for the client, Navidrome sometimes gets stuck and crashes (see attached stack trace).
I cannot yet reproduce it deterministically, but maybe the logs help already to identify the issue.

The sonixd client was running in the background as well, but I observed the download issue a couple of times in the last week without any other client running.

### Expected Behaviour

Album gets downloaded without Navidrome crashing.

### Steps to reproduce

1. Download album in substreamer app

### Platform information

 - Navidrome version: [0.49.3](https://github.com/navidrome/navidrome/releases/tag/v0.49.3)
 - Operating System: Raspbian GNU/Linux 10 (buster), Navidrome runs in docker container

### Additional information

- [full json.log of the container showing two crashes](https://github.com/navidrome/navidrome/files/10830976/5b7986a06e2ff64f40e136e0a7436a53a5fe9264579859700d6f5a04765c5761-json.log.zip)
- client: Substreamer iOS App, 6.0.6
- sonixd 0.15.3

**Comment by chinalichen** [comment]
I'm facing this problem also.

Bug Reproductions
1. play one song.
2. switch to next song.
3. drag the progress bar to 80%.
4. oops, substreamer crash.

----------------
substreamer works fine with airsonic, same playlist.

**Comment by lrebscher** [comment]
@chinalichen seems to me like a different problem since substreamer is crashing but not navidrome. Would suggest to post this also in the [substreamer reddit channel](https://www.reddit.com/r/substreamer/) since the app should not crash even if navidrome is doing sth unexpected. :)

**Comment by lrebscher** [comment]
I can now reproduce a problem and a crash but it has nothing to do with downloading the albums and the crash occurs only when using sonixd client (0.15.3).

**Scenario:**
-  I have an album that consists of songs in wma format.
- when I want to stream a single song of this album in the Navidrome UI or in the substreamer app, the loading spinner is displayed indefinitely in the UI and I see a single "Streaming file" request in the container logs
- when I do the same action in Substreamer or Sonixd client, it bombards the server with "Streaming file" requests until the server crashes

Independent of the client, I can not play the wma songs.
Interestingly, I was able to play these songs yesterday via substreamer app without an issue (I'll try again once scan completed, maybe it has sth do with that).

[Container Info Log of Reproduction steps with sonix client](https://github.com/navidrome/navidrome/files/10951615/crash.txt)
[Container Debug Log of Reproduction steps with sonix client](https://github.com/navidrome/navidrome/files/10951687/crash_debug.txt.zip)

**Comment by lrebscher** [comment]
I could get the wma files to play in Navidrome UI and sonixd by setting transcoding of the player to mp3 as suggested in [this issue](https://github.com/navidrome/navidrome/issues/1592#issuecomment-1023014852).

Doesn't work with substreamer though, but I guess I'll just convert the wma files to mp3 by using ffmpeg to circumvent these issues.

It would be nice if there could be either (1) some kind of error message in case the format is not supported or (2) a fallback to mp3 transcoding.

**Comment by deluan** [comment]
Glad you made it work. As you already figured out, .WMA is not supported in most platforms, it needs to be transcoded for mobile clients and web browsers to play it.

Reading the logs, I see Sonixd is bombarding your server with stream requests, basically causing a DOS attack :) Not sure if this is something with Sonixd when (trying to) play .WMA files? @jeffvli any ideas?

For your suggestions "(1) some kind of error message in case the format is not supported or (2) a fallback to mp3 transcoding", both have to be handled on the client, not server. For Navidrome UI, we have an issue already open to implement this: #2051

**Comment by deluan** [comment]
Thanks @jeffvli . Maybe there is a way to check if the error is something like "format not supported" or similar, so you wouldn't even need to try again?

@lrebscher , can we close this now?
