### ISSUE TITLE
Option to calculated average artist and album ratings from their respective song ratings 

### ISSUE THREAD

**Issue by isle9** [navidrome/navidrome#2212]
### Is your feature request related to a problem? Please describe.

The problem right now is that I need to rate all of my artists and albums individually.

### Describe the solution you'd like

I would instead like to just be able to rate songs and automatically get a rating for artists and albums.

### Describe alternative solutions that would also satisfy this problem

/

### Additional context

It would also be nice if this could be introduced for genres, if they ever get ratings in some ways, and even for other data like years, decades, and pretty much anything else.

**Comment by certuna** [comment]
You can also rate artists and albums directly - how would this work?

- Suppose an artist has three songs rated 4 stars, OK, Navidrome calculates the artist rating as 4 stars
- Suppose you then set the artist rating to 5 stars directly from the UI - what happens then? Artist rating = 5 stars?
- Suppose you then rate another song with 4 stars, what happens then? Recalculated back to 4 stars? Stay at 5 stars?

**Comment by certuna** [comment]
I think this could be done - the "blacklist" would then just be a boolean in the `artist` and `album` table, and would be set to 1 soon as you manually rate an artist or album, and set back to 0 when you remove the rating, where it would revert back to the track average.

TBH I'm still not entirely convinced that the behaviour is desirable/logical to users that when the user rates one good song on an album/playlist five stars, and doesn't rate any other songs, the album automatically becomes a five star album. But if enough people like it, why not.

Can you code in Go? If you can find a good way to implement it, you can write a PR & submit it for review.

**Comment by isle9** [comment]
> TBH I'm still not entirely convinced that the behaviour is desirable/logical to users that when the user rates one good song on an album/playlist five stars, and doesn't rate any other songs, the album automatically becomes a five star album. But if enough people like it, why not.

There could be an option to either keep the manual sort until you rate a certain amount of songs or a way to either filter or sort albums / artists that don't have a certain number of manually rated songs yet.
I personally prefer the second option. You could set up your default album / artist lists to only show those that have enough rated songs, and you could have an extra smart playlist to show them all together or just the ones that don't have enough rated songs.

> Can you code in Go? If you can find a good way to implement it, you can write a PR & submit it for review.

Unfortunately no, but there's a possibility that I maybe learn it in the somewhat near future.
