### ISSUE TITLE
Feature request: in artist view, seperate artist's albums from compilations the artist appears on

### ISSUE THREAD

**Issue by emes81** [navidrome/navidrome#2214]
Say, for instance, that a Navidrome instance has a lot of DJ Screw mixes. All of them, even. Clicking 2pac's artist page on that Navi instance would show hundreds of DJ Screw mixes; 2pac's actual albums would be lost in the haystack.

An easy fix to this would be to split between "Albums" and "Appears on"

Jellyfin does something similar:

![image](https://user-images.githubusercontent.com/25403691/221603547-3bbb5d01-8280-4f31-b973-d9566c66986a.png)

**Comment by metalheim** [comment]
This already included in #961

**Comment by certuna** [comment]
PR submitted: sort artist's own albums before his compilation appearances.
