### ISSUE TITLE
Lyrics continue to display for previous track if you press next track

### ISSUE THREAD

**Issue by metalsl** [navidrome/navidrome#2218]
### Description

Lyrics continue to display (overlapping) for the previous track if you press the "next track" button in the web GUI.

### Expected Behaviour

Lyrics should only display for currently playing track.

### Steps to reproduce

1. Start a track and display lyrics
2. Allow lyrics to start showing
3. Press next track button
4. Previous track's lyrics will continue to display and will be mixed in with lyrics from the current track.

### Platform information

 - Navidrome version: v0.49.3
 - Browser and version: Chrome Version 109.0.5414.119 and Firefox 110.0 (64-bit)
 - Operating System: 

### Additional information

Lyrics behave properly when clicking on a new track directly in the GUI.  This only seems to happen using the "next track" button.

**Comment by leafney** [comment]
v0.50.1 encountered the same problem
