### ISSUE TITLE
Download link copy (like in sonixd)

### ISSUE THREAD

**Issue by rombat** [navidrome/navidrome#2221]
### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/9024503/222740211-ca6a278b-3edc-444a-a5f9-f8ffd31ed799.png)
Sonixd has a nice feature that allow the user to copy download link, along with the download button.
That would be nice to have such a feature in Navidrome

**Comment by deluan** [comment]
I don't think this is a good idea, even in Sonixd, as it exposes the authentication in the generated link. Whoever gets the link can use it to access any functionality of your server exposed through Subsonic API. If you are an admin, they can modify/delete playlists, users, shares, etc... I'd say it is a *big* NO!

On the other hand, I'll implement download for shares in #2125, so you will be able to create a share of the album/artist/song/playlist, and send it as a safe link to anyone, without compromising your authentication.

I'm closing this as it won't be implemented like Sonixd, and it will be possible with #2125.

CC: @jeffvli, please consider removing this functionality, or supporting Shares.
