### ISSUE TITLE
[Bug]: RecentlyAddedByModTime stopped working

### ISSUE THREAD

**Issue by mpodshivalin** [navidrome/navidrome#2233]
### But first, have you done your homework?

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3 (8b93962f)

### Current Behavior

When using a ND_RECENTLYADDEDBYMODTIME=true Docker parameter, Recently added still sorts albums by its import date, not file modification date

### Expected Behavior

Sorting by "Recently added" should sort albums by their file modification date

### Steps To Reproduce

1. Run Navidrome with ND_RECENTLYADDEDBYMODTIME=true
2. Add a song with file modification date 1990-01-01
3. Go to Recently added albums
4. See it on the top of the list

### Environment

```markdown
- OS: Debian 11.5
- Browser: Firefox 110
- Client: Navidrome
```

### How Navidrome is installed?

Docker

### Configuration

```toml
docker run -d \
  --name navidrome \
  -v /mnt/data0/music:/music \
  -v /home/debian/navidrome/data:/data:rw \
  -p 4533:4533 \
  -e ND_LOGLEVEL=error \
  -e ND_SESSIONTIMEOUT=24h \
  -e ND_LISTENBRAINZ_ENABLED=false \
  -e ND_LASTFM_ENABLED=false \
  -e ND_ENABLEEXTERNALSERVICES=false \
  -e ND_RECENTLYADDEDBYMODTIME=true \
  docker.io/deluan/navidrome:latest
```

### Anything else?

**There were no such issues 1-2 releases earlier, everything worked correctly**

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
Also, please change your `ND_LOGLEVEL` to `debug`, and check in the startup log if the value was actually read:
```
Starting service
 _   _             _     _
| \ | |           (_)   | |
|  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___
| . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
| |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
\_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
                                        Version: dev

Loaded configuration from '/Users/deluan/Development/navidrome/navidrome.toml': &conf.configOptions{
...
    Address:                          "localhost",
    Port:                             4533,
    MusicFolder:                      "music",
    DataFolder:                       "./data",
...
    RecentlyAddedByModTime:           true,
...
}
DEBU[0000] Opening DataBase                              dbPath="data/navidrome.db?cache=shared&_busy_timeout=15000&_journal_mode=WAL&_foreign_keys=on" driver=sqlite3
```

**Comment by mpodshivalin** [comment]
Thank you for such quick response!

I've checked and it seems that the issue is connected to the update process. So the actual steps to repeat the problem are more complicated:
1. Run Navidrome [v0.48.0](https://github.com/navidrome/navidrome/releases/tag/v0.48.0) with ND_RECENTLYADDEDBYMODTIME=true
2. Add a song with file modification date 1990-01-01
3. Go to Recently added albums
4. See it at the end of recently added albums - everything works correctly so far
5. Update to [v0.49.0](https://github.com/navidrome/navidrome/releases/tag/v0.49.0)
6. See it on the top of the list

Even if I downgrade to v0.48.0 after the update, the album still shows up on top

**Comment by deluan** [comment]
Ah, this may be caused by the fact that 0.49.0 added some DB migrations that require a full scan. When this happens, the `updated_at` times in the DB become zero until the next scan. Check the "Updated At" value of one of the albums. If this is the case, just run a scan and it should be fixed when it finishes.

Please let me know.

**Comment by mpodshivalin** [comment]
> Ah, this may be caused by the fact that 0.49.0 added some DB migrations that require a full scan. When this happens, the `updated_at` times in the DB become zero until the next scan. Check the "Updated At" value of one of the albums. If this is the case, just run a scan and it should be fixed when it finishes.
> 
> Please let me know.

I've tried a full scan but for some reason it doesn't help, I've double checked the modified times, and they are definitely old :)

So in short I've found that:
* Full scan on v0.48.0 does not put the albums on top
* Full scan on v0.49.0 does not put the albums on top as well (if the tracks are new)
* If tracks were scanned on v0.48.0, after the update, v0.49.0 puts albums on top of the recently added

**Comment by deluan** [comment]
Sorry, but I can't reproduce it locally. Is it possible for you to send me your 0.48.0 `navidrome.db` file? If you can, send it to deluan @ navidrome.org

**Comment by mpodshivalin** [comment]
If this issue is not reproducible, it seems like the problem in somewhere in my configuration/data, I'll try to debug more first and narrow down the issue in order to not waste your time :) Will report in a couple of days. The software is great, I've just finished importing my 1007 albums music collection, with ratings and play counts :)

**Comment by mpodshivalin** [comment]
I've just waited and added new albums for a while, so now this is no longer an issue (after the upgrade, old albums still come on top, but not before the new albums I've added)
The issue is probably somewhere on my side either way, so the problem is solved :)
