### ISSUE TITLE
[Bug]: EnableFavourites=false does not hide Favourite button in artist page

### ISSUE THREAD

**Issue by sjohannes** [navidrome/navidrome#2245]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3

### Current Behavior

The Favourite button is shown in artist page when EnableFavourites=false.

### Expected Behavior

The Favourite button is hidden in artist page when EnableFavourites=false.

### Steps To Reproduce

1. Set EnableFavourites = false.
2. Go to an artist details page.
3. See the Favourite button next to the artist name.

### How Navidrome is installed?

Binary (from downloads page)

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
Thanks for reporting!
