### ISSUE TITLE
Field smart_count doesn't work when use translation

### ISSUE THREAD

**Issue by SoSolife** [navidrome/navidrome#2261]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3(377e7eb)

### Current Behavior

For examples, 
it would show second field when I add some songs to playlist according to this [translation](https://github.com/navidrome/navidrome/blob/7ea111322b5a9d9bae0041a0db732bf06fc50ba2/resources/i18n/zh-Hans.json#L346), but it only shows first field. On the contrary, it shows correctly in English without translations. And it has same problem with deleting some songs from playlist.

### Expected Behavior

It will show correctly as well as in English when I use translation.

### Steps To Reproduce

1. With translation,

![2023-03-17_164236](https://user-images.githubusercontent.com/24560074/225856638-cfda7b76-2aa2-4533-89b7-7e1d4676aa27.jpg)
![2023-03-17_164259](https://user-images.githubusercontent.com/24560074/225856681-6acf2afd-c679-4e0a-bee3-c6580c8df55b.jpg)
![2023-03-17_164333](https://user-images.githubusercontent.com/24560074/225860481-5b348577-02fb-41a9-b400-f738181a3b20.jpg)
![2023-03-17_164344](https://user-images.githubusercontent.com/24560074/225860551-91c70f9e-f7ea-4b35-8cae-b4fea8b2bd3e.jpg)

3. Without translation,

![2023-03-17_164409](https://user-images.githubusercontent.com/24560074/225857992-68859a22-1cb6-414c-8a1b-3b2be8a6a771.jpg)
![2023-03-17_164419](https://user-images.githubusercontent.com/24560074/225858034-ec27a39d-f86b-411f-8190-82148c633857.jpg)
![2023-03-17_164551](https://user-images.githubusercontent.com/24560074/225860843-55f164ed-ffd5-48ea-a122-872e8ef762ef.jpg)
![2023-03-17_164636](https://user-images.githubusercontent.com/24560074/225860868-44010b9a-7ac5-4cd3-b316-29961a244e1b.jpg)

### Environment

```markdown
- OS: Debian 11
- Browser: Chrome 111.0.5563.65 on Windows 11
```

### How Navidrome is installed?

Binary (from downloads page)

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
This seems to be a limitation of the Polyglot.js, the library used for translation. You can see that looks like it always consider the first pluralization group for Chinese languages:

https://github.com/airbnb/polyglot.js/blob/master/index.js#L60

I suggest opening a ticket with that library, if you feel this is wrong (sorry, but I don't speak Chinese).

**Comment by SoSolife** [comment]
Oh, I see. it shows correct that I just try French which writes in Line 62. Not just Chinese, Japanese and Thai also show incorrect.

**Comment by SoSolife** [comment]
> This seems to be a limitation of the Polyglot.js, the library used for translation. You can see that looks like it always consider the first pluralization group for Chinese languages:
> 
> https://github.com/airbnb/polyglot.js/blob/master/index.js#L60
> 
> I suggest opening a ticket with that library, if you feel this is wrong (sorry, but I don't speak Chinese).
The author of the dependency library insists that there is no need to distinguish between singular and plural in the output format, so the only solution is to modify the Chinese translation file, not to choose branches, and to keep only one template.

**Comment by deluan** [comment]
Yeah, I see... Well, we can keep one "branch" for now, and revisit it if they change idea.

**Comment by ljharb** [comment]
To be clear, I'm not insisting, I'm just trying to understand the use case. If the language itself doesn't differentiate between single and plural, why would the UI need to?

**Comment by SoSolife** [comment]
> To be clear, I'm not insisting, I'm just trying to understand the use case. If the language itself doesn't differentiate between single and plural, why would the UI need to?

The point is that if it can distinguish, it can enable more customized content to be created like `Delete %{name} |||| Delete %{smart_count} %{name}` instead of focusing on field smart_count. In Chinese it just deals with `删除 %{smart_count} 项 %{name}` but I assume that it can deals with `删除 %{name} ||||  删除 %{smart_count} 项 %{name}` like English version's form. The value of reutun just provides different ways to make translation which the condition is if plural.

It's easier to modify specific translation file to just concisely show meanings than the library which has manys of black boxs to use. I realize your thoughts through the communication of these days.
