### ISSUE TITLE
[Bug]: Scrobble with earlier time shouldn't override last play date

### ISSUE THREAD

**Issue by upsuper** [navidrome/navidrome#2262]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3

### Current Behavior

When using Subsonic API to scrobble with a time, that time is always saved as last played time, even if it's earlier than the existing last played time. 

### Expected Behavior

The last played time should only be updated if the time is later.

### Environment

```markdown
(I'm using my own cli program to test the API behavior.)
```

### How Navidrome is installed?

Binary (from downloads page)

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
Thanks for the PR, but I'm pondering if this is the correct behaviour in this case. Scrobbles should not be sent out of order from the client. From [Last.fm docs](https://www.last.fm/api/scrobbling):

> Scrobbles should be sent in order, therefore cached scrobbles should be sent before new scrobbles. 

Not sure if we should just ignore the out-of-order scrobble, instead of incrementing the playCount. What are you trying to achieve in your program?

**Comment by upsuper** [comment]
I want to increase the play count without touching the last play count in some cases.

Also I have my server offline most of the time, so different clients may sync with it out of order among them.

**Comment by deluan** [comment]
> I want to increase the play count without touching the last play count in some cases.

Is this for scripting? If so, we may try to find a different solution for that.

> Also I have my server offline most of the time, 

Clients are expected to send scrobbles in order as well, or they wont be counted in Last.fm. Have you seen any client sending scrobbles out-of-order?

**Comment by upsuper** [comment]
> Clients are expected to send scrobbles in order as well, or they wont be counted in Last.fm. Have you seen any client sending scrobbles out-of-order?

It's not that a client sends them out of order, but two clients may send them in conflict. For example,
* I play a song on my mobile at 12am when the server is offline,
* on 9am I play the same song on the computer with the server (on the computer) online,
* on 10am the mobile client finds that the server is online so it tries to send the scrobble request.

At this point, I would expect the last play be 9am not 12am which is sent by mobile at 10am.

**Comment by deluan** [comment]
Yeah, never had this situation myself, but makes sense. Let's use your PR, but in this case externals services could get out of sync with your local playCounts. Can;t think of any better solution :/

**Comment by upsuper** [comment]
I can't think of a better solution either. I think last.fm should think about this case as well because we can't expect all clients to be online all the time.

(But I don't use last.fm so I don't care to be honest ;)

**Comment by upsuper** [comment]
> in this case externals services could get out of sync with your local playCounts.

By the way, I don't think the PR makes it worse. Previously the local play count is updated as well, and if external services would be rejecting out-of-order scrobble, they would have already been rejecting it.
