### ISSUE TITLE
Columns To Display - inconsistent menu order

### ISSUE THREAD

**Issue by bbsixzz** [navidrome/navidrome#2278]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3 (8b93962f)

### Current Behavior

I was looking for the Year column for my playlists but couldn't find it. 

Then I noticed the inconsistent menu order for Songs/Playlists/Albums.

Songs----------------------------------------Playlists------------------------------Albums
![songs](https://user-images.githubusercontent.com/47334163/227813139-f5179d08-49f7-4ce4-9b41-abc21301bf46.png)![playlist](https://user-images.githubusercontent.com/47334163/227813163-efc4e33c-786f-47a8-9c6e-c1e31ad5affc.png)![albums](https://user-images.githubusercontent.com/47334163/227813114-8eddc3b8-fe15-4ead-937e-677cc37e87f9.png)

The # Column in Songs doesn't even show/seem to do anything, at least on my 1080p display.

### Expected Behavior

Year column availability in playlists.

[Edit] I found it. The menu is actually scrollable but no affordances are given.

Consider expanding the menu to show all options and have them sorted consistently.

### Environment

```markdown
- OS: Debian GNU/Linux 11 (bullseye)
- Browser: Safari Version 16.3 (18614.4.6.1.6)
- Client: WebUI
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
I'll add `Year` to the PlaylistSongs view column options.

The order is inconsistent because, as the columns can't be reordered, I put them in the order that makes more sense to be displayed in the each view, IMHO. This will change when upgrading to React-Admin 4, which supports [column reordering](https://marmelab.com/react-admin/SelectColumnsButton.html):

![SelectColumnsButton](https://user-images.githubusercontent.com/331353/228087170-34c1cf03-28c0-417c-8be1-c5791869fa09.gif)

**Comment by bbsixzz** [comment]
> Actually, `Year` is already there, you need to scroll down to see more options:

Yes I made a comment above it under Expected Behavior:

> [Edit] I found it. The menu is actually scrollable but no affordances are given.
> Consider expanding the menu to show all options and have them sorted consistently.

 I guess we both fell for the same trick :]

React-Admin 4 looks amazing and appears to fix all these issues.

Many thanks again for your excellent work.
