### ISSUE TITLE
[Bug]: Right-to-left support is missing

### ISSUE THREAD

**Issue by zayedalsaidi** [navidrome/navidrome#2280]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3-SNAPSHOT (9a508f2c)

### Current Behavior

After changing the language to Arabic or Farsi, the web page will not update to be in right-to-left direction. 

### Expected Behavior

After change the language to Arabic or Farsi, the interface should be in right-to-left direction.  The <body>tag should have direction: rtl property.

### Environment

```markdown
- OS:Windows 10
- Browser: Firefox
- Client:NavidromeUI [Firefox/Windows]
```

### How Navidrome is installed?

Binary (from downloads page)

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
This won't change in the current UI version, but I'll try to enable it in the next version (using React Admin v4). I know Arabic should be RTL, but is it a blocker for releasing the translation?

**Comment by zayedalsaidi** [comment]
No, it's not a blocker. Please release the translation as soonest 😀

في الاثنين، ٣ أبريل ٢٠٢٣, ٣:٠٥ ص Deluan Quintão ***@***.***>
كتب:
