### ISSUE TITLE
[Bug]: Incomplete song query

### ISSUE THREAD

**Issue by fightroad** [navidrome/navidrome#2286]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3

### Current Behavior

I upload a lot of dj songs. In the song interface, I searched through dj, but not all of them were found. incomplete search

### Expected Behavior

search complete

### Environment

```markdown
- OS:
- Browser:
- Client:
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by metalheim** [comment]
Are your files tagged correctly with a title and artist? 
What kind of files (mp3/aac/wav etc.) are these?

**Comment by fightroad** [comment]
I turned on the variable ND_SEARCHFULLSTRING, it seems that I can search all, my song information is in Chinese
