### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by psmoros** [navidrome/navidrome#2290]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@thewhiteevil) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by deluan** [comment]
Thanks for reaching out. I'll add a SECURITY.md later today, but you can report security issues using the specific option when opening an issue:
<img width="1450" alt="Screenshot 2023-04-01 at 10 52 38 AM" src="https://user-images.githubusercontent.com/331353/229296531-0b1d9590-ef16-4978-a9bf-e3e478dc5b9e.png">

**Comment by psmoros** [comment]
It's weird I don't see this option on my end... Besides won't this be public?

**Comment by deluan** [comment]
Humm... I never used that option, so maybe it is misconfigured. But not, it won't be public. Anyway, while I don't fix it, you can send the information to security @ navidrome.org

Thanks

**Comment by psmoros** [comment]
Ok thank you :)

**Comment by deluan** [comment]
The _Report a security vulnerability_ option is now enabled, if you prefer to use it.

**Comment by deluan** [comment]
@psmoros Any news on this?

**Comment by Thewhiteevil** [comment]
I had sent the report to security @ navidrome.org 4 days before.

**Comment by deluan** [comment]
I didn't receive anything.... Can you try forwarding it to deluan @ navidrome.org? Or better yet, using the _Report a security vulnerability_ option in GH.

**Comment by psmoros** [comment]
sent! Sorry for the delay
