### ISSUE TITLE
Cover animation settings in shared link

### ISSUE THREAD

**Issue by cproensa** [navidrome/navidrome#2301]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3

### Current Behavior

While testing the new Shared links feature, i've noticed that the landing page, with the player for the shared link, shows the cover rotating, even thoguh i have disabled that feature with `ND_ENABLECOVERANIMATION: false`

### Expected Behavior

ND_ENABLECOVERANIMATION should be honored in the "shared link" player page

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
The player used in the Share uses all the default configuration, without any tweaking we had to apply to the main UI interface.

I may take a look at integrating them into one, but I don't want to spend too much time with this player anymore, I'd like to spend effort in creating a new one: #2285
