### ISSUE TITLE
Strange UI responsiveness on zoom-out

### ISSUE THREAD

**Issue by ElleshaHackett** [navidrome/navidrome#232]
When zooming out (ctrl-) in the Album Grid view, the whole GUI zooms except the images (at least not properly). At least when going back from 100% to 25%. The images should be responsive too. Can we use % and scaling instead of static image sizes? 

Also with my 1920x1080 resolution in Windows with a default 125% Zoom in Windows, the GUI is just too high and falls behind the play bar. I think we should make it a bit more responsive to work better in different resolutions and settings.

**Comment by deluan** [comment]
Yeah, I have to spent more time with the responsiveness edge cases. I'm validating it for desktop, tablet and mobile, but only with fixed dimenisions

**Comment by ElleshaHackett** [comment]
"only with fixed dimenisions" as in adaptive instead of responsive?

**Comment by deluan** [comment]
This requires a new cover grid, and will be taken into consideration when(if) developing it
