### ISSUE TITLE
Volume normalization (in web player)

### ISSUE THREAD

**Issue by JaneX8** [navidrome/navidrome#233]
Volume is usually a big problem in libraries. When volume is normalized tools like MP3Gain and I believe also replaygain add information to the ID3 tag without touching the data itself. So just analyzing the volume and adding metadata. I think we should have a setting to enable support for that at least in the webplayer. I don't know exactly what tags are used for that but I suggest that we research that and use that information.

I have some ideas on the implementation (and I have no idea if it's a common implementation like this, just came to my mind).

Lets say we have three songs with different volume levels:
- Song A: 25
- Song B: 50
- Song C: 75

Assuming the normal level should be 50, you'd expect Song A to have a metadata tag saying +25 and song C having a tag saying -25.

Now I suggest we introduce two volume levels in the Web Player. One Hidden and one Shown. The Shown one is simply for the user to control the output volume from 0-100%.

The hidden one can be used for the volume correction according to the metadata tag. So when our hidden volume is 50, we can use the tag to add or remove 25 from the baseline volume depending on the metadata tag but it won't affect the volume setting of the users 0-100% which is just an overall volume control.

_Regarding streaming capabilities to other devices and when other apps are used over the Airsonic API, I have no solution to fix this yet without actually changing the data (during transcoding)._

**Comment by deluan** [comment]
I think this is a matter of exposing the replaygain tags to the player, and each player has to handle it individually.

For Navidrome's own player, this would have to be handled by the upstream project, https://github.com/lijinke666/react-music-player. Not sure if this is actually possible to do with the browser's HTML5 mediaplayer.

Will keep this open and may come back to it later, but I'd argue that more important than volume normalization is [gapless playback](https://github.com/lijinke666/react-music-player/issues/81)

**Comment by ElleshaHackett** [comment]
Gapless playing should definitely be a feature to keep on the backlog. If the upstream player doesn't want to introduce it we should maybe search for alternatives using browser tech that does support it. You could also then make a setting which player to use (preferably not).

Regarding normalization, yes exposing the tags to the player is a start. I will research later if the upstream project has this feature requested or is working on it, or if other options are available. I would also want to keep this on the backlog.

**Comment by andrewzah** [comment]
@deluan I opened a [feature request](https://github.com/lijinke666/react-music-player/issues/135) but the author stated if this functionality is desired, we should submit a PR.

**Comment by deluan** [comment]
Yeah, I saw that.... Well, I don't have too much time either ATM, but may come back to this and try to contribute back to his project.

**Comment by andrewzah** [comment]
Do you think [something like this example](https://github.com/est31/js-audio-normalizer/blob/master/normalizer/normalizer.html#L27) based on [ReplayGain](http://wiki.hydrogenaud.io/index.php?title=ReplayGain_1.0_specification#Gain_calculation) could work entirely in the frontend? That way it wouldn't be reliant on replaygain tags existing.

**Comment by deluan** [comment]
Not sure. When I'm ready to work on this, I'll take a look at the options and ask feedback here

**Comment by rochakjain361** [comment]
I would love to work on this issue for this edition of GSOC! Can't wait to get to know more about the project and community!

**Comment by abhinavmaharana** [comment]
I would love to work on this issue for this edition of GSOC! Can't wait to get to know more about the project and community!

**Comment by ishtiaqSamdani** [comment]
I have just completed my exams, so I am late 
can I still contribute to this cause  I  am really interested in it
I have an idea that we can add it to the Alexa problem too
mentor I hope you will guide me on this :)

**Comment by swayamg20** [comment]
Is this issue still open? I was reading about this issue and I think I can solve this issue, can you help me on that please.

**Comment by JaneX8** [comment]
This issue shouldn't be closed. Even if dependency is unmaintained. As @andrewzah pointed out, possible other solutions (in frontend) for volume normalization could work.

**Comment by deluan** [comment]
This issue was closed because a solution was implemented in #1988, and was already merged.
