### ISSUE TITLE
[Bug]: Long-names of tracks deforming the view

### ISSUE THREAD

**Issue by soyelmismo** [navidrome/navidrome#2332]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3 (8b93962f)

### Current Behavior

normal size of view with an album with normal track names:
![Captura de pantalla de 2023-04-27 10-15-56](https://user-images.githubusercontent.com/123757457/234908457-cee809fc-099c-4fd7-8ddf-95e31ee25bd4.png)

normal size of view with an album with a long-named track (cant view the track menu options unless you go to the right or zoom out:
![Captura de pantalla de 2023-04-27 10-15-47](https://user-images.githubusercontent.com/123757457/234908621-2abe4222-30ed-4da7-a2be-2e2d8bda7745.png)

### Expected Behavior

screenshot with zoom out expecting the normal behaviour but for big screens, not optimal for tiny screens like mine
![Captura de pantalla de 2023-04-27 10-17-03](https://user-images.githubusercontent.com/123757457/234908841-004465dd-dbb1-4b66-acbf-ea5b5139a2aa.png)

the track names should have 3 dots at the end or something like that which let you know that the name is longer but - its shortened - to avoid dimension problems

idk. i can zoom in in other normal albums and its just using multi line view for track names except for that weird track and if you zoom a lot you loose the track menu options

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
This was already discussed in #240. As I'm rewriting the UI with the new React-Admin version 4, I'll see if this can be accommodated. Will keep this open for now.
