### ISSUE TITLE
UI improvement for Album page

### ISSUE THREAD

**Issue by ElleshaHackett** [navidrome/navidrome#236]
When the Album page is open it would be great if you could click on the Artist name to see all Albums of that artist.

**Comment by deluan** [comment]
You mean the Album Artist or the individual artists of each track? Right now you can click on the Album Artist. Track artists are not possible right now, as they are not in the DB and if you have an artist that only appears in a compilation, it would cause an exception if clicked

**Comment by ElleshaHackett** [comment]
I meant: Track artists on the Album page. I'm aware that would require a tremendous data standardization part.

**Comment by deluan** [comment]
For track artists, this will be possible once #211 is in place.

**Comment by deluan** [comment]
This will be tackled in #211
