### ISSUE TITLE
[Bug]: missing error message when playing unsupported formats (WMA)

### ISSUE THREAD

**Issue by sebastianschauenburg** [navidrome/navidrome#2393]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [ ] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3 (8b93962f)

### Current Behavior

When an album is added, containing .wma files, it works. But trying to play it, it just hangs. I assumed something serious was wrong, until I saw the fileformat and went 'duh'. But because the album was added successfully and could be selected to play, I assumed I would be able to play / use it.

P.S. I tested with both the browser and a subsonic android client.

### Expected Behavior

An error message telling the user that the file format is not supported (or anything like that).

### Steps To Reproduce

1. Add a WMA file to your music collection
2. Try to play the WMA file

### Environment

```markdown
- OS: Debian 11.7
- Browser: Mozilla Firefox
- Client: Ultrasonic
```

### How Navidrome is installed?

Docker

### Anything else?

A bit related to this report where they ask for [WMA support](https://github.com/navidrome/navidrome/issues/1592), but not supporting WMA and just showing an error would suffice for me to be honest. Transcoding WMA to another (supported) format is trivial

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by dweymouth** [comment]
To be clear, WMA is supported by the server, i.e. the scanner will read the tags just fine, add it to the DB, and the transcoding engine can convert it to another format such as opus. The web UI won't support playing WMA without transcoding, or any other codec that's not supported natively by the browser it's running in. Some Subsonic clients, such as [Supersonic](https://github.com/dweymouth/supersonic) should be able to play WMA directly but for the web UI and other clients that don't play WMA, you will likely want to set up transcoding.

**Comment by sebastianschauenburg** [comment]
Thanks for that addition!
I haven't specifically enabled transcoding, because it will negatively impact performance (personal choice). Good to know that it technically should/could work (and the situations in which it does not work).
Feel free to close this "bug". Or perhaps I'll write a few lines of documentation for this (hope you won't mind if I borrow your content @dweymouth ) ;-)
