### ISSUE TITLE
UI improvements on table columns/rows

### ISSUE THREAD

**Issue by JaneX8** [navidrome/navidrome#240]
When long values are shown in the tables of the different library pages the table tends to look weird as the column width tends to change, even when browsing through the lists.

I would suggest to (at least) give each column a static width % to make it very stable or at least a max-width % (less favorable because then still the column sizes will change when browsing). And then there are two options regarding content that is too long (that would be cool if its made configurable per user):

1. Wrapping text with break-word (meaning your rows can vary in height)
2. Wrapping text without break-word (meaning your rows are the same height and not everything is visible when it's too long). This is what Spotify does and it makes the GUI look very clean, calm and aesthetic.

I personally would prefer that last option. You could see the full name by hovering over it and the name shown could be cut off like `Some long name featuring artist be...`.

**Comment by deluan** [comment]
I'd love to do that, and already spent some time trying to implement it, but not enough to make it work :)

The current behaviour is the default for ReactAdmin, and every "deep" change like this one has to be well thought, as it will be basically implemented by copying RA code into Navidrome's codebase and customizing it, which could make it incompatible with future RA releases

**Comment by JaneX8** [comment]
It should be reopened.

**Comment by deluan** [comment]
I may take a look on this again while rewriting the UI in ReactAdmin 4
