### ISSUE TITLE
[Bug]: no required module provides package github.com/ReneKroon/ttlcache/v2

### ISSUE THREAD

**Issue by yonas** [navidrome/navidrome#2400]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

f5d9782

### Current Behavior

The build fails with:

```
utils/cached_http_client.go:13:2: no required module provides package github.com/ReneKroon/ttlcache/v2; to add it:
        go get github.com/ReneKroon/ttlcache/v2
```
```
$ go get github.com/ReneKroon/ttlcache/v2
go: github.com/ReneKroon/ttlcache/v2@v2.11.1: parsing go.mod:
        module declares its path as: github.com/jellydator/ttlcache/v2
                but was required as: github.com/ReneKroon/ttlcache/v2
```

### Expected Behavior

No errors.

### Steps To Reproduce

1. git clone https://github.com/navidrome/navidrome
2. cd navidrome
3. gmake setup
4. gmake buildall

### Environment

```markdown
- OS: FreeBSD 13.2
- Browser: N/A
- Client: N/A
```

### How Navidrome is installed?

Built from sources

### Configuration

```toml
N/A
```

### Relevant log output

```shell
$ gmake setup
...
$ gmake buildall
...
WARNING: This command does not build the frontend, it uses the latest built with 'make buildjs'
go build -ldflags="-X github.com/navidrome/navidrome/consts.gitSha=f5d9782 -X github.com/navidrome/navidrome/consts.gitTag=v0.48.0-SNAPSHOT" -tags=netgo
utils/cached_http_client.go:13:2: no required module provides package github.com/ReneKroon/ttlcache/v2; to add it:
        go get github.com/ReneKroon/ttlcache/v2
gmake: *** [Makefile:79: build] Error 1
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
Looks like the issue is that the upstream library author renamed their GitHub user from `ReneKroon` to `jellydator`. I'll try to migrate to version v3, using the new name, which would resolve the issue.

In the meantime you can try:
- Playing with the `GOPROXY` env var.
- Specifying the same version as the project uses when running `go get`: 
```
go get github.com/ReneKroon/ttlcache/v2@v2.11.0
```

**Comment by yonas** [comment]
@deluan Thanks, that worked. :tada: 

I've created a new bug for another compiling error: #2403
