### ISSUE TITLE
[Bug]: React test formatFullDate fails as it is locale specific

### ISSUE THREAD

**Issue by phw** [navidrome/navidrome#2402]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

Latest git commit

### Current Behavior

The test `formatFullDate` in `src/utils/formatters.test.js` is failing on locales other then English, as the date formatting is locale dependent. Below is the test failing with German locale:

```
> react-scripts test --watchAll=false

 FAIL  src/utils/formatters.test.js
  ● formatFullDate › format bytes

    expect(received).toEqual(expected) // deep equality

    Expected: "Jun 2011"
    Received: "Juni 2011"

      43 |   it('format bytes', () => {
      44 |     expect(formatFullDate('2011')).toEqual('2011')
    > 45 |     expect(formatFullDate('2011-06')).toEqual('Jun 2011')
         |                                       ^
      46 |     expect(formatFullDate('1985-01-01')).toEqual('Jan 1, 1985')
      47 |     expect(formatFullDate('199704')).toEqual('')
      48 |   })

      at Object.<anonymous> (src/utils/formatters.test.js:45:39)

```

### Expected Behavior

Tests pass independent of locale. Probably locale should be set specifically for the test to English or C

### Steps To Reproduce

    LC_ALL=fr make pre-push

to fix failing tests if you are running a foreign locale:

    LC_ALL=C make pre-push

### Environment

```markdown
- OS: Ubuntu 23.04
```

### How Navidrome is installed?

Built from sources

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
Thanks for catching this. I added this piece of code to the tests, hoping it would avoid this:
```
  beforeAll(() => {
    const toLocaleString = Date.prototype.toLocaleString
    // eslint-disable-next-line no-extend-native
    Date.prototype.toLocaleString = function (locale = 'en-US', ...args) {
      return toLocaleString.call(this, locale, ...args)
    }
  })
``` 

but looks like it didn't. I'll take al look.
