### ISSUE TITLE
FreeBSD: utils/cache/file_caches.go:222:41: cannot use fs (variable of type *spreadFS) as fscache.FileSystem value in argument to fscache.NewCacheWithHaunter: *spreadFS does not implement fscache.FileSystem (wrong type for method Create)

### ISSUE THREAD

**Issue by yonas** [navidrome/navidrome#2403]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

f5d9782

### Current Behavior

Running `gmake build` fails.

### Expected Behavior

Compiling should not fail.

### Steps To Reproduce

git clone https://github.com/navidrome/navidrome
cd navidrome
gmake setup
gmake buildall

### Environment

```markdown
- OS: FreeBSD 13.2
- Browser: N/A
- Client: N/A
```

### How Navidrome is installed?

Built from sources

### Relevant log output

```shell
WARNING: This command does not build the frontend, it uses the latest built with 'make buildjs'
go build -ldflags="-X github.com/navidrome/navidrome/consts.gitSha=f5d9782 -X github.com/navidrome/navidrome/consts.gitTag=v0.48.0-SNAPSHOT" -tags=netgo
# github.com/navidrome/navidrome/utils/cache
utils/cache/file_caches.go:222:41: cannot use fs (variable of type *spreadFS) as fscache.FileSystem value in argument to fscache.NewCacheWithHaunter: *spreadFS does not implement fscache.FileSystem (wrong type for method Create)
                have Create(string) ("github.com/djherbis/stream".File, error)
                want Create(string) ("gopkg.in/djherbis/stream.v1".File, error)
utils/cache/file_caches.go:227:5: ck.SetKeyMapper undefined (type *fscache.FSCache has no field or method SetKeyMapper)
gmake: *** [Makefile:79: build] Error 1
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
This seems to be the same problem as before: Dependencies not properly cached. My suggestion is to take a look at the [GOPROXY](https://jfrog.com/blog/why-goproxy-matters-and-which-to-pick/) config variable.

For other FreeBSD related issues, please post it as a [discussion](https://github.com/navidrome/navidrome/discussions/categories/q-a). FreeBSD is not officially supported and this is not a "bug" in Navidrome, it is an issue with building it on an unsupported OS.
