### ISSUE TITLE
Disable autocomplete on login screen (privacy/security)

### ISSUE THREAD

**Issue by ElleshaHackett** [navidrome/navidrome#241]
Please disable autocomplete on the login screen with `autocomplete="off"`. Might the application be vulnerable to cross-site scripting (XSS) than it should be way harder to grab the saved usernames/passwords.

Also, on shared computers (in case Navidrome would be exposed to the internet) you don't want the login history to appear, leaking out previously used usernames.

As with all options, if you choose not the secure/privacy-by-default option than make it configurable on the settings page :) maybe under a privacy/security section.

**Comment by deluan** [comment]
This is a browser "feature", and I could not find a way to disable it. `autocomplete=off` (or `autoComplete) seems to be ignored.

**Comment by ElleshaHackett** [comment]
Here is an example: https://rsolomakhin.github.io/autofill/.

1. Type something in "Basic form key/value Autocomplete (unstructured data)" click submit, go back. Try to type the first letter of what you just typed. Autocomplete pops up.
2. Then try the same for "Basic form key/value Autocomplete (autocomplete="off")"

**Comment by Sohalt** [comment]
I don't think this is actually useful.
Chrome (https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/zhhj7hCip5c), Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=956906), and Safari (https://lists.w3.org/Archives/Public/public-webapps/2013OctDec/1028.html) ignore the `autocomplete=off` setting for password fields, to allow password managers to fill in saved passwords.
If you have an XSS vulnerability, you can execute arbitrary JS on the client and this won't make any difference.

**Comment by deluan** [comment]
> I don't think this is actually useful.
> Chrome (https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/zhhj7hCip5c), Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=956906), and Safari (https://lists.w3.org/Archives/Public/public-webapps/2013OctDec/1028.html) ignore the `autocomplete=off` setting for password fields, to allow password managers to fill in saved passwords.

Yeah, that's what I also found out. I think this issue is "non-solvable". Any additional thoughts, @ElleshaHackett ?

**Comment by rochakjain361** [comment]
I think in the newer releases of Material UI, this issue is fixed, and now on applying `autoComplete = off` to the username field on the login page, the autocomplete feature is disabled simply. 
Before disabling autocomplete:

![Screenshot from 2021-03-17 02-38-20](https://user-images.githubusercontent.com/57208018/111380070-e563bf00-86c9-11eb-8aa1-1d7b3df123e9.png)

After:

![Screenshot from 2021-03-17 02-38-38](https://user-images.githubusercontent.com/57208018/111380094-ea287300-86c9-11eb-98c6-b4059df795fe.png)

**Comment by deluan** [comment]
I actually don't think this behaviour should change.... As @Sohalt pointed out, this would get into the way of Password Managers. Any thoughts, @jvoisin?

**Comment by jvoisin** [comment]
Yeah, no need to change the behaviour.
