### ISSUE TITLE
[Bug]: Playlist Sorting by title and album title sorts by capitlization 

### ISSUE THREAD

**Issue by g1gabyt3333** [navidrome/navidrome#2425]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3

### Current Behavior

![image](https://github.com/navidrome/navidrome/assets/63312367/b45c8b86-f628-4ea4-8caf-5ff41a314b1e)
After all songs with a capital letter are alphabetically sorted then songs with a lower case letter are sorted alphabetically. This same behavior also happens when sorting by album title as well.

### Expected Behavior

What should happen is titles should sort regardless of case sensitivity. For example it should be AaBbCc instead of the current ABCabc sorting. 

### Steps To Reproduce

Sort playlist by either title or album title.

### Environment

```markdown
- OS: Ubuntu 22.04.2
- Client: Navidrome WebUI
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by picklepopper1** [comment]
I don’t know if it’s helpful to know, or if the fix is global, but radio stations have the same issue.

**Comment by certuna** [comment]
> I see the issue. I was able to reproduce it. I want to work on this issue. Assign this issue to me. I will be working on the issue

If you write a patch to fix it you can submit it as a PR, no "assigning" needed I think?

**Comment by Alestrix** [comment]
Has this been worked on? Issue still present.

**Comment by breakfast-first** [comment]
I also had this issue with artist sorting until I turned on PreferSortTags. Now I can use the Artist Sort tag to properly sort them, but trying the same method with album sorting did not work. I would like to have case-insensitive sorting globally.

**Comment by Dylancyclone** [comment]
Still an issue in 0.51.1
In the album view it is very weird to have an album starting with a capital "Z" sort before an album starting with a lowercase "a". Unfortunately `PreferSortTags` doesn't seem to help

**Comment by deluan** [comment]
The PR #2993 should fix all cases described in this issue. Please let me know if it works and if if it causes any other issues. This develop build should be safe to try if you are using version 0.52.0.

**Comment by deluan** [comment]
Was anyone able to test PR #2993?

**Comment by Dylancyclone** [comment]
[v0.52.5](https://github.com/navidrome/navidrome/releases/tag/v0.52.5) fixed this for me, I just had to do a full library scan first in case anyone else is having issues
