### ISSUE TITLE
[Bug]: Radio page loop

### ISSUE THREAD

**Issue by BobHasNoSoul** [navidrome/navidrome#2443]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

latest docker stable

### Current Behavior

when a admin has added a lot of radio stations to the radio page and then a user opens the radio page they can only see the first page and when clicking next page it loops back to the 1st. 

the stations are definatley there and can be seen in part by increasing the page items.

### Expected Behavior

to go to the next page of radio stations

### Steps To Reproduce

1. add radio stations more than the page usually holds for me my personal list is 40 long
2. get a user to login and go to the radio page
3. get the user to click for the next page of radios to be listed, it will never list just reloads and loops the first page.

### Environment

```markdown
- OS: Docker (ubuntu)
- Browser: chrome and firefox
- Client: navidrome web ui
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

UPDATE:
Workaround for now if you have less than 50 stations, use the sort option on the name with page items set to 25 to get the first 25 and last 25.  This appears to be a bug within the web ui itself rather than the implementation in the server.

**Comment by picklepopper1** [comment]
I can confirm this is also an issue for me. It’s definitely the web UI that’s the issue.

**Comment by picklepopper1** [comment]
Bumping. Still an issue in current release
