### ISSUE TITLE
[Bug]: Mount two MUSIC folders in docker

### ISSUE THREAD

**Issue by Vendo232** [navidrome/navidrome#2453]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3 (8b93962f)

### Current Behavior

Would like to mount 2 folders with music files using docker.

    volumes:
      - /home/server/navidrome:/data
      - /mnt/media/music:/music:ro
      - /mnt/plexshare/music:/music2:ro

Is it possible, Navidrome is not picking up songs from music2 folder. 

### Expected Behavior

add secound music folder in docker compose

    volumes:
      - /home/server/navidrome:/data
      - /mnt/media/music:/music:ro
      - /mnt/plexshare/music:/music2:ro

### Environment

```markdown
- OS:
- Browser:
- Client:
```

### How Navidrome is installed?

Docker

### Configuration

```toml
volumes:
      - /home/server/navidrome:/data
      - /mnt/media/music:/music:ro
      - /mnt/plexshare/music:/music2:ro
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by metalheim** [comment]
Not really a bug, navidrome can only understand one music directory (which is /music by default for docker installation).

You could just mount the second directory in /music and navidrome will see it:

```
volumes:
  - /home/server/navidrome:/data
  - /mnt/media/music:/music:ro
  - /mnt/plexshare/music:/music/plexshare:ro
```

**Comment by Vendo232** [comment]
thank you sir for quick response. the /music/plexshare:ro did not work, docker won`t start

error msg:
failed to deploy a stack: Container navidrome-navidrome-1 Recreate Container navidrome-navidrome-1 Recreated Container navidrome-navidrome-1 Starting Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/mnt/plexshare/music" to rootfs at "/music/plexshare": mkdir /var/lib/docker/overlay2/a6b736ea5412ad31653163b1f9f9dd44ede41e59af6734ce93a934e4fb68bc98/merged/music/plexshare: read-only file system: unknown

**Comment by kgarner7** [comment]
You can accomplish this by having both volumes as subdirectories of `/music`
```yaml
    volumes:
      - "/mnt/media/music:/music/1:ro"
      - "/mnt/plexshare/music:/music/2:ro"
```

**Comment by antonsizikov** [comment]
> im wondering if you need to create the folder locally first before mounting the
/music/plexshares

For me it works to delete container and recreate it again with two mounting points with subdirectories.

**Comment by kimsonvu** [comment]
> You can accomplish this by having both volumes as subdirectories of `/music`
> 
> ```yaml
>     volumes:
>       - "/mnt/media/music:/music/1:ro"
>       - "/mnt/plexshare/music:/music/2:ro"
> ```

This work for me. 1000 Thanks!

**Comment by Szeraax** [comment]
I do the same approach with mounting multiple folders. Works great in all cases as far as I'm aware. Closing
