### ISSUE TITLE
Expose playing details using API and enable use of Webhooks

### ISSUE THREAD

**Issue by JaneX8** [navidrome/navidrome#246]
For the intergration with home assistant (home-assistant.io). I would love to be able to ask the Navidrome API:
- Is someone playing something (or is it paused or idle) and what playing position (tracks in queue and position and playing position in current track)?
- How many total songs, artists and albums are present?

Above method would require a pull. A push would be even better. I would love to see optional/configurable webhooks on a "play", "pause", "stop", "idle" action. Which could be as simple as sending a HTTP GET request to a given URL. That way Navidrome could function as a Trigger in Home Assistant and other tools and easily make cool stuff available like "turn the lights off if Navidrome starts playing", "pause the vacuum cleaner when Navidrome starts playing", "play my favorite playlist when I get home".

_Getting the playing position is helpful for automation like "fade on the lights slowly when the last song in the queue is playing the last 20 seconds"_.

**Comment by tcurdt** [comment]
Would be cool to have.
But this would probably need some kind of event queue for webhooks?
Not sure how the LastFM scrobbling was implemented - but I see an overlap.

**Comment by deluan** [comment]
Thanks for the suggestion.

> For the intergration with home assistant (home-assistant.io). I would love to be able to ask the Navidrome API:
> 
> * Is someone playing something (or is it paused or idle) and what playing position (tracks in queue and position and playing position in current track)?

Exact position is not possible, as the server does not have control over the clients' playback. The best that can be done is already available in the [`getNowPlaying` endpoint](http://subsonic.org/pages/api.jsp#getNowPlaying)

> * How many total songs, artists and albums are present?

This will most probably be implemented as part of the Subsonic extensions, a joint effort among Subsonic server and clients developers.

> 
> Above method would require a pull. A push would be even better. I would love to see optional/configurable webhooks on a "play", "pause", "stop", "idle" action. Which could be as simple as sending a HTTP GET request to a given URL. That way Navidrome could function as a Trigger in Home Assistant and other tools and easily make cool stuff available like "turn the lights off if Navidrome starts playing", "pause the vacuum cleaner when Navidrome starts playing", "play my favorite playlist when I get home".

Push of scrobblres and nowplaying is being implemented as a webhook. See #2229 

> 
> _Getting the playing position is helpful for automation like "fade on the lights slowly when the last song in the queue is playing the last 20 seconds"_.

As I said above, this level of detail is not possible. The best you can get is how long ago a track started playing, and hope the client did not pause the song.

This issue will be closed once #2229 is merged.

@tcurdt See #2229 :)
