### ISSUE TITLE
[Bug]: WAV format music tags do not display Chinese properly

### ISSUE THREAD

**Issue by genesis-lua** [navidrome/navidrome#2468]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3 (8b93962f)

### Current Behavior

When I tagged the music in WAV format, I found that the Chinese could not be displayed normally after scanning, while the music in other formats could be displayed normally, so I was very troubled. At the same time, I sorted out the English songs in WAV format in the music library and found that they could display tags normally. Can fix tag support Chinese WAV format?
![image](https://github.com/navidrome/navidrome/assets/26401920/3773bd3a-616f-4f79-8adb-b4fe591794af)

### Expected Behavior

I hope that songs Chinese WAV format can display tag metadata normally

### Environment

```markdown
- OS:
- Browser:
- Client:
```

### How Navidrome is installed?

Docker

### Configuration

```toml
docker run
  -d
  --name='Navidrome'
  --net='host'
  -e TZ="Asia/Shanghai"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Genesis-server"
  -e HOST_CONTAINERNAME="Navidrome"
  -e 'TCP_PORT_4533'='4533'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'ND_ENABLETRANSCODINGCONFIG'='true'
  -e 'ND_TRANSCODINGCACHESIZE'='1000MB'
  -e 'ND_SCANNER_EXTRACTOR'='ffmpeg'
  -e 'ND_DEFAULTLANGUAGE'='zh-Hans'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/xushier/HD-Icons/master/border-radius/Navidrome_B.png'
  -v '/mnt/remotes/192.168.50.168_gene-nas/Media/Music/':'/music':'ro'
  -v '/mnt/user/appdata/docker/navidrome/data':'/data':'rw' 'deluan/navidrome:latest'
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by metalheim** [comment]
WAV as a format isn't great for tag support in general as different taggers do it differently.
Some taggers apply id3 tags to wav files, some do the "proper" thing and add tags to the LIST / INFO chunk of WAV files.

Here some background to WAV tagging:
https://www.robotplanet.dk/audio/wav_meta_data/

Can you please explain how (which application, which tag format) you tagged these files?
You can also try to set the `ND_SCANNER_EXTRACTOR` to "taglib", maybe it helps?

**Comment by phw** [comment]
The issue description sounds like the files might have tags in an `INFO` chunk. But as INFO chunks don't have a way to handle character encoding it gets read wrongly. 

Not sure how Navidrome currently handles this. Probably should guess the encoding, but still this will be hit and miss. WAVE just has poor tagging support.
