### ISSUE TITLE
[Bug]: Server refuses connection from Android and IOS

### ISSUE THREAD

**Issue by tekgamerpt** [navidrome/navidrome#2478]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3

### Current Behavior

Running Navidrome server on Proxmox LXC container.
Everything works like it should until i try to connect from mobile devices (android and ios). Connections are refused using app's like substreamer or even on browser
On PC's using wifi or ethernet, everything is fine
Also im trying to connect by lan using internal ip and 4553 port.
Container does not have firewall

Am i missing something?

Thank you

### Expected Behavior

I should connect normally on all devices

### Environment

```markdown
- OS:
- Browser:
- Client:
```

### How Navidrome is installed?

Built from sources

### Configuration

```toml
Installed on Proxmox 8 using install script
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by sandreas** [comment]
@tekgamerpt @deluan 
I get a 503 if I try to remove items from Playlists in substreamer. Is this the same problem or is this something else?
