### ISSUE TITLE
[Bug]: can't get cover from local file

### ISSUE THREAD

**Issue by cfandora** [navidrome/navidrome#2479]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

docker  tag:develop

### Current Behavior

I forgot to add cover in album folder at first, so it got cover from last.fm.
Now I add the cover, but it still shows the cover from last.fm not local file.
I tried removing the album and then adding and scanning it again, but in the end, it still showed cover from last.fm

### Expected Behavior

Anytime it shows cover from local file first.

### Steps To Reproduce

1. add album without cover
2. it will get cover from last.fm
3. add cover to album folder, it still shows cover from last.fm
4. remove then add and scan album, it still shows cover from last.fm

### Environment

```markdown
- OS: Debian 11
- Browser: Chrome 115.0.5790.171 on Windows 11
- Client: Feishin / 音流
```

### How Navidrome is installed?

Docker

### Configuration

```toml
version: "3"
services:
  navidrome:
    image: deluan/navidrome:develop
    container_name: navidrome
    ports:
      - "4533:4533"
    environment:
      # Optional: put your config options customization here. Examples
      ND_SCANSCHEDULE: 1m
      ND_LOGLEVEL: debug
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      ND_ENABLETRANSCODINGCONFIG: 'true'
      ND_LASTFM_APIKEY: redacted
      ND_LASTFM_SECRET: redacted
      ND_SPOTIFY_ID: redacted
      ND_SPOTIFY_SECRET: redacted
      ND_LASTFM_LANGUAGE: zh
      ND_ENABLESHARING: 'true'
      ND_PLAYLISTSPATH: Playlist
      ND_AUTOIMPORTPLAYLISTS: 'true'
    volumes:
      - "./data:/data"
      - "./music:/music:ro"
    restart: unless-stopped
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by cfandora** [comment]
I find one way to show local cover
touch all album files and add again :)

**Comment by dnno** [comment]
Navidrome caches album art so that it doesn't have to retrieve it from the source everytime it is needed. What I did before: delete the images directory in the cache folder. This will reset ALL cached images, however. Not sure what's the recommended way to update artwork - I'd be interested in knowing...
