### ISSUE TITLE
[Bug]: .toml configuration MusicFolder attribute problem

### ISSUE THREAD

**Issue by pencail** [navidrome/navidrome#2486]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3

### Current Behavior

Specify the music folder by configuring the MusicFolder in the navidrome.toml file，After changing the folder designated by MusicFolder，navidrome cannot scan music in new folder，It always shows the music in the first folder
### For example：
Initially set MusicFolder="C:\Music"
Then change to MusicFolder="C:\Music1"
The music read in navidrome is still in Music

### Expected Behavior

Specify the music folder by configuring the MusicFolder in the navidrome.toml file，After changing the folder designated by MusicFolder，navidrome cannot scan music in new folder，It always shows the music in the first folder
### For example：
Initially set MusicFolder="C:\Music"
Then change to MusicFolder="C:\Music1"
The music read in navidrome is still in Music

### Environment

```markdown
- OS:Windows Server 2022
- Browser: Chrome 115.0.5790.173
- Client:
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
LogLevel = 'DEBUG'
ScanSchedule = '@every 1h'
TranscodingCacheSize = '150MiB'

MusicFolder = 'C:\Music'
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by certuna** [comment]
Does this happen after a restart of Navidrome?

**Comment by pencail** [comment]
> Does this happen after a restart of Navidrome?

Yes, after the setup is complete, so does the reboot

**Comment by metalheim** [comment]
Can you please try a forward slash in the path name instead of a backslash?
So
`C:/Music`

**Comment by pencail** [comment]
> Can you please try a forward slash in the path name instead of a backslash? So `C:/Music`

yes, it has been tried，Still can't change the folder
