### ISSUE TITLE
[Bug]: can't restore the minimzed player if you switch to desktop mode

### ISSUE THREAD

**Issue by avh4** [navidrome/navidrome#2496]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3

### Current Behavior

If the mobile layout player is minimized and then you switch to desktop layout, then the player is stuck in iconified mode and you can't restore it (until you switch back to mobile layout).

### Expected Behavior

Either of these would make sense to me:
- when you switch from mobile to desktop layout, if the player is a floating icon, then it immediately returns to the normal desktop layout bottom-bar player
- or, if the player stays iconified when switching to desktop mode, then clicking it should restore the normal desktop layout bottom-bar player

### Steps To Reproduce

1. Log in to Navidrome
2. Start playing some music
3. Shrink the window so that mobile layout is triggered, and you now see the full-screen mobile layout player
4. Click the "X" in the top right of the full-screen player, and you now see the player as a floating icon
5. Enlarge the window so that desktop layout is triggered
6. Try clicking the floating icon player, but nothing happens.  If you click the "X" on the floating icon, then it destroys the playlist and stops the music.

### Environment

```markdown
- OS: Linux
- Browser: Firefox
- Client: Navidrome web GUI
```

### How Navidrome is installed?

Docker

### Configuration

```toml
(I think this is not relevant to this frontend issue; lmk if you want me to provide it)
```

### Relevant log output

```shell
No log output in the javascript console when trying to click the floating icon.
```

### Anything else?

There is some brief mention of this in https://github.com/navidrome/navidrome/issues/1217, but that issue as a whole seems to be about something different.

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by certuna** [comment]
Yes this is a known bug in the upstream player component https://github.com/lijinke666/react-music-player , but as this project is not maintained anymore there's not a lot of chance of it getting fixed.
