### ISSUE TITLE
[Bug]: Smart playlist will not update before full rescan

### ISSUE THREAD

**Issue by flemmingss** [navidrome/navidrome#2500]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

Version:	0.49.3 (8b93962f)

### Current Behavior

I have a this smart playlist that is not updating if I am not doing a "Full rescan" by the Web UI. It is out of date for weeks if I don't do that.
If I Go to "Songs" and sort by "Data added", there the new tracks are displaying fine. Even without a full rescan.

**recently_added_individual_tracks.nsp:**
`{
  "all": [
    {"contains": {"filepath": "/music/Individual_tracks"}}
  ],
  "sort": "dateadded",
  "order": "desc",
  "limit": 200
}`

### Expected Behavior

I would expect the new songs to appear in the smart playlist automatically 

### Steps To Reproduce

1. create the playlist
2. view it
3. Add more songs to the /music/Individual_tracks folder
4. view it again, and see the songs are not there, but they are available in Navidrome.
5. 

### Environment

```markdown
- OS: Windows 11
- Browser: Google Chrome
- Client: Web UI, Subtracks and Symfonium (teste with these)
```

### How Navidrome is installed?

Docker

### Configuration

```toml
docker run
  -d
  --name='navidrome'
  --net='bridge'
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="UnRAID"
  -e HOST_CONTAINERNAME="navidrome"
  -e 'ND_SCANSCHEDULE'='1m'
  -e 'ND_LOGLEVEL'='info'
  -e 'ND_SESSIONTIMEOUT'='24h'
  -e 'ND_BASEURL'=''
  -e 'ND_IMAGECACHESIZE'='200MB'
  -e 'ND_SPOTIFY_ID'='xxx'
  -e 'ND_SPOTIFY_SECRET'='xxx'
  -e 'ND_ENABLETRANSCODINGCONFIG'='true'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:4533]/'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/selfhosters/unRAID-CA-templates/master/templates/img/navidrome.png'
  -p '4533:4533/tcp'
  -v '/mnt/user/appdata/navidrome':'/data':'rw'
  -v '/mnt/user/share_media/media/music/organized/':'/music':'rw' 'deluan/navidrome'
xxx
```

### Anything else?

Almost same as this one: https://github.com/navidrome/navidrome/issues/1851
But in my case, opening the web ui itself does not solve the issue.

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by kja999** [comment]
Hi, I have just seen this issue and possibly is related to one I was about to create.
Smart Playlists seem to only refresh when the user they belong to opens that playlist. By default smart playlists are created for admin, and so other users (even when shared) cannot trigger an update.
I think this is a bug, all users with access to a smart playlist should be able to trigger it to refresh.

For this issue you raised, are you using this playlist as a different user than the playlist owner?
