### ISSUE TITLE
[Bug]: Missing music

### ISSUE THREAD

**Issue by ssnepenthe** [navidrome/navidrome#2511]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3 (8b93962f)

### Current Behavior

Not sure if this is worth reporting again... likely related to #379, #359.

Forcing a re-scan with `navidrome scan -f` seems to have fixed it. Feel free to close if you think this is a sufficient solution.

I have been slowly cleaning up some old music with musicbrainz picard and importing into navidrome.

I noticed when importing three albums with the same name (days of the new) that not all songs were found in navidrome.

There were 38 songs total:

![Screenshot from 2023-09-06 18-26-39](https://github.com/navidrome/navidrome/assets/10903810/283d0654-1305-40e2-9ae9-4ddc4b10b0f0)

But navidrome only saw 13:

![Screen Shot 2023-09-06 at 18 25 37](https://github.com/navidrome/navidrome/assets/10903810/9b0daa6c-9e43-4d83-81de-3a9924329da8)

Looking a little closer I noticed that navidrome was showing a total of 1315 songs in my library when it should have been 1349 - an additional 9 songs were missing somewhere.

Checking the logs the only related entry seems be a warning about an error warming cache - probably not relevant.

### Expected Behavior

All files to be imported by the initial scan.

### Steps To Reproduce

I haven't been able to reliably reproduce this issue...

I am slowly importing music 100-200 tracks at a time using rsync over ssh with `-avPz` flags to sync my local music dir to a remote server - not sure if relevant.

### Environment

```markdown
- OS: ubuntu 22.04.3
- Browser: ff
- Client: web browser
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by jmillerv** [comment]
Based on recent experience with odd behavior and Docker, the only thing I can strongly suggest is log into your containers and make sure the Docker file system mirrors the file system you're mounting. My Docker path somehow got a duplicate folder in there, but everything looked fine on the machine that hosts the music files.

**Comment by ssnepenthe** [comment]
As far as I can tell the filesystem matches inside and outside of the container. And like I said if I manually trigger a re-scan navidrome correctly finds all music.

I have run into this an additional 2 or 3 times since I originally posted this issue.

I wonder if it could be a timing issue... Is it possible that this might be happening if a scan is triggered while a file transfer is still in progress?

**Comment by jmillerv** [comment]
How often do you have it set to automatically rescan? I'm hosting on Unraid but the important thing from this screenshot is the ND_SCANSCHEDULE environment variable. I have mine set to 12 hours because I know I'll manually scan if I really need it. 

![image](https://github.com/navidrome/navidrome/assets/50455719/1d5439bf-4d03-48c3-80b5-e746a2b0b301)

**Comment by ssnepenthe** [comment]
I had it at the default of every 1 minute.

I have since changed it to every 10 minutes and so far it seems to have fixed the issue.

Not sure if this should be considered a bug or not...

**Comment by quantenzitrone** [comment]
I had the same problem, my imported playlist should have had 305 songs, but only 180 or something were visible.

If anyone else is on NixOS doesn't know how to rescan:
1. go root, the data folder is owned by root
2. `cd /var/lib/navidrome` (the the default data folder)
4. `config=$(systemctl cat navidrome.service | grep ExecStart | cut -d ' ' -f 3)` to get the config file location
5. get a navidrome binary into your path with
	- `nix shell nixpkgs#navidrome` (flakes)
	- `nix-shell -p navidrome` (channels)
6. `navidrome scan -c $config -f` do execute the full scan

**Comment by quantenzitrone** [comment]
It didn't work :(
It scanned all the missing music and added them to my library, but none of them are playable.

**Comment by quantenzitrone** [comment]
I FOUND THE PROBLEM!
Somehow, some of my music was not readable by the navidrome user.
Make sure the all the folders are `drwxr-xr-x` and all music files are `-rw-r--r--` so navidrome can read them.
I could scan the music, because I did the scan as root, but navidrome runs as the navidrome user, which is not root.

**Comment by dodancs** [comment]
Hmm, I seem to have a similar issue, but the album is not showing up at all:
![image](https://github.com/user-attachments/assets/91451aac-51d1-40aa-9868-0768cf41d501)
![image](https://github.com/user-attachments/assets/3265bd09-ebf1-4145-8904-f8ee17df321c)

The files are there, the permissions are the same as for any other folder/file that is shown without issues in Navidrome. The number of albums also jumped up from 683 to 684, so it was able to scan for it:
![image](https://github.com/user-attachments/assets/c0e5e8e4-7073-4d9a-9cd6-5a9880156fcf)
Also by the logs, it has been scanned successfully and discovered all of the 37 songs:

```
INFO[0004] Finished processing changed folder            deleted=0 dir="/music/Disclosure/Settle (Special Edition) - 2013" elapsed=88.3ms updated=37
```

I then also tried to update from 0.52.0 to 0.52.5, and I still have the same issue. I tried to clear the browser cache etc., but also to no avail.

**Comment by metalheim** [comment]
Can you share how the files are tagged?
Maybe navidrome did read the files, but the album tag isnt correct

**Comment by dodancs** [comment]
> Can you share how the files are tagged? Maybe navidrome did read the files, but the album tag isnt correct

What do you mean by tagged? Metadata?

**Comment by metalheim** [comment]
Yes exactly. Navidrome only cares for the metadata. So if that's not right, then the album wont Show up correctly

**Comment by dodancs** [comment]
> Yes exactly. Navidrome only cares for the metadata. So if that's not right, then the album wont Show up correctly

Seems like all of the songs have basically zero metadata about the album, song, etc.:
![image](https://github.com/user-attachments/assets/2bcb5546-57e9-46e3-8afa-ce609b978afc)

**Comment by dodancs** [comment]
Hell yeah, it works! So for other people, make sure your songs have the proper metadata:

![image](https://github.com/user-attachments/assets/829a9385-af07-4755-8675-3db1e10c0cc0)

```
$ exiftool 14\ -\ Help\ Me\ Lose\ My\ Mind.flac 
ExifTool Version Number         : 12.40
File Name                       : 14 - Help Me Lose My Mind.flac
Directory                       : .
File Size                       : 31 MiB
File Modification Date/Time     : 2024:07:15 11:56:01+02:00
File Access Date/Time           : 2024:07:15 10:36:43+02:00
File Inode Change Date/Time     : 2024:07:15 11:56:01+02:00
File Permissions                : -rw-r--r--
File Type                       : FLAC
File Type Extension             : flac
MIME Type                       : audio/flac
Block Size Min                  : 1152
Block Size Max                  : 1152
Frame Size Min                  : 469
Frame Size Max                  : 4333
Sample Rate                     : 44100
Channels                        : 2
Bits Per Sample                 : 16
Total Samples                   : 10768092
MD5 Signature                   : 2bbf75a47a0af17d50123a6832bcdc17
Vendor                          : reference libFLAC 1.2.1 20070917
Album                           : Settle (Special Edition)
Artist                          : Disclosure
Copyright                       : 2014 Universal Island Records, a division of Universal Music Operations Limited
Date                            : 2013
Genre                           : Elektronika
Organization                    : Universal-Island Records Ltd.
Title                           : Help Me Lose My Mind
Track Number                    : 14
Tracktotal                      : 37
Duration                        : 0:04:04
```

**Comment by deluan** [comment]
Seems that this was fixed. Closing it now. If anyone still have issues with this feel free to open an new Q&A discussion in https://github.com/navidrome/navidrome/discussions/categories/q-a
