### ISSUE TITLE
Support TAK files

### ISSUE THREAD

**Issue by MononeV** [navidrome/navidrome#2514]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3 (8b93962f)

### Current Behavior

Navidrome not showing TAK (Tom's lossless Audio Kompressor) codec files.

### Expected Behavior

Navidrome to recognise and scan TAK files.

### Steps To Reproduce

I have some collections of music in .tak format. Recently I realised that they are not showing in the webUI.

### Environment

```markdown
- OS: Debian
- Browser: Chrome 116.0.5845.180 on Windows 11
- Client: WebUI
```

### How Navidrome is installed?

Docker

### Configuration

```toml
docker run -d \
   --name navidrome \
   --restart=unless-stopped \
   --user 1000:1000 \
   -v /mnt/sdb/Music:/music \
   -v /opt/Navidrome:/data \
   -p 4533:4533 \
   -e ND_LOGLEVEL=info \
   -e ND_ENABLESHARING=true \
   -e ND_SPOTIFY_ID=* \
   -e ND_SPOTIFY_SECRET=* \
   deluan/navidrome:latest
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by metalheim** [comment]
Support *could probably* be added with an addition to:
https://github.com/navidrome/navidrome/blob/f941347cf189387b0bca8c9cac7c747e343b5b10/consts/mime_types.go#L14

as it seems TAK uses
- APE v2 Tags
- ffmpeg can decode TAK files
https://wiki.hydrogenaud.io/index.php?title=TAK

But it is certainly a niche format. Very few to no players/clients will play the files (without transcoding).
So i would generally advise to once re-encode these files as flac tbh. 
It is a losless conversion and flac is very well supported everywhere.

**Comment by MononeV** [comment]
> Support _could probably_ be added with an addition to:
> 
> https://github.com/navidrome/navidrome/blob/f941347cf189387b0bca8c9cac7c747e343b5b10/consts/mime_types.go#L14
> 
> as it seems TAK
> 
> * uses APE v2 Tags
> * ffmpeg can decode TAK files
>   https://wiki.hydrogenaud.io/index.php?title=TAK

Yes, I think it should not be too hard to implement since Navidrome can already recognise APE v2 tags.

**Comment by apkatsikas** [comment]
I confirmed adding the entry for tak on `navidrome/consts/mime_types.go` will allow for scanning .tak files, and using web UI transcode can successfully transcode, allowing us to play the file as an mp3 on-the-fly via Navidrome web client.

However, TagLib officially does not support tak (via docs on https://taglib.org/) - and even a properly tagged via APE v2 Tags (used https://www.mp3tag.de/en/) still won't be able to read the tags. All the info shows as Unknown, and the logs emit `WARN[0002] TagLib: Error reading metadata from file. Skipping  error="cannot parse file media file"` - via this line https://github.com/navidrome/navidrome/blob/03119e5ccfaebc6a618831bb7c312e5ce007ed2b/scanner/metadata/taglib/taglib_wrapper.go#L56

The question is - is being able to scan the file and play via transcode (or download) sufficient support to justify making the change? I'm happy to do the PR but the TagLib limitation gave me pause as to if this was worth it or well-enough supported.

**Comment by deluan** [comment]
Hey @apkatsikas, thanks for testing this out. I think if we cannot properly extract tags from a specific file format, we should not add official support for it. 

But maybe the `ffmpeg` extractor is able to handle it? Can you try changing `Scanner.Extractor` to `ffmpeg` and try to reimport the file? If it can read the tags, then it is ok to add it, and maybe document the restriction.

**Comment by apkatsikas** [comment]
@deluan - I deleted everything from the data folder and brought the service back up with scanner as ffmpeg - it got the correct artist and track title. It did miss the album art, but I'm not certain if that was possible user error by me:

`11:05:25 AM GO.1 |  WARN[0002] Error warming cache                           error="error cacheing id='ar-40c06a6bfff85cf3048866a213d38db0_0': could not get a cover art for ar-40c06a6bfff85cf3048866a213d38db0_0: artwork unavailable"`.

I can make a PR to add tak to the mime types with a comment that it will require ffmpeg scanner/TagLib will not be supported.

**Comment by deluan** [comment]
If ffmpeg supports it, it should be able to extract embedded coverart from the file. Try this command:
```
ffmpeg -i YOURFILE.TAK -an -vcodec copy -f image2pipe - > image.jpg
```
and see if it creates a valid `image.jpg`

Anyway, go ahead and create a PR. Also, please send me the TAK file you are using for your tests.

**Comment by apkatsikas** [comment]
@deluan here is a Creative Commons full-length track - https://drive.google.com/file/d/1n7wNVWcP5-YDin7X0ne9cClFJd1Nlc5f/view?usp=sharing - I wasn't aware of the embedded artwork concept but it works fine now that I did it correctly.

The PR I opened also has a 1 second test noise tak file derived from the existing wav fixture file https://github.com/navidrome/navidrome/pull/2745
