### ISSUE TITLE
[Bug]: Title expect only file name and no folder name

### ISSUE THREAD

**Issue by thelou1s** [navidrome/navidrome#2523]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3-SNAPSHOT

### Current Behavior

Title sometimes show folder+file name

### Expected Behavior

Title only show file name

### Environment

```markdown
- OS: MacOS 13.5.2 (Docker)
- Browser: Safari
- Client: Safari
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by certuna** [comment]
this is normal, if there's no Title in the tags, the filename is displayed.

**Comment by thelou1s** [comment]
Thank you for reply，
filename is fine, but not foldername+filename

**Comment by metalheim** [comment]
Then tag your files with a song title.
Navidrome is explicitly tag-based

**Comment by dmarcoux** [comment]
I think this issue should be closed since it is not a bug as @metalheim said.
