### ISSUE TITLE
[Bug]: The browser page freezes when there are a large number of tracks in the album.

### ISSUE THREAD

**Issue by VlaK0r** [navidrome/navidrome#2539]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

 v0.50.0 Latest

### Current Behavior

The browser page freezes when there are a large number of tracks in the album.
https://musicbrainz.org/release-group/0eb70f80-7d09-4554-8b54-ebc157098ab6

![image](https://github.com/navidrome/navidrome/assets/77666575/ae49176c-0a2e-447d-ae62-8df78206f44a)

![image](https://github.com/navidrome/navidrome/assets/77666575/9ec1539c-84f8-46b9-9049-6900c4496fb3)

![image](https://github.com/navidrome/navidrome/assets/77666575/c6c56687-7583-42f9-bc36-5979ae8c16c8)

### Expected Behavior

I suggest dividing it into pages, for example 200 - 300 tracks.

### Environment

```markdown
- OS:Debian 12
- Browser:Firefox 117.0.1 64
- Client:Firefox 117.0.1 64
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by grange85** [comment]
I am getting the same issue here - just loaded in an album with 109 tracks and things break/freeze when trying to play tracks:

### Environment

- PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
- NAME="Raspbian GNU/Linux"
- VERSION_ID="11"
- VERSION="11 (bullseye)"
- VERSION_CODENAME=bullseye
- ID=raspbian
- ID_LIKE=debian

Tested on:

 - Firefox 119.0 (64-bit)
 - Chrome Version 118.0.5993.117 (Official Build) (64-bit)
 

### How Navidrome is installed?

Linux install

**Comment by VlaK0r** [comment]
Dear developer, can I hope that you will pay attention to this problem?

**Comment by deluan** [comment]
This is an known issue and I hope to get it fixed with the refactoring of the UI. For now, you can try setting `DevActivityPanel=false`. For more details see https://github.com/navidrome/navidrome/issues/1186

**Comment by VlaK0r** [comment]
> This is an known issue and I hope to get it fixed with the refactoring of the UI. For now, you can try setting `DevActivityPanel=false`. For more details see #1186
Thanks!
