### ISSUE TITLE
[Bug]: Cover art with AIFF format unable to process from embedded target

### ISSUE THREAD

**Issue by whosboosh** [navidrome/navidrome#2544]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3

### Current Behavior

Attempts to get navidrome to read and process covert art for .aiff file formats fail with a log in navidrome as:
`WARN[0004] Error warming cache error="error cacheing id='ar-62ec006a06b72cebf6213a43949246dc_0': could not get a cover art for ar-62ec006a06b72cebf6213a43949246dc_0: artwork unavailable"`
All clients show the generic covert art for these files that fail.

In my navidrome.toml I have: `CoverArtPriority = "cover.*, folder.*, front.*, embedded"`
After converting these files to FLAC, navidrome has no issues reading the file format. I did a familiar ffmpeg command to convert all files in the current directory from .aiff to .flac which preserves the covert art metadata. `find . -type f -iname "*.aiff" -exec sh -c 'bn=${1##*/}; bn=${bn%.*}; ffmpeg -loglevel 16 -i "$1" "${bn}.flac"' . {} \;`

### Expected Behavior

Cover art is processed from the file metadata and shown in the GUI

### Steps To Reproduce

1. Obtain any .aiff files with cover art attached. (Those downloaded from bandcamp have this issue)
2. Run navidrome with the config option `CoverArtPriority = "embedded"` to prevent navidrome obtaining cover art via external sources or cover.jpg file if it exists
3. See if navidrome is able to process the file and display the covert art in clients

### Environment

```markdown
- OS: Fedora 38
- Browser: Version 1.58.131 Chromium: 117.0.5938.92 (Official Build) unknown (64-bit)
- Client:
```

### How Navidrome is installed?

Binary (from downloads page)

### Relevant log output

```shell
`WARN[0004] Error warming cache error="error cacheing id='ar-62ec006a06b72cebf6213a43949246dc_0': could not get a cover art for ar-62ec006a06b72cebf6213a43949246dc_0: artwork unavailable"`
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by eclecticpassions** [comment]
I have the same issue. Even if the art is embedded, Navidrome doesn't see it. Also the .aiff file can't be played on the webplayer.
