### ISSUE TITLE
[Bug]: FLAC file names do not display properly in the song list

### ISSUE THREAD

**Issue by tianyuliufang233** [navidrome/navidrome#2569]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3

### Current Behavior

FLAC file names do not display properly in the song list

### Expected Behavior

I upload the flac file to the music directory and restart the service, and the name displayed in the song list is not the file name

### Environment

```markdown
- OS: centos
- Browser:  edge 118.0.2088.46
- Client:
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by metalheim** [comment]
Not a Bug!
Navidrome doesnt care about the filename. Navidrome reads the Song title Tag in the file and displays that.

Check what tags your file has with Mp3tag or similar Software.

**Comment by tianyuliufang233** [comment]
oh thanks
