### ISSUE TITLE
[Bug]: Genres not updated after a full scan

### ISSUE THREAD

**Issue by codeinabox** [navidrome/navidrome#2574]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3 (8b93962f)

### Current Behavior

When I change the genres of a recording using Picard with `Preserve timestamps of tagged files` enabled, and then click on `Full Rescan` in Navidrome it still displays the previous genres after the scan is complete.

### Expected Behavior

That after a full rescan the updated genres are used and displayed.

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by mneuburg-livefront** [comment]
Yes, I had to throw away the database to get it to read my genre changes.

**Comment by dweymouth** [comment]
I can confirm this on 0.50.1 - album genres are updated but it appears track genres are not. (I don't use any client that shows track genres directly but old genres I removed still appear in the library genres list and show e.g. "Album count: 0, Track Count: 10" in Supersonic)

**Comment by deluan** [comment]
> I can confirm this on 0.50.1

Or 0.51.0?

**Comment by dweymouth** [comment]
No, I am still on 0.50.1 Docker. I should get around to updating though.. But I imagine this still exists in 0.51.0 unless a change to genres scanning went in.

**Comment by deluan** [comment]
@codeinabox It will be fixed in #2709, as a "Full Rescan" will actually mean it. Currently it still relies on the files modification timestamp to update some info.

@dweymouth Your's is a different issue. Please open a new bug ticket.
