### ISSUE TITLE
[Bug]: Webinterface shows "No Songs yet."

### ISSUE THREAD

**Issue by 9129440428** [navidrome/navidrome#2581]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3-SNAPSHOT (59f0c487)

### Current Behavior

Webinterface has issues with showing songs.

/app/#/song shows entries as expected at the beginning of the music file import but after some time it changes to
"No Songs yet."!

Fetching data from the /api/song endpoint via curl or python works and also searching titles in the sonos app via bonob works.

level=warning msg="media CountAll error" error="data not found"

I have no idea how to debug the issue and i can't find the files that causing the issue. (might be some mp3 tag... idk)

Music files are located on a local btrfs subvolume.

### Expected Behavior

/app/#/song should skip issues or print an error message

### Steps To Reproduce

IDK

### Environment

```markdown
- OS: MAC
- Browser: Chrome
- Client:
```

### How Navidrome is installed?

Docker

### Configuration

```toml
version: "3"
services:
  navidrome:
    container_name: navidrome
    network_mode: host
    image: deluan/navidrome:develop
    privileged: false
    read_only: true
    user: 1004:1001
    ports:
      - "4533:4533"
    environment:
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=debug  
      - ND_SESSIONTIMEOUT=24h
      - TZ=Europe/Vienna
    volumes:
      - /navidrome/data:/data
      - /Music:/music:ro
    cap_drop:
      - SYS_ADMIN
```

### Relevant log output

level=warning msg="media CountAll error" error="data not found"

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by metalheim** [comment]
Is navidrome still on the Initial scan?

Can you try a stable release instead of the develop:branch?

**Comment by 9129440428** [comment]
I saw that request in the logfile from clicking on songs in the webfrontend which ends in "No Songs yet."

`
time="2023-11-02T19:20:38Z" level=debug msg="HTTP: GET http://192.168.X.X:4533/api/song?_end=15&_order=ASC&_sort=title&_start=0" elapsedTime=83.3ms httpStatus=200 remoteAddr="192.168.8.100:64177" requestId=XXXXXXXXXXX responseSize=17407 userAgent="XXXXXXXXXXXXXXXX"
`

Putting that into a python script works flawless. 
`
import requests

base_url = "http://192.168.X.X:4533"

login_url = f"{base_url}/auth/login"
login_data = {
    "username": „XXXX“,  
    "password": „XXXX“  
}

login_response = requests.post(login_url, json=login_data, verify=False)
login_response_json = login_response.json()
token = login_response_json.get("token")
print(token)

if token:
    headers = {
        "x-nd-authorization": f"Bearer {token}"
    }

    songs_url = f"{base_url}/api/song?_end=15&_order=ASC&_sort=title&_start=0"
    songs_response = requests.get(songs_url, headers=headers, verify=False)
    print("Response Content:", songs_response.text)
    songs_data = songs_response.json()

    if songs_response.status_code == 200:
        print("List of Songs:")
        for song in songs_data:
            print(song)
    else:
        print(f"Failed to fetch songs. Status code: {songs_response.status_code}")
else:
    print("Authentication failed. Check your credentials.")
`

**Comment by 9129440428** [comment]
The X-Total-Count header sent by the api with "song?_end=15&_order=ASC&_sort=title&_start=0" is 0 even though
data get delivered.

**Comment by 9129440428** [comment]
You can close that "issue"!

The time I've spent on it, I won't get back.

It looks like the app somehow needs to write data to the local container filesystem (swapping idk?!?)
after about 40000+ files being scanned.

Setting "read_only: true" causing the api to return X-Total-Count 0 with that amount of files.
