### ISSUE TITLE
[Bug]: Fuzzy search is not supported during the search

### ISSUE THREAD

**Issue by hhs66317** [navidrome/navidrome#2596]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3

### Current Behavior

Suppose I had the following songs now

让一切随风
风中的承诺

When searching for "风"

Only the following can be retrieved

风中的承诺

### Expected Behavior

I hope the following results can be obtained

让一切随风
风中的承诺

### Environment

```markdown
- OS:
- Browser:
- Client:
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
You can enable the config option [SearchFullString](https://www.navidrome.org/docs/usage/configuration-options/#:~:text=%22%40every%201m%22-,SearchFullString,-ND_SEARCHFULLSTRING), it should allow the substring search in your example (it is not fuzzy).

Fuzzy search may be added as part of #255.

If the config change does not help, feel free to report on the issue #255.

**Comment by hhs66317** [comment]
> You can enable the config option [SearchFullString](https://www.navidrome.org/docs/usage/configuration-options/#:~:text=%22%40every%201m%22-,SearchFullString,-ND_SEARCHFULLSTRING), it should allow the substring search in your example (it is not fuzzy).
> 
> Fuzzy search may be added as part of #255.
> 
> If the config change does not help, feel free to report on the issue #255.

thx！
Your method is very useful, thank you again！
