### ISSUE TITLE
Change theme based on browser's settings

### ISSUE THREAD

**Issue by brianpierson2020** [navidrome/navidrome#260]
It would be fancy to have an option to automatically switch between light (day) and dark (night) mode based on sunset/sunrise in current timezone. Just dropping it here for the backlog.

**Comment by deluan** [comment]
Not sure if there is demand for this. I'd surely not use it :) 
I'll keep this issue open to let others chime in.

**Comment by Kernald** [comment]
I'd like to see something like that, but rather than time-based, making use of CSS's `prefers-color-scheme` would probably make more sense - https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by deluan** [comment]
@Kernald That's actually a great idea! I think this kind of thing is out-of-scope for Navidrome, and should be the browser/OS responsibility, and this attribute makes total sense. I'll take a look at this

**Comment by deluan** [comment]
Info on how to use `prefers-color-scheme` with Material-UI's themes: https://material-ui.com/customization/palette/#user-preference

**Comment by YashJipkate** [comment]
HI @deluan @brianpierson2020! I would like to work on this issue.

**Comment by dpirad007** [comment]
@deluan In applying this feature, the user model would have to include weather the user has ever changed the theme, As any time the app loads i can do a check to see the preference dark or light, However if the user selects light then on the next reload it should not default to dark by the system preference. Or am i missing something?

**Comment by deluan** [comment]
The idea is to have a new option, "Auto", that would switch automatically between "Light" and "Dark", based on the browser's theme. If the user sets it to anything else ("Light", "Dark", ...), Navidrome would only use the selected theme, ignoring the browser's theme

**Comment by dpirad007** [comment]
> The idea is to have a new option, "Auto", that would switch automatically between "Light" and "Dark", based on the browser's theme. If the user sets it to anything else ("Light", "Dark", ...), Navidrome would only use the selected theme, ignoring the browser's theme

Ohh okay, cool

**Comment by YashJipkate** [comment]
@deluan Following up on our discussion. According to your idea, I tried to implement this by placing the hook in `Layout` and added an additional theme choice `Auto` in the select theme dropdown. The only problem is reading from `localStorage`. Reading in `themeReducer` changes the `theme` state, which reflects in the dropdown as it changes from `Auto` to `Light/Dark`. 
What I thought was to not read the `localStorage` in the reducer and let it set the `theme` state to `Auto` and read from the `localStorage` when we need it (like in `Layout` or `Player`). 
Another option can be to create an entirely new state to store the theme name, while the current `theme` state would represent the preferred user 'theme mode'.
What are your thoughts on this? Is there any other way this can be done?

**Comment by deluan** [comment]
You actually don't need to use the `localStorage` as I proposed before. You could use the hook in the [`Layout` component](https://github.com/navidrome/navidrome/blob/a168f46b959479858333fbcdc2c62d8635c6c533/ui/src/layout/Layout.js#L16), and if the selected theme is "Auto", it calls the hook to retrieve the browser/OS preferred theme and set it accordingly.

**Comment by YashJipkate** [comment]
Thanks, @deluan, for the guidance; I learned a lot about the codebase and the practices. I have made #835 to fix this issue now. Please take a look!
