### ISSUE TITLE
[Bug]: Albums with multiple artists are split by artists

### ISSUE THREAD

**Issue by diyoyo** [navidrome/navidrome#2600]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3 

### Current Behavior

In the Albums -> All 's tab, one single album with multiple artists will show up as many times as there are artists...

### Expected Behavior

One Album = One album card in the Albums->All's tab.

### Environment

```markdown
- OS: Linux
- Browser: not important
- Client: Web
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by certuna** [comment]
https://www.navidrome.org/docs/faq/

I have an album with tracks by different artists, why is it broken up into lots of separate albums, each with their own artist?

Navidrome only organises music by tags, it will not automatically group a folder containing a bunch of songs with different artists into one album.

For a “Various Artists” compilation, the Part Of Compilation tag (TCMP for id3, COMPILATION for FLAC) must be set, for all tracks.

For a single-artist album with a different artist name for each track (for example “Alice feat. Bob” , “Alice feat. Carol”), the Album Artist tags must be the same (“Alice”) for all tracks.
