### ISSUE TITLE
[Bug]: Most favorite albums disappear after upgrading version 0.50.0

### ISSUE THREAD

**Issue by TengYangTuoHai** [navidrome/navidrome#2618]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.50.0

### Current Behavior

When I used version 0.50.0 and waited for the scan to complete, the albums previously flagged as favorites disappeared

### Expected Behavior

Need to display the original albums marked as favorites correctly

### Environment

```markdown
- OS: Ubuntu 22.04
- Browser: Edge 119.0.2151.58 on MacOS
- Client:
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
With the default behaviour of splitting albums by release date, the Album IDs were probably changed, causing Navidrome to consider them different albums. Sorry for the inconvenience, I failed to add this breaking change behaviour to the release notes. If you have a backup of the `navidrome.db` file, you can restore it and change the new [Scanner.GroupAlbumReleases](https://www.navidrome.org/docs/usage/configuration-options/#:~:text=Scanner.GroupAlbumReleases) to `true`, to simulate the old behaviour.

**Comment by TengYangTuoHai** [comment]
I don't have a backup of the database, but since my data volume is relatively small, I can manually restore it, so it's okay for me. However, I think it should be documented in the update notes to prevent other users with larger data volumes from upgrading and experiencing widespread data loss.

**Comment by deluan** [comment]
Yeah, just added that. Thanks!
