### ISSUE TITLE
[Bug]: If the time of the lyrics is: [xx:xx.xxx], "No lyrics" is displayed.

### ISSUE THREAD

**Issue by terryyj** [navidrome/navidrome#2619]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.50.0

### Current Behavior

If the time of the lyrics is: [xx:xx.xxx], "No lyrics" is displayed.
If the time of the lyrics is: [xx:xx.xx], the lyrics can be displayed

### Expected Behavior

If the time of the lyrics is: [xx:xx.xxx], the lyrics can also be displayed

### Environment

```markdown
- OS:Windows 10
- Browser:Google Chrome
- Client:Web UI
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by apkatsikas** [comment]
I think this issue will be fixed by https://github.com/navidrome/navidrome/pull/2656

**Comment by deluan** [comment]
Yes this will be fixed in #2656, to be part of the next release.

**Comment by apkatsikas** [comment]
I think https://github.com/navidrome/react-music-player/pull/3 also needs to go along with it. .xxx lyrics will be supported without it, but the multiplication bug is fixed in the player there, which prevents problems with lyrics appearing out of order.
