### ISSUE TITLE
[Bug]:  Version v0.50.0 may fail to start on a Docker setup based on X86/64.

### ISSUE THREAD

**Issue by tty228** [navidrome/navidrome#2621]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

v0.50.0

### Current Behavior

Upgrading from v0.49.2 to v0.50.0

### Expected Behavior

Running smoothly

### Steps To Reproduce

Version v0.50.0 cannot start on my machine, which is based on X86_64 OpenWrt. After launching, the Docker logs show "stderr: exec /app/navidrome: exec format error." 
I attempted to change the image to navidrome:develop, and now it runs smoothly in version 0.50.0-SNAPSHOT (53607fe1).

I only see one OS/ARCH image on the https://hub.docker.com/r/deluan/navidrome/tags website. Could there be an error during the image generation?

![微信截图_20231117181451](https://github.com/navidrome/navidrome/assets/33397881/0a5b40dc-9c3e-4c27-aff3-a75915231fca)

### Environment

```markdown
- OS: Windows 10
- Browser: edge
- Client:
```

### How Navidrome is installed?

Docker

### Relevant log output

```shell
stderr: exec /app/navidrome: exec format error
stderr: exec /app/navidrome: exec format error
stderr: exec /app/navidrome: exec format error
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by fabsmusicjunkie** [comment]
I have the same problem with my raspberry pi 4 (Raspbian, 64bit)

**Comment by clanps** [comment]
Having the same problem also with my raspberry pi 4 (Raspberry Pi OS Lite, 64-bit)

**Comment by dro-ex** [comment]
Same.  Rancher desktop mac mini 2018

**Comment by deluan** [comment]
Yes, there was an issue when publishing the new image to Docker Hub, but it was successfully pushed to GHCR, as mentioned by @sprnza .

I was able to manually fix the AMD64 image, but the ARM ones are still broken. The issue was already fixed and next release will be pushed normaly to both repositories.

**Comment by ScruffyDerHausmeister** [comment]
Can you fix it in ARM docker image also?

**Comment by deluan** [comment]
> Can you fix it in ARM docker image also?

I prefer to let the pipeline deploy all images, and not mess manually with the docker repo. Next version (0.50.1 due tomorrow) will be published for all platforms normally.

If you can't wait, I suggest using the `ghcr.io/navidrome/navidrome:0.50.0` image.
