### ISSUE TITLE
[Bug]: Music files with multiple artists will only display the first artist.

### ISSUE THREAD

**Issue by tty228** [navidrome/navidrome#2623]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

Version:	0.50.0-SNAPSHOT (53607fe1)

### Current Behavior

In the ID3v2 tag specification, the separator between multiple artists is ";". 
For example, if a song has two artists, their names can be written as "Artist1; Artist2". These song files can be correctly recognized with multiple artists on Windows and foobar2000. 
However, in Navidrome, only the first artist is displayed, and other artists are ignored.

Windows & foobar2000:

![111111](https://github.com/navidrome/navidrome/assets/33397881/8e71e833-a184-4699-9bf9-8e33eee5c4ef)

![微信截图_20231117215234](https://github.com/navidrome/navidrome/assets/33397881/c5bca5e1-ce9f-4c51-be9b-c08582756f12)

Navidrome:
![3333](https://github.com/navidrome/navidrome/assets/33397881/5931f8b4-3318-4ed0-8252-03333c033d13)
![2222](https://github.com/navidrome/navidrome/assets/33397881/3bec6b22-4878-43a0-a4e9-839ef9de1180)

### Expected Behavior

Correctly recognizing multiple artists.

### Environment

```markdown
- OS: Windows 10
- Browser: Microsoft Edge 119.0.2151.58 on Windows 10
- Client:
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by metalheim** [comment]
#238

**Comment by tty228** [comment]
> #238当前稳定版本中未实现多艺术家支持 它将在 #2524 合并时实现

Thanks
