### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jahsen** [navidrome/navidrome#2637]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [ ] I'm using the latest version (your issue may have been fixed already)

### Version

Missing Windows Binaries for version 0.50.0

### Current Behavior

Missing Windows Binaries for version 0.50.0

* In the docs it says: 
If you can’t find a pre-built binaryfor your platform, you should open an issue in the project’s GitHub page.
Thanks

### Expected Behavior

Windows Binaries for version 0.50.0

### Environment

```markdown
- OS:Windows
- Browser:
- Client:
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by zeezhao** [comment]
There us a bug in Windows version, so removed. See
https://old.reddit.com/r/navidrome/comments/17x62nb/navidrome_0500_just_released/

**Comment by jahsen** [comment]
Sorry about that :)
