### ISSUE TITLE
[Bug]: Albums show twice, one empty, one full

### ISSUE THREAD

**Issue by khalimerot** [navidrome/navidrome#2638]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

Docker : Version: 0.50.0 (fee0f40a)

### Current Behavior

All my albums are showing twice, one album is empty, one is normal

![3](https://github.com/navidrome/navidrome/assets/20107904/6ef4a6fa-c352-43db-baf5-3be0ad492410)
![2](https://github.com/navidrome/navidrome/assets/20107904/9cc4d9bd-b559-4514-b768-d57fdebe5eeb)
![1](https://github.com/navidrome/navidrome/assets/20107904/da0789b4-1bd9-4bef-b0d1-15dd57510f7c)
![4](https://github.com/navidrome/navidrome/assets/20107904/91615367-5e2d-4dcd-9428-c3a699ba258f)

### Expected Behavior

Each album must appear only once

### Environment

```markdown
- OS:Unraid 6.12.3
- Browser: Chrome
- Client: navidrome web UI, Symfonium, Substreamer
```

### How Navidrome is installed?

Docker

### Relevant log output

time="2023-11-20T11:56:18Z" level=info msg="Finished processing changed folder" deleted=0 dir="/music/Anime - Comics/Beck/BECK Original Soundtrack - BECK" elapsed=2.07s updated=21
time="2023-11-20T11:56:26Z" level=info msg="Finished processing changed folder" deleted=0 dir="/music/Anime - Comics/Beck/BECK Original Soundtrack - KEITH" elapsed=730.7ms updated=12

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by khalimerot** [comment]
I don't know what's going on, but i noticed the quick scan is extremely slow.
I'll remove navidrome from my daily backup so it can complete a full scan, and check if things goes better after.

**Comment by metalheim** [comment]
Noticed this too at first. But once the Initial full scan was completed, navidrome removed the empty albums for me

**Comment by khalimerot** [comment]
yep something strange must have happen, making navidrome need a full rescan, but as my server is stopping everyday for backup, it must not have the time to scan everything.

I removed the container from the backup for today, i'll check if it's better tommorow evening.

Thanks for the input

**Comment by metalheim** [comment]
Version 0.5.0 added a bunch of new metadata fields, hence it needs to rescan all files (full rescan).
I think the cleanup of empty objects is done at the end of the scan, so if you cancel the scan, the cleanup doesnt happen and you are left with empty albums.

**Comment by khalimerot** [comment]
1 Day and an half later it as completed the scan, and indeed, duplicate was removed.
problem solved.

**Comment by metalheim** [comment]
That seems like a slow scan for sure!
But happy that it is eventually completing and cleaning up.

If the issue is solved, please close the issue :)

**Comment by khalimerot** [comment]
Scanning over network with more than 10k folders, and there is other services running through the network, so yes it take a while. 
i'll close it.
