### ISSUE TITLE
[Bug]: multiple genres not working correctly with symfonium /opensubsonic 

### ISSUE THREAD

**Issue by metalheim** [navidrome/navidrome#2642]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.50.0-SNAPSHOT (a5dfd2d4)

### Current Behavior

After upgrading to latest develop tagged branch (with #2597 merged), i noticed that symfonium does not recognize any genre for any Song and/or Album.

All my Songs are tagged with multiple genres.
Even Songs that were added to my library after the navidrome upgrade are missing genre in symfonium.

Songs/albums that had 1 Genre (in symfonium) before the navidrome upgrade now have none 

### Expected Behavior

Songs and albums should have multiple genres correctly recognized by symfonium 

### Environment

```markdown
- Client: symfonium 6.1.0 (1168)
```

### How Navidrome is installed?

Docker on a synology NAS

#### Symfonium logs (symfonium generated a 10GB logfile... im filtering out some relevant lines

```shell


```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
@Tolriq, any ideas?

**Comment by Tolriq** [comment]
Well no logs no chocolate, I have not yet tested last version will try to find time today.

**Comment by Tolriq** [comment]
@deluan there's no portable windows build of 0.50 can't test :(

**Comment by metalheim** [comment]
@Tolriq thanks for chiming in, i think this is a navidrome issue.
I captured Symfonium Debug logs (which are 420MB just from today) and it seems that navidrome is returning

```getSong``` responses for a specific song:
[x] genre
[x] genres (multiple if they are there)

This looks perfect like i would expect it, Example response:
https://textbin.net/iutdwtk3aj

```search3``` responses for Albums:
[x] genre
[] genres (always returns emtpy array "[]")

Example response: https://textbin.net/5syp45khc3

```search3``` responses for Songs:
[x] genre
[] genres (always returns emtpy array "[]")

Example response (shortened) https://textbin.net/geuxs3pklc

@dweymouth since you implemented most opensubsonic features, could you please check on this?

**Comment by deluan** [comment]
@Tolriq you can use this build: 
[navidrome_windows_amd64_windows_amd64_v1.zip](https://github.com/navidrome/navidrome/files/13426054/navidrome_windows_amd64_windows_amd64_v1.zip)

@dweymouth Is it working with Supersonic?

**Comment by deluan** [comment]
@Tolriq You can download the latest build from here: https://github.com/navidrome/navidrome/suites/18375209413/artifacts/1064128656

**Comment by deluan** [comment]
In my test here (using Jamstash or curl), Navidrome is replying with correct `genres` array:
```json
{
    "subsonic-response": {
        "status": "ok",
        "version": "1.16.1",
        "type": "navidrome",
        "serverVersion": "0.50.0-SNAPSHOT (a5dfd2d4)",
        "openSubsonic": true,
        "album": {
            "id": "52242aca2a01502e12a496d753661933",
            "name": "Hit Parade 5",
            "artist": "Various Artists",
            "artistId": "03b645ef2100dfc42fa9785ea3102295",
            "coverArt": "al-52242aca2a01502e12a496d753661933_60fc987f",
            "songCount": 14,
            "duration": 3917,
            "created": "2021-07-24T22:48:49.314676958Z",
            "userRating": 0,
            "year": 1982,
            "genre": "Pop",
            "genres": [{
                "name": "Pop"
            }, {
                "name": "Hip-Hop"
            }],
            "musicBrainzId": ""
        }
    }
}
```

**Comment by Tolriq** [comment]
As @metalheim said if the search3 endpoints returns empty genres then Symfonium takes it as there's no genre as expected. Search3 must return proper values too for albums and songs.

**Comment by deluan** [comment]
Yes, I see that it is broken and will try to fix that tonight as I mentioned. It is not Symfonium's issue. Hopefully I'll be able to fix it before tonight's release

**Comment by dweymouth** [comment]
> Not sure why the getSong result is broken, though.

Could it be the same reason? That the query isn't doing a join with the genres table? I didn't dig into the DB layer but if the MediaFile struct returned by the db query has its Genres property populated, it will be marshaled into the OpenSubsonic response.

**Comment by metalheim** [comment]
@dweymouth getSong looks fine, only search3 misses the multivalued genres from what I can See

https://github.com/navidrome/navidrome/issues/2642#issuecomment-1820663554

Its just that symfonium uses search3 to sync all Song and Album entries

**Comment by dweymouth** [comment]
@deluan I see that in the `getAlbumList2` implementation you are calling `GetAllWithoutGenres` on the albums repository [here](https://github.com/navidrome/navidrome/blob/master/server/subsonic/album_lists.go#L64C54-L64C54), and it seems that `GetAll` is already an existing function alongside `GetAllWithoutGenres`. So maybe the fix is as simple as switching to calling that method to retrieve albums in both the album list endpoints and `search3`? I am away from my devbox with my navidrome build environment set up so I can't test this myself but it seems like hopefully it should be a quick fix.

**Comment by deluan** [comment]
> So maybe the fix is as simple as switching to calling that method to retrieve albums in both the album list endpoints and search3?

Yep, that's my plan. But the reason to use `GetAllWithoutGenres` is basically performance. I'll do some testing before changing that.

As @metalheim mentioned, `getSong` is not an issue, my bad.

**Comment by dweymouth** [comment]
This is not the place for this discussion (can start something in OpenSubsonic later) but I feel like we may need something similar to Jellyfin's `setIncludeFields` eventually, where clients can say they don't need `genres` or a certain field to be filled for a given API call, to allow the server to optimize the query if possible

**Comment by Tolriq** [comment]
Yes it's needed for the new future endpoints that also handle all the new filters and sorts.

**Comment by metalheim** [comment]
Can confirm that #2648 solves this issue.
Now symfonium picks up all my genres :)
