### ISSUE TITLE
[Bug]: Version in "About" still 0.50.0 after Upgrade to 0.50.1

### ISSUE THREAD

**Issue by skaramuz** [navidrome/navidrome#2652]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.50.1

### Current Behavior

I installed the new version 0.50.1 yesterday. However, the version number 0.50.0 still appears in the "About"-dialog.

### Expected Behavior

After upgrading to 0.50.1, 0.50.1 should also appear in the "About"-dialog

### Environment

```markdown
- OS:
- Browser:
- Client:
```

### How Navidrome is installed?

Binary (from downloads page)

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by metalheim** [comment]
It does Show 0.50.1 for me
Can you force a Browser refresh ( `Ctrl` + `F5`) please?

**Comment by pattmax00** [comment]
I can also confirm that it appears correctly for me after upgrading today.
Exactly what steps did you take to update?

**Comment by skaramuz** [comment]
I did the following steps:

`service navidrome stop
wget https://github.com/navidrome/navidrome/releases/download/v0.50.1/navidrome_0.50.1_linux_amd64.tar.gz
tar xfvz navidrome_0.50.1_linux_amd64.tar.gz
service navidrome start`

**Comment by deluan** [comment]
But did you refresh the browser window? If not, it will still be running the old version.

**Comment by skaramuz** [comment]
If I execute the binary directly at CLI, the version number is correct, but it is displayed incorrectly in the browser (several browsers, PCs and after I have pressed CTRL-F5). But that "bug" ist not really important ;-)

'./navidrome -v'
'0.50.1 (f69c27d1)'

Many thanks for your great work!

**Comment by skaramuz** [comment]
I'm an idiot ;) I updated the binary under /var/lib/navidrome, not under /opt/navidrome. Sorry!
