### ISSUE TITLE
[Bug]: Clickable Artists work but it fails for Artists without Albums

### ISSUE THREAD

**Issue by kobayashi90** [navidrome/navidrome#2658]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.50.1

### Current Behavior

Exspecting that it doesnt show an error like this one if you click on an Artist without an Album.
![firefox_TrEYjTwaYB](https://github.com/navidrome/navidrome/assets/51263756/a299a734-4918-4221-8377-64f289b15bfa)

### Expected Behavior

Well that its working?

### Steps To Reproduce

Create an Album with Various Artists and have for example Mozart on track 1-10 and Bach on track 11.

### Environment

```markdown
- OS: Windows 11
- Browser: Firefox
- Client: Navidrome Web
```

### How Navidrome is installed?

Docker

### Configuration

```toml
-
```

### Relevant log output

```shell
-
```

### Anything else?

-

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
This can happen if the album was just imported but the scan process is still running. Can you confirm the scan process finished successfully?

**Comment by certuna** [comment]
Yeah this should only happen during the scan, afterwards the non-album artists are cleaned up and the links disappear.

https://github.com/navidrome/navidrome/pull/2583 fixes this, but isn't merged yet

**Comment by kobayashi90** [comment]
well then please merge it @deluan and make an 0.50.2 or something because i had to downgrade before ive got many errors while moving from 0.49.3 to 0.50.1 like the date formatting not being accepted (example: 10/09/2011) and others like musicbrainz id missing even tho the file doesnt had that tag to beginn with..
![firefox_EQo8NJ7hMK](https://github.com/navidrome/navidrome/assets/51263756/dd0cdffb-6463-4ebb-8631-97a29e90068e)

**Comment by kobayashi90** [comment]
> #2583 fixes this by making all artists clickable, but isn't merged yet

Ah i didnt seen this change for some reason but great that somebody already solved that problem.

**Comment by deluan** [comment]
> well then please merge it @deluan and make an 0.50.2 or something because i had to downgrade before ive got many errors while moving from 0.49.3 to 0.50.1 like the date formatting not being accepted (example: 10/09/2011) and others like musicbrainz id missing even tho the file doesnt had that tag to beginn with.. ![firefox_EQo8NJ7hMK](https://private-user-images.githubusercontent.com/51263756/286703962-dd0cdffb-6463-4ebb-8631-97a29e90068e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyODMzNzEsIm5iZiI6MTcwMTI4MzA3MSwicGF0aCI6Ii81MTI2Mzc1Ni8yODY3MDM5NjItZGQwY2RmZmItNjQ2My00ZWJiLTg2MzEtOTdhMjllOTAwNjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE4Mzc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0OWRmM2ZiOWNmN2QyNmE5YzYxN2NhODg5YzY5OWZjODdkMmRhMzQxZjUwNzU4Nzc4ZjNlMDYxODgzYWFmMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r3i7ZDxYwzkJLeMBAqbonjrp9bXkESnKw9YIJk2Z2nY)

These are just warnings to let you know there's something wrong with your tags. They are not something new in 0.50.1, it has always been like this, is just that you didn't noticed before :)

And as @certuna and I said, clicking on an artist without albums is only an issue while the full scan is happening. Once it finishes, all artists without albums should have their links removed.

Please confirm this is your case (scan still running)

**Comment by certuna** [comment]
> ive got many errors while moving from 0.49.3 to 0.50.1 like the date formatting not being accepted (example: 10/09/2011)

This is not a bug, your tags have incorrectly formatted dates, they should be in the ISO format `2011-09-10`.

`10/09/2011` is impossible to parse since it could mean either 10 September or 9 October.

**Comment by kobayashi90** [comment]
> `10/09/2011` is impossible to parse since it could mean either 10 September or 9 October.

Alright will ignore this error then.



> Please confirm this is your case (scan still running)

After Scan it fixed itself but newly added albums show all artists being clickable as [shown here](https://www.squidify.org/app/#/album/ec8e567af285e1bb77020f2eecd4363e/show).
Also here is what the logs say
![t5282cmeZi](https://github.com/navidrome/navidrome/assets/51263756/7e0ebe8f-b9b3-4254-8ebe-09cc35ae8e0b)

**Comment by kobayashi90** [comment]
> The "fix" will be importing all artists, as per @certuna's PR. Let's keep this issue open so other people can find it while the PR is not merged.

Any idea when this will be pushed to master?

**Comment by deluan** [comment]
> Any idea when this will be pushed to master?

The PR requires more testing and needs to be checked for conflicts with other ongoing implementations. This may take a couple of months or so.
