### ISSUE TITLE
[Bug]: findMatchingTrack always prioritises tracks that have an annotation (even if annotation is irrelevant)

### ISSUE THREAD

**Issue by metalheim** [navidrome/navidrome#2670]
### Version
0.50.1-SNAPSHOT (cdccdc56)

### Summary:

The `findMatchingTrack` function `getTopSongs` is delivering worse results than it could imho because it always prioritises tracks that **an** annotation, even if the annotation is not relevant.

### Extensive description:

This happens when there is 
1. perfect matching song (Title, Artist, Albumartist, Year)
   - That doesn't have an annotation yet
3. another less perfect matching song (same title, artist, but its on compilation and from a year later than `1.`
   - But this track `2.` has an annotation (becaue i have played it once, but not rated or starred)
   
I guess the reason is that it uses `mediaFileRepository`  -> `GetAll` -> `newSelectWithAnnotation` which in its turn uses a LEFT JOIN of the `media_file` table and the `annotations` table, which results in null values for `rating` and `starred`  if an annotation doesnt exist.

`findMatchingTrack` *ORDER*s by `starred` and `rating` *descendingly*:
https://github.com/navidrome/navidrome/blob/cdccdc56c9072e539b808b998cf9bdfabe864149/core/external_metadata.go#L417

This then puts
track  `2.` (with `rating=0` and `starred=0`) **above**
track `1.` (with `rating=null` and `starred=null`)  

### Expected Behavior

If the annotations aren't relevant for this song (`rating=0` and `starred=0`), dont prioritise "0" over "null".

Im not sure where best to normalise / coalesce 0 the relevant annotation fields - maybe right in `newSelectWithAnnotation` ?

https://github.com/navidrome/navidrome/blob/cdccdc56c9072e539b808b998cf9bdfabe864149/persistence/sql_annotations.go#L22C2-L22C2

### Steps To Reproduce

Let's use the following example:

I want to getTopSongs for Artist "Cher". Among the Top Songs, there is the Song "Strong Enough" from her 1998 Album "Believe".

I have this song in my library multiple times, but 2 examples are enough to reproduce:

1. perfect matching song from the "Album Believe"
   - Title="Strong Enough", Artist="Cher", Year="1998", Compilation=0
   - Has no annotation (because it was never played/rated)
2. another copy from a 1999 "Best Songs of the year" type compilation
   - Title="Strong Enough", Artist="Cher", *Year="1999", Compilation=1*
   - has an annotation "play_count=1, starred=0, rating=0"

As stated above, `findMatchingTrack` takes 2. over 1. because it "has an annotation", even though the annotation shouldnt be relevant imho and 1. is the better match.

Heres the screenshot of SonixD which uses getTopSongs:
![image](https://github.com/navidrome/navidrome/assets/44159957/add800ba-d850-4bc3-a208-86be86ee2ca7)

Heres the 2 songs in navidrome "song list"
![image](https://github.com/navidrome/navidrome/assets/44159957/185b0579-7cc7-4599-88d5-ef9465273833)

As soon as i have a play on the song 1. 
![image](https://github.com/navidrome/navidrome/assets/44159957/3464b17a-fe67-4125-a590-7db2b17de77f)

It does also show correctly in SonixD -> GetTopSongs -> findMatchingTrack 

![image](https://github.com/navidrome/navidrome/assets/44159957/f6ccc651-00d9-490e-8bdb-4b81b88143fd)

### Environment
Docker on Synology NAS, but shouldn't be relevant here...

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by metalheim** [comment]
I tied to manually re-create the SQL query done by newSelectWithAnnotation (roughly, leaving out irrelevant parts).
I could reproduce the exact issue mentioned above in SQL.

When i just use ```sql COALESCE(starred, 0) as starred2``` and 
```sql COALESCE(rating,0) as rating2``` and then use these normalized columns, everything works as expected.

**Comment by deluan** [comment]
Interesting. I'll take a look, thanks for the investigation.

**Comment by deluan** [comment]
I think the best solution here is apply the `coalesce` in the `newSelectWithAnnotation` function. I'll do that and create a draft PR, so you can download it and test.

**Comment by deluan** [comment]
Please test the build from #2675 and let me know the results.

**Comment by metalheim** [comment]
Closing issue as PR #2675 solves it
