### ISSUE TITLE
[Bug]: Play count not working properly

### ISSUE THREAD

**Issue by afermar** [navidrome/navidrome#2672]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.50.1

### Current Behavior

Sometimes the play count does not increase after playing a track. It also happens in the [demo](https://demo.navidrome.org/).

![gif](https://github.com/navidrome/navidrome/assets/99222323/af6a0386-a329-449b-b67e-aff62b958069)

### Expected Behavior

Play count has to increase after a song has been played.

### Environment

```markdown
- OS:
- Browser:
- Client:
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by metalheim** [comment]
I think navidrome has registered the play (at 50% playback) and increased the playcount, just the frontend didnt update it in real time.
When you hit the `⟳` Button in the top right corner, it should update instantly.

**Comment by afermar** [comment]
That was it. Thanks!!
