### ISSUE TITLE
[Bug]: Original date not recognized

### ISSUE THREAD

**Issue by rombat** [navidrome/navidrome#2674]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.50.1

### Current Behavior

![image](https://github.com/navidrome/navidrome/assets/9024503/1387aead-b899-433b-a137-99d70ae62d85)
The second album (20th anniversary edition) has an original date of 2002-10-23, but it does not seem to be taken into account:
![image](https://github.com/navidrome/navidrome/assets/9024503/eac88dc1-481f-4825-b2d3-ed616d923e0c)
Here its complete tag (MediaInfo extract). I just took the first track, but all tracks have the same Date/Release date/Original date:

```
Format                                   : MPEG-4
Format profile                           : Apple audio with iTunes info
Codec ID                                 : M4A  (M4A /mp42/isom)
File size                                : 14.6 MiB
Duration                                 : 6 min 35 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 310 kb/s
Album                                    : ( ) 20th Anniversary Edition
Album/Performer                          : Sigur Rós
Part/Position                            : 1
Part/Total                               : 2
Track name                               : Vaka
Track name/Position                      : 1
Track name/Total                         : 8
Performer                                : Sigur Rós
Composer                                 : Georg Hólm, Jón Þór Birgisson, Kjartan Sveinsson, Orri Páll Dýrason
Genre                                    : Post-Rock
Recorded date                            : 2022-10-28
Encoded date                             : 2022-10-29 17:26:06 UTC
Tagged date                              : 2022-10-29 17:26:10 UTC
Copyright                                : © 2022 KRUNK
Cover                                    : Yes
Comment                                  : Sigur Rós’s third album, and for many the most quintessentially “Sigur Rós” record, celebrates its 20th anniversary on October 28, 2022. The album has been remastered by legendary mastering engineer Ted Jenson at Sterling Sound, who also mastered every Si
Encoding Params                          : (Binary)
ORIGINAL YEAR                            : 2002
MusicBrainz Album Type                   : album
MusicBrainz Album Status                 : Official
MusicBrainz Album Comment                : 2022 Remaster
MusicBrainz Album Id                     : 0d88596f-474d-47a0-bc2d-9987b8261621
LABEL                                    : Krúnk
pub                                      : Krúnk
MEDIA                                    : Digital Media
Album Artist Credit                      : Sigur Rós
Artist Credit                            : Sigur Rós
MusicBrainz Work Id                      : 24e4d95f-3ccd-319c-8dc3-108988275a7c
MusicBrainz Release Group Id             : 950a650b-1e8d-3097-92af-9f7686bba4f1
MusicBrainz Release Track Id             : aa591f4c-83fd-4e3a-b163-3072a173ff30
MusicBrainz Track Id                     : dcae22f5-ea8a-4b2a-b64f-bfec8460e450
MusicBrainz Album Artist Id              : f6f2326f-6b25-4170-b89d-e235b25508e8
MusicBrainz Artist Id                    : f6f2326f-6b25-4170-b89d-e235b25508e8
ORIGINALDATE                             : 2002-10-23
LYRICIST                                 : Georg Hólm, Jón Þór Birgisson, Kjartan Sveinsson, Orri Páll Dýrason
SETSUBTITLE                              : 20th Anniversary Edition
RELEASETIME                              : 2022-10-28
```

### Expected Behavior

it should be displayed just like Ágætis byrjun and its 20th anniversary edition:
![image](https://github.com/navidrome/navidrome/assets/9024503/f4f84fb4-0ea4-4462-b0b3-b125abfd8995)
![image](https://github.com/navidrome/navidrome/assets/9024503/765881ab-0278-45a9-969d-33e1e17828e3)

### Steps To Reproduce

I don't know, so far I've only identified this anomaly. I can provide files if necessary

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by telekineticyeti** [comment]
I can confirm that I am seeing the same (if not similar) behaviour:
<img width="827" alt="image" src="https://github.com/navidrome/navidrome/assets/2192465/e3521ca4-dba3-4649-b5f2-8a24e82ff98c">

<img width="832" alt="image" src="https://github.com/navidrome/navidrome/assets/2192465/b93c8c73-e725-4461-9117-5b4e77bb1a96">
<img width="704" alt="image" src="https://github.com/navidrome/navidrome/assets/2192465/909935b3-84f3-4a33-aa1e-8482a25365ba">

Seems to be causing a lot of albums in the library to look duplicated, however the duplications contain no tracks. Here's a portion of the logs on albums where this is happening:

```
time="2023-12-01T16:36:28Z" level=warning msg="Error parsing originaldate field for year" date=0000 file="/music/_Videogame Soundtracks and Covers/Altercation Compilation/41 - Zircon - Satsui no Koto.mp3"

time="2023-12-01T16:36:28Z" level=warning msg="Error parsing originaldate field for year" date=0000 file="/music/_Videogame Soundtracks and Covers/Altercation Compilation/44 - H3xal1te - K0mbat.mp3"

time="2023-12-01T16:36:28Z" level=warning msg="Error parsing originaldate field for year" date=0000 file="/music/_Videogame Soundtracks and Covers/Altercation Compilation/07 - MegaDriver - Tr00ibe (Street Fighter II_ Blanka Theme).mp3"

time="2023-12-01T16:36:28Z" level=warning msg="Error parsing originaldate field for year" date=0000 file="/music/_Videogame Soundtracks and Covers/Altercation Compilation/13 - Minibosses - Guile.mp3"

```

**Comment by metalheim** [comment]
> I can confirm that I am seeing the same (if not similar) behaviour, Version 0.50.1: <img alt="image" width="827" src="https://private-user-images.githubusercontent.com/2192465/287326612-e3521ca4-dba3-4649-b5f2-8a24e82ff98c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NTE1NzMsIm5iZiI6MTcwMTQ1MTI3MywicGF0aCI6Ii8yMTkyNDY1LzI4NzMyNjYxMi1lMzUyMWNhNC1kYmEzLTQ2NDktYjVmMi04YTI0ZTgyZmY5OGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDFUMTcyMTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDE3ZTZiNzViZWQ2NDdhNzM1MjU3YWRkYWZjODU1ZGZkMzFkZjc0MjJlYjkwODFmNTY2YWE5YmZjYjQ3Nzg1MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.s6uf58RoXoim_OlwxB3Rk1PYCz1IcY5WaEk24yMbKjU">
> 
> <img alt="image" width="832" src="https://private-user-images.githubusercontent.com/2192465/287326478-b93c8c73-e725-4461-9117-5b4e77bb1a96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NTE1NzMsIm5iZiI6MTcwMTQ1MTI3MywicGF0aCI6Ii8yMTkyNDY1LzI4NzMyNjQ3OC1iOTNjOGM3My1lNzI1LTQ0NjEtOTExNy01YjRlNzdiYjFhOTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDFUMTcyMTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2JhMWFmNzViOWNmMzA3NDJkYzQ0ODQyNTE3ZDZiNTdkOTEyMWQ2YmY0MzEyMWUyODI0OWZjYzllM2IyZThhOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6-Nt9012pww7JBkLAJyB5GmWHaVBJy__gtJUp7tNj6I"> <img alt="image" width="704" src="https://private-user-images.githubusercontent.com/2192465/287326518-909935b3-84f3-4a33-aa1e-8482a25365ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NTE1NzMsIm5iZiI6MTcwMTQ1MTI3MywicGF0aCI6Ii8yMTkyNDY1LzI4NzMyNjUxOC05MDk5MzViMy04NGYzLTRhMzMtYWExZS04NDgyYTI1MzY1YmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDFUMTcyMTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjlkNDdmMWY3YTY1NzYyNTZhZjI5ZjYwY2MxZmQ2YjhhN2NhN2NiMTJhMzE5OTBlMzJhNDdhNDdjOTNkYmYyYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gY6FmvI_iiqk9ZSRbL5NEGlpBC5-RwXfTi7N8GHRdSQ">
> Seems to be causing a lot of albums in the library to look duplicated, however the duplications contain no tracks. Here's a portion of the logs on albums where this is happening:
> 
> ```
> time="2023-12-01T16:36:28Z" level=warning msg="Error parsing originaldate field for year" date=0000 file="/music/_Videogame Soundtracks and Covers/Altercation Compilation/41 - Zircon - Satsui no Koto.mp3"
> 
> time="2023-12-01T16:36:28Z" level=warning msg="Error parsing originaldate field for year" date=0000 file="/music/_Videogame Soundtracks and Covers/Altercation Compilation/44 - H3xal1te - K0mbat.mp3"
> 
> time="2023-12-01T16:36:28Z" level=warning msg="Error parsing originaldate field for year" date=0000 file="/music/_Videogame Soundtracks and Covers/Altercation Compilation/07 - MegaDriver - Tr00ibe (Street Fighter II_ Blanka Theme).mp3"
> 
> time="2023-12-01T16:36:28Z" level=warning msg="Error parsing originaldate field for year" date=0000 file="/music/_Videogame Soundtracks and Covers/Altercation Compilation/13 - Minibosses - Guile.mp3"
> ```

For the "duplicate Album" issue: you need to wait for a full scan to finish

**Comment by telekineticyeti** [comment]
> 
> For the "duplicate Album" issue: you need to wait for a full scan to finish

My bad! Please disregard my previous comment.

**Comment by certuna** [comment]
That's strange indeed, this looks OK in the tags:
`ORIGINALDATE                             : 2002-10-23`
can you send me the file (either through Discord, or if you can provide a link)?

**Comment by rombat** [comment]
@certuna thanks !
The weird thing is that both "anniversary edition" albums were m4a files, tagged the same way as far as I know.
But if it will be fixed, then that's ok for me 👍🏼
