### ISSUE TITLE
[Bug]: Missing x86_64 release for 50.1

### ISSUE THREAD

**Issue by Fyrd** [navidrome/navidrome#2682]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

N/A

### Current Behavior

Under the [50.1 release assets](https://github.com/navidrome/navidrome/releases/tag/v0.50.1) (and the 50.0 release) the x86_64 release is missing.

Last appeared for [v0.49.3](https://github.com/navidrome/navidrome/releases/tag/v0.49.3).

I mostly bring this up because this is the release that's used in the example for linux installations:
https://www.navidrome.org/docs/installation/linux/#get-navidrome

### Expected Behavior

Asset for x86_64 should be included.

### Environment

```markdown
- OS:
- Browser:
- Client:
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
Sorry, there was a change in the assets naming (see [#2673](https://github.com/navidrome/navidrome/issues/2673#issuecomment-1836995576)) and I forgot to change the docs. The new name is [navidrome_0.50.1_linux_amd64.tar.gz](https://github.com/navidrome/navidrome/releases/download/v0.50.1/navidrome_0.50.1_linux_amd64.tar.gz)

I'll fix the docs ASAP.

Thanks for reporting!

**Comment by Fyrd** [comment]
Ah, I understand now. Thanks!
