### ISSUE TITLE
[Bug]: Cover art suddenly missing

### ISSUE THREAD

**Issue by phw** [navidrome/navidrome#2692]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

v0.50.1

### Current Behavior

Cover art cache files randomly get missing. I can have all cover art for all albums show up on one day, and on the next some cover art seemingly randomly is not show up. Loading the file's URL in a new tab will show an error about missing cache file:

```json
{"subsonic-response":{"status":"failed","version":"1.16.1","type":"navidrome","serverVersion":"0.50.1 (f69c27d1)","openSubsonic":true,"error":{"code":0,"message":"Internal Server Error: open /data/cache/images/5f/1a/5f1a7573e708b43c06a73336760f67e51fc667f5: no such file or directory"}}}
```

Restarting navidrome heals the issue.

### Expected Behavior

Cover art stays available

### Steps To Reproduce

Unsure how to reproduce. I have this issue for a while, but never reported it as I have no clear way of triggering the issue intentionally.

But this happens without interaction. E.g. I can do a fresh reset of everything (rescan the library to make sure it is up-to-date, stop navidrome, delete the files in data/cache/images, clear the browser cache). After starting navidrome it regenerates the cache images, all the cover art images show up.

Even without doing anything rechecking a day later might show missing cover art files. The majority of cover art will still be there, it is just some random entries.

### Environment

```markdown
- OS: Ubuntu Linux, docker container
- Browser: all (Firefox, Chromium)
- Client: n/a
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by phw** [comment]
This might actually have been the case. I just checked, and the cache folder was indeed 100MB in size which was the same as the limit. I have bumped it up to allow up to 1GB, I'll report back whether this solves the issue.

Anyway, wouldn't this still be a bug when it leads to broken image display? Shouldn't a requested image get generated if it is not in the cache, probably replacing the oldest one in the cache?

Or maybe this even happens, but then because all images where replaced at the same time it can happen that the oldest image getting pruned just happens to be another album image that is supposed to be displayed on the same listing page. That would be difficult to avoid :(

**Comment by metalheim** [comment]
> Anyway, wouldn't this still be a bug when it leads to broken image display? Shouldn't a requested image get generated if it is not in the cache, probably replacing the oldest one in the cache?

Yes that should be the correct behaviour!
I just wanted to narrow down the issue so far

**Comment by phw** [comment]
Just to give some numbers: Originally image cache was at default 100 MB. Now after increasing the limit the cache folder has grown to ~210 MB.

That would roughly mean that only half the images could be kept in cache. (of course different sizes, and there are probably a few that are larger then average, so I'd expect more then half in cache). Which would fit very well into my observation of missing covers when looking through the album list.

**Comment by deluan** [comment]
My understanding is that because the cache size was too small for your library, there was too much churn in the cache (remove/add files). Looks like you hit a race condition where the cache checked if the file was available before it was deleted, then tried to read it after it was deleted. The cache library we use should take care of these type of race conditions, but I'll take a look whenever I have time (not anytime soon) and try to reproduce it.

**Comment by sergio-ns** [comment]
Same issue here, many cover art images have disappeared all of a sudden, replaced by the stock image. I have bumped the cache size to 1GB with:
`ImageCacheSize = "1GB"`
cleared the browser cache, tried different browsers to no avail.

**Comment by barbartibal** [comment]
Reporting in for the same issue. The setup resembles OP´s specs. The behavior also started out of the blue without singnificant changes to the media Navidrome is handling. Happenens on FF, Edge and Chrome.

**Comment by sergio-ns** [comment]
Turned out that in my case the cover art images were missing because the Last.fm API key and secret were not configured correctly and in the right place. After fixing this, the images came back.
