### ISSUE TITLE
[Bug]: In Jukebox mode, filenames sent to mpv are not escaped at all, so can't be played by mpv/dac

### ISSUE THREAD

**Issue by etsiot** [navidrome/navidrome#2707]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.50

### Current Behavior

In Jukebox mode, filenames sent to mpv are not escaped at all, so can't be played by mpv/dac

Log below:
Dec 15 14:20:57 navidrome navidrome[4152]: time="2023-12-15T14:20:57+02:00" level=info msg="Found mpv" path=/usr/bin/mpv
Dec 15 14:20:57 navidrome navidrome[4152]: time="2023-12-15T14:20:57+02:00" level=debug msg="Executing mpv command" cmd="[/usr/bin/mpv --audio-device=alsa/default:CARD=A20 --no-audio-display --pause /mnt/music/_Staging/VA - Rolling With Punches - The Allen Toussaint Songbook (2012)/06. Don Covay - Everything I Do Gonh Be Funky (From Now On).flac --input-ipc-server=/tmp/mpv-ctrl-d444f9dc57b2fcd79cfc394ee311cf52.socket]"

### Expected Behavior

Filenames should be escaped so mpv can play them

### Steps To Reproduce

Enable jukebox mode
Provide the mpv alsa device in config
Play file from Ultrasonic in android, being in jukebox mode

### Environment

```markdown
- OS: Debian 11
- Browser: 
- Client: Ultrasonic
```

### How Navidrome is installed?

Package

### Configuration

```toml
MusicFolder = "/mnt/music"
Jukebox.Enabled = true
MPVPath = "/usr/bin/mpv"
Jukebox.Devices = [  
    [ "dac",          "alsa/default:CARD=A20" ]
]
Jukebox.Default = "dac"
LogLevel = "DEBUG"
```

### Relevant log output

```shell
Dec 15 14:20:57 navidrome navidrome[4152]: time="2023-12-15T14:20:57+02:00" level=info msg="Found mpv" path=/usr/bin/mpv
Dec 15 14:20:57 navidrome navidrome[4152]: time="2023-12-15T14:20:57+02:00" level=debug msg="Executing mpv command" cmd="[/usr/bin/mpv --audio-device=alsa/default:CARD=A20 --no-audio-display --pause /mnt/music/_Staging/VA - Rolling With Punches - The Allen Toussaint Songbook (2012)/06. Don Covay - Everything I Do Gonh Be Funky (From Now On).flac --input-ipc-server=/tmp/mpv-ctrl-d444f9dc57b2fcd79cfc394ee311cf52.socket]"
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by etsiot** [comment]
Running mpv directly from terminal,  I can play the file to the DAC when filename is escaped

**Comment by deluan** [comment]
Thanks for reporting, but this is not the issue. The paths are escaped, it just not appear like  they are in the logs. I just tried locally and I was able to play normally a path with spaces:
```
DEBU[0029] Executing mpv command                         cmd="[/opt/homebrew/bin/mpv --audio-device=auto --no-audio-display --pause music/Imagine Us/01-1685828-Back On Earth-For Us Tonight.mp3 --input-ipc-server=/var/folders/qj/3dm_yqfn27dbm1hrpl9jr7jc0000gn/T/mpv-ctrl-af42c344a7e714d1a187507fb115eac5.socket]"
```

If it was not able to play, it would show a ERROR log message, not DEBUG. To be able to figure this out, we need more logs. There should be an ERROR log message near the one you posted.

**Comment by etsiot** [comment]
Thanks for checking this out. You are right, tried again and I see the following socket error
`Dec 17 21:45:30 navidrome navidrome[8463]: time="2023-12-17T21:45:30+02:00" level=error msg="error or timeout waiting for control socket" error="timeout reached: 3s" socketname=/tmp/mpv-ctrl-b97e2d580831a9a97a138c8d730eae9a.socket `

**Comment by deluan** [comment]
This seems to be related to a bug in Ultrasonic, that is currently blocking it to work with Navidrome (and maybe other servers?): https://gitlab.com/ultrasonic/ultrasonic/-/issues/1266

Please follow that issue for updates. I'll close this but feel free to chime in if you have other concerns.
