### ISSUE TITLE
[Bug]: Navidrome Splitting Albums (not the FAQ issue)

### ISSUE THREAD

**Issue by dathbe** [navidrome/navidrome#2728]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.50.2 (823bef54)

### Current Behavior

Importing albums frequently results in a single album being split into multiple albums:
![2023-12-19 11_38_27-Navidrome — Mozilla Firefox](https://github.com/navidrome/navidrome/assets/14321825/607de5db-287b-41c0-bb59-62ee642310e9)

### Expected Behavior

Albums with consistent tagging should appear as a single album.

### Steps To Reproduce

1. Add album to media folder
2. Scan
3. Multiple albums appear

### Environment

```markdown
- OS: Docker (Debian)
- Browser: Firefox
- Client: Web interface
```

### How Navidrome is installed?

Docker

### Anything else?

I have confirmed that The "Album Artist" is the same across all tracks, "Artist" it the same across most tracks (even those that are split out), and there are no weird "compilation" tags (see [here](https://github.com/navidrome/navidrome/issues/709#issuecomment-753512963)).

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by dathbe** [comment]
Update on this.  I was also pointed to the ReleaseDate tag in song files as that can pose issues.  While I can't find any differences in that tag among the songs that are getting split out (in fact, I don't see that tag being set in any of the affected files), I was able to set the Docker environment variable ```ND_SCANNER_GROUPALBUMRELEASES=true```, and that seems to have fixed the issue.  I still can't figure out why the app is picking up my albums as being multiple releases, though.

**Comment by 0bmay** [comment]
are there multiple file formats? like a mixture of mp3, ogg, Flac etc?

**Comment by deluan** [comment]
Maybe the release dates are different? By default, Navidrome splits albums by release dates, to avoid merging different releases into one. See https://github.com/navidrome/navidrome/discussions/2668

**Comment by dathbe** [comment]
> are there multiple file formats? like a mixture of mp3, ogg, Flac etc?

Nope.  All are m4a.

> Maybe the release dates are different? By default, Navidrome splits albums by release dates, to avoid merging different releases into one. See #2668

I'm not seeing a "release date" tag (I've looked in mp3tag, MusicBrainz Picard, and iTunes).  If you have a rec on software that will show me all tags, I will check.  Picard did show an "original release date", which is the same on all songs in the album.

**Comment by deluan** [comment]
Check the all date tags (`date`, `year`, `originaldate`, `releasedate`, etc...). They must **all** match. As discussed in #2668, you can also set `Scanner.GroupAlbumReleases` to `true` if you don't have multiple releases of the same album in your collection.

**Comment by dathbe** [comment]
> (`date`, `year`, `originaldate`, `releasedate`, etc...). They must **all** match.

I mean, that can's possibly be right, can it?  I get why people would want to split by releasedate, but "date" is different from song to song all the time.  What about Greatest Hits albums where the songs come from across decades of standard albums?  I will use eyed3 when I have a minute and report back on what tags are different among the songs.

**Comment by deluan** [comment]
Yes, you are right, `Date` and `Year` will not split albums.

A quick way to validate if the dates are the issue is just setting `Scanner.GroupAlbumReleases=true`, restartind Navidrome and  checking if the split still happens. If it does, then releasedate/releaseyear or originaldate/originalyear maybe be not be matching.

**Comment by dathbe** [comment]
I have already fixed my immediate issue using ```Scanner.GroupAlbumReleases=true``` (or, more technically, ```ND_SCANNER_GROUPALBUMRELEASES=true``` since I am using Docker.  This DOES fix the issue.  And I don't personally care to have different "releases" split into different albums.  I have all my albums named uniquely to the extent I want them separated (e.g., "Greatest Hits [Artist Name]".

I'm mostly just trying to bug squash at this point, so here's what I've found.

The issue DOES seem to be related to the ```Year``` tag.  When I use mp3tag to set the ```Year``` to be the same for all of the songs in one of the affected albums, they combine into one album within Navidrome.  

The most baffling thing about this is that I then went back to a Greatest Hits album that has the ```Year``` tagged differently for each song, and it did NOT split that album.  So it's only _sometimes_ splitting an album based on ```Year```???  

I'm going to do a bit more searching to see if I can figure out any differences between those albums that are affected and those that are not, but it does have at least something to do with the ```Year``` tag.

**Comment by dathbe** [comment]
I'm at a loss.  I found an album that is itself illustrating the problem, and it's just baffling.

The songs as I have them have three ```Date``` tags according to MusicBrainz Picard.  This seems to be the same as the ```Year``` tag in mp3tag:

1. "1973"
2. "2000-09-26"
3. "1974"

When I load these songs into Navidrome, 1 and 3 combine into a single album.  2 goes into it's own album.

If I update #2 to be "1976" (all tagging done in mp3tag), they all group into the same album.  I seem to be able to set it to anything from <blank> to 1 to 1999 and it will group it with the other two.  But if I set it to 2000 or greater, it will split it out.  

Here's where it gets really weird.  If I set #2 to be, say, 2005, it STILL shows up in Navidrome as being "Year" 2000.  If I set all three to 2005, all three songs are grouped in the same album, but all three show up as the "Year" 2000.  If I set two of them to 2005 and the last to 2010, they split into two albums, but they all say "Year" 2000 within Navidrome.

I'm just spitballing here, but there seems to be a second date field that Navidrome is pulling from conditionally.  Perhaps it is pulling the earlier of the two dates?  And somehow it has some complicated ruleset for determining whether to split the songs?  If it pulls all three from the "Year"/"Date" field, it will allow grouping even if the the date is different.  But the second it starts pulling from this mystery second field, it gets very particular???

**Comment by dathbe** [comment]
More possibly useful info:

The original album I was having issues with (_Lover_, screenshot above) was an issue with how Navidrome handles the ```Year``` field as well.

All songs in the album have an ```Original Release Date``` of "2019-08-23" and an ```Original Year``` of "2019".  But they have different ```Date``` (MusicBrainz Picard field naming) with the following values:

1. 2019-08-23T07:00:00Z (tracks 1-2, 4, 6-13, 15, 17-18)
2. 2019-08-16T07:00:00Z (track 3)
3. 2019-07-23T07:00:00Z (track 5)
4. 2019-06-14T07:00:00Z (tracks 14)
5. 2019-04-26T07:00:00Z (tracks 16)

Know that I did not enter these values, so I believe these were coded by whoever sold me the songs (probably Apple since these are m4a files). 

Perhaps unsurprisingly given my findings above, it is these 5 groupings that show up as 5 different albums in Navidrome DESPITE the fact that all the songs have the same release date.

Even if I remove the "T07...." time information, the album is still split based on the ```Year```/```Date``` tag.  

Once again, if I set the ```Date``` to anything before 2019 (specifically, 1 Jan 2019), it will group the songs together.  This is true whether I set just the year, the year and date, or the year and date and time.  So "2018" works, but "2019" does not.  "2018-12-31" but not "2019-01-01".  "2018-12-31T11:59:59Z" but not "2019-01-01:00:00:00Z".

So it does seem to be related to whether it considers the ```Date``` or ```Original Release Date``` (or possibly ```Original Year```) to be earlier.  And then does some weird things where it thinks the ```Date``` is after the "original" date.  

I suspect this is not intended behavior.

**Comment by deluan** [comment]
So this is the logic used to map dates from tags:

https://github.com/navidrome/navidrome/blob/a6ed0442f2f4ccd7c6fe5d0efb9b6f7a9db05bc4/scanner/mapping.go#L177-L201

And then, `releaseDate` is used to disambiguate albums, here:
https://github.com/navidrome/navidrome/blob/a6ed0442f2f4ccd7c6fe5d0efb9b6f7a9db05bc4/scanner/mapping.go#L130-L138

I think @certuna can explain the decisions in these mappings a bit more in depth. I know most of it is related to a bug in Picard he was investigating. Maybe that's the part that is getting you?

**Comment by dathbe** [comment]
I have a hunch I've found the problem.  I'm not exactly sure what each line of code means, but it seems to be making the Picard correction when the ```year``` (aka date) is greater than OR EQUAL TO the originaldate.  This seems to be causing problems for me.  Because I think it sees my songs that have different ```data``` but same ```originalyear``` that are all within the same year to overwrite the ```originaldate``` with the ```year``` and then decide whether to break up the album.  So I think changing this line ```(year >= originalYear) ``` to ```(year > originalYear) ``` will fix the problem I'm seeing because it will leave my dates intact if they are sensible (i.e., the song is not tagged to have been made after the album was released).  Now, I don't know if this will cause some other problem that this code was designed to fix in the first place.  But I think this is the issue I'm experiencing.  

Stated another way, when song has ```date``` 2019-08-23 and ```originaldate``` 2019-08-22, this code says to group by ```date``` instead of ```originaldate``` which breaks being able to code an entire album by ```originaldate``` and expect it to be considered a single album.

**Comment by certuna** [comment]
OK apologies for the delay, here goes:
- the reason that the TaggedLikePicard logic is in there, is because Picard puts dates in the wrong fields: it puts the date that should be in `releasedate` (the re-release date of the album) in `date`, which is a field that's supposed to hold the _recording date_. Because ND sorts by `date` (it's the most logical date to sort on), this means those albums get sorted wrong, often decades later.
- to correct for this, ND tries to 'intelligently' detect when this happens (`originaldate` < `date`, no `releasedate`), and re-maps `date` to `releasedate`, and `originaldate` to `date` (which is the one we sort on)
- in your case however, your files are not 'wrongly tagged like Picard' but the 'intelligence' makes the mistake to map your date to `releasedate` even though it shouldn't.

>  Does it really come up that there are multiple releases within the same year?

Yes, a lot. Just have a look around in musicbrainz.org , you'll see tons of them. US/European releases with different tracklists, Japanese editions with bonustracks, various versions of singles with different remixes.

> Remove the Picard Maneuver entirely. How many people are tagging their music with the expectation that it's going to group albums by releasedate without ACTUALLY adding a releasedate tag??

A lot, because if you tag with Picard, you have put the release date in `date`, and you would expect albums to be disambiguated by that. So you *have* to remap it.

There's a few solutions I see:
- you manually tag your files with a `releasedate` (in any tag editor, mp3tag/Picard/Yate/kid3/etc).
- we introduce stricter detection of TaggedLikePicard: we could for example check if there's an MbzAlbumID tag, if there is none we don't do the `date` -> `releasedate` remapping
- remove grouping by `releasedate` entirely, and only group by Musicbrainz Album ID. That's nice if you are a big Picard/MBZ user, but what about the millions of releases that are not in the MBZ database?

**Comment by dathbe** [comment]
Does changing ```>=``` to ```>``` work?  This would more accurately catch those who are blindly tagging with Picard (releasedate for this version is after the originaldate for the first time the album was released), but not people who are being more discerning like me (date for this recording is the same as the originaldate for the first time the album was released).

Also, what is the exact name of the tag that needs to be set?  I'm not having any luck getting my tracks to combine into a single album by setting ```releasedate```.  The code above uses ```releaseYear```, but that seems to be a variable name and not necessarily the tag name.

**Comment by dathbe** [comment]
I'm still not getting expected results, even after fixing tags:
I have set a ```releasedate``` tag for all songs, and it is the same for all songs:
![2023-12-21 12_06_03-Tags](https://github.com/navidrome/navidrome/assets/14321825/6bc9ae95-96a3-4a4c-93c1-5f14e25cb756)
This has been confirmed in both mp3tag (where the image is from and Picard.  
The ```date``` tag (Picard terminology)/```year``` tag (mp3tag terminology) is different from song to song, and ND continues to split the album based on ```date```/```year```.

Is there a separate release year tag I need to set (setting ```releaseyear```, ```releaseYear```, ```release_year```, and ```release_Year``` did nothing)?

**Comment by certuna** [comment]
> I like the third option. Obviously it would be up to the devs to implement group by MBZ ID, but this would seemingly be more accurate. And to your concern that it will give a wrong sorting date, if someone is putting a date in `date`, they should expect the song to sort by that date. That's the way every other system I've seen does it, and users can't really expect anything else. In fact, they would probably be unhappy if songs were sorting by something else.

No, this is the problem. For songs tagged with Picard (there's billions out there), people will expect the sort date to be `originaldate`. Think of a 2005 reissue of the 1973 album "Dark Side Of The Moon". Picard will tag this `originaldate` = 1973, `date` = 2005. Users expect this to be sorted as a 1973.

> Also, what is the exact name of the tag that needs to be set?

`TDRL` in id3v2.4, `RELEASEDATE` in FLAC. These two are mapped by TagLib to the generic tag `releasedate`

**Comment by dathbe** [comment]
Further experimenting suggests this might be an issue specific to the way ND handles m4a files.

**Comment by dathbe** [comment]
After further investigation, this seems to be related to 
https://github.com/navidrome/navidrome/issues/2679
and
https://github.com/navidrome/navidrome/issues/2674

And is hopefully fixed by
https://github.com/navidrome/navidrome/pull/2680

I'll check once #2680 makes it into the the latest Docker build.

**Comment by mneuburg-livefront** [comment]
> I figured out why there isn't an uproar about this issue that I seem to be the only one experiencing

Actually I've been having this issue too, for several weeks now; the problem was so intractable that I reverted to an earlier release of Navidrome and deleted my database. I'm really glad to see it being worked on so diligently. Thanks for persevering.

**Comment by 0bmay** [comment]
> > I figured out why there isn't an uproar about this issue that I seem to be the only one experiencing
> 
> Actually I've been having this issue too, for several weeks now; the problem started with release 0.50.0 and was so intractable that I reverted to an earlier release of Navidrome and deleted my database. I'm really glad to see it being worked on so diligently, as a fix will permit me to resume updating to newer releases. Thanks for persevering.

I am affected by the issue too.  Usually it's a mixed mode album where I have mp3 and m4a's of the same album but different tracks.  I lost my library when a computer crashed a few years ago, but I was using iTunes Match at the time, so I was able to recover everything, but now some albums are fixed file formats. I didn't want to go through the hassle of re-ripping 1,000s of CD's.  At first I used the ENV setting to merge them, but I figured it would be better for the long run to make the metadata match and have been using Picard to fix everything (also updating the year when it is wrong).   I have been watching this thread.. so thanks all for reporting and tinkering...

**Comment by Tomosawa** [comment]
I have an album like this, where some songs have different artist names, but all these songs belong to the same album. So, I examined this piece of code and found it unable to successfully differentiate this situation. According to this code logic, as long as there are different artist names, they will be split into different albums. There is a logic issue here that needs to be addressed by fixing the code.

https://github.com/navidrome/navidrome/blob/6f7b48202e9135378f3696f28b8f49595f8a8f75/scanner/mapping.go#L130C1-L139C1

I think this piece of code should be modified as follows:
`func (s MediaFileMapper) albumID(md metadata.Tags, releaseDate string) string {
	if !conf.Server.Scanner.GroupAlbumReleases {
		if len(releaseDate) != 0 {
			albumPath = fmt.Sprintf("%s\\%s", albumPath, releaseDate)
		}
	} else {
		albumPath := strings.ToLower(fmt.Sprintf("%s\\%s", s.mapAlbumArtistName(md), s.mapAlbumName(md)))
	}
	return fmt.Sprintf("%x", md5.Sum([]byte(albumPath)))
}`

**Comment by dathbe** [comment]
Albums with multiple “artists” will sort together. You just need to make sure that the “album artist” is the same for the whole album. If you have a true compilation, you can use something like “Various Artists” for the album artist. I would think splitting by album artist (or artist if there is no album artist) would be the preferred method so that two “Greatest Hits” albums from two different artists don’t merge.

**Comment by Tomosawa** [comment]
> Albums with multiple “artists” will sort together. You just need to make sure that the “album artist” is the same for the whole album. If you have a true compilation, you can use something like “Various Artists” for the album artist. I would think splitting by album artist (or artist if there is no album artist) would be the preferred method so that two “Greatest Hits” albums from two different artists don’t merge.

I understand. I apologize for not noticing the additional 'Album Artist' field, aside from the 'Album' and 'Artist' fields. I've observed that songs categorized incorrectly often only have information in the 'Album' and 'Artist' fields, while the 'Album Artist' field is empty. Is there a way to group these songs into the same album solely based on the similarity of the 'Album' field?

**Comment by dathbe** [comment]
You could try the GroupAlbumReleases setting mentioned above to see if it does what you need, but it may not. You may need to tag affected albums with an Album Artist. You could probably write a short script to take the artist from the first song in each folder (aka album) of your collection and populate it into the album artist field.

**Comment by Tomosawa** [comment]
> You could try the GroupAlbumReleases setting mentioned above to see if it does what you need, but it may not. You may need to tag affected albums with an Album Artist. You could probably write a short script to take the artist from the first song in each folder (aka album) of your collection and populate it into the album artist field for all songs in that folder. Or if you really wanted to be crazy, you could use a tool like mp3tag or MusicBrainz Picard to add the same album artist to EVERY track in your collection.

I understand, although modifying EVERY track  would be quite troublesome, there isn't a better solution for now. I will try to do this. Thank you very much for your patient response.

**Comment by certuna** [comment]
> Is there a way to group these songs into the same album solely based on the similarity of the 'Album' field?

That won't work, you'll have every album called "Greatest Hits" grouped as one album.

**Comment by dathbe** [comment]
I can confirm that version [0.51.0](https://github.com/navidrome/navidrome/releases/tag/v0.51.0) (fd61b29a) fixes this on my setup.  Thanks for everyone's help.
