### ISSUE TITLE
[Bug]: artist images not being sent to symfonium app

### ISSUE THREAD

**Issue by rightsaidfred99** [navidrome/navidrome#2751]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

v0.50.2

### Current Behavior

A few years ago, this would work. Now all artist images are blank

### Expected Behavior

I use last.fm and also local artist.jpg images. While the last fm image fetching doesn't work at all (a seperate bug), the artist.jpg images do get used by navidrome. 

The problem it is it never gets passed downstream to symfonium app on android. 

### Environment

```markdown
- OS:
- Browser:
- Client:
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by TheRedSpy15** [comment]
What was the solution?

**Comment by rightsaidfred99** [comment]
In symfonium, I removed navidrome as the provider. Then reconnected it and it seemed to have worked only then. I can only assume I hadn't done this for over a year and a bit and things obviously change in the background, so perhaps that's all it was.

**Comment by tepiloxtl** [comment]
I think its worth noting my experience here. I had set up Symfonium with my Navidrome server on a new device this morning, and then configured Navidrome to pull artist images from Spotify in the evening, and Symfonium would still be unable to pull them until I removed and reconnected the provider again, so theres definitely some state change that one or either doesn't seem to handle well

**Comment by TheRedSpy15** [comment]
> I think its worth noting my experience here. I had set up Symfonium with my Navidrome server on a new device this morning, and then configured Navidrome to pull artist images from Spotify in the evening, and Symfonium would still be unable to pull them until I removed and reconnected the provider again, so theres definitely some state change that one or either doesn't seem to handle well

Agreed, this was the solution for me as well. I want to include that it still didn't work unless my navidrome user was an admin. Incase anyone is experiencing this issue in the future
