### ISSUE TITLE
[Bug]: "Play Similar Songs" on substreamer not working

### ISSUE THREAD

**Issue by JonneSaloranta** [navidrome/navidrome#2766]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

v0.50.2

### Current Behavior

Using Substreamer app Version 6.0.43 on iOS 17.3 to connect to my navidrome server which is working beautifully, but when playing a song and pressing "Play Similar Songs", the "popup" closes and nothing happens.

I'm running navidrome on Docker and i checked the console which was giving me this error

> time="2024-01-04T17:15:46Z" level=warning msg="API: Failed response" endpoint=/rest/getSimilarSongs.view error=70 message="data not found" requestId=4eb2ed69287a/Z3kq7opGwL-000002 username=jonne

![IMG_3954](https://github.com/navidrome/navidrome/assets/72470168/cb7f895f-1d30-43c7-a4b2-d7d104eb24b9)

Not sure if it's a navidrome or a substreamer issue. couldn't find anything related to this on google or in issues expect this issue #2706 which says the song scanning is being reworked. I don't think it has anything to do with this issue.

### Expected Behavior

Should play similar songs

### Steps To Reproduce

1. Play a song in substreamer 2. press on the 3 dots for a popup menu 3. Press "Play Similar Songs"

### Environment

```markdown
- OS:Docker image
- Client: Substream iOS app
```

### How Navidrome is installed?

Docker

### Configuration

```toml
docker-compose.yml


version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "/home/server02/navidrome/data:/data"
      - "/home/server02/jellyfin/music:/music:ro"
```
```


### Relevant log output

```shell
time="2024-01-04T17:15:46Z" level=warning msg="API: Failed response" endpoint=/rest/getSimilarSongs.view error=70 message="data not found" requestId=4eb2ed69287a/Z3kq7opGwL-000002 username=jonne
```

### Anything else?

The navidrome is behind Cloudflare and a nginx reverse proxy if it matters.

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by metalheim** [comment]
getSimilarSongs relies on data from last.fm - you dont seem to have last.fm configured. 

Can you please try to configure the last.fm Integration as explained here in the documentation? https://www.navidrome.org/docs/usage/external-integrations/#lastfm

**Comment by JonneSaloranta** [comment]
This seems to have solved my issue! 👍 Thanks for the quick response.
