### ISSUE TITLE
Add support for Original Date & Release Date tags

### ISSUE THREAD

**Issue by certuna** [navidrome/navidrome#278]
Navidrome currently only reads one date tag: `date` (`TDRC` in id3, `DATE` in FLAC, aka "Recording Date"). There are two more tags:
- `releasedate` (`TDRL` in id3, `RELEASEDATE` in FLAC) 
- `originaldate` (`TDOR` in id3, `ORIGINALDATE` in FLAC)

Support for the `releasedate` tag would be useful: id3-compliant taggers will put the (re-)release date of the album in `releasedate`, which would allow for better distinguishing between different editions of the same album.

Support for the `originaldate` tag would also be useful, since the popular auto-tagger MusicBrainz Picard (mis-)uses this tag to store the release date of the "master" edition of an album, and many users would like to see this field used for sorting albums/tracks chronologically, instead of the `date` tag (where Picard stores the reissue date from years later).

This topic will follow the efforts to implement them in a useful way.

# Update 13 Jan 2023

I think a good way to implement this without any inconvenience to people who don't use these two tags would be as below. This concept does not add any additional complexity to the UI, just a few extra dates to display.

Work in progress is ongoing in this fork: https://github.com/certuna/navidrome

## Serverside (Go)

- [x] new server configuration option `Scanner.GroupAlbumEditions = true/false` (default `true`)
- [x] new columns `date` & `release_date` (date) in `media_file` table
- [x] new columns `date` & `release_date` (date) in `album` table
- [x] scanner: rollup `date` and `release_date` to album level if they're all the same
- [x] count number of different releasedates on an album, and store that as `editions` (int) in the `album` table

Normally, we do like the id3 & Vorbis specs prescribe:
- [x] scanner: `date` tag -> `year`(= already implemented) and `date` (new, full date)
- [x] scanner: `releasedate` tag -> `release_date` (new)

If files are tagged like MusicBrainz Picard does (`originaldate` tag has the 'real' album date, the `date` tag has the (re-)release date, and there's nothing in the `releasedate` tag):
- [x] scanner: `originaldate` -> `year` & `date` (= the date used for sorting/filtering etc)
- [x] scanner: `date` tag -> `release_date`

If `GroupAlbumEditions = true` (default)
- no change to current behaviour, i.e. all tracks that happen to have the exact same album artist + album name ("Alice & Bob - Sing Songs Together") are grouped as 1 album, so the 1997 original and 2005 reissue are 1 album - but with visual dividers, see below.

If `GroupAlbumEditions = false`:
- [x] create a separate albumID for each `releasedate` (i.e. the 2005 reissue and the 1997 original will be two different albums)

### Native API:

- [x] send new fields `date` and `releaseDate`  in the `song` API endpoint
- [x] send new fields `date`, `releaseDate` and `editions` in the `album` API endpoint

### Subsonic API:

- nothing changes

## WebUI (JavaScript)

- Song List: no changes needed
- AlbumGrid: no changes needed
- AlbumList: no changes needed
- Year filter in Album List view: no changes needed
- Now Playing: no changes needed
- [x] AlbumDetails: display in the desktop view like: **♫ 1993-1997 · Released 6 September 2005 · 6 Songs · 35:43 · 48.92 MB** If `year` = `releaseyear`, just display the short form **2005 · 6 Songs · 35:43 · 48.92 MB** (= how it's done now). In the mobile view: **♫ 1993-1997 · ○ 2005 · 6 Songs**
- [x] AlbumSongs: sort album tracklists first by `releaseDate`, then `discNumber`, then `trackNumber`. Use a divider to divide different release versions of the same album, like "1997 Release" -> (tracklist of the 1997 edition) -> "2005 Release" -> (tracklist of the 2005 reissue) - note:  this can only happen when`GroupAlbumEditions = true`, because otherwise, a different release year means a different album.
- [x] AlbumGridView for Artist View: display the release year in the second line under the album cover like:
-  either **2005**, when the release year is not different (= how it's done now)
- or **♫ 1993-1997 · ○ 2005**  when they are not equal
- or **♫ 1993-1997 · ( 3 )))** when there are multiple release dates/editions of the album.

**Comment by deluan** [comment]
How would we support this through the Subsonic API? An option (per user?) to select which year field to report int the API responses?

**Comment by certuna** [comment]
Probably, yes, or just default it to one or the other. There's nothing we can do about the limitations of the Subsonic API...

**Comment by arg274** [comment]
I'd also also like to add that if the original release date is not found, it should fallback to the release date; I pretty much have to add this custom rule to all the other players I use.

**Comment by certuna** [comment]
In **id3v2.4**, there's three date fields defined:

- `TDRL` "Release Date" - explicitly specified as the date of *first* release, but in practice often misused to store the "re-release/re-issue date" (Picard, etc).
- `TDOR` "Original Date" - intended to store the release date of the original version of the song, in the case of covers/remixes/interpretations/etc. So: Nirvana's 1993 cover of David Bowie's "The Man Who Sold The World" would have 1970 in this field. The 1995 Hardfloor remix of New Order "Blue Monday" would have 1983 there, the year of the original "Blue Monday". But: in practice, this is not how this field is used by many taggers/players (Picard, for one). They store the "first release date" in this field instead. People seem to like it.
- `TDRC` "Recording Date" - self-explanatory, rarely used though

**Vorbis comments** (FLAC) are a total free-for-all, there's no formal specifications. The [Xiph specs](https://xiph.org/vorbis/doc/v-comment.html) only suggest a DATE field, to store the "Recording Date". In practice, everyone stores the "re-release date" there, and uses `ORIGINALDATE` (for "first release date") and `RECORDINGDATE` ("recording date").

So since there's two competing definitions for "release date" (date of first release, or re-release?) and "original date" (date of the original version of the song, or first release date?), how will Navidrome use/display this?

My proposal:
- internally in the ND db, store *four* date fields: `original version release date`, `recording date`, `first release date`, `re-release date`)
- allow the user to map id3/Vorbis tags to those, depending on which definition you like. Default should probably be how Picard does it.
- read the tags
- perform data validation check: `original version release date` ≤ `recording date` ≤ `first release date` ≤ `re-release date` (to be decided: what to do when it doesn't work?)
- auto-fill all blank fields
- in the navidrome UI, the standard sorting-by-date uses `first release date`. This field should probably also be the one used for subsonic API.

**Comment by deluan** [comment]
@certuna Thanks for the detailed investigation. Yeah, I think your suggestion make sense. Will probably base the implementation on that.

**Comment by certuna** [comment]
Note: having this fourth field for "original versions released" would be valuable for querying/browsing classical music, opera, jazz etc where there's a strong emphasis on interpretations of "standards" and historic compositions.

**Comment by SteveDinn** [comment]
I've also run into this issue when bands release "remastered" versions of older albums. It's like, "Yeah, I know it technically released in 2018, but this music is from 1992."

**Comment by certuna** [comment]
It's mostly a mess because id3 never explicitly defined a "reissue date" field.

**Comment by iophobia** [comment]
Just came here to comment on how needed this would be at least for my library. There's tons of remastered albums in there - multiple for some artists - and at least on my PC, I've been quite happy with the "Picard way" of organizing it in MusicBee, so that I can sort by original year. I very much support @certuna's proposition. This would eventually also allow for an easy differentiation of the dreaded "multiple album versions" issue since.

As for how to deal with empty "original year" tags: In MB, I have custom tag that falls back to release year when original year is not populated.

**Comment by onthecliff** [comment]
So any updates on this getting implemented? Is it possible? I would love for my library to look more organized.

**Comment by Maypul** [comment]
Also interested in this feature.

**Comment by certuna** [comment]
Been thinking about this some more. I think the way to implement this without any inconvenience to people who don't use this tag would be:
- [ ] new server configuration option `UseOriginalDate = true/false`
- [ ] new column `originalyear` in `media_file` table
- [ ] new column `releaseyear` in `album` table

If `UserOriginalDate` is False then nothing changes to what ND is reading, storing and displaying.

If UseOriginalDate is True then
###Serverside:
- [ ] scanner reads `TDOR/ORIGINALDATE` and populates `originalyear` with the year integer of that datevalue. If the tag is empty, it copies the value of `year`
- [ ] use `originalyear` instead of `year` to set `min_year` and `max_year` in the `album` table
- [ ] use max of `year` to set `releaseyear` in the `album` table
- [ ] Smart Playlists: if a .nsp query uses `originalyear` but the server has `UseOriginalDate` set to false, replace it with `year`
###Native API:
- [ ] send the value of `originalyear` instead of `year` as the `year` attribute in the `song` API endpoint
- [ ] send a new attribute `releaseyear` in the `album` API endpoint
###Subsonic API:
- [ ] send the value of `originalyear` instead of `year` as the `year` attribute for songs
- [ ] albums no change, works as expected
###WebUI:
- [ ] Album Details: display `releaseyear` in the desktop view like: _1993-1997 · Released 2005 · 6 Songs · 35:43 · 48.92 MB_ and in the mobile view like: _1993-1997 · 2005 · 6 Songs_
- [ ] Song List: because the Year column now uses the `originalyear` value, no changes needed
- [ ] Year filter in Album List view works on `min_date` and `max_date`, so works as expected
- [ ] Album List: the Year column shows the original dates _1993-1997_, as expected

Hope I can find some time to work on this in the near future

**Comment by hayesti** [comment]
Very interested in this feature, particularly to tackle the remasters/re-releases in my collection.

**Comment by koehntopp** [comment]
I'd like to add a UI change:

If GroupAlbumEditions = false:

   in AlbumGrid / AlbumList sort by ORIGINALDATE (which keeps different releases of the same album together)

**Comment by certuna** [comment]
That's how it's implemented in the PR: if an album is tagged "the Picard way" (ie, with 'originaldate' + 'date'), Navidrome will automatically use originaldate as the sorting/filtering date.

**Comment by koehntopp** [comment]
> That's how it's implemented in the PR: if an album is tagged "the Picard way" (ie, with 'originaldate' + 'date'), Navidrome will automatically use originaldate as the sorting/filtering date.

Perfect. I had read "AlbumGrid: no changes needed" as "no change to standard UI", which does not work well.

![image](https://user-images.githubusercontent.com/7113567/220906084-70d03a58-b406-42c0-8e88-4fa5bb10a560.png)

**Comment by Maypul** [comment]
@certuna would you tell me how to do it? For me it always use year from 'date' field.
https://prnt.sc/wXWgBQbMej3O I would love to use original release date everywhere. Using latest version on docker as of today.

**Comment by koehntopp** [comment]
I must be doing something wrong - I would expect Piano Man to appear as the first album, but the list seems to be sorted by RELEASEDATE instead of ORIGINALDATE?

<img width="1090" alt="image" src="https://github.com/navidrome/navidrome/assets/7113567/cfd2a665-cda6-4fbf-a255-f58702c224fc">

<img width="2021" alt="image" src="https://github.com/navidrome/navidrome/assets/7113567/c02c271b-251c-4a01-9e76-990aabe36621">

**Comment by certuna** [comment]
Ah - yes this happens in the case where there is no `DATE`. I'll fix that.

**Comment by koehntopp** [comment]
Before you're fixing the wrong path - there *is* a DATE ;)

<img width="1063" alt="image" src="https://github.com/navidrome/navidrome/assets/7113567/bec6e593-3f7c-476f-8800-89787c618b53">

**Comment by certuna** [comment]
Ah yes but then it sorts correctly - `DATE` (=recording date) is set to 2013.

**Comment by certuna** [comment]
`ORIGINALDATE` is a mess, because there's different implementations what this field should hold - if you go by the id3v2.4 specs, it should hold the date of the original song, in the case of a cover/live version/etc. So if you follow that definition, for example, the 1987 [i]Piano Man[/i] liver recording on Billy Joel's live album [i]A Matter of Trust[/i] should have `ORIGINALDATE` = 1973, `DATE` = 1987-10, `RELEASEDATE` = 2014-02-25. And you would probably expect to see it sorted as October 1987, and not 1973 or 2014.

But if you let Musicbrainz Picard tag the same album (with its default settings), all songs would have `ORIGINALDATE` = 1987-10, `DATE` = 2014-02-25, `RELEASEDATE` = empty - so if you expect it to be sorted as well it as October 1987, Navidrome needs to map the values differently.

**Comment by tsnavi** [comment]
What do I need to do to solve this on my server?
I still see the newer 'reissue' date as the only date, rather than the original release date as I would prefer to.

**Comment by altosys** [comment]
Can we get some clear docs for how files are supposed to be tagged in the end? I've read through the thread but there's so much back and forth that it's hard to see what tags Navidrome expects in the end to sort according to the original release date.

**Comment by rfunk** [comment]
It would have been nice if the default setting for `GroupAlbumEditions` had remained `true`, as this documents.
When the default changed to `false` it started splitting my anthology albums (flac) where I had used `originaldate` per-song (only where available) and not used `releasedate` (because my other software only supports `date`).
Setting `GroupAlbumEditions` to `true` does seem to have fixed my problem though.
