### ISSUE TITLE
[Bug]: Some artists don't show up in Artists search

### ISSUE THREAD

**Issue by fkrivsky** [navidrome/navidrome#2797]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.50.2

### Current Behavior

I have a band called Dødheimsgard in the library. However, when I search for them in the Artists section, I get no results.
Searching for 'Dødheimsgard' in the Albums section tho brings up all the albums...
Same happens when searching for "Dodheimsgard" with plain "o" character.

Artists results:
![image](https://github.com/navidrome/navidrome/assets/68921465/9d594627-b044-4a11-a038-191f22ce93f0)

Album results:
![image](https://github.com/navidrome/navidrome/assets/68921465/bbaf2b9b-72c5-456d-84c4-bbc2869078cb)

### Expected Behavior

Dødheimsgard should be searchable in Artists section.

### Steps To Reproduce

1. Have some album(s) by Dødheimsgard in the music folder
2. Search for "Dødheimsgard" or "Dodheimsgard"
3.  There are no results in Artists section but Albums return results.

### Environment

```markdown
- OS: Windows 10, Android 13
- Browser: Vivaldi 
- Client: Ultrasonic
```

### How Navidrome is installed?

Docker

### Configuration

```toml
# https://www.navidrome.org/docs/installation/docker/
version: "3"
services:
  app:
    image: deluan/navidrome:latest
    user: 1000:100 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      TZ: "Europe/Prague"
      ND_SCANSCHEDULE: "@every 15m"
      ND_LOGLEVEL: "debug"  
      ND_SESSIONTIMEOUT: "24h"
      ND_BASEURL: "https://<server>"
      ND_COVERARTPRIORITY: "cover.*, folder.*, front.*, embedded, external, *.jpg, *.png"
      ND_ENABLESHARING: "true"
      ND_ENABLETRANSCODINGCONFIG: "true"
      ND_ENABLEGRAVATAR: "true"
      ND_SUBSONICARTISTPARTICIPATIONS: "true"
    volumes:
      - "/opt/docker/config/navidrome:/data"
      - "/mnt/data/music:/music:ro"
    deploy:
      labels:
        - "diun.enable=true"
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
```

### Relevant log output

```shell
time="2024-01-18T14:02:01Z" level=debug msg="HTTP: GET http://<server>/api/album?_end=12&_order=ASC&_sort=name&_start=0&name=D%C3%B8dheimsgard" elapsedTime=14.86s httpStatus=200 remoteAddr=10.0.0.2 requestId=384e6b4709f2/gYIba4bMt7-000031 responseSize=17591 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
time="2024-01-18T14:02:01Z" level=debug msg="HTTP: GET http://<server>/api/album?_end=12&_order=ASC&_sort=name&_start=0&name=D%C3%B8dheimsgard" elapsedTime=14.86s httpStatus=200 remoteAddr=10.0.0.2 requestId=384e6b4709f2/gYIba4bMt7-000031 responseSize=17591 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
time="2024-01-18T14:06:18Z" level=debug msg="HTTP: GET http://<server>/api/artist?_end=15&_order=ASC&_sort=name&_start=0&name=D%C3%B8dheimsgard" elapsedTime=601.4ms httpStatus=200 remoteAddr=10.0.0.2 requestId=384e6b4709f2/gYIba4bMt7-000056 responseSize=2 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
Did you wait for the scan to finish? This can happen when the artist is new to the DB and the scan has not finished.

**Comment by fkrivsky** [comment]
It is an artist I had for a long time, and I also waited for over a week after noticing the issue. 
I can try and force a rescan...

**Comment by certuna** [comment]
This seems to work with me?
![Screenshot 2024-01-19 at 09 55 55](https://github.com/navidrome/navidrome/assets/62144283/562fab2d-7438-45bc-a6b5-153f081ef9cc)

**Comment by fkrivsky** [comment]
Thanks, I've run a rescan, will report back later...

**Comment by fkrivsky** [comment]
So in the end I dropped the whole db and started fresh. Dødheimsgard is now showing up in search results properly.
