### ISSUE TITLE
AirPlay 2 support [macOS]

### ISSUE THREAD

**Issue by certuna** [navidrome/navidrome#280]
For navidrome on macOS, implement routing the audio not just to local outputs but also casting to AirPlay devices. And AirPlay 2 because multi-room audio is awesome :)

https://developer.apple.com/documentation/avfoundation/airplay_2/getting_airplay_2_into_your_app

Implementing this with reverse engineered libraries for Windows/Linux is probably a lot harder, but on macOS it's a fairly straightforward thing.

**Comment by deluan** [comment]
It will be hard for me to implement this, as I don't have AirPlay devices at home. Can't you just stream a Safari tab to the AirPlay device?

**Comment by certuna** [comment]
I don't think so, at least I don't see this option in macOS Safari, and on mobile the stream would probably stop when the screen turns off, while you'd ideally want the audio connection navidrome <-> airplay speaker be continue running without active input from a controlling 3rd device.

But understood if you don't have the equipment to test, just thought if there's a Chromecast request this could work too.

**Comment by deluan** [comment]
When working on the Chromecast story (#250), I may take a look at this

**Comment by stefan1983** [comment]
Any update on this here yet? Thanks
