### ISSUE TITLE
[Bug]: Internal server error on almost all screens after upgrade from 0.50.2 to 0.51.0

### ISSUE THREAD

**Issue by cl-parsons** [navidrome/navidrome#2806]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.51.0

### Current Behavior

Almost every screen after logging in is crashed and prints "internal server error".

### Expected Behavior

Display the list of songs / albums

### Steps To Reproduce

With a working podman container with navidrome 0.50.2, switch to version 0.51.0.

### Environment

```markdown
- OS: Debian 11
- Browser: Firefox
- Client: Navidrome native
- Command : `podman run --replace -e ND_LOGLEVEL=debug -d --name navidrome --restart=unless-stopped --user 994 -p 192.168.42.1:4533:4533 -v /mnt/music:/music -v /var/lib/navidrome:/data -l io.containers.autoupdate docker.io/deluan/navidrome:0.51.0`
```

### How Navidrome is installed?

Docker

### Configuration

```toml
No specific configuration.
```

### Relevant log output

```shell
_   _             _     _
| \ | |           (_)   | |
|  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___
| . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
| |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
\_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
                          Version: 0.51.0 (fd61b29a)

Loaded configuration from '': &conf.configOptions{
    ConfigFile:                   "",
    Address:                      "0.0.0.0",
    Port:                         4533,
    UnixSocketPerm:               "0660",
    MusicFolder:                  "/music",
    DataFolder:                   "/data",
    CacheFolder:                  "/data/cache",
    DbPath:                       "/data/navidrome.db?cache=shared&_busy_timeout=15000&_journal_mode=WAL&_foreign_keys=on",
    LogLevel:                     "debug",
    ScanInterval:                 -1,
    ScanSchedule:                 "@every 1m",
    SessionTimeout:               86400000000000,
    BaseURL:                      "",
    BasePath:                     "",
    BaseHost:                     "",
    BaseScheme:                   "",
    TLSCert:                      "",
    TLSKey:                       "",
    UILoginBackgroundURL:         "/backgrounds",
    UIWelcomeMessage:             "",
    MaxSidebarPlaylists:          100,
    EnableTranscodingConfig:      false,
    EnableDownloads:              true,
    EnableExternalServices:       true,
    EnableMediaFileCoverArt:      true,
    TranscodingCacheSize:         "100MB",
    ImageCacheSize:               "100MB",
    EnableArtworkPrecache:        true,
    AutoImportPlaylists:          true,
    PlaylistsPath:                ".:**/**",
    AutoTranscodeDownload:        false,
    DefaultDownsamplingFormat:    "opus",
    SearchFullString:             false,
    RecentlyAddedByModTime:       false,
    PreferSortTags:               false,
    IgnoredArticles:              "The El La Los Las Le Les Os As O A",
    IndexGroups:                  "A B C D E F G H I J K L M N O P Q R S T U V W X-Z(XYZ) [Unknown]([)",
    SubsonicArtistParticipations: false,
    FFmpegPath:                   "",
    MPVPath:                      "",
    CoverArtPriority:             "cover.*, folder.*, front.*, embedded, external",
    CoverJpegQuality:             75,
    ArtistArtPriority:            "artist.*, album/artist.*, external",
    EnableGravatar:               false,
    EnableFavourites:             true,
    EnableStarRating:             true,
    EnableUserEditing:            true,
    EnableSharing:                false,
    DefaultDownloadableShare:     false,
    DefaultTheme:                 "Dark",
    DefaultLanguage:              "",
    DefaultUIVolume:              100,
    EnableReplayGain:             true,
    EnableCoverAnimation:         true,
    GATrackingID:                 "",
    EnableLogRedacting:           true,
    AuthRequestLimit:             5,
    AuthWindowLength:             20000000000,
    PasswordEncryptionKey:        "[REDACTED]",
    ReverseProxyUserHeader:       "[REDACTED]",
    ReverseProxyWhitelist:        "[REDACTED]",
    Prometheus:                   conf.prometheusOptions{Enabled:false, MetricsPath:"[REDACTED]"},
    Scanner:                      conf.scannerOptions{Extractor:"taglib", GenreSeparators:";/,", GroupAlbumReleases:false},
    Jukebox:                      conf.jukeboxOptions{
        Enabled: false,
        Devices: {
        },
        Default: "",
    },
    Agents:                           "lastfm,spotify",
    LastFM:                           conf.lastfmOptions{Enabled:true, ApiKey:"[REDACTED]", Secret:"[REDACTED]", Language:"en"},
    Spotify:                          conf.spotifyOptions{},
    ListenBrainz:                     conf.listenBrainzOptions{Enabled:true, BaseURL:"https://api.listenbrainz.org/1/"},
    DevLogSourceLine:                 false,
    DevLogLevels:                     {},
    DevEnableProfiler:                false,
    DevAutoCreateAdminPassword:       "[REDACTED]",
    DevAutoLoginUsername:             "[REDACTED]",
    DevActivityPanel:                 true,
    DevSidebarPlaylists:              true,
    DevEnableBufferedScrobble:        true,
    DevShowArtistPage:                true,
    DevOffsetOptimize:                50000,
    DevArtworkMaxRequests:            2,
    DevArtworkThrottleBacklogLimit:   100,
    DevArtworkThrottleBacklogTimeout: 60000000000,
    DevArtistInfoTimeToLive:          86400000000000,
    DevAlbumInfoTimeToLive:           604800000000000,
}
time="2024-01-22T11:37:27Z" level=debug msg="Opening DataBase" dbPath="/data/navidrome.db?cache=shared&_busy_timeout=15000&_journal_mode=WAL&_foreign_keys=on" driver=sqlite3
time="2024-01-22T11:37:27Z" level=info msg="goose: no migrations to run. current version: 20231209211223\n"
time="2024-01-22T11:37:27Z" level=info msg="Starting signaler"
time="2024-01-22T11:37:27Z" level=error msg="Agent not available. Check configuration" name=lastfm
time="2024-01-22T11:37:27Z" level=error msg="Agent not available. Check configuration" name=spotify
time="2024-01-22T11:37:27Z" level=info msg="Creating Image cache" maxSize="100 MB" path=/data/cache/images
time="2024-01-22T11:37:27Z" level=info msg="Configuring Media Folder" name="Music Library" path=/music
time="2024-01-22T11:37:27Z" level=info msg="Setting Session Timeout" value=24h
time="2024-01-22T11:37:27Z" level=info msg="Starting scheduler"
time="2024-01-22T11:37:27Z" level=info msg="Scheduling periodic scan" schedule="@every 1m"
time="2024-01-22T11:37:27Z" level=debug msg="Scheduler: start"
time="2024-01-22T11:37:27Z" level=debug msg="Scheduler: added" entry=1 next="2024-01-22 11:38:27 +0000 UTC" now="2024-01-22 11:37:27.488654414 +0000 UTC"
time="2024-01-22T11:37:27Z" level=info msg="Login rate limit set" requestLimit=5 windowLength=20s
time="2024-01-22T11:37:27Z" level=info msg="Found ffmpeg" path=/usr/bin/ffmpeg
time="2024-01-22T11:37:27Z" level=debug msg="Last.fm integration is ENABLED"
time="2024-01-22T11:37:27Z" level=debug msg="ListenBrainz integration is ENABLED" ListenBrainz.BaseURL="https://api.listenbrainz.org/1/"
time="2024-01-22T11:37:27Z" level=info msg="Spotify integration is not enabled: missing ID/Secret"
time="2024-01-22T11:37:27Z" level=info msg="Mounting Native API routes" path=/api
time="2024-01-22T11:37:27Z" level=error msg="Agent not available. Check configuration" name=lastfm
time="2024-01-22T11:37:27Z" level=error msg="Agent not available. Check configuration" name=spotify
time="2024-01-22T11:37:27Z" level=info msg="Creating Transcoding cache" maxSize="100 MB" path=/data/cache/transcoding
time="2024-01-22T11:37:27Z" level=debug msg="Loaded cache" dir=/data/cache/transcoding numItems=0
time="2024-01-22T11:37:27Z" level=info msg="Finished initializing cache" cache=Transcoding elapsedTime="320.931µs" maxSize=100MB
time="2024-01-22T11:37:27Z" level=debug msg="Throttling Subsonic getCoverArt endpoint" backlogLimit=100 backlogTimeout=1m maxRequests=2
time="2024-01-22T11:37:27Z" level=info msg="Mounting Subsonic API routes" path=/rest
time="2024-01-22T11:37:27Z" level=error msg="Agent not available. Check configuration" name=lastfm
time="2024-01-22T11:37:27Z" level=error msg="Agent not available. Check configuration" name=spotify
time="2024-01-22T11:37:27Z" level=debug msg="Throttling public images endpoint" backlogLimit=100 backlogTimeout=1m maxRequests=2
time="2024-01-22T11:37:27Z" level=info msg="Mounting Public Endpoints routes" path=/share
time="2024-01-22T11:37:27Z" level=info msg="Mounting LastFM Auth routes" path=/api/lastfm
time="2024-01-22T11:37:27Z" level=info msg="Mounting ListenBrainz Auth routes" path=/api/listenbrainz
time="2024-01-22T11:37:27Z" level=info msg="Mounting Background images routes" path=/backgrounds
time="2024-01-22T11:37:27Z" level=info msg="Mounting WebUI routes" path=/app
time="2024-01-22T11:37:27Z" level=info msg="----> Navidrome server is ready!" address="0.0.0.0:4533" startupTime=22ms tlsEnabled=false
time="2024-01-22T11:37:27Z" level=debug msg="Loaded cache" dir=/data/cache/images numItems=881
time="2024-01-22T11:37:27Z" level=info msg="Finished initializing cache" cache=Image elapsedTime=116.9ms maxSize=100MB
time="2024-01-22T11:37:29Z" level=debug msg="Executing initial scan"
time="2024-01-22T11:37:29Z" level=debug msg="Scanning folder" folder=/music lastModifiedSince="2024-01-22 11:36:29.006 +0000 UTC"
time="2024-01-22T11:37:29Z" level=debug msg="Directory tree loaded from DB" elapsed=261.4ms total=4195
time="2024-01-22T11:37:30Z" level=debug msg="Processing changed folder" dir="/music/Jérémie Grandsenne - After (2011)"
time="2024-01-22T11:37:30Z" level=info msg="Finished processing changed folder" deleted=0 dir="/music/Jérémie Grandsenne - After (2011)" elapsed=57.6ms updated=0
time="2024-01-22T11:37:30Z" level=warning msg="Error warming cache" error="error cacheing id='ar-e9c0ae405480f9e7781de3fb77f53314_0': could not get a cover art for ar-e9c0ae405480f9e7781de3fb77f53314_0: artwork unavailable"
time="2024-01-22T11:37:30Z" level=debug msg="Processing changed folder" dir="/music/VA - TCDNBv1 (2010)"
time="2024-01-22T11:37:30Z" level=info msg="Finished processing changed folder" deleted=0 dir="/music/VA - TCDNBv1 (2010)" elapsed=63.2ms updated=0
time="2024-01-22T11:37:30Z" level=debug msg="Processing changed folder" dir="/music/VA - TCDNBv3 (2009)"
time="2024-01-22T11:37:30Z" level=warning msg="Error warming cache" error="error cacheing id='ar-15036ff32108a148a167415c8307eb9a_0': could not get a cover art for ar-15036ff32108a148a167415c8307eb9a_0: artwork unavailable"
time="2024-01-22T11:37:30Z" level=warning msg="Error warming cache" error="error cacheing id='ar-c494f08f1eee10f64456e85b15db9c86_0': could not get a cover art for ar-c494f08f1eee10f64456e85b15db9c86_0: artwork unavailable"
time="2024-01-22T11:37:30Z" level=error msg="SQL: `SELECT coalesce(starred, 0) as starred, coalesce(rating, 0) as rating, coalesce(play_count, 0) as play_count, starred_at, play_date, album.* FROM album LEFT JOIN annotation on (annotation.item_id = album.id AND annotation.item_type = 'album' AND annotation.user_id = '2aecc026-173d-4170-add7-9c9d755d709c') WHERE album_artist_id IN ({:p0},{:p1},{:p2},{:p3},{:p4},{:p5},{:p6},{:p7},{:p8},{:p9},{:p10},{:p11})`" args="map[p0:d8b4569b8b7b282012b9b0b216cc6861 p1:d29b1db2ddca51c11166cbe78fd6eaf9 p10:7cfc8150d1ee19496d4ae8fa0c8f3346 p11:15036ff32108a148a167415c8307eb9a p2:7162cea405a7114733660002cf8cc3af p3:5146d251d4bb46cfe61d5447758ad83e p4:8c250d076e33b6caf72213e751c5bf88 p5:12106044fd7a0368aa59405505e22fab p6:da08b11ebb2ef95ebdd72209580b8e28 p7:4c0711c0dd6649d201428feb644fcf94 p8:29b2b7602ea409e6f94e2fbfdbb351dd p9:671fca90ffa6da5feb8fd88b414c35a5]" elapsedTime="765.181µs" error="sql: Scan error on column index 34, name \"image_files\": converting NULL to string is unsupported" rowsAffected=-1
time="2024-01-22T11:37:30Z" level=error msg="Error writing artists to the DB" error="sql: Scan error on column index 34, name \"image_files\": converting NULL to string is unsupported"
time="2024-01-22T11:37:30Z" level=info msg="Finished processing changed folder" deleted=0 dir="/music/VA - TCDNBv3 (2009)" elapsed=62.8ms updated=0
time="2024-01-22T11:37:30Z" level=error msg="Error updating folder in the DB" dir="/music/VA - TCDNBv3 (2009)" error="sql: Scan error on column index 34, name \"image_files\": converting NULL to string is unsupported"
time="2024-01-22T11:37:30Z" level=debug msg="Processing changed folder" dir="/music/VA - TCDNBv5 (2012)"
time="2024-01-22T11:37:30Z" level=error msg="SQL: `SELECT coalesce(starred, 0) as starred, coalesce(rating, 0) as rating, coalesce(play_count, 0) as play_count, starred_at, play_date, album.* FROM album LEFT JOIN annotation on (annotation.item_id = album.id AND annotation.item_type = 'album' AND annotation.user_id = '2aecc026-173d-4170-add7-9c9d755d709c') WHERE album_artist_id IN ({:p0},{:p1},{:p2},{:p3},{:p4},{:p5},{:p6},{:p7},{:p8},{:p9},{:p10},{:p11},{:p12},{:p13},{:p14},{:p15},{:p16},{:p17},{:p18},{:p19},{:p20},{:p21},{:p22},{:p23},{:p24},{:p25},{:p26},{:p27},{:p28},{:p29},{:p30})`" args="map[p0:d8541551e59e41a717bac468280f751d p1:e63dffcf6a161e18a9d47f546b4dc48f p10:3a66efdd4d3164187992b406274a24cf p11:02a2051354da38c5458ee37b9fccfe39 p12:416c15561452672c813fa844504d7ae6 p13:12106044fd7a0368aa59405505e22fab p14:d29b1db2ddca51c11166cbe78fd6eaf9 p15:be6f516e5e2ff5ebed94da11c6cda7f2 p16:671fca90ffa6da5feb8fd88b414c35a5 p17:24ebcd8e0b674632056fa986d298d829 p18:526daef78bfd4deb438c3b9388ef69c1 p19:ce6dc3630302b36bb53863e2f91bd2b9 p2:29b2b7602ea409e6f94e2fbfdbb351dd p20:f7892c8108519858feb73926121988ad p21:5146d251d4bb46cfe61d5447758ad83e p22:d8b4569b8b7b282012b9b0b216cc6861 p23:7162cea405a7114733660002cf8cc3af p24:167c39d25e48de57c666e93064b2e64c p25:7cfc8150d1ee19496d4ae8fa0c8f3346 p26:4c0711c0dd6649d201428feb644fcf94 p27:8c250d076e33b6caf72213e751c5bf88 p28:da08b11ebb2ef95ebdd72209580b8e28 p29:e82294d85a19a933f9ef83c6b0c2b742 p3:15036ff32108a148a167415c8307eb9a p30:91001f67cd30e1fdbcf3db7bdfabc9c8 p4:67cb7dbdb935430911459f5431d61701 p5:a0bdb61271ee939dd7d94eac0f55dbb9 p6:6dfe3a805cd47b52894bd11d1f98e4c6 p7:8a790c6d89afb306b05f86f859b16944 p8:3f83d8a5a04bf2c0a9bb605026f001ff p9:55c186131cadf69b45bbf816cb6e7184]" elapsedTime="731.814µs" error="sql: Scan error on column index 34, name \"image_files\": converting NULL to string is unsupported" rowsAffected=-1
time="2024-01-22T11:37:30Z" level=error msg="Error writing artists to the DB" error="sql: Scan error on column index 34, name \"image_files\": converting NULL to string is unsupported"
time="2024-01-22T11:37:30Z" level=info msg="Finished processing changed folder" deleted=0 dir="/music/VA - TCDNBv5 (2012)" elapsed=70.3ms updated=0
time="2024-01-22T11:37:30Z" level=error msg="Error updating folder in the DB" dir="/music/VA - TCDNBv5 (2012)" error="sql: Scan error on column index 34, name \"image_files\": converting NULL to string is unsupported"
time="2024-01-22T11:37:30Z" level=debug msg="Finished reading directories from filesystem" path=/music
time="2024-01-22T11:37:30Z" level=debug msg="Finished deleted folders check" elapsed="887.469µs" total=0
time="2024-01-22T11:37:30Z" level=debug msg="Removing non-album artist_ids"
time="2024-01-22T11:37:31Z" level=info msg="Finished processing Music Folder" added=0 deleted=0 elapsed=1.56s folder=/music playlistsImported=0 updated=0
time="2024-01-22T11:37:31Z" level=debug msg="Finished initial scan"
time="2024-01-22T11:37:31Z" level=debug msg="Started new EventStream connection" client="af990203-70c1-4c22-9a95-5aac95414c20 (masq - 194.254.113.19 - 007fb228-1c18-47e7-bb5e-3d6b608c6a17)" requestId=27c099146957/U3mUAsCXiu-000001 username=masq
time="2024-01-22T11:37:31Z" level=debug msg="Client added to EventStream broker" newClient="af990203-70c1-4c22-9a95-5aac95414c20 (masq - 194.254.113.19 - 007fb228-1c18-47e7-bb5e-3d6b608c6a17)" numActiveClients=1
time="2024-01-22T11:37:32Z" level=debug msg="Loaded background images from image service" elapsed=5.08s total=102
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by cl-parsons** [comment]
Gonna try this advice : 

https://github.com/navidrome/navidrome/issues/2168#issuecomment-1427088125

**Comment by cl-parsons** [comment]
It does not help... So please help!

**Comment by deluan** [comment]
Hey @cl-parsons, have you run any external script that touches the DB, like playlist importers, or sync scripts? This error should not occur if only Navidrome changes its database. 

Anyway, we are looking into a solution to fix this and make sure it does not happen in the future if a script tries to write this invalid data to the DB. Stay tuned for a PR with the fix.

**Comment by deluan** [comment]
@cl-parsons, can you try the version from PR #2812? Just download the binary (from the [PR](https://github.com/navidrome/navidrome/pull/2812#issuecomment-1904976696)) and replace your binary. If you are using docker, just use image `ghcr.io/navidrome/navidrome:pr-2812`

Remember to backup your DB before doing this.

Let me know if this fixes your issue.

**Comment by Tos26** [comment]
hello,
I got the same error after update from 0.50.2.
I tested the PR 2812 but I got the same issue: Internal server error !

**Comment by caiocotts** [comment]
Hey @Tos26!

Can you please post your logs with the error here?

**Comment by snowphone** [comment]
Same here even after trying pr-2812.

Here's the log:
[sixtyfive-pr-2812.log](https://github.com/navidrome/navidrome/files/14048714/sixtyfive-pr-2812.log)

**Comment by deluan** [comment]
@snowphone thanks for the log. 

@caiocotts Based on the logs, seems that there are more columns in the DB that need the `default ''` treatment. In @snowphone's case is the `media_file.mbz_release_track_id` column

**Comment by Tos26** [comment]
Here is my log from the version 0.51.0:
[Log.txt](https://github.com/navidrome/navidrome/files/14056306/Log.txt)

The database is coming from the previous version 0.50.2 and worked perfectly. 

Thanks for help !

**Comment by virgil9306** [comment]
I'm facing the same issue after upgrading.
Nothing else is touching the DB.

There might be some issue in the DB migration when upgrading?

I don't really understand the advice in the other threads. What's the solution? To manually update DB so every entry where `image_files` is `NULL` I need to replace with empty string `''`?

**Comment by caiocotts** [comment]
Hello @virgil9306!

I am currently implementing a migration to address these errors. I'm just testing it a bit to make sure it won't screw up other things. I will be creating a new PR in a bit.

**Comment by caiocotts** [comment]
Let me know if you guys have any issues with this. And remember to backup you `navidrome.db` file before testing.

**Comment by deluan** [comment]
@virgil9306 

> To manually update DB so every entry where `image_files` is `NULL` I need to replace with empty string `''`?
> 
> I wonder if just recreating the DB is also viable.

Both are valid options, but recreating the DB would make you lose all playcounts, favourits, ratings, etc... 

A better option is to test @caiocotts's PR. We are just waiting for feedback on this to release a bug fix.

**Comment by snowphone** [comment]
I tried #2840 (without full-scan after new deployment) and it seems the bug still exists.
Here's the log: 
 
[navi-pr-2840.log](https://github.com/navidrome/navidrome/files/14165620/navi-pr-2840.log)

**Comment by RedKage** [comment]
The only thing I know is, with version 0.51 navidrome doesn't seem to work with symfonium

I revert to 0.50 and it works

I use the binaries in this PR and it still doesn't work

I haven't checked the logs though. Didn't investigate too much, but the symfonium log returns

```
200  /rest/search3.view?query=%22%22&songOffset=0&songCount=1000&albumOffset=0&albumCount=0&artistOffset=0&artistCount=0&u=REDACTED&p=REDACTED&v=1.13.0&c=Symfonium&f=json (78ms, unknown-length body)
2024-02-05 07:48:30.175 Verbose/SubsonicLogger: <-- [608] 
2024-02-05 07:48:30.176 Error/SubsonicLogger: Error
java.io.EOFException: End of input
	at ur.q.a0(Unknown Source:79)
	at ur.q.K(Unknown Source:248)
	at ur.q.b(Unknown Source:4)
	at pd.s.w(Unknown Source:220)
	at pd.s.n(Unknown Source:12)
	at h6.g.h(Unknown Source:199)
	at pd.g0.X(Unknown Source:22349)
	at pd.p.w(Unknown Source:16)
	at vs.a.p(Unknown Source:5)
	at tt.i0.run(Unknown Source:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

Same error with this PR or version 0.51. Not sure if related to this bug here or not.

**Comment by Tos26** [comment]
hello,

I just tested the PR [#2840](https://github.com/navidrome/navidrome/pull/2840) and I have the same issue: Internal server error
Here is the [log file](https://github.com/navidrome/navidrome/files/14169333/Log.txt)

![Navidrome](https://github.com/navidrome/navidrome/assets/23366980/6789a3af-40fd-4f74-8125-0ea8b922ff4e)

**Comment by deluan** [comment]
@RedKage, we will need the logs from Navidrome to understand what is the issue for you.

Everyone else, there is a new build for #2840. Please check if it solve your issues, and post logs here if it does not.

**Comment by snowphone** [comment]
If you guys are struggling with testing and verifying the PR, it will be helpful to upload my sqlite.db files (of course only db, not actual songs)?

**Comment by deluan** [comment]
@snowphone If you can, that would be great: Send it to deluan @ navidrome.org, and put "GitHub issue #2806" in the title.

But most important: Did you try the latest build from PR #2840 (from 8pm EST)?

**Comment by snowphone** [comment]
I tested once more after your reply. There's something different since it takes quite a lot of time to fetch metadata (sorry, I forgot to copy the log). Unfortunately, the problem still exist. I've sent you an email with my DB so you may find out what is the problem.

**Comment by caiocotts** [comment]
@snowphone, your instance is not applying the new modifications because the migration has already been run.
That is to say, since the migration has the same file name, regardless of if it has been modified or not, it will not run again.
You need to use a backup of your DB before you tested first PR #2840 in order for the latest migration to be executed.

**Comment by snowphone** [comment]
@caiocotts just sent me a fixed DB and I tried this one with #2840. Thankfully it works really well and even the latest image (v0.51) works too :)

Thanks @caiocotts and @deluan!

[navi-pr-2840-works.log](https://github.com/navidrome/navidrome/files/14184628/navi-pr-2840-works.log)

**Comment by Tos26** [comment]
hello,

Still the same issue on my side with the last PR [#2840](https://github.com/navidrome/navidrome/pull/2840).
![Navidrome](https://github.com/navidrome/navidrome/assets/23366980/0f18f69a-c69f-41ba-a5ed-764af22627ce)

The [Log.txt](https://github.com/navidrome/navidrome/files/14184732/Log.txt)

Same errors since the beginnig of my tests of version 0.51:

`SELECT coalesce(starred, 0) as starred, coalesce(rating, 0) as rating, coalesce(play_count, 0) as play_count, starred_at, play_date, album.* FROM album LEFT JOIN annotation on (annotation.item_id = album.id AND annotation.item_type = 'album' AND annotation.user_id = '1d0678a4-03f2-4769-82d0-6b5dea869026') ORDER BY created_at desc LIMIT 36" args="map[]" elapsedTime=83.6ms error="sql: Scan error on column index 40, name \"external_info_updated_at\": unsupported Scan, storing driver.Value type <nil> into type *time.Time" requestId=MonServer/1cjiRHK25E-000028 rowsAffected=-1 username=User`

Or

`Error reading album: sql: Scan error on column index 40, name "external_info_updated_at": unsupported Scan, storing driver.Value type <nil> into type *time.Time`

**Comment by RedKage** [comment]
> @snowphone, your instance is not applying the new modifications because the migration has already been run. That is to say, since the migration has the same timestamp, regardless of if it has been modified or not, it will not run again. You need to use a backup of your DB before you tested first PR #2840 in order for the latest migration to be executed.

Then, assuming I have the same error as you guys, that would make sense that this PR didn't "work" for me as well since I just replaced the binary and kept the same database. 

> EDIT: Also it would be great if folks with this issue could confirm if they used any tool that writes to Navidrome's DB.

As a matter of fact, yes I did manually change entries in the DB because I recently moved my music folder to another path structure. So I did some manual sqlite updates. Using a windows portable software "DB Browser for SQLite Portable"

**Comment by deluan** [comment]
Hey @Tos26 , is it possible to send me a copy of your DB, so we can verify what is causing the problem for you? Last build should be working. 

If you are ok with it, please send it to deluan @ navidrome.org

**Comment by deluan** [comment]
> Then, assuming I have the same error as you guys, that would make sense that this PR didn't "work" for me as well since I just replaced the binary and kept the same database.

@RedKage and everyone in this thread who doesn't have a backup of the DB *before* trying the binary from #2840, you can it to run the migration again, you need to run a SQL command:
```
delete from goose_db_version where version_id = '20240122223340';
```

Then start Navidrome again. To be sure the migration is applied, you need to see the following lines at the beginning of the logs:
```
INFO[0000] OK   20240122223340_add_default_values_to_null_columns.go.go (150.25ms) 
INFO[0000] goose: successfully migrated database to version: 20240122223340 
```
Depending on the size of your library, it may take a few minutes to complete.

**Comment by deluan** [comment]
Here are the latest binaries from PR #2840. Please test (backup your DB first!) and give feedback. 

[navidrome_v0.51.0-SNAPSHOT_darwin_amd64.tar.gz](https://github.com/navidrome/navidrome/files/14187568/navidrome_v0.51.0-SNAPSHOT_darwin_amd64.tar.gz)
[navidrome_v0.51.0-SNAPSHOT_linux_386.tar.gz](https://github.com/navidrome/navidrome/files/14187569/navidrome_v0.51.0-SNAPSHOT_linux_386.tar.gz)
[navidrome_v0.51.0-SNAPSHOT_linux_amd64.tar.gz](https://github.com/navidrome/navidrome/files/14187570/navidrome_v0.51.0-SNAPSHOT_linux_amd64.tar.gz)
[navidrome_v0.51.0-SNAPSHOT_linux_arm64.tar.gz](https://github.com/navidrome/navidrome/files/14187572/navidrome_v0.51.0-SNAPSHOT_linux_arm64.tar.gz)
[navidrome_v0.51.0-SNAPSHOT_linux_armv5.tar.gz](https://github.com/navidrome/navidrome/files/14187573/navidrome_v0.51.0-SNAPSHOT_linux_armv5.tar.gz)
[navidrome_v0.51.0-SNAPSHOT_linux_armv6.tar.gz](https://github.com/navidrome/navidrome/files/14187574/navidrome_v0.51.0-SNAPSHOT_linux_armv6.tar.gz)
[navidrome_v0.51.0-SNAPSHOT_linux_armv7.tar.gz](https://github.com/navidrome/navidrome/files/14187575/navidrome_v0.51.0-SNAPSHOT_linux_armv7.tar.gz)
[navidrome_v0.51.0-SNAPSHOT_windows_386.zip](https://github.com/navidrome/navidrome/files/14187576/navidrome_v0.51.0-SNAPSHOT_windows_386.zip)
[navidrome_v0.51.0-SNAPSHOT_windows_amd64.zip](https://github.com/navidrome/navidrome/files/14187577/navidrome_v0.51.0-SNAPSHOT_windows_amd64.zip)

**Comment by Tos26** [comment]
> ~~Hey @Tos26 , is it possible to send me a copy of your DB, so we can verify what is causing the problem for you? Last build should be working. ~~
> 
> ~If you are ok with it, please send it to deluan @ navidrome.org~
> 
> EDIT: NVM, the binary posted in the PR was outdated! I'll post the current binaries for testing the PR here in this issue.

Hello Deluan,

I tested the last snapshot:
![Navidrome](https://github.com/navidrome/navidrome/assets/23366980/4fdb3b26-fa30-4055-831b-ba81b2699c5d)

I'm pleased to say that I didn't receive Internal server error anymore !! 
All seem ok from my side.

Thank you.

**Comment by deluan** [comment]
Thanks folks for the feedback. We will do some more testing and will release 0.51.1 this weekend.
