### ISSUE TITLE
[Bug]: userRating and playCount missing from getPlaylist.view

### ISSUE THREAD

**Issue by flyingOwl** [navidrome/navidrome#2816]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.51.0

### Current Behavior

A client (DSub in my case) is no longer showing the ratings of a song when displaying a playlist via the `getPlaylist.view` endpoint. Accessing the json endpoint via a web browser it is clear, that "playCount" and "played" are also missing from the response.

### Expected Behavior

The fields "userRating", "playCount" and "played" should be send out. This is still the case with v0.50.2.

### Environment

```markdown
- OS: Fedora 38
- Browser:
- Client: DSub 5.5.3
```

### How Navidrome is installed?

Docker

### Anything else?

This was probably introduced by: 0ca0d5da228a5c2810c6103185891272ade1cdbf
`playlist_repository.go` and `playlist_track_repository.go` got their queries changed. The fields in question are now accessed with a `coalesce()` wrapper.
See: https://github.com/navidrome/navidrome/blob/0ca0d5da228a5c2810c6103185891272ade1cdbf/persistence/playlist_repository.go#L348-L352
and: https://github.com/navidrome/navidrome/blob/0ca0d5da228a5c2810c6103185891272ade1cdbf/persistence/playlist_track_repository.go#L53-L55
This probably leads to different column names and therefore missing data. Some other `coalesce()` functions are appended with `as '...'` which gives this column the original name. This could also be the fix for this bug.
`starred` might also be missing but I have no such data to test. `played` (playDate) is missing because it is only set if `play_count > 0`.

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by caiocotts** [comment]
Hello @flyingOwl

Let us know if this error is still persistent on PR #2818.
