### ISSUE TITLE
[Bug]: Unable to Un-Rate Songs

### ISSUE THREAD

**Issue by dathbe** [navidrome/navidrome#2823]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.51.0 (fd61b29a)

### Current Behavior

Clicking the star rating of a rated song does NOT un-rate the song as it did in 0.50.x.

### Expected Behavior

Clicking the star rating a second time will un-rate the song.

### Steps To Reproduce

1. Rate a song or locate a rated song
2. Click the rating for that song (i.e., click the second star if the song has a 2-star rating)
3. Nothing happens

### Environment

```markdown
- OS: Docker on Debian
- Browser: Firefox
- Client: Web UI
```

### How Navidrome is installed?

Docker

### Configuration

```toml
n/a unless someone thinks it will help (confirmed that the bug exists in the Demo instance)
```

### Relevant log output

```shell
n/a
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by dathbe** [comment]
See #2824

**Comment by deluan** [comment]
Thanks for reporting. PR is merged. We have a bug fix release coming out this week, and this will be included.
