### ISSUE TITLE
[Bug]: Navidrome instance configuration is publicly visible in web UI html

### ISSUE THREAD

**Issue by LuigiVampa92** [navidrome/navidrome#2829]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.51.0

### Current Behavior

I load the main page of the web UI. I don't have any previous session. I open the page html source code and among the normal html there is also the Navidrome instance configuration, embedded into the "script" tag, and it contains private data (LastFM API key value). Here is the example:

```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="description" content="Navidrome Music Server - v0.51.0 (fd61b29a)"/>
    <link rel="apple-touch-icon" sizes="180x180" href="./apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="./favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="192x192" href="./android-chrome-192x192.png">
    <link rel="icon" type="image/png" sizes="16x16" href="./favicon-16x16.png">
    <link rel="mask-icon" href="./safari-pinned-tab.svg" color="#5b5fd5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <meta name="viewport" content="width=device-width,initial-scale=1"/>
    <link rel="manifest" href="./manifest.webmanifest"/>
    <meta property="og:site_name" content="Navidrome">
    <meta property="og:url" content="">
    <meta property="og:title" content="">
    <meta property="og:image" content="">
    <meta property="og:image:width" content="300">
    <meta property="og:image:height" content="300">
    <title>Navidrome</title>
    <script>window.__APP_CONFIG__ = "{\"baseURL\":\"\",\"defaultDownloadableShare\":false,\"defaultDownsamplingFormat\":\"opus\",\"defaultLanguage\":\"ru\",\"defaultTheme\":\"Dark\",\"defaultUIVolume\":100,\"devActivityPanel\":true,\"devShowArtistPage\":true,\"devSidebarPlaylists\":true,\"enableCoverAnimation\":true,\"enableDownloads\":true,\"enableExternalServices\":true,\"enableFavourites\":true,\"enableReplayGain\":true,\"enableSharing\":false,\"enableStarRating\":true,\"enableTranscodingConfig\":false,\"enableUserEditing\":true,\"firstTime\":false,\"gaTrackingId\":\"\",\"lastFMApiKey\":\"3b60XXXXXXXXXXXXXXXXXXXXXXXXd23d\",\"lastFMEnabled\":true,\"listenBrainzEnabled\":true,\"loginBackgroundURL\":\"/backgrounds\",\"losslessFormats\":\"ALAC,APE,DSF,FLAC,SHN,TAK,WAV,WV,WVP\",\"maxSidebarPlaylists\":100,\"variousArtistsId\":\"03b6XXXXXXXXXXXXXXXXXXXXXXXX2295\",\"version\":\"0.51.0 (fd61b29a)\",\"welcomeMessage\":\"Personal music storage\"}"</script>
    <script>window.__SHARE_INFO__ = null </script>
    <script defer="defer" src="./static/js/main.c6349510.js"></script>
    <link href="./static/css/main.90bfad59.css" rel="stylesheet">
</head>
<body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root">
    </div>
</body>
</html>
``` 

### Expected Behavior

Navidrome instance configuration should not be public.

I am not 100% sure if it is a bug or not. Maybe some of this data is intended to be left public, but I suspect that it is a mistake.

### Steps To Reproduce

1. Open Navidrome web UI in the browser
2. Open the page source code

### Environment

```markdown
- OS: Debian 12
- Browser: 120.0.6099.199 for MacOS (official build) (x86_64)
```

### How Navidrome is installed?

Docker

### Anything else?

Thank you for the awesome product and your hard work! I have been using it for a couple of months already and everything is great!

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
The configuration available in the index.html file is not considered private. The Last.fm API Key is an exception (although it was a public value until recently).

Anyway, I removed the API Key from the index.html, and it is now sent as part of the login response. See 1f71e567

Thanks for bringing this to my attention.
