### ISSUE TITLE
[Bug]: dates with spaces or no month/day are not able to be parsed

### ISSUE THREAD

**Issue by michaelkrieger** [navidrome/navidrome#2833]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.51.0

### Current Behavior

Errors are logged:
```
msg="Error parsing date field for month + day" date="2014- 6- 9" file="...m4a"
msg="Error parsing date field for month + day" date="2011- 9-27" file="...m4a"
msg="Error parsing date field for month + day" date="2014- 6- 9" file="....m4a"
msg="Error parsing date field for month + day" date=2013-00-00 file="....mp3"
```

### Expected Behavior

Navidrome should use its best efforts to accommodate these odd tags

### Steps To Reproduce

1. Have a file with a date format including these spaces instead of a zero for the date
2. Scan the library

### Environment

```markdown
- OS: Debian Linux / Docker
- Browser: Chrome
- Client: N/A
```

### How Navidrome is installed?

Docker

### Configuration

```toml
ND_SCANSCHEDULE: 24h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 48h
      ND_PLAYLISTSPATH: "**/Playlists/**"
      ND_ENABLEEXTERNALSERVICES: "true"
```

### Relevant log output

```shell
msg="Error parsing date field for month + day" date="2014- 6- 9" file="...m4a"
msg="Error parsing date field for month + day" date="2011- 9-27" file="...m4a"
msg="Error parsing date field for month + day" date="2014- 6- 9" file="....m4a"
msg="Error parsing date field for month + day" date=2013-00-00 file="....mp3"
```
```


### Anything else?

First, I think both of these date formats are improper.  Clearly a leading zero should be in the date (ie: 2014-06-09) and the 2013-00-00 should just be 2013.  That said, a surprising number of files, particularly M4A files, seem to have dates in this format, which makes me think it's out there, possibly produced by an Apple service or some tagger.

I do think that Navidrome, given that these formats are out there and appear to be pretty widely out there, should be able to interpret these dates, removing the month-day for the 00-00 and adding the 0's for the date with spaces.

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
> First, I think both of these date formats are improper.

Glad you acknowledge that :) 

There has been a lot of discussions regarding parsing dates and we decided to go with a strict validation: Dates can be in the formats `YYYY-MM-DD`, `YYYY-MM` or `YYYY`, padded with zeroes and that's it. Most if not all modern taggers use these formats (@certuna can keep me honest here)

I never saw the formats you are seen in the wild, and I even have a bunch of M4A files in my library, either bought from Apple or tagged with iTunes.

Having said that, I don't see any issues supporting these two (invalid) formats (`YYYY-00-00` and space-padded day and month), if @certuna does not see any issues with that.

I'll tag this issue as a `good-first-issue` and leave it as an exercise for new-comers to the project. The function that parses the date is found here: https://github.com/navidrome/navidrome/blob/1e5e8be19299422bbdd01931fefbabbf7c6b1965/scanner/metadata/metadata.go#L300

and its tests are here: https://github.com/navidrome/navidrome/blob/798b03eabd00d2153f44844d6715960afdb8d4ad/scanner/metadata/metadata_internal_test.go#L9-L27

One just need to add the necessary formats to the tests, and make the code works with it.

If anyone wants to work on this, feel free to submit a PR. Reach out if you have any questions.

**Comment by certuna** [comment]
Yeah these are invalid date formats, so they aren't parsed.

Up to you @deluan how much effort we want to put into the code to parse this. We'll never be able to catch all: `2001/12/31` or `12-31-2001` or `31.12.2001` or `Wednesday 31 December 2001`, there are infinite of ways that people can write off-spec dates in that frame.

**Comment by ChilledSlim** [comment]
I certainly think the 2023-00-00 is fairly common and I was shocked how many m4a’s had the spaces.

I think the 00-00 should be handled and treated as a year. I don’t really know if the one with spaces should be (as I agree it is wrong) but it just seems easy enough to detect.

many of the others aren’t used for tags as they’re not easily machine readable.

**Comment by michaelkrieger** [comment]
I certainly think the 2023-00-00 is fairly common and I was shocked how many m4a’s had the spaces.

I think the 00-00 should be handled and treated as a year. I don’t really know if the one with spaces should be (as I agree it is wrong) but it just seems easy enough to detect.

many of the others aren’t used for tags as they’re not easily machine readable.

**Comment by certuna** [comment]
`2023-00-00` and `2023- 1- 2` are already be parsed as `2023`, as you can see from the log, it only fails on the month+day part.
