### ISSUE TITLE
[Bug]: Navidrome can't find referenced songs  in playlists containing characters as äöü or é.

### ISSUE THREAD

**Issue by ElmarMuc** [navidrome/navidrome#2836]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

Navidrome can't find referenced songs in  containing characters as äöü or é.

### Current Behavior

I had already asked chatgpt to convert them to utf8. But it still not works. Have you got any idea? Probably escaping the characters? What kind of escape does Navidrome except?
It throws the following error message:
time="2024-01-30T23:30:39Z" level=warning msg="Path in playlist not found" error="data not found" path="/music/iTunes Music/Les Petits Chanteurs de Saint-Marc/Kinder des Monsieur Mathieu/08 Lueur D'été.mp3" playlist="Uwes _utf8"
time="2024-01-30T23:31:44Z" level=warning msg="Path in playlist not found" error="data not found" path="/music/iTunes Music/Zupfgeigenhansel/Miteinander/Nehmt abschied Brüder.mp3" playlist=Volkslieder_utf8

### Expected Behavior

Find the correct files.

### Environment

```markdown
- OS:Unraid
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
I'm pretty sure special characters are not the issue, as I have a lot of them myself, and here's an example:
```
$ cat Playlist_2836.m3u
Kraftwerk/Tone Float/01-06 Rückstoß Gondoliere.flac
Françoise Hardy/The Vogue Years/02-06 L’Amitié.mp3
Cazuza/Burguesia/01-06 Eu quero alguém.flac
```
![Screenshot 2024-01-31 at 6 56 32 PM](https://github.com/navidrome/navidrome/assets/331353/f04052da-9f8d-4d93-b65f-dccfa7da2309)


Maybe the paths are wrong? Can you Can you check the logs when you do a scan to import the playlist? You should see something like this:
```
time="2024-01-31T23:54:14Z" level=debug msg="Found playlist" lastUpdated="2024-01-31 23:54:01.565218547 +0000 UTC" name=Playlist_2836 numTracks=3 path=/music/library/Playlist_2836.m3u
time="2024-01-31T23:54:14Z" level=info msg="Adding synced playlist" owner=deluan path=/music/library/Playlist_2836.m3u playlist=Playlist_2836 requestId=38c8fe081ee4/yh55Wlb2Zx-003531 username=deluan
time="2024-01-31T23:54:14Z" level=debug msg="Imported playlist" lastUpdated="2024-01-31 23:54:01.565218547 +0000 UTC" name=Playlist_2836 numTracks=0 path=/music/library/Playlist_2836.m3u
```

**Comment by deluan** [comment]
Hey @ElmarMuc is this still an issue for you? Can I close this?

**Comment by deluan** [comment]
Closing as it is not reproducible. Let me know if you have any other concerns.

**Comment by ElmarMuc** [comment]
Still a problem Am 10.05.2024 um 23:42 schrieb Deluan Quintão ***@***.***>:﻿
Hey @ElmarMuc is this still an issue for you? Can I close this?
