### ISSUE TITLE
[Bug]: userRating, playCount and Starred are no longer returned in getPlaylist call..

### ISSUE THREAD

**Issue by 0bmay** [navidrome/navidrome#2841]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.51.0 (fd61b29a)

### Current Behavior

the fields UserRating, playCount and starred are no longer returned for songs in the getPlaylist call, possibly others..

### Expected Behavior

fields to be returned like previous versions...

### Environment

```markdown
- OS: ubundo - docker latest versions
- Browser:
- Client:
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by 0bmay** [comment]
sorry..  found a duplicate of this issue

**Comment by Menghini** [comment]
To help some future soul, the issue is #2819 which @0bmay is referring to.
