### ISSUE TITLE
Sharing feature does not work on mobile 

### ISSUE THREAD

**Issue by Retrockit** [navidrome/navidrome#2850]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.51.0

### Current Behavior

![image](https://github.com/navidrome/navidrome/assets/40707294/e22d7706-abb8-4e44-a824-546bef835166)

When sharing a track on mobile. This error populates, and sharing link does not get created

do not get this behavior on desktop browser. Sharing works on desktop browsers

### Expected Behavior

A mini pop-up in the webpage should come up saying “URL copied to clipboard: https://Linktosong.com/share/jwjxjdjd

### Steps To Reproduce

be on mobile phone

Click on three dots next to song or album

click share

In the pop-up press Shars

### Environment

```markdown
- OS: iOS 17.2.1
- Browser: Safari
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
I don't have an iOS to test it, but seems to be an issue with permissions on your phone. Maybe the issue is related to this? https://www.macrumors.com/2022/10/17/ios-16-1-paste-from-other-apps-settings/

Anyway, I can assure you this works (at least on Android):
![Screenshot 2024-02-10 at 9 23 38 PM](https://github.com/navidrome/navidrome/assets/331353/5341848c-0172-479b-a5e2-411d7a19500a)

**Comment by Retrockit** [comment]
> I don't have an iOS to test it, but seems to be an issue with permissions on your phone. Maybe the issue is related to this? https://www.macrumors.com/2022/10/17/ios-16-1-paste-from-other-apps-settings/
> 
> 
> 
> Anyway, I can assure you this works (at least on Android):
> 
> ![Screenshot 2024-02-10 at 9 23 38 PM](https://github.com/navidrome/navidrome/assets/331353/5341848c-0172-479b-a5e2-411d7a19500a)
> 
> 
> 
> 

I did do another test, but have my iPhone reach Navidrome over wireguard

The pop-up shows up when invoking the action on the wireguard IP, but not sure why it won't give that when on the public interface (at least on mobile)

Most strange

![image](https://github.com/navidrome/navidrome/assets/40707294/96ef1773-ea9b-419e-b19a-8dc8fa4401da)

**Comment by metalheim** [comment]
Browsers lock many features & permissions (such as a webapp beeing able to copy to clipboard) to websites with secure context (aka https with a valid cert)

**Comment by Stooovie** [comment]
Any tips for this? It would be enough to give the user a dialogue with the URL to copy manually. Right now, there's just an error banner that goes away too quickly to be able to copy the URL.

**Comment by dalloro** [comment]
Confirmed what @metalheim mentioned. It does not works when using a reverse proxy with valid certificate, but it does work when accessed via local ip:port. 

@Stooovie a workaround is to go to the Menu -> "Shares" -> [share that you just created] and copy the link from there. It is not ideal as it requires few "clicks", but I used it successfully in absence of a better solution.
