### ISSUE TITLE
[Bug]: Can't stream http://62.210.105.16:7000/stream?type=http

### ISSUE THREAD

**Issue by bilogic** [navidrome/navidrome#2856]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3 (8b93962f)

### Current Behavior

Most of my radio stations work except for http://62.210.105.16:7000/stream?type=http

### Expected Behavior

http://62.210.105.16:7000/stream?type=http should also stream as it works when loaded directly in Chrome

### Steps To Reproduce

Create a radio using http://62.210.105.16:7000/stream?type=http as the stream URL
Try to play it, won't work

### Environment

```markdown
- OS: Windows 10 22
- Browser: Chrome Version 121.0.6167.161 (Official Build) (64-bit)
- Client: Chrome Version 121.0.6167.161 (Official Build) (64-bit)
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
Sorry but not all radios are currently playable in Navidrome UI, because of errors caused by CORS or mixed content. This will be fixed when we have the option to proxy the radio through the server: #2187

**Comment by bilogic** [comment]
closing since it is being worked on in #2187
