### ISSUE TITLE
[Bug]: (webUI) Turning on replay gain downsamples song

### ISSUE THREAD

**Issue by rywng** [navidrome/navidrome#2865]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.51.0 (fd61b29a84117b4ab43cf6599a11d1d5110358a1)

### Current Behavior

In the navidrom webUI, when replay gain is set to album mode or track mode, the client will not only set the replay gain, but also downsample it to 44.1khz.

server log indicates that full file is sent without transcoding:

```
Feb 18 13:59:13 xxx navidrome[427]: time="2024-02-18T13:59:13+08:00" level=info msg="Streaming file" artist="xxx" bitRate=0 cached=false format=raw originalBitRate=3118 originalFormat=flac requestId=xxx/xxx title="xxx" transcoding=false user=xxx username=xxx
```

and in **firefox** web debugger's network panel, I can confirm that the raw audio file is indeed received, so seems to be a web client issue.

pw-top's output when replay-gain is **enabled**:
```
R   54    512  44100 216.7us   3.2us  0.02  0.00    0    S32LE 2 44100 alsa_output.usb-xxx-00.iec958-
R   70    826  44100 142.7us   9.6us  0.01  0.00    0    F32LE 2 44100  + LibreWolf
```

playing the same file, but replay-gain is **off** (also browser cache is cleaned):
```
R   54   8192 192000 211.5us   8.3us  0.00  0.00    0   S32LE 2 192000 alsa_output.usb-xxx-00.iec958-
R   70   8192 192000 147.3us  18.9us  0.00  0.00    0   F32LE 2 192000  + LibreWolf
```

### Expected Behavior

Turning on replay gain only change the gain of audio, but not downsampling. 

For example in [easyeffects](https://github.com/wwmm/easyeffects), when you enable effects, it changes the audio "in-place", without resampling, and the pw-top output of which looks like this:

```
R   53   1024  96000 630.2us   9.2us  0.06  0.00    0    S32LE 2 96000 alsa_output.usb-xxx-00.iec958-stereo
R   81      0	 0   3.3us   3.0us  0.00  0.00    0     F32P 2 96000  + easyeffects_sink
R   59      0	 0   1.7us   5.9us  0.00  0.00    0                   + ee_soe_output_level
R   72      0	 0   1.4us  81.3us  0.00  0.01    0                   + ee_soe_spectrum
R  105      0	 0 129.5us  73.0us  0.01  0.01    0                   + ee_soe_equalizer
R  109      0	 0   2.2us 111.5us  0.00  0.01    1                   + ee_soe_bass_enhancer
R  160      0  96000  52.5us  10.7us  0.00  0.00    0    S32LE 2 96000  + mpv
```

### Steps To Reproduce

1. Use **Firefox-based** browser, and clear cache
2. Change server config, although this should be reproducible even on default config
3. play any song with sample rate higher than 44.1khz, and check the stream sample rate using a tool like `pw-top` for `pipewire` on linux. By default replay-gain is off, so the sample rate should match the original audio file
4. click your avatar on right top corner > Personal > Replay Gain mode > set to `Use Album Gain` or `Use Track Gain`
5. Observe that the stream sample rate has been changed to _44.1khz_, indicating downsampling

### Environment

```markdown
- Client OS: Gentoo Linux (latest)
- Server OS: Arch Linux ARM (latest)
- Browser: Librewolf, Chromium
- Client: WebUI
```

### How Navidrome is installed?

Package

### Configuration

```toml
#
# https://www.navidrome.org/docs/usage/configuration-options/
#

# Folder to store application data (DB, cache…)
DataFolder = "/var/lib/navidrome"
MusicFolder = '/media/xxx'

Address = '127.0.0.1'
BaseUrl = 'https://xxx.com'

DefaultTheme = 'Spotify-ish'
EnableSharing = true
AutoImportPlaylists = false
SubsonicArtistParticipations = true

LastFM.Enabled = false
```

### Relevant log output

```shell
Feb 18 13:59:13 xxx navidrome[427]: time="2024-02-18T13:59:13+08:00" level=info msg="Streaming file" artist="xxx" bitRate=0 cached=false format=raw originalBitRate=3118 originalFormat=flac requestId=xxx/xxx title="xxx" transcoding=false user=xxx username=xxx
```

### Anything else?

**Note**: on **chromium**, audio is [always resampled to 48khz](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2828), so this bug only affects firefox users since chromium can't properly play hi-res audio.

i think the problem is explained well in the **current behaviour** section, and thanks for the awesome software :)

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
Thanks for reporting. This is the behaviour of the browser's media player, and we don't have much control over it. The example you posted (easyeffects) does not run in the browser, so it is not a apples to apples comparison.

Also note that we are working on a new UI/Player, so there won't be any significant work done on the current UI anymore. I'll keep this issue in mind when working on the new player, and will check if this is something that can be changed.

Closing this now as "Won't fix", but if anyone finds a simple way to change the player without much change/refactoring, let me know.
