### ISSUE TITLE
[Bug]: Quality Info does not display actual ReplayGain in all scenarios

### ISSUE THREAD

**Issue by NaanProphet** [navidrome/navidrome#2870]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.51.0 (fd61b29a)

### Current Behavior

Hello first of all thanks to everyone who contributed to https://github.com/navidrome/navidrome/pull/1988 and made ReplayGain support possible!

I was going through https://github.com/navidrome/navidrome/commit/1324a16fc534d2de0ccd7d1ebc0d5020b4e38af6 and there is a discrepancy between how the actual gain is calculated and what is displayed in the Quality Info hover. Tthis occurs when there is a positive gain but the peak is at or near 1.

Just to illustrate, I tagged a peak 0 dB file with album gain +10 dB and track gain -10 dB. I left the preamp gain at 0 dB in the Navidrome web browser.

* If I apply album gain, the volume does not change, even though hovering over the track name shows `<bitrate> 10 dB`.
* If I switch to track gain, hovering over the title shows `<bitrate> -10 dB` and the sound actually sounds softer.

### Expected Behavior

**Option 1**

Instead of determining Quality Info solely using the tags:

https://github.com/navidrome/navidrome/blob/1324a16fc534d2de0ccd7d1ebc0d5020b4e38af6/ui/src/common/QualityInfo.js#L35-L39

Display the same value as returned by the `calculateReplayGain` function:

https://github.com/navidrome/navidrome/blob/1324a16fc534d2de0ccd7d1ebc0d5020b4e38af6/ui/src/audioplayer/Player.js#L27-L35

**Option 2**

Provide the user the option to ignore peak tags

### Steps To Reproduce

1. Enable ReplayGain in Navidrome
2. Tag a file where Peak = 1 (no headroom) and Replay Gain value is > 0 dB
3. Leave Navidrome Preamp = 0 dB
4. Playback the file in Navidrome Web Client
5. There is no volume change but Quality Info suggests there is

### Environment

```markdown
- OS: macOS Sonoma 14.2.1 (23C71)
- Browser: Safari Version 17.2.1 (19617.1.17.11.12)
- Client: Navidrome Web Client
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by GuoYuefei** [comment]
EnableReplayGain = false
but have same

**Comment by NaanProphet** [comment]
Hi, I would still like to keep this issue open. I am willing to open a PR for it though. Appreciate if anyone can weigh in what they would like to see in the scenario given above

**Comment by deluan** [comment]
Thanks for raising this. I personally don't use ReplayGain (yet), so I don't know what would be the best approach. 

@kgarner7 any thoughts?

**Comment by deluan** [comment]
Hey @NaanProphet, can you please test the PR?
