### ISSUE TITLE
[Bug]: Favorites not showing in any android clients

### ISSUE THREAD

**Issue by webmind** [navidrome/navidrome#2871]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.51.1_linux_amd64

### Current Behavior

I can select the heart/favorite buttons within the webUI and then sort as favorite in the webUI. However neither in DSub, Ultrasonic or Tempo these files are listed under favorite. When I favorite a song in one of these apps, the other apps see them, but not in the webUI. 

This is all about favoriting songs, not albums or artists.

### Expected Behavior

When I favorite a song in any client, whether it's android app, desktop app or webUI to get the same list of favorites.

### Steps To Reproduce

1) favorite a song in the webUI
2) look in android client
3) see song not being favorites

### Environment

```markdown
- OS:Debian bookworm
- Browser: Firefox 121
- Client: react

- OS:Android 14
- Browser: n/a
- Client: dsub/tempo/ultrasonic
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
MusicFolder = "/srv/P3TB/music"
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by metalheim** [comment]
Dumb question, but are logged in as the same User in your Apps and in the webUI?

**Comment by Tolriq** [comment]
https://support.symfonium.app/t/symfomium-ratings-favorites-not-being-set-in-navidrome/3555

Got a similar kind of report, but can't repro.

Could the db migration have duplicated users and using different IDs for web interface and subsonic API.

**Comment by deluan** [comment]
This really seams to be caused by using different users for mobile and webui, @webmind please confirm.

@Tolriq without logs that one is hard to figure out, but as you pointed out on that issue, it could be caused by the DB issues solved in 0.51.1.

> Could the db migration have duplicated users and using different IDs for web interface and subsonic API.

Last time there was a migration changing anything in the user table was 2021, so no, there's no way for users to be duplicated by a bug in any recent migrations.

**Comment by Prankish8407** [comment]
To clarify on my post --> https://i.imgur.com/AbsThm0.png

**Comment by webmind** [comment]
> Dumb question maybe, but are logged in as the same User in your Apps and in the webUI?
> 
> Are you actually favoriting "Songs" in the Webui and not albums?

Yeah sorry, that was the issue. Still logged in as admin in the webUI... *facepalm*
