### ISSUE TITLE
[Idea] : Retro music in Navidrome

### ISSUE THREAD

**Issue by Beulu** [navidrome/navidrome#2894]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

Latest

### Current Behavior

Navidrome reading vgm, vgz, gym...

### Expected Behavior

This new feature ^^

### How Navidrome is installed?

Docker

- [X] I agree to follow Navidrome's Code of Conduct

Hi !

I saw this closed conversation : https://github.com/navidrome/navidrome/issues/1929 and I jsut ask why you don't insert source code of Game Music Emu in Navidrome (or for a plug in ?)

Thanks !

P.S. : sorry for the bug tag :\

**Comment by risalt** [comment]
+1 😀

**Comment by hologarden** [comment]
Likely too little demand for it to be implemented. As seen in #1929:
### [...] taglib does not support reading those formats yet. Thank you for your ideas though!
Though it has been referenced in the issues of the [official taglib repo.](https://github.com/taglib/taglib/issues/871) You could always try forking Navidrome to try implementing the feature on your own!

**Comment by deluan** [comment]
If `ffmpeg` support these formats, you can change your extractor to `ffmpeg` (`ND_SCANNER_EXTRACTOR=ffmpeg`).

You would also need to add the mime types to your system. You may try to override the `mime_types.yaml` file (only in development builds) by creating a `resources` directory under the same directory that holds your `navidrome.db` file, and create a modified coy of the `mime_types.yaml` inside it:

```
data_folder/
  navidrome.db
  resources/
     mime_types.yaml
```

Anyway, closing this as there is nothing much that Navidrome can do if `taglib` or `ffmpeg` do not support these file formats.

**Comment by Beulu** [comment]
Thanks all for your answers.

deluan : you mean I need to code ? Because I can't ? Or is this just a configuration by file/options modifications ?

**Comment by deluan** [comment]
No coding required, you just need to create a copy of the [mime_types.yaml](https://raw.githubusercontent.com/navidrome/navidrome/master/resources/mime_types.yaml) file in the folder I mentioned above, and add the mime type for the file types you want. 

Example, for vgm file format, I googled "vgm mime type" and found this: https://www.digipres.org/formats/sources/wikidata/formats/#q105863074

So you would add a line in the `mime_type.yaml` file like this in the "types" section:
```
...
  .vgm: audio/x-mod
```

But this will only work if `ffmpeg` can recognize the file. You can test it by going to the command line and running:
```
ffmpeg -i your_file.vgm
```

and check if it shows valid information about the file, like title, artist, album. If not, the files will be impoirted, but will be classified as `Unknown Artist/Unknown Album`

Hope this helps.

**Comment by Beulu** [comment]
OK, with Windows and command bat I got this :

![image](https://github.com/navidrome/navidrome/assets/72515988/2ff05b95-75a4-4b50-ba0d-364550549f96)

Seems ffmpeg reads .vgm.

Great, got this too :

![image](https://github.com/navidrome/navidrome/assets/72515988/0a17062d-d070-43f4-9135-591a194b599d)

Seems ffmpeg reads .vgz !

VLC needs to "unzip" .vgz to be read (and take more space disk)

I'm sorry in advance because configuration is not my best part. Working on it. Try to investigate your method.

Thanks again !

**Comment by deluan** [comment]
Good news is that `ffmpeg` can read metadata. Bad news is that your files are using non-standard tags: `song` for `title`, `author` for `artist`. So Navidrome won't be able to map these correctly. You'll need to change it to match standard tags.

**Comment by Beulu** [comment]
Damn ! I'm not motivated to change those metadata for all files. Maybe if I find a library with modified tags.

You mean if I upgrade mime_types.yaml navidrome will read game musics, even if metadatas are not good ? Is it possible to add it for future updates ? Is it possible to convert song to title and author for artist automatically for all those specific files ?

Thanks !

**Comment by deluan** [comment]
> You mean if I upgrade mime_types.yaml navidrome will read game musics, even if metadatas are not good ? 

Yes, but they will show as `Unknown Artist/Unknown Album`

> Is it possible to add it for future updates ?

In the new scanner I'm working on (#2709), you'll be able to map tags similar to how you map mime types. So yes, you'll be able to configure this.

> Is it possible to convert song to title and author for artist automatically for all those specific files ?

Maybe you can find a tool that does the mapping for you? I _think_ you may use MusicBrainz Picard for that, or maybe other taggers, but I'm not sure.

**Comment by Beulu** [comment]
> > You mean if I upgrade mime_types.yaml navidrome will read game musics, even if metadatas are not good ?
> 
> Yes, but they will show as `Unknown Artist/Unknown Album`
> 
Nevermind ! (for the moment ^^)

> > Is it possible to add it for future updates ?
> 
> In the new scanner I'm working on (#2709), you'll be able to map tags similar to how you map mime types. So yes, you'll be able to configure this.
> 
Great news ! I was stucked on hologarden response.

> > Is it possible to convert song to title and author for artist automatically for all those specific files ?
> 
> Maybe you can find a tool that does the mapping for you? I _think_ you may use MusicBrainz Picard for that, or maybe other taggers, but I'm not sure.
I'll checked with Musicbee, maybe try MusicBrainz and/or find a good place to download welltag albums.

I really would try if it's working but i'm not sure about linux manipulations and don't want to break everything...
