### ISSUE TITLE
[Bug]: The Enable Last.fm Preferences switch cannot be turned on

### ISSUE THREAD

**Issue by autunn** [navidrome/navidrome#2939]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.51.1

### Current Behavior

The Enable Last.fm Preferences switch cannot be turned on，Tips on the lastfm website“Invalid API key. If you are a third party developer see our authentication how-to to find out more.”

### Expected Behavior

The Enable Last.fm Preferences switch cannot be turned on，Tips on the lastfm website“Invalid API key. If you are a third party developer see our authentication how-to to find out more.”

### Environment

```markdown
- OS:
- Browser:
- Client:
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by metalheim** [comment]
Please share your configuration (either config file or docker run/docker compose). 
Otherwise it is Impossible to troubleshoot your issue.

My guess so far is that you do not correctly have a lastfm Apikey configured. Similar to this issue here:

https://github.com/navidrome/navidrome/discussions/2938#discussioncomment-9027688

**Comment by autunn** [comment]
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1026:100
    ports:
      - "4533:4533"
    volumes:
      - "/volume1/docker/navidrome/data:/data"
      - "/volume3/Video/Media/MUSIC:/music:ro"
    environment:
      - ND_SCANSCHEDULE=6m  # 扫描频率
      - ND_DEFAULTLANGUAGE=zh-Hans  # 默认语言
      - ND_ENABLEGRAVATAR=true  # 启用 Gravatar 功能
      - ND_ENABLECOVERANIMATION=true  # 启用封面动画功能
      - ND_ENABLEDOWNLOADS=true  # 启用下载功能
      - ND_ENABLETRANSCODINGCONFIG=false  # 关闭转码功能
      - ND_SPOTIFY_ID=17917e811d1----------------0cc257b05  # Spotify API ID
      - ND_SPOTIFY_SECRET=ee0c876f----------------0f7e8eb36  # Spotify API 密钥
      - ND_LASTFM_ENABLED=true  # 启用 Last.fm 功能，留空表示启用
      - ND_LASTFM_LANGUAGE=zh  # Last.fm 语言设置
      - ND_LASTFM_APIKEY=68a8491c5----------------02621d27ddc  # Last.fm API 密钥
      - ND_LASTFM_SECRET=720818cc----------------06284  # Last.fm 密钥
      - ND_LOGLEVEL=info  # 日志级别设置
      - ND_SESSIONTIMEOUT=24h  # 会话超时时间设置
      - HTTP_PROXY=http://192.168.1.224:7890  # HTTP 代理设置
      - HTTPS_PROXY=http://192.168.1.224:7890  # HTTPS 代理设置
    restart: unless-stopped  # 容器重启策略

**Comment by autunn** [comment]
After refreshing the browser cache, I have solved the problem that the "Enable Last.fm Preferences" switch won't turn on, but some artists in my Navidrome still can't get their avatars or profiles, both of which are available on last.fm or spotify

**Comment by autunn** [comment]
![Uploading 1.png…]()
A profile picture but no profile

**Comment by autunn** [comment]
![Uploading 1.png…]()
A profile picture but no profile

**Comment by autunn** [comment]
No profile picture, no profile
![Uploading 2.png…]()

**Comment by autunn** [comment]
There is a profile but no profile picture
![Uploading 3.png…]()

**Comment by kgarner7** [comment]
Artist images are only available from
Spotify API

**Comment by deluan** [comment]
Seems that this was resolved.
