### ISSUE TITLE
[Bug]: IOS device unable to play

### ISSUE THREAD

**Issue by icfy-dmc** [navidrome/navidrome#2944]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.51.1 (6d253225)

### Current Behavior

Unable to play any tracks after logging in with iOS device
Always loading
![image](https://github.com/navidrome/navidrome/assets/55734511/2ef95333-4f99-4d7a-9ebd-807fa0c451a0)

### Expected Behavior

Normal playback

### Steps To Reproduce

1. Login
2. Click on any song

### Environment

```markdown
- OS: Ubuntu 22.04.1 LTS (GNU/Linux 5.17.15-edge x86_64)
- Browser: ios safari、ios chrome、WeChat browser
- Client:
```

### How Navidrome is installed?

Docker

### Configuration

```toml
version: "3"
services:
  navidrome:
    image: deluan/navidrome:0.51.1
    container_name: navidrome
    user: 1000:1000 # should be owner of volumes
    ports:
      - 4533:4533
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      ND_DEFAULTLANGUAGE: zh-Hans
      ND_DEFAULTTHEME: Ligera
    volumes:
      - /root/navidrome/data:/data
      - /mnt/nas/music:/music:ro
```

### Relevant log output

```shell
time="2024-04-08T08:05:56Z" level=info msg="Streaming file" artist="陈楚生,王栎鑫,陆虎,张远,俞灏明" bitRate=0 cached=false format=raw originalBitRate=320 originalFormat=mp3 requestId=3b95411af9af/hVdmz4iKnr-018606 title="直到世界尽头 (Live)" transcoding=false user=guestDemo username=guestDemo
time="2024-04-08T08:05:56Z" level=info msg="Streaming file" artist="陈楚生,王栎鑫,陆虎,张远,俞灏明" bitRate=0 cached=false format=raw originalBitRate=320 originalFormat=mp3 requestId=3b95411af9af/hVdmz4iKnr-018607 title="直到世界尽头 (Live)" transcoding=false user=guestDemo username=guestDemo
time="2024-04-08T08:05:56Z" level=info msg="Streaming file" artist="陈楚生,王栎鑫,陆虎,张远,俞灏明" bitRate=0 cached=false format=raw originalBitRate=320 originalFormat=mp3 requestId=3b95411af9af/hVdmz4iKnr-018608 title="直到世界尽头 (Live)" transcoding=false user=guestDemo username=guestDemo
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by icfy-dmc** [comment]
I tested other brands of mobile phones, and the functionality is normal
Samsung and Xiaomi

**Comment by happyTonakai** [comment]
What client app are you using? It seems the server works well according to the log output.

**Comment by fl4co** [comment]
I have the same problem, endless spinning as shown in the picture by OP and song never starts. No errors in the logs, neither original nor transcoded will play.

It happens only in the Web UI (tested Safari and Firefox), iOS clients such as substreamer or Amperfy work fine.

**Comment by fl4co** [comment]
I can add more details: if shared files are opened in a iOS browser (Safari tested), the playback won't start. However, if downloading is allowed in the sharing options then the playback will start when the download button is activated, instead of triggering a file download.

**Comment by icfy-dmc** [comment]
> What client app are you using? It seems the server works well according to the log output.

I tried both iPhone 15 Pro and iPhone 13 Mini and it didn't play (iOS 17.4.1)
But I tried to use the iPad and found it to be normal

**Comment by estebanmedinao** [comment]
any solution for the problem, iOS is not playing

**Comment by MonzterDev** [comment]
Can confirm this as well.

**Comment by YesThatAllen** [comment]
We're having this as well.. our site is hosted on Pikapod.
[0.51.1](6d253225)

I wonder if people are experiencing this only on recent iOS, or if it's a recent change in navidrome…

I can sometimes get Chrome to play after refreshing, but I can't get Safari to play at all:


```
time="2024-04-24T02:50:23Z" level=info msg="Streaming file" artist="Lead Tracks" bitRate=0 cached=false format=raw originalBitRate=192 originalFormat=mp3 requestId=d2695c99c40c/gJ8Dym2IqZ-014566 title="Little Patch Of Heaven - Lead Predominant" transcoding=false user=UNKNOWN
```

I restarted the pod, but that didn't seem to have an affect.

**Comment by estebanmedinao** [comment]
Resultado de traducción
I also have it hosted on pikapods, I thought that might be the only problem there, but even the navidrome demo on the official website doesn't work on iOS either.

**Comment by deluan** [comment]
For those with this issue, this is the problem: 

> The issue started with iOS 17.4.1. The iPad works but iPhone 13 Pro doesn’t. I tried different browsers but this happens on Chrome and Safari. 

We are not looking into fix this, as we are working on a new UI, with a new player. So, unless someone wants to jump in and try to fix it, the workaround is to use a native client for iOS. Some options:

[play:Sub](http://michaelsapps.dk/playsubapp/)
[substreamer](https://substreamerapp.com/)
[Amperfy](https://github.com/BLeeEZ/amperfy#readme)
[iSub](https://isub.app/)

**Comment by estebanmedinao** [comment]
Pude hacer que el reproductor web funcionara en iOS 17.4.1 en las funciones de configuración de Safari, desactive "alternate WebM Player"  Con eso se carga sin problemas en iOS 17.4.1 ![ IMG_0303]
(https://github.com/navidrome/navidrome/assets/8879013/ed40784f-2d28-4145-8899-6ad8b42312b0)

**Comment by johnelliott** [comment]
> I was able to get the web player to work on iOS 17.4.1 in Safari settings functions, disable "alternate WebM Player"
> 
> With that it loads without problems in iOS 17.4.1
> 
> [ IMG_0303](https://github.com/navidrome/navidrome/assets/8879013/ed40784f-2d28-4145-8899-6ad8b42312b0)

Thanks so much, this was super annoying and I took to debugging mobile safari with a USB cable to see that the stream just wasn't working. This fixed it for me.

**Comment by Joesepherus** [comment]
> I was able to get the web player to work on iOS 17.4.1 in Safari settings functions, disable "alternate WebM Player"
> 
> With that it loads without problems in iOS 17.4.1
> 
> [ IMG_0303] (https://github.com/navidrome/navidrome/assets/8879013/ed40784f-2d28-4145-8899-6ad8b42312b0)

Very nice! That's working for me. I knew safari was doing something crazy again. Thanks!

**Comment by sharpsteelsoftware** [comment]
This is happening to my friend too she has iOS 11. Plays fine on all her other devices (tablet, windows) and on my devices (linux, mac, android).

**Comment by YesThatAllen** [comment]
iOS 17.5 appears to have resolved the issue for me (no need to adjust the `alternate WebM Player` settings)
