### ISSUE TITLE
Ability to persist or store the row per page value.

### ISSUE THREAD

**Issue by themitchnz** [navidrome/navidrome#295]
The default of 15 rows per page may not be the ideal value for all users. It would be nice to be able to set your own value and/or save the change.

Personally I would be happy with 1 value across Artist/Album/Songs but I would go with any implementation.

**Comment by deluan** [comment]
I pushed a change in 9490374 to save the `perPage` selection in the localStorage. Can you please test it? Binaries are here: https://github.com/deluan/navidrome/actions/runs/105293156, and it is in the latest `develop` Docker image

**Comment by deluan** [comment]
Unfortunately this cannot be achieved by saving the React Admin state to localStorage. I reverted the commit and will keep this in the backlog.

**Comment by legobuild** [comment]
I just made a comment on #132 about this. Would it be possible to add a few higher options than 50?
