### ISSUE TITLE
[Bug]: Data reset after docker-compose restart!

### ISSUE THREAD

**Issue by gangstareloading** [navidrome/navidrome#2965]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

v0.51.1

### Current Behavior

restarting the navidrome docker container causes all data to be lost.
songs get rescanned
all users deleted

### Expected Behavior

restarting should keep all users data.
songs may get rescanned
users accounts should stay

### Steps To Reproduce

1. create a docker-compose file with the service:

```navidrome_service:
 image: (image_id)
 ports:
     - "4533:4533"
 volumes:
     - "/home/music/Music/some_music:/music"
```

2. run it and create some accounts and listen to some music
3. restart it (docker-compose restart)
4. everything's gone :(

### Environment

```markdown
- OS:Ubuntu 20.04 latest
- Browser: Firefox
- Client: same OS & broweser.
```

### How Navidrome is installed?

Docker

### Configuration

```toml
version: '3.9'
services:
navidrome_service:
 image: (image_id)
 ports:
     - "4533:4533"
 volumes:
     - "/home/music/Music/some_music:/music"
```

### Anything else?

everything at the /data folder (outside the container) got deleted.

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
You need to map a volume for your `data` folder, or else it will be a ephemeral space inside the container. Ex:

```
    volumes:
      - "/home/music/Music/some_music:/music"
      - "/path/to/data:/data"
```

See https://www.navidrome.org/docs/installation/docker/ for more info on using Navidrome with Docker.
