### ISSUE TITLE
[Bug]: playlist comment spoiler causes misplacement of playlist info

### ISSUE THREAD

**Issue by metalheim** [navidrome/navidrome#2992]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.52.0-SNAPSHOT (7c5eec71)

### Current Behavior

The PR #2973 works well on long playlist comments, but if you have a short playlist comment that doesnt need a spoiler (f.e. just one line), it causes the "Playlist info" (# of songs, length and size) to float right and wrap line.
That looks ugly.

Short playlist comment (1 line)
![image](https://github.com/navidrome/navidrome/assets/44159957/16ae8699-750d-4dbc-9fc5-9c8e36dbf248)

Long playlist comment (OK)
![image](https://github.com/navidrome/navidrome/assets/44159957/78f23c74-1f4c-4254-ae51-68cbba30ff16)

### Expected Behavior

Playlist info to not look ugly and dont wrap lines.
Maybe just put it above the comment to solve the issue easily?

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by TimHi** [comment]
That is indeed ugly. 👀I have the next week off, I'll probably find time to look into it.

**Comment by deluan** [comment]
No worries, was a quick fix.

**Comment by metalheim** [comment]
Lovely, thanks!
