### ISSUE TITLE
[Bug]: The retrieval of data fails when sorting by createAt after the number of songs exceeds 50,000.

### ISSUE THREAD

**Issue by gitbobobo** [navidrome/navidrome#3006]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.52.0 (92a98cd5)

### Current Behavior

This bug can be triggered on the web page of Navidrome:  

1. Enter the list of all songs.
2. Scroll to the second page, at this point the browser's URL will have some additional request parameters: `filter=%7B%7D&order=ASC&page=2&perPage=15&sort=title`
3. Change `sort=title` to `sort=createdAt`, press enter to trigger the request, the page should be able to receive data and update normally.
4. Then modify the values of `page` and `perPage` so that the result of page * perPage is greater than 50,000, press enter and you will see an error on the page.
5. But changing `sort=createdAt` back to `sort=title` will make everything normal again.

![](https://private-user-images.githubusercontent.com/57163257/328739400-037028e7-5b57-419f-8732-aa5ba2c8a898.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzc4NDksIm5iZiI6MTcxNTEzNzU0OSwicGF0aCI6Ii81NzE2MzI1Ny8zMjg3Mzk0MDAtMDM3MDI4ZTctNWI1Ny00MTlmLTg3MzItYWE1YmEyYzhhODk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAzMDU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MmJkZDZmMmYzZTNjM2Q5NWVmMDZmYTM4Y2YzMDk5NzZkYTUzODA0MWIzY2VmMjJlNDRkZTJiODE0ZmIyYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oU8hOTpg4uZQQaAVNtqvBlsyVLig5jew6ZwVrepcpUA)

### Expected Behavior

Can normally retrieve songs after the 50,000th one using the createdAt sorting method.

### Environment

```markdown
- OS: DSM 7.2
- Client: StreamMusic

([StreamMusic](https://github.com/gitbobobo/StreamMusic) is a software I developed. It connects through the Navidrome API instead of the Subsonic API. The `api/song?_sort=createdAt` interface is used for incremental synchronization, which can reduce the waiting time for users. Therefore, in my view, it is very necessary for this interface to function properly.)
```

### How Navidrome is installed?

Docker

### Relevant log output

```shell
2024/05/08 10:13:10 ERRO[37483] SQL: SELECT coalesce(starred, 0) as starred, coalesce(rating, 0) as rating, coalesce(play_count, 0) as play_count, starred_at, play_date, media_file.*, coalesce(position, 0) as bookmark_position FROM media_file LEFT JOIN annotation on (annotation.item_id = media_file.id AND annotation.item_type = 'media_file' AND annotation.user_id = 'd667af88-6315-4166-94bb-64242a552837') LEFT JOIN bookmark on (bookmark.item_id = media_file.id AND bookmark.item_type = 'media_file' AND bookmark.user_id = 'd667af88-6315-4166-94bb-64242a552837') WHERE media_file.oid not in (SELECT media_file.oid FROM media_file LEFT JOIN annotation on (annotation.item_id = media_file.id AND annotation.item_type = 'media_file' AND annotation.user_id = 'd667af88-6315-4166-94bb-64242a552837') LEFT JOIN bookmark on (bookmark.item_id = media_file.id AND bookmark.item_type = 'media_file' AND bookmark.user_id = 'd667af88-6315-4166-94bb-64242a552837') ORDER BY created_at asc LIMIT 50250) ORDER BY created_at asc LIMIT 50 args="map[]" elapsedTime="147.951µs" error="ambiguous column name: created_at" requestId=navidrome/mmaRXnnph2-003519 rowsAffected=-1 username=Navidromeadmin

2024/05/08 10:13:10 2024/05/08 02:13:10 Error reading mediafile: ambiguous column name: created_at

2024/05/08 10:13:10 ERRO[37483] HTTP: GET http://192.168.124.11:4533/api/song?_end=50300&_order=ASC&_sort=createdAt&_start=50250 elapsedTime=46.7ms httpStatus=500 remoteAddr="172.28.0.1:38218" requestId=navidrome/mmaRXnnph2-003519 responseSize=49
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
It is not about the size, the `createdAt` column seems to be causing conflicts in the generated SQL: 
```
2024/05/08 11:54:13 Error reading mediafile: ambiguous column name: created_at
```
