### ISSUE TITLE
UPnP/DLNA support

### ISSUE THREAD

**Issue by Kernald** [navidrome/navidrome#305]
This might be outside of Navidrome's scope, but #250 and #280 make me think that it might not be a stupid idea. I have a few speakers at home that act as UPnP receivers. I've been looking for a way to control them from a desktop software/web app for a while, and an integration in Navidrome would be really cool to see.

**Comment by deluan** [comment]
My priority in terms of streaming protocol will be Chromecast (#250). Depending on how much effort it will be to add it, I may take a look at other protocols. I'll leave this open in case someone has some other thoughts to share, or wants to contribute.

**Comment by sabamimi** [comment]
My programming skills a little bit rusty , but I will try .... (now retired with plenty of time)

**Comment by certuna** [comment]
I know there's still quite a lot of older DLNA/UPnP hardware around, but I'm having some doubts how useful is it to put in the work to develop that if all current speakers/receivers either do ChromeCast, AirPlay or Bluetooth?

**Comment by metalheim** [comment]
> I know there's still quite a lot of older DLNA/UPnP hardware around, but I'm having some doubts how useful is it to put in the work to develop that if all current speakers/receivers either do ChromeCast, AirPlay or Bluetooth?

The Amazon firetv devices only do dlna/upnp :(

**Comment by sabamimi** [comment]
I did solve this by using a upnp/dlna package using the same media shared
folder.
In my case Navidrome is running in a docket in Open Media Vault and it has
a plugin for UPnP/DLNA
So that is my work around
In case it helps
Kind regards

Le jeu. 13 mai 2021 à 14:26, Stephan Wahlen ***@***.***> a
écrit :

**Comment by metalheim** [comment]
@sabamimi thanks, I also have an instance of `minidlna` running in parallel to navidrome. It works, but isn't very elegant (Metadata scanning, storing and interpretation is done twice, favorites and playlists aren't available) 
Also, navidrome handles metadata much better than most other software.

I see there's many different workarounds (dsub->dlna casting, parallel dlna server) so this isn't a priority for navidrome.
Just wanted to show, that there would be appreciation for it :)

**Comment by bjhiltbrand** [comment]
As someone looking to migrate from Airsonic, the biggest thing holding me back from moving to Navidrome is the lack of DLNA support. I use DLNA to stream to my A/V Receiver fairly regularly, and this would be a great feature to bring in to Navidrome.

**Comment by HeaDBanGer84** [comment]
DLNA would be great, but airplay would be also fine for me.

**Comment by make-nz** [comment]
There are plenty semi old devices which make great DLNA Media Renderer and they may be dear friends to those people who are using them.

There are also YAMAHA, DENON and others HiFi Receivers / TVs well above a $500-$1500 price range people do not want to throw out.

And all the Desktop-Player supporting DLNA… 

A Logitech Media Server(with SqueezeSonic 0.6 plugin) and 3 Squeezebox Radios is a great setup,
but in my family we run 11 TVs, HiFis, Streaming Boxes… all connecting to the Subsonic Server via DLNA.

So, in my opinion, there is a huge range of existing DLNA users, but less users going for the new stuff they do not have (yet)-
New is tempting — I'm here at navidrome ;-)  But old stuff just works… and switching out a server just make more sense — again, in my opinion.

So thanks for the work and I'm looking forward seeing DLNA added

Cheers

**Comment by raudraido** [comment]
I do not even understand how someone could but "music streaming" and "chromecast" in the same sentence. There is no professional equipment with chromecast in it as fas as I know.  I did install Jellyfin only for DLNA support. Also Im using firefox when streaming form PC and when I choose where to cast, it says "google cast not available", cause of google of course. It's available in Chrome.

**Comment by Kernald** [comment]
"Professional" equipment or not isn't the question. The fact is, Chromecasts are popular devices. While I don't use them myself any regularly, the prioritization makes sense.

I also assume such an implementation would take place on the back-end, which makes your rant about browser-specific support irrelevant.

**Comment by AIndoria** [comment]
> I do not even understand how someone could use "music streaming" and "chromecast" in the same sentence. There is no professional equipment with chromecast in it as fas as I know. 

Are you so unfamiliar with the recent technological developments and how people use them? The popularity of smart speakers has exploded. It's become very commonplace to cast/stream your music to smart speakers, devices etc.

Hell, we use audiobookshelf to cast audiobooks to our bedroom speakers when we sleep for example.

**Comment by raudraido** [comment]
> Are you so unfamiliar with the recent technological developments and how people use them? The popularity of smart speakers has exploded. It's become very commonplace to cast/stream your music to smart speakers, devices etc.
> 
> Hell, we use audiobookshelf to cast audiobooks to our bedroom speakers when we sleep for example.

I'm very familiar with tech developments. I assume that a good portion of navidrome users are more than a typical average music listener and maybe wants listen more than a BT wireless crappy compressed audio with mono speaker. I even think they have some special equipment for listening music.. and I doubt that equipment supports chromecast...

**Comment by Kernald** [comment]
Can we maybe stop with the unjustified elitism here? Maybe you don't use Chromecast compatible speakers, maybe some people do, who cares. If you think something else should be prioritised, maybe submit a pull request for that feature?

**Comment by AIndoria** [comment]
Yeah I really don't get it. "we better people who use this software  use $4000 speakers and you plebe with your $150 speakers should not get this feature" is a weird POV.

>more than a typical average music listener 

Something something 200 IQ Rick and Morty copypasta here.

-----

I really don't understand when people fight against features. If **you** don't use it, fine. Why are you against letting **others** use it as well? It's not a zero sum game, and it doesn't make your experience less if others get a feature that you will never use.

**Comment by deluan** [comment]
Can we please stop the discussion? I get enough notifications about _valid_ issues and feedback, don't need to receive 5 messages a day about an irrelevant discussion. I don't want to start locking conversations, but I'll do if needed. Thanks.

**Comment by AIndoria** [comment]
There are 15 comments over the course of 2.5 years, but fair enough. Albeit I'm just curious why you think advocating for a certain feature is 'invalid' feedback.
