### ISSUE TITLE
[Bug]: "Something went wrong" error in artists tab

### ISSUE THREAD

**Issue by DECsystem20** [navidrome/navidrome#3070]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.52.5

### Current Behavior

Hello! I often get the error "Something went wrong. A client error occurred and your request couldn't be completed." when I navigate to artists tab. I found similar, closed issue here: https://github.com/navidrome/navidrome/issues/776, but my stacktrace is slightly different.

### Expected Behavior

I could list and search artists.

### Steps To Reproduce

Open the "Artists" tab or search for an artist if it is already open.

### Environment

```markdown
- OS: MacOS 12.1
- Browser: Chrome 125.0.6422.141
```

### How Navidrome is installed?

Docker

### Relevant log output

```shell
main.3a9220d3.js:2 TypeError: Cannot read properties of undefined (reading 'size')
    at p_ (main.3a9220d3.js:2:1120252)
    at si (main.3a9220d3.js:2:340881)
    at Gs (main.3a9220d3.js:2:393181)
    at Tl (main.3a9220d3.js:2:380422)
    at jl (main.3a9220d3.js:2:380350)
    at Pl (main.3a9220d3.js:2:380213)
    at bl (main.3a9220d3.js:2:377179)
    at main.3a9220d3.js:2:326673
    at t.unstable_runWithPriority (main.3a9220d3.js:2:525995)
    at Ko (main.3a9220d3.js:2:326450)
cs @ main.3a9220d3.js:2
a.componentDidCatch.n.callback @ main.3a9220d3.js:2
ma @ main.3a9220d3.js:2
gs @ main.3a9220d3.js:2
Nl @ main.3a9220d3.js:2
t.unstable_runWithPriority @ main.3a9220d3.js:2
Ko @ main.3a9220d3.js:2
Il @ main.3a9220d3.js:2
bl @ main.3a9220d3.js:2
(anonymous) @ main.3a9220d3.js:2
t.unstable_runWithPriority @ main.3a9220d3.js:2
Ko @ main.3a9220d3.js:2
$o @ main.3a9220d3.js:2
Yo @ main.3a9220d3.js:2
Fl @ main.3a9220d3.js:2
t.unstable_runWithPriority @ main.3a9220d3.js:2
Ko @ main.3a9220d3.js:2
Ml @ main.3a9220d3.js:2
(anonymous) @ main.3a9220d3.js:2
D @ main.3a9220d3.js:2
x.port1.onmessage @ main.3a9220d3.js:2
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by shadowkatt** [comment]
i am having this same issue (logs attached)
[log.txt](https://github.com/user-attachments/files/16326308/log.txt)

**Comment by deluan** [comment]
Thanks for reporting it. I fixed it now in the `develop` branch, but I don't have a timeline for when there will be a new release. Maybe in the next couple of months.
