### ISSUE TITLE
[Request]: Can you provide the binary file of FreeBSD?

### ISSUE THREAD

**Issue by twtctwte** [navidrome/navidrome#3079]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

new

### Current Behavior

我找不到freebsd的二进制构建

### Expected Behavior

no

### Environment

```markdown
- OS:
- Browser:
- Client:
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
no
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
While I don't have any plans to support FreeBSD binary in the main project, I'd gladly accept a PR to add this.

But that does not mean you can't use it with FreeBSD. There is a community-created package for it, and the instructions are here: https://www.navidrome.org/docs/installation/freebsd/
