### ISSUE TITLE
[Bug]: Favorite tracks are ignoring album tracklist

### ISSUE THREAD

**Issue by inter5tella** [navidrome/navidrome#3087]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.52.5

### Current Behavior

Flagging a song as 'favorite' (a.k.a. heart) will move the song to the bottom of the list of a album that is using track number order. By this, the track will be skipped if the track number is reached but will be played after the very last track of the album.

![grafik](https://github.com/navidrome/navidrome/assets/12923644/284cd4e3-2711-4dda-ad1a-d31049e605ec)

Just because it is not possible to sort by title number, the track will be played only after the album's tracklist end<.

### Expected Behavior

Even if a track is flagged as favorite, it will remain in the album track order list.

### Steps To Reproduce

1. Open a existing album
2. Select a track between the 1st and the last one
3. Flag the track as Favorite
4. Check if the track is getting moved to the bottom of the playlist

### Environment

```markdown
- OS: Windows 11
- Browser: Firefox 126.0.1
- Client: Using server web version 0.52.5 (c5560888)
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
Thanks for trying Navidrome!

I'm a bit puzzled by your report, I never saw this behaviour before. Here's a screen capture from our demo server:


https://github.com/navidrome/navidrome/assets/331353/f6afc261-ae5e-4d90-af7d-1ed0d2024bb3

**Comment by inter5tella** [comment]
Thanks for your reply. 
I've removed the fav icon from the impacted track and did a hard refresh of the page. It seems the track n° 8 will now always stay at the end of the tracklist after track n° 18.
I've also did a sort by year and artist and did a refresh but the track still remains at the end of the list.
