### ISSUE TITLE
[Feedback]: Please Make A Way Around To Use Navidrome With GitHub Pages It Would Be Really A Help Please

### ISSUE THREAD

**Issue by astrodev63alt** [navidrome/navidrome#3156]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

Latest

### Current Behavior

A Feedback

### Expected Behavior

Need Support For GitHub Pages

### Environment

```markdown
- OS:
- Browser:
- Client:
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by astrodev63alt** [comment]
Please Help

**Comment by deluan** [comment]
Not sure if I understand what you mean by "GitHub Pages". Assuming you want some documentation, have you checked our documentation website, www.navidrome.org? Also, you can ask specific questions in the "Discussions" part of GitHub: https://github.com/navidrome/navidrome/discussions/categories/q-a, or in our Discord and/org Reddit communities.

Hope this is what you are looking for.
