### ISSUE TITLE
"Radio stations": Library, Genre, Decade, etc

### ISSUE THREAD

**Issue by certuna** [navidrome/navidrome#316]
The "Radio stations" feature is one of the best things about PlexAmp, navidrome should have it too.
- Library Radio
- Random Album Radio (i.e. Album Shuffle)
- Genre Radio (probably limit the list to genres with more than x songs)
- Decade Radio

Could be exposed in WebUI and Subsonic API (dummy folders)

**Comment by deluan** [comment]
Subsonic API already exposes endpoints for this (ex: http://www.subsonic.org/pages/api.jsp#getSimilarSongs), and it is already implemented by DSub

After integrating with Last.FM and/or MBZ (#18, #113) in the Subsonic API, I will expose some of these features in the UI

**Comment by staticn0de** [comment]
Hi @deluan, I setup Navidrome yesterday. I have a large library and its still importing. I have installed the play:Sub app on my phone and it has connected and working (can stream). I noticed that the app has a radio stations button which does not seem to do anything (no options to add and none autopopulate.) I've come over from plex and plexamp that had theme channels. Is this still to come?

**Comment by deluan** [comment]
@staticn0de, not sure what play:Sub calls "radio stations", Subsonic API provides [Internet Radios](http://www.subsonic.org/pages/api.jsp#getInternetRadioStations) and [Similar Songs from Last.FM](http://www.subsonic.org/pages/api.jsp#getSimilarSongs). The Internet Radio feature will most probably not be implemented any time soon, but the Similar Songs is coming and is tracked by this issue. I'm currently working on Last.FM integration.

**Comment by deluan** [comment]
UPDATE: artist radio (`getSimilarSongs`) is implemented in master, and available through the Subsonic API. It will be part of the next release.

**Comment by msartiano** [comment]
Hello, may I ask if Internet Radios added then? If so, how would I add my internet radios to Navidrome?
Thanks, the Software is amazing!

**Comment by deluan** [comment]
@msartiano Internet Radios (Shoutcast, etc...) is not a feature that is in the road map. May be implemented in the future, though, but we currently have no plans for that.
