### ISSUE TITLE
[Bug]: Memory usage grows over time (memory leak?)

### ISSUE THREAD

**Issue by sochotnicky** [navidrome/navidrome#3167]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.52.5

### Current Behavior

My installation of Navidrome keep eating more memory over time. See graph:
![image](https://github.com/user-attachments/assets/a09d0a8e-64d2-4c61-94f6-dfee10dd7e92)

I suspect this is related to number of goroutines:
![image](https://github.com/user-attachments/assets/ff1c39a4-d616-4877-a2ca-1fe09b0eff38)

I was sort of waiting for https://github.com/navidrome/navidrome/issues/2003 to see if that will resolve this but since it didn't filing this followup.

### Expected Behavior

I would expect memory usage to stay more or less stable over time or at least get "cleaned up" periodically.

### Steps To Reproduce

Not really sure if there's anything specific about my install but some background:
I use Synology device with NFS mounts to share music for Navidrome. There's synology-specific directories `@eaDir` which are not readable. Had a quick look at the source code and didn't see any obvious leak related to this however.

### Environment

```markdown
- OS:NixOS
- Browser: Not relevant since I rarely use web interface, but Firefox 
- Client: Subsonic
```

### How Navidrome is installed?

Package

### Configuration

```toml
Using JSON config so:

{
  "Address": "0.0.0.0",
  "EnableSharing": true,
  "ImageCacheSize": "5GB",
  "MusicFolder": "/music",
  "Port": 4533,
  "Prometheus": {
    "Enabled": true
  },
  "TranscodingCacheSize": "500MB"
}
```

### Anything else?

I really want to mention I've been a Navidrome user for quite a while and I love it. Thank you for working on this.

I can workaround this bug easily enough with systemd limits so it's not a big deal in my case.

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by sochotnicky** [comment]
One idea I have about what this might be caused by:
I use default ScanSchedule so Navidrome triggers library scan every minute. Assuming the scan takes more than one minute I wonder if we could just have more and more scan goroutines "queued" up this way. I've disabled the scheduled scan and see if that will help (I don't add to my library all that often)

**Comment by Extent421** [comment]
I've been seeing the same thing for quite a while, with a very similar setup except that my music folder is local to the Synology and not mounted via NFS.  This shows system memory usage over the last year, all of the leakage is due to the navidrome container
![image](https://github.com/user-attachments/assets/6d852893-f55b-49db-9f06-5a9ebccdada6)

I'm not sure if it's scans stacking up, in my logs it looks like my typical scan time is 0.6 seconds.  I tried setting the scan interval to 10 minutes instead of 1 to see if that makes any difference.  At the very least I'm sure that it's not anything client related, as my instance has been running for the last couple months with its external port disabled with no apparent change in the speed of the leak.

**Comment by mintsoft** [comment]
I am pretty sure that this is already fixed in master, however the fix (https://github.com/navidrome/navidrome/pull/3031) hasn't been folded into a release yet

**Comment by mintsoft** [comment]
https://github.com/navidrome/navidrome/releases/tag/v0.53.0 is out now so it should be easy enough to test by upgrading to the latest version

**Comment by sochotnicky** [comment]
> Yeah, I think it is fixed.
> 
> @sochotnicky I'm closing it now, but feel free to chime in if you have any other concerns.

I won't be able to re-test for at least a few weeks but I trust the evaluation and other folks testing/confirming so all good from my end.
