### ISSUE TITLE
[Bug]: Album order is broken when sorting by artist

### ISSUE THREAD

**Issue by lk-davidegironi** [navidrome/navidrome#3185]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.52.5

### Current Behavior

When sorting Album by Artist, I notice a strange behavior. On new tagged album (later than 0.52.0) the order is mismatched.
All my album has ALBUM tag for album name, ARTIST and ALBUMARTIST for artist name.

Let's suppose to have those album
ARTIST,ALBUMARTIST: Bingo - ALBUM: Album  (tagged before running 0.52.5)
ARTIST,ALBUMARTIST: Ciller - ALBUM: Other album  (tagged before running 0.52.5)
ARTIST,ALBUMARTIST: Zipper - ALBUM: My new album  (tagged before running 0.52.5)
ARTIST,ALBUMARTIST: Flumium - ALBUM: This is an album (tagged after running 0.52.5)
ARTIST: many_names, ALBUMARTIST: Compilation ALBUM: This is a compilation, TCMP=1 (tagged before running 0.52.5)
What I'm expecting is the following order:

What I get is
1) Album (Bingo)
2) Other album (Ciller)
3) My new album (Zipper)
4) This is an album (Flumium)
5) This is a compilation (Compilation)

### Expected Behavior

1) Album (Bingo)
2) Other album (Ciller)
3) This is an album (Flumium)
4) My new album (Zipper)
5) This is a compilation (Compilation)

### Steps To Reproduce

1. Load a few album using 0.52.0 (see my sample above)
2. Change the ARTIST and ALBUMARTIST after running 0.52.5

### Environment

```markdown
- OS: Ubuntu 22.04
- Browser: Chrome 127.0.6533.89 on Windows 10 x64
- Client: feishin, subtracks, or web navidrome client
```

### How Navidrome is installed?

Binary (from downloads page)

### Anything else?

I tag album with mp3tag.
It's maybe due to this?

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by certuna** [comment]
Compilation albums get the Album Artist "Various Artists", so expected behaviour would be that the compilation album gets sorted between Flumium and Zipper.

If you check the tags, do you have anything in the Sort Artist/Sort Album Artist fields?

**Comment by lk-davidegironi** [comment]
Thanks. The problem is not the compilation sorting, those are correct. The problem is that I expect Zipper later than Flumium, and then Compilation. Like I had before editing my mp3.
Maybe rebuilding the entire db?

**Comment by certuna** [comment]
Do your files have Sort Artist/Sort Album Artist tags?

**Comment by lk-davidegironi** [comment]
No,

I usually have: ALBUM, ARTIST, ALBUMARTIST, TITLE, TRACK, YEAR and GENRE
For multi CD album i also have DISCNUMBER.

Anyway, just an update.
I've removed the db file, and restarted navidrome. It's now working as expected. Maybe an issue with my db?

**Comment by certuna** [comment]
Yeah maybe - if it happens again, please post it so we can investigate. Deluan is working on a [big refactoring of the scanner and the DB](https://github.com/navidrome/navidrome/pull/2709) (early days, still experimental) - some old issues will be gone, but it's new code so we'll have to catch any new issues.
