### ISSUE TITLE
[Bug]: Disc context menu contains broken "Share" and "Get Info" entries

### ISSUE THREAD

**Issue by TheLastZombie** [navidrome/navidrome#3204]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

c95fa11a2fa25d1a4ed9a75b75262b04d5137671

### Current Behavior

The context menu for discs contains the two entries "Share" and "Get Info", however, neither seem to be implemented for discs.

https://github.com/user-attachments/assets/8e4aa7ac-d8dd-4b57-a1df-cce2dba52b68

### Expected Behavior

Both items should either work as expected or be removed from the menu. I can open a PR doing the latter, if that's ok.

### Steps To Reproduce

1. Add an album to the library that has multiple discs (with files tagged as such)
2. Navigate to the album in the Navidrome web interface
3. Open the context menu on one of the disc rows

### Environment

```markdown
- OS: Windows 11
- Browser: LibreWolf 129.0.1-1
- Client: Navidrome
```

### How Navidrome is installed?

Built from sources

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by certuna** [comment]
Yeah this needs to be fixed - there's going to be a big UI rework from [ReactAdmin v3 to v5](https://marmelab.com/blog/2024/06/20/react-admin-v5.html), so probably best to do it there, unless you can write a quick patch yourself.

**Comment by kgarner7** [comment]
Other UI bugfixes have been recently merged in, so if it's fairly simple I anticipate this would be likely to get merged as well. If it's simple I don't see a reason why not
