### ISSUE TITLE
Adjusting album art

### ISSUE THREAD

**Issue by maverick40** [navidrome/navidrome#323]
Could you set up a system to reduce the size of the album covers. ?

Also put in option different preconfigured display mode;
Cut in half the display with two columns, on the left the titles of the tracks in the album and on the right the cover? a bit like that. Thank you for your excellent work and your pleasant relationship with the users. A dev present and listening is great

https://i.imgur.com/01H7Mrv.png
https://i.imgur.com/zfsFWu0.jpg

thx very much

**Comment by deluan** [comment]
I plan to introduce a "slide" that would allow changing the size of the cover arts in the album grid (and in the artist view in the future).

**Comment by bouhormq** [comment]
I would love to take on this challenge for this edition of GSOC! Can't wait to get to know more about the community!

**Comment by kjain0073** [comment]
Hi @maverick40, if this is not assigned to anyone, Can I take up this issue?

**Comment by deluan** [comment]
Hi @kjain0073 this would be part of a larger refactor. The goal would be to rewrite the whole album grid. It is listed as one of the GSoC's ideas: https://www.navidrome.org/docs/gsoc/#new-album-grid

**Comment by armedev** [comment]
I would like to work on this mini-project to enhance the UI, I also saw the GSoC project idealist, it would be nice if you could assign me this issue later I will be looking forward to applying to GSoC as a contestant on the application date.

![Screenshot from 2021-03-12 23-29-07](https://user-images.githubusercontent.com/51921579/110979686-f12e4900-838a-11eb-81fe-cb4b5585cc48.png)

**Comment by Anurag5086** [comment]
Hello, I am interested in this issue. I came across this though the GSoC idealist. I would like to work on this as a GSoC Participant. Looking forward to GSoC as a contestant.

**Comment by deluan** [comment]
@kjain0073 The curent AlbumGrid is too convoluted, and it is better rewrite it from scratch. That's the goal of the GSoC idea "New Album Grid". Having this slide is just one part of it. If you implement the slide in the current grid, it will be a throw away effort....

**Comment by YashV1729** [comment]
Hello , I've seen that the code is quite convoluted and not easy to understand , @deluan I'm interested in making the AlbumGrid from the scratch and making it as per the required design as Plex interface. Can I move forward with this issue?

**Comment by jvoisin** [comment]
This is a non-trivial issue, not well-fitted as a simple pre-GSoC task.
As written [navidrome's documentation]( https://www.navidrome.org/docs/gsoc/ ), as well as on the [GSoC website](https://summerofcode.withgoogle.com/organizations/5157984449069056/):

> Students willing to take part of the Google Summer of Code 2021 with navidrome should send a couple of pull-requests, to demonstrate that they're both motivated and capable of writing code and contributing to the project.

> We're also expecting a written application, with a timeline and a proper design draft: you can use this one as template: https://docs.google.com/document/d/1kDPGgr_D5tQuYLQi_gEGlkuQ-DlU8GH5kDBqZbVSC7I/edit

Nobody is expected to take ownership of GSoC tasks before being officially selected/accepted to work on it *during* the GSoC.

**Comment by YashV1729** [comment]
> This is a non-trivial issue, not well-fitted as a simple pre-GSoC task.
> As written [navidrome's documentation](https://www.navidrome.org/docs/gsoc/), as well as on the [GSoC website](https://summerofcode.withgoogle.com/organizations/5157984449069056/):
> 
> > Students willing to take part of the Google Summer of Code 2021 with navidrome should send a couple of pull-requests, to demonstrate that they're both motivated and capable of writing code and contributing to the project.
> 
> > We're also expecting a written application, with a timeline and a proper design draft: you can use this one as template: https://docs.google.com/document/d/1kDPGgr_D5tQuYLQi_gEGlkuQ-DlU8GH5kDBqZbVSC7I/edit
> 
> Nobody is expected to take ownership of GSoC tasks before being officially selected/accepted to work on it _during_ the GSoC.

Ok I got it, thank you for clearing my doubt. I'll do the process accordingly.

**Comment by aryan0078** [comment]
assign this to me

**Comment by Dnouv** [comment]
@aryan0078, sorry but as @jvoisin, stated it would be a GSoc task, please refer to this comment for further instructios.

> This is a non-trivial issue, not well-fitted as a simple pre-GSoC task.
> As written [navidrome's documentation](https://www.navidrome.org/docs/gsoc/), as well as on the [GSoC website](https://summerofcode.withgoogle.com/organizations/5157984449069056/):
> 
> > Students willing to take part of the Google Summer of Code 2021 with navidrome should send a couple of pull-requests, to demonstrate that they're both motivated and capable of writing code and contributing to the project.
> 
> > We're also expecting a written application, with a timeline and a proper design draft: you can use this one as template: https://docs.google.com/document/d/1kDPGgr_D5tQuYLQi_gEGlkuQ-DlU8GH5kDBqZbVSC7I/edit
> 
> Nobody is expected to take ownership of GSoC tasks before being officially selected/accepted to work on it _during_ the GSoC.

**Comment by Dnouv** [comment]
@deluan, if it is still available, I would like to work on this project as my first open-source project, not as a part of GSoC. In return, I hope to get the required guidance. Thanks!
