### ISSUE TITLE
[Bug]: Last.fm authorization redirect uses old/incorrect API key

### ISSUE THREAD

**Issue by AbramK24** [navidrome/navidrome#3234]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.52.5

### Current Behavior

I recently deactivated my old Last.fm API key and secret and created a new pair. However, the redirect page to authorize Navidrome as a Last.fm application (as triggered on the personal settings page) uses the old API key in the url despite the new key being set correctly as an environment variable. This prevents authentication and results in a vague "Authorization unsuccessful please try again" message from Last.fm. The work around is to manually replace the old API key with the new key in the url. Afterwards, the authorization is successful.

### Expected Behavior

Ability to authenticate without needing to edit authentication url.

### Steps To Reproduce

1. Deactivate current Last.fm API key/secret pair
2. Create new key/secret pair
3. Set new pair as environment variables
4. Toggle Last.fm integration in settings
5. Attempt to authenticate using redirect

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
When you change your Last.fm API Key and secret, you need to logout and login on the UI. Try that and let me know.
