### ISSUE TITLE
Back to play queue source

### ISSUE THREAD

**Issue by maverick40** [navidrome/navidrome#324]
Could you add the links to (back) the albums in the playlists windows (playlists and playlist currently playing) to find the source album?

thx

**Comment by deluan** [comment]
I added linking from a playlist to albums in 0.21.0. For the play queue (what you call "playlist currently playing"), changes to the upstream [React Player](https://github.com/lijinke666/react-music-player) would be required, not sure how to tackle this.

I'll leave this issue open so I can give it more thinking.

**Comment by deluan** [comment]
I added a link from the playing song to the album. I'll keep this open as I still have to find a way to link from the play queue list to the album

**Comment by deluan** [comment]
Closing this, as I don't think the upstream player library will ever implement this.
