### ISSUE TITLE
[Bug]: Cannot play entire album

### ISSUE THREAD

**Issue by fenixthebuilder** [navidrome/navidrome#3241]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

latest

### Current Behavior

I just uploaded an album to my Navidrome server, but for some reason it doesn't play at all. All the other albums I have on there work fine, but this one is not. This is the error I get:
`time="2024-09-07T14:37:57Z" level=warning msg="API: Failed response"

endpoint=/rest/stream error-70 message="data not found" requestId=dcd839caa2be/vtCDqcjlab-000319`

I tried to download the album on another computer, I've checked the metadata and everything is fine and the songs are playing locally (I mean when I try to play them on another device, not on Navidrome). I tried to enable transcoding, deleted and reuploaded the album, try changing the name of the folder, but nothing.
 What is happening? What can I do?
 

### Expected Behavior

It should play the album without an issue.

### Environment

```markdown
- OS: Windows, Android
- Browser: Chrome
- Client: Navidrome Web UI, Tempo Android App
```

### How Navidrome is installed?

Docker

### Configuration

```toml
version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    user: 1000:1000
    ports:
      - "4533:4533"
    environment:
      ND_SCANSCHEDULE: 1h
#      ND_UILOGINBACKGROUNDURL: https://unsplash.com/it/foto/fotografia-aerea-della-catena-montuosa-coperta-di-neve-sotto-il-cielo-bianco-e-blu-durante-il-giorno-9wg5jCEPBsw
      ND_UIWELCOMEMESSAGE: "Welcome to my HomeLab Spotify clone. Start Listening now!"
      ND_DEFAULTLANGUAGE: "it"
      ND_ENABLEGRAVATAR: true
      ND_SCANNER_EXTRACTOR: ffmpeg
      ND_DEVACTIVITYPANEL: "false"
      ND_ENABLETRANSCODINGCONFIG: true
#      ND_SCANNER_GROUPALBUMRELEASES: true
      ND_LOGLEVEL: info, error, warn, debug, trace
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      ND_ARTISTARTPRIORITY: external
      ND_COVERARTPRIORITY: external
      ND_SPOTIFY_ID: 
      ND_SPOTIFY_SECRET:
      ND_LASTFM_APIKEY: 
      ND_LASTFM_SECRET: 
#      ND_SUBSONICARTISTPARTICIPATIONS: true
      ND_ENABLESHARING: true
      ND_DEFAULTTHEME: Spotify-ish
#      ND_TLSCERT: /root/navidrome/cert/cert.pem
#      ND_TLSKEY: /root/navidrome/cert/private.key
    volumes:
      - "/root/navidrome/data:/data"
      - "/root/Musica:/music:ro"
```

### Relevant log output

```shell
time="2024-09-07T14:37:57Z" level=warning msg="API: Failed response"

endpoint=/rest/stream error-70 message="data not found" requestId=dcd839caa2be/vtCDqcjlab-000319
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
Based on the logs, seems that the files are missing. Try doing a full rescan. 

If it still does not work, can you please send me one of the files from this album? If you can, send it to deluan @ navidrome.org
