### ISSUE TITLE
[Bug]: Shows back instead of front cover for FLAC tracks

### ISSUE THREAD

**Issue by jgoerzen** [navidrome/navidrome#3254]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.52.5

### Current Behavior

My music library consists of FLAC files which have been annotated by Musicbrainz' Picard.  Sometimes, Musicbrainz contains multiple artwork images for a track.  For instance, the cover, an image of the disc itself, an image of the back side, etc.

When a back side image is present, Navidrome uses that, rather than the correct front cover.

Here's an excerpt from `metaflac --list` on one of these tracks:

```
METADATA block #3
  type: 6 (PICTURE)
  is last: false
  length: 79860
  type: 3 (Cover (front))
  MIME type: image/jpeg
  description: 
  width: 500
  height: 500
  depth: 0
  colors: 0 (unindexed)
  data length: 79818
...
METADATA block #4
  type: 6 (PICTURE)
  is last: false
  length: 198137
  type: 4 (Cover (back))
  MIME type: image/jpeg
  description: 
  width: 599
  height: 541
  depth: 0
  colors: 0 (unindexed)
  data length: 198095
```

If I subsequently run `metaflac --block-number=3 --export-picture-to=/tmp/foo.jpg`, I get the front cover as expected. `metaflac --block-number=4 --export-picture-to=/tmp/foo.jpg` shows the back cover.  So I know the annotations within the FLAC file are correct.  For this file, Navidrome is showing the back cover, not the front cover, at all locations in the interface.

### Expected Behavior

Navidrome should use the front cover.

### Steps To Reproduce

Just have a FLAC file with multiple kinds of images in it, saved by Musicbrainz picard.

### Environment

```markdown
- OS: Debian bookworm
- Browser: Firefox (but this also appears in Symfonium Android app and everywhere that this might be used)
- Client: n/a
```

### How Navidrome is installed?

Binary (from downloads page)

### Relevant log output

```shell
Not seeing anything here
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Just noticed it on v0.53.3 too, suddenly wrong pics shown, this didn't happen on the old <0.50 version I had.
This hopefully gets fixed then, because I apparently have many FLAC with more than only front cover.

**Comment by SingularReza** [comment]
Same here. But its not the back cover per se, but the last picture block added in the file

**Comment by deluan** [comment]
Cover arts are extracted using the github.com/dhowden/tag package. It only supports a single cover and I don't have control over which one to get.

To solve this issue we would need to extract artwork with TagLib, something I've been thinking of and may add after the new scanner (#2709) is released.

The workaround is to add a `cover.jpg` image in the album folder.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Interestingly this never happened on the older Releases, so something has changed.
I didn't change anything in my Library.
I now also can't put a cover.jpg in every of the tens of thousands of Folders only because of that.

Why it always took the first Cover and now suddenly the last one?
What changed from v0.4x -> v0.53.3 ?

And those covers are also internally tagged with front, back, etc. So it should be possible to pick front else simply the first one.

**Comment by deluan** [comment]
> 
> Why it always took the first Cover and now suddenly the last one? What changed from v0.4x -> v0.53.3 ?

Not sure, would have to dig into `github.com/dhowden/tag` changelog. I'll take a look and see if it is something we can revert, or maybe open an issue with them.

> And those covers are also internally tagged with front, back, etc. So it should be possible to pick front else simply the first one.

This does not make any difference for this library, as we don't have a way to specify which one we want. It just return some arbitrary image. Moving to TagLib would allow this.

**Comment by kgarner7** [comment]
> > Why it always took the first Cover and now suddenly the last one? What changed from v0.4x -> v0.53.3 ?
> 
> Not sure, would have to dig into `github.com/dhowden/tag` changelog. I'll take a look and see if it is something we can revert, or maybe open an issue with them.
> 
> > And those covers are also internally tagged with front, back, etc. So it should be possible to pick front else simply the first one.
> 
> This does not make any difference for this library, as we don't have a way to specify which one we want. It just return some arbitrary image. Moving to TagLib would allow this.
> 
> EDIT: Feel free to open an issue with `github.com/dhowden/tag` and link this issue there :)

My best guess is that this change is coming in how https://github.com/dhowden/tag/pull/69 changed the behavior parsing files (in v0.48.0). Based off of the implementation now, it looks like this package will return the _last_ metadata picture.

You can definitely do it via taglib, but this'll lead to more c++ : )

**Comment by deluan** [comment]
> You can definitely do it via taglib, but this'll lead to more c++ : )

Yeah, _eventually_ we will have to do this. 

For now, maybe we can revert and pin a version of the `tag` package prior to that PR? Or contribute with code to extract all images? Maybe a new method that returns a map?

**Comment by kgarner7** [comment]
> > You can definitely do it via taglib, but this'll lead to more c++ : )
> 
> Yeah, _eventually_ we will have to do this.
> 
> For now, maybe we can revert and pin a version of the `tag` package prior to that PR? Or contribute with code to extract all images? Maybe a new method that returns a map?

Not sure if reverting is necessarily the right choice, as there may be other PRs you want. The latter _might_ be a better option, but as far as I can tell `tag` is in general single-valued anyway...

**Comment by deluan** [comment]
I don't think there is anything else after the PR was merged that is used by Navidrome, except that PR itself, as it fixes some [Ogg pictures edge cases](https://github.com/dhowden/tag/issues/64#issuecomment-619280684)

>  is in general single-valued anyway

It is, but it is time for them to start supporting multi-values. We can add a `.Pictures()` method to the interface, maybe. If that lib starts supporting multi-values, we can even make it the default, as it is faster than TagLib and is enough for most music libraries out there.

**Comment by deluan** [comment]
Hey folks! Can someone send me one file that has this issue (deluan @ navidrome . org)? I'll try to fix it in the upstream library.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
I just wanted to send one and then saw that there was only one Front Pic in the files, so i checked further and saw that apparently the default CoverArtPriority Order has changed. The default always was "embedded" first, guess the default has changed somewhere between 0.4x and v0.53.3. So I now put CoverArtPriority into the config and put embedded as first like it was default before. Currently doing a Full Scan to fix it. If I now encounter one that has the other bug, I gonna send you a link.

**Comment by deluan** [comment]
Yeah, this was changed when we introduced fetching album cover art from Last.fm in #2061, version v0.49.0. Glad you were able to figure this out!

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Yeah, the full scan now also finished and i didn't see any wrong ones anymore.
I additionally checked about 100 folders with FLACs and I didn't find any with more than one embedded pic, but many with different folder.jpg, cover.jpg or front.jpg than the one embedded.
I can't check every folder, but it seems that this fixed it for me and so I can't send you a File with that issue.
But I guess OP certainly has one.

**Comment by jgoerzen** [comment]
Hi @deluan I have emailed you an example file just now.  Thanks!

**Comment by deluan** [comment]
@jgoerzen Can you try the version from the PR #3348? The PR does not select the cover, but juts grabs the first image, instead of the last. 

To see results, you'll need to remove the image cache folder.

**Comment by jgoerzen** [comment]
> @jgoerzen Can you try the version from the PR #3348? The PR does not select the cover, but juts grabs the first image, instead of the last.

Thanks for your work on this!

This makes things better for the majority of the albums, but worse for a minority of them.  I have emailed you an example where it now goes for the back instead of the front cover.  In this example, indeed the front cover was listed last.

All of these files were saved by Musicbrainz Picard.  I don't know what determines the order, or even if it is deterministic.  In any case, an algorithm like this is probably suitable:

- Look for front cover, reported by `metaflac --list` as `type: 3 (Cover (front))`
- If you don't find one, fallback to... something.  Maybe just pick the first image

Thanks again!

- John

**Comment by deluan** [comment]
> Look for front cover, reported by metaflac --list as type: 3 (Cover (front))
> If you don't find one, fallback to... something. Maybe just pick the first image

Yeah, I plan to implement it this way, but I want to hear back from the upstream maintainer first (on https://github.com/dhowden/tag/issues/109), before diverging too much from the original library.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
But I also have some files with only one front cover that use (Cover (other)), for those selecting the first is good, but selecting front would break it. Guess some taggers simply use different types or also none at all.

Here a List what is selectable in Mp3Tag
![image](https://github.com/user-attachments/assets/f1941141-bf20-41a0-b5a3-50594f6edb63)

There also is no fixed order, you can add as many pics you want and select the type freely for each one and it's also possible to have multiple (Cover (front)).

But usually the first is the one to be used for albums no matter the type set.

**Comment by deluan** [comment]
> but selecting front would break it.

You mean, because there is no Front image or because the image is wrong?

Anyway, the idea is to search for images in this order:
- Matches "cover" AND "front"
- Matches "front"
- First image

I think this woulkd solve the majority of the cases. In the future we may support other embedded images, but for now this should solve the issue. I'm still waiting to hear back from https://github.com/dhowden/tag/issues/109 before working on this.

**Comment by deluan** [comment]
Hey @jgoerzen, I updated #3348 to follow the following algorithm to find the proper cover:

- Description matches "cover" AND "front"
- Description matches "front"
- Description matches "cover"
- First image

Can you try it and let me know?

**Comment by jgoerzen** [comment]
Thanks!  Does there happen to be a new amd64 Linux build?  If not, I'll go build it, just thought I'd check first.

**Comment by deluan** [comment]
> Thanks! Does there happen to be a new amd64 Linux build? If not, I'll go build it, just thought I'd check first.

Yes, the attachments on the comment from @github-actions bot in the PR are always updated with the last artifacts from the last passing build: https://github.com/navidrome/navidrome/pull/3348#issuecomment-2387482135

**Comment by jgoerzen** [comment]
This is a big improvement over unpatched Navidrome!  There are a few remaining odd cases, but I'm not entirely convinced they're Navidrome's fault.  Many thanks!
