### ISSUE TITLE
[Bug]: Transcoding not functioning

### ISSUE THREAD

**Issue by liamdmccann** [navidrome/navidrome#3262]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

Navidrome 0.52.5 (c5560888)

### Current Behavior

Hello there. I'm attempting to transcode FLAC files via
a. Navidrome through Firefox browser and
b. Symfonium

I am consistently getting output files of between 2-20kb from FLAC files of up to 200MB in size. This error is consistent across AAC,. MP3 and OPUS, no matter the bitrate. I've installed ffmpeg correctly but otherwise am very new to Navidrome, so excuse me for any rookie mistakes or issues w. logs. (I'm still trying to figure out where to find logs.)

### Expected Behavior

Expecting to have transcoded files saved.

### Environment

```markdown
- OS: Windows
- Browser: Firefox 128.0
- Client: Navidrome 0.52.5 (c5560888)
```

### How Navidrome is installed?

Built from sources

### Configuration

```toml
# This is just an example! Please see available options to customize Navidrome for your needs at
# https://www.navidrome.org/docs/usage/configuration-options/#available-options

LogLevel = 'DEBUG'
ScanSchedule = '@every 10m'
TranscodingCacheSize = '5000MB'

# IMPORTANT: Use single quotes for paths in Windows
MusicFolder = 'F:\FLAC - boxsets'

# Set this to the path of your ffmpeg executable
FFmpegPath = 'C:\Program Files\ffmpeg\bin\ffmpeg.exe'

ND_LOGLEVEL = "debug"
```

### Relevant log output

```shell
C:\Program Files\Navidrome>Navidrome.exe
 _   _             _     _
| \ | |           (_)   | |
|  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___
| . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
| |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
\_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
                          Version: 0.52.5 (c5560888)

Loaded configuration from 'C:\Program Files\Navidrome\navidrome.toml': &conf.configOptions{
    ConfigFile:                   "C:\\Program Files\\Navidrome\\navidrome.toml",
    Address:                      "0.0.0.0",
    Port:                         4533,
    UnixSocketPerm:               "0660",
    MusicFolder:                  "F:\\FLAC - boxsets",
    DataFolder:                   ".",
    CacheFolder:                  "cache",
    DbPath:                       "navidrome.db?cache=shared&_busy_timeout=15000&_journal_mode=WAL&_foreign_keys=on",
    LogLevel:                     "DEBUG",
    ScanInterval:                 -1,
    ScanSchedule:                 "@every 10m",
    SessionTimeout:               86400000000000,
    BaseURL:                      "",
    BasePath:                     "",
    BaseHost:                     "",
    BaseScheme:                   "",
    TLSCert:                      "",
    TLSKey:                       "",
    UILoginBackgroundURL:         "/backgrounds",
    UIWelcomeMessage:             "",
    MaxSidebarPlaylists:          100,
    EnableTranscodingConfig:      false,
    EnableDownloads:              true,
    EnableExternalServices:       true,
    EnableMediaFileCoverArt:      true,
    TranscodingCacheSize:         "5000MB",
    ImageCacheSize:               "100MB",
    AlbumPlayCountMode:           "absolute",
    EnableArtworkPrecache:        true,
    AutoImportPlaylists:          true,
    PlaylistsPath:                ".;**/**",
    AutoTranscodeDownload:        false,
    DefaultDownsamplingFormat:    "opus",
    SearchFullString:             false,
    RecentlyAddedByModTime:       false,
    PreferSortTags:               false,
    IgnoredArticles:              "The El La Los Las Le Les Os As O A",
    IndexGroups:                  "A B C D E F G H I J K L M N O P Q R S T U V W X-Z(XYZ) [Unknown]([)",
    SubsonicArtistParticipations: false,
    FFmpegPath:                   "C:\\Program Files\\ffmpeg\\bin\\ffmpeg.exe",
    MPVPath:                      "",
    MPVCmdTemplate:               "mpv --audio-device=%d --no-audio-display --pause %f --input-ipc-server=%s",
    CoverArtPriority:             "cover.*, folder.*, front.*, embedded, external",
    CoverJpegQuality:             75,
    ArtistArtPriority:            "artist.*, album/artist.*, external",
    EnableGravatar:               false,
    EnableFavourites:             true,
    EnableStarRating:             true,
    EnableUserEditing:            true,
    EnableSharing:                false,
    DefaultDownloadableShare:     false,
    DefaultTheme:                 "Dark",
    DefaultLanguage:              "",
    DefaultUIVolume:              100,
    EnableReplayGain:             true,
    EnableCoverAnimation:         true,
    GATrackingID:                 "",
    EnableLogRedacting:           true,
    AuthRequestLimit:             5,
    AuthWindowLength:             20000000000,
    PasswordEncryptionKey:        "[REDACTED]",
    ReverseProxyUserHeader:       "[REDACTED]",
    ReverseProxyWhitelist:        "[REDACTED]",
    HTTPSecurityHeaders:          conf.secureOptions{CustomFrameOptionsValue:"DENY"},
    Prometheus:                   conf.prometheusOptions{Enabled:false, MetricsPath:"[REDACTED]"},
    Scanner:                      conf.scannerOptions{Extractor:"taglib", GenreSeparators:";/,", GroupAlbumReleases:false},
    Jukebox:                      conf.jukeboxOptions{
        Enabled: false,
        Devices: {
        },
        Default:   "",
        AdminOnly: true,
    },
    Agents:                           "lastfm,spotify",
    LastFM:                           conf.lastfmOptions{Enabled:true, ApiKey:"[REDACTED]", Secret:"[REDACTED]", Language:"en"},
    Spotify:                          conf.spotifyOptions{},
    ListenBrainz:                     conf.listenBrainzOptions{Enabled:true, BaseURL:"https://api.listenbrainz.org/1/"},
    DevLogSourceLine:                 false,
    DevLogLevels:                     {},
    DevEnableProfiler:                false,
    DevAutoCreateAdminPassword:       "[REDACTED]",
    DevAutoLoginUsername:             "[REDACTED]",
    DevActivityPanel:                 true,
    DevSidebarPlaylists:              true,
    DevEnableBufferedScrobble:        true,
    DevShowArtistPage:                true,
    DevOffsetOptimize:                50000,
    DevArtworkMaxRequests:            5,
    DevArtworkThrottleBacklogLimit:   100,
    DevArtworkThrottleBacklogTimeout: 60000000000,
    DevArtistInfoTimeToLive:          86400000000000,
    DevAlbumInfoTimeToLive:           604800000000000,
}
time="2024-09-15T23:14:58+10:00" level=debug msg="Opening DataBase" dbPath="navidrome.db?cache=shared&_busy_timeout=15000&_journal_mode=WAL&_foreign_keys=on" driver=sqlite3
time="2024-09-15T23:14:58+10:00" level=info msg="goose: no migrations to run. current version: 20240511210036\n"
time="2024-09-15T23:14:58+10:00" level=debug msg="Jukebox is DISABLED"
time="2024-09-15T23:14:58+10:00" level=info msg="Starting scheduler"
time="2024-09-15T23:14:58+10:00" level=debug msg="Scheduler: start"
time="2024-09-15T23:14:58+10:00" level=info msg="Creating Image cache" maxSize="100 MB" path="cache\\images"
time="2024-09-15T23:14:58+10:00" level=error msg="Agent not available. Check configuration" name=lastfm
time="2024-09-15T23:14:58+10:00" level=info msg="Setting Session Timeout" value=24h
time="2024-09-15T23:14:58+10:00" level=error msg="Agent not available. Check configuration" name=spotify
time="2024-09-15T23:14:58+10:00" level=info msg="Login rate limit set" requestLimit=5 windowLength=2
time="2024-09-15T23:14:58+10:00" level=info msg="Found ffmpeg" path="C:\\Program Files\\ffmpeg\\bin\\ffmpeg.exe"
time="2024-09-15T23:14:58+10:00" level=info msg="Configuring Media Folder" name="Music Library" path="F:\\FLAC - boxsets"
time="2024-09-15T23:14:58+10:00" level=debug msg="Last.fm integration is ENABLED"
time="2024-09-15T23:14:58+10:00" level=debug msg="ListenBrainz integration is ENABLED" ListenBrainz.BaseURL="https://api.listenbrainz.org/1/"
time="2024-09-15T23:14:58+10:00" level=info msg="Spotify integration is not enabled: missing ID/Secret"
time="2024-09-15T23:14:58+10:00" level=debug msg="Loaded cache" dir="cache\\images" numItems=317
time="2024-09-15T23:14:58+10:00" level=debug msg="Registered metadata extractor" id=ffmpeg version=2024-09-12-git-504c1ffcd8-full_build-www.gyan.dev
time="2024-09-15T23:14:58+10:00" level=debug msg="Registered metadata extractor" id=taglib version=2.0.1
time="2024-09-15T23:14:58+10:00" level=info msg="Scheduling periodic scan" schedule="@every 10m"
time="2024-09-15T23:14:58+10:00" level=info msg="Mounting Native API routes" path=/api
time="2024-09-15T23:14:58+10:00" level=debug msg="Scheduler: added" entry=1 next="2024-09-15 23:24:58 +1000 AEST" now="2024-09-15 23:14:58.6407436 +1000 AEST"
time="2024-09-15T23:14:58+10:00" level=error msg="Agent not available. Check configuration" name=lastfm
time="2024-09-15T23:14:58+10:00" level=error msg="Agent not available. Check configuration" name=spotify
time="2024-09-15T23:14:58+10:00" level=info msg="Creating Transcoding cache" maxSize="5.0 GB" path="cache\\transcoding"
time="2024-09-15T23:14:58+10:00" level=debug msg="Throttling Subsonic getCoverArt endpoint" backlogLimit=100 backlogTimeout=1m maxRequests=5
time="2024-09-15T23:14:58+10:00" level=info msg="Finished initializing cache" cache=Image elapsedTime=25.3ms maxSize=100MB
time="2024-09-15T23:14:58+10:00" level=info msg="Mounting Subsonic API routes" path=/rest
time="2024-09-15T23:14:58+10:00" level=error msg="Agent not available. Check configuration" name=lastfm
time="2024-09-15T23:14:58+10:00" level=error msg="Agent not available. Check configuration" name=spotify
time="2024-09-15T23:14:58+10:00" level=debug msg="Throttling public images endpoint" backlogLimit=100 backlogTimeout=1m maxRequests=5
time="2024-09-15T23:14:58+10:00" level=info msg="Mounting Public Endpoints routes" path=/share
time="2024-09-15T23:14:58+10:00" level=info msg="Mounting LastFM Auth routes" path=/api/lastfm
time="2024-09-15T23:14:58+10:00" level=info msg="Mounting ListenBrainz Auth routes" path=/api/listenbrainz
time="2024-09-15T23:14:58+10:00" level=info msg="Mounting Background images routes" path=/backgrounds
time="2024-09-15T23:14:58+10:00" level=info msg="Mounting WebUI routes" path=/app
time="2024-09-15T23:14:58+10:00" level=debug msg="Scheduler: stop"
time="2024-09-15T23:14:58+10:00" level=debug msg="Loaded cache" dir="cache\\transcoding" numItems=0
time="2024-09-15T23:14:58+10:00" level=info msg="Finished initializing cache" cache=Transcoding elapsedTime=96.2ms maxSize=5000MB
time="2024-09-15T23:14:59+10:00" level=debug msg="Loaded background images from image service" elapsed=361.6ms total=119
time="2024-09-15T23:15:00+10:00" level=debug msg="Executing initial scan"
time="2024-09-15T23:15:00+10:00" level=debug msg="Scanning folder" folder="F:\\FLAC - boxsets" lastModifiedSince="2024-09-15 23:14:47.659 +1000 AEST"
time="2024-09-15T23:15:00+10:00" level=debug msg="Directory tree loaded from DB" elapsed=23.9ms total=113
time="2024-09-15T23:15:00+10:00" level=debug msg="Finished reading directories from filesystem" path="F:\\FLAC - boxsets"
time="2024-09-15T23:15:00+10:00" level=debug msg="Finished deleted folders check" elapsed= total=0
time="2024-09-15T23:15:00+10:00" level=debug msg="No changes found in Music Folder" elapsed=46.1ms folder="F:\\FLAC - boxsets"
time="2024-09-15T23:15:00+10:00" level=debug msg="Finished initial scan"
time="2024-09-15T23:15:00+10:00" level=error msg="Fatal error in Navidrome. Aborting" error="error creating tcp listener: listen tcp 0.0.0.0:4533: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
time="2024-09-15T23:15:00+10:00" level=info msg="Closing Database"
time="2024-09-15T23:15:00+10:00" level=info msg="Navidrome stopped, bye."
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by kgarner7** [comment]
The logs you've shown do not include anything related to transcoding. Try playing a stream with transcoding enabled (either on the client, or via the Players tab), and then see the output of the logs. You're looking for outputs like
> level=info msg="Streaming file" artist=\<artist\> bitRate=\<preferred bitrate\> cached=false format=\<target format\> originalBitRate=1109 originalFormat=flac

**Comment by liamdmccann** [comment]
Thanks - I've done as directed above, and transcoding is still not functioning, see below:

> 
> 
> time="2024-09-16T07:49:40+10:00" level=debug msg="Started new EventStream connection" client="30b4c462-7016-4566-b3b9-2a7aab04ad20 (liamdmccann - 127.0.0.1:54262 - e77245ff-f5bb-47a2-b734-91254087c2e8)" requestId=Liam-PC/0PIFZeqgms-000001 username=liamdmccann
> time="2024-09-16T07:49:40+10:00" level=debug msg="Client added to EventStream broker" newClient="30b4c462-7016-4566-b3b9-2a7aab04ad20 (liamdmccann - 127.0.0.1:54262 - e77245ff-f5bb-47a2-b734-91254087c2e8)" numActiveClients=1
> time="2024-09-16T07:49:40+10:00" level=debug msg="HTTP: GET http://localhost:4533/app/navidrome-service-worker.js" elapsedTime= httpStatus=200 remoteAddr="127.0.0.1:54263" requestId=Liam-PC/0PIFZeqgms-000002 responseSize=1492 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0"
> time="2024-09-16T07:49:41+10:00" level=debug msg="HTTP: GET http://localhost:4533/app/navidrome-service-worker.js" elapsedTime= httpStatus=200 remoteAddr="127.0.0.1:54263" requestId=Liam-PC/0PIFZeqgms-000003 responseSize=1492 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0"
> time="2024-09-16T07:49:41+10:00" level=debug msg="HTTP: GET http://localhost:4533/app/3rdparty/workbox/workbox-core.prod.js" elapsedTime="827.3µs" httpStatus=200 remoteAddr="127.0.0.1:54289" requestId=Liam-PC/0PIFZeqgms-000004 responseSize=3122 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0"
> time="2024-09-16T07:49:41+10:00" level=debug msg="HTTP: GET http://localhost:4533/app/3rdparty/workbox/workbox-navigation-preload.prod.js" elapsedTime= httpStatus=200 remoteAddr="127.0.0.1:54291" requestId=Liam-PC/0PIFZeqgms-000008 responseSize=660 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0"
> time="2024-09-16T07:49:41+10:00" level=debug msg="HTTP: GET http://localhost:4533/app/3rdparty/workbox/workbox-sw.js" elapsedTime="827.3µs" httpStatus=200 remoteAddr="127.0.0.1:54288" requestId=Liam-PC/0PIFZeqgms-000005 responseSize=1359 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0"
> time="2024-09-16T07:49:41+10:00" level=debug msg="HTTP: GET http://localhost:4533/app/3rdparty/workbox/workbox-routing.prod.js" elapsedTime="321.4µs" httpStatus=200 remoteAddr="127.0.0.1:54263" requestId=Liam-PC/0PIFZeqgms-000007 responseSize=3499 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0"
> time="2024-09-16T07:49:41+10:00" level=debug msg="HTTP: GET http://localhost:4533/app/3rdparty/workbox/workbox-strategies.prod.js" elapsedTime="825.6µs" httpStatus=200 remoteAddr="127.0.0.1:54290" requestId=Liam-PC/0PIFZeqgms-000006 responseSize=6858 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0"
> time="2024-09-16T07:49:50+10:00" level=debug msg="API: New request /rest/stream" client=NavidromeUI requestId=Liam-PC/0PIFZeqgms-000009 username=liamdmccann version=1.8.0
> time="2024-09-16T07:49:50+10:00" level=error msg="Error starting transcoder" error="starting cmd: exec: \"C:\\\\Program\": executable file not found in %PATH%" id=3e0e34ec6406de17e9206e835c8e2028 requestId=Liam-PC/0PIFZeqgms-000009
> time="2024-09-16T07:49:50+10:00" level=error msg="Error accessing transcoding cache" error="invalid argument" id=3e0e34ec6406de17e9206e835c8e2028 requestId=Liam-PC/0PIFZeqgms-000009
> time="2024-09-16T07:49:50+10:00" level=info msg="Streaming file" artist="The Associates" bitRate=320 cached=false format=aac originalBitRate=973 originalFormat=flac requestId=Liam-PC/0PIFZeqgms-000009 title=No transcoding=true user=liamdmccann
> time="2024-09-16T07:49:50+10:00" level=warning msg="API: Failed response" endpoint=/rest/stream error=0 message="Internal Server Error: invalid argument" requestId=Liam-PC/0PIFZeqgms-000009
> time="2024-09-16T07:49:50+10:00" level=debug msg="HTTP: GET http://localhost:4533/rest/stream?u=liamdmccann&t=[REDACTED]&s=[REDACTED]&f=json&v=1.8.0&c=NavidromeUI&id=3e0e34ec6406de17e9206e835c8e2028&_=1726436298123" elapsedTime=5.1ms httpStatus=200 remoteAddr="127.0.0.1:54290" requestId=Liam-PC/0PIFZeqgms-000009 responseSize=206 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0"

I've checked - ffmpeg (2024-09-12) is definitely in my PATH, so I'm not entirely sure why Navidrome isn't recognising it. 

Thanks in advance!

**Comment by kgarner7** [comment]
> time="2024-09-16T07:49:50+10:00" level=error msg="Error starting transcoder" error="starting cmd: exec: "C:\\Program": executable file not found in %PATH%"

The path to ffmpeg is wrong. Unfortunately I'm not too familiar with Windows pathing, and I know there's some weird things you may need to do.

**Comment by liamdmccann** [comment]
Thanks for this - after several attempts of reinstalling ffmpeg, I finally got this working by removing the spaces as suggested. Thanks a lot!
