### ISSUE TITLE
[Bug]: Nested playlists not working at all

### ISSUE THREAD

**Issue by TobiasDax** [navidrome/navidrome#3275]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.53.0 (910a4612)

### Current Behavior

I would love to have a smart playlists that combines the songs of multiple other (smart) playlists. Form what i have seen here: https://github.com/navidrome/navidrome/issues/3017 this should already work and the issue with not refreshing playlists should also be fixed in the current version.
But for me thats not the case at all sadly.
i have multiple playlists, some smart some not:
Playlists:
`Base - Deutschrap` id: `053954cf-4074-4008-838a-6949cdbeab77`
`Base - Deutschrock` id: `ca56593c-7dfc-4007-9f63-f2c897319884`

Smart Playlists:
`Genre Deutschrap` id: `8c2e7d55-c301-49c1-93d7-40ada31d1683`
`Genre Rock Deutsch` id: `2fe16ead-d9a3-4b9b-8caa-64d6edfae5f6`

i tried the following smart playlists:

```
{
  "any": [
    {
      "inPlaylist": {
        "id": "053954cf-4074-4008-838a-6949cdbeab77"
      }
    },
    {
      "inPlaylist": {
        "id": "ca56593c-7dfc-4007-9f63-f2c897319884"
      }
    }
  ]
}
```

```
{
  "any": [
    {
      "inPlaylist": {
        "id": "8c2e7d55-c301-49c1-93d7-40ada31d1683"
      }
    },
    {
      "inPlaylist": {
        "id": "2fe16ead-d9a3-4b9b-8caa-64d6edfae5f6"
      }
    }
  ]
}
```

Both playlists are empty, containing 0 tracks instead of the combined tracks of the other playlists.

### Expected Behavior

The smart playlists should contain all tracks present in the two referenced playlists.

### Environment

```markdown
- OS: UNRAID, Docker
- Browser: Vivaldi, Firefox
- Client: WebUI and Feishin
```

### How Navidrome is installed?

Docker

### Configuration

```toml
Official UNRAID template
```

### Relevant log output

```shell
{
  "time": "2024-09-17T17:21:40Z",
  "level": "info",
  "msg": "Updating synced playlist",
  "path": "/music/XX Playlists/Dax Wide.nsp",
  "playlist": "Dax Wide"
}
```

### Anything else?

Would love to get some help on this, there is nothing relevant in the logs, but if i can add some additional informations just tell me

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
Was this working on previous versions, or did it stop in 0.53.0?

Do you see any errors or warnings in the logs, when you open the Playlist in the Navidrome UI?

**Comment by deluan** [comment]
Sorry, bad documentation! The nested playlists must be public for them to be used with the `inPlaylist` operator. This post better explains it: https://www.reddit.com/r/navidrome/comments/1ac8q2a/smart_playlist_that_contains_other_playlists/

Let me know if that works for you.

**Comment by TobiasDax** [comment]
> Sorry, bad documentation! The nested playlists must be public for them to be used with the `inPlaylist` operator. This post better explains it: https://www.reddit.com/r/navidrome/comments/1ac8q2a/smart_playlist_that_contains_other_playlists/
> 
> Let me know if that works for you.

ok, yeah that fixed all my problems ;)
