### ISSUE TITLE
[Bug]: Random album sort does not get reset

### ISSUE THREAD

**Issue by ulfurinn** [navidrome/navidrome#3277]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.53.0

### Current Behavior

The random album view is always in the same order.

### Expected Behavior

Reloading the view should re-randomize the order, as [the original PR](https://github.com/navidrome/navidrome/pull/1841) mentions. The described behaviour of reseeding the RNG on the first page is not working.

### Environment

```markdown
- OS:
- Browser:
- Client:
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
Yeah, I noticed this yesterday. I usually get a new seed of Random Albums by clicking in the "Random Albums" link. I'll work on this tonight.

**Comment by deluan** [comment]
It is fixed in `master` (thanks @kgarner7). It may take a while (at least couple of weeks) to release it, though.

**Comment by mgonzalezm** [comment]
@deluan The recent release broke the view of random songs in ultrasonic. It is now impossible to get a different set of random songs.

![screenshot](https://github.com/user-attachments/assets/f7c07176-b2f1-4a40-9435-25dfbfc9df1f)

maybe it is related

**Comment by deluan** [comment]
Hummm, it is probably because of the backend changes I did for 0.53.0, not this PR, that's fixing it in the UI.

I'll test Ultrasonic tonight and see if I can fix it for this weekend's bug fix release

**Comment by deluan** [comment]
@mgonzalezm Which version are you using? Version 0.53.0 had an issue that was causing this, but it was fixed in 0.53.1. Can you please confirm?
