### ISSUE TITLE
[Bug]: Incorrect acquisition of tags in Vorbis comment format using TagLib.

### ISSUE THREAD

**Issue by naiar** [navidrome/navidrome#3299]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.53.1 and also current source (11d96f)

### Current Behavior

When reading a music file with Vorbis tag comments (ogg, flac etc.),  via taglib, the values for album, artist, date, and title are incorrect.
(contains two identical values)

Example

for
```
tags, err := Read("tests\fixtures\test.ogg")
```
tags is following:
```
map[_track:[3] album:[Album Album] albumartist:[Album Artist] artist:[Artist Artist] bitrate:[43] bpm:[123] channels:[2] comment:[Comment1Comment2] compilation:[1] date:[2014 2014] discnumber:[1] disctotal:[2] duration:[1] encoder:[Lavc58.134.100 libvorbis] fbpm:[141.7] genre:[Rock] lengthinmilliseconds:[1038] lyrics:[[00:00.00]This is [00:02.50]unspecified [00:00.00]This is [00:02.50]English] replaygain_album_gain:[+7.64 dB] replaygain_album_peak:[0.11772506] replaygain_track_gain:[+7.64 dB] replaygain_track_peak:[0.11772506] samplerate:[8000] title:[Title Title] totaldiscs:[2] totaltracks:[10] tracknumber:[3] tracktotal:[10]]
```

Remark
- In Navidrome, when a tag contains two or more values, a process is executed to make only one tag value, so that two values, such as title, will not be displayed on the screen.
-This problem does not occur with mp3. (use ID3 tag)

### Expected Behavior

```
tags, err := Read("tests\fixtures\test.ogg")
```
tags should look like this:
```
map[_track:[3] album:[Album] albumartist:[Album Artist] artist:[Artist] bitrate:[43] bpm:[123] channels:[2] comment:[Comment1Comment2] compilation:[1] date:[2014] discnumber:[1] disctotal:[2] duration:[1] encoder:[Lavc58.134.100 libvorbis] fbpm:[141.7] genre:[Rock] lengthinmilliseconds:[1038] lyrics:[[00:00.00]This is [00:02.50]unspecified [00:00.00]This is [00:02.50]English] replaygain_album_gain:[+7.64 dB] replaygain_album_peak:[0.11772506] replaygain_track_gain:[+7.64 dB] replaygain_track_peak:[0.11772506] samplerate:[8000] title:[Title] totaldiscs:[2] totaltracks:[10] tracknumber:[3] tracktotal:[10]]
```

### Steps To Reproduce

1. run Navidrome
2. execute scan
3. Check the results of running Read (in taglib_wrapper.go).

### Environment

```markdown
- OS: Ubuntu 22.04
- Browser: Firefox (irrelevant for browsers) 
- Client: Web
```

### How Navidrome is installed?

Built from sources

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
This is not an issue, this is working as expected. Duplicated values are removed in a subsequent step.
