### ISSUE TITLE
[Bug]: imported .m3u playlists information is parsed in a case sensitive manner omitting artists albums and tracks when metadata doesn't match case in folder name

### ISSUE THREAD

**Issue by 7ujmnbvfr456yhgt** [navidrome/navidrome#3373]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.53.3

### Current Behavior

Previous playlists that had imported successfully had a bunch of songs go missing but they were still present in the library. Through some trial and error I realized that missing songs had capitalization discrepancies between the metadata in the track and either the folder for the artist / album and/or track.

e.g. if the filepath specified in the playlist was "Rza/album name/track  name" but the metadata for artist was "RZA" it would no then the affected tracks would no longer show up in the playlists. 

Not sure whether this is a bug per se, but since it didn't used to do this and I can't see anything in the configuration options about this I'm guessing it's not intended. Most music managers that auto-organize files based on metadata do not change the case of the folder names if the only thing changed is the case, and there are times when an artist will use e.g. all caps for some releases but not others so it would be nice to have an option to ignore case in m3u file paths. 

I can't think of a reason the case where ignoring the case of a file path in an m3u would break a playlist but maybe I'm wrong about that.

### Expected Behavior

imported m3u playlists shouldn't be case-sensitive as was the case previously 

### Environment

```markdown
- OS: Linux (debian)
```

### How Navidrome is installed?

Docker

### Configuration

```toml
version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
#    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 30 * * * *
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      ND_AUTOIMPORTPLAYLISTS: true
      ND_PLAYLISTSPATH: MusicBeeMirror/ExportedPlaylists/___FORSYNC___
    volumes:
      - "/var/lib/docker/volumes/navidrome/_data:/data"
      - "/mnt/media:/music:ro"
#    Networks:
#      - bridge
#      - navidrome_default
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by metalheim** [comment]
I dont think this has anything to do with metadata, since navidrome only matches the filepath of the m3u vs. the filepath in navidromes database. The metadata is then attached from navidromes DB data, but that is at a later stage.

> I can't think of a reason the case where ignoring the case of a file path in an m3u would break a playlist but maybe I'm wrong about that.

Most file systems (Windows beeing the exception) are case-sensitive. So it could happen that both files exist, f.e.:
`Rza/album name/track name`
`RZA/album name/Track Name`

Parsing file paths from m3u playlists case-insensitively creates ambiguity.
IMHO, file paths **are** case-sensitive and m3u files should be created correctly (with correct case).

**Comment by 7ujmnbvfr456yhgt** [comment]
Didn't realize Windows was the exception with case-insensitive file paths, so it makes sense to not change the default parsing behaviour. But at any rate this behaviour is new because playlists that had previously worked for months and several updates suddenly removed songs (I'm using musicbee to organize files and generate m3u playlists, which I think is quite common).

>>I dont think this has anything to do with metadata, afaik navidrome only matches the filepath of the m3u vs. the filepath in navidromes database. The metadata is then attached from navidromes DB data, but that is at a later stage.

I think you're right - it's only to do with metadata indirectly. In musicbee I guess that - since windows doesn't care about case in file names - when you edit the metadata of a song to change the case and nothing else it doesn't bother changing the folder names in windows from e.g. Rza to RZA, but it does change the name of the path in the m3u file to math the new case of the file. Because it only changes it in the m3u and not windows filenames that creates a mismatch that then is evident on a linux system where I mirror my library and exported playlists to.

I understand that the behaviour is stemming from musicbee but I post it here because I haven't updated musicbee in over a  year and navidrome was finding all the songs in those exported playlists without issue before so it seems something changed there and it was able to handle case-mismatch previously. I also get that since navidrome is running on linux in this case it shouldn't change the default filepath parsing but it would be beneficial to be able to make it parse it in a case-insensitive manner as an option (I just checked with navidrom 0.53.2 and it works in a case insensitive manner there) as a lot of people use musicbee to export playlists and organize libraries.

**Comment by metalheim** [comment]
Alright, if the behaviour is something that changed with the latest update, then it might have been introduced by the changes in playlist-import that were made in this commit:
https://github.com/navidrome/navidrome/commit/46be041e7b86f3fe2bc6cf5f1f64a80c757c0f75

Maybe @deluan can take a look when he has time

Ideally, MusicBee would still write the "correct" (technically they are kinda correct, as in windows FS, both filepaths are correct, since paths are case-insensitive) filepaths to the m3u playlists.

**Comment by deluan** [comment]
This case-sensitive behaviour was actually introduced in 0.53.3, in this commit: https://github.com/navidrome/navidrome/commit/13af8ed43ac42cfbcc19588c39ad0e65c7733bc6

I'd argue that this is the correct behaviour, and the fact that it was case-insensitive before was a bug that was fixed by the commit above. Specially because Windows systems can also be set to case-sensitive: https://learn.microsoft.com/en-us/windows/wsl/case-sensitivity)

**Comment by 7ujmnbvfr456yhgt** [comment]
Well fair enough, but I think (unless I'm wrong) the fact that the case-insensitivity hasn't been brought up / noticed as a bug before, that there are actually very few cases where it would cause a problem *specifically in a music directory* given how they are routinely organized, and that the current behaviour is more likely to cause issues for users who use both windows and linux. Again, not arguing for a change in the default, just an option to use the 0.53.2 behavior.

Also, while windows directories can be changed to case-sensitive in the OS, the software in charge of altering those directories (i.e. musicbee in this particular case) won't necessarily follow suit. I will post this issue to the musicbee forums and hopefully it can be added as an option there, but there are other music organizers on windows that will still run in to the same problem. 

At any rate thanks for all the work you do developing navidrome. It's feature complete enough for my needs that I can probably just hang out on 0.53.2 for a while

**Comment by deluan** [comment]
Yeah, valid points. I'll take a look at this and if it is a simple change, I may change it back to case-insensitive (old behaviour) and have an option to make it case-sensitive, just in case this breaks other use-cases.

Anyway, I think this must be raised with the MusicBee project, as this seems to be a bug on their side, specially considering that Windows supports case-sensitivity.

**Comment by 7ujmnbvfr456yhgt** [comment]
Thanks!

Just posted it to the musicbee forums. Wasn't the first time it has come up there so hopefully it gets more traction this time.

**Comment by deluan** [comment]
@caiocotts can you please take a look at this?
