### ISSUE TITLE
[Bug]: The album order seems to be sorted by the album artist.

### ISSUE THREAD

**Issue by GoGoBlacktea** [navidrome/navidrome#3411]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [ ] I'm using the latest version (your issue may have been fixed already)

### Version

Version:	0.53.3 (13af8ed4)

### Current Behavior

The album order seems to be sorted by the album artist.
![01](https://github.com/user-attachments/assets/9426ecf5-56d0-4233-a8ce-7d5c8b073f13)
![02](https://github.com/user-attachments/assets/b9d3a77a-cde2-4f7c-96ab-fd7267022b69)
![03](https://github.com/user-attachments/assets/0b56e7a9-b6cb-4cf8-866a-8f6a9e4baa8f)

### Expected Behavior

The album order can be sorted by the album name.
The album artist order can be sorted by the album artist info.

### Environment

```markdown
- OS:
- Browser:
- Client:
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by kgarner7** [comment]
See https://www.navidrome.org/docs/faq/#-i-have-an-album-with-tracks-by-different-artists-why-is-it-broken-up-into-lots-of-separate-albums-each-with-their-own-artist. Your problem is that the Album Artist tag is different for each of the tracks in the album, so it's being split.
