### ISSUE TITLE
[Bug]: Incorrect play queue order when playing albums with multiple discs

### ISSUE THREAD

**Issue by Wibble199** [navidrome/navidrome#3557]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

v0.53.3

### Current Behavior

When using the Web UI and clicking the play button on an album from a view where it shows multiple albums (e.g. recently added, random, etc.), the tracks are added to the queue in an unexpected order. They are being sorted by track number first, then disk, i.e: Disc 1, Track 1; Disc 2, Track 1; Disc x, Track 1; Disc 1, Track 2; Disc 2, Track 2; etc.

Interestingly if you click on the album to go to the details of the album, and click the play button from there, the tracks are ordered as expected (Disc 1, Track 1; Disc 1, Track 2; Disc 1, Track x; Disc 2, Track 1; etc.)

### Expected Behavior

Would expect the track order to be consistent regardless of how the album is played.

### Steps To Reproduce

This is the album I will using for the example screenshots:

![The first few tracks of disc 1](https://github.com/user-attachments/assets/44015f06-23be-45b8-84fa-908cdbc09873)

![The first few tracks of disc 2](https://github.com/user-attachments/assets/ed55d06a-5d74-4691-ad82-886ca1217ca3)

1. Find an album which has multiple discs in an album view (such as random, most viewed, etc.)
2. Click on the play button on that album.
3. Observe the order of tracks in the play queue. Notice that it is: D1 T1, D2 T1, D1 T2, D2 T2, etc.

![The generated play queue order](https://github.com/user-attachments/assets/f83298e1-5ac1-469d-918a-e4915c10ecc4)

5. Open the album details and click the play button in there.
5. Observe the order of tracks in the play queue. It is now: D1 T1, D1 T2, D1 T3, etc.

![The generated play queue order](https://github.com/user-attachments/assets/0862d10a-f348-4d10-b150-5151148f7e03)

### Environment

```markdown
- OS: Windows 11
- Browser: Firefox 133.0.3
- Client: Navidrome Web UI
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
Good catch, will fix it for this weekend's release. Thanks!
