### ISSUE TITLE
[Bug]:  Container fails to gracefully shutdown on SIGTERM

### ISSUE THREAD

**Issue by devon-wolf** [navidrome/navidrome#3601]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.54.2

### Current Behavior

When running Navidrome (v0.54.2) in a container, the application does not gracefully shutdown when receiving a SIGTERM signal. While the application acknowledges the signal and begins shutdown (logging "Stopping HTTP server"), it never completes the shutdown process. I have tested this with both the recommended Docker setup as well as with Podman (my preferred setup). Both Docker and Podman need to use SIGKILL after a 10-second timeout in order to stop the container.

Current behavior:
1. On receiving SIGTERM, Navidrome logs: "Stopping HTTP server"
2. The shutdown process hangs indefinitely if signal sent with Ctrl+C in foreground; it has to be stopped with the container's `stop` command.
3. When using `stop` command:
   - Podman output from command shows: `WARN[0010] StopSignal SIGTERM failed to stop container navidrome in 10 seconds, resorting to SIGKILL`
   - Docker events at time of command show: Initial SIGTERM (signal=15), followed by SIGKILL (signal=9) after 10 seconds, with container finally exiting with code 137 (SIGKILL termination)

### Expected Behavior

Navidrome should gracefully shutdown within the 10-second SIGTERM timeout period.

### Steps To Reproduce

Using Podman:
```bash
podman pod create --name navidrome-pod --userns keep-id -p 127.0.0.1:4533:4533

# and then
podman run --name navidrome --pod navidrome-pod -v /path/to/data:/data -v /path/to/music:/music:ro docker.io/deluan/navidrome:latest
# podman run -d with the same command for detached
```

Using Docker:
```bash
docker run --name navidrome --user $(id -u):$(id -g) -p 127.0.0.1:4533:4533 -v /path/to/data:/data -v /path/to/music:/music:ro deluan/navidrome:latest
# docker run -d with the same command for detached
```

Stop container using either:
- Ctrl+C if running in foreground (and move to another terminal/session to use the `stop` command)
- If using Docker, follow events in another terminal/session with `docker events --filter container=navidrome`
- `podman stop navidrome` or `docker stop navidrome` if running detached

### Environment

```markdown
- OS: Debian 12 (bookworm)
- Browser: N/A
- Client: N/A
- Podman version: 4.3.1
- Docker version: 27.4.1
```

### How Navidrome is installed?

Docker

### Relevant log output

```shell
[Navidrome logs from running container, from server ready to Ctrl+C]
time="2024-12-28T02:03:21Z" level=info msg="----> Navidrome server is ready!" address="0.0.0.0:4533" startupTime=51.8ms tlsEnabled=false
time="2024-12-28T02:03:21Z" level=debug msg="Loaded background images from image service" elapsed=208.5ms total=128
time="2024-12-28T02:03:23Z" level=debug msg="Executing initial scan"
time="2024-12-28T02:03:23Z" level=info msg="Configuring Media Folder" name="Music Library" path=/music
time="2024-12-28T02:03:23Z" level=debug msg="Registered metadata extractor" id=ffmpeg version=6.1.2
time="2024-12-28T02:03:23Z" level=debug msg="Registered metadata extractor" id=taglib version=2.0.2
time="2024-12-28T02:03:23Z" level=debug msg="Scanning folder" folder=/music lastScan="2024-12-28 01:27:40.008395214 +0000 UTC"
time="2024-12-28T02:03:23Z" level=debug msg="Directory tree loaded from DB" elapsed=1.5ms total=7
time="2024-12-28T02:03:23Z" level=debug msg="Finished reading directories from filesystem" path=/music
time="2024-12-28T02:03:23Z" level=debug msg="Finished deleted folders check" elapsed="1.259µs" total=0
time="2024-12-28T02:03:23Z" level=debug msg="No changes found in Music Folder" elapsed=3.5ms folder=/music
time="2024-12-28T02:03:23Z" level=debug msg="Finished initial scan"
^Ctime="2024-12-28T02:03:48Z" level=debug msg="Scheduler: stop"
time="2024-12-28T02:03:48Z" level=info msg="Stopping HTTP server"
```

### Anything else?

Looking at existing issues, #2197 looks potentially related - the problem I'm seeing isn't related to any ongoing process (like scanning, as in that issue) as far as I can see, but it wouldn't surprise me to learn these are the same issue.

The application functions normally otherwise; this only affects shutdown behavior.

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by kgarner7** [comment]
Known issue. Resolved by https://github.com/navidrome/navidrome/pull/3593
