### ISSUE TITLE
[Bug]: Required to create admin again

### ISSUE THREAD

**Issue by lwabish** [navidrome/navidrome#3602]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.54.2 (0b184893)

### Current Behavior

After successfully setup and creating admin user, sometime later when I try to login with the same browser, I will be redirect to the admin user creating page.

This problem does not appear in Edge Private Mode, which means I can only re login in private mode. Maybe It's related to cookie?But deleting cookie doesn't fix this.

### Expected Behavior

After creating admin user, I should be redirect to login page, not init page.

### Environment

```markdown
- OS: debian with docker image tag latest (running in kubernetes with pvc mounted to persist data)
- Browser: edge 131.0.2903.112 
- Client: mac
```

### How Navidrome is installed?

Docker

### Anything else?

I found a closed issue maybe a little related but not sure : https://github.com/navidrome/navidrome/issues/613

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by lwabish** [comment]
I changed storage type from slow nfs to better ssd type . Home this work and let me observe for another week.

**Comment by aarondoet** [comment]
I also have this issue, I tried deleting cookies and localStorage in the devtools which did not change anything. After deleting the cache entries I was redirected to the login page again instead of the admin setup page.

OS Ubuntu 22.04.5 LTS
Navidrome v0.54.2 (0b184893) (docker container)
Firefox v133.0.3

**Comment by b202i** [comment]
Same problem here. It seems to happen after upgrading via docker. 
```bash
docker compose down
docker compose pull
docker compose up -d --force-recreate
```
I've cleared browser cookies and still no better. In the past, the workaround is to keep creating more admin accounts, but why?
