### ISSUE TITLE
Suggestion: Album should appear in Library submenu and graphical indication for submenus

### ISSUE THREAD

**Issue by antipiot** [navidrome/navidrome#430]
Hey Deluan, hope you're doing great!

Following all the updates you did recently, i've come with 2 things that may be, for me, improved:

1:I would like to suggest, if possible, to put "Albums" menu and related submenus in the "Library" one.
2:It may be a good thing to add a graphical indice to show the menu and submenus can be deployed
On my side, i'd expect something like this:

Library
  Artist
  Albums
      All
      Random
      ....
  Songs

thanks for your great work!

Regards

**Comment by deluan** [comment]
For item 1), there's a limitation in the current menu implementation that only allows two levels, so I'm not able to have something like _Library->Albums->Random_. I don't have any plans to rework the menu ATM, but I may change this later, put all items at the same level, similar to iTunes:
<img width="197" alt="Screen Shot 2020-08-05 at 3 04 30 PM" src="https://user-images.githubusercontent.com/331353/89453281-03794200-d72d-11ea-96f3-29e6a186590e.png">

Regarding item 2), I didn't quite understand it. What do you mean by "deploy"?

**Comment by antipiot** [comment]
Your suggestion for menu looks great to me.

for item 2, my apologies, i was thinking about a symbol that may indicate there are submenus as here but when not deployed:
![image](https://user-images.githubusercontent.com/26579988/89463964-ee71d280-d76f-11ea-9305-ba48677a8796.png)
![image](https://user-images.githubusercontent.com/26579988/89464102-29740600-d770-11ea-801c-96c06b0356ac.png)

**Comment by Dnouv** [comment]
@antipiot, for item 2, please have a look at the attached screenshot. Do you want something like this,
After,
![image](https://user-images.githubusercontent.com/61188295/116972331-7ae9fb00-acd8-11eb-82fc-aa08bc4b54f9.png)

Before,
![image](https://user-images.githubusercontent.com/61188295/116972276-6ad21b80-acd8-11eb-98f8-7e502774e28c.png)


@deluan, should I go ahead with this arrow icon in place of the Album icon and create a PR?
Please feel free to provide feedback. Thank you!

**Comment by antipiot** [comment]
> please have a look at the attached screenshot. Do you want something like this,
> After,

This looks Great! That's it.
Actually i'm asking myself if it really makes sense to have a submenu for library: my point is that albmus are part of a library and thus should show inside "library" aswell  - or Hide the library submenu entry wich i found  is not that usefull.
Why not have something like this and consider "library" as the root of all menus:

> Albums
Artists
Songs 
Playlists

instead of 

> Albums
> Library
   Artists
   Songs 
   Playlists

Hope you understood my explanations and point.

Thanks for having a look!

Regards - JS

**Comment by Dnouv** [comment]
Thanks for your feedback, @antipiot, about all items under the library. I understood your point; it was well explained by you. It would probably require a proper discussion and feedback from members, so maybe for your item 1, you will need to wait a little longer. I hope you may understand, but about the submenu dropdown icon, it is a small change so, it will be done promptly.

**Comment by antipiot** [comment]
> you will need to wait a little

Thanks for your time @Dnouv  - im in no hurry and, indeed, it's only my though about the GUI improvements that i would appreciate.
the submenu dropdown Icon is already a great thing :-)

**Comment by Dnouv** [comment]
Thanks for understanding and your kind words; We will definitely look into your suggestions. Till then, if you encounter any other issues, please feel free to create a GH issue.

**Comment by deluan** [comment]
@Dnouv Thanks for the PR, but I don't think this is relevant anymore, as we don't have the "Library" root menu anymore. I rather leave this unchanged until we add Smart Playlists to the Sidebar menu, when we will have to redo the Menu (again).

@antipiot, will close this for now, but feel free to reopen if you have any concerns.
