### ISSUE TITLE
Add "Shuffle All" to Album Lists views

### ISSUE THREAD

**Issue by deluan** [navidrome/navidrome#453]
It needs to respect any applied filters.

@williamkray:
> i'd also like to see this ability in the search/filter view, etc... for example, i have many starred albums, i'd like to be able to shuffle-play everything there.

From: https://github.com/deluan/navidrome/issues/409#issuecomment-676803070

**Comment by williamkray** [comment]
Thanks for opening this separate ticket!

as i explore the interface more, i see that the functionality exists in various views, but seems to be in multiple locations depending on the view. for example, if i visit an album to view it's tracks, i'm greeted with the options below the album art:

![Screenshot_20200820150432](https://user-images.githubusercontent.com/8409433/90830551-b41f3e00-e2f6-11ea-8a7e-f0ee9b0ed653.png)

if i visit a playlist, i see different options under the playlist description, but in a similar location:
![Screenshot_20200820150655](https://user-images.githubusercontent.com/8409433/90830618-d44efd00-e2f6-11ea-9080-7b9d30dee79f.png)

but if i visit the songs view of my entire library, the shuffle option is the only one available, and it's in the top right of the screen:
![Screenshot_20200820150752](https://user-images.githubusercontent.com/8409433/90830664-f183cb80-e2f6-11ea-8161-09748d8c3b7c.png)

seems like along with adding the functionality to the other filtered album views, it would be nice to have consistency for these options as well regarding both location of the buttons and which buttons are available.

**Comment by deluan** [comment]
Thanks for the feedback. Originally all action buttons were on the right (the default in React-Admin), but some users were complaining they were too far from the menu, causing a lot of mouse "traveling"... Then I moved the ones in the album/playlist views to the left, as these views do not have filters.

For the list views in general (songs, albums, artists), that have filters, I can't seem to find a good approach. I could move the buttons to the left and the search box and filters to the right, but not sure if this would be a good thing...

Regarding the unification of actions, yes, I'm planning to revamp all views (specially the list views) to make them more consistent and interchangeable (ex: playlists could be viewed as albums or songs).

For this issue here, I'll focus on adding a "shuffle all" to album lists, but please feel free to open a different issue to cover this UX suggestions.
