### ISSUE TITLE
add consistent playback options in all library views

### ISSUE THREAD

**Issue by williamkray** [navidrome/navidrome#456]
per conversation here: https://github.com/deluan/navidrome/issues/453#issuecomment-678801128

currently the most ideal playback options are in a single album view:
![album-view-current](https://user-images.githubusercontent.com/8409433/91093936-f7d3b980-e60e-11ea-9e6e-8926dc0bb78d.png)

it would be nice to have consistency across all views from a UX standpoint, and from a functionality standpoint. mockups are included below to indicate that this layout would work in views that both do and don't support filtering.

recently added albums mockup:
![recent-albums-mockup](https://user-images.githubusercontent.com/8409433/91094347-86e0d180-e60f-11ea-8bb5-6af8479c00b5.png)

starred albums mockup:
![starred-albums-mockup](https://user-images.githubusercontent.com/8409433/91094395-93fdc080-e60f-11ea-91b3-997a2e3b7dc0.png)

playlist mockup:
![playlist-mockup](https://user-images.githubusercontent.com/8409433/91094424-9cee9200-e60f-11ea-8476-30e6a9bba028.png)

all songs mockup (can still be filtered, note the removal of "shuffle all" in top right corner):
![songs-mockup](https://user-images.githubusercontent.com/8409433/91094465-ab3cae00-e60f-11ea-9f4f-f2f3474bed70.png)

**Comment by williamkray** [comment]
not included in the mockups would be an additional button, visible in any album-oriented view, that allows shuffle-by-album playback vs. shuffle-by-song playback. this wouldn't be necessary in song-oriented views, as it is implied that shuffle playback in a song list would be shuffled by song.

**Comment by williamkray** [comment]
this is still a valuable and relevant feature request that improves user experience.

**Comment by deluan** [comment]
Thanks for the suggestion. This will be taken in consideration on the new UI, to be released probably in Q2.
