### ISSUE TITLE
UX feature request: Single search bar

### ISSUE THREAD

**Issue by SpencerDub** [navidrome/navidrome#468]
### Is your feature request related to a problem? Please describe.

The search box should always be available for, uh...searching.

I get the concept of context-sensitive searching, and I think that search boxes should also exist within views for albums, artists, songs, etc., that should search only that specific type of content. But sometimes I don't know what I'm searching for, or I'm not sure if it's a song title or an album title. More often than not, I'm on an album page, having just played it, and I want to add more to the playlist. Where is the search box? I have no idea. I just want to be able to search again quickly for something -- anything.

### Describe the solution you'd like

The search box should be permanently visible from the header bar at the top. Maybe the entire box, or maybe just a magnifying glass icon that expands into the full box when moused-over or clicked. Maybe something like this, but matching the colours of the header.
![image](https://user-images.githubusercontent.com/3911507/112644200-e90ee880-8e23-11eb-9103-03c71477f178.png)

I know the Subsonic API returns artists, tracks, and albums, but Navidrome may require a new view that shows these three types of items.

### Additional context
It would be cool to have queries that can be annotated with prefixes, i.e., `album:Metallica` vs. `artist:Metallica`

## Original description by @SpencerDub:
 It would be convenient to have a single search bar that could simultaneously search all fields, rather than having to first select the view related to one's search.

**Comment by deluan** [comment]
As I commented [here](https://github.com/deluan/navidrome/issues/255#issuecomment-680992525), this requires a better Full Text Search implementation. Also a design not currently supported out-of-box by React-Admin, but it is doable

**Comment by SpencerDub** [comment]
@deluan Totally fair, I just wanted to open the issue. I'm in no rush. 🙂

**Comment by TheFlatworm** [comment]
In revamping the search bar into a universal search across all categories - ALBUMS, ARTISTS, ALBUM ARTISTS, and SONGS. It would be great to have search return results of matches in playlists, so that playlist names would be listed if a song in question is in that playlist

**Comment by Empty2k12** [comment]
Another welcome feature would be advanced patterns. I have a library of ballroom/latin music prefixed with song abbreviation and number of bars (e.g. RB24), then allowing a search like "RB{24-28}" to return all rumba songs with 24 to 28 bars. Inspiration could be drawn from [seiri](https://github.com/chyyran/seiri)s bangs.
