### ISSUE TITLE
User webhooks

### ISSUE THREAD

**Issue by tcurdt** [navidrome/navidrome#478]
As mentioned in #18 it would be nice to allow user to configure webhooks to pass events to other system like e.g. Zapier.
The following events come to mind:

1. play with attributes artist, album, track, played time, total time, cover url
2. scrobble (played 90%) with attributes artist, album, track, played time, total time, cover url
3. pause with attributes artist, album, track, played time, total time, cover url
4. added to starred with attributes artist, album, track, total time, cover url
5. removed from starred with attributes artist, album, track, total time, cover url
6. added to playlist with attributes TBD
7. remove from playlist with attributes TBD

ATM I am mostly interested in 1., 2. and 3.

**Comment by MoralCode** [comment]
there don't seem to be any existing go libraries for _sending_ webhooks. i might play around with trying to make one based on https://freek.dev/1383-sending-and-receiving-webhooks-in-laravel-apps.

**Comment by deluan** [comment]
@MoralCode I don't see a need for a library to send webhooks... They are usually an HTTP GET/POST, and GoLang's http client is straightforward and simple enough. Maybe I'm missing your point?

**Comment by MoralCode** [comment]
I was mostly thinking of a library just as a way to make implementing webhooks easy and simple for applications like Navidrome. To me it seems like the hardest part of implementing webhooks is the setup process of collecting the settings from the user and storing them.

I was thinking a library could be useful for simplifying this storage of webhook configurations so an app like Navidrome would just need to pass in the settings from the user and an internal key/identifier for representing that particular webhook-able "event". Whenever the app decides is appropriate for the webhook to be called, it could just be a one-liner to the effect of `webhooks.trigger('webhook-event-id-here', optional_additional_data)` and the library would handle looking up the stored webhook configuration(s) for the event and send the data.

**Comment by MoralCode** [comment]
I have something basic thrown together at https://github.com/MoralCode/go-event-webhooks and am starting to see how simple sending a webhook is.

**Comment by MoralCode** [comment]
@tcurdt is there a particular service (you mentioned Zapier) that you are interested in sending these webhooks to at first? just added https://github.com/MoralCode/go-event-webhooks/issues/6 tas a TO-DO item for the webhook library I am making for this and am curious if any particular service should be prioritized

**Comment by tcurdt** [comment]
@MoralCode I used Zapier just as one of the common examples. I'd probably send them to n8n or nodered instead. Or even write my own service.

**Comment by deluan** [comment]
I think another good example is IFTTT

**Comment by MoralCode** [comment]
awesome! I added those as ideas to the issue I mentioned within the library.

**Comment by tcurdt** [comment]
Seems there is overlap with https://github.com/navidrome/navidrome/issues/246

**Comment by tcurdt** [comment]
It would still be "nice to have" but I think we could close this issue by just having the last.fm scrobbler URL be configurable.
It's not yet, is it?

https://github.com/navidrome/navidrome/blob/master/conf/configuration.go#L103

**Comment by deluan** [comment]
#2229 will handle 1 and 2. 3 is not currently possible as the clients do not send this info to the server. The other will be eventually implemented
