### ISSUE TITLE
Language setting is not persistent after refreshing browser 

### ISSUE THREAD

**Issue by ericgaspar** [navidrome/navidrome#484]
Language setting reset from French to English after browser F5 refresh. Is there a way to make this setting persistent? (variable in config file...)

**Comment by deluan** [comment]
It should persist the settings and in fact I can't reproduce this issue in Chrome and Firefox:

![Kapture 2020-09-07 at 09 33 07](https://user-images.githubusercontent.com/331353/92393074-48f2ab80-f0ed-11ea-9ee9-31e881b76525.gif)

Which browser are you using?

**Comment by ericgaspar** [comment]
I am using Firefox.
step to reproduce:
- I set language to Français
- I clear the cache with F5
- reload the page and login again
- I am back into English

**Comment by deluan** [comment]
If you clear the cache, it will reset to English, as the selection is stored in the browser's localStorage. There's currently no way to store these preferences on the server.

Not sure why F5 is clearing the cache, though... That's not the behaviour on my Firefox

**Comment by ericgaspar** [comment]
I can't reproduce this problem on another computer ... F5 clearing the cache behaviour is maybe associated with a plugin... Thank you for your time (I guess you can close this issue)

**Comment by deluan** [comment]
I'll keep this open as I plan to at some point store preferences in the server.
