### ISSUE TITLE
[Feature Request]: Smart Playlist based on skip to play ratio.

### ISSUE THREAD

**Issue by jaddel** [navidrome/navidrome#50]
This project sounds amazing! 

If we could get smart playlists based on the skip to play ratio, we had a perfect dynamic playlist, that adjusts to our momentary listening Habits.

Lets say i have 6 root playlists :

Pacing: calm, active, neutral
Style: acoustic, electronic, mixed

All my music is sorted into these lists.

Now i do a smart list from calm and acoustic, which is dynamically updating by the skip to play ratio. Then songs with a ratio of < 1 will be played more often and songs with a ratio of > 1 will be played less.

If some one can recommend any other client based server, where this is possible please let me know.

**Comment by deluan** [comment]
That's a great usage for SmartPlaylists! The only bummer here is that the Subsonic API does not provide any means to register Skips...

I tried to autodetect it in the first versions of Navidrome, but it was not reliable, specially because the different clients uses the `/scrobble` endpoint inconsistently.

I'll give some more thought to Skip detection once I start implementing the SmartPlaylists feature.

**Comment by deluan** [comment]
By the way, did you ever got these smart playlists you described working in any music software? Which one? iTunes?

**Comment by jaddel** [comment]
Hey, it would be really cool to see this in navidrome! Let me know how to support this. 

Unfortunately not natively, a friend of mine had the idea already a few year ago and since then i was searching the for a server / client based setup supporting this, but without luck. 

Itunes provides skip and play count but you can't get the ratio. My friend managed to find a work around in iTunes, but it requires a very complex structure of referencing smart playlists (more than a few hundred) and if you reach a certain amount of skips or plays your need to add extra sets of playlist... 
So it's not optimal at all and when you want to use apple music, for some reason you can't have smart playlists referencing other playlists. 

If you ever going to implement this please provide options, that we can customize how skips or plays are counted. 
Lets say in some lists i want it to be based on seconds or alternatively > < xx% of song length.  

I also requested this on the ampache project and the developer apparently also needs to implement skips first. https://github.com/ampache/ampache/issues/2288

thx for your effort.

**Comment by jaddel** [comment]
**Update about the Basic Idea:**

The general idea it that if one has large playlists that one listens to often, it would be nice to filter out the songs that have already been played or skipped in the recent past. To further refine this, the period for which each song is filtered out can be varied by how much one likes the song. This would mean that one's favourites are being played more often while songs that one likes but doesn't want to hear every day are being played more rarely. 

To filter out a song, one needs to know when it was last played or skipped to define something such as "not played in the past two days and not skipped in the past four days"

To define how much a song is liked, two approaches are possible: either manually, by giving each song a star rating or by automatically by operationalising liking as a quotient of play count over skip count. The latter approach means that no active input of the user is required and that liking can organically vary over a period of time. 
For this, the skip and play count of a song are required. Ideally, these counts are specific to each playlist, as one might like a song better in one playlist as opposed to another depending on how well the song fits the rest of the playlist. 
A resulting filter might then be: "for songs with a play/skip ratio > 2: not played in the past four days and not skipped in the past eight days; for songs with a play/skip ratio > 4: not played in the past two days and not skipped in the past four days"

**Comment by deluan** [comment]
My current plan for Smart Playlists is to support rules-based playlists, similar to iTunes. Even though I loved your idea, I don't want to hard-code anything as specific as your suggestion, but instead provide means for users to create their own playlists.

About handling skips, I think that if the player does not send the `scrobbled` with submission=false before the next song starts playing, we can assume the song was skipped. I'll try to implement this when I start working in the smart playlists feature.

To support your idea, I will introduce skip/play ratio (if I get skip counter to work properly), but don't think it makes sense to have the counters per playlist.

**Comment by jaddel** [comment]
Thank you for picking it up. 

Skip and Play Counts per Playlist would be nice to have —> Ideally, these counts are specific to each playlist, as one might like a song better in one playlist as opposed to another depending on how well the song fits the rest of the playlist.

Still even it works without this feature it would be really cool to have this. :)

**Comment by jaddel** [comment]
Hello Deluan, may i ask how is the status on this? 

Thank you.

**Comment by deluan** [comment]
Sorry, but there is still a lot of work to be done before I tackle smart playlists... I may get to this in about a month, but don't quote me on this :P

But rest assured that it will be done, as smart playlists is one of the main features that motivated me to start this project

**Comment by jaddel** [comment]
cool, thankyou for the response.

**Comment by Extarys** [comment]
Washing dishes earlier, I was thinking that - or similar. A smart playlist/dj that would play the song less often the more it's skipped :P

**Comment by Extarys** [comment]
Bad bot!

**Comment by deluan** [comment]
This is not possible as there's no "skip" event, and even if I implement it in Navidrome's UI, Subsonic clients wouldn't be able to report skips, as the API does not support it.

So I think this idea, although great (I used to have a playlist like that in iTunes), is not feasible for the time being.

**Comment by Extarys** [comment]
Thanks @deluan - It would have been dope though!! :P (I remember Amarok with the track score!)
