### ISSUE TITLE
Support numeric genres in ID3 tags?

### ISSUE THREAD

**Issue by thias** [navidrome/navidrome#503]
I just realized that I had a few albums that weren't displaying their genre properly, but something like `(155)` instead of `Downtempo`. After digging a bit, it seems like it's valid for ID3v2 tags to reference ID3v1 numerical genres in parenthesis like this (see https://id3.org/id3v2.3.0 TCON section).

I only had a handful of affected albums, so I just re-tagged them with the genre as full string, but maybe "fixing" this could be useful to others.

```
sqlite> SELECT artist, name, genre FROM album WHERE genre LIKE '(%';
The Streets|DJ-Kicks: Booka Shade|(155)
Digitalism|DJ-Kicks: Digitalism|(159)
The Prodigy|No Tourists|(152)
[...]
```
If this is because ffmpeg is showing "(155)" for the genre (it is), and migrating to taglib will fix it, then feel free to just close this issue :sweat_smile:

**Comment by deluan** [comment]
Thanks for the research, I've seen these numerical genres before, but never spent time investigating as I don't use genres :P

I'm not sure if taglib will read it properly, will leave this issue open until I take a look.
