### ISSUE TITLE
(re)design the current played song UI

### ISSUE THREAD

**Issue by guim31** [navidrome/navidrome#520]
I don't know if this is possible for you, but it would be great if we could get something like the big circle shown on small portrait screens ?
I often listen to music from a Rpi with the official 7" touchscreen display, I access the webUI and everything is ok.
But I would love to have bigger multimedia controls (play/pause, ffw/fbw, rating,...) and a view of the album art corresponding.

**Comment by deluan** [comment]
I don't think this is possible in the current upstream [React Player](https://github.com/lijinke666/react-music-player)... I'm about to open some issues in that project, so I'll add a feature request for this

**Comment by guim31** [comment]
Ok I understand.

Little question as I just saw the React Player github, is it a choice of yours to disabled the "close" button ont the right ? 
Would it be possible / interesting to show it or at least give the option to use it or not ? (I like to close the player when I'm done listening music)

(and again, thanks a lot for all your work, maybe I'm boring with all my questions / requests... but it's because I use your product a lot !)

**Comment by deluan** [comment]
The "Close" button actually destroys the React component, and I could not find a simple way to "recreate" it afterwards. If you want to get rid of the player, you can use the _trash_ icon in the Play Queue, and it will get hidden:

<img width="542" alt="Screen Shot 2020-09-24 at 11 16 13 AM" src="https://user-images.githubusercontent.com/331353/94164768-74002d80-fe57-11ea-8347-bda2b200b425.png">

**Comment by guim31** [comment]
Oh ok ! Thanks for the tip ;)

**Comment by deluan** [comment]
Hey @guim31, I was able to add the "Close" button (27adb84177c9d0ccc8503142d5629a40cff53705), will be part of the next release. Thanks for the suggestion, it made me revisit this and find a solution :)

**Comment by deluan** [comment]
Ops, closed by mistake! This will be possible when https://github.com/lijinke666/react-music-player/issues/166 from the upstream React Player project is done

**Comment by deluan** [comment]
Hey @guim31, is this what you were looking for (from https://github.com/lijinke666/react-music-player/issues/166)?

![95676735-f9733400-0bf2-11eb-8aff-6d165a17a587](https://user-images.githubusercontent.com/331353/95816850-104a8100-0cee-11eb-9049-f3b160c5ac07.png)

I still have to figure out a way to enable this in Navidrome, but at least it is not blocked anymore :)

**Comment by guim31** [comment]
Yes it is !!!
That's cool, I would love to use a solid background instead of the transparency one (or set the transparency to something darker), but the idea is this one, hope you can test it soon :) 
Thanks for the message !

**Comment by the-pro** [comment]
I would love to work on this issue. Can you assign me this

**Comment by deluan** [comment]
@the-pro, I think the solution for this is to add a new option in the "Personal" panel, something like: "Mobile Player Resolution" (argh, please suggest a better name) with the value of the breakpoint, and use it in the [`mobileMediaQuery` parameter](https://github.com/lijinke666/react-music-player#bulb-customize-mobile-media-query). This will require to save this option in the Redux store. See how the NotificationToggle works: https://github.com/navidrome/navidrome/blob/0d35148152c6e495559c2d5e9540a6840cf1d89e/ui/src/personal/Personal.js#L129

Let me know if you really want to give it a try, and I'll assign it to you.

**Comment by the-pro** [comment]
Yes i would most definitely want to work on this issue. I went through the code and i think i can do this

**Comment by the-pro** [comment]
Hi @deluan i wanted to know the input method to take the resolution.
Also after i am storing it in the redux store how to re render the player without reloading the page.
Here is the working video : 


https://user-images.githubusercontent.com/42973786/111073875-899d0880-8506-11eb-9661-0f641235f3ce.mp4

**Comment by deluan** [comment]
I haven't thought too much about this, maybe a `select` with a list of breakpoints? Feel free to suggest something. Just remember this has to be straightforward for end users, that don't know anything about responsive designs and breakpoints...

Regarding the re-render, I would assume that if you just change the Player's property, it should redraw if needed....
