### ISSUE TITLE
ActivityPub support

### ISSUE THREAD

**Issue by LibreHacker** [navidrome/navidrome#528]
See
https://funkwhale.info/

**Comment by deluan** [comment]
Thanks for trying Navidrome!

Care to expand the request? What feature(s) would you like to see implemented? Are they covered by #390?

As Navidrome is focused on personal music library, there are currently no plans to implement any kind of server-to-server communication. The scope of any "social" features will be focused on a single instance of Navidrome, and it is not a priority for now. For some of the "social" features that might be implemented, see #390

**Comment by aschrijver** [comment]
If you decide in future to add AP support then you may find inspiration in the delightful lists at https://codeberg.org/fediverse and - as soon as there are plans I can include you on it as well. You can find help at [SocialHub](https://socialhub.activitypub.rocks) community and use the crowdsourced [Guide for new AP implementers](https://socialhub.activitypub.rocks/t/guide-for-new-activitypub-implementers/479) to help you get going. It looks like some features in #390 are good candidates to be supported by AP.

**Comment by codeinabox** [comment]
I wonder if instead of Navidrome handling this, it would make more sense to scrobble the listen to say Lastfm or Listenbrainz which then shared the listen via ActivityPub

**Comment by deluan** [comment]
Closing this as the kind of server-to-server federation as seen in Funkwhale is not in scope for Navidrome. Once features in #390 are implemented, it may be worth to take another look at the client-to-server protocol and check if anything could fit Navidrome's scope.
