### ISSUE TITLE
Change Year filter from single input box to a two-handle range slider

### ISSUE THREAD

**Issue by certuna** [navidrome/navidrome#533]
It's currently impossible in the ND WebUI to filter albums/tracks/artists for a date range, it's now just a plain input field where users can fill in one year manually.

There are many examples on the web (and in apps) how this can achieved in a more user-friendly way with a two-handle range slider (min and max): see for example [here](https://www.cssscript.com/html5-multi-handle-range-slider-polyfill-solution-multirange/)

**Comment by deluan** [comment]
The filters in the UI are meant to be simple, or the top bar could become very cluttered. I personally don't thin a slider (as the example in the link) would be good for year range... I also think smart playlists are a better option to achieve what you want. 

Also there's an open issue discussing how to improve the filters vs smart playlists  in #215. And it is waiting your reply :P

**Comment by certuna** [comment]
This would allow for example to very quickly filter the song list down to, say, genre "Rock" and 1990-1999 for an ad-hoc "90s Rock" selection.

I love smart playlists since you can save them, but a quick filter is more useful than the steps: go to playlist, new playlist, add year filter, enter start year 1990, enter end year 1999, add genre filter, select "Rock", name the playlist, save, play.

**Comment by SteveDinn** [comment]
Perhaps the "filter" controls could be used on both the search page and the smart playlist creation page, because they're basically the same thing. And ultimately be able to "create smart playlist from this search"
