### ISSUE TITLE
Feature request: Warn when adding song that already exists in music playlist

### ISSUE THREAD

**Issue by kevinrolfes** [navidrome/navidrome#554]
When adding a song to a music playlist, it would be very helpful to receive a warning if that song is already present in the playlist, with the ability to abort the operation and not add a duplicate song to the playlist.

A use case for this feature is as follows: I own many albums and have curated a playlist of the songs I want in rotation while driving. This playlist has around 1000 songs. When I am playing a whole album and I hear a song that I want to be present in that playlist, I try to add it to the playlist. If it is not in the playlist, it is added. If it is already in the playlist, I see a warning and can choose not to add a duplicate.

For example, the now-defunct Google Play Music app issued this warning when the user attempted to add a song which was already present in the playlist:

![duplicate_song_warning](https://user-images.githubusercontent.com/10903820/95265924-ce09d700-07f7-11eb-8d65-eda4bde4aea5.jpg)

Of course, the requested warning could only be seen when using the Navidrome UI and not a third-party Subsonic client like DSub or Audinaut.

**Comment by deluan** [comment]
Yeah, I also miss this confirmation sometimes. Thanks for the suggestion.

But for the exact use case you gave as an example, I use "stars". It is faster to star/unstar a song than it is to add it to a playlist, and it avoids duplicates automatically.

**Comment by RitikPandey1** [comment]
I wolud like to work on this, Please assign this issue to me @deluan

**Comment by RitikPandey1** [comment]
When I'm trying to push changes to repository, I'm getting this error. 
![error1](https://user-images.githubusercontent.com/57366926/111036369-e59f5880-8444-11eb-8f47-0093862d11dc.PNG)
@deluan  how can I resolve this ?
