### ISSUE TITLE
UX improvement: consistent placement of play next button when selecting items

### ISSUE THREAD

**Issue by Sohalt** [navidrome/navidrome#559]
Currently the "play next" and "play later" buttons move to the right when selecting songs to show the count of selected items. It would be nice if they stay in the same place (also the contrast when items are selected is pretty bad).

![2020-10-10-172803_2291x886_scrot](https://user-images.githubusercontent.com/2157287/95659027-c8293400-0b1e-11eb-8583-73d903b9590f.png)
![2020-10-10-172823_2296x885_scrot](https://user-images.githubusercontent.com/2157287/95659028-c8c1ca80-0b1e-11eb-8fb6-79a4e62c7fb8.png)

**Comment by deluan** [comment]
Well, this has also been pointed out in other issues, ex: #456. Originally all actions were on the right side, but some users asked for them to be on the left side, specially for the album view, to reduce the mouse "travel". I still don't know what would be the best solution here....

Re: contrast, yes, I keep forgetting this, I'll try to fix for next release

**Comment by Sohalt** [comment]
I would agree that keeping them on the left is better. I would potentially move the indicator how many items are selected to a separate row (though you would need to be careful to not make this shift everything in a vertical direction) or maybe remove it entirely. Or maybe move the count next to the "select all" checkbox.

**Comment by guim31** [comment]
+1 for the left side everywhere

**Comment by verma-pulkit** [comment]
@jvoisin shall I work on the color contrast and moving the details to the left part..?

**Comment by deluan** [comment]
@verma-pulkit: The contrast has been fixed a while ago:
<img width="974" alt="Screen Shot 2021-03-15 at 12 48 16 PM" src="https://user-images.githubusercontent.com/331353/111189893-eb07ba80-858c-11eb-89a8-35512e878479.png">


Re: position of buttons, If you want to try moving things to the left as suggested, feel free to submit a PR. Remember this is just for the BulkActionButtons. I'm not sure if the end result will be great but we can experiment with it.

**Comment by Himanshunitrr** [comment]
@verma-pulkit are you working on this issue?

**Comment by Dnouv** [comment]
@Himanshunitrr, well, right now, I am working on this issue.

**Comment by GeneralChauhan** [comment]
@Dnouv  are you still working on this issue?

**Comment by Dnouv** [comment]
Hello @GeneralChauhan, actually, I had a PR open for this issue, although it is on hold due to a lack of a good option. 
So the issue is open for contribution. If you have a good idea, please go ahead. 
Feel free to comment. Thank you!

**Comment by Sohalt** [comment]
The UI has changed quite a bit since this was opened. I propose a new solution in https://github.com/navidrome/navidrome/issues/1537 so I'm closing this.
