### ISSUE TITLE
Feature request:  allow for inferring missing metadata from path and filename patterns

### ISSUE THREAD

**Issue by darkphoenix** [navidrome/navidrome#560]
I've been looking into using Navidrome to replace Ampache (ampache/ampache), however, there is a very important feature that Ampache has and Navidrome seems to lack: Ampache can, in the case of an untagged file, infer album, artist and title based on specified filename and path patterns.  This works surprisingly well for my huge, in many parts untagged library and is a rather important feature to me.  Would it be possible to add something similar to Navidrome?

**Comment by deluan** [comment]
I think that is doable. I'll take a look and let you know. Question: Is the pattern used by Ampache configurable?

**Comment by darkphoenix** [comment]
It is, as I recall there are two different settings for file pattern and path pattern, which can be defined with variables for artist, album, title etc.

**Comment by certuna** [comment]
Probably best to indicate in the UI some way that this is inferred data, for example by displaying it as greyed out text? That way it's transparent to the user to see which songs still need to be tagged.
