### ISSUE TITLE
Downloading transcoded copies

### ISSUE THREAD

**Issue by ryansalerno** [navidrome/navidrome#573]
I love the download function so much. And now that it's got filesizes (which look and work great--thanks!), the final bit of perfection would be to download transcoded copies of files/playlists/albums.

Obviously this is complicated from a number of directions. Some possible solutions to some of the complexity:

* You don't want multiple buttons.

    So maybe a dropdown a la Bandcamp would make sense (and then in the three dot menu from listing entries, the download row could have a carat like at the far left of the list and then function as a flyout menu). Or maybe all the buttons are simplified and they all just spawn a modal.

* You need to tell download options apart from each other.

    The simplest thing is to just use the filetype as a name (since this is stored and appears in the file info). Potentially an album or playlist could have files spanning multiple types, though. In this case, maybe something like "Original files" as a catch-all? Or, similarly, "Mixed" or something would be acceptable.

    But it would be very helpful to have some file info, in the case of 24/96 FLACs or even just regular FLACs if you're expecting MP3s to put on your iPhone or something. This would give you a reason to want to choose a transcoded copy or not.

    For transcodes, since options are user-defined, you could use the "target format" row, or the "target name" row for safety in case there are multiple enabled targets of the same format (which also gets back to the Bandcamp example and its V0 and 320 distinctions).

* Transcoded filesizes don't always exist.

    This one's rough. The easiest thing I can think of is to include or generate a 10s snippet of some tone or CC0 track and then run it through the enabled transcode settings, measuring the output. Then you can extrapolate based on duration and the multiples of the test filesize that gets returned. This could be tied to the transcode settings themselves, and could be a fun thing to display in the table row there ("estimated size of 3m song" or something).

* Transcoded files don't always exist.

    I don't know if it would be easier to implement some kind of "please wait" situation while the files transcode and then get zipped up, but more likely the better experience would be to use the email that exists for the user and send them a link to come back to when the work is done. But since you cache transcodes anyway, it probably makes sense to just warm that cache as normal and not store the zip file, but to still stream it on the fly when the button is clicked again or special URL is accessed directly.

    Transcoded entries in the dropdown/flyout/modal-list could have a little icon denoting they're going to transcode first. Maybe this is always present for transcodes and the color/fill/opacity changes when the files are coming from cache vs needing to be generated, or maybe it only exists when the files don't.

That makes this a really complicated thing to bite off, so I understand completely if it gets dealt to the bottom of the list over and over....

- [ ] Redo transcoding subsystem? (you mentioned wanting to do this in Discord)
- [ ] Figure out consistent modal layout, or nested option selecting from download buttons everywhere they appear
- [ ] Display filetypes (including media info about bits/sample-rate)
- [ ] Change default Target Names for default transcode commands since they're more public facing (an easy one!)
- [ ] Calculate or otherwise estimate approximate filesizes per transcode command
- [ ] Determine, and then indicate, whether cached transcodes exist for the given view
- [ ] Handle someone coming back to a download...
- [ ] ...or create some sort of holding screen that's appropriate for how long a transcode + zip operation could take
- [ ] ???

**Comment by deluan** [comment]
Thanks for the detailed request :) 

The hardest part will definitely be the UI/UX. On the server side, it would be very simple to create an option for the `download` endpoint that receives the `maxBitRate` and `format` (as soon as the new transcoding is done [#351]). The sizes can be estimated using the formula: (Duration*BitRate*1000) / 8. 

Transcoding the files in real-time is easy and usually fast enough (maybe not much for a Pi 1 or smaller system), the bottleneck is the transmission over the wire. So for transcoding we could simply use the current stream mechanism, that even handles the cacheing. We wouldn't need to pre-process the download and have a "come back later" functionality.
