### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by ericlathrop** [navidrome/navidrome#585]
The web UI might already have keyboard shortcuts, but I've been unable to locate them. I'd specifically like a shortcut for play/pause. Many apps use the "?" key to popup a list of all keyboard shortcuts.

**Comment by deluan** [comment]
The only kbd shortcuts right now is <SPACE> to play/pause. I plan to add more in the future, and adding the ? is a great idea, thanks!

Do you have suggestions on other keys? Like what to use for Skip to next song, Play previous song, etc... ?

**Comment by ericlathrop** [comment]
Woah, I just saw that Navidrome in Firefox on Ubuntu shows media controls, and the normal keyboard media keys work. I didn't know that was possible in a web page. That solves my immediate problem. For some reason the album art doesn't show up, though.

Anyways, suggested keyboard shortcuts:

- Maybe `alt+letter` to jump to the different Albums/Library sections
- Some way to focus the search bar
- Arrows + `hjkl` to move selections around in lists
- `<` and `>` to go previous/next pages

**Comment by alexmat** [comment]
`s` or `*` to star the currently playing song would be nice to have

**Comment by certuna** [comment]
Here's the list for [Spotify](https://support.spotify.com/us/article/Keyboard-shortcuts/). I must say, I prefer Ctrl-Left/Right for skipping tracks, less accidental presses.

**Comment by Rishabh-malhotraa** [comment]
@deluan How about the idea of custom keybinds?

**Comment by deluan** [comment]
@certuna I actually copied Left/Right from our beloved iTunes 😛 

@Rishabh-malhotraa , it is more code to maintain that adds little value / will not be used by most users. We can poll users in our #general Discord channel, but I'd like to hear end-users' opinions, not devs opinions :)

I'll close this as the main shortcuts are implemented, together with a help dialog (activated with "?") as per @ericlathrop's original request. We can open a new issue if someone wants to suggest other ideas related to this.

**Comment by bbsixzz** [comment]
I would like to suggest a command that takes you to the currently playing track in an album.

Just like clicking the currently playing track.

Cheers

**Comment by deluan** [comment]
> I would like to suggest a command that takes you to the currently playing track in an album.
> 
> Just like clicking the currently playing track.
> 
> Cheers

That's a good suggestion, thanks! Can you please open a new GH issue, so this is not buried in a closed issue, and can be picked up by other contributors? Thanks!

**Comment by bbsixzz** [comment]
You got it! 

https://github.com/navidrome/navidrome/issues/1336
