### ISSUE TITLE
Streaming for Mobile

### ISSUE THREAD

**Issue by etcimon** [navidrome/navidrome#586]
The appropriate transcoding options for mobile should be 

`ffmpeg -i %s -map 0:0 -b:a %bk -v 0 -c:a libvorbis -f webm -`

And force the bitrate to be a certain amount for the bandwidth limits set below.

Now, because most players will not buffer mp3 or others properly, webm was specifically designed to support a streaming buffer that is equal to the playback bitrate.

So, there should be a bandwidth limit to avoid full media download on mobile networks, which can use gigabytes easily when skipping many songs after the first 5 seconds.

Here is a nginx setting that works well for me:

```
        limit_rate_after 300k;
        limit_rate       48k;
```

Hope this helps.

**Comment by deluan** [comment]
Hey @etcimon, thanks for taking a look at this. When you say mobile, you mean mobile apps (Subsonic clients) or mobile browser? Either way, I'll take a look at this when revamping the Transcoding feature in #351

**Comment by etcimon** [comment]
For both but personally I use ultrasonic and I think it would be nice being able to choose the transcoding, bandwidth limit and bitrate from the client to have a "Streaming + buffer" setting that prevents downloading the whole songs within 5 seconds of playing them if wifi is not detected

**Comment by certuna** [comment]
> most players will not buffer mp3 or others properly

The format has been around for 25 years now, you'd expect applications/libraries buffer it correctly by now, what specific issues are there with the current implementations?

**Comment by etcimon** [comment]
> The format has been around for 25 years now, you'd expect applications/libraries buffer it correctly by now, what specific issues are there with the current implementations?

If you try e.g. the mp3s from billboards, no idea why but sometimes the buffer would be 300kb before it can play, and sometimes 3mb wasn't enough (in ultrasonic). I did a lot of testing and webm was perfect.

**Comment by deluan** [comment]
Sorry, but I don't quite understand the action you are suggesting. Is it just a matter of creating a new transcoding with the command above? Or does it also need some change code? What about the Nginx config, Is it required?

**Comment by etcimon** [comment]
Well, for mobile streaming to work you need to limit the bandwidth and use webm, because the other transcoding options I've tried failed to use a predictable buffer. I think clients should be able to choose &streaming=true, and navidrome would automatically transcode to webm and use a bandwidth limit to 48KB/s after a fast download of the first 300KB

**Comment by deluan** [comment]
I don't think this is easy to coordinate with all clients out there (adding a `streaming=true` param). Maybe this can be created as a page in the documentation, explaining the issue and pointing to creating the new transcoding option and help to configure the reverse proxy?

**Comment by etcimon** [comment]
The problem is, streaming is the default option in all major media players (amazon music, spotify, apple music, etc). Making this a major configuration burden hidden in the docs is quite a bit 1990ish

**Comment by deluan** [comment]
As is the Subsonic API :P. But I agree with you, I'll take this in consideration when working on the new transcoding options #351. Maybe adding a flag to the transcoding option to rate-limit the stream, and also add a default `webm` transcoding option by default (together with the current `opus` and `mp3`). Do you think this would be enough?

**Comment by etcimon** [comment]
Yes, making it more extensible like that would be even better, it would be nice too if it followed the `maxBitRate` parameter and could set the rate-limit to a value relative to the bitrate. E.g. `$initDownload=$bitRate * 10, $bandwidth=$bitRate*1.2`

**Comment by etcimon** [comment]
The `maxBitRate` is from this query btw: ` "GET /rest/stream.view?id=e8e90f73a7ecdfa7596b55dd9b572629&maxBitRate=320&u=etcimon&c=Ultrasonic&f=json&v=1.12.0&p=enc:507373777264313238 HTTP/1.1" 200 6603155 "-" "okhttp/3.10.0" "-"`

**Comment by deluan** [comment]
Yeah, I'll do that **_if_** I can get a simple and lightweight way to rate-limit the streaming in Go. Or else this will need to be done at the reverse proxy level
