### ISSUE TITLE
MP3 will not play in Dsub if song title tag contains "/"

### ISSUE THREAD

**Issue by iang77** [navidrome/navidrome#592]
The songs will play in Navidrome's web UI but not to Dsub. I believe this is a Navidrome issue as the same songs will play to Dsub from Airsonic.

**Comment by deluan** [comment]
Hummm. I don't think this is the real issue. I have tons of songs with `/` in their titles and they play correctly (I just tried _The Fall - 41 Loop / Houston_ and it worked)

Did you try multiple songs with `/` in their names?  What is your environment (Windows, Linux, Docker)? Is you music library mounted over a network share?

Can you send me a song that has this issue (as a DM in Discord), so I can try to reproduce the issue here?

**Comment by iang77** [comment]
Ah damn, I thought I had it!
Ok I'll send you an example in discord.
I'm running navidrome on a raspberry pi (I think it's a model b 3+) running buster. I run it directly on the pi not in docker. My music is on a Synology over a network share.
Admittedly I only tried one song but I tried changing several different tags before this eventually worked.

Cheers

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by iang77** [comment]
Hey

Hopefully you recall this issue.

This is FYI really. I asked the Darren the DSub developer to take a look at this issue to see if it is something Dsub related. His reply is below (his comments in italics). I'm not 100% sure what he means but I wonder if it's something to do with the way my music is stored externally to my RPi. Hope this helps.

Cheers
Ian



Here's a couple of examples of tracks that have the issue:
Godspeed You! Black Emperor - Lift your Skinny Fists Like Antennas to Heaven (all the tracks, there is a lot of "/")
Anne Muller - Heliopause - "Aarhus / Reminiscences"

But interestingly the tracks that contain "/" on Bernard Herrmann - North By North West don't seem to have the issue.
I've tried removing the "/" from the filename on the Godspeed tracks but it had no effect if the tag still had the "/" in it.


One of the example children returned from the server:

<child id="55798211c0cbb88aa39e21a5cb6b37ad" parent="8de7904879fcdd721f0db07210bac4ad" isDir="false" title="Storm: Lift Yr. Skinny Fists Like Antennas To Heaven / Gathering Storm / "Welcome To Barco Am/Pm..." / Cancer Towers On Holy Road Hi-Way" album="Lift Your Skinny Fists Like Antennas To Heaven" artist="Godspeed You! Black Emperor" track="1" year="2000" genre="Rock" coverArt="al-8de7904879fcdd721f0db07210bac4ad" size="54102146" contentType="audio/mpeg" suffix="mp3" duration="1352" bitRate="320" path="Godspeed You! Black Emperor/Lift Your Skinny Fists Like Antennas To Heaven/Storm: Lift Yr. Skinny Fists Like Antennas To Heaven / Gathering Storm / "Welcome To Barco Am/Pm..." / Cancer Towers On Holy Road Hi-Way.mp3" discNumber="1" created="2014-04-26T23:29:31Z" albumId="8de7904879fcdd721f0db07210bac4ad" artistId="ce13052cb6d1b612467040d837c76d91" type="music" isVideo="false"/>


I am not able to reproduce the same issue. On my phone all of the files from "Lift your Skinny Fists Like Antennas to Heaven" for example were downloadable and playable.

I am guessing the issue is coming from the fact that some paths in the code are trying to use the path listed in the child entry. In this case that path is completely not valid. Stock Subsonic will never return a path like that, because in Subsonic that is the literal path to the file on the server. This server appears to be generating a path based on the file tags, which is generating bad data. Looking through it I don't think this is something I can really fix while maintaining compatibility with other Subsonic servers that implement it the other way. The server needs to be changed replace all of those dashes in the filename in the path to be something else like a "-". For example instead of Godspeed You! Black Emperor/Lift Your Skinny Fists Like Antennas To Heaven/Storm: Lift Yr. Skinny Fists Like Antennas To Heaven / Gathering Storm / "Welcome To Barco Am/Pm... it should be something like Godspeed You! Black Emperor/Lift Your Skinny Fists Like Antennas To Heaven/Storm: Lift Yr. Skinny Fists Like Antennas To Heaven - Gathering Storm - "Welcome To Barco Am-Pm....

For example here is it returned by Subsonic based on the tags:

<song id="17210" parent="17211" isDir="false" title="Storm: Lift Yr. Skinny Fists Like Antennas To Heaven / Gathering Storm / "Welcome To Barco Am/Pm..." / Cancer Towers On Holy Road Hi-Way" album="Lift Your Skinny Fists Like Antennas To Heaven" artist="Godspeed You! Black Emperor" track="1" year="2000" genre="Rock" size="54102146" contentType="audio/mpeg" suffix="mp3" duration="1352" bitRate="320" path="Testss/Storm Lift Yr.mp3" isVideo="false" playCount="0" discNumber="1" created="2020-12-31T23:52:35.000Z" albumId="1286" artistId="478" type="music"/>





________________________________

**Comment by deluan** [comment]
Thanks for the info. If the "fabricated" paths are the issue, you can disable it and use the real paths (as Subsonic/Airsonic do), using the "Report Real Path" option: #625

But looks like this is happening only in your setup, as even @daneren2005 was not able to reproduce it. Well, try using real paths and let me know.

**Comment by iang77** [comment]
Looks like we finally got there! It took a server restart for the setting to apply but it works now.

Thank you!
Ian

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by deluan** [comment]
Not sure why it worked (as this is not an issue for others), but I'm glad the issue is fixed for you!!

Will implement the mapping suggested by Darren ('/' -> '_') for the "fabricated" paths. Will keep this issue open to track it.

**Comment by iang77** [comment]
Perfect - thanks again.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
