### ISSUE TITLE
Feature request: add song to multiple playlists

### ISSUE THREAD

**Issue by esfateev** [navidrome/navidrome#609]
Hi!
If you would like to add song to multiple playlists, it will be more user-friendly IMHO to perform this action in "One-click". Is it possible to add this feature? 

Thanks, love this project!

BR, Eugene

**Comment by deluan** [comment]
Thanks for the suggestion, but I'm not sure about this one..... Do you know any music player with this feature? 

I'm also not sure about the UX in this case, how to implement this without making the UI too complex for the simple use case (add to one playlist)

**Comment by Darthagnon** [comment]
Maybe he's thinking about something like the Polymer Youtube "Add to Playlist" popup window - Click on a "Add to Playlist" button next to a song, and the popup window displays a scrollable list of existing playlists (plus a "New Playlist" field) with checkboxes next to each playlist. Check boxes for desired playlists for a song, click OK, and it's added to all the selected playlists.

**Comment by deluan** [comment]
@Darthagnon thanks, never saw this, but that could work. Will try it in a future release

**Comment by esfateev** [comment]
@Darthagnon yes that's exactly what i meant! Youtube is a good example :)
