### ISSUE TITLE
Need to clear browser cache after creating admin

### ISSUE THREAD

**Issue by gramakri** [navidrome/navidrome#613]
I am creating a navidrome package for Cloudron (at https://git.cloudron.io/cloudron/navidrome-app). I have noticed a peculiar behavior:

* Install navidrome. Create admin user.
* Logout
* I see login screen.
* Reload navidrome in browser.
* The UI keeps asking me to create admin user.
![image](https://user-images.githubusercontent.com/82041/98182070-b5094a00-1eb9-11eb-9ce2-e177ed908afb.png)
* Trying to create admin user will say "Error: Forbidden"

If I clear the cache, it shows login screen.

**Comment by gramakri** [comment]
The bug is reproducible with chrome and firefox. Also, I can see that the admin user exists in the sqlite database.

```
sqlite> select * from user; 
a9762f97-8750-4c86-8067-8cd93190243b|admin|Admin||Mh12ac21|1|2020-11-05 00:19:26||2020-11-05 00:19:26|2020-11-05T00:19:26.177282093Z
```

**Comment by deluan** [comment]
Hey, thanks for creating the package!

I can't seem to reproduce the issue here (using Chrome on macOS), but it is happening with Firefox. This used to happen in very early versions, but it's supposed to be fixed since April. I'll investigate a little more and let you know. Thanks!

**Comment by gramakri** [comment]
@deluan After a bit of debugging, I found it's something to do with service worker. If you go to Firefox/Chrome, App -> Service Worker -> Unregister and then reload the page, it starts working again. 

Also, I can confirm with curl that firstTime is set to false correctly in app config. So it's a frontend issue.

**Comment by deluan** [comment]
Thanks for the information. The service worker was introduced recently, when we added PWA capabilities to Navidrome. Will have to figure out how to handle this situation. Seems that it caches the index.html by default.

**Comment by certuna** [comment]
This might offer a solution: https://github.com/facebook/create-react-app/issues/7700

**Comment by deluan** [comment]
Thanks for the digging, @certuna 

It seems that most solutions on the links above will require to "eject" the CRA app, meaning all build and config code will be added to Navidrome's codebase, and will make it impossible to upgrade CRA in the future....

But there is hope: https://github.com/facebook/create-react-app/issues/3171#issuecomment-331583584 
Will try this later this weekend.

**Comment by certuna** [comment]
That would probably also fix the issue I've just encountered: even though I've updated my server twice (0.36 and 0.37) since I installed the PWA on my iPhone, it still says 0.35 in Menu-About, i.e. it has cached the assets on install and isn't refreshing them, even when I tap the 'refresh' icon.

**Comment by deluan** [comment]
The library used by the link I posted above (sw-precache) is deprecated.... and the new version of CRA removed the provided service worker due to [too many problems with them without proper configuration](https://github.com/facebook/create-react-app/issues/4674#issuecomment-406943230)

We will need more time to properly configure a service worker for Navidrome and not rely on the default provided by CRA. This will require a bit more work (I never used service workers before), so I thin kthe sensible thing to do for now is to introduce a config option to enable the service worker, and it would be disabled by default.

Thoughts?

**Comment by deluan** [comment]
Found another, possibly simpler and more elegant solution: https://felixgerschau.com/create-a-pwa-update-notification-with-create-react-app/ 

Will try it this week.

**Comment by certuna** [comment]
That's a great find, looks like the best thing to use. Maybe also use the "refresh" button on the top right to not just reload dynamic content, but also force a reload of the static files at the same time?

**Comment by obbardc** [comment]
I had the same issue when upgrading to a new version using docker on develop branch: the web ui asked me to create a new admin user even though I already have an admin user. Eventually it let me login though.

**Comment by deluan** [comment]
For those having this issue, another workaround for now is to Force Reload the UI (Shift+Control+R)

**Comment by certuna** [comment]
Shift-Control-R not so effective on phone or smart TV unfortunately...

Can we add a quick "clear the serviceworker cache" snippet to the js triggered by the Refresh button top right, like this:

```
caches.keys().then(function(names) {
    for (let name of names)
        caches.delete(name);
});
```

**Comment by deluan** [comment]
Nice finding, will take a look at adding this. I tried the solution from the post I linked, but it is not as straightforward as it seems. Still have to figure out some loose ends

**Comment by TheLonelinessOfHS** [comment]
Hi, same issue here. Hope you can fix this. Thanks.

**Comment by deluan** [comment]
Another possible solution to reload assets on a new version: https://deanhume.com/displaying-a-new-version-available-progressive-web-app/ (thanks @certuna)

**Comment by certuna** [comment]
I think my PR fixes it, please test :) Also, name of this issue should probably be changed to: `Need to clear service worker cache after creating admin`

**Comment by deluan** [comment]
I'll keep the issue open until I test it thoroughly. Thanks @certuna !

**Comment by deluan** [comment]
I can confirm this is fixed!! Thanks again @certuna ! Now we have to come-up with the fancy "There's a new version available, please refresh" logic :)

**Comment by certuna** [comment]
I'll make a new issue for that.
