### ISSUE TITLE
[Feature Request] - Album collections

### ISSUE THREAD

**Issue by dertasiu** [navidrome/navidrome#626]
Hello!
It would be awesome to have a feature similar to the playlists, but to group albums in.
This way we could make collections like "Top 100 albums...", "Concerts that are awesome".
It could be right below the "Playlists" menu item.
![playlist-collections](https://user-images.githubusercontent.com/11269785/99155085-44caa780-26b5-11eb-840b-0418a610bf8c.png)

The only problem that I see with this feature is how to implement it with the Subsonic API. Lately I have been rating albums in Airsonic with stars and, in DSub, they appear as a list of albums. I don't know if there is something similar in the API itself.
![best-dsub](https://user-images.githubusercontent.com/11269785/99155109-5ca22b80-26b5-11eb-9598-e4128ce0483a.jpg)

Another solution could be having a "Collection" checkbox in a playlist. That way it would be compatible with Subsonic API and it would only present differently on the web client. A bad thing about this idea is that, conceptually, we would be grouping tracks and not albums, although it would be much easier to group certain concerts that are included in some anthologies, like the King Crimson ones.
![kc-foobar2000](https://user-images.githubusercontent.com/11269785/99155136-996e2280-26b5-11eb-8439-1d73861eb3ae.png)

**Comment by certuna** [comment]
This could be implemented the way Apple has done it, i.e. allow playlists to be displayed in the album view

So you fill up a playlist full of whole albums, set the album view as default for that playlist -> album collection

**Comment by deluan** [comment]
Yes, Smart Playlists + Album view will solve this. It won't be available through Sunsonic API, though... Currently if you just want to create a list of Best albums, you can "star" the albums and they will appear in DSub's Starred view.

**Comment by certuna** [comment]
Still relevant and valuable.
