### ISSUE TITLE
Playlist group/multiple playlists into one

### ISSUE THREAD

**Issue by Extarys** [navidrome/navidrome#636]
I never really saw this feature elsewhere so maybe it's a niche request/feature but I'll explain what I'd like/what I'm doing. This is not high priority, but a simple suggestions other users could also comment on. Although this could be easily implemented once **smart playlists** are implemented.

I have multiple playlists in the style of "my own very best"

- Era - My own very best
- Enya - My own very best
- Faun - My own very best

I'd like a way to merge those playlists into a single automated playlist:
- Celtic/New-age - My own very best

I could also do the same for other styles/genre and events.

Adding a song to any of the playlists above would either also add it to the last one or the last one just pulls songs from each playlists. 
So either it's static, you add a song to one, it automatically add the song to the dynamic one (same on delete) or,
dynamic, the dynamic playlist pulls the songs of all other playlists on request.

I can imagine a playlist with a bar on top displaying a table:

This playlist also includes the songs of the following playlists: *list of playlists with number of songs etc*

**What does it fixes/solves? TLDR**
I currently have a "My own very best" for ~20 artists. I also have a playlist "Pop", "Old pop" (which is songs adults were listening when I was younger I still enjoy but are a little _quitch_. One for hip-hop/rap, another similar that are smoother, one for songs from my region, etc. I end up adding the same song on multiple playlists. I also tend to add the original song when the same one is on multiple albums but sometime I make a mistake so the same recording on 2 or 3 different albums have 10+ play count.

Having a way to merge multiple playlists dynamically would allow easier management for the users having a lot of music/playlists.

**Comment by deluan** [comment]
This will definitely be possible with Smart Playlists, with rules like this (from iTunes):
<img width="852" alt="Screen Shot 2020-11-17 at 10 11 36 AM" src="https://user-images.githubusercontent.com/331353/99407641-5383ab00-28bd-11eb-8626-7f2cd1c95a27.png">

**Comment by Extarys** [comment]
Oh thank you! It's been a long time since I was able to play with smart playlists, the ecosystem is limited on linux - or maybe just for music server in general. I wasn't sure if this was a normal thing.

:rocket:
