### ISSUE TITLE
Ratings in local UI?

### ISSUE THREAD

**Issue by bricas** [navidrome/navidrome#639]
First of all, thank you very much for this app! It's been very responsive on my Pi-based server, unlike other ones I've tried.

I'm moving from desktop-hosted content to my server and I'm hoping to get as close to what I'm used to as possible.

I've been using Banshee as a player and I've gotten used to two things: 1) smart playlists (which I see in another ticket that you're planning on implementing [yay!]) and 2) ratings (0-5).

I see in the subsonic code that you support both stars and ratings, but it seems like the local UI only supports stars. Is there a plan to include (or enable by config) ratings?

Thanks again.

**Comment by deluan** [comment]
Thanks for trying Navidrome! Yes, 5-star ratings will come to the UI at some point, probably before the Smart Playlist implementation. Keep tuned :)

**Comment by bricas** [comment]
Excellent. Thank you! :trophy:

**Comment by neilchauhan2** [comment]
Hi @deluan, I would like to work on this. I could see there is a method in server code the setRatings in the subsonic folder. I would like to know a little more about how do you want the ratings to be implemented. Do you want the ratings to be visible only at the individual song or do you want the ratings to visible on both playlist items and the the individual song item?

**Comment by deluan** [comment]
@neilchauhan2 Ideally we would display the 5-star rating everywhere. Keep in mind that albums and artists can have stars. Example form DSub: 

![Screenshot_20210313-103005](https://user-images.githubusercontent.com/331353/111035411-71cf6280-83e8-11eb-8e6a-2d8e8eacdb08.png)

I though about adding the 5-star rating to the song, artist and album ContextMenus.

**Comment by neilchauhan2** [comment]
@deluan I'll go through it and let you know if I'm stuck somewhere. One question I have is, what is going to be the default value for the ratings, i.e. are we trying to show the general ratings as per other people's response for a particular song and artist or is this a personalized rating which is only limited to the current user. In any case how do I fetch the default value for the ratings? Is there some method available in the ui already for that purpose, or do I need to create a new method(api call) to fetch and change ratings? I would like to have some guidance over this.

**Comment by deluan** [comment]
Hey @neilchauhan2 I think it is worth to take a look at DSub and see how it handles it: https://github.com/daneren2005/Subsonic/releases (of course only if you have an Android device)

Answering your questions:
- Currently the UI does not handle the ratings in any way, but the APIs are in place.
- The rating is personal, and it is returned as part of the `/song` `/album` and `/artist` API calls. To set the rating you can use the Subsonic API endpoint: http://subsonic.org/pages/api.jsp#setRating. The implementation will be very similar to how Navidrome handles "Starred" items.

> Lastly, I'm fetching music from my music folder, can I know if there is a way to fetch music from the api so that I could make changes to the ratings for a particular song based on the api. Otherwise, I guess the changes might remain local since the music is being fetched from a local directory.

I didn't understand what you are asking here. Navidrome's web UI is fully based on two APIs (one proprietary and the Subsonic API), and does not access any local files. All operations goes through the GoLang server.

**Comment by neilchauhan2** [comment]
> Lastly, I'm fetching music from my music folder, can I know if there is a way to fetch music from the api so that I could make changes to the ratings for a particular song based on the api. Otherwise, I guess the changes might remain local since the music is being fetched from a local directory.

@deluan by this I mean, as stated in the build setup readme I created a music folder in which I have saved 2 songs. I'm only able to view those songs in the entire Web UI when I use `make dev` . So I'm only able to view the songs that are available in my music folder in the project. How do I fetch music from the api?

**Comment by neilchauhan2** [comment]
![screencapture-localhost-4533-2021-03-19-18_05_49](https://user-images.githubusercontent.com/31568159/111780978-22080400-88de-11eb-8058-69ffecd4655b.png)

![screencapture-localhost-4533-2021-03-19-18_05_21](https://user-images.githubusercontent.com/31568159/111780942-16b4d880-88de-11eb-9002-9170b463926d.png)

@deluan I've implemented the `setRatings` feature for the **Songs** and **Albums** as you can see from the above screenshots. But, I'm not able to implement the ratings feature for **Artists**. Since, in the **ArtistList** component, each item is a link, and after adding the Ratings component each time I try to rate the artist, I get redirected to the Artist's Albums without the ratings being applied to the Artist.

**Comment by neilchauhan2** [comment]
> But, I'm not able to implement the ratings feature for Artists. Since, in the ArtistList component, each item is a link, and after adding the Ratings component each time I try to rate the artist, I get redirected to the Artist's Albums without the ratings being applied to the Artist. Could you tell me how can I implement the ratings feature for Artists?

@deluan I've figured this out, and now its working. But now the issue is that the while I'm trying to hit the `/setRating` endpoint for Artist, the ratings are not been applied. But in case of Albums and Songs everything works fine. Not sure why am I running into this issue. I'm almost done with the setRating feature, and I'll raise a PR shortly. Please review and let me know why the Rating feature is not working for Artist.

**Comment by neilchauhan2** [comment]
#862

**Comment by AndersMoberg** [comment]
Been waiting for ratings in the Navidrome UI for quite a while, so very excited to see this turn up as a pull request. Not certain where I should add this comment, but having both ratings and the "starring" iconography be the same could be confusing for the newcomers.

Some players use the "heart" icon for one of them. I still personally associate stars with a rating, so perhaps "staring" thing should change to use hearts instead?

Perhaps the user should be able to select between the two (or more?) for both ratings and starring in the personal settings page?

**Comment by neilchauhan2** [comment]
@deluan I've created a PR for the Ratings, #862 please have a look. The Ratings feature works perfectly for Albums and Songs. But, in case of Artist I guess there is some issue with the subsonic api. I tried changing the ratings for Artist even with a REST client Postman, but still the ratings are not been updated. I still enabled the ratings feature for Artists, it might be possible there would have some issue with my machine in dealing with the api. So, please have a look and let me know what needs to be changed.
I've added screenshots in the PR of the final update.
**PR** - #862

**Comment by neilchauhan2** [comment]
@AndersMoberg I agree to you, having 6 stars in UI can be a little confusing for some people, but I've made an update such that the Rating label is attached to the Item Lists so that people know what these stars mean, you can see the screenshots in the PR. And, in my opinion as well using stars for rating is more preferable because people find it more relatable. But still, we can definitely think about changing the **Star Feature Icon** to a **Heart Icon**, and change the typography (name of the Star feature) from **Star** to **Favorites**, since most platforms use Heart Icon for **Starred/Favorite** Items, Songs, Posts, etc.

**Comment by metalheim** [comment]
@neilchauhan2 I like the idea of changing the iconography towards *heart* for *favorite*. As you said, most music platforms do it this way and it would make a useful distinguish between *stars as rating* and *favorite*.

It's just that subsonic terminology uses *star* already (f.e. API calls to _getStarred_ endpoint). So I guess its a somewhat political decision if navidrome is willing to divert from the subsonic naming convention.

**Comment by deluan** [comment]
Yes, we decided to go with "Love"/"Loved" terminology and Heart as icon, it is less confusing and more inline with modern music services/players. But will keep it compatible with Subsonic API's  "Star" endpoints.

**Comment by neilchauhan2** [comment]
@metalheim I'm working on it, and soon you'll be seeing a :heart: instead of a :star: in the UI.

**Comment by neilchauhan2** [comment]
@deluan I've refactored the current Star feature to Love feature. Please review the PR #908

**Comment by metalheim** [comment]
Looks great

**Comment by neilchauhan2** [comment]
@deluan I've enabled the feature to turn on/off the Favorites/Loved feature. Please review the PR #917.

**Comment by neilchauhan2** [comment]
@deluan I've Added the Ratings feature with the option to enable/disable ratings. I've also added the `enableStarRating` config var to the server config. Please review the PR #986.
