### ISSUE TITLE
[WebUI] utilize Sort Order tags

### ISSUE THREAD

**Issue by certuna** [navidrome/navidrome#643]
Navidrome reads and stores Sort Order id3/Vorbis tags (Artist, Composer, Album, Song), but the Web UI doesn't use any of them when sorting by album or song title.

Proposal:

- _always_ use Sort Order tags for Album and Song titles
- _optionally_ use Sort Order tags for Artist/Composer: since MusicBrainz uses this field to store persons as "Lastname, Firstname", and many users prefer to see "Rick Astley" sorted under R, not A.

**Comment by KucharczykL** [comment]
Hi, would this also solve issues like having Japanese, Chinese and other-than-English names sorted after everything else instead of where it's supposed to be?

**Comment by certuna** [comment]
If the sort field (Sort Artist, Sort Album, Sort Title, etc) contains the Romanized names, then yes.

**Comment by upsuper** [comment]
It seems that at least some of the sort tags are not properly read. See #2188.

**Comment by KucharczykL** [comment]
Still interested because of how it affects non-Latin names.
