### ISSUE TITLE
ND_ADDRESS is not IPv4/IPv6-neutral

### ISSUE THREAD

**Issue by certuna** [navidrome/navidrome#646]
Currently, the Navidrome [configuration option](https://www.navidrome.org/docs/usage/configuration-options/) for IP address binding is:

Environment Variable: `ND_ADDRESS`
Description: IP address the server will bind to
Default: `0.0.0.0` (all IPs)

a) this suggests Navidrome can only bind to IPv4 addresses, as `0.0.0.0` only covers all *IPv4* addresses. In reality of course, Navidrome binds to all IPv6 addresses (`::`) too. I'm [updating the documentation](https://github.com/navidrome/website/pull/18) to reflect that.

b) this option appears to only allow binding to one address (so IPv4 _or_ IPv6). In a dual stack environment you probably want to bind to two addresses, one IPv4 and one IPv6. Or even multiple IPv6 addresses, since you can have multiple addresses per interface there. If this variable already does allow multiple values (comma separated?), then the docs should reflect this, if it doesn't, then support for it should be added.

**Comment by deluan** [comment]
(a) is merged. I agree with (b), we should support specifying different IPs for each stack. For reference: https://groups.google.com/g/golang-nuts/c/_cCyCgDfP-Y/m/jtZbieMCwPMJ

If anyone wants to tackle this, PRs are welcome :)

**Comment by certuna** [comment]
I guess we get new environment variables `ND_V4ADDRESS` and `ND_V6ADDRESS`

For IPv6 I suggest the following binding values:
- empty (defaults to all IPv6 addresses, aka `::`)
- "stable" (binds to all IPv6 addresses except temporary)
- "local" (binds to only ULA and link-local addresses)
- one address or a list of multiple (and also allow subnets so ND binds to all addresses from the subnet)
For IPv4:
- empty (defaults to all IPv4 addresses, aka `0.0.0.0`)
- one address or a list of multiple
