### ISSUE TITLE
[webUI] Album grid does not respect window size with narrow window

### ISSUE THREAD

**Issue by kolmone** [navidrome/navidrome#647]
Album grid view works inconsistently when viewed in a narrow window i.e. a phone screen where only two albums fit on the screen horizontally. On some pages of the album list the layout is broken in such way that the page content is wider than the window size and scrollable horizontally. Other pages of the album list work as expected, so the issue seems to be caused by specific albums (specific pages in my library always behave the same way).

Issue does not happen with old album grid layout in v0.36.1

Example screenshots from Chrome on Android, I can also replicate the issue in Firefox on Windows.

Correctly working page of my album list:
![working](https://user-images.githubusercontent.com/1036201/99812619-5990ba80-2b4f-11eb-89c5-1430a536c7b2.png)

Incorrectly working page:
![not_working](https://user-images.githubusercontent.com/1036201/99812631-5c8bab00-2b4f-11eb-9809-36de98c4901c.png)

Incorrectly working page zoomed out to show all content, text and other elements on the page are smaller:
![not_working_zoomed](https://user-images.githubusercontent.com/1036201/99812638-5eee0500-2b4f-11eb-8b61-e62c9a2b41a2.png)

**Comment by deluan** [comment]
Thanks for reporting this, I also noticed this yesterday. I think it is probably caused by the album's title and artist caption, that is new in this layout. Will take a look.

**Comment by Dnouv** [comment]
@deluan, I would like to work on this issue. Please assign me on this if it's still available.

**Comment by Dnouv** [comment]
@deluan, as per your suggestion, I added the albums with long names and a page full of albums but still could not reproduce the issue on the Album grid.
Here is the screenshot of the Album page.
<img width="210" alt="localhost_4533_(iPhone X)" src="https://user-images.githubusercontent.com/61188295/111420297-f8e64880-8710-11eb-9ebd-16648409249a.png">

**Comment by deluan** [comment]
Well, thanks for fixing the issue in the AlbumDetail view, but unfortunately this issue is still happening in the Album Grid:
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/331353/111727512-65606500-8841-11eb-90a4-52d053a54c57.gif)

**Comment by deluan** [comment]
I think I finally got it fixed! Will do more testings and it should be in the next release.
