### ISSUE TITLE
What do these errors mean after the latest update 

### ISSUE THREAD

**Issue by BobWs** [navidrome/navidrome#657]
Hi,
After updating to the latest version in keep getting these errors in the logs. What does it mean?
And how to solve this..
Thanks in advance.

`ERRO[0138] HTTP: GET http://music.mydomain.com/rest/getCoverArt.view?t=cca8f5ed7e5e98fc01e4c55af2768d06&c=playSub_iPadAir3rdgen&id=a7e7f5a56e78da8a54de66275eda0729&u=username&size=120&v=1.9.0&s=891689E5-A23F-4CE1-8BB3-2CA4FD5AFA53&f=json  elapsedTime="821.937µs" httpStatus=503 remoteAddr=192.168.178.232 requestId=navidrome/a7c8LCgW1H-000941 responseSize=22
stdout
11:20:31`

**Comment by deluan** [comment]
Weird. Do you see any issues with the covers in the play:Sub? Can you please add here the few lines above the error?

**Comment by BobWs** [comment]
No I don’t see any weird things or issues with the covers in play:sub.

Here’s the rest of the log before the error.

INFO[0000] Creating Transcoding cache maxSize="100 MB" path=/data/cache/transcoding stdout 11:18:13
INFO[0000] Mounting routes path=/rest stdout 11:18:13
INFO[0000] Mounting routes path=/app stdout 11:18:13
INFO[0000] Login rate limit set requestLimit=5 windowLength=20s stdout 11:18:13
INFO[0000] Navidrome server is accepting requests address="0.0.0.0:4533" stdout 11:18:13
INFO[0000] Finished initializing cache cache=Transcoding elapsedTime=27.321459ms maxSize=100MB stdout 11:18:13
INFO[0000] Finished initializing cache cache=Image elapsedTime=96.687028ms maxSize=100MB stdout 11:19:29
INFO[0077] Streaming file artist=Joe bitRate=0 cached=false format=raw originalBitRate=320 originalFormat=mp3 title="Man in Your Life" transcoding=false user=user stdout 11:19:30
INFO[0077] Streaming file artist=Joe bitRate=0 cached=false format=raw originalBitRate=320 originalFormat=mp3 title="Man in Your Life" transcoding=false user=user stdout 11:19:30
INFO[0077] Now Playing artist=Joe title="Man in Your Life" user=user stdout 11:20:04
INFO[0111] Streaming file artist=Roxette bitRate=0 cached=false format=raw originalBitRate=320 originalFormat=mp3 title="Listen To Your Heart (Swedish Single Edit)" transcoding=false user=user stdout 11:20:04
INFO[0111] Streaming file artist=Roxette bitRate=0 cached=false format=raw originalBitRate=320 originalFormat=mp3 title="Listen To Your Heart (Swedish Single Edit)" transcoding=false user=user stdout 11:20:05
INFO[0112] Now Playing artist=Roxette title="Listen To Your Heart (Swedish Single Edit)" user=user stdout 11:20:17
ERRO[0125] HTTP: GET http://music.mydomain.com/rest/getCoverArt.view t=408452ede7af01e92cdc04b26ad8effc&c=playSub_iPadAir3rdgen&id=f2daf773054b5b537140f3d2d3b97137&u=user&size=120&v 1.9.0&s=6618DE65-ABB3-4959-8464-EE2BD4281A33&f=json  elapsedTime=65.415569ms httpStatus=503 remoteAddr=192.168.178.232 requestId=navidrome/a7c8LCgW1H-000189 responseSize=22 stdout 11:20:18
ERRO[0125] HTTP: GET http://music.mydomain.com/rest/getCoverArt.view?t=4aaf9c7cbbf0cc705d2bd96bb3e34927&c=playSub_iPadAir3rdgen&id=eba2c3a5698e38d45f7118a6f02878b4&u=user&size=120&v=1.9.0&s=3C20F9A3-C8C1-49B8-8142-CB50D5C62B50&f=json  elapsedTime=82.04765ms httpStatus=503 remoteAddr=192.168.178.232 requestId=navidrome/a7c8LCgW1H-000190 responseSize=22

**Comment by deluan** [comment]
I don't see anything wrong.....  the error 503 is [Service Unavailable](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503) and it is not one of the errors returned by Navidrome. Maybe your reverse proxy is returning this error? What happens if you open the URL in the browser?

**Comment by deluan** [comment]
I don't see anything wrong.....  the error 503 is [Service Unavailable](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503) and it is not one of the errors normally returned by Navidrome.

Can you change the log level to `trace`, call one of the `getCoverArt.view` URL with errors from  the browser, and send me the logs generated by the call? You can send it to me in private through reddit: /u/deluan, to my email deluan AT navidrome.org, or through Discord if you have an account there.

**Comment by BobWs** [comment]
Vert strange but today I haven't seen the error message in the log! I will keep an eye on it and report back if it happens again.

**Comment by BobWs** [comment]
> Vert strange but today I haven't seen the error message in the log! I will keep an eye on it and report back if it happens again.

Guess it was a onetime thing because the error message is still there. Don’t see any thing strange and as far as I can see everything is working fine. 

Merry Christmas!🎄🎁
