### ISSUE TITLE
feature request -> Visualizer

### ISSUE THREAD

**Issue by count00zero** [navidrome/navidrome#674]
First things first: I really LOVE navidrome and your work you are investing in it!
It's fast, it's stable, it's great! :)

I'm a sucker for "viz" ... therefore I like the Milkdrop Visualizer Feature of mStream (https://github.com/IrosTheBeggar/mStream).

Do you think it would be able to include something like that (in the future) in the  navidrome webplayer (NavidromeUI)?

just ~~beggin'~~ sayin' :)

**Comment by deluan** [comment]
Hey, thanks, glad you like it!

Yes, this may be implemented in the future. If anyone wants to give it a shot: https://github.com/jberg/butterchurn

**Comment by Rishabh-malhotraa** [comment]
@deluan @jvoisin I can try to implement this, it should not be that hard to do, I also went through some examples for audio visualisation on GitHub and codepen and I like these one, please guide me on which one should i go ahead with while implementing this feature. I am listing them in order of preference

1. [https://codepen.io/alexdevp/full/RNELPV](https://codepen.io/alexdevp/full/RNELPV) Seems Easiest to Implement and this also has a react library, so implementing this would be straight forward
2. [https://codepen.io/prakhar625/pen/zddKRj](https://codepen.io/prakhar625/pen/zddKRj) : Easy WEBGL THREEJS Implementation, this one also has a medium blog written about it so it shouldn't be hard to implement
3. [https://labs.fluuu.id/lines/](https://labs.fluuu.id/lines/) I find this the most aesthetically pleasing but I don't know if would lag for old computers
4. [https://alexmubarakshin.github.io/mu-vis/](https://alexmubarakshin.github.io/mu-vis/) This one looks like big brother from 1984 :O

I also love how mubert does its audio visualization (its an AI generative music app), the visualization looks like  these if you are interested [example1](https://www.uberviz.io/viz/word-problems/) [example2](https://lhbzr.com/)
But these look somewhat atypical to implement

Looking forward to hearing back from you.

**Comment by deluan** [comment]
@Rishabh-malhotraa , thanks for the suggestions, but the original feature request is for implementing a [Milkdrop](https://en.wikipedia.org/wiki/MilkDrop)-like visualizer, and none of the options you showed falls into that category. I did some research in the past to see what could be used here, and the library that seems to be a good fit is [Butterchurn](https://github.com/jberg/butterchurn).

The issue with Butterchurn (and any viz library for that matter), is that they are huge (Butterchurn is 700Kbytes+), and adding such libraries would slow down Navidrome's start-up times.

If we could find a way to load it dynamically, like requesting it from the server only if enabled/configured, then we could "afford" adding it to the project. I didn't spent too much time thinking about a way to do it, so if you can think of something, you can try.

**Comment by Rishabh-malhotraa** [comment]
> If we could find a way to load it dynamically, like requesting it from the server only if enabled/configured, then we could "afford" adding it to the project. I didn't spent too much time thinking about a way to do it, so if you can think of something, you can try.

I think the react way of doing this would be by  [code splitting](https://reactjs.org/docs/code-splitting.html), i.e lazy loading the component
``` jsx
const MilkdropVisulaizer = React.lazy(()=> import("components/Visualizer"));
```
>*By using React to handle the loading of each module, we can lazily load in components at any point with our app. This includes nested modules*.

and then render that component only when we have the setting to have milkdrop visualization is set as true.

``` jsx
  ...
  return (
      {
        shouldShowMilkDropComponent && <MilkDropComponent />
      }
  )
```


![react-lazy-chunks-lazy-load](https://user-images.githubusercontent.com/54576074/112748040-d983d100-8fd6-11eb-81ad-318bc06ff2ed.jpg)

**Comment by deluan** [comment]
@Rishabh-malhotraa I had issues with code splitting and tree-shaking in the past, so my current approach is to not add any dependencies unless strictly necessary, but if you prove our WebPack config will handle this situation, go for it.

**Comment by count00zero** [comment]
I personally think that any visualization which is implementable - without breaking code or adding to much payload - is a great addition ... mustn't be milkdrop :)

**Comment by Rishabh-malhotraa** [comment]
> I personally think that any visualization which is implementable - without breaking code or adding to much payload - is a great addition ... mustn't be milkdrop :)

I right now am trying to get the butterchum milk drop visualization working in Navidrome, anyway do have a preference for the ones I have mentioned earlier.

**Comment by count00zero** [comment]
> I am trying to get the butterchum milk drop visualization working in Navidrome, anyway do you like any in particular of the ones that I have mentioned earlier.

I personally like #1 and maybe #2 :)
