### ISSUE TITLE
New feature - playlist options for admin

### ISSUE THREAD

**Issue by abescalamis** [navidrome/navidrome#698]
Can you please add the option for the admin to select which user can edit a playlist and also the ability to change owner of playlist.

**Comment by deluan** [comment]
You mean, edit playlists in general or given permissions for each playlist? I will probably introduce the former option, but having fine grained playlist permissions is not in the current plans. Ability to change a playlist's owner is covered by #490. There's a small issue with the React Admin library that prevented me to release this, but it is coming.

**Comment by abescalamis** [comment]
What I meant is for the admin to be able to lock the playlist, so the users cannot make changes or delete the playlist, but he can select which user/users can edit or delete the playlist

**Comment by mradermaxlol** [comment]
@deluan is playlist refactoring mentioned in #1366 going to (by chance) help this issue in any way?

**Comment by deluan** [comment]
> @deluan is playlist refactoring mentioned in #1366 going to (by chance) help this issue in any way?

Well, it may help as the code becomes simpler, but it is not related to this issue at all. 

> As far as I understand, it's in the scope of this issue.

Yes it is. Also being able to change the owner of a playlist which will probably be implemented first, but i don't have a timeline for any of this, as I have other priorities in the project ATM.
