### ISSUE TITLE
Suggestion for console client and MPD integration? 

### ISSUE THREAD

**Issue by garret** [navidrome/navidrome#699]
I have been using for some time the greatest `ncmpcpp` to control my music from a `mpd` server. I recently switched to Navidrome and I am enjoying it. However, I miss a well-developed console client to reproduce music. 

Are you aware of a console client I could use which can play music from Navidrome(/airsonic)? 

On Reddit I found a message where @deluan states that MPD integration is scheduled for some time in the future. I was surprised to not find any issues open about that. May I ask if there is already a defined roadmap/ETA for that? 

Keep up with the good work and compliments for this amazing project!

**Comment by deluan** [comment]
Thanks for trying Navidrome!

There are two terminal clients I know about that work with Navidrome: 
- https://github.com/tryffel/jellycli
- https://github.com/wildeyedskies/stmp

But they are normal clients, meaning that they play the music in the audio device attached to them. They do not control the server. For that we need to have the Jukebox mode (#364) in place, that will allow the server to play music through audio devices attached to it, and then clients can control what to play there.

Once the Jukebox mode is in place, it _may_ be simple to add support for MPD clients, but this is just an idea and I have to measure the effort/benefit of doing it, as there are a bunch of other features that, IMO, have a higher priority.

**Comment by garret** [comment]
Do you think a solution with mopidy installed next to navidrome with the subsonic and mpd plugins could work to control navidrome music with ncmpcpp?

**Comment by deluan** [comment]
Don't know, I actually never used MPD servers and clients, just read an overview of how, but never installed anything... Try and let us know :D

**Comment by deluan** [comment]
Closing it for lack of activity. Please reopen if you have any other concerns.
