### ISSUE TITLE
Starting a playlist from a specific song only adds the remainder of the playlist to the queue (Web UI)

### ISSUE THREAD

**Issue by danshilm** [navidrome/navidrome#703]
The expected behaviour was that when I start playing a playlist from a specific song, the whole playlist is added to the queue and the specific song starts playing. That way, I can still go the previous song in the playlist since it is all in the queue. 

However, in the Web UI, only the songs after the specific song are added to the queue. 
This is not the case in Music Stash nor DSub.

**Comment by deluan** [comment]
Sorry for the delay. Yes this was necessary when I first implemented the play queue management, as the upstream react-player project didn't have better ways to manipulate the queue. It changed in recent versions, so I may take another look and see if this can be improved.

**Comment by danshilm** [comment]
Sure, you want me to keep this open until you see if its possible now?

**Comment by deluan** [comment]
Yes, let's keep this open. I'll try to take a look at this this week

**Comment by deluan** [comment]
This should be fixed in ace5c905. Please test the latest build and let me know.

**Comment by danshilm** [comment]
Works as desired in https://github.com/navidrome/navidrome/commit/ace5c905eb81a80bc54f9f7d8889c7815a4c9af7. Thanks a lot 👍🏼 This is one of those things that I do a lot that works the same way in all the other players I used which breaks Jakob's Law like you mentioned.

**Comment by deluan** [comment]
Thanks @YashJipkate for your previous PR #976, you were right: The "Play Next" behaviour is already broken in master, it is a bug in the React Player. I'll open an issue with that project and will try to fix it this weekend.

**Comment by YashJipkate** [comment]
There is an issue already opened by me, you might want to take a look at https://github.com/lijinke666/react-music-player/issues/349.
