### ISSUE TITLE
Database: log all plays instead of just updating play count and last played

### ISSUE THREAD

**Issue by certuna** [navidrome/navidrome#714]
Currently, the `annotation` table has for each track the `rating`, `starred`, `play_count` and `play_date`.
It would be useful if Navidrome would not just update `play_count` and `play_date` (=last played), but log all plays. That way, future features like "most played last month" or historic graphs can be implemented.

I'd suggest a new table `play_log` with columns `user_id`, `item_id`, `play_date`, `play_length`, `skipped`. Adding play length would also allow stats like which artist you listened to the most, not by number of songs but by time.

**Comment by metalheim** [comment]
I very much like the idea of having that statistics, but I see some downsides. 

I think play_length can't be supported through the subsonic API as many clients download the whole song once you start playing.
Also with multiple users listening to a lot of songs, performance could get problematic, as there could be possible millions of plays in that play_log table. 

I'm more looking forward to last.fm (or alternative services) scrobbling functionality, leaving the statistics part to an external service.

**Comment by certuna** [comment]
You're right with play_length, the Subsonic API doesn't really have the ability to sync that info back to the server.

Last.fm is a very useful service of course, but I guess part of the appeal of self-hosting is that you also retain the play stats locally?

SQLite is no OracleDB of course, but a simple 5-column table with 10 million records probably shouldn't pose to many issues? You might need to add some intermediary tables if you encounter slow SQL queries, but in principle play counts are pretty light (ie, you're only appending data at the end, no big write operations anywhere else in the table).

**Comment by deluan** [comment]
I thought about that in the past, and I decided to integrate with services that better handle this type of things, like Last.FM, Libre.FM and ListenBrainz. For the self-hosted folks, someone suggested [Maloja](https://www.reddit.com/r/navidrome/comments/jy2gr0/feature_inquiry_most_playedstats/). As @metalheim noted, storing this log in SQlite3 may not cause performance (and disk space?) issues. 

Maybe a different storage system could help, one option is to use a time-series DB, but I still think this should be handled by an external tool.

Dev notes: When implementing scrobbling, it should allow for new services to be added. There should be a Scrobbler interface, that could be implemented for new services.

**Comment by deluan** [comment]
This can be currently implemented with Maloja and the ListenBrainz API with a custom URL (#1774). CLosing this for now, as it is currently out of scope to provide this statistics in Navidrome itself. Let me know if you have any concerns.
