### ISSUE TITLE
Respect files' last modified timestamp for recently added media

### ISSUE THREAD

**Issue by pacija** [navidrome/navidrome#717]
Hi,

would it be possible for navidrome to respect media files' "last modified" timestamp for "recently added" media?

At the moment, navidrome considers date of import, making my whole library "recently added" when first imported. Airsonic (and if I'm not mistaken also Jellyfin) consider last modified attribute, which correctly sorts music by file modification date, not by import to application date. This enables having multiple media servers having consistent view of release addition timeline.

Thank you in advance,

**Comment by deluan** [comment]
That makes sense. Actually I thought it was already like this :P

It will be fixed in the next release. Thanks!

**Comment by deluan** [comment]
I just realized why it was not implemented like this before: If you add an album to your library, but it has modified times in the past, it may not appear at the top of the Recent Added list. Not sure if using modified times is a good approach here... Thoughts?

**Comment by pacija** [comment]
Well, my music library grows over last two decades, a dozen or so releases per month. Over the time I used bunch of media servers, and at the moment I am using multiple media servers simultaneously. It is very important to me that media servers respect date of adding media to the library (file system), not date of adding media to that particular media server.

If I want to "refresh" some album so it appears from certain date, it is easy to modify its timestamp and re-scan the library.

**Comment by deluan** [comment]
I have to do more testings with this, and may introduce a config option. I think if we use the modification time, if you change tags of a file it will be considered a new file and will go to the beginning of the "Recently Added", which is undesirable...

The current behaviour is actually what iTunes (and now macOS' Music) uses: If you re-import your library, the "date added" attribute is set to the time of scanning.

**Comment by jvoisin** [comment]
> The current behaviour is actually what iTunes (and now macOS' Music) uses: If you re-import your library, the "date added" attribute is set to the time of scanning.

I prefer this behaviour.

**Comment by danshilm** [comment]
> 
> 
> > The current behaviour is actually what iTunes (and now macOS' Music) uses: If you re-import your library, the "date added" attribute is set to the time of scanning.
> 
> I prefer this behaviour.

+1

**Comment by FabioC4** [comment]
> I have to do more testings with this, and may introduce a config option.

Yes Deluan! A config option would be nice, on older Navidrome builds if i scanned files with old date attributes (Ex. 2010) they would appear as "Recently Added" but buried down the list, maintaining the new files on top. In my case this is the desired behavior. 

I reinstalled my build with the newer release, and when scanning for first time the same files it shows on top random old songs and if i add later new music it then shows on top that new songs.

Thanks!

**Comment by pacija** [comment]
I think, from users' point of view, it would be great if users could decide wheather they want "recently added by import date" or "recently added by last modified date", so I agree with @FabioC4 that config option would be nice.

In a way, for tech savvier people, Navidrome having "recently added by last modified date" gives ability people who want "recently added by import date" to do it - just touch all files in collection with today's date before importing.

As a side note, I never thought I would ever hear anyone say "let's replicate iTunes behaviour, that's the one we like and use", yet here we are. I guess I'm getting old 👴

**Comment by pacija** [comment]
> if you change tags of a file it will be considered a new file

I am not 100% sure but I think I tested this some time ago and noticed that just tag change in easytag, without other modifications (eg. renaming file) preserves original filestamp.

**Comment by certuna** [comment]
Personally, I prefer file creation date :)

If I downloaded a file or ripped a CD in 2017 (creation date), fixed some tags in 2019 (modified date), and added it to the library in 2021, then I'd like the library to show that I added this to my music library in 2017, not 2019.

**Comment by pacija** [comment]
Creation date is also ok. It can also be controlled with `touch`, should one want to put release in particular period of addition to the library.

You're probably right about iTunes, last time I tried to use it was more than 10 years ago, perhaps it was improved in the meantime. Nowadays I mostly use clementine on FreeBSD, foobar2000 on Windows, and dsub on Android.

I am so vocal about respecting file timestamps for import because it saved me a few months ago. I have airsonic instance which has been growing for last 4 years. I mostly memorize releases by period when I first got them and added them to the library. It is also fun to see what I was listening to 3 years ago, or last summer etc. When this instance crashed irrepairably (no application and database backup, only media files were on another NAS), I thought I lost my release addition timeline. I was so happy to see that, after clean install and media import, all the releases was in same "added to library" order, bacause airsonic respected file timestamps.

**Comment by FabioC4** [comment]
> I reinstalled my build with the newer release, and when scanning for first time the same files it shows on top random old songs and if i add later new music it then shows on top that new songs.

In case anyone is wondering or wants to see how it would look, I just use the following URL to sort the items by new: "/#/song?order=DESC&sort=updated_at"

For my mobile APP, i currently just add all my latest songs to a playlist and then import to Navidrome.

**Comment by deluan** [comment]
Hey @pacija sorry for the long delay in getting this done. I'm introducing a new option in the next version that will allow you to use `mtime` for sorting by Recently Added. The config option is `RecentlyAddedByModTime` and it is a boolean (default false).

You should not need to reimport to use it. It will be part of the next release.

@certuna: Unfortunately there's no reliable way to obtain the creation time in Linux, and most of its filesystems doesn't even implement it. So I decided to leave this option out.

**Comment by pacija** [comment]
Much appreciated, works as intended!
