### ISSUE TITLE
Taglib fails to extract metadata from rclone mounts

### ISSUE THREAD

**Issue by vestingz** [navidrome/navidrome#746]
I am not exactly sure whether this is an issue with navidrome, but I am posting it nevertheless. Please close at your own discretion.

Recently I moved to a remote server for navidrome, which mounts my locally stored music library into navidromes ./music folder via rclone/sftp. According to the logs, navidrome was able to read and scan the files just fine, but apparently was not able to extract any tags. All files just appeared on the frontend with an arbitrary cover picture and under [Undefined Title] and [Undefined Artist]. Interestingly enough, my old play queue still played all the files just fine.
Removing navidrome.db did not help, but since I changed the metadata extractor from taglib to ffmpeg, the all goes well again - just the extraction process seems to be slower by some magnitude.

**Comment by deluan** [comment]
Rclone mounts are usually a lot slower than other protocols (SMB, NFS), but should work, will take a look and confirm it is not an issue with taglib+rclone before closing this. Thanks for the report

**Comment by deluan** [comment]
Hey @vestingz, can you please check if this still occurs in the latest version (0.45.1)?

**Comment by vestingz** [comment]
> Hey @vestingz, can you please check if this still occurs in the latest version (0.45.1)?

Hi @deluan, thanks for looking into this!
Sorry, I am running a different setup now, which doesn't involve remote 
mounts anymore :( Maybe I can find some time soon to test it. I will 
update this thread accordingly, then.

**Comment by vestingz** [comment]
> That would be great, thanks! Please let me know if get to test it or
> if you won't have time to do it. In that case I'll close this issue.

Within the next few weeks, it seems like I won't delve into it - just 
started a new job. I think it is safe to close it for now. If I can 
provide some results, we can still reopen. Thanks! :)

**Comment by earnestma** [comment]
Hi @deluan, I can confirm this is still happening on v0.47.5. I'm using an rclone mount with an s3 remote. Is there any information I could give you to help?

**Comment by jackoliver** [comment]
Came here with this exact issue, switching to `ffmpeg` from `taglib` solved it for me.
