### ISSUE TITLE
Ability to share a subset of the library

### ISSUE THREAD

**Issue by jvoisin** [navidrome/navidrome#748]
It would be nice to be able to share an arbitrary subset (tracks, artists, albums, …) of my library with anonymous users.

**Comment by rohitgeddam** [comment]
I would like to work on this!

**Comment by Devesh21700Kumar** [comment]
i would like to implement this feature

**Comment by syedsafi30** [comment]
This project seems interesting, I would be happy to work on this.

**Comment by Tejas21-design** [comment]
This really seems to be intresting,  i would love to work on this

**Comment by Tejas21-design** [comment]
can somebody help me to how to contribute to this project

**Comment by deluan** [comment]
@Tejas21-design You can start by [setting up your dev environment](https://www.navidrome.org/docs/developers/dev-environment/) and joining our [Discord](https://discord.gg/2qMuMyHfSV). There's a #dev and a #gsoc channel there.

**Comment by Harshkaushik14** [comment]
Willing to work on this project. & I want to fix some issues which i faced too.

**Comment by rohitgeddam** [comment]
> It would be nice to be able to share an arbitrary subset (tracks, artists, albums, …) of my library with anonymous users.

***Just to be clear " Anonymous users are the ones who are not added as a user on our server? "*** 


### My Thoughts
- I would like to implement a feature to generate a sharable link ( just like in google docs ) that can be used to share albums with other users ( on a different server )
  - let me know if it should be done in a different way

###  Few questions

- Should the anonymous user be logged in ( on a different server ) to view our shared albums?
   - Does an anonymous user here means the user can just click on the sharable link and he can play the songs without logging in?
- Do i need to create a different page ( one that dosen't require login ) just for playing songs from a sharable link?

***Please share your thoughts on this***

**Comment by SobhanBera** [comment]
**I too want to join the party. And contribute to this project. And learn something.**

### According to Me:
- I think every song, album, artist data, has its own unique id to fetch data from the database
- If not then I will create some id for songs, artists, album. (something like this - https://some_api_end_point/songs/[id] this id would be related to the song in some way. (only if the song doesn't have any id initially)
- when the user goes to the particular web URL. we could fetch the id from the request and fetch the song, artist's data, album's data for that id.
- via response, we could show the details of the data.

**Require advice**
Thanks

**Comment by deluan** [comment]
This is a big task, as it will require changes to both backend and frontend. We will have to implement all "Sharing" [Subsonic endpoints](http://subsonic.org/pages/api.jsp#getShares), and we will have to implement a new anonymous webpage with the new player. Also a new "CRUD" for shared media.

For those thinking about tackling this, please install and take a look on how this is done in Airsonic. That is exactly what we want to achieve. It offers the sharing option in the Web UI, and also in the Subsonic API. You can test the endpoints with [DSub](https://github.com/daneren2005/Subsonic/releases)

**Comment by rohitgeddam** [comment]
@deluan this looks interesting and challenging, I am on it.

**Comment by SobhanBera** [comment]
> This is a big task, as it will require changes to both backend and frontend. We will have to implement all "Sharing" [Subsonic endpoints](http://subsonic.org/pages/api.jsp#getShares), and we will have to implement a new anonymous webpage with the new player. Also a new "CRUD" for shared media.
> 
> For those thinking about tackling this, please install Airsonic and take a look at how this is done there. That is exactly what we want to achieve. It offers the sharing options in the Web UI, and also in the Subsonic API. You can test the endpoints with [DSub](https://github.com/daneren2005/Subsonic/releases)

### Me too

**Comment by anarcat** [comment]
for the record, i have tried again and again to use this feature in AirSonic and it has always failed me. the most anyone got from my share links was an authentication screen. :p i have high hopes that this will allow *completely anonymous* users to access my instance... not everyone has access to a navidrome server! :)

**Comment by YashJipkate** [comment]
I'm trying to implement this in my free time now. But with the new job and GSoC, it is hard to squeeze in. I'll try to get this done ASAP.

**Comment by morbificagent** [comment]
Any news about this?

**Comment by deluan** [comment]
If @YashJipkate can't work on it, I'll probably get to it after finishing Smart Playlists (#1417) and Multiple Artists (#238)

**Comment by morbificagent** [comment]
That would be great!
I know... much to do... so many thanks for this

**Comment by bricej13** [comment]
I've built an initial stripped-down fronteend for this: [https://github.com/bricej13/navidrome-embed](https://github.com/bricej13/navidrome-embed)

It currently works by passing in subsonic credentials as query params for testing, but once the share backend is setup it should be relatively trivial to switch to the new api.

**Comment by AlmightyFrog** [comment]
As I didn't get it clearly from reading this issue: Will it be possible also for normal users in the system to restrict which folders are available?

A possible use-case would be to add a accound for kids but don't put there there access to more explicit/loud music.

**Comment by metalheim** [comment]
> As I didn't get it clearly from reading this issue: Will it be possible also for normal users in the system to restrict which folders are available?
> 
> A possible use-case would be to add a accound for kids but don't put there there access to more explicit/loud music.

I think this feature would rather bei used to share 1 album or 1 playlist at a time with non-users (as in no account).

What you're looking for is probably better solved by #192 and/or #1357

**Comment by JVT038** [comment]
Any updates? I'd really appreciate this feature!

**Comment by max-tet** [comment]
This feature would be so useful for the integration of Navidrome with this product I'm trying to get started: [Portal](https://getportal.org/).

Can I just request that the sharing URL which is used for anonymous playback has a different prefix from the rest of the app? Right now, all of the Navidrome UI is at `/app/`. So maybe anonymous listening could be at `/share/` or something like that? I hope this introduces no additional effort.

The reason is that this would make it very straightforward to setup access control on Portal as described [here](https://docs.getportal.org/routing_and_ac/#access-control).

**Comment by anarcat** [comment]
Nice to see this is implement, really cool!

Is there a way for users to download the actual files from the share endpoint? I have given the feature a shot and I can't seem to find a way to do that...

**Comment by deluan** [comment]
> Is there a way for users to download the actual files from the share endpoint? I have given the feature a shot and I can't seem to find a way to do that...


Not at the moment, but please open a new issue and I can ry to implement it for next release.

**Comment by anarcat** [comment]
you're awesome, done in #2125 thanks!
