### ISSUE TITLE
Random sort changes each time you switch pages

### ISSUE THREAD

**Issue by markasoftware** [navidrome/navidrome#749]
In random sort mode, clicking the next page button changes the random ordering, so some of the same albums show up. Maybe a random seed should be stored in the url?

**Comment by SteveDinn** [comment]
I posted about this on the discord several weeks back. Should have logged a bug :)

I don't think there's any point in having the random section paginated because it doesn't make any sense. Any "next" or "previous" page is just another first page of a random query.

**Comment by deluan** [comment]
Thanks for opening this. There's no simple (and performant) way to use a seed in a random sorted SQLite3 query. I did some research, there are some hacks, but they are not performant. Will keep this open if someone has any ideas.

**Comment by AeronCyther** [comment]
I think I have a potential solution for this.
