### ISSUE TITLE
[Feature request] Playlist update after import

### ISSUE THREAD

**Issue by anatosun** [navidrome/navidrome#753]
First, thank you for the great work. The playlist import feature is especially the one that made me migrate to this project.

Now, after importing a playlist with an m3u file, any change added to the playlist in Navidrome is not added to the original m3u. Of course, we have the ability to download the updated m3u file directly from the UI. Yet, having the original m3u file updated automatically could be useful when working with other softwares such as Rekordbox or Traktor to have them in turn update the playlists.

**Comment by deluan** [comment]
Thanks for trying Navidrome!

Originally I planned to implement a "two way sync", but there are some complications in implementing it and I decided not to do it. Take a look here: https://github.com/deluan/navidrome/issues/105#issuecomment-626376542

Maybe change the auto-sync flag from a boolean (auto import or not) to a combo: Off, Auto-import, Auto-Export). The sync would be unidirectional, but the user would be able to select which direction to sync. What do you think?

**Comment by fwicht** [comment]
Oh yes now I see the difficulties around this feature implementation...

Changing the “direction” of the sync can be a solution indeed but we would need that option globally so to make a smooth and easy export feature, what do you think?

In my opinion, it would also be good to have the option to export it either in relative or absolute path.

**Comment by fwicht** [comment]
Hey, @deluan, no worries!

> What do you mean by "global"? One flag to control the direction of all playlists sync in Navidrome? That would not be a very flexible option....
- What I meant by 'globally' was to give the user the possibility of exporting every playlists from his library with a single and global option.
> The problem is: Relative to what? To the MusicFolder path?
- As for 'relative', I probably meant relative to the m3u8 files themselves. This way the playlists could be exportable to any software on any system. For example, say you want to export your playlists to a DJ software like Rekordbox on your PC. Well, you could successfully download your playlists and import them into the software. If the path was the original one from the server (absolute), it would most likely **not** be recognised from the software.

I hope this clarify what I meant in the previous comment.

**Comment by Crazy-Ginger** [comment]
I am still be interested in this feature. 
Manually syncing playlists is still really cumbersome and automating it would be a nice feature

My use case (if that's important to anyone):
When I have internet access on my devices I stream via the navidrome UI. However, when my internet goes down or I'm travelling with my laptop, I use a local player (Audacious, Foobar2000). It would be nice if these players used the same playlists I've created in Navidrome but I have to keep downloading the playlists from the web UI and manually altering file paths in VSCode. 

Being able to sync a `Playlists` folder across all my devices would be very welcome

**Comment by Jucgshu** [comment]
I too am interested in this feature. I tried with the API but I don't get consistent results around paths.

Thanks a lot for the work on Navidrome.
