### ISSUE TITLE
Add Ability to Upload

### ISSUE THREAD

**Issue by TheFlatworm** [navidrome/navidrome#770]
Give users the ability to upload to a special folder and have the admin get an email of the upload.

**Comment by deluan** [comment]
Hey @TheFlatworm , thanks for the suggestion, but this is something that has been discussed [before](https://github.com/navidrome/navidrome/issues/311) and the verdict is that (IMO) it is not a good fit for Navidrome itself. You can always use a software built specifically for this purpose, like FileBrowser, or even a simple FTP dropbox. If you use Docker, here's an example: https://github.com/geekedtv/Docker-Music-Stack

What Navidrome can do is have this `upload` folder as a separated library, so t would auto-scan and make available any new files. This will be possible when multiple libraries is implemented (#192)
