### ISSUE TITLE
[feature request] add playlists to default view option

### ISSUE THREAD

**Issue by ForgetfulMagnet** [navidrome/navidrome#771]
When I open Navidrome, I always click the playlists button first. It would save me a lot of clicks if the playlists were open by default. Adding the playlist view as an option to the default view setting would achieve that.

**Comment by deluan** [comment]
Playlists will (soon?) move to the left menu bar, similar to other music players (Spotify, iTunes, etc..)
<img width="302" alt="Screen Shot 2021-02-09 at 9 37 23 AM" src="https://user-images.githubusercontent.com/331353/107379096-98813d00-6aba-11eb-8803-9c1a2161b615.png">

**Comment by doggogoesbork** [comment]
random question to the above, could we add songs to playlists by just dragging them onto them? Nextcloud's music plugin works this way and makes it really easy to add songs

**Comment by deluan** [comment]
I'd love to enable that. When I get to implement this, I'll take a look on how to enable drag'n'drop for it

**Comment by aniketbiswas21** [comment]
@deluan I'd love to work on this. Can you help me get started?

**Comment by KashyapPavra** [comment]
@deluan If the feature is still to be added, I’d love to work on it.

**Comment by deluan** [comment]
For those wanting to tackle this, you'll need a bit of understanding on how to [customize React-Admin](https://marmelab.com/react-admin/Theming.html#using-a-custom-menu). Changes will most probably be applied to Navidrome's [Sidebar Menu](https://github.com/navidrome/navidrome/blob/847531391dab0dd4f5ac4951767d4698f920dfdb/ui/src/layout/Menu.js).

**Comment by cynequil** [comment]
Is this option related to only macOS version of navidrome? The dev or demo edition doesn't seem to have in place (in the side menu) on click dropdown showing all the available playlists.
![Screenshot_20210316_004338](https://user-images.githubusercontent.com/19496170/111210173-f097eb80-85f2-11eb-814f-cac8b5d20af7.png)

**Comment by jvoisin** [comment]
As @deluan said on the 9th of February:

> Playlists will (soon?) move to the left menu bar, similar to other music players (Spotify, iTunes, etc..)

This is not yet implemented.

**Comment by cynequil** [comment]
@jvoisin I get it. That was a different player all together. I am going to look at it then.

**Comment by Dnouv** [comment]
@jvoisin, the playlist in the left menu bar would be like in the screenshot attached below, or does it need to be different? Could you please review it and provide feedback.
<img width="277" alt="navid_play" src="https://user-images.githubusercontent.com/61188295/111380307-2bb91e00-86ca-11eb-84ea-e129af9373e8.png">

Thank you!

**Comment by Dnouv** [comment]
@deluan, could you please review the above-mentioned playlist on the left comment.

**Comment by deluan** [comment]
@Dnouv, yes, that's the idea. Keep in mind that, for a better UX, the left menu bar should scroll independently from the main view, similar to Spotify, Apple Music, and others:
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/331353/111731801-9abd8080-884a-11eb-8c72-97d636979eab.gif)

But in mobile view, it should stay as it is today.

**Comment by aldrinjenson** [comment]
@Dnouv , if it's alright with you, may I try giving a shot at this please.?

**Comment by Dnouv** [comment]
Sure @aldrinjenson, please go ahead.

**Comment by deluan** [comment]
Reopening it as is is merged but not complete. It is behind a feature flag, so if you want to experiment with it, set `DevSidebarPlaylists=true` in your config options

**Comment by deluan** [comment]
Drag and drop implemented in 6c3e45de41ca0d996a0efb6a588ddd6c91b35275. Will be part of next release (0.46.0)
