### ISSUE TITLE
Navidrome 0.40 - unhealthy docker container on armv7

### ISSUE THREAD

**Issue by 0xERR0R** [navidrome/navidrome#773]
Navidrome 0.40 starts as "unhealthy" docker container. I run navidrome on Rasbperry pi 3 behind traefik and unhealthy state makes the container unreachable. 
Message from docker inspect `Connecting to localhost:4533 (127.0.0.1:4533)\nwriting to stdout\nwget: clock_gettime(MONOTONIC) failed\n`
The problem is not a navidrome itself, it is caused by update to alpine 3.13 (which was released last month). See https://github.com/alpinelinux/docker-alpine/issues/135

It looks like it is only arm7 issue.

As workaround, I suggest to bump alpine version in the docker file to 3.12

Workaround for affected users: add following to docker-compose.yml
```yml
healthcheck:
  disable: true
```

**Comment by deluan** [comment]
Thanks for letting me know!

Unfortunately I don't think locking the version to 3.12 and not getting future upgrades is a solution.... based on the linked issue, the real solution is to update the server: https://github.com/alpinelinux/docker-alpine/issues/135#issuecomment-762397429

For those having this issue, please upgrade your system as per linked instructions or disable the `healthcheck` as suggested above

Closing this now, but feel free to reopen if you have other concerns

**Comment by ilPeo** [comment]
I confirm, updating libseccomp fixed the problem.
For anyone like me running Raspbian Buster on Raspberry pi I got libseccomp2 from buster-backports.
