### ISSUE TITLE
"Something went wrong" when viewing Library > Artists

### ISSUE THREAD

**Issue by CTParkinson** [navidrome/navidrome#776]
Hi!

Just came over from Airsonic, intending to move away from it fully.
Standard set up with Docker, media folder scanned, and now when I view artists I get the following error in Console:

```
TypeError: Cannot read property 'id' of undefined
    at pa (ContextMenus.js:200)
    at Ya (react-dom.production.min.js:153)
    at vs (react-dom.production.min.js:261)
    at cl (react-dom.production.min.js:246)
    at sl (react-dom.production.min.js:246)
    at Zs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Uo (react-dom.production.min.js:122)
    at $o (react-dom.production.min.js:123)
```

I can see that the issue lies on this line
`filter: { album_artist_id: props.record.id },`
in `ArtistContextMenu`
Though I'm not sure what `props.records` is intended to be but it looks like at static > js > artist > ArtistList.js:72 `record` is not supplied to `ArtistContextMenu`, which leads me to believe this isn't an issue with my media?

I'm not familiar with React, so I don't really know what's going on there and it totally could be my media, but that's where my investigation took me.

**Comment by CTParkinson** [comment]
So... immediately after posting I decided I should just force a refresh, ctrl + F5, to see what happens and the artists now load.
Which I can't make sense of if it were in the react files, as they wouldn't change whether they were cached or not...
However it's loading now.

But I'll leave this open just in case there is something you can gleam from this, if there potentially is an issue.

**Comment by deluan** [comment]
Thanks for the report! 

Yes, the stacktrace is helpful, will put a fix to avoid breaking like that. And not, it is not your media, this is caused by some weird internal state from React Admin, where it tries to render things that are not there yet.
