### ISSUE TITLE
Scanning of DSF and DFF and playing of FLAC files

### ISSUE THREAD

**Issue by mandickay** [navidrome/navidrome#778]
I installed Navidrome 0.40.0-SNAPSHOT (501af141) via docker on my Armbian OS. The app is able to scan my FLAC files  but not my DSD collections, which are mostly DSF and a few DFF files. There is nowhere in the app where I can configure it to be able to scan DSF or DFF files.

In addition, it seems that Navidrome can only play my files as MP3. My FLAC files have to be transcoded to mp3. Again, there is nowhere in the app where I could be able to edit it so as to make it FLAC playable.

**Comment by deluan** [comment]
Hey, thanks for trying Navidrome.

`.DSF` files are only scannable using the `ffmpeg` extractor. You can enable it by setting the `Scanner.Extractor = "ffmpeg"` in your config file or setting the `ND_SCANNER_EXTRACTOR=ffmeg` env var in your docker config.

`.DFF`, currently Navidrome ignores this extension. I don't have of such files, but you can send me one and I can take a look.

In terms of streaming, the server will glad serve any file extension the client (or UI) asks for. You have to be sure the client or UI have the capability to play them. I tested FLAC playback in DSub (Android), and in the UI when running in Chrome and Firefox.

If your client/browser does not support FLAC playback, then you need to configure transcoding. This is a client limitation, and in the case of Navidrome's WebUI, it is a limitation in the browser.

Hope this answer your questions

**Comment by mandickay** [comment]
**time="2021-02-14T06:00:54Z" level=info msg="Finished processing changed folder" dir="/music/The_Alan_Parsons_Project-Eye_In_The_Sky-(Arista)-DSF128-LP-1982" elapsed=4.13s purged=0 updated=10
time="2021-02-14T06:00:55Z" level=info msg="Finished processing changed folder" dir="/music/The_Alan_Parsons_Project-The_Turn_Of_A_Friendly_Card-(Arista)-DSF128-LP-1980" elapsed=1.19s purged=0 updated=10**

I finally managed to have the Navidrome to scan my DSF files! I am yelling at it now!

Now it comes to the issue of adding new transcoding commands. I want to create a transcode for opus audio 192k. I read some ffmpeg examples online but couldn't make them work on Navidrome. Navidrome often replies with "Internal Server Error". I'd be grateful if I could have your advice on this.

**Comment by deluan** [comment]
You shouldn't need to create a new transcoding. You just have to edit the Player's properties, select the "Opus" transcoding and set the Max Bit Rate you want (192k in your case):
<img width="689" alt="Screen Shot 2021-02-15 at 1 28 55 PM" src="https://user-images.githubusercontent.com/331353/107982332-d3d7ac00-6f91-11eb-9775-09a579ad3f8a.png">

**Comment by deluan** [comment]
Hey @mandickay, were you able to figure this out? Can I close this issue?

**Comment by mandickay** [comment]
Yes, I got it sorted myself. Please close this comment.
Many thanks.
