### ISSUE TITLE
Album Art Does Not Update on Quick/Full Scans

### ISSUE THREAD

**Issue by drinn** [navidrome/navidrome#792]
I'm having an issue with my Navidrome installation (0.40.0) where if the album art for a given album gets changed, I seemingly am unable to get that change reflected in my browser. I've tried the usual affairs of cleaning out the cache/cookes, etc. but the only thing that reliable seems to to work is to wipe out my navidrome database and start over.

This isn't a huge deal, but is a minor inconvenience when trying to ensure everything stayed synced and is properly represented.

I'm running my instance as a docker container. I tried messing around with the ImageCacheSize after reading some other reports of album art issues, but nothing seems to fix the issue reliable (other than starting the DB from scratch). How can I help you guys troubleshoot this issue?

**Comment by metalheim** [comment]
Are your files marked as "modified on _<Date>_"? Some Tagging software does not mark that it has modified the files.
Navidrome therefore thinks the file hasnt been changed and skips looking for updates.

If that is the issue, you can force the modification date to _<now>_ with the console command (on linux)
`touch file.mp3`

**Comment by drinn** [comment]
I played around with things this morning and have not gotten things to fail in the way that I was seeing earlier.

Thank you for mentioning the filename modification date as the item that navidrome looks at for changes. I had previously been trying to touch the parent directory of the files instead of the individual files themselves.

I'll go ahead and close out this issue and if I continue to have a problem, I'll reopen another one.
