### ISSUE TITLE
[Feature Request] Transcode FLAC Files When Downsample Requested

### ISSUE THREAD

**Issue by drinn** [navidrome/navidrome#794]
As a person with limited mobile bandwidth a month, I'm wondering if it would be possible to transcode FLAC files if/when a request to downsample a song is requested? The Dsub app seems to specify a max bitrate for files over wifi vs mobile.  When I'm on wifi, I'd just assume have the full FLAC file on my phone for the best quality. But if I'm out and using my limited mobile data, I have the maximum bitrate set to try and conserve some bandwidth.

I tested this out today with a 1000k+ bitrate FLAC file and despite my maximum mobile bitrate being set to 320k, it downloaded the entire FLAC file unmodified to my phone.

I'd rather not set transcoding for the entire Dsub player to mp3 files since, as stated above, FLAC is fine if downloaded on a local unmetered connection. But it would be nice to have a way that if a file exceeds a given bitrate, to have it transcode and downsample to the set rate to conserve that metered bandwidth.

Hope that makes sense.

**Comment by drinn** [comment]
... or would it be possible to transcode FLAC files to a chosen lossy format in general?

I like the idea of using opus files for better quality vs. mp3 given the same bitrate. But most of my library is already in mp3 format and converting from mp3 to opus will only serve to further degrade the quality of those files. Hence, having a blanket opus transcode as exists today which converts all my mp3s to opus wouldn't be ideal.

If there were a way to pass through my existing mp3s directly to the client and to transcode large FLAC files to opus, that would be nice. Rethinking the above, it might be preferable for me to actually not have any FLAC files on my phone since space is more limited and probably overkill for the headphones/speakers that I'd be using to play that media through anyway.

Sorry to change gears here compared to my original suggestion. But both were suggested as a way to save on mobile bandwidth usage with the added effect of saving storage space on the client device.

**Comment by deluan** [comment]
Hey @drinn, the current transcoding options in Navidrome are not flexible enough for this use case. I'll rewrite it at some point (soon-ish I hope). Take a look at #351

**Comment by drinn** [comment]
Thanks for the response. I actually did a complete 180 on this (and hence, closed the case) and decided to just enable opus transcoding for my Dsub player entirely. With opus being so efficient and practically transparent at 128k bitrate (from what I've tested and read), I've decided to just let my entire library be transcoded to opus before arriving to my phone. The space savings of even 320k bitrate mp3s down to 128k bitrate opus with possibly no (real world) loss of quality was pretty appealing, so I've settled on doing that.

Maybe worth a rewrite at some point in the future if you see fit. But I've had a change of heart on the usage case so closed the issue instead of keeping it open.

**Comment by deluan** [comment]
This is exactly how I use transcoding: All music sent to DSub is transcoded to 128Kbps Opus, even MP3 and other Opus files. In my tests I could not feel any difference. Could be my bad hearing, though 😝 

Even then, I will rewrite it, to give more flexibility for different use cases

**Comment by drinn** [comment]
Same here. I hadn't experimented with opus until recently and was amazed at
the difference between opus and mp3 at lower bitrates. I probably could
have settled for 96kbps and not known the difference, so 128k is more than
enough. 96kbps mp3 files sound like garbage. 😝

Transparent (to me) compression at opus 128k + the space savings it gives
on a limited storage mobile device is amazing. Thank you for all your work
with the project!
