### ISSUE TITLE
Starred item from DSub wont appear in Starred items

### ISSUE THREAD

**Issue by sintpon** [navidrome/navidrome#801]
Just as stated - i use Star control in DSub (i use android and android auto as well), so starred item appear in bookmarks page in DSub, but not in Starred in Navidrome.
Am i doing anything wrong way?

**Comment by deluan** [comment]
Currently Navidrome's UI does not have a consolidated view to show all your starred items in one place. When you go to "Albums->Starred", it only shows albums. If you want to see the starred songs (or artists), you need to go to that view, and filter by starred:

![Screen Recording 2021-03-07 at 1 23 33 PM](https://user-images.githubusercontent.com/331353/110250279-7c9d7980-7f48-11eb-82ff-53deb203af6f.gif)

Hope this answers your question

**Comment by sintpon** [comment]
thanks, would be perfect to have ability to export such filter as m3u (i used to import starred items to my main library management software).
Patiently waiting for some LastFM integration (love tracks).
