### ISSUE TITLE
Better accessbility while playing a song from an album

### ISSUE THREAD

**Issue by aniketbiswas21** [navidrome/navidrome#809]
## Problem Description

The current way of playing a single song might be a bit difficult for some users to figure out since there is no distinct play button visible.

![Screenshot from 2021-03-10 13-14-51](https://user-images.githubusercontent.com/51146347/110594611-08124700-81a3-11eb-8dfc-4e88ae674054.png)

## Possible Solution

We can show a play button on hover next to the song name(kind of like what Spotify does in its web player. I have attached a screenshot for reference.

![Screenshot from 2021-03-10 13-10-11](https://user-images.githubusercontent.com/51146347/110595143-ae5e4c80-81a3-11eb-871e-7fda7e73bdbd.png)

## References

https://open.spotify.com/

**Comment by deluan** [comment]
Thanks for the suggestion, this is would be awesome. It may require some customization to React-Admin's DataGrid. We already have some customization here: https://github.com/navidrome/navidrome/blob/2010fcf4ca75616272a4275661f7eec32a54a1ca/ui/src/common/SongDatagrid.js

**Comment by aniketbiswas21** [comment]
I'd love to work on this.

**Comment by ketangupta34** [comment]
Hey @deluan , Can I work on this??

**Comment by ashikka** [comment]
Hello @deluan, can you assign me this issue? I'd love to work on this.

**Comment by pkspyder007** [comment]
@deluan I found an implementation similar to this issue
I would like to create a similar kind of functionality and the previous work on this issue would serve as a great base for reference.

https://user-images.githubusercontent.com/19896788/114260074-42644380-99f0-11eb-9057-1946e4af524d.mp4

**Comment by aniketbiswas21** [comment]
@pkspyder007 Actually I did implement this in #819. But, in order to achieve this, there is a lot of logic to be handled (Due to the fact how ```Player.js``` is currently implemented). To simplify the process, we first would have to rewrite how ```Player.js``` works and then we can proceed with this.

@deluan Thoughts?

**Comment by vian9** [comment]
Can I work on this issue? @deluan

**Comment by deluan** [comment]
@vian9 This has been discussed in the past and it is not trivial. There was an almost complete implementation in PR #819, but in the end we decided to put this on hold as the integration with the player was too convoluted. Currently we are preparing to add Infinite Scroll, and we are also holding back any changes to the song grids because of this.

We can come back to this after the infinite scroll is released and is stable
