### ISSUE TITLE
Unicode (special) chars in Windows file paths are not parseable

### ISSUE THREAD

**Issue by deluan** [navidrome/navidrome#810]
When running Navidrome on Windows, the default Scanner.Extractor (taglib) is currently not able to read filepaths that contains any unicode chars (accents and special symbols). This is probably caused by the way we open the file to read the metadata, using a `char *` for the filepath instead of a unicode string: https://github.com/navidrome/navidrome/blob/caeff2862ae82d9a60219bc34fca06ba57635105/scanner/metadata/taglib/taglib_parser.cpp#L14

The symptom observed by this issue is that the files that have special chars in their paths are not imported by Navidrome. **This bug only affects Windows users.**

Currently the workaround is to change the metadata extractor to `ffmpeg`, by setting `Scanner.Extractor="ffmpeg"` in the [config options](https://www.navidrome.org/docs/usage/configuration-options/)

**Comment by the-pro** [comment]
Could we change the `char *` to a wide character datatype? Although I am not sure if that will work.

**Comment by deluan** [comment]
I did a quick try and it didn't seem to work, but I was in a rush, so I may have done something wrong. I added it here to give GSoC folks some small tasks to validate their coding skills :)

**Comment by parthsarthiprasad** [comment]
since it's windows only @deluan I think it might be related to https://stackoverflow.com/questions/1520986/open-file-in-taglib-with-unicode-chars-in-filename 
`IIUC, this library comes from the Linux world (where file names are expressed as char arrays), and was later ported to Windows (where file names are expressed as wchar_t arrays). The FileName ctor taking a wchar_t array is thus probably conditionally compiled on Windows (i.e., inside #ifdef _WIN32 or something similar)
`

**Comment by certuna** [comment]
Wow, an 11 year old bug, haha!

Problem is that defaulting back to ffmpeg as tag library is not sustainable towards the future where ND will use multi-valued fields (which ffmpeg [can't read](https://trac.ffmpeg.org/ticket/6949), also a 10+ year old limitation).

**Comment by dpirad007** [comment]
https://stackoverflow.com/questions/5642251/taglib-how-to-handle-utf-8-encoded-file-paths , This is the fix i found for windows. Apparently in windows it expects both char* as well as wide char.

**Comment by dpirad007** [comment]
@deluan Would Something like this work?, Im not sure how to test this though
```
#ifdef _WIN32
  TagLib::FileRef f(reinterpret_cast<const wchar_t *>(filename), true, TagLib::AudioProperties::Fast);
```

**Comment by deluan** [comment]
I don't know what would work... Have to experiment. To reproduce the issue, just rename one of the your music files and add a special char to it (ñ, †, ø, ¢, etc...). When scanning, Navidrome will not import it

**Comment by Xx-Ness-xX** [comment]
> urrently the workaround is to change the metadata extractor to `ffmpeg`, by setting `Scanner.Extractor="ffmpeg"` in the [config options](https://www.navidrome.org/docs/usage/configuration-options/)

Thanks, after making the change I was able to get Navidrome to scan my Chinese & Japanese songs
