### ISSUE TITLE
Feature req: Play m4a

### ISSUE THREAD

**Issue by anegrin** [navidrome/navidrome#813]
Can't play m4a files directly from any client (web UI or android app like DSub) - mp3 are playing

logs:

`level=info msg="Streaming file" artist=Soundtrack bitRate=0 cached=false format=raw originalBitRate=1411 originalFormat=m4a title="XXXXXXXXXXX" transcoding=false user=navidrome`

ffmpeg info of the file

```
ffmpeg -i XXXXXXXXXXX.m4a
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/aarch64-linux-gnu --incdir=/usr/include/aarch64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '01 - A Story of Boy Meets Girl.m4a':
  Metadata:
    major_brand     : M4A
    minor_version   : 512
    compatible_brands: M4A isomiso2
    title           : XXXXXXXXXXX
    artist          : Soundtrack
    album           : XXXXXXXXXXX
    comment         : fre:ac - free audio converter <https://www.freac.org/>
    genre           : Rock
    date            : 2009
    track           : 1/19
    encoder         : fre:ac v1.1.4
    media_type      : 1
  Duration: 00:01:35.48, start: 0.000000, bitrate: 693 kb/s
    Stream #0:0(und): Audio: alac (alac / 0x63616C61), 44100 Hz, stereo, s16p, 692 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
```

file info

```
XXXXXXXXXXX.m4a: ISO Media, Apple iTunes ALAC/AAC-LC (.M4A) Audio
```

navidrome version is 0.40; i've tryed cleaning cache folder and also database files

web UI is not playing at all neither is the android App but i noticed that:

- Android app (DSub) is locally caching the file
- The cached file size is correct (matching the server)
- The cached file is "mp3" but the type is indeed "m4a" and can be played if renamed

this is the response header from the browser

```
HTTP/1.1 206 Partial Content
Accept-Ranges: bytes
Content-Length: 8273308
Content-Range: bytes 0-8273307/8273308
Content-Type: audio/mp4
Feature-Policy: autoplay 'none'; camera: 'none'; display-capture 'none'; microphone: 'none'; usb: 'none'
Last-Modified: Fri, 05 Mar 2021 12:38:47 GMT
Referrer-Policy: same-origin
Set-Cookie: nd-player-6e61766964726f6d65=bdf3df2f-017c-4cab-a359-b9216f610b81; Path=/; Max-Age=31536000; HttpOnly
Vary: Origin
X-Content-Duration: 95
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
Date: Thu, 11 Mar 2021 09:56:00 GMT
```

to make it work i had to setup transcoding for such clients to be "mp3" or "opus" - it would BE great to stream the file "as is"

if not possible or this does not depend on navidrome i'm sorry and please close :)

**Comment by deluan** [comment]
Thanks for using Navidrome. ALAC encoding is not supported by most players. I don't know any Android player that supports it, and I'm pretty sure it is not supported by any web browser as well. 

If you want to avoid transcoding your files to a lossy format, your best bet is to convert them to FLAC, which is well supported by major browsers and all Android clients. You can also transcode them to FLAC on the fly, but due to the way transcoding currently works in Navidrome, it would transcode *all* your files to FLAC, even mp3. This may not be a big issue for you though, if you don't mind about the extra space/bandwidth required.

Let me know if this answers your question

**Comment by anegrin** [comment]
thanx! very detailed explanation. i tested what you suggest and yes not browser neither android can play m4a if ALAC is the encoding. sorry for the noise
