### ISSUE TITLE
Make the commit clickable in the `about` dialog

### ISSUE THREAD

**Issue by jvoisin** [navidrome/navidrome#814]
It would be nice to be able to click on the commit hash to be able to see the actual commit on github

**Comment by deluan** [comment]
Not sure about this one. I don't see the value of this for a end user....

**Comment by Himanshunitrr** [comment]
Can you please elaborate the issue?

**Comment by rochakjain361** [comment]
I would love to work on this issue. @deluan @jvoisin can you please assign me to this issue?

**Comment by deluan** [comment]
Thanks @rochakjain361  and @Himanshunitrr , but we decided not to implement this. Closing now.
