### ISSUE TITLE
Make the version number in the about dialog clickable

### ISSUE THREAD

**Issue by jvoisin** [navidrome/navidrome#815]
It would be nice to be able to click on the version number in the about dialog to land on the corresponding changelog, like https://github.com/navidrome/navidrome/releases/tag/v0.40.0 for the versions 0.40.0

**Comment by parthsarthiprasad** [comment]
@jvoisin can you assign me the task, I believe a simple href will do the task?

**Comment by rochakjain361** [comment]
Sorry to interrupt @parthsarthiprasad, but just before you asked to assign the issue I've already committed on my forked repo and was about to make the pull request. Being a simple href fix I thought to get it done asap. Hope it's fine.

**Comment by parthsarthiprasad** [comment]
no worries, I just reviewed it, seems fine, it seems your PR failed some tests, try to fix it for now.

**Comment by deluan** [comment]
Fixed in #817

**Comment by deluan** [comment]
Hey

**Comment by deluan** [comment]
Hey @rochakjain361 , just found a small issue in your PR. When the version is a SNAPSHOT, it leads to a 404 page. This happens when using a development docker build. 

Maybe a solution for this is, in case of a snapshot, change the URL to something like https://github.com/navidrome/navidrome/compare/v0.40.0...5f7c7393 , where the hash is the gitCommitID in the version. This would all commits since the released version.

**Comment by rochakjain361** [comment]
Hey @deluan, can you share the string that is being saved as the version in the config.js file while using a development docker build. I've understood the solution to this problem but then the dialog box is using the version string from the config file which in the development server is simply 'dev', so if I can get the string being used there, I can proceed easily
https://github.com/navidrome/navidrome/blob/18fda0d9549037e7c5093e56c85e26877f21074d/ui/src/config.js#L5
https://github.com/navidrome/navidrome/blob/18fda0d9549037e7c5093e56c85e26877f21074d/server/app/serve_index.go#L31

**Comment by deluan** [comment]
Sure, the string is `0.40.0-SNAPSHOT (18fda0d9)`.

 It is not trivial to get the real config in dev mode, as the request for `index.html` is intercepted by webpacks' dev server and does not reach the backend to create a proper `index.html` with the config injected to it. For dev purposes, you can just change the version in the `config.js` file to the string I sent above.

<img width="479" alt="Screen Shot 2021-03-13 at 10 21 34 AM" src="https://user-images.githubusercontent.com/331353/111034934-ea80ef80-83e5-11eb-8487-4718fc69a3a6.png">

**Comment by Himanshunitrr** [comment]
Close this issue as its already solved.

**Comment by satyaarthchhabra** [comment]
@deluan  is this issue still open. if yes can i work on it

**Comment by deluan** [comment]
Sorry @satyaarthchhabra, but this is actually solved. Closing it now.
