### ISSUE TITLE
Create a Spotify theme

### ISSUE THREAD

**Issue by jvoisin** [navidrome/navidrome#816]
It would be nice to have a spotify theme, if only to make it easy for people migrating from it to navidrome.

- [Spotify's branding guide](https://developer.spotify.com/documentation/general/design-and-branding/)
- [Spotify's web app]( https://open.spotify.com/ )

**Comment by HassanRahim26** [comment]
Hey @jvoisin, 
I am interested in working on this issue. However, I am not very familiar with the codebase. Can you please guide me about how to proceed with solving this?

**Comment by K-Kumar-01** [comment]
> It would be nice to have a spotify theme, if only to make it easy for people migrating from it to navidrome.
> 
> * [Spotify's branding guide](https://developer.spotify.com/documentation/general/design-and-branding/)
> * [Spotify's web app](https://open.spotify.com/)

does it mean that the ui needs to be redesigned?

**Comment by jvoisin** [comment]
The documentation is [here]( https://www.navidrome.org/docs/developers/creating-themes/ ).

**Comment by deluan** [comment]
@K-Kumar-01 It is not a UI redesign, it is more related to fonts and color palette. See the Material-UI documentation to understand what is possible to customize.

**Comment by K-Kumar-01** [comment]
@deluan 
I got it and have already started working on it.
Please assign the issue to me.
I will send some screenshots or recording ASAP

**Comment by dpirad007** [comment]
@deluan Ill give this a shot as well

**Comment by K-Kumar-01** [comment]
@deluan 
I have made a PR for the issue. Let me know if there are any changes required.

**Comment by deluan** [comment]
Thanks @K-Kumar-01!
