### ISSUE TITLE
creating new component for smaller displays.

### ISSUE THREAD

**Issue by armedev** [navidrome/navidrome#823]
before:
![Screenshot from 2021-03-13 11-45-44](https://user-images.githubusercontent.com/51921579/111021379-c9be9700-83f1-11eb-875c-8746d3dbee03.png)

after:

![Screenshot from 2021-03-13 11-40-01](https://user-images.githubusercontent.com/51921579/111021244-0342d280-83f1-11eb-8568-e301007a5a6c.png)

it looks more accessible and clean.

**Comment by ketangupta34** [comment]
Hey, this is a good suggestion. @deluan I would like to work on this!!!

**Comment by deluan** [comment]
Thanks for the suggestion/PR, but I'm not sure about your solution.... Song duration is rather important, and should be easily visible in the grid. I like how DSub shows it, but I think to get something similar, we would need to rewrite/create a new `SimpleList` component:
![Screenshot_20210313-103005](https://user-images.githubusercontent.com/331353/111035222-6465a880-83e7-11eb-8abc-6689bef0f274.png)

**Comment by armedev** [comment]
if I could just shift it to right it should work I thought giving more breathing room for title.

**Comment by armedev** [comment]
also @deluan if you saw it if you keep timestamp next to stars it kinda feels it is showing stars value like the first one in your image
[4:57] if you could keep it next to author name there would be more room to the song rating :)

**Comment by armedev** [comment]
> Thanks for the suggestion/PR, but I'm not sure about your solution.... Song duration is rather important, and should be easily visible in the grid. I like how DSub shows it, but I think to get something similar, we would need to rewrite/create a new `SimpleList` component:
> ![Screenshot_20210313-103005](https://user-images.githubusercontent.com/331353/111035411-71cf6280-83e8-11eb-8e6a-2d8e8eacdb08.png)

@deluan I just showed you how it would look by only changing the code in songs section if you could allow i can try creating a new SimpleList component

**Comment by deluan** [comment]
Sure, you can try it. Try creating a `SongSimpleList` and using it here: https://github.com/navidrome/navidrome/blob/847531391dab0dd4f5ac4951767d4698f920dfdb/ui/src/song/SongList.js#L81

PS: You don't need to handle the 5-star rating as in DSub, but it would be a bonus if you can :) For that, the `song` record contains a `rating` number, 0-5. Currently the WebUI has no way to set this value, but you can set it using DSub or just fake the value

**Comment by armedev** [comment]
@deluan I will try to create a new SongSimpleList,
I assume you are saying to let the timestamp be next to the author also I will just take fake value to calculate the rating which you can provide from the song data later.

**Comment by deluan** [comment]
No, the duration (timestamp) _needs to be aligned to the right_. This is the most important part of this. If it is next to the author, it will be really difficult to read it. You don't have to bother with the 5-star rating, just the context menu and the ⭐ that are already in the SimpleList

**Comment by armedev** [comment]
ok on it.

**Comment by armedev** [comment]
@deluan @jvoisin kindly check the new PR I have created the component as @deluan said :),

**Comment by jvoisin** [comment]
How does it looks now with super-long titles?

**Comment by armedev** [comment]
awesome also a bit different from others. :D

**Comment by certuna** [comment]
Somewhat related issue: I see that in the mobile view, `/album/AlbumSongs.js` drops the "artist" field, which is fine if it's a one-artist album, but for compilation it makes the experience pretty bad. So probably a good thing to replicate this SongSimpleList to that view too?

**Comment by deluan** [comment]
Yeah, we could use the same component in that view. @armedev, can you experiment with it? Not sure how easy it is to replace the `SongDatagrid` in the `AlbumDetail` and PlaylistDetail` views...

**Comment by armedev** [comment]
Yeah, I can try to implement it. @deluan did the SongSimpleList look right for you?
if yes I can proceed with the album and playlist implementation.

**Comment by certuna** [comment]
I just posted this as a separate issue https://github.com/navidrome/navidrome/issues/846
That is just for the desktop webview, so doesn't concern the mobile view like this SimpleList does. Shouldn't overlap too much.

**Comment by armedev** [comment]
hey, @deluan I was trying to recreate the album list with the new component I created but I found out that the album list has a fixed grid, so what do you suggest?

![Screenshot from 2021-03-15 22-46-08](https://user-images.githubusercontent.com/51921579/111194099-da812f80-85e0-11eb-93c4-ccbfb4f88b5c.png)

if we want to implement it using the SongSimpleList component we should probably remove time as a column :P

**Comment by deluan** [comment]
The idea is to replace the `SongDataGrid` with your new `SongSimpleList`, but only on mobile devices (similar to what we do in `SongList`). But, as I said above:
> Not sure how easy it is to replace the `SongDatagrid` in the `AlbumDetail` and PlaylistDetail` views...

**Comment by armedev** [comment]
hey, @deluan take a look at this,

![Screenshot from 2021-03-15 23-10-29](https://user-images.githubusercontent.com/51921579/111196791-b410c380-85e3-11eb-9465-710091139355.png)

**Comment by deluan** [comment]
I think we don't need the checkboxes when on mobile, and we don't need the header as well

**Comment by armedev** [comment]
yeah if we can create an option in the playlist or album saying select song we could remove the select option for every song.
as for the header in grid, it has the ability to sort which can be useful in mobile but we can remove only the time option in the header.

**Comment by armedev** [comment]
hey, @deluan I was searching for a way in which a component could fit in all [song, album, playlist, artist] section and I came up with this design, 

![Screenshot from 2021-03-15 23-56-54](https://user-images.githubusercontent.com/51921579/111202709-31d7cd80-85ea-11eb-8a68-0b804f204058.png)

pros:
**we can keep the grid header and have all abilities sorting the list in terms of name or time**

cons:
**If the title becomes too long it will become a nightmare**

as @jvoisin suggested that we can`t limit the number of characters in a song title and prefer wrapping,
what do you suggest @deluan?

**Comment by certuna** [comment]
IMO looks like too little space for the song title.

**Comment by armedev** [comment]
> I like the look with short titles, but IMO looks like too little space for the song title?

No its just a figma design i have made in reality the title has a enough breathing room :)

**Comment by armedev** [comment]
@deluan I have recreated the component SongSimpleList to match the above design now it looks like this,

![Screenshot from 2021-03-16 23-26-38](https://user-images.githubusercontent.com/51921579/111357578-711c2200-86af-11eb-91d8-49ab94320db9.png)

this design has the ability to fit in your album list and playlist,
what do you suggest @deluan @jvoisin should I push the code?
or do you suggest any mods?

**Comment by metalheim** [comment]
looks great imho :)

**Comment by deluan** [comment]
I prefer the design in the PR: https://github.com/navidrome/navidrome/pull/833#issuecomment-800845282
