### ISSUE TITLE
Docs: Contributing Guide

### ISSUE THREAD

**Issue by K-Kumar-01** [navidrome/navidrome#827]
In my opinion, navidrome should also have a contributing guide. Currently, we don't have any `CONTRIBUTING.md` file. 
The contributing file will help in many ways:
1. Defining a structure for pull requests (along with proper commit conventions)
2. Defining a structure to open any issue.

This will improve the project structure as well as ensure more readability and understanding of commits made and issues opened.

**Comment by deluan** [comment]
Agree. I'll try to write one this weekend. Thanks for the suggestion/reminder :)

**Comment by K-Kumar-01** [comment]
> Agree. I'll try to write one this weekend. Thanks for the suggestion/reminder :)

Can I make a draft doc having some basic guidelines for these things?
If they are suitable, then they can be used.

**Comment by deluan** [comment]
@K-Kumar-01 Sure, go ahead!

**Comment by K-Kumar-01** [comment]
@deluan 
I have created a PR. Let me know if there are any changes required.

**Comment by metalheim** [comment]
@deluan we have contributing guidelines now, can this be closed?
