### ISSUE TITLE
Songs with special characters are omitted from imported playlist

### ISSUE THREAD

**Issue by cristobalvp** [navidrome/navidrome#829]
In Linux, I can see all the songs at the album, but if a playlist (m3u) is imported, all the songs with special chars are omitted.
Later, I can add them manually without problems.

**Comment by deluan** [comment]
Thanks for the report. Are you using `taglib` (default) or `ffmpeg` as your `Scanner.Extractor` option?

**Comment by cristobalvp** [comment]
Hi. I do not have anything configured in ND_SCANNER_EXTRACTOR, so I suppose that I am using taglib, but the same behaviour is happenning with the variable set to ffmpeg

**Comment by josepmdc** [comment]
Hi, I would like to take a look at this issue if it's ok. I tried with a song like this "%&ñò$•¿¡¡$Öņ.mp3" and I couldn't reproduce the issue, the song was imported with the entire playlist. What kind of special chars are giving you the problem?

**Comment by cristobalvp** [comment]
Hi, my files have the following characters: äÖöüßí
For example I have the following error for the file "006 - DJ Ötzi - Oktoberfest Party Music - Anton aus Tirol.mp3"

Since you are not having the issue, I checked my m3u file, and it was an error with the encoding. It was saved as ANSI instead of UTF8. After converting to UTF8, the playlist is imported correctly in Navidrome.

Sorry for the inconvenience and thanks for your time!
