### ISSUE TITLE
Single color scheme throughout the Application

### ISSUE THREAD

**Issue by ketangupta34** [navidrome/navidrome#830]
As of now a lot of different colors are used throughout the app. There is a need to have a common color scheme.
Navbar - Blue
Icons -  White
labels - light bluish
Playing song - purple

A single color scheme looks more premium.

**Comment by deluan** [comment]
I'm not a design person, and to make things worse I'm color blind 😛 

So feel free to submit a PR with improvements to the current theme(s), if this is something you can handle. Here's some information on how themes work in Navidrome: https://www.navidrome.org/docs/developers/creating-themes/

**Comment by ketangupta34** [comment]
Sure, I would love to work on this!!

**Comment by deluan** [comment]
Try to add your improved theme as a new one, giving it a new name. That's because nobody ever complained about the current colors (after last tweaks), and I don't want to disrupt our user's experience. Besides, the more options the better (in this case) :)

**Comment by ketangupta34** [comment]
Yes, I'll make a new file.

**Comment by SobhanBera** [comment]
Hey @deluan , Can I also give it a chance with a new theme??

**Comment by ketangupta34** [comment]
hey there, the main issue that is faced while making color throughout the application common is that the react-music-player CSS properties need to be updated either through a webpack.config file or through a .less file.

**Comment by deluan** [comment]
@ketangupta34 Yes, that's a limitation. It would be great to come-up with some way to change its colours dinamically, without too much "hacking"... It could also maybe a simple PR to their project, where we enable it to receive an object with all overridden colours, similar to how it handles translations. But this is only worth if it is a simple task.

**Comment by ketangupta34** [comment]
@deluan I am able to make the text color of the song title similar to the theme, but the green primary-color is an issue, I'm reviewing the music-player's GitHub too, and see if something can be done without creating a new file.

**Comment by SobhanBera** [comment]
Hey! @deluan Could I also try on this. If it would be a success I will make a PR soon. I will just try it.

**Comment by SobhanBera** [comment]
# Can I create a particular function like this:
## 1st Idea:
```
cosnt currentTheme(lightSelector = "", darkSelector = "", spotifySelector = "", otherThemeSelector = "") {
    const theme = useSelector(state => state.theme)
    return theme == 'light' ? '0' : theme === 'dark' ? '1' : theme === 'spotify' ? 2 : theme === 'others' ? ...;
}
```

This function could be in the useStyles function like this:
```
const useStyles = makeStyles((theme) => {
    albumName: {
        backgroundColor: currentTheme('white', 'black', 'green', 'other', ...),
    }
})
```

## 2nd Idea:
```
cosnt currentTheme() {
    const theme = useSelector(state => state.theme)
}
```

And we can use it like this:
```
const useStyles = makeStyles((theme) => {
    albumName: {
        backgroundColor: currentTheme().primary,
        textColor: currentTheme().secondary,
    }
})
```
We could provide these values while we are changing the themes. Instead of changing the value 'dark' to 'light' or vice versa, we could change the whole theme property with primary, secondary, and more colours.

Maybe I am wrong and this strategy could be improved, And if this idea is good then please tell me I will continue in this feature to create some more themes.

**Comment by ketangupta34** [comment]
@deluan I tried this issue but as you said edits are needed in the music players Github, I have raised an issue there and will try to solve it there. Till that time, this cannot be resolved in a standardized manner. You can reassign it or close the issue.
Thank you!

**Comment by deluan** [comment]
I'm closing this for now.
