### ISSUE TITLE
POSTing to an invalid URL (eg //rest/) 405s but produces no log

### ISSUE THREAD

**Issue by durin42** [navidrome/navidrome#836]
I noticed this because mopidy-subidy doesn't dedupe trailing slashes on its configured URL, so it was requesting paths that looked like the cURL invocation below. It was getting silent 405s, even at `--loglevel debug`. Reproduced against the navidrome hostport without a reverse proxy involved, eg
`curl -v -X POST 'http://$HOSTPORT/$BaseUrl//rest/ping.view'` (or even without the `ping.view`). If you do a GET you get redirected to the web UI instead.

**Comment by deluan** [comment]
I'd have to take a look, but seems that the logging middleware is not capturing this type of (POST) request. Thanks for the report!

**Comment by ketangupta34** [comment]
@deluan can you provide some more detail about this issue?? I would like to have a look at this.

**Comment by deluan** [comment]
To tackle this, you'll need a good understanding of HTTP servers in Go and how middlewares work in general. Seems that the logging middleware (responsible for generating log messages) is being configured after the point that the server returns the 405, so then it does not log such invalid requests. 

Basically what we want to achieve here is: When a request similar to the `curl` one in the description reaches Navidrome, it needs to generate a log message.

More about this issue can be found in this conversation: https://discord.com/channels/671335427726114836/671335427726114839/820846530323283968

**Comment by josepmdc** [comment]
I was taking a look at this issue and I noticed that if I add this line in the function initRoutes in the server.go file:
```go
func (a *Server) initRoutes() {
    // ...
    r.Use(requestLogger) // I added this
    r.Use(injectLogger) // This is already in the code
    // ...
}
```
the logging middleware does get called and logs the 405 response as a WARN. Does it make sense to add this line here? It's already getting called on the MountRouter function of the same file, but it doesn't get called with the 405 response, I don't know why.
Also I don't know exactly what the injectLogger middleware does but I tried removing it and the logger still worked. What does it do? By looking at the code it looks like it binds the logger to the context but I don't quite understand it.

**Comment by deluan** [comment]
Hey @josepmdc , thanks for looking into this. I don't remember why I didn't add the `requestLogger` to the `initRoutes()` function, will have to take a look. Will get back to you after checking it out.

The `logger` injected in the context by `injectLogger`, is used by the `log` package, to add things like `requestId` to the `log `messages.

**Comment by deluan** [comment]
@josepmdc Now I remember: When I implemented the `requestLogger` it was logging at `info` level, and I didn't want log messages for things like the UI bundle and static resources, to reduce the noise. Now that it is `debug` level, I think it is ok to move it to all requests (in the `initRoutes`) and remove it from the `MountRouter` function. Let's try this and I'll take a look at the logs and see if it does not cause too much noise. Can you please submit a PR?
