### ISSUE TITLE
Artist List view based on standard React Admin template

### ISSUE THREAD

**Issue by certuna** [navidrome/navidrome#847]
Replace the [current bare-bones Artist view](https://user-images.githubusercontent.com/62144283/111197872-4357b000-85bf-11eb-9152-97df99d30d89.png) with one based on [this one from the React Demo](https://marmelab.com/react-admin-demo/#/customers) website:

![Screen Shot 2021-03-15 at 18 07 46](https://user-images.githubusercontent.com/62144283/111192460-5cf5f900-85b9-11eb-8502-e346c6349195.png)

We should probably stick close to this boilerplate component to minimize the work, but even within those boundaries there should be some good functionality to be added here (please contribute if you have other ideas, or really dislike these):

**Columns**
- [ ] Multi-select boxes so you can quickly add all songs of artists `Tom`, `Dick` and `Harry` to one playlist, or Play Now, Play Next, etc - basically, exact same component as in the existing `Songs` view.
- [ ] `Artist` : Navidrome now has artist images so it can look like the Customer column of the demo site
- [ ] `Country` : either from tags, or pulled from last.fm / musicbrainz
- [ ] `Years` : Year range of the artist's songs, eg `1984-2013`, similar way it's handled in the text version of the existing `Albums` list.
- [ ] `Genres` : like the "Segments" column in the demo, all genres for the artist, ranked by number of songs. So an artist with ten `Rock` songs and one `Reggae` song would get `Rock, Reggae`.  _Note: if there's not enough space, maybe only the top 3 Genres?_
- [ ] `Songs/Albums` : number of songs and albums: `48/5`for an artist with 48 songs and 5 albums, `1/0` for an artist with 1 song on a "various artists" compilation. More compact than the current 2-column implementation.
- [ ] `Total time` : total duration of all songs by the artist: `245:12`
- [ ] `Plays` : cumulative plays for all tracks
- [ ] `Last Played`
- [ ] `Popularity` : I believe last.fm has a metric for that? Google Trends? _(maybe not essential, but great for generating outrage among our elderly users when Megan Thee Stallion gets ranked above The Beatles)_
- [ ] `Rating` : average rating of the 1-5 scores for the artist's songs
- [ ] `Star` : like the current view, so you can "like" the artist

**Filters**
- [ ] `Only Album Artists` : filters out artists who only have compilation album appearances
- [ ] `Genre` : like the Segments one in the demo
- [ ] `Last Played` : This Month, Last Year, etc - just like in the demo site
- [ ] `Decade` : just a list of decades is the easiest/quickest way, but in the end I think a two-handle range slider ( https://github.com/navidrome/navidrome/issues/533 ) in the top bar instead is better
- [ ] `Role` : once the 'roles' feature is added ( https://github.com/navidrome/navidrome/issues/211 ), this is where filtering for Composer/Conductor/Remixer/DJ-mixer/Producer/etc can go

**Search**
- [ ] Probably not where it is in the demo website, I think the idea with Omnisearch is to put that in the top bar?

**Comment by rohitgeddam** [comment]
This looks like a good enhancement, I will give it a try!

**Comment by ruddi10** [comment]
@deluan  can you assign this to me

**Comment by certuna** [comment]
Bear in mind that this is not only front end work - at the moment the `artist` REST endpoint in the API only returns a limited set of fields: `name`, `albumCount`, `songCount` and `playCount` (and a lot more, but not the fields needed for the functionality described above).
- things like `min_year`, `max_year`, total time, average rating, last played, and genre(s) are all info that is already in the database, one way or another, but needs to be added to the `artist` table, and added to the `artist` endpoint
- things like country, popularity are not in the DB at all yet, so that needs to be implemented from the ground up: the scanner needs to read it from the tags (or pull from another source like last.fm/etc), the db schema needs a field to store it, and the API needs to expose it.

**Comment by ruddi10** [comment]
Okk

**Comment by rohitgeddam** [comment]
![artist_api](https://user-images.githubusercontent.com/48797475/112503651-1ec6b980-8db1-11eb-9a56-a5219a0002f2.png)

We would like to display the artist image on the artist tab however, the API is returning an empty string
```
"smallImageUrl": "",
"mediumImageUrl": "",
"largeImageUrl": "",
```

how should we fetch the artist image?
* we can fetch the image from the react app using some other external API.
* we can fetch the artist image while we are scanning for the album on the backend and save that to DB.
* some other way ( suggestions please )

**Comment by deluan** [comment]
Artist metadata is handled on the server side. We don't want the UI talking to external services (and potentially introducing some privacy issues).

If (and only if) the image URLs are empty, you can retrieve them using the `getArtistInfo2` api call: http://subsonic.org/pages/api.jsp#getArtistInfo2
