### ISSUE TITLE
Make Album Detail Screen Responsive on smaller devices

### ISSUE THREAD

**Issue by rohitgeddam** [navidrome/navidrome#855]
The Album Detail screen is not responsive in some cases ( where the album name is longer )

![navidrome_album_detail_before](https://user-images.githubusercontent.com/48797475/111747585-7c409f00-88b5-11eb-8506-476a66efba98.gif)

related issue -  #845

**Comment by deluan** [comment]
This was fixed in #845. Are you still seeing this issue?

**Comment by rohitgeddam** [comment]
> This was fixed in #845. Are you still seeing this issue?

Yes the issue was still there, I looked at #845, but somehow it didn't solve the issue, I had made changes after the commit for issue #845 was merged into master, I made a small change and now it works.

**Comment by deluan** [comment]
Yeah, I was able to reproduce it on albums with long `comment` fields. Maybe we just need to apply the changes to that field? Or else is truncates the comment field, where it would be better to add some padding (or a `...`) at the end of the field:

<img width="379" alt="Screen Shot 2021-03-21 at 2 55 02 PM" src="https://user-images.githubusercontent.com/331353/111917284-91543400-8a55-11eb-9c67-da3498b4d3ca.png">

**Comment by rohitgeddam** [comment]
***How about we make the details in a column on smaller screen? This way even if the title is longer it will wrap to the next line***


## Before
<img width="439" alt="Screenshot 2021-03-19 at 3 26 27 PM" src="https://user-images.githubusercontent.com/48797475/111918186-f174c580-8aa9-11eb-8a50-5201e4cb4b18.png">

## After
<img width="352" alt="Screenshot 2021-03-19 at 3 33 34 PM" src="https://user-images.githubusercontent.com/48797475/111918185-efab0200-8aa9-11eb-946f-a97db6b5490c.png">

**Comment by deluan** [comment]
Hummm, I'm not sure how I feel about this, I think it is worth to ask for feedback on the #general channel in Discord. 

But this does not answer my main question: Should we apply the changes you are suggesting to fix responsiveness to the comment only, to avoid it being truncated like I posted in my previous comment?

**Comment by rohitgeddam** [comment]
we can either truncate long comments or we can set overflow property to scroll on css, 
![navidrome_overflow](https://user-images.githubusercontent.com/48797475/111919465-1bc98180-8ab0-11eb-8f0c-5b27ee51e53d.gif)

**Comment by deluan** [comment]
I prefer to just break the line and continue the text in the next line. Your example above is already doing this (...John_Bartmann/Royalty-Free_Soundtrack.... is breaking at the Royalty-Free), just don't know why it still needs to scroll....

**Comment by rohitgeddam** [comment]
Yea, It was annoying why the word wasn't breaking at the right place { ...John_Bartnann/ }. turns out it was a simple fix

please review #856
