### ISSUE TITLE
Select multiple songs/albums and perform a task on them

### ISSUE THREAD

**Issue by KashyapPavra** [navidrome/navidrome#859]
Currently Navidrome does not have the feature to select multiple songs/albums and perform a task on them.
Like the below example of Apple Music:

https://user-images.githubusercontent.com/22401926/111804062-b7fb5900-88f5-11eb-8e7e-e1be1e0aa0ee.mov

1. A discussion can be opened regarding what tasks can be performed as currently there is no option to perform any task even on a single album or song. We could capture a right click event and add these task list.
2. Once we have a list of task, next would be to add a drag and select functionality

**Comment by deluan** [comment]
Selecting multiple albums in AlbumGrid view would be awesome. But your statement about not having tasks per song/album is incorrect. We have tasks for Albums, Artists and Songs. And we can select multiple songs to perform tasks on them:

https://user-images.githubusercontent.com/331353/111810541-827e4d80-88ac-11eb-934e-d09de9e8baa0.mov

https://user-images.githubusercontent.com/331353/111810569-8a3df200-88ac-11eb-98a0-38c76c4a4f94.mov


https://user-images.githubusercontent.com/331353/111810572-8b6f1f00-88ac-11eb-9c56-a473b8571d23.mov

**Comment by KashyapPavra** [comment]
@deluan Ohh I missed this because I checked just for albums, which does not have an option to select multiple items and perform a task. I see there are already a bunch of tasks, so should I implement the drag and select feature? also add a feature for selecting multiple items and perform a task for albums as well?

**Comment by deluan** [comment]
Yes, that would be awesome. Not sure if drag and select is the best option though, as it cannot be used in mobile. Maybe use the same pattern we have in `Songs`? Maybe add a "Select" button at the top right (besides "Add Filter"), that would enter "select mode", showing a checkbox on each album? We could then leverage the `BulkActionsToolbar` from React-Admin.

**Comment by KashyapPavra** [comment]
@deluan maybe we can have a different approach for mobile drag and select, like this which is implemented for Apple Photos app :

https://user-images.githubusercontent.com/22401926/111825835-f56be080-890d-11eb-9e6a-139ea6ca1675.MP4

I am trying to implement the ``BulkActionsToolbar`` for albums, we might need an additional component ``AlbumBulkActions.js`` just similar to ``SongBulkActions.js`` , and then add it to ``AlbumList.js``
