### ISSUE TITLE
 Search Engine Optimization (SEO) for the web pages

### ISSUE THREAD

**Issue by Shruti3004** [navidrome/navidrome#860]

**Comment by Shruti3004** [comment]
@deluan I want to work on this issue

**Comment by jvoisin** [comment]
There is no need for "SEO" for the "web pages".

**Comment by deluan** [comment]
@Shruti3004 If you are talking about applying SEO practices to Navidrome website (https://www.navidrome.org), this is the wrong repo. The correct one is https://github.com/navidrome/website

On the other hand, Navidrome itself should be as SEO UN-friendly as possible, as it is a[ self-hosted app](https://en.wikipedia.org/wiki/Self-hosting_(web_services)), and users don't want to have their servers indexed by Search Engines.
