### ISSUE TITLE
Ability to peer with other instances

### ISSUE THREAD

**Issue by not-wlan** [navidrome/navidrome#861]
Hi!

Something I'd really like to see in navidrome would be the ability to peer with other instances to share music with your friends & family. For the end user it would be similar to the library sharing found in Plex.

**Comment by deluan** [comment]
Thanks for trying Navidrome! Even though the scope of Navidrome is of a personal music server, this may be implemented in the future, as a UI-only feature. See also the #748 feature request, that will allow you to share music with people that does not have a Navidrome instance running.
