### ISSUE TITLE
Weird behaviour while using navidrome

### ISSUE THREAD

**Issue by the-pro** [navidrome/navidrome#864]
I am not sure if this is a serious issue but it surely seems weird while using navidrome:

Bug:

Some symbols turn black from white after minimizing and maximizing the player. It happens only in dark mode and spotify-ish mode both of which uses a dark theme.

Steps to reproduce:

- play a song
- observe the '>' symbols in the list
- minimize it
- maximize it
- observe the '>' symbol in the list

![bitmap](https://user-images.githubusercontent.com/42973786/111884002-b65c8e80-89e4-11eb-94f9-80aa1c89e4c1.png)

**Comment by deluan** [comment]
Which browser you see this happening? Can you reproduce it with the [demo site](https://demo.navidrome.org)? I can't reproduce the issue with the latest version, nor with my local copy (master), when using Chrome.

**Comment by the-pro** [comment]
I am using firefox browser and yes sir it can be produced in the demo site after minimizing and maximizing the audio player

![navise](https://user-images.githubusercontent.com/42973786/111894468-f0ec1880-8a30-11eb-86b5-20fff891c43e.png)

**Comment by deluan** [comment]
Are you sure you have the latest code, without any local changes? I can't reproduce it here (Firefox on macOS):

![ezgif com-gif-maker](https://user-images.githubusercontent.com/331353/111917528-d0cf5000-8a56-11eb-8f30-57f00feb6d6e.gif)

**Comment by the-pro** [comment]
No sir you have to minimize and maximize the audio player. I produced the above on the demo site

**Comment by deluan** [comment]
Still not able to reproduce it.... Can you post a video?

**Comment by the-pro** [comment]
Yes sir here it is:

https://user-images.githubusercontent.com/42973786/111918386-de162a00-8aaa-11eb-8ff2-e076feb626cb.mp4

**Comment by deluan** [comment]
Ah yes, I see. I was able to reproduce this issue in Chrome as well. Good catch. This is probably caused by the player being removed and added back to the DOM by React, causing aconflict with Material-UI. A comment from a discussion about this in the past:

> What casues this is react will add/remove styles based on whats on the page, because the jkmusicplayer is added and removed to the dom when you clear playlist (or hit the minus button) it weill remove the styles reuquired for that component and because its rendering the material-ui component its adding and removing it and css priority is shifting on for the class .MuiIconButton-root

Do you think you can fix this?

**Comment by the-pro** [comment]
I would definitely like to try

**Comment by deluan** [comment]
I did a `git bisect` to find when this bug was introduced. It is definitely caused by what I describe in the previous comment. Here's the commit, if you want to investigate:
```
b18e3289fb3b12b594505fb90678ad3efc711c60 is the first bad commit
commit b18e3289fb3b12b594505fb90678ad3efc711c60
Author: Deluan <deluan@navidrome.org>
Date:   Mon Aug 24 19:38:29 2020 -0400

    Add StarButton to player

 ui/src/audioplayer/Player.js        |  5 ++++-
 ui/src/audioplayer/PlayerToolbar.js | 30 ++++++++++++++++++++++++++++++
 ui/src/common/StarButton.js         |  1 +
 3 files changed, 35 insertions(+), 1 deletion(-)
 create mode 100644 ui/src/audioplayer/PlayerToolbar.js
 ```

**Comment by Balaguru4580** [comment]
Weirdly enough, on firefox and chromium on Ubuntu, the black arrow problem occurs whenever the player is closed. The favorite heart icon also turns black.

I wasn't able to reproduce the minimize problem that seems to be the main issue, but this seems to be related as wel.

I think I'll also take a crack at this and see what's going on. Thanks @deluan for providing the commit where that happened by the way. I'll try and use that as a starting point to working on fixing it.
