### ISSUE TITLE
Media Folder is empty. Aborting scan.  (Even if media folder is not empty)

### ISSUE THREAD

**Issue by gg-dev-05** [navidrome/navidrome#868]
After following the procedure for setting up the dev environment specified [here](https://www.navidrome.org/docs/developers/dev-environment/). If a user is having **no sub folders** in the media folder then navidrome returns 
```
[00] ERRO[0002] Media Folder is empty. Aborting scan.
```
after running the command  ```make dev``` even if the folder is having some mp3 files.

**Comment by deluan** [comment]
As we discussed in Discord, this is a bug. Navidrome wrongly shows this message when there are no subfolders in the MusicFolder, a rather uncommon situation for self-hosted users, but something that can happen in development environments.

This check was implemented to avoid deleting all your library in a situation where your music folder is not mounted when Navidrome starts:

https://github.com/navidrome/navidrome/blob/6ee45a9ccc5e7ea4290c89030e67c99c0514bd25/scanner/tag_scanner.go#L107-L111

But this check is wrong. We actually need to check if Navidrome could not find any files, not folders.

**Comment by gg-dev-05** [comment]
@deluan Can I work on this issue?

**Comment by deluan** [comment]
Sure! Let me know if you have any questions.

**Comment by gg-dev-05** [comment]
@deluan I am thinking about the following solution 

 If any file with the extension(mp3, ogg, wav) is present then don't show this error message of empty folder.
Is this solution fine? Also what other extensions are to be included?

**Comment by deluan** [comment]
You shouldn't check for files in the folder. Other functions in the scanner logic already do that, you should only check if they found and processed any files or not.

**Comment by g4rry420** [comment]
Is this issue still open or not ?

**Comment by deluan** [comment]
It is. The open PR does not work in some situations, but as this affects not many ND users, and a simple workaround exists (put songs in a subdir under the Music Folder), it is very low priority at the moment. I plan to take a look at it once I get to the [Multiple Libraries](https://github.com/navidrome/navidrome/issues/192) implementation

**Comment by fuomag9** [comment]
My case maybe it's "anomalous", but I don't care about organizing my music and I just dump it all in the same folder so I'm getting this error as well

**Comment by l4kr** [comment]
I'm adding that my folder structure is /music/artist/album/song.mp3 and I am also getting this issue.

**Comment by deluan** [comment]
This will be fixed in the new scanner I'm working on. In the meantime the workaround is documented here: https://github.com/navidrome/navidrome/issues/937#issuecomment-1257089106
