### ISSUE TITLE
The scan fails with an error

### ISSUE THREAD

**Issue by KorobeinikovIgor** [navidrome/navidrome#873]
My log:
$ navidrome

2021/03/22 12:21:44 goose: no migrations to run. current version: 20201213124814
INFO[0000] Starting scanner                              interval=1m0s
INFO[0000] Configuring Media Folder                      name="Music Library" path=music
INFO[0000] Creating Image cache                          maxSize="100 MB" path=cache/images
INFO[0000] Finished initializing cache                   cache=Image elapsedTime="419.725µs" maxSize=100MB
INFO[0000] Found ffmpeg                                  path=/usr/bin/ffmpeg
INFO[0000] Last.FM integration not available: missing ApiKey/Secret 
INFO[0000] Spotify integration is not enabled: artist images will not be available 
INFO[0000] Creating Transcoding cache                    maxSize="100 MB" path=cache/transcoding
INFO[0000] Mounting routes                               path=/rest
INFO[0000] Finished initializing cache                   cache=Transcoding elapsedTime=10.5ms maxSize=100MB
INFO[0000] Mounting routes                               path=/app
INFO[0000] Login rate limit set                          requestLimit=5 windowLength=20s
INFO[0000] Navidrome server is accepting requests        address="0.0.0.0:4533"
INFO[0001] Setting Session Timeout                       value=24h
ERRO[0002] Error stating dir                             error="stat music: no such file or directory" path=music
ERRO[0002] Error loading directory tree                  error="stat music: no such file or directory"
ERRO[0002] There were errors reading directories from filesystem  error="stat music: no such file or directory"
ERRO[0002] Scan was interrupted by error. See errors above  error="stat music: no such file or directory"
ERRO[0002] Error importing MediaFolder                   error="stat music: no such file or directory" folder=music
ERRO[0002] Errors while scanning media. Please check the logs 
ERRO[0002] scan error                                   
ERRO[0062] Error stating dir                             error="stat music: no such file or directory" path=music
ERRO[0062] Error loading directory tree                  error="stat music: no such file or directory"
ERRO[0062] There were errors reading directories from filesystem  error="stat music: no such file or directory"
ERRO[0062] Scan was interrupted by error. See errors above  error="stat music: no such file or directory"
ERRO[0062] Error importing MediaFolder                   error="stat music: no such file or directory" folder=music
ERRO[0062] Errors while scanning media. Please check the logs 
ERRO[0062] scan error                                   
ERRO[0122] Error stating dir                             error="stat music: no such file or directory" path=music
ERRO[0122] Error loading directory tree                  error="stat music: no such file or directory"
ERRO[0122] There were errors reading directories from filesystem  error="stat music: no such file or directory"
ERRO[0122] Scan was interrupted by error. See errors above  error="stat music: no such file or directory"
ERRO[0122] Error importing MediaFolder                   error="stat music: no such file or directory" folder=music
ERRO[0122] Errors while scanning media. Please check the logs 
ERRO[0122] scan error                                   
ERRO[0182] Error stating dir                             error="stat music: no such file or directory" path=music
ERRO[0182] Error loading directory tree                  error="stat music: no such file or directory"
ERRO[0182] There were errors reading directories from filesystem  error="stat music: no such file or directory"
ERRO[0182] Scan was interrupted by error. See errors above  error="stat music: no such file or directory"
ERRO[0182] Error importing MediaFolder                   error="stat music: no such file or directory" folder=music
ERRO[0182] Errors while scanning media. Please check the logs 
ERRO[0182] scan error                                   

OS: MANJARO LINUX ARM64 (64 bits)
Device: Raspberry Pi 4

**Comment by deluan** [comment]
Did you configure your MusicFolder to point to the folder where your music files are stored? By default (your case, based on the logs), it looks for a folder named `music` under the current directory.

**Comment by KorobeinikovIgor** [comment]
Thank you, this working
