### ISSUE TITLE
update cached webUI when new server version is detected

### ISSUE THREAD

**Issue by certuna** [navidrome/navidrome#875]
Currently, the Navidrome web UI caches all JS/HTML assets client-side once, on login. When a new version of the server is installed, the clients do not automatically refresh their assets.

Logging out [now clears the serviceworker cache](https://github.com/navidrome/navidrome/pull/854), so from 0.41 onwards, a manual logout/login cycle will refresh the web UI/PWA. But if a user has not logged out in a few months, he could still have the cached 0.37 web code running while the server version is already at 0.41. This is clearly undesirable. Requiring all the server's users to manually log out/log in whenever the server is updated is impractical. A forced reload (Shift-Ctrl-R) works, but is unintuitive, and impossible on mobile platforms or tv browsers.

So, this enhancement to the web UI would:
1. perform a check if there are new remote assets
2. reload all assets

Considerations for step 1: How would a check work?
- implement a new `version` REST endpoint in the API, client stores the current version string and "last checked for new version" date in localStorage and periodically runs a check?
- add a `version` element to all/some API responses and with each API call, check against the localStorage version string?
- perhaps nothing server-side is needed, and this can be done automatically using some built-in ServiceWorker 'magic' that detects changes?

Considerations for step 2:
- do we actually want to prompt users "upgrade the web app yes/no"?
- or should it just force-reload silently (given that server updates happen relatively infrequently)?

Some light reading on the subject:

https://redfin.engineering/how-to-fix-the-refresh-button-when-using-service-workers-a8e27af6df68
https://deanhume.com/displaying-a-new-version-available-progressive-web-app/
https://stackoverflow.com/questions/33262385/service-worker-force-update-of-new-assets
https://stackoverflow.com/questions/40100922/activate-updated-service-worker-on-refresh#
https://stackoverflow.com/questions/52221805/any-way-yet-to-auto-update-or-just-clear-the-cache-on-a-pwa-on-ios

**Comment by deluan** [comment]
Thanks for creating this. I tagged it as a "good first issue", but it may not be as straightforward (it is not for me :P, home someone with better JS skills than mine and PWA knowledge steps in)

**Comment by armedev** [comment]
@deluan I think it is not a good first issue, it has to do with how service workers work they update if there is a byte of change
which we can utilize to update the service worker by providing version numbers to service workers automatically from servers
after which we have to replace our cache with new data which is quite complicated though :P

**Comment by pkspyder007** [comment]
@deluan What if we have a `/version` route in the backend and on our application load i.e. `useEffect` of the `App` component we can check for the version change.
If true we can clear the cache similar to how we do it on logout using clearServiceWorkerCache() in authProvider.js and on a new request the service worker will automatically cache the new request responses
@certuna Did I missed something about service workers, I am also not experienced with them.

**Comment by deluan** [comment]
We don't want to force an update, we want something similar to GMail: A message saying "There is a new version. Click here to refresh". There is some discussion about this here: https://github.com/navidrome/navidrome/issues/613#issuecomment-724359765

**Comment by pkspyder007** [comment]
So yes that could also be implemented in the same manner instead of forcing we can have a confirm box pop to ask the user to choose Yes or no for update

**Comment by deluan** [comment]
I implemented a Notification when the server updates in 877f01bd. Based on the conversation above, and the current "network-first " PWA implementation, I think this can be closed?

What do you think, @certuna ?

**Comment by certuna** [comment]
If it all works, fine with me!
