### ISSUE TITLE
artist list ui problem

### ISSUE THREAD

**Issue by armedev** [navidrome/navidrome#890]
In the artist list, the mobile UI is not optimized :>

![Screenshot from 2021-03-23 10-17-08](https://user-images.githubusercontent.com/51921579/112094431-40f9e500-8bc1-11eb-8882-719ce2b4fdb5.png)

should create a new UI for the displaying of artists.

**Comment by armedev** [comment]
@deluan can I work on this issue?

if yes, you can assign it to me. will submit a PR.

**Comment by jvoisin** [comment]
No need to be assigned an issue to work on it :)
