### ISSUE TITLE
Bug : BulkActionToolbar in playlist remain open

### ISSUE THREAD

**Issue by RitikPandey1** [navidrome/navidrome#896]
Found a bug. If I select and delete the 3 songs from playlist, after it  `3 items selected` message was still there and `BulkActionToolbar` remains open.

![navidromeBug](https://user-images.githubusercontent.com/57366926/112252246-c42f3f80-8c82-11eb-8698-f8913f45a063.gif)

**Comment by RitikPandey1** [comment]
I'd like to resolve this bug.

**Comment by metalheim** [comment]
Can confirm this happens to me too.

**Comment by deluan** [comment]
Fixed in #898
