### ISSUE TITLE
Change menu icon when menu is selected

### ISSUE THREAD

**Issue by ruhci28** [navidrome/navidrome#899]
On selecting the menu item the icon does not change.  I think if we will change the icon on the selection then it will enhance UI. 
Like in Spotify the icons changes 

https://user-images.githubusercontent.com/59759735/112264191-83412600-8c96-11eb-979b-99abe02f2d80.mov

But in navidrome the icons does not changes

https://user-images.githubusercontent.com/59759735/112264245-994ee680-8c96-11eb-91c6-96f8234d63ef.mov

@deluan  @jvoisin should I do this change in UI

**Comment by ruhci28** [comment]
I try to apply some changes 

https://user-images.githubusercontent.com/59759735/112264893-8d175900-8c97-11eb-8c70-4b9a761f1043.mov
@jvoisin  should i proceed with it.?

**Comment by deluan** [comment]
That seems nice. Please create a PR

**Comment by ruhci28** [comment]
Okay i will create a PR soon after refactoring the code

**Comment by deluan** [comment]
Closed by #903
