### ISSUE TITLE
Bug: Encounter "ReferenceError: caches is not defined" error in console

### ISSUE THREAD

**Issue by kaiiiz** [navidrome/navidrome#901]
* Version: 0.41.0
* Testing Environment: Raspberry Pi 4, Raspbian, docker
* Browser: Brave 1.21.77 (Chromium 89.0.4389.90) and Firefox 86.0.1

After the service startup, it's hanging on loading page, and the following error appear in brave browser's console:

```
Uncaught (in promise) ReferenceError: caches is not defined
    at ce (authProvider.js:102)
    at Object.logout (authProvider.js:62)
    at useLogout.js:44
    at CoreAdminRouter.js:89
    at CoreAdminRouter.js:43
    at Object.throw (CoreAdminRouter.js:24)
    at s (CoreAdminRouter.js:16)
```

![image](https://user-images.githubusercontent.com/30596812/112361140-094c8380-8d0e-11eb-9fcb-9631fcccb9bf.png)

Then I test it in firefox, it's function normally:

![image](https://user-images.githubusercontent.com/30596812/112361394-4b75c500-8d0e-11eb-89c4-5a89630dfb52.png)

After doing some research, I find out that: **Chrome and Safari only expose `CacheStorage` to the windowed context over HTTPS** (Ref: https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage), so it's failed since I've not setup https yet.

I consider this as a bug since I always test the functionality of the service before doing some advanced stuffs (reverse proxy, https...etc), so I think it's abnormally to have this error and hope this can be fixed.

**Comment by certuna** [comment]
Yeah this is a bit of a thing with these days - more and more new features formally require https, but fallback behaviour over http is unpredictable.

**Comment by aldrinjenson** [comment]
Hey, this has some major trouble in mobile devices.
Tested on both chrome and Brave for android.
![errorLog](https://user-images.githubusercontent.com/53407417/112714250-76733b00-8eff-11eb-9729-0882bdaacfa6.jpeg)

### Steps to reproduce
- try logging out and signing in again in Chrome/Brave browser for Android
- Or try opening the link in incognito mode for Chrome/Brave

Apparently, the cacheStorage is available in Chrome android only if the content is served through ssl it seems!
https://stackoverflow.com/questions/53094298/window-caches-is-undefined-in-android-chrome-but-is-available-at-desktop-chrome.

Is adding a check to see the availability before deletion the right fix? That solves the problem. Though I'm not sure if this is the best/permanent solution.

**Comment by deluan** [comment]
@certuna Any thoughts?
