### ISSUE TITLE
After upgrading to v.0.41.0 the About dialog is still showing v.0.40.0

### ISSUE THREAD

**Issue by stefanomarty** [navidrome/navidrome#905]
After upgrading to the latest version, the navidrome binary on the server shows the correct v.0.41.0:
```
/opt/navidrome/navidrome --version
0.41.0 (ba922bbf)

```
but the About dialog keeps showing the previous one:
<img width="236" alt="Schermata 2021-03-25 alle 09 29 46" src="https://user-images.githubusercontent.com/3297621/112443164-ec837080-8d4c-11eb-9dab-f5a7fc3a53fb.png">

`Version:	0.40.0 (8799358a)
`

I cannot figure out why, the only place I found a reference to version v.0.40.0 is AboutDialog.test.js
Is it possible it's loading the wrong version number from here?

**Comment by certuna** [comment]
https://github.com/navidrome/navidrome/issues/875

**Comment by stefanomarty** [comment]
Thanks, hadn't seen that. Clearing the Chrome browser cache soved it.
