### ISSUE TITLE
 After updating to 0.41.0 unable to access navidrome

### ISSUE THREAD

**Issue by DowXor** [navidrome/navidrome#906]
Hello,

Thanks you for this super app !

After updating to 0.41.0, I can't access to navidrome. I just have this message : 

![image](https://user-images.githubusercontent.com/57010998/112454814-5bff5d00-8d59-11eb-864f-3b539d7afa18.png)

I have cleared the older installation (var/lib/navidrome) but always KO. Nothing in journalctl. Scan is ok but no access.

Can you help me ?

Navidrome run on Debian 10 (update OK)

Config file : 
```
LogLevel = 'DEBUG'
ScanInterval = '1h'
TranscodingCacheSize = '150MiB'
MusicFolder = '/mnt/Musiques/'
```

Service config : 
```
[Unit]
Description=Navidrome Music Server
After=remote-fs.target network.target
AssertPathExists=/var/lib/navidrome

[Install]
WantedBy=multi-user.target

[Service]
User=navidrome
Group=navidrome
Type=simple
ExecStart=/opt/navidrome/navidrome --configfile "/var/lib/navidrome/navidrome.toml" -p 50003 --scaninterval "168h" --enabletranscodingconfig
WorkingDirectory=/var/lib/navidrome
TimeoutStopSec=20
KillMode=process
Restart=on-failure

# See https://www.freedesktop.org/software/systemd/man/systemd.exec.html
DevicePolicy=closed
NoNewPrivileges=yes
PrivateTmp=yes
PrivateUsers=yes
ProtectControlGroups=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
RestrictNamespaces=yes
RestrictRealtime=yes
SystemCallFilter=~@clock @debug @module @mount @obsolete @reboot @setuid @swap
ReadWritePaths=/var/lib/navidrome

# You can uncomment the following line if you're not using the jukebox This
# will prevent navidrome from accessing any real (physical) devices
#PrivateDevices=yes

# You can change the following line to `strict` instead of `full` if you don't
# want navidrome to be able to write anything on your filesystem outside of
# /var/lib/navidrome.
ProtectSystem=full

# You can comment the following line if you don't have any media in /home/*.
# This will prevent navidrome from ever reading/writing anything there.
#ProtectHome=true

```

**Comment by certuna** [comment]
It's probably this: https://github.com/navidrome/navidrome/issues/904

Try either:
- force reload (Shift-Ctrl-R)
- clear browser cache
Does that fix it?

**Comment by DowXor** [comment]
I have already try this :/ 
And I tested access with Brave and Edge : same problem

**Comment by metalheim** [comment]
I had the same issue. 
Manually going to **<your-domain:port>/app/#/login** I was presented with the login screen. After logging in there, everything worked as usual :)

**Comment by DowXor** [comment]
Well done :)
It works !

So, the redirection no longer works since the update in 0.41.0.
I leave the developers closed this issue when they will read your comment.

Thanks you :)

**Comment by deluan** [comment]
Thanks for the report. This is a know issue and a fix will be release soon. Also thanks for @metalheim for providing the [workaround](https://github.com/navidrome/navidrome/issues/906#issuecomment-806715056)

**Comment by deluan** [comment]
Will keep this open until more testing is done. If anyone is having this issue, please try with the latest dev build (should be available in ~10 minutes)

**Comment by deluan** [comment]
Seems to work fine. Please feel free to report back if you still see this error.

**Comment by aldrinjenson** [comment]
Hey, I think we should keep this issue or #950 open till a new production build is released.
Otherwise, new users facing this issue won't be able to search and find a fix quickly in the issues tab. 

Or, is doing something like a hot-fix a good idea?
