### ISSUE TITLE
Album name in Navbar

### ISSUE THREAD

**Issue by ruhci28** [navidrome/navidrome#909]
#### current navbar
![Screenshot 2021-03-26 at 9 10 18 AM](https://user-images.githubusercontent.com/59759735/112574095-a0e7ca00-8e13-11eb-82a0-7458dd2a977b.png)

#### After adding the name of the album in the navbar
![Screenshot 2021-03-26 at 9 03 25 AM](https://user-images.githubusercontent.com/59759735/112574128-b0ffa980-8e13-11eb-9986-e4a32c9e82b8.png)

@jvoisin @deluan does I should proceed with this change.?

**Comment by jvoisin** [comment]
Sure.

**Comment by deluan** [comment]
Actually, I'm not sure about that. Even though it is not great right now, I never added the title in this view because it duplicates the name in the title and in the page. And in a mobile view, it would be even worse. 

Unless you come up with a good solution to avoid the duplication, I wouldn't touch this.

**Comment by Dnouv** [comment]
I agree with @deluan; for mobile view, lengthy titles might be an issue. How about implementing it as desktop-only.

**Comment by samarsault** [comment]
> Actually, I'm not sure about that. Even though it is not great right now, I never added the title in this view because it duplicates the name in the title and in the page. And in a mobile view, it would be even worse.

Agreed, I believe adding album name in the appbar is redundant, even in the desktop version.

**Comment by certuna** [comment]
Also, showing the album name when you're playing a songs-oriented playlist is probably not really what you're interested in.

**Comment by deluan** [comment]
So, most agree this is not a great idea, at least with the current page/menubar layout. I will close this, then. Thanks @ruhci28 for the suggestion.
