### ISSUE TITLE
Albums Details and Song Details UI is different

### ISSUE THREAD

**Issue by ruhci28** [navidrome/navidrome#910]
### Album Details and Song Details UI is different

![Screenshot 2021-03-26 at 10 18 27 AM](https://user-images.githubusercontent.com/59759735/112582542-c3caac00-8e1c-11eb-94c5-a7aec7eebc11.png)
![Screenshot 2021-03-26 at 10 17 14 AM](https://user-images.githubusercontent.com/59759735/112584250-7c90eb00-8e1d-11eb-959f-b4f8c6a5283a.png)

#### Make both the details look similar
![Screenshot 2021-03-26 at 10 16 56 AM](https://user-images.githubusercontent.com/59759735/112584193-608d4980-8e1d-11eb-9108-d15b8a025491.png)

**Comment by deluan** [comment]
This is not a bug, but it would be nice to be fixed :)

**Comment by Dnouv** [comment]
@ruhci28, sorry to bother you, just wanted to know whether you're still working on this issue?

**Comment by ruhci28** [comment]
Yes i am working on it

**Comment by deluan** [comment]
Hey @ruhci28, sorry, but I approved @Dnouv's PR, didn't see you were also working on this (too many people to keep track 😛 )

If you still want to work on this, as a follow up, you could refactor the code and create a single component that could be used in both Album and Song details. Tests would be a plus :)
