### ISSUE TITLE
Search box should always be visible, perhaps up in the header bar

### ISSUE THREAD

**Issue by SteveDinn** [navidrome/navidrome#912]
### Is your feature request related to a problem? Please describe.

The search box should always be available for, uh...searching.

I get the concept of context-sensitive searching, and I think that search boxes should also exist within views for albums, artists, songs, etc., that should search only that specific type of content. But sometimes I don't know what I'm searching for, or I'm not sure if it's a song title or an album title. More often than not, I'm on an album page, having just played it, and I want to add more to the playlist. Where is the search box? I have no idea. I just want to be able to search again quickly for something -- anything.

### Describe the solution you'd like

The search box should be permanently visible from the header bar at the top. Maybe the entire box, or maybe just a magnifying glass icon that expands into the full box when moused-over or clicked. Maybe something like this, but matching the colours of the header.
![image](https://user-images.githubusercontent.com/3911507/112644200-e90ee880-8e23-11eb-9103-03c71477f178.png)

I know the Subsonic API returns artists, tracks, and albums, but Navidrome may require a new view that shows these three types of items.

### Additional context
It would be cool to have queries that can be annotated with prefixes, i.e., `album:Metallica` vs. `artist:Metallica`

**Comment by deluan** [comment]
Thanks @SteveDinn, this is already being tracked in the #468 and #255, and is also one of the proposed [subprojects for GSoC](https://www.navidrome.org/docs/gsoc/#5-omnisearch)

I may borrow your (well articulated) description and add it to #468. I'm closing this for now to avoid duplication. Feel free to add additional comments on the issues linked above.
