### ISSUE TITLE
A greeting message for users

### ISSUE THREAD

**Issue by Dnouv** [navidrome/navidrome#916]
### Is your feature request related to a problem? Please describe.

No, it's not related to a problem, rather an enhancement related most of the sites nowadays has auto greeting feature based on the users time as "Good evening," "Good morning."

### Describe the solution you'd like

A greeting message at the top of the album list would be nice.

### Describe alternative solutions that would also satisfy this problem

It is just an optional feature request, and if it gets positive responses, I would like to implement this feature.

### Additional context

Here is the attached screenshot of the greeting on Spotify
<img width="692" alt="spotify_greeting" src="https://user-images.githubusercontent.com/61188295/112721194-a08d2300-8f28-11eb-9497-c87a46044796.png">

**Comment by jvoisin** [comment]
I don't like this idea: I like navidrome because of its simple interface, adding useless text would go against this.

**Comment by Dnouv** [comment]
Ok, anyways, it was optional; thanks for your feedback, @jvoisin. Should I close this issue?

**Comment by deluan** [comment]
Yeah, while we don't have a "home" view, I don't see any place for this message. Thanks for the suggestion, though.
