### ISSUE TITLE
navbar overlapping scrollbar

### ISSUE THREAD

**Issue by Vivekk07** [navidrome/navidrome#919]
### Description

Navbar and music bar overlaps scrollbar when profile dropdown is opened

### Steps to reproduce

1. Play any song
2. Click on your profile icon to open a dropdown
3. Notice the navbar and music bar overlaps scrollbar

### Platform information

 - Navidrome version: 0.41.0 (ba922bbf)
 - Browser and version: Chrome Version 89.0.4389.90
 - Operating System: Windows 10

### Screenshot
![image](https://user-images.githubusercontent.com/44539761/112745889-3b3d3e80-8fc9-11eb-9057-92b980ab4e4c.png)

**Comment by Dnouv** [comment]
Yeah, @Vivekk07, I was able to reproduce this issue; I'm working on this and will get it fixed soon. Thanks for reporting this issue.

**Comment by Vivekk07** [comment]
@Dnouv I am working on it myself too, but sure you can go ahead as well

**Comment by KaramveerSidhu** [comment]
@Dnouv @Vivekk07 , the navbar overlaps the scrollbar even if you don't play a song.

**Comment by Dnouv** [comment]
@KaramveerSidhu, thanks for following the issue. It was overlapping, which I have tried to fix now. 
Here is the screenshot after the fix,
![navid919](https://user-images.githubusercontent.com/61188295/112750614-240d4980-8fe7-11eb-8772-0c32b0380749.png)

**Comment by KaramveerSidhu** [comment]
@Dnouv Great work! Though it would look even better if there's a little less space between the user details bar and the scrollbar.

**Comment by Dnouv** [comment]
Sorry @KaramveerSidhu, I am not sure if I fully understand your comment. Is it that you're suggesting to decrease the gap between the Dev admin popup and scrollbar?

**Comment by KaramveerSidhu** [comment]
@Dnouv Yes!

**Comment by Dnouv** [comment]
> @Dnouv Yes!

Something like this @KaramveerSidhu ?
<img width="955" alt="navid919n" src="https://user-images.githubusercontent.com/61188295/112763881-f1ce0d00-9023-11eb-83a7-54fe3ac4b46c.png">

**Comment by KaramveerSidhu** [comment]
@Dnouv Absolutely! It looks much better.

**Comment by Dnouv** [comment]
@jvoisin, @deluan, the same issue is on the react admin site. Should we report this on the react-admin repository or try to fix it for navidrome. Here is the screenshot of the demo page.
<img width="960" alt="Navbar overlap at top-right corner" src="https://user-images.githubusercontent.com/61188295/113000264-4640cc00-918d-11eb-89f1-c9be100f15f5.png">

**Comment by deluan** [comment]
I think opening an issue in React-Admin and discussing it there may be a better approach. We may be missing some edge case, some special resolution that your PR could break. I'd like to hear what they have to say about it.
