### ISSUE TITLE
Unwanted ConsoleLog Error thrown by the browser

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [navidrome/navidrome#921]
### Description

Unwanted `console.error`  thrown by the browser

![Screenshot from 2021-03-29 00-28-33](https://user-images.githubusercontent.com/54576074/112764362-c1876e00-9025-11eb-8aa8-3279bf8e81ed.png)

The browser is complaining that we have nested `<a>` tag which is forbidden/bad-practice
The component which is causing is in file :- `ui/src/Album/AlbumGridView.js` because we have nested Link Tags
``` jsx
// snippet from AlbumGridView.js
  <Link
    className={classes.albumLink}
    to={linkToRecord(basePath, record.id, 'show')}
  >
    <Typography className={classes.albumName}>{record.name}</Typography>
    {showArtist ? (
      <ArtistLinkField record={record} className={classes.albumSubtitle} />
    ) : (
      <RangeField
        record={record}
        source={'year'}
        sortBy={'maxYear'}
        sortByOrder={'DESC'}
        className={classes.albumSubtitle}
      />
    )}
  </Link>

--------------------------------------
// code for ArtisLinkField

export const ArtistLinkField = withWidth()(({ record, className, width }) => {
  const artistLink = useGetHandleArtistClick(width)
  return (
    <Link
      to={artistLink(record.albumArtistId)}
      onClick={(e) => e.stopPropagation()}
      className={className}
    >
      {record.albumArtist}
    </Link>
  )
})

```

### Expected Behaviour

Eliminate the error generated by the browser in the console:

- This could be solved by either adding a property `component="div"` in either of the Link Component, ([LINK component API](https://material-ui.com/api/link/#props))
- Or [programmatically navigate](https://stackoverflow.com/questions/42123261/programmatically-navigate-using-react-router-v4) to the new link using react-router-dom 

### Steps to reproduce

1. Open browser console

### Platform information
 - Browser and version: Chrome
 - Operating System Ubuntu 20.04

**Comment by aldrinjenson** [comment]
Ahh. Good catch. Thanks for the heads up.
Don't think changing component type is a good idea here.
Also Links shouldn't be wrapping over each other AFAIK.
Lemme see if there's some easy fix🤞

**Comment by deluan** [comment]
Yeah, this is a know issue, and was left like this because it is (apparently) harmless. This is something that will be fixed with the Album Grid rewrite, one of the GSoC projects. If it is not picked-up for GSoC, the rewrite will be done at some point
