### ISSUE TITLE
Unrecognized prop error in console

### ISSUE THREAD

**Issue by aldrinjenson** [navidrome/navidrome#925]
### Description
A recent change to code base causes a minor error and shows up in the console

### Expected Behaviour
Error shouldn't be there

### Steps to reproduce

1. Open the Album view
2. Go to Album list view by toggling in top-right
3. Check console

### Platform information

 - Navidrome version: latest master version
 - Browser and version: both Firefox and chrome latest version
 - Operating System: Ubuntu 20.04

### Additional information

 - Screenshots 
![image](https://user-images.githubusercontent.com/53407417/112768162-3a8fc100-9038-11eb-88c0-998660ba5d42.png)

 - Logs? 
```
Warning: React does not recognize the `syncWithLocation` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `syncwithlocation` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in table (created by ForwardRef(Table))
    in ForwardRef(Table) (created by WithStyles(ForwardRef(Table)))
    in WithStyles(ForwardRef(Table)) (created by ForwardRef)
    in ForwardRef (at AlbumListView.js:78)
    in AlbumListView (at AlbumList.js:96)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by ForwardRef(Card))
    in ForwardRef(Card) (created by WithStyles(ForwardRef(Card)))

```

**Comment by deluan** [comment]
Yeah, this seems to be a left over from #891. Simply deleting this property should do the trick.

**Comment by aldrinjenson** [comment]
@deluan , I'm afraid just deleting the property won't solve the issue(in fact the error still persists in the latest master).
