### ISSUE TITLE
Enhancing the login-form

### ISSUE THREAD

**Issue by KaramveerSidhu** [navidrome/navidrome#927]
### Description

Enhancing and adding styles to the navidrome login-form to make it more visually appealing.

### Platform information

 - Navidrome version:  v0.41.0
 - Browser and version: Chrome v88.0.4324.150 
 - Operating System: Debian GNU/Linux 9.13 (stretch)

![Screenshot from 2021-03-29 12-04-26](https://user-images.githubusercontent.com/51775341/112796103-1c9d7d00-9087-11eb-916e-220f0f06d4df.png)

**Comment by KaramveerSidhu** [comment]
@deluan  I'll be working on this now.

**Comment by samarsault** [comment]
I think such changes are better suited to be part of a theme, instead of the component code. 
Right now, I see that the LightTheme is being enforced in the login page. Shouldn't it be using the currentTheme?

**Comment by certuna** [comment]
Problem is, the theme is stored per user (right?), so before the login there is nothing yet.

**Comment by samarsault** [comment]
> Problem is, the theme is stored per user (right?), so before the login there is nothing yet.

No, I meant it is hard coded (see below)
https://github.com/navidrome/navidrome/blob/404253a88104c729069ce0ddd66502ecc871cd9e/ui/src/layout/Login.js#L13-L18

**Comment by deluan** [comment]
To make the Login use the previously selected theme, we need to Wrap it with a ThemeProvider like [here](https://github.com/marmelab/react-admin/blob/27e446b9cf53340b3fb83f069094db4b3b0a2582/examples/demo/src/layout/Login.tsx#L199): 
```js
const LoginWithTheme = (props: any) => (
    <ThemeProvider theme={createMuiTheme(lightTheme)}>
        <Login {...props} />
    </ThemeProvider>
);
```
But instead of hardcoding the `lightTheme`, we can use our own `useCurrentTheme` hook to get the user preference (or darkTheme as default)

**Comment by samarsault** [comment]
@deluan Yeah, should we go that way then?

**Comment by KaramveerSidhu** [comment]
@samarsault As you have already observed, since the app is under development yet, the LightTheme is hard coded. However as pointed by @deluan we can use the useCurrentTheme to get the user preference. Currently I am working on improving the visual appeal of the LightTheme. We also need to ask the user the preferred theme and update the DOM accordingly. That is a topic of a seperate issue. If you would like to work on that, you may go ahead and open a issue for the same if you wish. Thanks for following up and observing things closely.
