### ISSUE TITLE
Background images from Unsplash are not music-related anymore

### ISSUE THREAD

**Issue by certuna** [navidrome/navidrome#928]
For some reason, the random "music"-tagged pictures that Navidrome loads from Unsplash in the login screen seem to have dropped the "music" theme, and I've been seeing mostly non-music related images (some examples: girl eating ice cream, woman behind laptop, abstract wallpaper). At this point it's probably better to bundle or link to a small carousel of appropriate images than to rely on a somewhat erratic 3rd party API.

**Comment by K-Kumar-01** [comment]
@certuna 
I would like to work on this issue. Please assign this to me

**Comment by Dnouv** [comment]
@K-Kumar-01, there is no need to get assigned to work, you can go ahead and work on the issue without being assigned.

**Comment by certuna** [comment]
I think we probably need some consensus on what we actually want from this:
- bundle a couple of stock images with the ND binary?
- host them on navidrome.org and link to them?
- allow the user to load custom images?

**Comment by samarsault** [comment]
I think the quickest fix would be the change the search term in here -
https://github.com/navidrome/navidrome/blob/404253a88104c729069ce0ddd66502ecc871cd9e/ui/src/config.js#L4-L9

I've seen relevant images with search terms `musician` and `concert`.
Maybe it can be changed to that

**Comment by rochakjain361** [comment]
But again, this issue can occur after the update in the URL in config.js. Unsplash is a free public domain image website that can still have wrongly tagged `musician` or other `music` related queries in the future.

**Comment by jvoisin** [comment]
@samarsault 's is the best solution I think.

**Comment by samarsault** [comment]
On further inspection however, I found that we still are getting many unrelated pictures.
The best solution, which I found is to use an unsplash collection instead (See https://github.com/navidrome/navidrome/pull/936)

**Comment by K-Kumar-01** [comment]
@samarsault 
I was actually working on this as I mentioned above. It would be better if you can wait some time before making a PR :sweat_smile: 
It would not result to duplication of work

**Comment by samarsault** [comment]
Apologies @K-Kumar-01, I didn't realise that. Will keep that in mind.

**Comment by certuna** [comment]
The issue is more that we're relying on a 3rd party API, do we want to continue doing this or choose something more predictable/controllable?

**Comment by samarsault** [comment]
> The issue is more that we're relying on a 3rd party API, do we want to continue doing this or choose something more predictable/controllable?

I feel collections are very much controllable. For instance, right now we are using a collection someone else created but we can very much create our own collection and use that instead.

**Comment by K-Kumar-01** [comment]
@certuna 
I was wondering if we can save around 20 files in .webp format and then load them randomly.
In this way, we are ensuring that we are not depending on a third-party library. Also we would have 20 different images>
Though it will increase the bundle size. ;_;

**Comment by certuna** [comment]
Exactly:
- link to an unsplash collection: we have to maintain that
- link to a collection of images on navidrome.org : extra traffic for @deluan 
- include images with the binary: bigger bundle
- generate mosaic images from library cover art: cool, but who wants to/can code this in Go?
- allow users to specify a folder containing images: as above :)

**Comment by K-Kumar-01** [comment]
@certuna 
So should I go with my approach of currently saving 20 images and choosing a random among them?

**Comment by jvoisin** [comment]
Bundling a bunch of picture looks overkill to me: just use a plain color instead if you don't like unsplash.

**Comment by SteveDinn** [comment]
Is there any way to currently disable this feature and just go with a plain background?

**Comment by jvoisin** [comment]
If I remember correctly, yes

**Comment by deluan** [comment]
Will take a look at this thread later and answer any pending questions. For now, just answering @SteveDinn's question:

> Is there any way to currently disable this feature and just go with a plain background?

Yes, there is: https://www.reddit.com/r/navidrome/comments/kxfa52/option_to_set_static_color_for_login_page_that/

**Comment by Balaguru4580** [comment]
I looked into the Unsplash Source and it seems like I'm getting better results by just removing the '/random/' part of the URL. Do let me know if this change is alright.

That being said though, it is still around 10% erratic, like pictures of people operating cameras and whatnot, but for the most part it seems like it's working better.

**Comment by deluan** [comment]
I think there are a few solutions that can all be implemented, and they are non-conflicting (no wasted effort) if they are implemented in this order:

1) Merge @samarsault's PR, that points to a specific collection of images in Unsplash. This is ok but the suggested collection is too small, I think.
2) Create our own collection, maintained by the project
3) Implement a new endpoint in ND, that serves a random image from a folder specified by the user. When this folder is specified, it enables the endpoint and overrides the `UILoginBackgroundURL` config option to reference the endpoint
4) We could also implement the album cover mosaic suggested by @certuna, as an extra option. 

Thoughts?

**Comment by deluan** [comment]
I don't want to bundle any images.... I rather point to a collection in Unsplash (managed by the project, i.e: US) and the user can set the images they want

**Comment by Balaguru4580** [comment]
I see. So, how about having a line in the TOML file that allows them to point to a folder with user set images? I'm thinking that approach might make it easier for a user to just link the picture library they want to use.

**Comment by deluan** [comment]
This was fixed in a previous version, by creating a dedicated [Unsplash collection](https://unsplash.com/collections/20072696/navidrome)
