### ISSUE TITLE
Admin should be able to delete selected songs/albums using the UI.

### ISSUE THREAD

**Issue by rohitgeddam** [navidrome/navidrome#938]
### Is your feature request related to a problem? Please describe.

I added a song that I don't like and now I want to remove it from the list,
Admin should have an option to delete selected songs/albums.

### Describe the solution you'd like
![delete_song](https://user-images.githubusercontent.com/48797475/112854164-32cd2c80-90cb-11eb-9922-153ffbd6a824.png)

we can have a delete button to delete selected songs.

### Describe alternative solutions that would also satisfy this problem

Removing songs from the music folder should remove them from the UI.

### Additional context

related - #937

**Comment by jvoisin** [comment]
Absolutely not.
Navidrome isn't a music management system, it's a music player, who shouldn't be editing my music in any way.

If you want to manage your music, there are better ways, like [Musicbrainz' Picard]( https://picard.musicbrainz.org/ ) for example

**Comment by certuna** [comment]
Probably never going to happen, Navidrome is designed to be 'read only' on your media files, so no deleting or modifying tags. [First item in the FAQ](https://www.navidrome.org/docs/faq/).

**Comment by rohitgeddam** [comment]
Oh Ok
