### ISSUE TITLE
Album's Song List Rearrangement

### ISSUE THREAD

**Issue by TheFlatworm** [navidrome/navidrome#943]
When an album is selected and the songs are displayed the title bar above the song list looks to be part of the list itself:

<img width="1405" alt="Screen Shot 2021-03-29 at 1 52 47 PM" src="https://user-images.githubusercontent.com/5423879/112901068-2334f000-9099-11eb-8049-773baa9e7377.png">

Could this be redesigned to separate the header more clearly - something  like this:

<img width="1411" alt="Screen Shot 2021-03-29 at 2 10 50 PM" src="https://user-images.githubusercontent.com/5423879/112901168-4069be80-9099-11eb-826f-f4041a59f066.png">

**Comment by TheFlatworm** [comment]
This would probably apply to other pages that has a list view as well.

**Comment by certuna** [comment]
I agree this header line should be separated better (bold it? all-caps? different bg colour?). The [react-admin demo site](https://marmelab.com/react-admin-demo/#/customers) bolds the headers, for example.

I don't think moving the Play-Shuffle-Play Next bar up into the album metadata area is a good idea, that's already where (long) comments go, and we also probably need that space in the future for more album-level metadata like label/cat#/review/credits/etc.

**Comment by certuna** [comment]
And here's Plex: no headers either. They have a design where a lot of elements (checkbox, the `...` icon) in front only appear on mouse-over.
![Screen Shot 2021-03-30 at 12 16 35](https://user-images.githubusercontent.com/62144283/112973647-dfea8800-9151-11eb-802b-f188aaad8088.png)

**Comment by certuna** [comment]
And here's Spotify, which does have a headers list (all-caps, with a line divider):
![Screen Shot 2021-03-30 at 12 24 13](https://user-images.githubusercontent.com/62144283/112974707-0bba3d80-9153-11eb-9bb7-0a59a1b46987.png)

**Comment by TheFlatworm** [comment]
Airsonic as well, has no header

<img width="2076" alt="Screen Shot 2021-03-30 at 2 38 49 PM" src="https://user-images.githubusercontent.com/5423879/113060684-d79c4800-9165-11eb-9fe1-56e27089250e.png">

**Comment by Balaguru4580** [comment]
Alright. Working on this right now. I'm thinking Bold would be good for differentiating it along with some additional spacing. Any thoughts on design is welcome!

**Comment by Balaguru4580** [comment]
Right now I've made a pretty simple design of just making it bold and spacing out the header. I think it matches the UI scheme pretty well, but I'm open to altering it.

**Comment by deluan** [comment]
Hey @TheFlatworm , let me know if the changes by @Balaguru4580 are what you were looking for. They are subtle but may be enough of a differentiation

**Comment by TheFlatworm** [comment]
Hi!  I believe that would do - it's easier on the eyes.  Thanks!
