### ISSUE TITLE
Show discSubtitle also for 1-disc albums

### ISSUE THREAD

**Issue by certuna** [navidrome/navidrome#947]
At the moment, Navidrome only shows the disc subtitle when there's 2 or more discs. This means it won't show the disc subtitle for a 1-disc album.

In [SongDatagrid.js](https://github.com/navidrome/navidrome/blob/ac37bf3631610747001f44fe843517f3fdf0ac08/ui/src/common/SongDatagrid.js) this is caused by the line 156-158:
```
    if (!showDiscSubtitles || set.size < 2) {
      set.clear()
    }
```
If I remove these lines, 1-disc albums with subtitles show correctly:

![Screen Shot 2021-03-30 at 15 42 43](https://user-images.githubusercontent.com/62144283/112998741-9f4d3780-916e-11eb-98be-0ce33b39c4a4.png)

However this also makes 0-disc or 1-disc albums without subtitles show the DiscSubtitleRow, which we don't want either:

![Screen Shot 2021-03-30 at 15 45 14](https://user-images.githubusercontent.com/62144283/113008541-68c7ea80-9177-11eb-8e35-da9198d6cfe7.png)

So I guess this needs to change to something like this, where the row is only cleared when the discSubtitle is empty:
```
    if (!showDiscSubtitles || (set.size < 2 && discSubtitle.length === 0)) {
      set.clear()
    }
```
Except `discSubtitle` is not defined and my JS skills are not good enough to do this properly...

**Comment by metalheim** [comment]
Good Input! Sorry, I misunderstood you in Discord.

> However this also makes 0-disc or 1-disc albums without subtitles show the DiscSubtitleRow, which we don't want either

Yes and no. It's convenient that Navidrome hides it currently, but the reason to need a "fix" is in our own messy tagging. If it can be fixed in tags, it should be IMHO

**Comment by deluan** [comment]
Thanks for the report. In my collection there is not a single occurrence of a single disc album with discSubtitle.... I'll take a look at that.

**Comment by certuna** [comment]
> Yes and no. It's convenient that Navidrome hides it currently, but this can be fixed by just deleting the DISCNUMBER / TPOS tag, right?

That's what a "0-disc album" is, it's an album without a discnumber. Currently Navidrome hides the disc subtitle row for albums with no disc number, or "1" or "1/1".

> In my collection there is not a single occurrence of a single disc album with discSubtitle

Disc Subtitle (`TSST`, etc) is quite practical to tag subtitles, like "30th Anniversary Edition" or "2015 Remaster" etc. You could of course always append that in the regular album title like "Thriller (25th Anniversary Edition)" but that makes the album title unnecessarily long, plus I noticed this extra text sometimes makes it harder for some players (Emby, Plex) to successfully match the album name to the original album in last.fm/musicbrainz/allmusic/etc and pull in reviews/credits/etc from there.

**Comment by metalheim** [comment]
@certuna The more I use Navidrome, I start to agree with you. Storing Information in the Disc Title can be useful, even for 1-disc albums. (For the reasons you mentioned, "Japanese Release" or "2015 Remaster" etc.)

And since it can be read already, it would be easy for navidrome to show it (only when there is a `TSST` in place)

**Comment by deluan** [comment]
Is it ok to remove the disc number when it is `0`?
<img width="958" alt="Screen Shot 2021-06-25 at 11 12 25 AM" src="https://user-images.githubusercontent.com/331353/123445883-54449400-d5a6-11eb-9356-3cbf1b21ad55.png">

**Comment by deluan** [comment]
Better?

<img width="628" alt="Screen Shot 2021-06-25 at 11 23 09 AM" src="https://user-images.githubusercontent.com/331353/123447351-bfdb3100-d5a7-11eb-9d73-99ce4aef8e68.png">

**Comment by SteveDinn** [comment]
Does the subtitle also show up in the grid or list view?

**Comment by certuna** [comment]
Pretty hard to do, since it's song metadata, not album metadata (an album can have multiple discs with multiple subtitles)
