### ISSUE TITLE
Context menu for Playlists.

### ISSUE THREAD

**Issue by YashJipkate** [navidrome/navidrome#958]
### Is your feature request related to a problem? Please describe.

If I want to download or add some playlist(s) to my queue, I need to individually go to each playlist and add it from the Actions toolbar. A context menu like the one in tracks/albums/artists that pops up would be handy.

### Describe the solution you'd like

A three dots button should be placed beside the 'Edit' button that would open up the context menu.

### Additional context

This is how the context menu appears in the albums:
![Screenshot from 2021-04-01 12-08-06](https://user-images.githubusercontent.com/34203227/113253597-10156080-92e3-11eb-8c04-117a530fbb8f.png)

A solution like this for Playlists would be desirable.

**Comment by deluan** [comment]
Yes, that could be a good enhancement. Let's wait for the #941 to be merged, to avoid merge conflicts
