### ISSUE TITLE
Don't expose songs paths for regular users

### ISSUE THREAD

**Issue by deluan** [navidrome/navidrome#959]
### Is your feature request related to a problem? Please describe.
For security reasons, paths should not be exposed to users that are not administrators. 
<img width="1436" alt="Screen Shot 2021-04-01 at 10 41 01 PM" src="https://user-images.githubusercontent.com/331353/113374614-7332e180-933b-11eb-8854-5edb20bf04b1.png">

### Describe the solution you'd like
**UI**: Only shows the song `path` in the `SongDetails.js` if the user is admin
**Backend**: The REST route for `/app/api/song/` (in `server/app/app.go`) should not expose the path when the user is not an administrator. Not sure how to achieve this in a simple way. Maybe a custom JSON marshaler?
**Subsonic API**: No changes to the Subsonic API are required. It needs to expose the Path for compatibility reasons (oh, well)

### Describe alternative solutions that would also satisfy this problem
We should at least remove the path from the UI

**Comment by Balaguru4580** [comment]
Alright. I'll take a crack at this!

**Comment by certuna** [comment]
isn’t this better solved in the database, as part of the support for multiple music folders?

so store for each record in the media_file table:
- a base folder index # (referencing a table containing the multiple folders)
- a relative path

then it’s fairly trivial to expose in the API the base folder + relative path for an Admin, and the relative path for a non-Admin

**Comment by deluan** [comment]
@certuna Your suggestion os definitely the long term solution, but I opened this as a quick and simple, `good-first-issue` for the GSoC students to get their hands dirty in the codebase.

Can you please add your proposed solution to the #192 story, so we don't lose track of it?

**Comment by rochakjain361** [comment]
I'd also love to work on this issue

**Comment by AeronCyther** [comment]
Is this issue up for taking?

**Comment by deluan** [comment]
@AeronCyther: The UI part is basically done by @rochakjain361 in PR #968 , but you can try to fix the backend, to not send the path in the response when the user is not admin

**Comment by AeronCyther** [comment]
Alright, I'll get to that then

**Comment by AeronCyther** [comment]
I went through everything and experimented with a few things. As far as I can see, there are two ways to go about this.
1. Making a new MediaFile type (say AdminMediaFile) where Path doesn't have a JSON field. This also requires making a corresponding "AdminMediaFileRepository) that works with our  new type. Code repetition can be minimised using embedded structs, but it's still pretty messy,
2. Second approach also involves making a new MediaFile type in the same way as the approach illustrated above. The key difference is that instead of making a new repository, we'll need to create alternate R, RX equivalent functions in app.go and local alternatives for Get, GetAll functions that we are currently using(deluan/rest).

I'm leaning more towards the second approach because it would involve less code repetition, and can potentially be reused for other such features that we may need in the future(choosing not to display certain information to non-admins). Should I proceed with that?

**Comment by AeronCyther** [comment]
2nd approach does lead to some code duplication when compared to deluan/rest which can be avoided by introducing a few functions in that repo. @deluan is that possible?

**Comment by Balaguru4580** [comment]
I worked on this for quite some time and I came to the same conclusions you did. However, I wasn't able to get the alternate R and RX functions to work since I wasn't able to figure out how to modify the GetAll function that accessed the data.

But yeah, messing with the MediaFile struct seems to break too many things since it's been referenced well over 100 times in the code base.  So, I'm also leaning towards the second approach here.

**Comment by AeronCyther** [comment]
Without being able to directly modify deluan/rest, the best we can do is duplicate the needed code and make *minor* modifications. There are too little changes to justify repeating so much code. That is why I want to avoid this scenario if possible. However, if there is no choice then we can't really do anything about it.

**Comment by AeronCyther** [comment]
I made a draft with working path obfuscation based on the user being an admin.
#1000

**Comment by deluan** [comment]
@AeronCyther I did a quick look at your PR, there's a lot of improvements that can be made, and I'm glad to go over it with you in Discord. I actually did a simple implementation myself and I can share and explain it with you, so it can be helpful for your learning process.

The thing is that I'm not sure if I want to change it, as it would introduce code that adds complexity to the server side API, and this will be removed once we introduce multiple music folder, as per @certuna's comment.

So I think for now we can just hide it from the UI, but not touch the server. In terms of security, I'm not sure the real value of this, as the Subsonic API exposes the paths anyway (as per its specification), so a ill-motivated user could get the path easily using any Subsonic API endpoint that returns songs. @jvoisin , any comments in this regards?

**Comment by AeronCyther** [comment]
I'd be more than happy to learn how I can improve my code. I guess this can be put on hold till multiple folder support is added. But isn't path optional in Subsonic API?

**Comment by jvoisin** [comment]
Having path only hidden client-side is useless in my opinion.

**Comment by certuna** [comment]
The more I think about it, I think that the best action is not expose the file path (in the API) to regular users at all, just to admins.

**Comment by AeronCyther** [comment]
> The more I think about it, I feel that the best action is indeed not to expose the file path (in the API) to regular users at all, not even relative. Agree that this shouldn't be client-side.

That's exactly what I thought. Paths shouldn't be exposed for any reason

**Comment by Balaguru4580** [comment]
This might become relevant when multiple folders are supported though.

I can see the utility of already being able to find which folder a song is from. With multiple folders this utility just increases.

**Comment by AeronCyther** [comment]
> This might become relevant when multiple folders are supported though.
> 
> I can see the utility of already being able to find which folder a song is from. With multiple folders this utility just increases.

That might be true for admins, but non admins have no need to know where the files are located. For example, you do not know where the files are stored in spotify. You don't need to. Users are supposed to listen to music. When technical difficulties arise, the administrators _might_ need to know where files are located. Other than that, giving more information than needed is a good way to introduce potential security vulnerabilities.

**Comment by deluan** [comment]
My opinion is: As long as we support the Subsonic API, there's no point in hiding the paths in other parts of Navidrome, from a pure security perspective.

**Comment by AeronCyther** [comment]
If we absolutely have to return paths, how about mapping real file paths to virtual file paths? Not relative, virtual. All media files may be album_name/media_name or something along those lines?

Should be more _secure_ than relative paths

**Comment by deluan** [comment]
> If we absolutely have to return paths, how about mapping real file paths to virtual file paths? Not relative, virtual. All media files may be album_name/media_name or something along those lines?

This is actually the default behaviour in Navidrome, but there's an option to enable real paths, as it breaks some clients:
<img width="456" alt="Screen Shot 2021-04-16 at 10 17 51 AM" src="https://user-images.githubusercontent.com/331353/115037992-14be4500-9e9d-11eb-91bb-d1fac4afd25b.png">

**Comment by AeronCyther** [comment]
> If we absolutely have to return paths, how about mapping real file paths to virtual file paths? Not relative, virtual. All media files may be album_name/media_name or something along those lines?
> 
> Should be more _secure_ than relative paths

There's actually an issue with this approach. It probably doesn't work with _unofficial_ copies of songs grouped together by being stored in a folder. This will probably end up showing everything under unknown album, right?

**Comment by deluan** [comment]
Yes it will... Usually people that don't care about tags use "Browse by folder", a feature Navidrome does not implement

**Comment by vian9** [comment]
Is this issue resolved?
