### ISSUE TITLE
Play icon became dark on "light" theme.

### ISSUE THREAD

**Issue by deluan** [navidrome/navidrome#960]
### Description

The play icon that appears on top of album covers needs to always be forced to be white, and not "inherit" (default). This is the expected appearence:

Correct, from the demo server (version 0.41.0):
<img width="247" alt="Screen Shot 2021-04-01 at 11 46 22 PM" src="https://user-images.githubusercontent.com/331353/113378223-7d0d1280-9344-11eb-9aac-83f35f684f87.png">

Wrong, from master:
<img width="251" alt="Screen Shot 2021-04-01 at 11 47 01 PM" src="https://user-images.githubusercontent.com/331353/113378285-9ada7780-9344-11eb-81a8-d3645a206f94.png">

### Expected Behaviour

The play button must always be white when displayed over an album cover.

### Steps to reproduce

1. Select "Light" theme. 
2. Go to an Album List
3. Hover the mouse over an album

### Platform information

 - Navidrome version: latest from master
 - Browser and version: all browsers
 - Operating System: all OSes

### Additional information

The play button has to be "white" **ONLY** on album covers, in other places where it appears in the UI it is correct.

**Comment by shishir610** [comment]
Hey! I'd love to work on this issue.

**Comment by deluan** [comment]
@shishir610 Go ahead!

**Comment by shishir610** [comment]
@deluan Tested on Chrome and Firefox and it's fixed, issue was that `className` property for the `<IconButton />` was being overridden. 

Chrome/Firefox working:
![image](https://user-images.githubusercontent.com/27198773/113386407-d0647c80-93a7-11eb-9a28-3f4b18423add.png)

**Comment by deluan** [comment]
Just make sure it still works in other themes, looks like your change breaks the green PlayButton in "Spotify-ish"

**Comment by shishir610** [comment]
Fixed it for all themes as and when necessary. 

Dark: 
![image](https://user-images.githubusercontent.com/27198773/113498502-0b42ed80-952b-11eb-96a8-c0262bb1a23c.png)

Light: 
![image](https://user-images.githubusercontent.com/27198773/113498513-26156200-952b-11eb-9ee5-e37d7d60edc6.png)

Spotify-ish:
![image](https://user-images.githubusercontent.com/27198773/113498520-3f1e1300-952b-11eb-8c3a-8f85f3110657.png)

**Comment by deluan** [comment]
Thanks, but without a PR I can't validate it...  ;)

**Comment by shishir610** [comment]
@deluan Kindly do look into the PR and suggest changes (if any)
