### ISSUE TITLE
Material UI Minimising the development bundle size

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [navidrome/navidrome#967]
## Description

Reduces bundle size of UI folder during development. 

Currently, at many places, we import components using the following method
``` jsx
import { makeStyles, MenuItem, ListItemIcon, Divider } from '@material-ui/core'
//ui/layout/Appbar.js
```

which is considerably slower than doing the following 

``` jsx
import { makeStyles } from '@material-ui/core/styles'
import MenuItem from '@material-ui/core/MenuItem'
import ListIemIcon from '@material-ui/core/ListItemIcon'
import Divider from '@material-ui/core/Divider'
```

Read: https://material-ui.com/guides/minimizing-bundle-size/

> Development bundles can contain the full library which can lead to slower startup times. This is especially noticeable if you import from @material-ui/icons. Startup times can be approximately 6x slower than without named imports from the top-level API. - MUIDocs

### Describe the solution you'd like
 Use the Babel plugin (this needs to be added to the creat-react-app webpack configuration, which means ejecting the react-app. If we don't want to eject the create-react-app we need to use a project like [create-react-app-rewired](https://www.npmjs.com/package/react-app-rewired) or [nextjs](https://www.npmjs.com/package/next) which natively supports editing the webpack configuration without ejecting the react-app.

Arguments against ejecting react app : - [Read here](https://medium.com/curated-by-versett/dont-eject-your-create-react-app-b123c5247741)
> This option provides the best User Experience and Developer Experience:
>
>UX: The Babel plugin enables top-level tree-shaking even if your bundler doesn't support it.
>DX: The Babel plugin makes startup time in dev mode as fast as Option 1.
>DX: This syntax reduces the duplication of code, requiring only a single import for multiple modules. Overall, the code is easier to read, and you are less likely to make a mistake when importing a new module. - MUIDocs

### Describe alternative solutions that would also satisfy this problem
Manually change the imports in every file of the UI folder (seems like a painfully undertaking D:)

### Additional context

**It does not affect the production-build because create-react-app automatically does tree-shaking when building an optimized build, but it does not during a development which could slow down build times.**

**Comment by SobhanBera** [comment]
This seems interesting to achieve.

**Comment by deluan** [comment]
IMHO, this is not really necessary, as it affects only the development bundle size. Even though the startup is currently slow, after the dev server is up and running any changes are instantaneously picked-up. Sure, we would have faster startups, but you shouldn't have to start the dev server more than a couple of times a during a code session. Usually once is enough.

The "solutions" are also not that great:
- Ejecting the app would be a worse DX, as the codebase would become more bloated and it would be more code to maintain. 
- Moving to Next.js is a huge undertaking. Not sure if it is worth the trouble.
- create-react-app-rewired is not as actively maintained as the official one.
