### ISSUE TITLE
Play icon inside an album or playlist does not switch to "pause" while playing

### ISSUE THREAD

**Issue by shishir610** [navidrome/navidrome#973]
### Description

The play icon that appears inside an album to play all the songs in the album needs to change state to "pause" while playing and not remain on "play"

Correct (example from Spotify):
While paused:
![image](https://user-images.githubusercontent.com/27198773/113499371-30d3f500-9533-11eb-8d73-012792f25b11.png) 

While playing:
![image](https://user-images.githubusercontent.com/27198773/113499382-3df0e400-9533-11eb-80f3-cdd33744f23b.png)

Wrong (from navidrome/master):
While paused: 
![image](https://user-images.githubusercontent.com/27198773/113499427-90320500-9533-11eb-855b-3b6a651886d7.png)

While playing:
![image](https://user-images.githubusercontent.com/27198773/113499433-932cf580-9533-11eb-8274-ab547ffe36a5.png)

### Expected Behaviour

State of button must be "play" while paused and "pause" while playing. 

### Steps to reproduce

1. Go to album list. 
2. Select a particular album. 
3. Click on Play

### Platform information

 - Navidrome version: latest from master
 - Browser and version: all browsers
 - Operating System: all OSes

### Additional information

BONUS FIX: The play icon upon hover of an album must also follow suit and change state accordingly. (Refer screenshot)
![image](https://user-images.githubusercontent.com/27198773/113499480-e1da8f80-9533-11eb-9c49-8dcbd9c3b362.png)

**Comment by samarsault** [comment]
That seems to be the case with both playlist and albums, and across themes.
Though you can use the keyboard shortcuts and the player below, a pause button is nice-to-have

**Comment by shishir610** [comment]
Yep, that's right. It is an enhancement to the already existing feature.

**Comment by ghana7989** [comment]
can I take up this issue?

**Comment by shishir610** [comment]
I'm also contributing to Navidrome and I opened this issue so that I could open a PR on it. I'm already working on it, sorry.

**Comment by deluan** [comment]
The `PlayButton` can query the redux store (using `useSelector`) to know if the current album is the one being played. Similar to what we do in the song title (California Love in the screenshot below: https://github.com/navidrome/navidrome/blob/9d2426a601cc7464086994401d8bda8133b9ec84/ui/src/common/SongTitleField.js#L31
<img width="358" alt="Screen Shot 2021-04-05 at 8 04 58 PM" src="https://user-images.githubusercontent.com/331353/113640780-3a9c4c00-964a-11eb-8ed1-ca77634e6fb3.png">

But this needs to be a bit smarter, it need to know if we are playing a playlist or an album. We may need to add to the store what triggered the play (album or playlist) as we currently don't have this information in the store.

**Comment by deluan** [comment]
Maybe `latest` is a too generic name, but yes, that would the gist of it.

**Comment by shishir610** [comment]
Does `recentAlbumOrPlaylist` work?

**Comment by deluan** [comment]
Yeah, better. You have to reset it when the play action comes from artist or album.... Maybe it is better to combine this functionality with the current play* actions, maybe not... Didn't think about it throughly

**Comment by shishir610** [comment]
From my thought process, the play icon is visible ONLY when a user clicks on an album or a playlist. That's the only time we need to change state. For any other interaction (say, with the Artists or Songs) is irrelevant. We check whether the current track is playing and if it is, then we check whether `recentAlbumOrPlaylist` is same as current album. Anything else falls outside this functionality right?

**Comment by deluan** [comment]
What if you play an album, then play an artist and go back to that album view? It would still show as "Playing".... That's why I said it should reset for song and artist.

**Comment by shishir610** [comment]
Ah got it. So, a third action RESET to be dispatched when user interacts with any of the left side panel buttons? Any other events that need to dispatch this RESET action?

**Comment by deluan** [comment]
Not that I know, but maybe it is good to add it to the `onBeforeDestroy()` of the player as well

**Comment by shishir610** [comment]
How do I check whether the `currentTrack` is the one that belongs to the selected `recentAlbumOrPlaylist`? 
Specifically, if we are in an album with albumId `x`, how do I check if the current track also has albumId of `x`? 
Same applied to if we are in a playlist as well.

As of now, `currentTrack` has trackId, uuid and paused properties. How do we include a `albumOrPlaylistId` property?

**Comment by shishir610** [comment]
Nevermind the previous question. I figured it out. Only issue I'm facing right now is pausing tracks anywhere in the app. I tried creating another action `pauseTracks` which just sets `queue.current.paused: true`. But that doesn't seem to be working. In Redux Dev Tools > Diff tab, that is the only change (`queue.current.paused: false -> true`) that happens, but I guess it has something to do with `ReactJkMusicPlayer`. Please leave a comment if anyone knows anything about this. Thanks!

**Comment by shishir610** [comment]
Everything seems to be working except the play button click in "pause" state (aka pause button click). Please do tell me what I need to do. The issue is same as previous comment (referenced below 👇)

> Nevermind the previous question. I figured it out. Only issue I'm facing right now is pausing tracks anywhere in the app. I tried creating another action `pauseTracks` which just sets `queue.current.paused: true`. But that doesn't seem to be working. In Redux Dev Tools > Diff tab, that is the only change (`queue.current.paused: false -> true`) that happens, but I guess it has something to do with `ReactJkMusicPlayer`. Please leave a comment if anyone knows anything about this. Thanks!

**Comment by deluan** [comment]
@shishir You should dispatch an action to pause, save it in Redux store, and in the `Player.js` read it and control the `ReactJkMusicPlayer`. @aniketbiswas21  did a good work on this in his PR #819,  you may take a look at some ideas from there.

**Comment by shishir610** [comment]
Thanks @deluan @aniketbiswas21, I understood
