### ISSUE TITLE
Docker contrainer suck on "Loading". No admin user found!

### ISSUE THREAD

**Issue by TaakoMagnusen** [navidrome/navidrome#974]
These are my docker  settings [1](https://i.imgur.com/kdxwFuG.png) [2](https://i.imgur.com/6ycYcEd.png)

The page is stuck on "Loading. The page is loading, just a moment please."

Got this error:

    
    | \ | | (_) | |
    | \| | __ ___ ___ __| |_ __ ___ _ __ ___ ___
    | . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
    | |\ | (_| |\ V /| | (_| | | | (_) | | | | | | __/
    \_| \_/\__,_| \_/ |_|\__,_|_| \___/|_| |_| |_|\___|
    Version: 0.41.0 (ba922bbf)
    
    
    2021/04/04 04:01:38 goose: no migrations to run. current version: 20210322132848
    
    time="2021-04-04T04:01:38Z" level=info msg="Starting scanner" interval=1m0s
    time="2021-04-04T04:01:38Z" level=info msg="Configuring Media Folder" name="Music Library" path=/music
    time="2021-04-04T04:01:38Z" level=info msg="Creating Image cache" maxSize="200 MB" path=/data/cache/images
    time="2021-04-04T04:01:38Z" level=info msg="Finished initializing cache" cache=Image elapsedTime="239.018µs" maxSize=200MB
    time="2021-04-04T04:01:38Z" level=info msg="Found ffmpeg" path=/usr/bin/ffmpeg
    time="2021-04-04T04:01:38Z" level=info msg="Last.FM integration not available: missing ApiKey/Secret"
    time="2021-04-04T04:01:38Z" level=info msg="Spotify integration is not enabled: artist images will not be available"
    time="2021-04-04T04:01:38Z" level=info msg="Creating Transcoding cache" maxSize="100 MB" path=/data/cache/transcoding
    time="2021-04-04T04:01:38Z" level=info msg="Finished initializing cache" cache=Transcoding elapsedTime="176.034µs" maxSize=100MB
    time="2021-04-04T04:01:38Z" level=info msg="Mounting routes" path=/rest
    time="2021-04-04T04:01:38Z" level=info msg="Mounting routes" path=/app
    time="2021-04-04T04:01:38Z" level=info msg="Login rate limit set" requestLimit=5 windowLength=20s
    time="2021-04-04T04:01:38Z" level=info msg="Navidrome server is accepting requests" address="0.0.0.0:4533"
    time="2021-04-04T04:01:40Z" level=warning msg="No admin user found!" error="data not found"
    
    time="2021-04-04T04:02:40Z" level=warning msg="No admin user found!" error="data not found"
    
    time="2021-04-04T04:03:40Z" level=warning msg="No admin user found!" error="data not found"
    
    time="2021-04-04T04:03:40Z" level=warning msg="No admin user found!" error="data not found"

**Comment by ShubhamSwati** [comment]
hey, can you please elaborate on the issue, I am new to open source projects, I want to work on this issue..

**Comment by jvoisin** [comment]
It looks like you forgot to create a user.

**Comment by deluan** [comment]
@TaakoMagnusen If this is your issue: https://github.com/navidrome/navidrome/issues/950

It was already fixed in the latest development build and will soon be released. As a workaround you can follow these steps:

> As a quick fix, as suggested by @metalheim, please try manually going to `your-domain:port/app/#/login` where you'll be presented with the login screen

If you are having further issues, you can try the latest dev build  as a fix as well. https://github.com/navidrome/navidrome/issues/906#issuecomment-809809881

**Comment by TaakoMagnusen** [comment]
@deluan that workaround (going to `app/#/login`) was simple and effective! , thanks! Will close the issue and look forward to the next release.

Awesome project btw, really enjoying it!
