### ISSUE TITLE
Multiple libraries... music, audiobooks...

### ISSUE THREAD

**Issue by truthsword** [navidrome/navidrome#977]
Docker user here... I'd like to see libraries so my music isn't intermingled with my audiobooks. In Docker I envision...

/my/audiobook/path > /audiobooks
/my/music/path > /music

...hoping I'd be able to map those separately.

Is that possible? Thank you.

... and a side question re: Docker... is PUID/PGID accepted? Or PID/GID? Or?

**Comment by Balaguru4580** [comment]
This has already been opened as issue #192 . Thanks for sharing your feedback. It's clear that there is definite demand for that idea right now.

**Comment by jvoisin** [comment]
Marking as duplicate from #192, as pointed by @Balaguru4580

**Comment by deluan** [comment]
Answering your side question:
> ... and a side question re: Docker... is PUID/PGID accepted? Or PID/GID? Or?

Check https://github.com/navidrome/navidrome/issues/531, and https://www.navidrome.org/docs/installation/docker/#customization

**Comment by truthsword** [comment]
Thanks. So I can't pass these as environmental variables. I'll sort 
through that.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
I like the idea and it would also be useful for me to separate some types of albums into categories or libraries.
However, I would already be happy to do the whole thing with extended tags instead special separated folders.

Like:
![image](https://user-images.githubusercontent.com/5566460/198872642-aa18183b-b149-419c-8a57-8b5cdda673ac.png)
![image](https://user-images.githubusercontent.com/5566460/198872671-8f1d1c88-8b43-4f97-b4a5-ad637bf3f660.png)

Which then Results in:
![image](https://user-images.githubusercontent.com/5566460/198872938-902bb534-864b-486e-a8f0-c11e8e6a77e3.png)

I also personaly don't care if Artists are also separated or not.
The only thing important is that albums/songs are separated.

In order not to disturb existing libraries, this tag should of course be optional, i.e. files where this is not set all go into the main library as they are currently.
