### ISSUE TITLE
Demo site is not working

### ISSUE THREAD

**Issue by phanindra-max** [navidrome/navidrome#993]
### Description

the demo site : [Demo Site](https://demo.navidrome.org/app/index.html ) is not working
### Expected Behaviour

What you would have expected to happen instead.

### Steps to reproduce

1. Open the demo [site](https://demo.navidrome.org/app/index.html)
2. I see this message
![Screenshot 2021-04-07 190222](https://user-images.githubusercontent.com/51989959/113874870-da391600-97d3-11eb-94d2-80184b06b829.png)

I tried to open the Demo Site to play around the UI and got this, I am not sure on what could be the reason. Maybe this is a minor issue from serverside I wanted to mention.

**Comment by deluan** [comment]
This is a bug in 0.41.0 (the version in the demo site): https://github.com/navidrome/navidrome/issues/906#issuecomment-806715056

Check that issue for a workaround.
