### ISSUE TITLE
Warning when clearing the queue of songs

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [navidrome/navidrome#996]
If I have a list of songs in my queue which if suppose I want to add a new song to the queue and I mistakenly add play instead of play next it clears out my previous queue.
I was wondering if we already have a queue we can show the user the message
'Songs are already queued, do you want to add the song to the queue?'
In form of a dialog and if the user answers with yes the song is added to the queue else a new queue is formed(current behavior) and previous songs are removed from the queue.

https://user-images.githubusercontent.com/54576074/113947884-409c5380-9829-11eb-99c4-fe3c49233966.mp4

**Comment by deluan** [comment]
I understand your suggestion, but not sure if this is really important... Don't remember seeing this in any mainstream player.... 

@certuna / @jvoisin Thoughts?

**Comment by Rishabh-malhotraa** [comment]
> I understand your suggestion, but not sure if this is really important... Don't remember seeing this in any mainstream player.... 
> 
> @certuna / @jvoisin Thoughts?

It's a feature in apple music if I'm not mistaken.

**Comment by deluan** [comment]
> It's a feature in apple music if I'm not mistaken.

Just checked, no confirmation/warnings in Apple Music android and desktop, and Spotify and Deezer web.

**Comment by Rishabh-malhotraa** [comment]
> > It's a feature in apple music if I'm not mistaken.
> 
> Just checked, no confirmation/warnings in Apple Music android and desktop, and Spotify and Deezer web.

I guess they would have changed it, because I remember using this feature when I had iPhone its been a while though 

![apple-music-101-clear-your-up-next-queue-remove-unwanted-upcoming-songs](https://user-images.githubusercontent.com/54576074/113962466-60da0b80-9845-11eb-8309-54527dfbaac7.jpg)

**Comment by jvoisin** [comment]
I don't think it's worth showing a warning for this.
